[Serializer] Give access to the context to support* methods
symfony/symfony pull request #19371
Opened 2016-07-16 16:43 UTC by dunglas

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no (?)
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | yes: interfaces will change in 4.0
| Tests pass?   | yes
| Fixed tickets | comma-separated list of tickets fixed by the PR, if any
| License       | MIT
| Doc PR        | n/a

This is a current use case to want to access the context form the `supports*` methods. This PR fixes this limitation.

Maybe can it be considered a bug fix?

2016-07-16 21:17 UTC, Ener-Getick commented on src/Symfony/Component/Serializer/Normalizer/ArrayDenormalizer.php
> +        $context = 4 === func_num_args() ? func_get_arg(3) : [];
Long array syntax should be used

2016-07-16 21:18 UTC, Ener-Getick commented on src/Symfony/Component/Serializer/Normalizer/CustomNormalizer.php
> +     * @param array  $context Options available to the denormalizer
Shouldn't this be inherited ?

2016-07-16 21:19 UTC, Ener-Getick commented on src/Symfony/Component/Serializer/Normalizer/GetSetMethodNormalizer.php
> +        $context = 3 === func_num_args() ? func_get_arg(2) : [];
Long syntax

2016-07-16 23:07 UTC, ogizanagi commented
I always wondered why it was not already the case and assumed it was by design.
However, IIRC, the Serializer previously used a hash of the `supports*` methods arguments, in order to cache the normalizer/denormalizer instance to use for those arguments.
Now, should we consider the fact someone may have mimic this behavior in it's own serializer, and that the cache would be compromised by not taking care of the `context` (which can also create issue in order to be serialized, but that's another topic) ?

2016-07-17 09:42 UTC, dunglas commented on src/Symfony/Component/Serializer/Normalizer/CustomNormalizer.php
> +     * @param array  $context Options available to the denormalizer
It isn't because the contributor as changed the description IMO.

2016-07-17 09:50 UTC, dunglas commented
@ogizanagi It's not a problem because we don't use the context in support* methods of built-in normalizers. It can be broken only if someone use the context and has its own cache mechanism... But it's his responsibility.

2016-07-17 13:41 UTC, theofidry commented
@dunglas I would be 👎 for this one. It is a limitation for sure, but having the context in the supports makes the lookup for the (de)normalizer much more dynamic, thus extremely hard to cache. Now let's say you have a set of data that you want to denormalize in a `UserInterface` object, and provide a different concrete class depending of the context, you can always have a `UserDenormalizer` supporting `UserInterface`, have a denormalizer for each case, and manually pick the right denormalizer in `UserDenormalizer`. If there's too many custom denormalizers, it might be worth to abstract it a bit to make it more easy, but IMO it's not a very common use case.

2016-07-17 15:00 UTC, Ener-Getick commented
I agree with @dunglas this is not part of the symfony promises imo.

@theofidry if you change the context the serializer output will very likely change too so i don't get what's the problem. Moreover it shouldn't change that much.

2016-07-17 17:22 UTC, theofidry commented
> Moreover the context shouldn't change that much.

The context is very likely to change a lot, it already changes natively to handle proxies or cache keys. In ApiPlatform for example, we also have a lot of keys passing through the context (`type`, `normalization_context`, `denormalization_context`, `resource_class` etc.)

> If you change the context the serializer output will very likely change too so i don't get what's the problem.

Yeah the output may change, but so does the context. It makes much harder to predict the result for a given context and now you have to handle the context, which is dynamic and accessible to all normalizers (hence very likely to change) for caching. The context was initially for giving additional info on *how* to (de)normalize a set of data. Adding it to the `supports*` is making use of it for *which* (de)normalizer can use handle it. It's not innocent, and IMO brings more trouble than it's worth.

2016-07-17 22:43 UTC, Ener-Getick commented
@theofidry if i'm not wrong the things such as proxy classes, cache keys, etc. are generated only when the cache is cleared ? If this is true then the context should remain the same.
I'll investigate more later thanks for your explanation ☺

Anyway imo as the context describes how to (de)serialize an object it must be possible to not execute a normalizer in case it doesn't support some part of the context.

2016-07-18 12:51 UTC, Ener-Getick commented
Maybe adding a new field ``dynamic_fields`` to the context would solve your issue @theofidry ?

2016-07-18 20:31 UTC, Ener-Getick commented on src/Symfony/Component/Serializer/Normalizer/ArrayDenormalizer.php
> +        $context = 4 === func_num_args() ? func_get_arg(3) : array();
should be changed to ``func_num_args() > 3 ? func_get_arg(3) : array()`` for consistency (this is always written like that) and for clarity

2016-07-18 20:37 UTC, theofidry commented
@Ener-Getick could mitigate it, but looks horribly brittle to me. I just feel like this feature is about trying to extend the usage of context for something it is not meant. I'm not the one who gets to decide, but IMO it will only add complexity to something that is already very complex and make it messier.

@dunglas is there any use case in which you want to use this feature?

2016-07-18 20:59 UTC, Ener-Getick commented
@theofidry I just looked the code @ogizanagi mentioned and it is no longer in the code (the normalizer to use is always determined) so there are absolutely no problem.
It's last occurrence is in ``2.6`` which is no longer maintained and is not compatible with symfony 3.

So there won't ever be any issues about caching here (except if someone doesn't use the latest patches but this is not our problem...).

I'm in favor of merging that as a feature (as people were limited but didn't have a weird behaviour).

There are many use cases. For example if you use normalization groups with custom normalizers, you may want to have one normalizer per group.

2016-07-18 21:23 UTC, theofidry commented
@Ener-Getick I fail to see how have a dynamic array that can change from one call to another is not going to have an impact on caching. It may not have one in the Symfony code base right now but it will definitely have some in userland (I am not talking of BC, but of usability).

>There are many use cases. For example if you use normalization groups with custom normalizers, you may want to have one normalizer per group.

To that I would said my argument still stands:

>Now let's say you have a set of data that you want to denormalize in a UserInterface object, and provide a different concrete class depending of the context, you can always have a UserDenormalizer supporting UserInterface, have a denormalizer for each case, and manually pick the right denormalizer in UserDenormalizer. If there's too many custom denormalizers, it might be worth to abstract it a bit to make it more easy, but IMO it's not a very common use case.

So it's not that I don't see the use case (and believe me, I'm the first one *abusing* of it), but I don't believe it belongs to the core.

2016-07-18 21:42 UTC, Ener-Getick commented
@theofidry nothing is cached anymore about which normalizer to use so we can't have a problem about that ^^

2016-07-18 22:18 UTC, theofidry commented
>nothing is cached anymore about which normalizer to use so we can't have a problem about that ^^

Nevermind misread your comment. Indeed if there is no caching there anymore should be alright.

2016-07-27 11:07 UTC, mcfedr commented
Maybe there _should_ be caching? For a system with many Normalizers there is likely to be some gain from do so - You can imagine a Serializer that uses code generation to make this really fast.

Thinking if the use cases for this outweigh not being able (or so able) to create a cache in the future.

It seems like if the action of a Normalizer needs to change based on the content, it could always delegate in the actual normalize/denormalize methods.

2016-07-27 11:25 UTC, theofidry commented
@mcfedr caching at this level has been removed because proved to be more likely to cause bugs than anything else. The Serializer lookup is usually quite fast unless you really do weird things in your `supports*()`, if you want something faster still, the best thing is to cache the whole result.

2016-08-16 09:30 UTC, dunglas commented
ping @symfony/deciders

2016-09-21 13:46 UTC, ogizanagi commented
It would be great to have this feature for 3.2 :)

2016-09-21 14:02 UTC, nicolas-grekas commented
Changing the interfaces needs a smooth upgrade path. In this case, we have no choice but create new interfaces that extend the current ones, while deprecating them.

2016-09-21 14:08 UTC, dunglas commented
@nicolas-grekas It will be very difficult to find a better name than the current one. Maybe can we let interfaces as-is in 4.0+ (with the comment)? Updating every single implementation of these interfaces to use the new ones will be a very tedious work. But I agree, breaking existing code is a worst solution and we will not do it.

2016-09-21 14:23 UTC, nicolas-grekas commented
`ContextAware*Interface`?

2016-09-21 14:58 UTC, dunglas commented
Status: needs work

2016-09-21 15:21 UTC, Ener-Getick commented
@nicolas-grekas can't we instead trigger a deprecation when the last argument is not implemented? I don't like having new interfaces.

2016-09-21 15:25 UTC, nicolas-grekas commented
How would you do that? An interface cannot trigger any deprecation. Who would trigger it?

2016-09-21 15:29 UTC, Ener-Getick commented
The serializer, it should cover most cases.

2016-09-21 15:39 UTC, nicolas-grekas commented
@Ener-Getick could be tried :)

2016-09-21 17:23 UTC, Ener-Getick commented
@dunglas do you see what i'd like to do or do you need help? :)

2016-09-21 17:57 UTC, ogizanagi commented
@Ener-Getick : I fail to see how you expect to do it from the `Serializer`, considering the fact that, in the [old version of this PR](https://github.com/symfony/symfony/pull/19371/commits/8871fd7e94ab1cc167b55ca92f14a21e464fa38a) normalizers using it won't be able to have the `$context` argument in the signature, [but will still use something like `$context = 3 === func_num_args() ? func_get_arg(2) : [];` in order to acces it](https://github.com/symfony/symfony/pull/19371/commits/8871fd7e94ab1cc167b55ca92f14a21e464fa38a#diff-7a9e62dfccb4f89883ddfb1ad2dd8896R76). 😕 

Regarding new interfaces, when will the new `ContextAware*Interface` interfaces be deprecated and the support switch in order to make the original interfaces support the `$context` natively ?

Can't we create the new interfaces at the root of the component with the same name as before, and deprecate old ones instead ?

2016-09-21 18:00 UTC, ogizanagi commented on src/Symfony/Component/Serializer/Encoder/ContextAwareDecoderInterface.php
> +interface ContextAwareDecoderInterface extends DecoderInterface
[I don't think it can work by extending the old interface](https://3v4l.org/fjjMK) or am I missing something ? 😕

2016-09-21 19:05 UTC, Ener-Getick commented
@ogizanagi i was thinking only triggering deprecations for third party libraries and updating the symfony's api in 4.0. 
And i don't like much having new interfaces as it forces people to upgrade to a new interface AND update their api instead of only updating their api.

2016-09-22 06:24 UTC, dunglas commented
> @nicolas-grekas can't we instead trigger a deprecation when the last argument is not implemented? I don't like having new interfaces.

I doesn't feel confortable with this. From my experience, implementations of the `NormalizerInterface` are often used alone (without building an instance of the `Serializer` class). If we trigger a deprecation from the `Serializer` class, we will have no upgrade path for this case.

On the other hand, @nicolas-grekas's proposal is nice because it doesn't imply do deprecate anything. The new `ContextAware*Interface` interfaces can be implemented only by normalizers and encoders needing to have the context in their support method. Existing normalizers/encoders can be left untouched.

2016-09-22 06:31 UTC, dunglas commented on src/Symfony/Component/Serializer/Encoder/ContextAwareDecoderInterface.php
> +interface ContextAwareDecoderInterface extends DecoderInterface
It works if the argument is optional: https://3v4l.org/UiviL
I wasn't aware of that (thanks @nicolas-grekas for the hint) but it's practical here.

2016-09-22 06:35 UTC, ogizanagi commented on src/Symfony/Component/Serializer/Encoder/ContextAwareDecoderInterface.php
> +interface ContextAwareDecoderInterface extends DecoderInterface
Great :)

2016-09-22 06:51 UTC, dunglas commented
Status: needs review

2016-09-22 06:57 UTC, nicolas-grekas commented on src/Symfony/Component/Serializer/Normalizer/ArrayDenormalizer.php
> +        $context = func_num_args() > 3 ? func_get_arg(3) : array();
Why not uncommenting the argument? (Same at other places)

2016-09-22 06:58 UTC, nicolas-grekas commented on src/Symfony/Component/Serializer/Encoder/ChainDecoder.php
> +class ChainDecoder implements DecoderInterface/*, ContextAwareDecoderInterface*/
Why not replacing by the new interface?

2016-09-22 06:58 UTC, nicolas-grekas commented on src/Symfony/Component/Serializer/Encoder/ChainDecoder.php
> + * @author Kévin Dunglas <dunglas@gmail.com>
Really? :)

2016-09-22 06:59 UTC, nicolas-grekas requested changes

2016-09-22 07:34 UTC, dunglas commented on src/Symfony/Component/Serializer/Encoder/ChainDecoder.php
> +class ChainDecoder implements DecoderInterface/*, ContextAwareDecoderInterface*/
Because it will introduce a BC break (it will change the signature of the public method of this class).

2016-09-22 07:36 UTC, dunglas commented on src/Symfony/Component/Serializer/Normalizer/ArrayDenormalizer.php
> +        $context = func_num_args() > 3 ? func_get_arg(3) : array();
Same as before, adding a new argument to a public method isn't allowed by our BC policy.

2016-09-22 15:38 UTC, Ener-Getick commented
@dunglas that sounds weird to me to have an interface only for a new argument.
Maybe we could hook into the autoloading and detect classes that are not updated. That one looks a bit hacky but we could use it for many bc issues (and we could eventually find a solution to disable it in production to improve perf).

But are this interfaces used that often without the sf serializer ?

2016-09-23 16:24 UTC, Ener-Getick commented
We could create a new util class that would be very useful for many bc layers concerning interfaces:
```php
final class DeprecationDetectorAutoloader
{
    private static $registered = false;
    private static $enabled = true;
    private static $deprecationDetectors = array();

    /**
     * Has to be used before {@see self::register()}, or it has no effect.
     */
    public static function disable()
    {
        self::$enabled = false;
    }

    public static function register()
    {
        if (!self::$enabled || self::$registered) {
            return;
        }

        // trigger deprecations for classes already loaded
        foreach (get_declared_classes() as $class) {
            self::triggerDeprecations($class);
        }

        // Extend the autoloading functions
        $autoloadFunctions = spl_autoload_functions();
        if (false === $autoloadFunctions) {
            return;
        }

        // Unregister existing autoloaders as we extend them
        foreach ($autoloadFunctions as $function) {
            spl_autoload_unregister($function);
        }

        spl_autoload_register(function ($class) use ($autoloadFunctions) {
            // load the class
            foreach ($autoloadFunctions as $function) {
                $function($class);
                if (class_exists($class)) {
                    break;
                }
            }

            self::triggerDeprecations($class);
        });
        self::$registered = true;
    }

    public static function triggerDeprecations($class)
    {
        foreach(self::$deprecationDetectors as $detector) {
            $detector($class);
        }
    }

    public static function addDeprecationDetector(callable $deprecationDetector)
    {
        self::$deprecationDetectors[] = $deprecationDetector;
    }
}
```

It would be used like that:
```php
// you interface file
DeprecationDetectorAutoloader::addDeprecationDetector(function($class) {
    if (is_a($class, 'MyInterface') {
        @trigger_error('MyInterface is deprecated', E_USER_DEPRECATED);
    }
}
DeprecationDetectorAutoloader::register();
```

We should disable it when used in prod to have better perf but it won't be registered unless the concerned interfaces are loaded anyway.
WDYT?

2016-09-28 14:26 UTC, dunglas commented on src/Symfony/Component/Serializer/Encoder/ChainDecoder.php
> +    public function supportsDecoding($format/*, array $context = array()*/)
It's is very unlikely that some extended this class (I never seen this at least).

2016-09-28 14:29 UTC, Ener-Getick commented on src/Symfony/Component/Serializer/Encoder/ChainDecoder.php
> +    public function supportsDecoding($format/*, array $context = array()*/)
Or third option, deprecate extending this class?

2016-09-28 14:32 UTC, nicolas-grekas commented on src/Symfony/Component/Serializer/Encoder/ChainDecoder.php
> +    public function supportsDecoding($format/*, array $context = array()*/)
I'd personnaly be ok for 1. and uncomment all the currently commented code

2016-09-28 14:34 UTC, dunglas commented on src/Symfony/Component/Serializer/Encoder/ChainDecoder.php
> +    public function supportsDecoding($format/*, array $context = array()*/)
if we uncomment this code, we can also remove the trick with `func_num_args()`.

2016-09-28 14:35 UTC, nicolas-grekas commented on src/Symfony/Component/Serializer/Encoder/ChainDecoder.php
> +    public function supportsDecoding($format/*, array $context = array()*/)
and remove the double interface yes :)

2016-09-28 14:57 UTC, Ener-Getick commented on src/Symfony/Component/Serializer/Encoder/ChainDecoder.php
> +    public function supportsDecoding($format/*, array $context = array()*/)
Third option is deprecating extending this class :)

2016-10-24 17:54 UTC, ogizanagi commented
What is left to do with this one ? Is it still achievable for 3.2 and do you need any help to finish this PR @dunglas ?

AFAIU, we need to:
- make the `ChainDecoder` only implements `ContextAwareDecoderInterface`, uncomment the `/*, array $context = array()*/` argument and remove `func_num_args` hacks.
- make the `ChainEncoder` only implements `ContextAwareEncoderInterface`, uncomment the `/*, array $context = array()*/` argument and remove `func_num_args` hacks.

considering its quite uncommon to extend both chain encoders/decoders.

And we're good ?

2016-10-25 10:49 UTC, dunglas commented
I've uncommented all the commented code. It should be ok now to merge this PR.

However I'm unsure if it's ok or not to uncomment new arguments in the `Serializer` class. People may have extended its `supports*` methods. IMO it's not common but it can be considered as a (small) BC break.

WDYT? /cc @symfony/deciders

2016-10-25 18:21 UTC, xabbuh commented
@dunglas That is indeed a BC break and our BC promise forbids such a change (see http://symfony.com/doc/current/contributing/code/bc.html#changing-classes):

> | **Type of Change**  | **Change Allowed** |
|---|---|
| **Public Methods**  |  |
| Add argument with a default value  | No  |

2016-10-26 05:43 UTC, dunglas commented
@xabbuh yes I know but see this thread for the why: https://github.com/symfony/symfony/pull/19371#discussion_r80930575

We have 3 solutions if we want to merge give access to the context in `supports*` methods:

* Merge this PR without the last commit: https://github.com/symfony/symfony/pull/19371/commits/1cceb990dedb780c0be544cbaae0a4706d3d75c9 it doesn't introduce a BC break but has a bad upgrade path
* Merge this PR as is (including the last commit): it introduces a theoretical BC break but provide a smooth upgrade path (a line in the CHANGELOG should be enough for people having this BC to upgrade easily)
* Keep the hack only for the `Serializer` class (and not for chain classes) to prevent the most likely BC but have a smooth upgrade path for other classes

2017-01-28 19:18 UTC, dunglas commented
I've used the same strategy than in https://github.com/symfony/symfony/blob/5bd3a000d830e685791276f7f2975e8c649586b5/src/Symfony/Component/DependencyInjection/Compiler/Compiler.php#L75-L86

It should be ready now.

Status: Needs review

2017-02-13 10:31 UTC, nicolas-grekas commented on src/Symfony/Component/Serializer/Encoder/ChainDecoder.php
> +                    @trigger_error(sprintf('Method %s() will have a second `$context = array()` argument in version 4.0. Not defining it is deprecated since 3.3.', get_class($this), __FUNCTION__), E_
can't we remove this block since the class is `@final` now?

2017-02-13 10:31 UTC, nicolas-grekas commented on src/Symfony/Component/Serializer/Encoder/ChainEncoder.php
> +                    @trigger_error(sprintf('Method %s() will have a second `$context = array()` argument in version 4.0. Not defining it is deprecated since 3.3.', get_class($this), __FUNCTION__), E_
could be removed

2017-02-13 10:31 UTC, nicolas-grekas commented on src/Symfony/Component/Serializer/Encoder/ChainEncoder.php
> +                    @trigger_error(sprintf('Method %s() will have a third `$context = array()` argument in version 4.0. Not defining it is deprecated since 3.3.', get_class($this), __FUNCTION__), E_U
could be removed

2017-02-13 10:31 UTC, nicolas-grekas commented on src/Symfony/Component/Serializer/Normalizer/ArrayDenormalizer.php
> +                    @trigger_error(sprintf('Method %s() will have a fourth `$context = array()` argument in version 4.0. Not defining it is deprecated since 3.3.', get_class($this), __FUNCTION__), E_
make the class `@final` instead?

2017-02-13 10:31 UTC, nicolas-grekas commented on src/Symfony/Component/Serializer/Serializer.php
> +                    @trigger_error(sprintf('Method %s() will have a third `$context = array()` argument in version 4.0. Not defining it is deprecated since 3.3.', get_class($this), __FUNCTION__), E_U
make the class `@final` instead?

2017-02-13 10:31 UTC, nicolas-grekas commented on src/Symfony/Component/Serializer/Serializer.php
> +                    @trigger_error(sprintf('Method %s() will have a fourth `$context = array()` argument in version 4.0. Not defining it is deprecated since 3.3.', get_class($this), __FUNCTION__), E_
remove?

2017-02-13 10:31 UTC, nicolas-grekas commented on src/Symfony/Component/Serializer/Serializer.php
> +                    @trigger_error(sprintf('Method %s() will have a second `$context = array()` argument in version 4.0. Not defining it is deprecated since 3.3.', get_class($this), __FUNCTION__), E_
remove?

2017-02-13 10:31 UTC, nicolas-grekas commented on src/Symfony/Component/Serializer/Serializer.php
> +                    @trigger_error(sprintf('Method %s() will have a second `$context = array()` argument in version 4.0. Not defining it is deprecated since 3.3.', get_class($this), __FUNCTION__), E_
remove?

2017-02-13 12:54 UTC, dunglas commented on src/Symfony/Component/Serializer/Serializer.php
> +                    @trigger_error(sprintf('Method %s() will have a third `$context = array()` argument in version 4.0. Not defining it is deprecated since 3.3.', get_class($this), __FUNCTION__), E_U
Overriding this class is common (even if it's not a good practice IMO). Not sure it is worth it to make it final.

2017-02-13 13:07 UTC, nicolas-grekas approved these changes
:+1:

2017-02-13 14:29 UTC, fabpot commented on src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php
> +                if ($this->serializer->supportsDenormalization($data, $class, $format, $context)) {
@dunglas Can you check that my conflict resolution is the right one. If not, can you fix it directly on master? Thanks.

2017-02-13 14:29 UTC, fabpot commented
Thank you @dunglas.

2017-02-13 14:29 UTC, closed without merging

2017-02-13 14:50 UTC, dunglas commented on src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php
> +                if ($this->serializer->supportsDenormalization($data, $class, $format, $context)) {
@fabpot fixed in b5d9b3b99e.

2017-02-13 14:52 UTC, fabpot commented on src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php
> +                if ($this->serializer->supportsDenormalization($data, $class, $format, $context)) {
thanks