[SecurityBundle] Allow accessing remember_me services via FirewallMap
symfony/symfony pull request #19819
Opened 2016-09-01 22:45 UTC by chalasr

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #3137
| License       | MIT
| Doc PR        | todo

This allows to retrieve the `RememberMeServices` service of the current firewall from any container aware class using `Container::get('security.firewall.map')->getRememberMeServices(Request $request)`.

It seems there are use cases, see the ticket and the ones mentioning it (some from FOSUserBundle)

2016-09-01 23:50 UTC, HeahDude commented on src/Symfony/Bundle/SecurityBundle/Security/FirewallMap.php
> +        $context = $this->getContext($request);
What about caching contexts by requests using a `SplObjectStorage`?

2016-09-02 06:44 UTC, iltar commented
So does this encourage developers to avoid the security configuration to do it programmatically outside of the firewall? If so, sounds like a bad idea. All authentication related stuff should go through the firewall.  If this is a DX issue, maybe that should be solved instead?

2016-09-02 07:50 UTC, chalasr commented
@iltar That's not the goal of this PR, although you're right, it can be a side effect. 
I didn't just create a public alias of this service nor propose a LoginManager as [FOSUB did it](https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Security/LoginManager.php) for avoiding wrong usages by accessing the service of any firewall . The most relevant use case to me is when using third party libraries for authenticating users such as OAuth, where it can be useful to access the remember me services for persistence. ATM I don't see any alternative for fixing this issue while being restrictive on this point. Any clue?

2016-09-02 07:52 UTC, chalasr commented on src/Symfony/Bundle/SecurityBundle/Security/FirewallMap.php
> +        $context = $this->getContext($request);
It could be a good candidate I think!

2016-09-02 07:56 UTC, iltar commented
I don't know any alternative so I guess this is the way to go for the case at hand

2016-09-14 21:23 UTC, chalasr commented
@iltar Just re-read you.

> to avoid the security configuration

This allows to access the `remember_me` services of the _current_ firewall, involving to have this one secured, so it requires configuration as well as per the classic way (at least setting up a `remember_me`, which needs a form-positioned security factory configured, a user provider, etc.).
So this just allows to be authenticated by requesting a different endpoint than the login one, e.g. from a registration confirmation sent by email, which is IMHO useful.

BTW, Guard already provides a way to authenticate users programatically (which, contrarily to this, doesn't seem to require any configuration) via [`GuardAuthenticatorHandler::authenticateUserAndHandleSuccess()`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Security/Guard/GuardAuthenticatorHandler.php).

This PR could give a structured way to solve the related issues, and it is IMHO a nice have.

2016-09-28 01:40 UTC, lemoinem requested changes
Hi,

Thanks for the contribution. If you could take a look at my comment regarding the tests...

If you could also provide a docs PR, I think we would be good to go to Reviewed status.

2016-09-28 01:40 UTC, lemoinem commented on src/Symfony/Bundle/SecurityBundle/Tests/Security/FirewallContextTest.php
> +        $this->assertEquals($rememberMeServices, $context->getRememberMeServices());
Wouldn't `assertSame` be better in these cases?

2016-09-28 01:41 UTC, lemoinem commented
Status: Needs work

2016-09-28 11:14 UTC, chalasr commented
@lemoinem I updated the test according to your suggestion.

About the doc PR, I would like to have at least a thought from the core team before submitting it. Doc PRs being most often created after merging the code PR, it should not be a problem for marking this as reviewed.

Thank you for your review

2016-09-28 12:07 UTC, lemoinem approved these changes
Looks good to me! :+1:

2016-09-28 12:07 UTC, lemoinem commented
Status: Reviewed

2016-10-12 07:54 UTC, chalasr commented on src/Symfony/Bundle/SecurityBundle/Security/FirewallMap.php
> +        $context = $this->getContext($request);
Done in #20196

2016-11-05 11:01 UTC, chalasr commented
Not ready as is.
Status: needs work

2016-11-11 11:27 UTC, chalasr commented
Closing this as it doesn't look the best way to fix the related tickets.

2016-11-11 11:27 UTC, closed without merging