[Form] Add support for DateTimeImmutable
symfony/symfony pull request #19889
Opened 2016-09-08 11:17 UTC by jameshalsall

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #9508
| License       | MIT
| Doc PR        | TODO

This PR is an initial concept for adding support for \DateTimeImmutable in the Form component. 

The `DateType`, `TimeType` and `DateTimeType` now support a new "input" option called "datetimeimmutable". When this is set the returned values from `$form->getData()` will be instances of `\DateTimeImmutable` instead of `\DateTime` (which is the case for an "input" value of "datetime" - the default).

To implement the transformers for `DateTimeImmutable` I have extended the `DateTime` transformers and opened an extension point to get the class name. I originally toyed with wrapping the `DateTime` transformers with counterparts for `DateTimeImmutable` that would transform the `DateTime` instance to a `DateTimeImmutable`, but this would be bad for performance as we'd have to instantiate twice.

I'm looking for feedback on this approach before I finalise it.

2016-09-08 11:26 UTC, HeahDude commented on src/Symfony/Component/Form/Extension/Core/DataTransformer/DateTimeImmutableToArrayTransformer.php
> + * @package Symfony\Component\Form\Extension\Core\DataTransformer
We don't use `@package` in symphony core

2016-09-08 11:37 UTC, HeahDude commented on src/Symfony/Component/Form/Extension/Core/Type/DateTimeType.php
> +                $viewTransformerClass = $immutable ? DateTimeImmutableToRfc3339Transformer::class : DateTimeToRfc3339Transformer::class;
Why not passing the flag to the data transformers constructor so they use the right class internally?

2016-09-08 11:47 UTC, unkind commented on src/Symfony/Component/Form/Extension/Core/DataTransformer/DateTimeImmutableToArrayTransformer.php
> +class DateTimeImmutableToArrayTransformer extends DateTimeToArrayTransformer
Why not just `DateTimeToArrayTransformer::immutable()`?

2016-09-08 12:43 UTC, jameshalsall commented on src/Symfony/Component/Form/Extension/Core/DataTransformer/DateTimeImmutableToArrayTransformer.php
> +class DateTimeImmutableToArrayTransformer extends DateTimeToArrayTransformer
A factory method?

2016-09-08 12:46 UTC, jameshalsall commented on src/Symfony/Component/Form/Extension/Core/Type/DateTimeType.php
> +                $viewTransformerClass = $immutable ? DateTimeImmutableToRfc3339Transformer::class : DateTimeToRfc3339Transformer::class;
This is a good idea, although the constructors are already pretty lengthy, e.g. [`DateTimeToArrayTransformer::__construct()`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Extension/Core/DataTransformer/DateTimeToArrayTransformer.php).

I agree that the form Types probably know too much about the immutable handling than they should in their current form.

2016-09-09 13:16 UTC, jameshalsall commented on src/Symfony/Component/Form/Extension/Core/Type/DateTimeType.php
> +                $viewTransformerClass = $immutable ? DateTimeImmutableToRfc3339Transformer::class : DateTimeToRfc3339Transformer::class;
I've updated this now so it passes a flag to existing DateTime transformers

2016-09-09 13:55 UTC, HeahDude commented on src/Symfony/Component/Form/Extension/Core/DataTransformer/DateTimeToArrayTransformer.php
> +            $dateTime = new $dateTimeClass(sprintf(
`@return \DateTime` line 111 should be changed to `@return \DataTime|\DateTimeImmutable` and also in other transformers

2016-09-09 13:56 UTC, HeahDude commented on src/Symfony/Component/Form/Extension/Core/DataTransformer/BaseDateTimeTransformer.php
> +     * @param bool   $immutable      If the datetime is immutable
`If the datetime is immutable` => `Whether to use \DateTimeImmutable'`

2016-09-09 14:02 UTC, HeahDude commented
Much better :)

2016-09-09 14:10 UTC, jameshalsall commented on src/Symfony/Component/Form/Extension/Core/DataTransformer/DateTimeToArrayTransformer.php
> +            $dateTime = new $dateTimeClass(sprintf(
Updated to `@return \DateTimeInterface`

2016-09-14 22:31 UTC, gharlan commented
I would like to have an option to use custom DateTime class (extending `\DateTime` or `DateTimeImmutable`).

2016-09-17 20:24 UTC, HeahDude commented on src/Symfony/Component/Form/Extension/Core/DataTransformer/DateTimeToArrayTransformer.php
> +     * @return \DateTimeInterface Normalized date
the hint should be explicit here IMO: `@return \DateTime|DateTimeImmutable` since no other implementation is used.

2016-09-17 20:25 UTC, HeahDude requested changes

2016-09-17 20:27 UTC, HeahDude commented
@gharlan I think this is a topic for another PR.

2016-09-20 20:13 UTC, jameshalsall commented on src/Symfony/Component/Form/Extension/Core/DataTransformer/DateTimeToArrayTransformer.php
> +     * @return \DateTimeInterface Normalized date
I think leaving it as `\DateTimeImmutable` is still semantically correct, and is more concise

2016-09-20 20:13 UTC, jameshalsall commented
@fabpot @webmozart what are the chances of this making it into 3.2 before the end of the development phase?

2016-09-28 01:29 UTC, lemoinem approved these changes
The tests are failing because of issues in SecurityBundle or the VarDumper Component, and a (purposefully) malformed ini for hhvm.

If you could prepare the docs PR, I think this is quite ready to be merged.

2016-09-28 08:01 UTC, jameshalsall commented
I'm away for the next few days so I'll work on the docs PR when I return.

2017-02-01 09:44 UTC, kaiwa commented
> I'll work on the docs PR when I return.

@jameshalsall I hope you returned :laughing:

2017-02-01 10:11 UTC, jameshalsall commented
@kaiwa Haha, I completely forgot about this - I'll add it to my TODO list to create the docs PR

2017-03-01 16:39 UTC, HeahDude commented
I would not merge this one as is, in favor of more work to address the last (and most important IMHO) part of the related issue:

>If a new major version of Symfony bumps the requirement to PHP 5.5+, the normalized data could then be switched to the DateTimeImmutable class to simplify the logic (which is currently cloning the DateTime to avoid modifying the original one.

2017-03-01 16:43 UTC, fabpot commented
Makes sense. So, I'm closing this one as Symfony 3 does require PHP 5.5+.

2017-03-01 16:43 UTC, closed without merging

2017-03-01 16:50 UTC, HeahDude commented
I have an idea of what to do for this, but some other issues must be addressed first.

2017-03-01 16:52 UTC, HeahDude commented
In the mean time, it's really easy to implement a model transformer in user land if needed.

2017-03-01 16:52 UTC, jameshalsall commented
Wish you'd have said that back in September ;)