[Console] Escape default value in SymfonyStyle::ask()
symfony/symfony pull request #19961
Opened 2016-09-18 13:38 UTC by chalasr

| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #19493 
| License       | MIT
| Doc PR        | n/a

2016-09-18 14:00 UTC, ro0NL commented
This needs to be done on a per case basis? Ie. `case $question instanceof ChoiceQuestion:` requires a different approach right?

2016-09-18 14:11 UTC, sstok commented on src/Symfony/Component/Console/Helper/SymfonyQuestionHelper.php
> +        if (null !== $default) {
Needs to be skipped for `ConfirmationQuestion`, else bool is converted to a string.

2016-09-18 14:12 UTC, sstok requested changes

2016-09-18 14:41 UTC, chalasr commented
I made the change, refactoring a bit btw so we stop duplications.
If it looks less readable, please say me so I rollback and do the change for each case of the switch that need it.

2016-09-18 14:45 UTC, ro0NL commented
Yeah.. i would say revert and escape where needed.

2016-09-18 15:49 UTC, chalasr commented
Reverted.

2016-10-05 03:05 UTC, fabpot commented
Thank you @chalasr.

2016-10-05 03:06 UTC, merged