Hide commands from TextDescriptor, but allow invoking
symfony/symfony pull request #20029
Opened 2016-09-22 20:13 UTC by jwdeitch

I would like to hide commands from cluttering the TextDescriptor, but still allow their invocation from code or cron.

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | comma-separated list of tickets fixed by the PR, if any
| License       | MIT
| Doc PR        | reference to the documentation PR, if any

2016-09-25 20:06 UTC, ro0NL commented on src/Symfony/Component/Console/Command/Command.php
> +    private $hidden;
Should be `$this->hidden = false;`

2016-09-25 20:07 UTC, ro0NL commented on src/Symfony/Component/Console/Command/Command.php
> +    public function setHidden($hiddenBool)
Should be `$hidden`

2016-09-25 20:09 UTC, jwdeitch commented on src/Symfony/Component/Console/Command/Command.php
> +    public function setHidden($hiddenBool)
indeed. Thank you sir

2016-09-25 20:09 UTC, ro0NL commented on src/Symfony/Component/Console/Command/Command.php
> +     * @param bool $hiddenBool To show this command or not
Derp.

2016-09-25 20:10 UTC, ro0NL commented on src/Symfony/Component/Console/Command/Command.php
> +     * @param bool $hiddenBool To show this command or not
What about `To hide the command in application descriptions`.

2016-09-25 20:18 UTC, ogizanagi commented
What about other descriptors ?

2016-09-25 20:22 UTC, ro0NL commented
@ogizanagi all format use `ApplicationDescription::getCommands`. https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Console/Descriptor/JsonDescriptor.php#L67

2016-09-25 20:23 UTC, jwdeitch commented
@ogizanagi Sorry which speicifically? The other descriptors seems to call `ApplicationDescription->getCommands()`

2016-09-25 20:27 UTC, ogizanagi commented
@ro0NL, @jwdeitch : Oh right. Sorry. PR title & description may be updated I guess then 😉 .

2016-09-29 10:21 UTC, javiereguiluz commented
Could we change the method names to follow the same notation as for services? Instead of `setHidden()` and `isHidden()` -> `setPublic(true / false)` and `isPublic()` ?

2016-09-29 18:45 UTC, ro0NL commented
Maybe if we run a private command it should give you a heads up in verbose mode..  would that be useful?

2016-09-29 18:55 UTC, jwdeitch commented
Good idea. Should we merge this first then address that? Or I can throw it into this PR

2016-09-29 18:57 UTC, ogizanagi commented
@jwdeitch : Could you update the testsuite (`AbstractDescriptorTest`) by adding a new private command in `DescriptorApplication2` ?

2016-09-29 19:02 UTC, ogizanagi requested changes

2016-09-29 19:02 UTC, ogizanagi commented on src/Symfony/Component/Console/Command/Command.php
> +     * @param bool $public To show this command or not
I'd suggest something like: `Whether the command should be publicly shown or not.` and remove the above description (which brings nothing more IMHO).

2016-09-29 19:02 UTC, ogizanagi commented on src/Symfony/Component/Console/Command/Command.php
> +     * @return bool If the command is public or not
Same. I feel this repetition is useless.

2016-09-30 19:38 UTC, fabpot commented on src/Symfony/Component/Console/Command/Command.php
> +        $this->public = $public;
should be `$this->public = (bool) $public;`

2016-09-30 19:38 UTC, fabpot commented on src/Symfony/Component/Console/Command/Command.php
> +    public function setPublic($public)
What about `setPrivate()` without an argument? I don't see a need to switch from private to public.

2016-09-30 19:47 UTC, javiereguiluz commented on src/Symfony/Component/Console/Command/Command.php
> +    public function setPublic($public)
I suggested changing it to `setPublic(false)` to mimic Symfony services ... where you must set `public: false` for private services. If we use opposing techniques to do the same (`public: false` for services, `private: true` for commands) we're increasing the learning curve.

2016-09-30 19:55 UTC, jwdeitch commented on src/Symfony/Component/Console/Command/Command.php
> +    public function setPublic($public)
we could meet in the middle at `setPublicity` as it's not favoring one way or another :)

2016-10-05 02:53 UTC, fabpot commented
Thank you @jwdeitch.

2016-10-05 02:53 UTC, merged

2016-10-20 22:35 UTC, wouterj commented
I think calling this *private* will have the same confusion that was just solved with the services: I expect I cannot run private services outside the app, but I still can. It's simply only hidden in the command listing.

Calling this *hidden* does a better job in describing the feature imo.

2016-10-21 13:48 UTC, fabpot commented
I tend to agree with @wouterj. A private command is indeed not really private in the same sense as for the container, it's just hidden from the list of commands and can still be executed like any other commands. @javiereguiluz WDYT?

2016-10-21 13:57 UTC, javiereguiluz commented
I understand "private" as something hidden, secret, confidential, special. Those are precisely the [synonyms of the "private" word](http://www.thesaurus.com/browse/private). If we talk about commands that cannot be executed outside the app, to me that would be: "banned", "secured", "disabled", "closed", etc.

But if this is confusing to others, then "hidden" is also a very understandable name for this feature.

2016-10-21 14:53 UTC, stof commented
@javiereguiluz the confusion is that it has a different behavior than ``private`` in the DI component:

- in DI, a private service can be injected into other services, but cannot be accessed from the outside of the container
- in console, a private command can be called like any other command, as long as you know it exists.

2016-10-21 19:28 UTC, xabbuh commented
I agree with @wouterj and @fabpot. I opened #20266 which would rename `$public` to `$hidden`.