Deprecate the special SYMFONY__ environment variables
symfony/symfony pull request #20100
Opened 2016-09-30 07:51 UTC by javiereguiluz

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | yes
| Tests pass?   | yes
| Fixed tickets | #20089
| License       | MIT
| Doc PR        | -

2016-09-30 08:13 UTC, nicolas-grekas commented
Just challenging this one: the pending PR on this topic now says:
> You can also define the default value of any existing parameters using special environment variables named after their corresponding parameter prefixed with SYMFONY__ after replacing dots by double underscores (e.g. SYMFONY__KERNEL__CHARSET to set the default value of the kernel.charset parameter). These default values are resolved when compiling the service container and won't change at runtime once dumped.

See http://pr-6918-6qmocelev2lwe.eu.platform.sh/configuration/external_parameters.html#environment-variables

To me, the use case is different. `env()` parameters do not allow this (setting the default value of parameter at compile time through env vars).
Do we really consider this as something we don't want to support anymore?

2016-09-30 08:33 UTC, nicolas-grekas commented
If the answer is yes (see above challenge), shouldn't we deprecate `EnvParametersResource` and `getEnvParameters` also?

2016-09-30 08:34 UTC, iltar commented
@nicolas-grekas if `SYMFONY__` indicated that it was a value only used to build parameters and stores the calculated version, maybe something like `build_env(...)` could solve the problem?

2016-09-30 08:37 UTC, nicolas-grekas commented
It's also a matter of who own the relationship between the env and the config.
`env()` or any such alternatives are the way to go to *pull* from the env.
`SYMFONY__` *push* to parameters.
Different directions, different use case to me.

2016-10-01 09:07 UTC, ro0NL commented
> It's also a matter of who owns the relationship between the env and the config.

Deprecating the magic `SYMFONY__` vars brings back the ownership to the config.. imo that's a good thing.

2016-10-01 11:04 UTC, wouterj commented
If deprecation is coming, I don't agree with the implementation of the deprecation. I can imagine people want to keep the `SYMFONY__` parameters and just instead request them with `env('SYMFONY__')` (to ease migration). This will currently still result in the deprecation...

2016-11-24 11:21 UTC, nicolas-grekas commented
I propose #20618 as an alternative to using `SYMFONY__` env vars for compile time env vars resolution. Which means I'm not :+1: to deprecate them, thus unlocking this PR from my pov.

2016-12-09 11:35 UTC, nicolas-grekas commented
@wouterj can you think of another way? IMO, it looks sensible the way it is now.

2016-12-19 06:33 UTC, xabbuh requested changes

2016-12-19 06:33 UTC, xabbuh commented on src/Symfony/Component/HttpKernel/Kernel.php
> +                @trigger_error(sprintf('The special environment variables that start with SYMFONY__ (such as "%s") are deprecated as of 3.2 and will be removed in 4.0. Use instead the %env()% syntax
3.3

2016-12-19 06:33 UTC, xabbuh commented on src/Symfony/Component/HttpKernel/Tests/KernelTest.php
> +        ErrorAssert::assertDeprecationsAreTriggered($expectedDeprecations, function () use ($kernel, $method) {
You now have to use the annotation instead.

2017-01-06 14:34 UTC, nicolas-grekas commented
don't forget this one @javiereguiluz

2017-01-06 16:11 UTC, javiereguiluz commented
@nicolas-grekas updated with the fixes suggested by reviewers.

2017-01-06 17:35 UTC, xabbuh requested changes

2017-01-06 17:35 UTC, xabbuh commented on src/Symfony/Component/HttpKernel/Kernel.php
> +                @trigger_error(sprintf('The special environment variables that start with SYMFONY__ (such as "%s") are deprecated as of 3.3 and will be removed in 4.0. Use instead the %env()% syntax
I would move "instead" after "syntax".

2017-01-06 17:35 UTC, xabbuh commented on src/Symfony/Component/HttpKernel/Tests/KernelTest.php
> +     * @expectedExceptionMessage The special environment variables that start with SYMFONY__ (such as "SYMFONY__FOO__BAR") are deprecated as of 3.3 and will be removed in 4.0. Use instead the %env()%
`@expectedDeprecation`

2017-01-06 17:40 UTC, ro0NL commented
> If deprecation is coming, I don't agree with the implementation of the deprecation. I can imagine people want to keep the SYMFONY__ parameters and just instead request them with env('SYMFONY__') (to ease migration). This will currently still result in the deprecation...

This is true. Defining an `SYMFONY__` env var is not deprecated, only the magic part where it's set as a parameter.

I also dont really agree on tests here.. using reflection smells.

I think roughly the path is
- Remove `$_SERVER` implementation
- Trigger deprecation if a `SYMFONY__` var is defined, but not configured as a parameter, ie;

```yaml
'database.name': '...'
```

- Otherwise set de default parameter along with it, ie;

```yaml
'database.name': '%env(SYMFONY__DATABASE_NAME)%'
```

Should work out right?

2017-01-06 17:45 UTC, nicolas-grekas commented
Let be pragmatic here: if any `SYMFONY__` env var exists, its because *we* asked for them. Which means it's OK to deprecate *the env vars*. MHO.

2017-01-06 17:46 UTC, ro0NL commented
:+1: ok then. Already thought something like that.. just wanted to make sure we did not overlooked it :)

2017-01-06 17:48 UTC, ro0NL commented on src/Symfony/Component/HttpKernel/Kernel.php
> +                @trigger_error(sprintf('The special environment variables that start with SYMFONY__ (such as "%s") are deprecated as of 3.3 and will be removed in 4.0. Use instead the %env()% syntax
` and will be removed in 4.0`

We cant really remove user env vars ^^ i'd go with `and will not be supported anymore in 4.0`.

2017-01-26 21:43 UTC, chalasr commented
Instead of triggering the deprecation when registering the parameter, couldn't we trigger it when getting the parameter (reversing the key transformation and trigger if we find it in $_SERVER)?

Also, shouldn't the `Kernel::getEnvParameters()` method be deprecated?

2017-02-14 13:57 UTC, nicolas-grekas commented
rebase needed - to make tests green at least

2017-03-06 09:42 UTC, javiereguiluz commented
The rebase wen't wrong ... closing it in favor of #21889.

2017-03-06 09:42 UTC, closed without merging