[HttpKernel] Parse bundle name+namespace at once
symfony/symfony pull request #20117
Opened 2016-10-01 16:06 UTC by ro0NL

| Q             | A
| ------------- | ---
| Branch?       | "master"
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | comma-separated list of tickets fixed by the PR, if any
| License       | MIT
| Doc PR        | reference to the documentation PR, if any

2016-10-01 23:59 UTC, lemoinem commented
Hey,

Since this is not a bug fix. Shouldn't this be applied against `master`? Or is the performance boost that big?

2016-10-02 01:36 UTC, fabpot commented
That's definitely for master

2016-10-02 01:44 UTC, lemoinem requested changes

2016-10-02 01:44 UTC, lemoinem commented on src/Symfony/Component/HttpKernel/Bundle/Bundle.php
> +        $class = get_class($this);
Since this is intended to target `master`, I'm guessing you could replace that by `static::class`?

2016-10-02 01:44 UTC, lemoinem commented
Status: Needs Work

2016-10-02 08:34 UTC, ro0NL commented
> Or is the performance boost that big?

Not sure.. it must gain something i guess :) I thought it was nice little tweak for 2.7 as well.

Ie. imo its not a bug fix nor a new feature (new feature for the user that is). I guess the thing is we should be safe with refactoring.. as things can easily go [wrong](https://github.com/symfony/symfony/pull/19848) :sweat_smile: 

Ill target master :+1:

2016-10-02 15:59 UTC, fabpot commented
Thank you @ro0NL.

2016-10-02 15:59 UTC, merged