DomCrawler: Allow pipe (|) character in link tags when using Xpath expressions
symfony/symfony pull request #20229
Opened 2016-10-16 20:17 UTC by klausi

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | no
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

Drupal issue: https://www.drupal.org/node/2808085
Mink issue: https://github.com/minkphp/Mink/pull/720

We need the pipe (|) character for testing in Drupal. Example: `<a href="/example">Klausi|Claudiu</a>` should be findable with an XPath expression targeting the tag content Klausi|Claudiu.

Failing test case as a start to demonstrate the problem.

2016-10-16 20:34 UTC, klausi commented
I copied the splitUnionParts() method 1:1 from Mink, see https://github.com/minkphp/Mink/blob/master/src/Selector/Xpath/Manipulator.php#L77

2016-10-17 01:14 UTC, jibran commented on src/Symfony/Component/DomCrawler/Tests/CrawlerTest.php
> +                    <a href="/example">Klausi|Claudiu</a>
Why not use FooBar?

2016-10-17 07:52 UTC, stloyd requested changes

2016-10-17 07:52 UTC, stloyd commented on src/Symfony/Component/DomCrawler/Crawler.php
> +        for ($i = 0; $i < strlen($xpath); ++$i) {
`strlen()` should be moved out from, from here to not be called on every interation of `for()`

2016-10-17 08:24 UTC, stof commented
:+1: for this (note that I already reviewed the code in Mink)

2016-10-17 09:08 UTC, iltar commented on src/Symfony/Component/DomCrawler/Tests/CrawlerTest.php
> +                    <a href="/example">Klausi|Claudiu</a>
I think the idea was to use fake data and names all the time

2016-10-17 11:36 UTC, jakzal commented
Is there any performance impact of this change?

2016-10-17 13:16 UTC, stof commented
there is a perf impact for this change, especially when using pcre.jit (this effect might be multiplied by the fact that the JIT may perform better when using the same regex in a loop though). However, the current splitting is broken.
It is possible to minimize the impact for XPath not using union by short-circuiting splitting when there is no ``|`` in the string.

See https://gist.github.com/stof/5131c79c576600800aac7313b182d44d

2016-10-17 13:35 UTC, stof commented
@nicolas-grekas maybe you have an idea of some PHP magic to reduce the performance impact here.

2016-10-18 08:26 UTC, nicolas-grekas commented
See #20235

2016-10-18 11:44 UTC, klausi commented
I think we can close this one now in favor of #20235 which has a couple of performance improvements. Thanks @nicolas-grekas !

2016-10-18 11:44 UTC, closed without merging