[LDAP] expose instance of ConnectionInterface in Ldap
symfony/symfony pull request #20245
Opened 2016-10-19 11:52 UTC by fruitwasp

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        |

2016-10-19 12:50 UTC, xabbuh requested changes

2016-10-19 12:50 UTC, xabbuh commented on src/Symfony/Component/Ldap/LdapInterface.php
> +    public function getConnection();
This is a BC break and cannot be done.

2016-10-19 12:51 UTC, xabbuh commented
Can you explain the use case for this change?

2016-10-19 13:00 UTC, fruitwasp commented
I would like to access [Connection.isBound](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Ldap/Adapter/ExtLdap/Connection.php#L39) to check whether it's already bound or not and therefore should bind to ldap or not.

2016-10-20 17:27 UTC, ro0NL commented
Makes sense to have `LdapInterface::isBound` along with `bind`. I dont think it should expose the whole connection object.

And apparently it can be done :) see https://github.com/symfony/symfony/issues/20258#issuecomment-255152599

2016-10-21 07:54 UTC, fruitwasp commented
As adding methods to the `LdapInterface` breaks bc, I've only added the method `isBound` to the implementation `Ldap`, which works exactly like `Ldap::bind`

2016-11-03 09:03 UTC, fruitwasp commented
@csarrazi

2016-11-03 10:07 UTC, csarrazi commented
The thing is, I am not really fond of exposing the `isBound()` method. The main reason for this is that you won't be able to tell which DN was used when binding to the LDAP server, which may induce someone into thinking that a user is logged in, whereas in reality, you were bound using a search user, or even bound anonymously.

At some point, I was actually even considering removing the `isBound()` method and the associated property from the Connection object as it may induce people into thinking that they are already collected with the correct user.

2016-11-08 08:30 UTC, csarrazi commented
Another addition. The only reason why the `isBound()` method and its associated property exist is to prevent re-binding with an anonymous user when issuing a query, if already bound previously.
If there was no bound user before, then the query issues an anonymous bind.

To sum up, it is not the responsibility of the ldap component to track which user is bound to the current connection, but the application.

All in all, I'm 👎 on exposing the `isBound()` method.

2016-11-08 14:49 UTC, fabpot commented
Closing then

2016-11-08 14:49 UTC, closed without merging