[Yaml] Fix String offset cast error in Inline parser
symfony/symfony pull request #20335
Opened 2016-10-28 07:36 UTC by romainneutron

| Q             | A
| ------------- | ---
| Branch?       | 3.2/master
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | N/A
| License       | MIT

2016-10-28 11:34 UTC, GuilhemN requested changes

2016-10-28 11:34 UTC, Ener-Getick commented on src/Symfony/Component/Yaml/Tests/InlineTest.php
> +        Inline::parse('{this, is not, yaml}');
Actually this is valid and should be equivalent to `{ this: ~, is not: ~, yaml: ~ }`.

2016-10-28 11:37 UTC, Ener-Getick commented
BTW my PR already [fixes that](https://github.com/symfony/symfony/pull/19750/files) but does a lot of stuff at the same time.

2016-10-30 08:49 UTC, romainneutron commented
As we're already in a release candidate status for 3.2, adding new features is not possible. If you have a better fix, just let me know @Ener-Getick . This patch solves an issue in the current version

2016-10-30 08:57 UTC, Ener-Getick commented
Then let's wait for 3.3, but i don't think making invalid something that should be valid is a solution.

2016-10-30 10:28 UTC, xabbuh commented on src/Symfony/Component/Yaml/Tests/InlineTest.php
> +        Inline::parse('{this, is not, yaml}');
You are right. But this string wasn't even parsed before, was it? But we should nonetheless choose a better failing test case here.

2016-11-02 12:57 UTC, nicolas-grekas commented
:+1:
at least we won't miserably fail with a PHP Warning :)
and throwing a parse error for a syntax not supported by the current parser is fine for now IMHO.

2016-11-02 13:19 UTC, Ener-Getick commented
I reviewed your pr again and it looks like indeed that the input you test resulted at least in a warning as @nicolas-grekas said. 
So i'm 👍 for this (it should probably be merged in 2.7), it can't hurt.

2016-11-02 13:37 UTC, nicolas-grekas commented
Checked: this is for master only, 2.7 already fails properly here, the strpos is new to 3.2.

2016-11-02 13:45 UTC, nicolas-grekas commented
See #20388 on 2.7

2016-11-02 14:03 UTC, fabpot commented
Thank you @romainneutron.

2016-11-02 14:03 UTC, merged