[FrameworkBundle] Improve performance of ControllerNameParser
symfony/symfony pull request #20374
Opened 2016-11-01 12:03 UTC by enumag

| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets |
| License       | MIT
| Doc PR        |

Today I was searching for bottlenecks in my application using Blackfire. And among other things I found one in Symfony. Blackfire showed that `Symfony\Bundle\FrameworkBundle\Controller\ControllerNameParser::findAlternative()` was called almost 300 times which took 28 miliseconds.

It turns out that `Symfony\Bundle\FrameworkBundle\Routing\DelegatingLoader::load()` is calling `ControllerNameParser::parse()` without actually needing to do so because `$controller` is in the class::method notation already. `ControllerNameParser` threw an exception, DelegatingLoader caught and ignored it - that's ok. The problem is that generating the exception message took a lot of time because findAlternative is slow (in my case it called the levenshtein function over 5000 times) and was completely useless because the exception is ignored anyway.

2016-11-01 12:19 UTC, stloyd requested changes

2016-11-01 12:19 UTC, stloyd commented on src/Symfony/Bundle/FrameworkBundle/Controller/ControllerNameParser.php
> +        if (3 !== count($parts) || $parts[1] === '') {
Second check would be faster so IMO should be first ;)

2016-11-01 12:28 UTC, enumag commented on src/Symfony/Bundle/FrameworkBundle/Controller/ControllerNameParser.php
> +        if (3 !== count($parts) || $parts[1] === '') {
Can't be first because `$parts[1]` might not exist.

2016-11-01 17:49 UTC, ro0NL commented on src/Symfony/Bundle/FrameworkBundle/Controller/ControllerNameParser.php
> +        if (3 !== count($parts) || $parts[1] === '') {
Perhaps check `[0]` and `[2]` as well for emptiness?

2016-11-02 07:22 UTC, nicolas-grekas commented
Just wondering: would it make sense to add this check in DelegatingLoader instead?
Something like:
```patch
--- a/src/Symfony/Bundle/FrameworkBundle/Routing/DelegatingLoader.php
+++ b/src/Symfony/Bundle/FrameworkBundle/Routing/DelegatingLoader.php
@@ -21,7 +21,7 @@ use Psr\Log\LoggerInterface;
  * DelegatingLoader delegates route loading to other loaders using a loader resolver.
  *
  * This implementation resolves the _controller attribute from the short notation
- * to the fully-qualified form (from a:b:c to class:method).
+ * to the fully-qualified form (from a:b:c to class::method).
  *
  * @author Fabien Potencier <fabien@symfony.com>
  */
@@ -85,7 +85,8 @@ class DelegatingLoader extends BaseDelegatingLoader
         $this->loading = false;
 
         foreach ($collection->all() as $route) {
-            if ($controller = $route->getDefault('_controller')) {
+            $controller = $route->getDefault('_controller');
+            if ($controller && false === strpos($controller, '::')) {
                 try {
                     $controller = $this->parser->parse($controller);
                 } catch (\InvalidArgumentException $e) {
```

2016-11-02 08:32 UTC, enumag commented
@nicolas-grekas I can add that as well but the change in ControllerNameParser should be done regardless in my opinion.

2016-11-02 08:39 UTC, nicolas-grekas commented on src/Symfony/Bundle/FrameworkBundle/Controller/ControllerNameParser.php
> +        if (3 !== count($parts) || $parts[1] === '') {
we prefer yoda style: `'' === $parts[1]`

2016-11-05 08:44 UTC, enumag commented
@nicolas-grekas  @ro0NL All fixed.

2016-11-05 09:42 UTC, nicolas-grekas commented
:+1:

2016-11-05 11:09 UTC, xabbuh commented
👍

2016-11-05 11:18 UTC, ro0NL reviewed
:+1:

2016-11-05 11:18 UTC, ro0NL commented on src/Symfony/Bundle/FrameworkBundle/Controller/ControllerNameParser.php
> +        // The second condition is for cases when this method is called with the
I think the exception message is already straightforward now? Imo. no need for this comment.

2016-11-05 11:18 UTC, ro0NL commented on src/Symfony/Bundle/FrameworkBundle/Routing/DelegatingLoader.php
> +            if ($controller && false === strpos($controller, '::')) {
Instead, maybe add a comment here about skipping FQCN's for performance.

2016-11-06 07:11 UTC, enumag commented
@ro0NL Like this?

2016-11-10 15:35 UTC, dunglas commented on src/Symfony/Bundle/FrameworkBundle/Routing/DelegatingLoader.php
> +            if ($controller && false === strpos($controller, '::')) {
What do you think about using a guard clause here to reduce the complexity of the code?

```php
if (!$controller || false !== strpos($controller, '::')) {
    continue;
}
```

2016-11-10 16:27 UTC, enumag commented on src/Symfony/Bundle/FrameworkBundle/Routing/DelegatingLoader.php
> +            if ($controller && false === strpos($controller, '::')) {
@dunglas Good idea. I'll change it.

2016-11-10 17:06 UTC, dunglas commented
👍

2016-11-10 21:58 UTC, enumag commented on src/Symfony/Bundle/FrameworkBundle/Routing/DelegatingLoader.php
> +            if ($controller && false === strpos($controller, '::')) {
Done.

2016-11-19 10:28 UTC, enumag commented
I didn't notice the coding style error before, Fixed now. Anything else?

2016-11-24 12:55 UTC, enumag commented
The failed test does not seem related.

2016-11-25 11:34 UTC, enumag commented on src/Symfony/Bundle/FrameworkBundle/Routing/DelegatingLoader.php
> +            // If $controller is in class::method notation already skip it for performance.
@nicolas-grekas Understood, done.

2016-11-25 11:41 UTC, stof commented
👍 for this

And should we apply it to older branches too ? We did it in the past for some performance improvements.

On a side note, this will not improve the performance in prod, except for the cache warmup, as the routing loader is not called once anymore the matcher and generator are cached.

2016-11-25 12:12 UTC, nicolas-grekas commented
Thank you @enumag.

2016-11-25 12:12 UTC, closed without merging

2016-11-25 18:33 UTC, fabpot commented
This one should not have been merged in 2.7. It does not fix a bug. This should have been merged in master instead (not even 3.2 at this stage).