Fix context listener misbehaviour
symfony/symfony pull request #20401
Opened 2016-11-03 14:28 UTC by Einenlum

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | yes
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #4498
| License       | MIT
| Doc PR        | |

The implementation of `ContextListener` is not logical.

Here is the actual difference between the `ContextListener` and the `ChainUserProvider`.
The `ContextListener` will only loop if the provider throws an `UnsupportedUserException`:

```php
foreach ($this->userProviders as $provider) {
    try {
        // …
        return $token;
    } catch (UnsupportedUserException $e) {
        // let's try the next user provider
    } catch (UsernameNotFoundException $e) {
        if (null !== $this->logger) {
            $this->logger->warning('Username could not be found in the selected user provider.', array('username' => $e->getUsername(), 'provider' => get_class($provider)));
        }

        return;
    }
}
```

The `ChainUserProvider` on the other hand, will try to refresh the user with every provider even if the user was not found : 

```php
foreach ($this->providers as $provider) {
    try {
        return $provider->refreshUser($user);
    } catch (UnsupportedUserException $e) {
        // try next one
    } catch (UsernameNotFoundException $e) {
        $supportedUserFound = true;
        // try next one
    }
}
```

This is not only undocumented, it is also very disturbing. This leads to strange behaviours: If you had not set a chain provider, the login is successful but right after the redirection you're anonymous again without form error.

We really need to fix this incoherent behaviour. `ChainProvider` should be necessary only if you want to use multiple providers for **a specific firewall**.

(Tests are failing already on master, not linked to the PR)

2016-11-03 14:40 UTC, aguidis commented
:+1:

2016-11-03 15:08 UTC, Nek- requested changes

2016-11-03 15:08 UTC, Nek- commented on src/Symfony/Component/Security/Http/Firewall/ContextListener.php
> +                continue;
why drop the comment (which is accurate) and add a continue (which is useless) ?

2016-11-05 11:04 UTC, xabbuh commented
Imo the context listener should rather not try to use all user providers to refresh the user, but should only use the user provider that was configured to the active firewall.

2016-11-06 09:20 UTC, Einenlum commented
@xabbuh Agreed. But the question still remain when there is no firewall configured for the firewall, doesn't it?

2016-11-06 09:38 UTC, xabbuh commented
@Einenlum It should then use the first configured user provider like it's done elsewhere.

2016-12-09 15:22 UTC, slaci commented
This is very optimistic solution :P If you have 3 providers and you need the 3th, then the first two will query, fetch or something their backends on every page load. For example 3 query per page load just to refresh the user... and can be worse if you have rest api providers or anything else slow.

And the continue doesn't do anything there, if you just use that exception (UnsupportedException) then you are doing the same thing :)

Checking the firewall's provider is tricky too, because:
1. It seems very hard to check which firewall are we in. In 3.2 there is a new FirewallConfig or FirewallContext class which may help, dont know.
2. The firewall may have a provider key, but one firewall may have more than one authentication method which can overwrite that provider key. For example form_login and basic may have distinct providers in the same firewall, if someone like suffering.

So you don't really know, which method (provider) the user came from.

The only solution would be to save the provider in the token or user, but as fabpot said in the connected issue, it was there once, and they removed it for unkown reasons. Changing the tokeninterface would be big bc break, so no much hope :P

2016-12-27 14:28 UTC, nicolas-grekas commented
Note that BC breaks are not allowed, so you'll need another approach if you need this in the core.

2017-02-27 21:26 UTC, xabbuh commented
closing in favour of #21791

2017-02-27 21:26 UTC, closed without merging

2017-03-04 12:39 UTC, xabbuh commented
@Einenlum Can you check if #21865 fixes your issue?