[Workflow] Improved validator PHPdoc clarifying its API
symfony/symfony pull request #20492
Opened 2016-11-11 17:55 UTC by ro0NL

| Q             | A
| ------------- | ---
| Branch?       | "master"
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | comma-separated list of tickets fixed by the PR, if any
| License       | MIT
| Doc PR        | reference to the documentation PR, if any

See also https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/ValidateWorkflowsPass.php#L48

2016-11-11 17:58 UTC, ro0NL commented
@HeahDude sorry missed your changes in #20490, to me this makes more sense, rather then combining `true` and `throw`.

2016-11-12 09:44 UTC, xabbuh commented
I agree that it is not really intuitive to throw an exception in case of an invalid definition, but return `true` otherwise.

2016-11-12 09:44 UTC, xabbuh commented on src/Symfony/Component/Workflow/Validator/DefinitionValidatorInterface.php
> +     * @return void
should be removed entirely

2016-11-13 09:36 UTC, ro0NL commented
So.. what about removing the `WorkflowValidator` - https://github.com/symfony/symfony/pull/20490#discussion_r87690017?

Looks like a premature optimization to me..

2016-11-13 10:02 UTC, ro0NL commented
Back to 1 workflow validator and 1 state machine validator seems most intuitive to me =/

2016-11-13 12:55 UTC, HeahDude commented
You should not validate every workflows as a single place workflow, this feels wrong to me.

2016-11-13 13:19 UTC, ro0NL commented
Not sure i understand.. right now it's optin.

2016-11-13 13:29 UTC, HeahDude commented
Ok haven't look at the code yet :p

2016-11-13 13:34 UTC, HeahDude requested changes

2016-11-13 13:34 UTC, HeahDude commented on src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/ValidateWorkflowsPass.php
>          if ($tag['type'] === 'state_machine') {
Please use yoda condition

2016-11-13 13:34 UTC, HeahDude commented on src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/ValidateWorkflowsPass.php
>          } elseif ($tag['marking_store'] === 'scalar') {
`single_state`

2016-11-13 13:34 UTC, HeahDude commented on src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/ValidateWorkflowsPass.php
> +            $name = 'workflow_single_place';
You should rename this `workflow_single_state` for consistency

2016-11-13 13:34 UTC, HeahDude commented on src/Symfony/Component/Workflow/Validator/WorkflowValidator.php
> +                        sprintf(
Should be inlined

2016-11-13 13:34 UTC, HeahDude commented on src/Symfony/Component/Workflow/Validator/WorkflowValidator.php
> +                if (1 < count($transition->getTos())) {
`If (count($transition->getTos()) > 1)`

2016-11-13 13:46 UTC, ro0NL commented on src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/ValidateWorkflowsPass.php
>          } elseif ($tag['marking_store'] === 'scalar') {
That would be a bug fix right?

2016-11-13 13:48 UTC, HeahDude commented on src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/ValidateWorkflowsPass.php
>          } elseif ($tag['marking_store'] === 'scalar') {
Needed since https://github.com/symfony/symfony/commit/08464c9f2c059c5292fc9bfe991d6b74437389c9

2016-11-13 13:49 UTC, HeahDude commented on src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/ValidateWorkflowsPass.php
>          } elseif ($tag['marking_store'] === 'scalar') {
Since you already at bug fixing :)

2016-11-13 14:00 UTC, ro0NL commented on src/Symfony/Component/Workflow/Validator/WorkflowValidator.php
> +                if (1 < count($transition->getTos())) {
This was, as is, accepted before.. and is actually yoda style. Not sure we should change it now..

2016-11-13 14:00 UTC, ro0NL commented on src/Symfony/Component/Workflow/Validator/WorkflowValidator.php
> +                        sprintf(
Same.

2016-11-14 09:26 UTC, lyrixx commented on src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/ValidateWorkflowsPass.php
> +        switch ($name) {
It's a bit cumbersome to have a `if / else` then the same `switch`
And IMHO, we could remove the cache layer to make code simpler. it's a premature optimization that does not bring real perf improvement .

2016-11-14 09:27 UTC, lyrixx requested changes
One little comment, and after that I'm Ok with this PR.

2016-11-14 16:40 UTC, lyrixx approved these changes

2016-11-14 16:40 UTC, lyrixx commented
:+1: 

---

(I removed the Bug label, since it's not a bug. Could you edit your PR description?)

2016-11-14 16:54 UTC, HeahDude commented on src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/ValidateWorkflowsPass.php
> -        } elseif ($tag['marking_store'] === 'scalar') {
Actually this is a kind of bug :)

2016-11-14 17:01 UTC, lyrixx commented on src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/ValidateWorkflowsPass.php
> -        } elseif ($tag['marking_store'] === 'scalar') {
Why?

2016-11-14 17:03 UTC, HeahDude commented on src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/ValidateWorkflowsPass.php
> -        } elseif ($tag['marking_store'] === 'scalar') {
Missing from 08464c9.

2016-11-14 17:58 UTC, ro0NL commented on src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/ValidateWorkflowsPass.php
> -        } elseif ($tag['marking_store'] === 'scalar') {
Updated PR description.

2016-11-15 09:46 UTC, lyrixx commented
Good catch, thanks @ro0NL.

2016-11-15 09:47 UTC, closed without merging