Fix workflow initial place config
symfony/symfony pull request #20490
Opened 2016-11-11 15:31 UTC by HeahDude

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | https://github.com/symfony/symfony/pull/20458#issuecomment-259950141
| License       | MIT
| Doc PR        | ~

2016-11-11 16:42 UTC, xabbuh requested changes

2016-11-11 16:42 UTC, xabbuh commented on src/Symfony/Bundle/FrameworkBundle/Resources/config/schema/symfony-1.0.xsd
> +            <xsd:element name="initial_place" type="xsd:string" />
should be `<xsd:element name="initial_place" type="xsd:string" minOccurs="0" maxOccurs="1" />`

2016-11-11 16:45 UTC, HeahDude commented on src/Symfony/Bundle/FrameworkBundle/Resources/config/schema/symfony-1.0.xsd
> +            <xsd:element name="initial_place" type="xsd:string" />
Thank you fixed.

2016-11-11 16:53 UTC, xabbuh approved these changes

2016-11-11 17:05 UTC, HeahDude commented
I've also fixed the test.

2016-11-11 17:05 UTC, HeahDude commented
I've also fixed the test https://github.com/symfony/symfony/pull/20490/files#diff-aa781e95d1e8284ae37b68430bb2128bR31.

2016-11-12 09:46 UTC, xabbuh commented on src/Symfony/Component/Workflow/Validator/WorkflowValidator.php
> +        return true;
I think I tend to agree with @ro0NL that this method shouldn't return anything. Why is that method empty in the `WorkfowValidator` at all?

2016-11-12 09:53 UTC, HeahDude commented on src/Symfony/Component/Workflow/Validator/WorkflowValidator.php
> +        return true;
Ok I just remove this extra commit to keep the focus on the config fix in this PR.

2016-11-12 10:00 UTC, HeahDude commented on src/Symfony/Component/Workflow/Validator/WorkflowValidator.php
> +        return true;
Done.

2016-11-12 10:02 UTC, xabbuh commented on src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php
> +            ;
Not sure if it's really worth making this change. It makes `git blame` pretty useless when you try to figure out when a certain change was introduced without much value.

2016-11-12 11:38 UTC, stof commented on src/Symfony/Bundle/FrameworkBundle/Resources/config/schema/symfony-1.0.xsd
> +            <xsd:element name="initial_place" type="xsd:string" minOccurs="0" maxOccurs="1" />
should be an attribute, not a child tag

2016-11-12 16:18 UTC, HeahDude commented on src/Symfony/Bundle/FrameworkBundle/Resources/config/schema/symfony-1.0.xsd
> +            <xsd:element name="initial_place" type="xsd:string" minOccurs="0" maxOccurs="1" />
Fixed, thanks

2016-11-12 16:20 UTC, xabbuh commented on src/Symfony/Bundle/FrameworkBundle/Resources/config/schema/symfony-1.0.xsd
> +        <xsd:attribute name="initial_place" type="xsd:string" />
I would move it after the sequence next to the already existing attribute.

2016-11-12 16:52 UTC, HeahDude commented on src/Symfony/Bundle/FrameworkBundle/Resources/config/schema/symfony-1.0.xsd
> +        <xsd:attribute name="initial_place" type="xsd:string" />
Missed that, thanks!

2016-11-15 09:55 UTC, lyrixx requested changes

2016-11-15 09:55 UTC, lyrixx commented on src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php
> +            ;
I agree with @xabbuh

2016-11-15 09:56 UTC, lyrixx commented
@HeahDude Could you finish this one? I want to merge it asap.

2016-11-15 10:01 UTC, stof requested changes

2016-11-15 10:01 UTC, stof commented on src/Symfony/Bundle/FrameworkBundle/Resources/config/schema/symfony-1.0.xsd
> +        <xsd:attribute name="initial_place" type="xsd:string" />
the attribute name should use a dash in XML, not an underscore

2016-11-15 14:05 UTC, HeahDude commented
@lyrixx done!

2016-11-15 14:06 UTC, HeahDude commented on src/Symfony/Bundle/FrameworkBundle/Resources/config/schema/symfony-1.0.xsd
> +        <xsd:attribute name="initial_place" type="xsd:string" />
fixed

2016-11-15 14:32 UTC, lyrixx approved these changes

2016-11-15 14:32 UTC, lyrixx commented
:+1:

2016-11-15 14:33 UTC, lyrixx commented
Good catch, thanks @HeahDude.

2016-11-15 14:33 UTC, merged