[Form] Added is_empty_callback option to collection type.
symfony/symfony pull request #20496
Opened 2016-11-11 22:31 UTC by Koc

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | ?
| Fixed tickets | #13601, #13940
| License       | MIT
| Doc PR        | coming soon

2016-11-11 23:44 UTC, HeahDude requested changes
I like this, thanks for your proposal!

2016-11-11 23:44 UTC, HeahDude commented on src/Symfony/Component/Form/Extension/Core/EventListener/ResizeFormListener.php
> +                if (($child->isEmpty() || (null !== $isEmptyCallback && $isEmptyCallback($child->getData()))) && ($isNew || $this->allowDelete)) {
I would add a variable above to ease readability:
```php
/* @var $child FormInterface */
$isNew = !isset($previousData[$name]);
$isEmpty = $child->isEmpty() || (null !== $isEmptyCallback && $isEmptyCallback($child->getData());

// $isNew can only be true if allowAdd is true, so we don't
// need to check allowAdd again
if ($isEmpty && ($isNew || $this->allowDelete)) {

2016-11-11 23:44 UTC, HeahDude commented on src/Symfony/Component/Form/Extension/Core/Type/CollectionType.php
> +            'is_empty_callback' => null,
Please add:
```php
$resolver->setAllowedTypes('is_empty_callback', array('null', 'callable'));
```

2016-11-12 10:55 UTC, Koc commented
@HeahDude done. Also I've changed the test to better description of this new feature.

2016-12-26 10:50 UTC, Koc commented
can anybody review and merge?

2016-12-26 11:04 UTC, HeahDude commented
Some may have some concern about the naming of this option, for me it's a 👍

Status: Reviewed

2017-02-08 11:21 UTC, xabbuh commented
I agree with the implementation, but the option name doesn't sound good. For example, we don't check if the whole collection is empty, but only check for each submitted entry if it should be ignored. Can we think of a better name?

2017-02-08 11:29 UTC, Koc commented
give some examples of a better name, I'll rename it

2017-02-08 17:01 UTC, xabbuh commented
What about something like `filter_entry` as we are basically filter our collection entries inside the callback?

2017-03-17 03:25 UTC, murilolobato commented
If `is_empty_callback` is a option, I would rename it to just `is_empty`.

2017-03-22 17:57 UTC, fabpot commented
@Koc What about @xabbuh suggestion for the name?

2017-03-23 11:26 UTC, Koc commented
@fabpot done, except I prefer `entry_filter` to be consistent with other options like `entry_type`/`entry_options`. Callable should return true for leave entry in collection.

Test failure is unrelated.

2017-03-23 16:01 UTC, yceruto commented
IMHO, the option should be the same `delete_empty`, accepting bool or callable. Use `true` to delete (non-compound) empty entries, and use a callable function to delete (compound with or without `data_class`) empty entries like `Author(null)` or `array('firstName' => '')`.

In case of compound entries with `data_class`:
```
'delete_empty' => function (Author $obj = null) {
    return null === $obj || empty($obj->firstName);
},
```
In case of compound entries without `data_class`:
```
'delete_empty' => function ($data) {
    return empty($data['firstName']);
},
```
Thus, we avoid problem to use a new option `entry_filter` (learning curve!!) which depends of `delete_empty = true` also.

2017-03-23 16:14 UTC, murilolobato commented
When the property gets renamed, I can add the test I've made in #22014

2017-03-23 16:28 UTC, yceruto commented on src/Symfony/Component/Form/Extension/Core/EventListener/ResizeFormListener.php
> +                $needRemove = $child->isEmpty() || (null !== $entryFilter && !$entryFilter($child->getData()));
It is about whether the child form/data is empty or not, so the previous name `isEmpty` sounds better IMO ;)

2017-03-23 20:47 UTC, Koc commented
@yceruto interesting idea, will implement it tomorrow

2017-03-24 12:34 UTC, yceruto commented on src/Symfony/Component/Form/Extension/Core/EventListener/ResizeFormListener.php
> +                $isEmpty = $child->isEmpty() || true === $entryFilter($child->getData());
The `$entryFilter` and the empty closure function looks a bit overkill, can be simplified to:
```
$isEmpty = $child->isEmpty() || (is_callable($this->deleteEmpty) && true === $this->deleteEmpty($child->getData());
```

2017-03-24 12:56 UTC, yceruto commented on src/Symfony/Component/Form/Tests/Extension/Core/Type/CollectionTypeTest.php
> +        $this->assertEquals(array('s_first', 's_last'), $form[0]->getData());
Missing keys https://travis-ci.org/symfony/symfony/jobs/214628660#L3215

2017-04-09 13:11 UTC, HeahDude commented on src/Symfony/Component/Form/Extension/Core/EventListener/ResizeFormListener.php
> +                /* @var $child FormInterface */
This change should not be done in master.

2017-04-09 20:05 UTC, Koc commented on src/Symfony/Component/Form/Extension/Core/EventListener/ResizeFormListener.php
> +                /* @var $child FormInterface */
why not? it improves autocomplete

2017-04-09 21:24 UTC, Koc commented on src/Symfony/Component/Form/Tests/Extension/Core/Type/CollectionTypeTest.php
> +        $this->assertEquals(array('s_first', 's_last'), $form[0]->getData());
fixed

2017-04-09 21:24 UTC, Koc commented on src/Symfony/Component/Form/Extension/Core/EventListener/ResizeFormListener.php
> +                $isEmpty = $child->isEmpty() || true === $entryFilter($child->getData());
changed

2017-04-09 21:51 UTC, HeahDude commented on src/Symfony/Component/Form/Extension/Core/EventListener/ResizeFormListener.php
> +                /* @var $child FormInterface */
Because this should target 2.7 :)

2017-06-04 20:25 UTC, yceruto commented
Should be rebased to 3.4 branch?

2017-07-23 00:09 UTC, Koc commented
@yceruto done
@ogizanagi please review

2017-07-23 09:30 UTC, Koc commented on src/Symfony/Component/Form/Extension/Core/EventListener/ResizeFormListener.php
> +                $isEmpty = $child->isEmpty() || (is_callable($entryFilter) && true === $entryFilter($child->getData()));
imho not. It will force us to duplicate standard checks inside callables

2017-07-23 09:40 UTC, ogizanagi commented on src/Symfony/Component/Form/Extension/Core/EventListener/ResizeFormListener.php
> +                $isEmpty = $child->isEmpty() || (is_callable($entryFilter) && true === $entryFilter($child->getData()));
I'm not convinced you need those standard checks to be run anyway. For instance, you'll already have to check for the data not being null inside your callable before further checks.

2017-07-23 09:43 UTC, Koc commented on src/Symfony/Component/Form/Extension/Core/EventListener/ResizeFormListener.php
> +                /* @var $child FormInterface */
ok, will open PR for that. Where can I find information about standards for inline `@var` phpdoc?

2017-07-23 09:54 UTC, ogizanagi commented on src/Symfony/Component/Form/Extension/Core/EventListener/ResizeFormListener.php
> +                /* @var $child FormInterface */
See PSR-5: https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc.md#3-definitions

About the foreach, though:

> This Standard does not cover this specific instance as a foreach statement is not considered to be a "Structural Element" but a Control Flow statement.

but still:

> It is RECOMMENDED to precede a "Structural Element" with a DocBlock where it is defined and not with each usage.

2017-07-23 09:56 UTC, Koc commented
@ogizanagi updated

2017-07-23 10:09 UTC, Koc commented
@ogizanagi updated again :), now all green

2017-07-23 10:27 UTC, ogizanagi approved these changes

2017-07-23 23:24 UTC, yceruto commented on src/Symfony/Component/Form/Extension/Core/EventListener/ResizeFormListener.php
> +        if ($entryFilter = $this->deleteEmpty) {
I guess `$entryFilter` can be removed?

2017-07-24 05:49 UTC, Koc commented on src/Symfony/Component/Form/Extension/Core/EventListener/ResizeFormListener.php
> +        if ($entryFilter = $this->deleteEmpty) {
Why? This variable uses some lines bottom

2017-07-24 12:24 UTC, yceruto commented on src/Symfony/Component/Form/Extension/Core/EventListener/ResizeFormListener.php
> +        if ($entryFilter = $this->deleteEmpty) {
Yep, but why not use `$this->deleteEmpty` directly? IMHO `$this->deleteEmpty($child->getData())` is quite easy to understand too.

2017-07-24 12:25 UTC, Koc commented on src/Symfony/Component/Form/Extension/Core/EventListener/ResizeFormListener.php
> +        if ($entryFilter = $this->deleteEmpty) {
because `$this->deleteEmpty()` will call undefined method `ResizeFormListener::deleteEmpty()`

2017-07-24 12:29 UTC, ogizanagi commented on src/Symfony/Component/Form/Extension/Core/EventListener/ResizeFormListener.php
> +        if ($entryFilter = $this->deleteEmpty) {
and `($this->deleteEmpty)()` is only doable in PHP 7.0+

2017-07-24 12:59 UTC, yceruto commented on src/Symfony/Component/Form/Extension/Core/EventListener/ResizeFormListener.php
> +        if ($entryFilter = $this->deleteEmpty) {
Yep, my bad ;)

2017-07-24 13:01 UTC, yceruto commented on src/Symfony/Component/Form/Extension/Core/EventListener/ResizeFormListener.php
> +        if ($entryFilter = $this->deleteEmpty) {
Yep, my bad ;)

2017-07-24 13:02 UTC, yceruto approved these changes

2017-07-25 06:41 UTC, xabbuh approved these changes

2017-07-26 06:57 UTC, fabpot commented
Thank you @Koc.

2017-07-26 06:57 UTC, merged

2017-07-26 06:57 UTC, fabpot commented
@Koc Can you submit a pull request to update the docs? Thank you