[Workflow] Minor fix workflow
symfony/symfony pull request #20507
Opened 2016-11-13 18:48 UTC by HeahDude

| Q             | A
| ------------- | ---
| Branch?       | 3.2
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | ~
| License       | MIT
| Doc PR        | ~

Some tests are run twice because the `SinglePlaceWorkflowValidatorTest` extends the `WorkflowTest`, let's use a static function instead.

2016-11-13 19:06 UTC, ro0NL commented on src/Symfony/Component/Workflow/Tests/Validator/SinglePlaceWorkflowValidatorTest.php
> +        $definition = WorkflowTest::createComplexWorkflow();
Maybe just create a minimal workflow here. I thought of this as well for #20492 but i forgot :))

2016-11-14 09:32 UTC, lyrixx requested changes

2016-11-14 09:32 UTC, lyrixx commented on src/Symfony/Component/Workflow/Tests/Validator/SinglePlaceWorkflowValidatorTest.php
> +        $definition = WorkflowTest::createComplexWorkflow();
:+1:

2016-11-15 09:54 UTC, lyrixx commented
@HeahDude Could you take time to finish this one, I wan to merge it asap

2016-11-17 10:12 UTC, lyrixx commented
Closing in favor of #20548

2016-11-17 10:12 UTC, closed without merging