[Serializer][XmlEncoder] Allow removing empty tags in generated XML
symfony/symfony pull request #20524
Opened 2016-11-15 08:42 UTC by amoiraud

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #20398 
| License       | MIT
| Doc PR        | ~

Allow a new option in $context of XmlEncoder.php to remove empty tags if $context['remove_empty_tags'] setted to true, changing this : 

```xml
    <node>
         <subnode>Value</subnode>
         <emptysubnode/>
    </node>
```

To this :

```xml
    <node>
         <subnode>Value</subnode>
    </node>
```

2016-11-15 11:42 UTC, xabbuh requested changes

2016-11-15 11:42 UTC, xabbuh commented on src/Symfony/Component/Serializer/Encoder/XmlEncoder.php
> +                    if ($data !== null || !isset($this->context['remove_empty_tags']) || $this->context['remove_empty_tags'] === false) {
should be `elseif`

2016-11-15 11:42 UTC, xabbuh commented on src/Symfony/Component/Serializer/Encoder/XmlEncoder.php
> +                    if ($data !== null || !isset($this->context['remove_empty_tags']) || $this->context['remove_empty_tags'] === false) {
and please also use a Yoda condition here: `null !== $data`

2016-11-15 12:41 UTC, amoiraud commented on src/Symfony/Component/Serializer/Encoder/XmlEncoder.php
> +                    if ($data !== null || !isset($this->context['remove_empty_tags']) || $this->context['remove_empty_tags'] === false) {
It's done :

```php
} elseif (null !== $data || !isset($this->context['remove_empty_tags']) || false === $this->context['remove_empty_tags']) {
    $append = $this->appendNode($parentNode, $data, $key);
}
```

2016-11-15 13:13 UTC, xabbuh approved these changes

2016-11-15 21:49 UTC, dunglas commented on src/Symfony/Component/Serializer/Tests/Encoder/XmlEncoderTest.php
> +        $context = array(
Can be inline

2016-11-15 21:49 UTC, dunglas commented
👍

2016-12-06 11:14 UTC, dunglas commented
Can you open a doc PR please @amoiraud

2016-12-06 12:58 UTC, dunglas commented
Thank you @amoiraud.

2016-12-06 13:00 UTC, closed without merging

2016-12-07 05:47 UTC, dunglas commented
@amoiraud, I suggest to add a new section about the XmlEncoder in https://github.com/symfony/symfony-docs/blob/master/components/serializer.rst and list its available options.