[FrameworkBundle] Use stderr when relevant in commands
symfony/symfony pull request #20586
Opened 2016-11-21 21:39 UTC by chalasr

| Q             | A
| ------------- | ---
| Branch?       | 2.8
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | n/a

Related to #15986

2016-11-21 23:55 UTC, fabpot commented
Can't be in 2.8, should be in master

2016-11-22 10:07 UTC, chalasr commented
Changed the scope then, proposing `SymfonyStyle::getErrorIo()` to ease writing to stderr using styles (feature), and secondly made built-in commands using it when it's relevant. Let me know if it should be done in two PRs.

2016-11-25 10:21 UTC, nicolas-grekas commented
@chalasr you decide :)

2016-11-25 10:24 UTC, stof commented
Even adding a new method must be in master, as it is a new feature

2016-11-25 10:25 UTC, stof requested changes

2016-11-25 10:25 UTC, stof commented on src/Symfony/Bundle/FrameworkBundle/Command/ConfigDebugCommand.php
> +            $errorIo->comment('For dumping a specific option, add its path as the second argument of this command. (e.g. <comment>debug:config FrameworkBundle serializer</comment> to dump the <commen
removing the return is broken

2016-11-25 11:02 UTC, chalasr commented
@stof It was about proposing the new method here and fixing the existing commands in another PR by creating the instance of `SymfonyStyle` in the commands themselves. see #20632

2016-11-25 11:02 UTC, chalasr commented on src/Symfony/Bundle/FrameworkBundle/Command/ConfigDebugCommand.php
> +            $errorIo->comment('For dumping a specific option, add its path as the second argument of this command. (e.g. <comment>debug:config FrameworkBundle serializer</comment> to dump the <commen
👍  fixed in #20632

2016-11-25 13:38 UTC, chalasr commented on src/Symfony/Component/Console/Tests/Style/SymfonyStyleTest.php
> +        $input = $this->getMock('Symfony\Component\Console\Input\InputInterface');
thanks, fixed

2016-12-13 09:10 UTC, fabpot commented on src/Symfony/Component/Console/Style/SymfonyStyle.php
> +    public function getErrorIo()
The method name looks weird to me as we don't use IO anywhere in the code IIRC

2016-12-13 09:55 UTC, chalasr commented on src/Symfony/Component/Console/Style/SymfonyStyle.php
> +    public function getErrorIo()
I agree. `getErrorStyle()` ?

2016-12-13 10:19 UTC, chalasr commented on src/Symfony/Component/Console/Style/SymfonyStyle.php
> +    public function getErrorIo()
Changed to `getErrorStyle()`

2016-12-13 12:25 UTC, chalasr commented on src/Symfony/Bundle/FrameworkBundle/Command/ConfigDebugCommand.php
> +            $errorIo->comment('For dumping a specific option, add its path as the second argument of this command. (e.g. <comment>debug:config FrameworkBundle serializer</comment> to dump the <commen
Could you please dismiss your review? As the change is no more in this PR

2017-01-06 14:02 UTC, nicolas-grekas commented on src/Symfony/Component/Console/Style/OutputStyle.php
> +            return;
should it throw instead?

2017-01-06 15:22 UTC, fabpot commented on src/Symfony/Component/Console/Style/OutputStyle.php
> +            throw new LogicException(sprintf('The output must be an instance of %s for using getErrorOutput().', ConsoleOutputInterface::class));
What about returning the regular output instead?

2017-01-06 16:45 UTC, chalasr commented on src/Symfony/Component/Console/Style/OutputStyle.php
> +            throw new LogicException(sprintf('The output must be an instance of %s for using getErrorOutput().', ConsoleOutputInterface::class));
Agreed, updated

2017-01-06 20:48 UTC, fabpot commented
Thank you @chalasr.

2017-01-06 20:48 UTC, merged