Remove unused GetSetMethodNormalizer::denormalize
symfony/symfony pull request #20623
Opened 2016-11-24 18:40 UTC by dunglas

| Q             | A
| ------------- | ---
| Branch?       | 3.1
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | n/a

2016-11-25 10:04 UTC, nicolas-grekas commented
:+1:

2016-11-25 10:07 UTC, stof commented
Are you sure about this ?

2016-11-25 10:07 UTC, nicolas-grekas commented
Here is the patch for this method comparing it to its parent implem.
Do you mean that this difference is useless and the parent implem is good enough?
```diff
     public function denormalize($data, $class, $format = null, array $context = array())
     {
-        if (!isset($context['cache_key'])) {
-            $context['cache_key'] = $this->getCacheKey($format, $context);
-        }
         $allowedAttributes = $this->getAllowedAttributes($class, $context, true);
         $normalizedData = $this->prepareForDenormalization($data);
 
         $reflectionClass = new \ReflectionClass($class);
         $object = $this->instantiateObject($normalizedData, $class, $context, $reflectionClass, $allowedAttributes);
 
+        $classMethods = get_class_methods($object);
         foreach ($normalizedData as $attribute => $value) {
             if ($this->nameConverter) {
                 $attribute = $this->nameConverter->denormalize($attribute);
             }
 
-            if (($allowedAttributes !== false && !in_array($attribute, $allowedAttributes)) || !$this->isAllowedAttribute($class, $attribute, $format, $context)) {
-                continue;
-            }
+            $allowed = $allowedAttributes === false || in_array($attribute, $allowedAttributes);
+            $ignored = in_array($attribute, $this->ignoredAttributes);
+
+            if ($allowed && !$ignored) {
+                $setter = 'set'.ucfirst($attribute);
 
-            $value = $this->validateAndDenormalize($class, $attribute, $value, $format, $context);
-            try {
-                $this->setAttributeValue($object, $attribute, $value, $format, $context);
-            } catch (InvalidArgumentException $e) {
-                throw new UnexpectedValueException($e->getMessage(), $e->getCode(), $e);
+                if (in_array($setter, $classMethods) && !$reflectionClass->getMethod($setter)->isStatic()) {
+                    $object->$setter($value);
+                }
             }
         }
```

2016-11-25 10:24 UTC, dunglas commented
@nicolas-grekas @stof In fact the parent method is better because it contains cache and validation. This methods deactivate cache and validation and IMO should be removed.

2016-11-28 05:55 UTC, xabbuh requested changes

2016-11-28 05:55 UTC, xabbuh commented on src/Symfony/Component/Serializer/Normalizer/GetSetMethodNormalizer.php
> -            $ignored = in_array($attribute, $this->ignoredAttributes);
If I didn't miss anything, ignored attributes will now no longer be ignored anymore.

2016-11-28 09:03 UTC, dunglas commented on src/Symfony/Component/Serializer/Normalizer/GetSetMethodNormalizer.php
> -            $ignored = in_array($attribute, $this->ignoredAttributes);
It's handled here: https://github.com/dunglas/symfony/blob/0896b02be073b8fa60fe6e8b3cf5d4f81b748bf8/src/Symfony/Component/Serializer/Normalizer/AbstractNormalizer.php#L217

2016-11-28 09:07 UTC, xabbuh commented on src/Symfony/Component/Serializer/Normalizer/GetSetMethodNormalizer.php
> -            $ignored = in_array($attribute, $this->ignoredAttributes);
thx

2016-11-28 09:07 UTC, xabbuh approved these changes

2016-11-28 09:25 UTC, theofidry commented
@dunglas whilst I agree with the removal of the PR wouldn't that break Sf BC break policy as a user may potentially extend this serializer and use this method? Wouldn't it be better to just deprecate it for now?

2016-11-28 09:28 UTC, xabbuh commented
@theofidry The method is still there (it's defined by the `AbstractObjectNormalizer`).

2016-11-28 09:29 UTC, theofidry commented
Fair, 👍 then

2016-11-29 08:09 UTC, fabpot commented
Thank you @dunglas.

2016-11-29 08:10 UTC, merged