DoctrineDataCollector: taught sanitizeParam to support classes with __toString implemented.
symfony/symfony pull request #20680
Opened 2016-11-29 11:18 UTC by FractalizeR

This PR teaches \Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCollector::sanitizeParam support objects, which implement __toString and therefore can be represented as a string with more sense, than "(object) ClassName". It also includes test for the feature.

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | [20673](https://github.com/symfony/symfony/issues/20673)
| License       | MIT
| Doc PR        | no

2016-12-01 19:44 UTC, nicolas-grekas commented
I think we need to dump the class name all the time. At least this is what Monolog does in this case:
https://github.com/Seldaek/monolog/blob/master/src/Monolog/Formatter/NormalizerFormatter.php#L101-L120

2016-12-02 07:56 UTC, FractalizeRMoby commented
Monolog in that source does both. It uses class name as a key, and `__toString()` call result as a value.

2016-12-02 08:15 UTC, FractalizeR commented
Monolog in that source does both. It uses class name as a key, and __toString() call result as a value.

2016-12-06 12:42 UTC, nicolas-grekas commented
@FractalizeR that's what I meant :) And I think that's wise.

2016-12-24 12:50 UTC, xabbuh requested changes

2016-12-24 12:50 UTC, xabbuh commented on src/Symfony/Bridge/Doctrine/DataCollector/DoctrineDataCollector.php
> +                array($var->__toString(), false) :
I agree that the class name should be dumped here as well. The way it is implemented will cause confusing results.

2017-02-16 14:21 UTC, fabpot commented
What's the status of this PR?

2017-03-01 15:44 UTC, fabpot commented
@FractalizeR Any news? Are still interested in finishing this PR?

2017-03-01 15:59 UTC, FractalizeR commented
Yeah, sure. But I am at lost who makes a decision about how this PR should really look like. I'm ready to make desired modifications, but someone responsible needs to tell me what needs to be adjusted.

2017-03-01 16:05 UTC, fabpot commented
I think we all agree that we need to keep the class name, even when there is a string representation.

2017-03-01 17:21 UTC, FractalizeR commented
Can we, then, use the following representation for objects, implementing `__toString()`

```
(object) className: '__toString() return result'
```
?

2017-03-01 17:30 UTC, fabpot commented
@FractalizeR I think that makes sense.

2017-03-02 09:06 UTC, FractalizeR commented
Done. Some tests fail, but this is not due my PR, but several other components. Looks like some PR was merged without ensuring tests pass.

2017-03-02 16:09 UTC, fabpot commented on src/Symfony/Bridge/Doctrine/Tests/DataCollector/StringRepresentableClass.php
> +        return $this->representation;
Can we simplify this class by removing the `representation` property and hardcode the text here directly?

2017-03-02 18:23 UTC, fabpot commented
Thank you @FractalizeR.

2017-03-02 18:23 UTC, closed without merging

2017-03-02 18:25 UTC, fabpot commented on src/Symfony/Bridge/Doctrine/Tests/DataCollector/StringRepresentableClass.php
> +        return $this->representation;
see 26c54c700b