fix - #20685: add class name to the cache key
symfony/symfony pull request #20745
Opened 2016-12-03 15:45 UTC by Simperfit

| Q             | A
| ------------- | ---
| Branch?       | 3.1
| Bug fix?      | yes
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets |  #20685 
| License       | MIT
| Doc PR        | 

Adding the class name to the cache key to avoid collision

2016-12-06 08:29 UTC, dunglas requested changes
Can you also add a test with a relation between ChildA and ChilB?

2016-12-08 13:12 UTC, dunglas approved these changes

2016-12-08 13:12 UTC, dunglas commented
👍

2016-12-08 13:26 UTC, stof commented on src/Symfony/Component/Validator/Tests/Fixtures/Entity.php
> -
this line should be kept

2016-12-08 13:41 UTC, Simperfit commented on src/Symfony/Component/Validator/Tests/Fixtures/Entity.php
> -
👍

2016-12-08 15:05 UTC, nicolas-grekas commented
Thank you @Simperfit.

2016-12-08 15:05 UTC, closed without merging