[FrameworkBundle] Allow multiple transactions with the same name
symfony/symfony pull request #20795
Opened 2016-12-06 19:05 UTC by Padam87

| Q             | A
| ------------- | ---
| Branch?       |  3.2
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #20794
| License       | MIT
| Doc PR        | -

I will add xml and php mapping if it is otherwise ok.

2016-12-07 08:45 UTC, xabbuh commented on src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php
> +                $transitionName = $transition['name'] ?: $transitionName;
I think we should normalise the values in the `Configuration` class already to ensure that an element with the `name` key is set.

2016-12-13 09:57 UTC, nicolas-grekas commented
ping @lyrixx

2016-12-13 14:58 UTC, lyrixx requested changes

2016-12-13 14:58 UTC, lyrixx commented on src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php
> +                                        ->scalarNode('name')->defaultNull()->end()
```
->scalarNode('name')
    ->isRequired()
    ->cannotBeEmpty()
->end()
```

2016-12-13 14:58 UTC, lyrixx commented on src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php
> +                                ->validate()
```
->beforeNormalization()
    ->always()
    ->then(function ($transitions) {
        // It's an indexed array, we let the validation occurs
        if (isset($transitions[0])) {
            return $transitions;
        }

        foreach ($transitions as $name => $transition) {
            $transition['name'] = $name;
            $transitions[$name] = $transition;
        }

        return $transitions;
    })
->end()
```

2016-12-13 15:03 UTC, lyrixx commented
Hello @Padam87 

Thanks for your PR. I added 2 comments about the code. Could you please update your code with my patch?

2016-12-13 15:04 UTC, stof commented
We should still validate that you don't have 2 transitions with the same name and a common from node though.

2016-12-13 15:06 UTC, lyrixx commented
> We should still validate that you don't have 2 transitions with the same name 

Yes, indedd

> and a common from node though.

Why? it's possible to have 2 transitions, with the same "from" name.

2016-12-13 15:12 UTC, stof commented
@lyrixx your ``Yes indeed`` being in the middle of the ``and`` qualifying transitions makes me think that you misunderstood my comment entirely (your ``Yes indeed`` looks like you want to forbid exactly what this PR is about allowing to configure)

2016-12-13 15:17 UTC, lyrixx commented
Oups, yes, you are right ;) Sorry.

2016-12-13 15:18 UTC, lyrixx commented
But i'm not sure we should validate the "name + from" here. It should be done in the symfony/component validator instead.

2016-12-13 15:35 UTC, stof commented
@lyrixx it indeed must be done in the workflow validator.
But it would not be bad to have an early validation in the DI class if it is easy to do (forbidding to configure an invalid workflow which would fail only later on). Validation during the compile time of the container would give early feedback without performance impact at runtime (as it happens at build time).

2016-12-13 15:45 UTC, lyrixx commented
@stof All validations are already done in a compiler pass ;)

2016-12-13 16:03 UTC, stof commented
then fine. I forgot that

2016-12-26 18:51 UTC, lyrixx commented
Hello @Padam87

I'm sorry, I totally forgot this PR because it was not tagged with `Workflow`.

Thanks for this PR!

:+1:

2016-12-26 20:42 UTC, fabpot commented
Thank you @Padam87.

2016-12-26 20:42 UTC, merged