[Console] improved code coverage for class Command
symfony/symfony pull request #20817
Opened 2016-12-07 14:52 UTC by ShinDarth

| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| License       | MIT

2016-12-10 12:41 UTC, Simperfit requested changes

2016-12-10 12:41 UTC, Simperfit commented on src/Symfony/Component/Console/Tests/Command/CommandTest.php
> +        $this->expectException(\InvalidArgumentException::class);
This is not possible in PHP 5.3 you should use the FQCN.

2016-12-15 13:12 UTC, stof commented on src/Symfony/Component/Console/Tests/Command/CommandTest.php
> +        $this->expectException(\InvalidArgumentException::class);
Well, ``InvalidArgumentException``

2016-12-17 15:48 UTC, ShinDarth commented on src/Symfony/Component/Console/Tests/Command/CommandTest.php
> +        $this->expectException(\InvalidArgumentException::class);
any clue?

2016-12-18 18:57 UTC, ShinDarth commented
@stof all good now, I guess it's ready to be merged.

2016-12-20 10:26 UTC, linaori approved these changes

2016-12-23 20:36 UTC, closed without merging