[HttpFoundation] Validate/cast cookie expire time
symfony/symfony pull request #20925
Opened 2016-12-14 18:41 UTC by ro0NL

| Q             | A
| ------------- | ---
| Branch?       | master 
| Bug fix?      | not sure
| New feature?  | not sure
| BC breaks?    | not sure :)
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #... 
| License       | MIT
| Doc PR        | symfony/symfony-docs#...

2016-12-15 07:43 UTC, fabpot commented on src/Symfony/Component/HttpFoundation/Cookie.php
> -            if (false === $expire || -1 === $expire) {
:+1: `-1` was returned by `strtotime` on PHP 5.1

2016-12-15 08:14 UTC, ro0NL commented on src/Symfony/Component/HttpFoundation/Cookie.php
> -            if (false === $expire || -1 === $expire) {
Prior to 5.1.0 actually ;)

2016-12-17 19:53 UTC, ro0NL commented
Failing test unrelated.

2016-12-24 12:48 UTC, xabbuh requested changes

2016-12-24 12:48 UTC, xabbuh commented on src/Symfony/Component/HttpFoundation/Tests/CookieTest.php
> +    public function testGetExpiresTimeIsCastedToInt()
`testGetExpiresTimeIsCastToInt`

2016-12-24 12:48 UTC, xabbuh commented on src/Symfony/Component/HttpFoundation/Tests/CookieTest.php
> +        $this->assertEquals(3600, $cookie->getExpiresTime(), '->getExpiresTime() returns the expire date as an integer');
`assertSame`

2016-12-24 12:54 UTC, ro0NL commented on src/Symfony/Component/HttpFoundation/Tests/CookieTest.php
> +        $this->assertEquals(3600, $cookie->getExpiresTime(), '->getExpiresTime() returns the expire date as an integer');
Nice catch!

2016-12-27 14:19 UTC, nicolas-grekas commented on src/Symfony/Component/HttpFoundation/Cookie.php
> +            throw new \InvalidArgumentException('The cookie expiration time must be a positive number value.');
This is a bc break if anyone is doing this for some reason.
We could deprecate, but the behavior is just fine when negative numbers are used here.
Instead, I'd rather fix getMaxAge and turn `0 !== $this->expire` into `0 >= $this->expire`.
and merge this in a lower branch

2016-12-27 14:46 UTC, ro0NL commented on src/Symfony/Component/HttpFoundation/Cookie.php
> +            throw new \InvalidArgumentException('The cookie expiration time must be a positive number value.');
I think we should indeed settle with `>=`. Nice one.. didnt thought of it :+1:

2016-12-28 08:26 UTC, nicolas-grekas commented
:+1:

2016-12-28 08:35 UTC, javiereguiluz commented on src/Symfony/Component/HttpFoundation/Cookie.php
> +        $this->expire = 0 < $expire ? (int) $expire : 0;
`$this->expire = max(0, (int) $expire)`  ?

2016-12-29 12:54 UTC, ro0NL commented on src/Symfony/Component/HttpFoundation/Cookie.php
> +        $this->expire = 0 < $expire ? (int) $expire : 0;
Not sure the extra function call is really worth it. Tend to keep it as is.

2017-01-03 03:24 UTC, fabpot commented
Thank you @ro0NL.

2017-01-03 03:24 UTC, merged