Add missing upgrade path for Request::isMethodSafe() deprecation
symfony/symfony pull request #20994
Opened 2016-12-19 22:29 UTC by chalasr

| Q             | A
| ------------- | ---
| Branch?       | 3.2

2016-12-19 22:42 UTC, xabbuh requested changes
We need to update the upgrade guide for 4.0 too.

2016-12-19 22:49 UTC, chalasr commented
@xabbuh done

2016-12-19 22:50 UTC, xabbuh requested changes

2016-12-19 22:50 UTC, xabbuh commented on UPGRADE-4.0.md
> +   not supported anymore and throws an exception. Disable checking only for cacheable methods
It won't throw an exception. It will simply return `false`.

2016-12-19 22:55 UTC, chalasr commented on UPGRADE-4.0.md
> +   not supported anymore and throws an exception. Disable checking only for cacheable methods
It is what the deprecation warning says: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Request.php#L1506
Should we change it?

2016-12-19 23:17 UTC, xabbuh commented on UPGRADE-4.0.md
> +   not supported anymore and throws an exception. Disable checking only for cacheable methods
I think that comment refers to passing `true` to the method.

2016-12-19 23:22 UTC, chalasr commented on UPGRADE-4.0.md
> +   not supported anymore and throws an exception. Disable checking only for cacheable methods
I thought the argument would be uncommented as is so the exception would be thrown when omitting to pass the argument to `false` explicitly.

2016-12-19 23:26 UTC, chalasr commented on UPGRADE-4.0.md
> +   not supported anymore and throws an exception. Disable checking only for cacheable methods
updated

2016-12-20 04:14 UTC, fabpot commented
Thank you @chalasr.

2016-12-20 04:14 UTC, merged