[Cache] remove is_writable check on filesystem cache
symfony/symfony pull request #21025
Opened 2016-12-22 13:45 UTC by 4rthem

| Q             | A
| ------------- | ---
| Branch?       | 3.1
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #21024 
| License       | MIT
| Doc PR        | -

* Use 755 mode for directories creation
* Remove `is_writable` check in FilesystemAdapter to avoid exception on read-only filesystems

2016-12-22 13:53 UTC, nicolas-grekas requested changes
when `file_put_content` fails (see https://github.com/symfony/symfony/pull/21025/files#diff-fe14fffdd6799f339b2daf1045d09360R133)
we should report more info. In the else block, I think we should call error_get_last and use the message there to throw a CacheException (the AbstractAdapter will deal with it properly).

2016-12-22 13:53 UTC, nicolas-grekas commented on src/Symfony/Component/Cache/Adapter/FilesystemAdapter.php
> +            @mkdir($directory, 0755, true);
This should be reverted: the complete code bases uses 777 when calling mkdir.

2016-12-22 13:53 UTC, nicolas-grekas commented on src/Symfony/Component/Cache/Adapter/FilesystemAdapter.php
> +            @mkdir($dir, 0755, true);
revert

2016-12-23 12:02 UTC, 4rthem commented
OK but currently, the `doSave` method iterates over all the values to save, even if one fails. It's only at the end that we have `return $ok;`.

Adding an exception in this method will conflict with the boolean return IMO.
We should either throw an exception at the first fail or analyze why `file_put_contents` or `rename` has failed. Maybe an `is_writable` call if `$ok` is false?

```php
// Symfony\Component\Cache\Adapter\FilesystemAdapter::doSave
if (!$ok && !is_writable($this->directory)) {
    throw new CacheException(sprintf('Cache directory is not writable (%s)', $this->directory));
}
```

2016-12-23 13:26 UTC, nicolas-grekas commented
True concern, and AbstractAdapter already has the required logic to do what you say: it retries saving each key individually when batch save fails.

2016-12-28 08:23 UTC, nicolas-grekas commented
Thank you @4rthem.

2016-12-28 08:23 UTC, merged