[FrameworkBundle][Monolog] Added a new way to follow logs
symfony/symfony pull request #21080
Opened 2016-12-28 15:53 UTC by lyrixx

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

----

If you want to try this PR, you can use [my fork](https://github.com/lyrixx/symfony-standard/tree/server-log):
```bash
git clone https://github.com/lyrixx/symfony-standard -b server-log symfony-se-logs
cd symfony-se-logs
composer install
bin/console server:start
bin/console server:log
```
and from anywhere `curl http://0:8000`

---

Basically, it's a new way to view and filter real time logs, from the CLI.

![screenshot12](https://cloud.githubusercontent.com/assets/408368/21525512/15a9ef1e-cd1e-11e6-9860-aad98e063a0f.png)

2016-12-28 17:06 UTC, yceruto commented
:+1: Thanks you for this awesome feature! `--filter <expresion language>` :astonished: !!

Just a minor fix in your description to try this PR correctly, because [`server_log` handler is configured into `config_dev.yml`](https://github.com/lyrixx/symfony-standard/blob/server-log/app/config/config_dev.yml#L21) we need to run `curl http://0:8000/app_dev.php/` to see the output ;)

2016-12-28 18:08 UTC, lyrixx commented
@yceruto By default, `bin/console` use the `dev` env. So the server is in `dev` env by default. That's why I did not add `/app_dev.php`, because it should not be necessary.

2016-12-28 18:58 UTC, yceruto commented
>@yceruto By default, bin/console use the dev env. So the server is in dev env by default. That's why I did not add /app_dev.php, because it should not be necessary.

Right, but when you run `curl http://127.0.0.1:8000/` we are in prod env right? the handler is not there and the `server:log` doesn't shows nothing.

I missing something :/ ?

2016-12-28 18:59 UTC, maidmaid commented on src/Symfony/Bundle/FrameworkBundle/Command/ServerLogCommand.php
> +            if ($filter && !$this->el->evaluate($filter, ['record' => $record])) {
What about evaluate directly ``$record`` with ``->evaluate($filter, $record)``? ``filter`` option becomes easier to use: from ``--filter "record['level'] > 200"`` to ``--filter "level > 200"``

2016-12-28 19:14 UTC, yceruto commented
> Right, but when you run curl http://127.0.0.1:8000/ we are in prod env right?

Nevermind, I forgot my env var in prod by default, sorry for the noise. This works as it is!

2016-12-28 23:37 UTC, robfrawley requested changes
You missed a bunch of short-array syntax instances. ;-) Thanks for this feature, though!

2016-12-29 08:44 UTC, hhamon commented
Very nice feature!

2017-01-06 09:49 UTC, lyrixx commented
@fabpot Should I move this command to the new server bundle?

2017-01-10 17:23 UTC, jakzal commented on src/Symfony/Bundle/FrameworkBundle/Command/ServerLogCommand.php
> +        $this->el = new ExpressionLanguage();
This property doesn't exist.

2017-01-10 22:32 UTC, fabpot commented
@lyrixx Indeed, it should be moved to the new web server bundle.

2017-01-12 16:29 UTC, lyrixx commented
I moved the command to the WebServerBundle.

2017-01-15 08:17 UTC, xabbuh commented
The `ServerLogCommand` on one side and the `VarDumperFormatter` and `ServerLogHandler` on the other side are not wired. Is that intended? Wouldn't it be better to split this in two PRs then?

2017-01-18 10:02 UTC, lyrixx commented
@xabbuh You are right, they are not wired. You might want to see my fork to see how it is wired.
IMHO, it's should not be split in 2 PRs because all theses classes work together.

2017-01-18 13:59 UTC, xabbuh commented
@lyrixx Why did you close here?

2017-01-18 14:33 UTC, lyrixx commented
Oups ... I don't know. Sorry for the noise.

2017-02-03 10:23 UTC, lyrixx commented
@fabpot It looks like you are not totally convinced by this PR. I could add "experimental" (cf http://symfony.com/blog/experimental-features) if you want.

2017-02-15 20:06 UTC, nicolas-grekas commented
I like this :) Here are some suggestions:
https://github.com/nicolas-grekas/symfony/commit/7b79e27b8545c2f34c0a7a3d87651196b223c57a

This patch fixes a 1s pause per log line I experienced when no log server was listening.
It uses persistent and asynchronous connections to make things faster.

2017-02-16 09:27 UTC, lyrixx commented
> This patch fixes a 1s pause per log line I experienced when no log server was listening.

I'm unable to reproduce it. Do you have a reproducer ?

2017-02-16 18:01 UTC, lyrixx commented
@nicolas-grekas I cherry-picked your commit and added a new one.

2017-02-16 18:17 UTC, yceruto commented on src/Symfony/Bridge/Monolog/Handler/ServerLogHandler.php
> +class ServerLogHandler extends AbstractHandler
missing author?

2017-02-16 18:18 UTC, yceruto commented on src/Symfony/Bridge/Monolog/Handler/ServerLogHandler.php
> +namespace Symfony\Bridge\Monolog\Handler;
missing license

2017-02-16 18:26 UTC, lyrixx commented on src/Symfony/Bridge/Monolog/Handler/ServerLogHandler.php
> +namespace Symfony\Bridge\Monolog\Handler;
Thanks. Fixed (both comments)

2017-02-16 18:27 UTC, lyrixx commented on src/Symfony/Bridge/Monolog/Handler/ServerLogHandler.php
> +                $logId = $record['extra'][$key];
Fixed.

2017-02-17 12:02 UTC, lyrixx commented on src/Symfony/Bundle/WebServerBundle/Command/ServerLogCommand.php
> +            ->addOption('show-extra', null, InputOption::VALUE_NONE, 'Display the extra')
It does not use the expression language for that. I don't understand

2017-02-17 12:03 UTC, lyrixx commented on src/Symfony/Bundle/WebServerBundle/Command/ServerLogCommand.php
> +            ->addOption('filter', null, InputOption::VALUE_REQUIRED, 'An expression to filter log. Example: record[\'level\'] > 200 or record[\'channel\'] in [\'app\', \'doctrine\']"')
I guess we broke something. Thanks.

2017-02-17 13:29 UTC, lyrixx commented on src/Symfony/Bundle/WebServerBundle/Command/ServerLogCommand.php
> +            ->addOption('filter', null, InputOption::VALUE_REQUIRED, 'An expression to filter log. Example: record[\'level\'] > 200 or record[\'channel\'] in [\'app\', \'doctrine\']"')
Actually, it's only `bin/console server:log --filter "level > 200"` ;) It's simpler.

2017-02-17 14:40 UTC, stof commented on src/Symfony/Bundle/WebServerBundle/Command/ServerLogCommand.php
> +            ->addOption('filter', null, InputOption::VALUE_REQUIRED, 'An expression to filter log. Example: record[\'level\'] > 200 or record[\'channel\'] in [\'app\', \'doctrine\']"')
yeah, a review comment suggested to simplify it, but the description of the option was not updated when implementing the requested change

2017-02-17 14:51 UTC, stof commented on src/Symfony/Bundle/WebServerBundle/Command/ServerLogCommand.php
> +            ->addOption('show-context', null, InputOption::VALUE_NONE, 'Display the context')
should we really have options for that ? Couldn't it simply be based on the verbosity instead ? This seems like a perfect use case for it: display more details in verbose mode.

2017-02-17 14:51 UTC, stof commented on src/Symfony/Bundle/WebServerBundle/Command/ServerLogCommand.php
> +        if ($input->getOption('filter')) {
this is wrong. ``initialize`` is called before the input validation is completed. so you should not start reading it here IMO

2017-02-17 14:51 UTC, stof commented on src/Symfony/Bundle/WebServerBundle/Command/ServerLogCommand.php
> +            ->addOption('host', null, InputOption::VALUE_REQUIRED, 'The server host', '0:9911')
why this default port ?

2017-02-17 15:00 UTC, lyrixx commented on src/Symfony/Bundle/WebServerBundle/Command/ServerLogCommand.php
> +            ->addOption('host', null, InputOption::VALUE_REQUIRED, 'The server host', '0:9911')
I really don't know.It was easy to type. What do you suggest ?

2017-02-17 15:01 UTC, lyrixx commented on src/Symfony/Bundle/WebServerBundle/Command/ServerLogCommand.php
> +            ->addOption('show-context', null, InputOption::VALUE_NONE, 'Display the context')
Indeed I will remove it.

Actually I'm working on a much better default log display in command.

2017-03-05 20:44 UTC, fabpot commented
@lyrixx any news?

2017-03-06 16:26 UTC, lyrixx commented
@fabpot I want to merge #21705 first, then I will rebase this one.

2017-03-07 11:26 UTC, lyrixx commented
Hello;

Here we go. I think this PR is ready for a last review.

I pushed everything to my fork for those who want to test it: https://github.com/lyrixx/symfony-standard/tree/server-log

2017-03-07 12:20 UTC, nicolas-grekas reviewed
I don't know how hard it'd be to functionally test that,
anyway, LGTM!

2017-03-07 12:20 UTC, nicolas-grekas commented on src/Symfony/Bridge/Monolog/Formatter/ConsoleFormatter.php
> +            $replacements['{'.$k.'}'] = sprintf('<comment>%s</>', $v);
if the `$v` string ends with a backslash, will it break escaping?

2017-03-07 12:45 UTC, lyrixx commented on src/Symfony/Bridge/Monolog/Formatter/ConsoleFormatter.php
> +            $replacements['{'.$k.'}'] = sprintf('<comment>%s</>', $v);
Good catch.
I have fixed this issue by escaping the value.
Thanks.

2017-03-10 09:23 UTC, nicolas-grekas approved these changes
:+1:

2017-03-14 10:19 UTC, lyrixx commented
:+1:

2017-03-14 18:59 UTC, fabpot commented
Thank you @lyrixx.

2017-03-14 18:59 UTC, merged