[Security] added voter report behavior
symfony/symfony pull request #21094
Opened 2016-12-29 15:10 UTC by maxperrimond

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes/no
| Fixed tickets | 
| License       | MIT
| Doc PR        | TODO

TODO

2016-12-29 15:21 UTC, linaori requested changes
The version constraints own't be correct between the bundle (service config) and the component, can you verify this?

2016-12-29 15:21 UTC, iltar commented on src/Symfony/Component/Security/Core/Authorization/AccessDecisionManager.php
> +    public function __construct(array $voters = array(), VoterContextFactoryInterface $contextFactory, $strategy = self::STRATEGY_AFFIRMATIVE, $allowIfAllAbstainDecisions = false, $allowIfEqualGrante
This is a BC break

2016-12-29 15:21 UTC, iltar commented on src/Symfony/Component/Security/Core/Authorization/Voter/Context/VoterContextFactory.php
> +    public function __construct(VoteReportCollectorInterface $collector, TranslatorInterface $translator, $translationDomain = null)
`Constructor.` can be removed, it adds nothing of value. The `$translationDomain` should probably just go on 1 line.

2016-12-29 15:21 UTC, iltar commented on src/Symfony/Component/Security/Core/Authorization/Voter/Report/VoteReportBuilder.php
> +class VoteReportBuilder implements VoteReportBuilderInterface
Should probably be final

2016-12-29 15:21 UTC, iltar commented on src/Symfony/Component/Security/Core/Authorization/Voter/Report/VoteReport.php
> +class VoteReport implements VoteReportInterface
Should probably be final

2016-12-29 15:21 UTC, iltar commented on src/Symfony/Component/Security/Core/Authorization/Voter/Context/VoterContextFactory.php
> +class VoterContextFactory implements VoterContextFactoryInterface
Should probably be final

2016-12-29 15:21 UTC, iltar commented on src/Symfony/Component/Security/Core/Authorization/Voter/Context/VoterContext.php
> +class VoterContext implements VoterContextInterface
Should probably be final

2016-12-29 15:21 UTC, iltar commented on src/Symfony/Component/Security/Core/Authorization/Voter/Context/VoterContext.php
> +    protected $translationDomain;
Unless there's a very good reason to make them protected, please make properties private

2016-12-29 15:21 UTC, iltar commented on src/Symfony/Component/Security/Core/Authorization/Voter/Report/VoteReportBuilder.php
> +            );
Is there a reason everything is on its own line in this method?

2016-12-29 15:21 UTC, iltar commented on src/Symfony/Component/Security/Core/Authorization/Voter/Report/VoteReportCollector.php
> +class VoteReportCollector implements \IteratorAggregate, VoteReportCollectorInterface
Should probably be final

2016-12-29 17:37 UTC, ro0NL commented
Maybe im missing it.. but isnt this about just the same as simply reporting from _your_ `VoterInterface::vote` method? Whatever the report strategy is..

In other words.. what's the difference between doing it in `initialize` vs. `vote`? The data is the same-ish, the calling order is the same... :confused: 

`vote` is already all about decision making, just not sure this can/should be captured with a standard...

2016-12-30 02:06 UTC, maxperrimond commented on src/Symfony/Component/Security/Core/Authorization/Voter/Report/VoteReportBuilder.php
> +            );
I thought, it's gonna be too long but no actually

2016-12-30 02:26 UTC, maxperrimond commented
@ro0NL Same as constraint validation in the form component, I wanted to give more verbosity on voters. For example as, a voter can support one or several objects and attributes, it can choose a decision without knowing the exact reason on your side.

```php
class MyVoter extends Voter
{
    // ...

   protected function voteOnAttribute($attribute, $subject, TokenInterface $token)
   {
        $user = $token->getUser();

        if ($user->isBad()) {
            return false;
        }

        if ($user->getAge() < 12) {
           return false;
        }

        return true;
   }
}
```
Here, for example, the voter can say no on an action with the current user but you can't tell that the user was a bad person or too young.

After for `initialize`, I know it's a bit a pollution and it's only for internal usage, that's why I tried to separate it from the `VoterInterface` but this method is in any case to be in decision making.

2016-12-30 09:32 UTC, ro0NL commented
I understand the usecase, im not sure a) if belongs to core and b) we really need 2 methods on this.

From my POV in `vote` is about decision-making, and where context diverges in many, many (i've seen some voters :)), many contexts. It's where the true magic happens.

Given
```php
if ($user->isBad()) {
    return false;
}

if ($user->getAge() < 12) {
   return false;
}

return true;
```

These are 3 contexts already, not sure you propose the if/else structure in `initialize` as well? But to me this is about at simple as adding a `$logger->info()` something above each return in `vote`. And im not sure _that_ should be standardized :)

Besides, i would do plain english i guess. Not translated; i think it's rather technical info (basically logs).

Using many voters will give better context by default.

But then again; im not sure why _you_ exactly want to separate this in 2 methods.

2016-12-30 09:43 UTC, iltar commented
I'm very happy to get a context of why it's not allowed. Imagine a list of options, but some are not allowed. As a person seeing those options, I want to know why they are not allowed. Currently I have to write a custom implementation on top of the voters (or next to it) to determine why, duplicating the domain logic.

2016-12-30 09:55 UTC, ro0NL commented
Ok that makes sense :) Still the calling order of both is the same.. meaning we dont really "initialize" all voters beforehand, not giving context beforehand.

What about a special `VoteResult`...


```php
//SomeVote::vote
return $yes ? self::GRANTED: new VoteResult(self::DENIED, 'report');
```

2017-01-12 12:19 UTC, maxperrimond commented
Quite like for a `VoteResult`, I will do some changes soon for a try

2017-01-14 08:34 UTC, ro0NL commented
Basically it would allow to follow all authorization checks for a given request, and collect them for the profiler. Meaning we can follow each decision in detail, additionally with custom user messages.

@maxperrimond @iltar wdyt?

2017-01-14 10:20 UTC, iltar commented
@ro0NL I like the idea of a vote report, but not the way it's implemented there. I don't like multiple return types, even if it enhances DX.

What about a second "introspectable" base Voter? It could be very similar to the original voter but has a different way to report:
```php
public function reportVoteOnAttribute(string $attribute, $subject, TokenInterface $token): VoteReport;
```

2017-01-14 10:35 UTC, ro0NL commented
We could always go with `vote()  : VoteResult` of course :) (additional interface).

Im just not sure if duplicating logic to provide detailed reports is convenient? You end up creating a common method providing the result + report..

2017-01-14 11:04 UTC, iltar commented
The "old" implementation could be nothing more than being decorated with a vote result without a message (for example)

2017-01-14 11:09 UTC, ro0NL commented
Exactly.

2017-01-16 12:54 UTC, maxperrimond commented
I made a new version of it with `VoterResult` as you mention, let me know what do you think of this version.
Cheerz

2017-01-16 13:12 UTC, linaori requested changes

2017-01-16 13:12 UTC, iltar commented on src/Symfony/Component/Security/Core/Authorization/AccessDecisionManager.php
> +    public function __construct(array $voters = array(), VoteReportBuilderInterface $reportBuilder, $strategy = self::STRATEGY_AFFIRMATIVE, $allowIfAllAbstainDecisions = false, $allowIfEqualGrantedDe
Note that this is still a BC break

2017-01-17 12:07 UTC, maxperrimond commented on src/Symfony/Component/Security/Core/Authorization/AccessDecisionManager.php
> +    public function __construct(array $voters = array(), VoteReportBuilderInterface $reportBuilder, $strategy = self::STRATEGY_AFFIRMATIVE, $allowIfAllAbstainDecisions = false, $allowIfEqualGrantedDe
Maybe I should set it and the behavior as optional to avoid the BC Break ?

2017-01-17 12:20 UTC, stof commented on src/Symfony/Component/Security/Core/Authorization/AccessDecisionManager.php
> +    public function __construct(array $voters = array(), VoteReportBuilderInterface $reportBuilder, $strategy = self::STRATEGY_AFFIRMATIVE, $allowIfAllAbstainDecisions = false, $allowIfEqualGrantedDe
it must be optional, and it must be at the end. Shifting all arguments is a BC break

2017-08-09 20:10 UTC, chalasr commented
@maxperrimond Any chance for this PR to be finished?

2017-09-27 14:56 UTC, weaverryan commented
Hmm... I like the idea... but it's a lot of code in core to accomplish this. I'm moving to the 4.1 milestone. But, unless we find a simpler implementation (after all, this is effectively "fancy logging"), I'm 👎. So, I hope you can prove me wrong with something simpler :)

2017-10-01 17:23 UTC, fabpot commented
Based on @weaverryan's last comment, I'm closing this PR as the code won't be merged anyway.

2017-10-01 17:23 UTC, closed without merging