#20411 fix Yaml parsing for very long quoted strings
symfony/symfony pull request #21279
Opened 2017-01-13 15:51 UTC by RichardBradley

| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #20411
| License       | MIT
| Doc PR        | no

This fixes #20411, a YAML string with too many backslash escapes can trigger a `PREG_BACKTRACK_LIMIT_ERROR` error in the Yaml parser.

There should be no behavioural change other than the bug fix

I have included a test which fails before this fix and passes after this fix.

2017-01-13 16:03 UTC, stof requested changes

2017-01-13 16:03 UTC, stof commented on src/Symfony/Component/Yaml/Tests/InlineTest.php
> +        $yamlString = Inline::dump(['longStringWithQuotes' => $longStringWithQuotes]);
the short array syntax does not work on PHP 5.3, which is still supported by Symfony 2.7. Please change it.

2017-01-13 16:04 UTC, stof commented
👍 (once the PHP 5.3 compat is fixed of course)

2017-01-13 17:02 UTC, RichardBradley commented on src/Symfony/Component/Yaml/Tests/InlineTest.php
> +        $yamlString = Inline::dump(['longStringWithQuotes' => $longStringWithQuotes]);
Sorry, good point. 
I've pushed a new version.

2017-01-13 17:08 UTC, stof approved these changes

2017-01-14 07:26 UTC, xabbuh commented
Thank you @RichardBradley.

2017-01-14 07:27 UTC, merged