[Workflow] Fixed support of multiple transition with the same name.
symfony/symfony pull request #21280
Opened 2017-01-13 16:03 UTC by lyrixx

| Q             | A
| ------------- | ---
| Branch?       | 3.2
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

---

The previous behavior was underterministic because it took the first
transition during the `can` and the `apply` method. But the "first"
does not mean anything. Now the workflown apply all possition transition
with the same name.

2017-01-13 20:30 UTC, MamWayne commented
Well done ;)

2017-01-14 09:33 UTC, Nyholm requested changes
I like this PR but I think it is missing one test.

Current marking: {a, b}. 
You have the following transitions: t1: a->c, t2: b->d. (Both transitions named "foobar")

You should check that {a,b} -> ["foobar"] -> {c,d}.

2017-01-14 16:42 UTC, lyrixx commented
@Nyholm I added a new test case.

2017-01-14 17:09 UTC, nicolas-grekas commented
:+1:

2017-01-14 17:17 UTC, Nyholm approved these changes
Awesome!

2017-01-15 16:28 UTC, fabpot commented
This is not strictly a bug fix. I understand that the current behavior is not the "right"/"expected" one, but I don't think this qualifies as something for 3.2. I would recommend to merge it in 3.3 instead.

@lyrixx Can you add a note in the component CHANGELOG about this change?

2017-01-16 09:54 UTC, lyrixx commented
IMHO, it should go on 3.2 because it will be impossible for 3.2 users to have the correct behavior, and then when they will upgrade to 3.3, the behavior will be different than what they know.

2017-01-16 10:00 UTC, lyrixx commented
Please note that there are not new visible interface, so it's a pure behavioral change

2017-01-18 05:36 UTC, fabpot commented
Thank you @lyrixx.

2017-01-18 05:36 UTC, merged