[FrameworkBundle] fixed custom domain for translations in php templates
symfony/symfony pull request #21359
Opened 2017-01-20 14:20 UTC by robinlehrmann

| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #20135
| License       | MIT
| Doc PR        |

2017-01-21 08:11 UTC, xabbuh requested changes

2017-01-21 08:11 UTC, xabbuh commented on src/Symfony/Bundle/FrameworkBundle/Translation/PhpExtractor.php
> +    protected static $sequences = array(
The `static` change should be reverted.

2017-01-21 08:11 UTC, xabbuh commented on src/Symfony/Bundle/FrameworkBundle/Translation/PhpExtractor.php
> +            foreach (self::$sequences as $sequence) {
Must then be reverted too.

2017-01-21 08:11 UTC, xabbuh commented on src/Symfony/Bundle/FrameworkBundle/Translation/PhpExtractor.php
> +    private function seekToMessageParamsEnd(\Iterator $tokenIterator)
maybe better name this `seekBehindMessageParams`

2017-01-21 08:11 UTC, xabbuh commented on src/Symfony/Bundle/FrameworkBundle/Translation/PhpExtractor.php
> +        if ('b"' !== $token && isset($token[1])) {
IMO this should be reverted as it is not part of the bug fix.

2017-01-21 08:11 UTC, xabbuh commented on src/Symfony/Bundle/FrameworkBundle/Translation/PhpExtractor.php
> +    private function provideRawString(\Iterator $tokenIterator)
What about `getStringValue()` instead?

2017-01-21 11:57 UTC, aitboudad requested changes

2017-01-21 11:57 UTC, aitboudad commented on src/Symfony/Bundle/FrameworkBundle/Translation/PhpExtractor.php
> +            if ('[' === $t[0] || '(' === $t[0]) {
you should not take account of braces inside a string
```php
->trans('msg', [ 'p' => '[ \'' ], 'not_messages')
```

2017-01-21 11:57 UTC, aitboudad commented on src/Symfony/Bundle/FrameworkBundle/Translation/PhpExtractor.php
> +            T_LNUMBER,
it can be an expression or function call

2017-01-21 12:41 UTC, robinlehrmann commented on src/Symfony/Bundle/FrameworkBundle/Translation/PhpExtractor.php
> +            T_LNUMBER,
I added a new test with array_map function and the tests passes. Can you explain what you mean please :) ?

2017-01-21 12:41 UTC, robinlehrmann commented on src/Symfony/Bundle/FrameworkBundle/Translation/PhpExtractor.php
> +            if ('[' === $t[0] || '(' === $t[0]) {
I added this line to my tests too and it passes.

2017-01-21 12:42 UTC, robinlehrmann commented on src/Symfony/Bundle/FrameworkBundle/Translation/PhpExtractor.php
> +        if ('b"' !== $token && isset($token[1])) {
Done

2017-01-21 12:42 UTC, robinlehrmann commented on src/Symfony/Bundle/FrameworkBundle/Translation/PhpExtractor.php
> +    private function seekToMessageParamsEnd(\Iterator $tokenIterator)
Done

2017-01-21 12:42 UTC, robinlehrmann commented on src/Symfony/Bundle/FrameworkBundle/Translation/PhpExtractor.php
> +    private function provideRawString(\Iterator $tokenIterator)
Done

2017-01-21 12:43 UTC, robinlehrmann commented on src/Symfony/Bundle/FrameworkBundle/Translation/PhpExtractor.php
> +            foreach (self::$sequences as $sequence) {
Done

2017-01-21 12:43 UTC, robinlehrmann reviewed
I added some tests and it passes.

2017-01-21 12:57 UTC, aitboudad commented on src/Symfony/Bundle/FrameworkBundle/Translation/PhpExtractor.php
> +            T_LNUMBER,
```php
<?php echo $view['translator']->transChoice('msg', 10 + 1, [], 'not_messages'); ?>
<?php echo $view['translator']->transChoice('msg', intval(4.5), [], 'not_messages'); ?>
```

2017-01-21 13:02 UTC, robinlehrmann commented on src/Symfony/Bundle/FrameworkBundle/Translation/PhpExtractor.php
> +            T_LNUMBER,
Okay, I added this lines and the Tests don't pass. Thank you!
I will fix it asap.

2017-01-22 07:43 UTC, xabbuh commented on src/Symfony/Bundle/FrameworkBundle/Translation/PhpExtractor.php
> +            T_LNUMBER,
I guess you can use the same approach here that is already used for skipping the message params.

2017-01-22 07:45 UTC, xabbuh commented on src/Symfony/Bundle/FrameworkBundle/Translation/PhpExtractor.php
> +            if ('[' === $t[0] || '(' === $t[0]) {
@aitboudad In your example, `$t` will be an array consisting of three elements where the value at index 0 is `T_CONSTANT_ENCAPSED_STRING` if I am not mistaken.

2017-02-03 14:40 UTC, robinlehrmann commented
Hi, @aitboudad @xabbuh 
I've fixed the issue and added some tests for it. Could you review my changes please ?

2017-02-03 14:52 UTC, xabbuh commented on src/Symfony/Bundle/FrameworkBundle/Translation/PhpExtractor.php
> +    const MESSAGE_ARGUMENTS_TOKEN = 1000;
I would name this `METHOD_ARGUMENTS_TOKEN`

2017-02-03 14:53 UTC, xabbuh commented on src/Symfony/Bundle/FrameworkBundle/Translation/PhpExtractor.php
> +    private function seekToMessageParamsEnd(\Iterator $tokenIterator)
I would now rename this too (something like `skipMethodArgument()`)

2017-02-03 16:09 UTC, xabbuh approved these changes
:+1:

Status: Reviewed

2017-02-03 16:13 UTC, aitboudad approved these changes

2017-02-03 16:30 UTC, fabpot commented
Thank you @robinlehrmann.

2017-02-03 16:30 UTC, merged