Use proper error message when session write fails #20807
symfony/symfony pull request #21421
Opened 2017-01-26 16:29 UTC by digilist

This improves the error message that is thrown if a session write fails (see #20807)

As there was no way to get the actual handler, I introduced a method on the SessionHandlerProxy. I hope that's okay, otherwise please give me a hint on what to do.

| Q             | A
| ------------- | ---
| Branch?       | 2.8
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #20807
| License       | MIT

2017-01-26 16:35 UTC, stof requested changes

2017-01-26 16:35 UTC, stof commented on src/Symfony/Component/HttpFoundation/Session/Storage/Proxy/SessionHandlerProxy.php
> +    public function getHandler(): \SessionHandlerInterface
The return type is a no-go as Symfony supports PHP 5.x

2017-01-26 16:35 UTC, stof commented on src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php
> +        } catch (\ErrorException $e) {
this won't work in prod, as notices and warnings are *not* turned into ErrorException exceptions there.

Code must not be written by assuming that the error handler has this behavior

2017-02-02 14:14 UTC, nicolas-grekas commented
Status: needs work

2017-02-07 10:39 UTC, digilist commented on src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php
> +        } catch (\ErrorException $e) {
Yes, currently the session write fails silently in production.

I updated the code to check the last error message and throw a E_USER_WARNING with the corrected message. However, the warning is not logged by default.

Alternatively, we can throw an Excpetion if the write fails, as it is an error anyway. However, it does break BC.

2017-02-14 14:15 UTC, nicolas-grekas commented
Instead of relying on some external error handler to trigger the exception, I'd suggest to register a temporary error handler that does the throw.

2017-02-18 23:03 UTC, digilist commented
That is a good idea! The code is much cleaner now.

2017-02-20 07:05 UTC, xabbuh commented on src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php
> +            $message = sprintf(
this can be inlined in the `trigger_error()` call

2017-03-05 20:28 UTC, fabpot commented
Thank you @digilist.

2017-03-05 20:28 UTC, closed without merging