[HttpFoundation] Find the original request protocol version
symfony/symfony pull request #21469
Opened 2017-01-31 08:47 UTC by thewilkybarkid

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #21468
| License       | MIT
| Doc PR        | 

Adds a new method to `Request` to find the original protocol version from the `Via` header, if the request is from a trusted proxy.

2017-01-31 12:23 UTC, dunglas requested changes

2017-01-31 12:23 UTC, dunglas commented on src/Symfony/Component/HttpFoundation/Request.php
> +            preg_match('~^(HTTP/)?([1-9].[0-9]) ~', $this->headers->get('Via'), $matches);
The `.` must be escaped (currently it matches `HTTP/1^1 ` for instance).

2017-01-31 12:30 UTC, nicolas-grekas commented
The other methods that use `isFromTrustedProxy` don't have the "Original" keyword in their name. What about just `getProtocolVersion()`?
Is there anything else that could be relevant in the "Via" header? Do you have any link documenting its value?

2017-02-02 13:59 UTC, nicolas-grekas commented
Status: needs work

2017-02-11 11:51 UTC, nicolas-grekas commented
Security issue: why should "Via" be trusted?
Any RFC that defines the semantic of the header?

2017-02-11 12:54 UTC, dunglas commented
@nicolas-grekas https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.45

2017-02-13 08:03 UTC, thewilkybarkid commented
@nicolas-grekas I used the term 'original' to distinguish the request that the user originally made (to some proxy) with the one that PHP has received. Happy to rename if there's a more suitable term.

2017-02-13 08:05 UTC, javiereguiluz commented on src/Symfony/Component/HttpFoundation/Request.php
> +     * Returns the original protocol version.
This description should be improved to explain very briefly what does "the original protocol" mean. Thanks!

2017-02-13 11:58 UTC, nicolas-grekas commented
We don't make any distinction for "original" host/ip/proto/port. I don't see why this is different for the version of the proto.

2017-02-13 16:11 UTC, thewilkybarkid commented
The response should be the protocol version used by the proxy, not the original client, so they need to be kept separate.

2017-02-13 16:15 UTC, dunglas commented
Maybe can we add a method to parse the `Via` header, with a shortcut to only retrieve the value of the first (original) protocol and version used?

It may be interesting to know the original protocol version (for instance to add different `Link` HTTP headers depending of the client capabilities).

2017-02-14 12:50 UTC, nicolas-grekas commented
> The response should be the protocol version used by the proxy, not the original client, so they need to be kept separate.

that's exactly my point yes: getHost, isSecure, getPort all return the info as used by the client - not the proxy. This should be the same here to me.
If one want to get access to the protocol used by the proxy, just call `$request->server->get('SERVER_PROTOCOL')`.

2017-03-22 19:12 UTC, nicolas-grekas approved these changes
:+1:

2017-03-22 19:15 UTC, fabpot commented
:-1: Your application is talking to the proxy, so we should return the HTTP protocol of the proxy, not the one used between the client and the proxy. I understand the use case, but that should be done in your application, not in Symfony.

2017-03-28 07:23 UTC, thewilkybarkid commented
The protocol version isn't being changed in the response.

2017-07-06 09:52 UTC, fabpot approved these changes

2017-07-06 09:58 UTC, fabpot commented
Thank you @thewilkybarkid.

2017-07-06 09:58 UTC, closed without merging