Static code analysis with Php Inspections (EA Extended)
symfony/symfony pull request #21537
Opened 2017-02-05 17:40 UTC by kalessil

| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | yes
| Tests pass?   | yes
| Fixed tickets | --
| License       | MIT
| Doc PR        | --

- Unnecessary proxy methods and methods duplicating  parents ones removed;
- Type casings instead of PHP4 functions;
- Usage of copy instead of file combining file get/put contents;
- One time use variables cleaned up;
- Superfluous functions calls in loop termination conditions fixed;

2017-02-05 17:42 UTC, kalessil commented on src/Symfony/Component/HttpKernel/DataCollector/Util/ValueExporter.php
>                  return sprintf('Object(%s) - %s', get_class($value), $value->format(\DateTime::ISO8601));
Perhaps someone fro the core team can give a go fixing this. I'm simply not sure if the change would introduce a BC break...

2017-02-05 19:14 UTC, dunglas requested changes

2017-02-05 19:14 UTC, dunglas commented on src/Symfony/Bundle/SecurityBundle/DependencyInjection/Security/Factory/SimpleFormFactory.php
> -    protected function createEntryPoint($container, $id, $config, $defaultEntryPoint)
Should be reverted, it's a BC break.

2017-02-05 19:22 UTC, xabbuh commented on src/Symfony/Bundle/FrameworkBundle/Tests/Fixtures/Resources/views/translation.html.php
> +<?php echo $view['translator']->transChoice('msg2', (int)4.5, [], 'not_messages'); ?>
The `intval()` call was intended here to have a test case with a function call. We could replace it with another function call, but IMO that's not really necessary as we are only talking about a test fixture here.

2017-02-05 19:23 UTC, xabbuh commented on src/Symfony/Component/HttpFoundation/Tests/Session/Storage/Handler/MongoDbSessionHandlerTest.php
> +                    $that->assertGreaterThanOrEqual(round((int)((string) $criteria[$that->options['expiry_field']]['$gte']) / 1000), $testTimeout);
missing space after `(int)`

2017-02-05 19:23 UTC, xabbuh commented on src/Symfony/Component/HttpFoundation/Tests/Session/Storage/Handler/MongoDbSessionHandlerTest.php
> +                    $that->assertGreaterThanOrEqual(round((int)((string) $criteria[$that->options['expiry_field']]['$gte']) / 1000), $testTimeout);
same below

2017-02-05 19:59 UTC, wouterj requested changes

2017-02-05 19:59 UTC, wouterj commented on src/Symfony/Component/HttpKernel/Client.php
> -    public function getRequest()
These 2 methods are intended in order to get correct autocompletion in IDE's. (the base client can only typehint `object`, while the HttpKernel client knows that object is a HttpFoundation request/response).

2017-02-05 19:59 UTC, wouterj commented on src/Symfony/Component/Security/Acl/Dbal/MutableAclProvider.php
> +        return preg_replace('/^SELECT id FROM/', 'DELETE FROM', $select);
these should be an empty line before a return statement

2017-02-05 20:28 UTC, kalessil commented on src/Symfony/Bundle/SecurityBundle/DependencyInjection/Security/Factory/SimpleFormFactory.php
> -    protected function createEntryPoint($container, $id, $config, $defaultEntryPoint)
Same function with the same body defined in a parent class, so BC is not introduced. 
In nutshell, this is duplicate code if \Symfony\Bundle\SecurityBundle\DependencyInjection\Security\Factory\FormLoginFactory::createEntryPoint

2017-02-05 20:35 UTC, kalessil commented on src/Symfony/Bundle/FrameworkBundle/Tests/Fixtures/Resources/views/translation.html.php
> +<?php echo $view['translator']->transChoice('msg2', (int)4.5, [], 'not_messages'); ?>
Hm, I wondering: what is the intention of using the function here, would you share the  idea with me please?

2017-02-05 20:47 UTC, kalessil commented on src/Symfony/Component/HttpKernel/Client.php
> -    public function getRequest()
I see the point, in this case following approach would work as well:
```php
/**
 * Client simulates a browser and makes requests to a Kernel object.
 *
 * @author Fabien Potencier <fabien@symfony.com>
 *
 * @method Request|null getRequest() A Request instance
 * @method Response|null getResponse() A Response instance
 */
```
Elegant and no additional code needed, what is your opinion aboutit?

2017-02-06 08:38 UTC, xabbuh commented on src/Symfony/Bundle/FrameworkBundle/Tests/Fixtures/Resources/views/translation.html.php
> +<?php echo $view['translator']->transChoice('msg2', (int)4.5, [], 'not_messages'); ?>
The corresponding test case is processing the PHP token stream. And this one is here to make sure that a function/method call wouldn't break.

2017-02-06 09:02 UTC, kalessil commented on src/Symfony/Bundle/FrameworkBundle/Tests/Fixtures/Resources/views/translation.html.php
> +<?php echo $view['translator']->transChoice('msg2', (int)4.5, [], 'not_messages'); ?>
Oh, I see. Don't you mind if I'll then use the ceil function instead?

2017-02-06 09:03 UTC, xabbuh commented on src/Symfony/Bundle/FrameworkBundle/Tests/Fixtures/Resources/views/translation.html.php
> +<?php echo $view['translator']->transChoice('msg2', (int)4.5, [], 'not_messages'); ?>
fine for me

2017-02-06 09:13 UTC, kalessil commented on src/Symfony/Bundle/FrameworkBundle/Tests/Fixtures/Resources/views/translation.html.php
> +<?php echo $view['translator']->transChoice('msg2', (int)4.5, [], 'not_messages'); ?>
Great, thank you =) Will update today (in the evening most probably)

2017-02-06 10:48 UTC, stof requested changes

2017-02-06 10:48 UTC, stof commented on src/Symfony/Component/DomCrawler/Crawler.php
> +        return new static($nodes, $this->uri, $this->baseHref);
should be reverted to simplify merging between branches (as of 2.8, we have additional code before the return statement)

2017-02-06 10:48 UTC, stof commented on src/Symfony/Component/HttpFoundation/Tests/Session/Storage/Handler/MongoDbSessionHandlerTest.php
> +            $that->assertGreaterThanOrEqual($expectedExpiry, round((int) ((string) $data[$that->options['expiry_field']]) / 1000));
does the ``(int)`` casting apply before or after the division by 1000 here ? This code is less readable than before, as it requires knowing the operator precedence (and I cannot guarantee that it works as before here without checking in the php documentation, as I don't know this precedence by heart)

2017-02-06 11:41 UTC, kalessil commented on src/Symfony/Component/DomCrawler/Crawler.php
> +        return new static($nodes, $this->uri, $this->baseHref);
Will do

2017-02-06 11:42 UTC, kalessil commented on src/Symfony/Component/HttpFoundation/Tests/Session/Storage/Handler/MongoDbSessionHandlerTest.php
> +            $that->assertGreaterThanOrEqual($expectedExpiry, round((int) ((string) $data[$that->options['expiry_field']]) / 1000));
Will add necessary `()` here

2017-02-06 17:53 UTC, kalessil commented on src/Symfony/Bundle/SecurityBundle/DependencyInjection/Security/Factory/SimpleFormFactory.php
> -    protected function createEntryPoint($container, $id, $config, $defaultEntryPoint)
ping @dunglas

2017-02-06 17:53 UTC, kalessil commented on src/Symfony/Component/HttpKernel/Client.php
> -    public function getRequest()
ping @wouterj

2017-02-16 12:44 UTC, fabpot commented on src/Symfony/Component/HttpKernel/Client.php
> -    public function getRequest()
@kalessil I think adding the annotations is indeed enough. Go for it.

2017-02-16 12:44 UTC, fabpot commented on src/Symfony/Component/HttpKernel/DataCollector/Util/ValueExporter.php
>                  return sprintf('Object(%s) - %s', get_class($value), $value->format(\DateTime::ISO8601));
That code is in a DataCollector, so there is no BC promise here. So, you can update the code.

2017-02-16 12:44 UTC, fabpot commented on src/Symfony/Component/Yaml/Parser.php
> +            for ($i = 0; $i < $blockLinesCount; ++$i) {
Can you inline the assignment in the `for` code?

2017-02-16 12:44 UTC, fabpot commented on src/Symfony/Component/HttpFoundation/BinaryFileResponse.php
> +            for ($i = 0; $i < $filenameLength; ++$i) {
Can you inline the assignment in the `for` code?

2017-02-16 12:55 UTC, kalessil commented on src/Symfony/Component/Yaml/Parser.php
> +            for ($i = 0; $i < $blockLinesCount; ++$i) {
Yes, will do.

2017-02-16 12:55 UTC, kalessil commented on src/Symfony/Component/HttpFoundation/BinaryFileResponse.php
> +            for ($i = 0; $i < $filenameLength; ++$i) {
Yes, will do.

2017-02-16 21:55 UTC, fabpot commented
👍

2017-02-16 22:22 UTC, kalessil commented
Ready now: all green

2017-02-16 22:27 UTC, fabpot commented
Thank you @kalessil.

2017-02-16 22:28 UTC, closed without merging