[Form] Allow to get form's children transformation failures
symfony/symfony pull request #21651
Opened 2017-02-17 13:17 UTC by ShinDarth

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| License       | MIT
| Doc PR        | needs to be accepted first

2017-02-17 13:21 UTC, xabbuh requested changes
This PR cannot be merged as is as adding a new method to an existing interface is a BC break. I am also not sure if this is really worth a dedicated method.

2017-02-17 13:21 UTC, xabbuh commented on src/Symfony/Component/Form/FormInterface.php
> +    public function getChildrenTransformationFailures();
Adding a new method to an interface is a BC break.

2017-02-17 13:23 UTC, ShinDarth commented on src/Symfony/Component/Form/FormInterface.php
> +    public function getChildrenTransformationFailures();
@xabbuh what about adding this method to the class Form only? Since button won't have it anyway....

2017-02-25 16:49 UTC, HeahDude commented on src/Symfony/Component/Form/Form.php
> +    public function getChildrenTransformationFailures()
What about `deep` and `flatten` argument?

2017-02-25 16:49 UTC, HeahDude commented on src/Symfony/Component/Form/FormInterface.php
> +    public function getChildrenTransformationFailures();
Sounds better.

2017-03-22 19:53 UTC, fabpot commented
@ShinDarth Any news on this PR?

2017-03-23 08:37 UTC, ShinDarth commented
well if we decided not to add the change to the interface, I can change that

2017-03-23 08:38 UTC, ShinDarth commented on src/Symfony/Component/Form/Form.php
> +    public function getChildrenTransformationFailures()
what would be the purpose? can you please give me an example?

2017-10-08 15:50 UTC, nicolas-grekas commented
Moving to 4.1. Rebase on master might be needed, where PHP 7.1 features can be used btw.

2018-01-26 13:57 UTC, xabbuh commented
@ShinDarth Would you like to finish here?

2018-03-31 05:35 UTC, fabpot commented
Closing this pull request as there is no more activity. @ShinDarth Feel free to reopen whenever you have time to finish it. Thanks.

2018-03-31 05:35 UTC, closed without merging