[DI] Add and wire ServiceSubscriberInterface
symfony/symfony pull request #21708
Opened 2017-02-21 22:56 UTC by nicolas-grekas

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | no test yet
| Fixed tickets | #20658
| License       | MIT
| Doc PR        | -

This PR implements the second and missing part of #20658: it enables objects to declare their service dependencies in a similar way than we do for EventSubscribers: via a static method. Here is the interface and its current description:
```php
namespace Symfony\Component\DependencyInjection;

/**
 * A ServiceSubscriber exposes its dependencies via the static {@link getSubscribedServices} method.
 *
 * It is expected that ServiceSubscriber instances consume PSR-11-based service locators internally.
 * This interface does not dictate any injection method for these service locators, although constructor
 * injection is recommended. In the list returned by {@link getSubscribedServices} method, service types
 * that start with an interrogation mark "?" are optional, while the other ones are mandatory service
 * dependencies. The injected service locators SHOULD NOT allow access to any other services not specified
 * by the method.
 *
 * @author Nicolas Grekas <p@tchwork.com>
 */
interface ServiceSubscriberInterface
{
    /**
     * Returns an array of service types required by such instances, optionally keyed by the service names used internally.
     *
     * For mandatory dependencies:
     *
     *  * array('logger' => 'Psr\Log\LoggerInterface') means the objects use the "logger" name
     *    internally to fetch a service which must implement Psr\Log\LoggerInterface.
     *  * array('Psr\Log\LoggerInterface') is a shortcut for
     *  * array('Psr\Log\LoggerInterface' => 'Psr\Log\LoggerInterface')
     *
     * otherwise:
     *
     *  * array('logger' => '?Psr\Log\LoggerInterface') denotes an optional dependency
     *  * array('?Psr\Log\LoggerInterface') is a shortcut for
     *  * array('Psr\Log\LoggerInterface' => '?Psr\Log\LoggerInterface')
     *
     * @return array The required service types, optionally keyed by service names
     */
    public static function getSubscribedServices();
}
```

We could then have eg a controller-as-a-service implement this interface, and be auto or manually wired according to the return value of this method - using the "kernel.service_subscriber" tag to do so.
eg:

```yaml
services:
  App\Controller\FooController:
    tags:
      - name: kernel.service_subscriber
        logger: monolog.logger.foo_channel
        router: my_router_service
```

The benefits are:
- it keeps the lazy-behavior gained by service locators / container injection
- it allows the referenced services to be made private from the pov of the main Symfony DIC - thus enables some compiler optimizations
- it makes dependencies autowirable (while keeping manual wiring possible)
- it does not add any strong coupling at the architecture level
- and most importantly and contrary to regular container injection, *it makes dependencies explicit* - each classes declaring which services it consumes.

Some might argue that:
- it requires to be explicit - thus more verbose. Yet many others think it's a good thing - ie it's worth it.
- some coupling happens at the dependency level, since you need to get the DI component to get the interface definition. This is something that the PHP-FIG could address at some point.

The implementation is not ready yet - but you can still wonder how it is expected to work by looking at it.

2017-02-22 08:44 UTC, stof requested changes

2017-02-22 08:44 UTC, stof commented on src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php
> +        if ($value instanceof AutowiredReference && ContainerInterface::EXCEPTION_ON_INVALID_REFERENCE !== $value->getInvalidBehavior() && $this->container->has((string) $value)) {
shouldn't it be ``AutowirableReference`` ?

2017-02-22 08:44 UTC, stof commented on src/Symfony/Component/DependencyInjection/Compiler/RegisterServiceSubscribersPass.php
> +        foreach ($services as $services) {
``$services`` looks undefined here

2017-02-22 08:44 UTC, stof commented on src/Symfony/Component/DependencyInjection/Compiler/RegisterServiceSubscribersPass.php
> +                $type = substr($type, 1);
shouldn't you validate that the type is still not empty here ? ``?```alone should be forbidden too.

2017-02-22 08:44 UTC, stof commented on src/Symfony/Component/DependencyInjection/ServiceSubscriberInterface.php
> +Psr\Container\ContainerInterface;
missing ``use``

2017-02-22 08:46 UTC, stof commented on src/Symfony/Component/DependencyInjection/Argument/ServiceLocatorArgument.php
> +class ServiceLocatorArgument extends Definition implements ArgumentInterface
won't this cause issues with recursive passes processing Definition objects ? Is it really a Definition ?

2017-02-22 09:12 UTC, Soullivaneuh commented on src/Symfony/Component/DependencyInjection/Compiler/RegisterServiceSubscribersPass.php
> +        foreach ($services as $services) {
Plus, the array and the item are the same variable, I don't think this is wanted.

2017-02-22 10:16 UTC, nicolas-grekas commented
Talking with others, it looks like this approach has one serious drawback: it does not play well with composition.
Say you have a class that uses trait1 and trait2, then the deps declaration can't be provided by each trait because of method name collision. Instead, the class itself must do it.
That's an issue getter does not have. use trait1 and trait2 which declares their deps via eg abstract getters, and composition is at its best.

2017-02-23 00:13 UTC, chalasr commented on src/Symfony/Component/DependencyInjection/Compiler/RegisterServiceSubscribersPass.php
> +        if (!$value instanceof Definition || $value->isAbstract() || $value->isSynthetic() || !$value->hasTag('kernel.service_subscriber')) {
should be added to `UnusedTagsPass::$whitelist`

2017-03-05 21:23 UTC, nicolas-grekas commented
PR rebased and ready

Status: needs review

2017-03-06 15:18 UTC, nicolas-grekas commented
Just added a few more test cases.

2017-03-10 14:29 UTC, nicolas-grekas commented
CHANGELOG entry added, PR ready.

2017-03-10 22:16 UTC, nicolas-grekas commented on src/Symfony/Component/HttpKernel/CHANGELOG.md
> - * added `TestSessionListener`
these were not added in 3.3

2017-03-11 09:16 UTC, nicolas-grekas commented
Second commit added, to implement the new interface where applicable in the code base.

2017-03-11 09:22 UTC, nicolas-grekas commented
As you can see, this allows having type-hinted service locators also, on top of explicit deps.
Can only help write more robust code and help IDEs provide auto-completion.

2017-03-22 19:28 UTC, fabpot commented on src/Symfony/Component/DependencyInjection/Compiler/RegisterServiceSubscribersPass.php
> +                continue;
Shoudn't we throw an exception instead?

2017-03-22 19:32 UTC, nicolas-grekas commented on src/Symfony/Component/DependencyInjection/Compiler/RegisterServiceSubscribersPass.php
> +                continue;
When there is not attributes at all, L75 creates "TypedReference" that target the service that has the same name as the type

2017-03-22 19:33 UTC, fabpot commented on src/Symfony/Component/DependencyInjection/Compiler/RegisterServiceSubscribersPass.php
> +                continue;
👍

2017-03-22 19:36 UTC, fabpot commented
Thank you @nicolas-grekas.

2017-03-22 19:36 UTC, merged

2017-04-24 11:02 UTC, chalasr commented on src/Symfony/Bundle/FrameworkBundle/Routing/Router.php
> +    }
@nicolas-grekas The service definition has not been updated (not tagged `container.service_subscriber`) so this is actually unused, is it expected?

2017-04-24 11:26 UTC, nicolas-grekas commented on src/Symfony/Bundle/FrameworkBundle/Routing/Router.php
> +    }
Expected: getParameter is used, so cannot by a PSR11 container.