[Serializer] Add Support for `object_to_populate` to CustomNormalizer
symfony/symfony pull request #21716
Opened 2017-02-22 15:51 UTC by chrisguitarguy

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #21715
| License       | MIT
| Doc PR        | n/a

This pulls a trait out of `AbstractNormalizer` with a method to extract the object to populate and adds some tests for it. Then uses that trait in both `AbstractNormalizer` and `CustomNormalizer` so both can support the `object_to_populate` key.

2017-02-24 11:44 UTC, dunglas requested changes

2017-02-24 11:44 UTC, dunglas commented on src/Symfony/Component/Serializer/Normalizer/AbstractNormalizer.php
>              unset($context[static::OBJECT_TO_POPULATE]);
Shouldn't this line be moved in in the trait too?

2017-02-24 11:44 UTC, dunglas commented on src/Symfony/Component/Serializer/Normalizer/ObjectToPopulateTrait.php
> +        return null;
Useless, can be removed.

2017-02-24 11:44 UTC, dunglas commented on src/Symfony/Component/Serializer/Normalizer/ObjectToPopulateTrait.php
> +     *                    Keeps backwards compatibility with `AbstractNormalizer`.
There is no reason to mention this in the comment IMO.

2017-02-24 11:45 UTC, dunglas commented
Just asking, what is the use case of this class? I think that it's always better to create custom normalizers (implementing the `NormalizerInterface` than adding the serialization logic in the class itself.

I would be in favor of deprecating this class and remove it from Symfony 3.

2017-02-24 12:36 UTC, chrisguitarguy commented on src/Symfony/Component/Serializer/Normalizer/AbstractNormalizer.php
>              unset($context[static::OBJECT_TO_POPULATE]);
Would involve passing context by reference into the trait. That's the only reason I didn't do it.

2017-02-24 12:43 UTC, chrisguitarguy commented
> Just asking, what is the use case of this class?

In my case, I was interested in using it with a "dumb" dto-like object.

```php
class SomeDto implements DenormalizableInterface
{
  // ...
}
```

The idea being to keep everything close together: the normalization, denormalization, and the DTO itself. So basically what you are against :)

I was interested in doing this because I think it's a lot nicer developer experience to keep the normalization/denormalization closer to the object being serialize/deserialized. Easier to understand and catch at a glance. Doesn't require you to register services in the container with a special tag, etc.

2017-02-24 13:24 UTC, felipsmartins commented on src/Symfony/Component/Serializer/Normalizer/ObjectToPopulateTrait.php
> +     *                    Keeps backwards compatibility with `AbstractNormalizer`.
Why?

2017-09-26 21:25 UTC, dunglas approved these changes

2017-09-26 23:15 UTC, fabpot commented
@chrisguitarguy Can you please rebase it so that we can merge it? Thanks. Base should also be changed to 3.4.

2017-09-27 00:39 UTC, chrisguitarguy commented
@fabpot rebased on 3.4. Did you want me to make any of the changes @dunglas suggested?

2017-09-27 00:50 UTC, fabpot commented
Looks like he approved this PR without any further changes :)

2017-09-27 17:32 UTC, fabpot commented
Thank you @chrisguitarguy.

2017-09-27 17:33 UTC, closed without merging