[Form] Add the FormTypeValidatorExtension to the TypeTestCase factory builder
symfony/symfony pull request #21780
Opened 2017-02-27 13:24 UTC by pierredup

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | N/A
| License       | MIT
| Doc PR        | TBA

When creating tests for forms that uses the `constraints` option, I always get the error that the option `constraints` does not exist. This is because that option is provided by the `FormTypeValidatorExtension` class.

So this adds the `FormTypeValidatorExtension` as a default form type extension when extending `Symfony\Component\Form\Test\TypeTestCase` as well as providing a way to register any custom form type extensions

2017-02-27 15:53 UTC, xabbuh commented on src/Symfony/Component/Form/Test/TypeTestCase.php
> +        $this->validator = $this->getMockBuilder('Symfony\Component\Validator\Validator\ValidatorInterface')->getMock();
This will break existing applications that use the `TypeTestCase` class, but do not have the Validator component installed.

2017-02-27 19:14 UTC, pierredup commented on src/Symfony/Component/Form/Test/TypeTestCase.php
> +        $this->validator = $this->getMockBuilder('Symfony\Component\Validator\Validator\ValidatorInterface')->getMock();
Wrapped the extension in a check to make sure ValidatorInterface exists

2017-02-27 19:58 UTC, xabbuh commented on src/Symfony/Component/Form/Test/TypeTestCase.php
> +    protected function getTypedExtensions()
If you want this to be called automatically based on the parent `FormIntegrationTestCase` class, you will have to rename this method to `getTypeExtensions()`.

2017-02-27 20:07 UTC, pierredup commented on src/Symfony/Component/Form/Test/TypeTestCase.php
> +    protected function getTypedExtensions()
Thanks, it was supposed to be `getTypeExtensions`, I don't know how that d sneaked in there

2017-02-27 21:34 UTC, smithandre approved these changes

2017-03-03 22:15 UTC, HeahDude commented
Hi @pierredup, thank you for proposing this.

In fact there is already this [TypeTestCase](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Tests/Extension/Validator/Type/TypeTestCase.php) form the validator extension that can be extended, it does extend the [base TypeTestCase](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Test/TypeTestCase.php) with the change you suggest.

I've opened https://github.com/symfony/symfony-docs/issues/7566 so we don't forget to document it, we may close here though.

2017-03-04 07:50 UTC, pierredup commented
@HeahDude I initially did try using that, but I got the error `Invalid argument supplied for foreach()` in Symfony/Component/Form/Extension/Validator/EventListener/ValidationListener.php:57.

This is because the `validate` method is not mocked, which means when it is called it just returns `null` which breaks the listener. So to solve this I can add the mock to the validator TypeTestCase class, but I opted to rather update the base TypeTestCase since most people would probably use that class in their tests and not know about the other class. But I'm happy to make that change instead.

This still leaves the issue that it's not easy to register your own type extensions. You can pass it as the second argument to the `PreloadedExtension` class, but that is not very intuitive (I'm not sure if most people even know about this).
Having a method to register a type extension the same as the `getExtensions` method is a lot clearer and easier to use

2017-03-04 13:30 UTC, HeahDude requested changes

2017-03-04 13:30 UTC, HeahDude commented on src/Symfony/Component/Form/Test/TypeTestCase.php
> +            $validator->expects($this->any())->method('validate')->will($this->returnValue(array()));
Then only this line should be added in the proper validator extension base type, we don't need to add the extension overhead to all base tests.

2017-03-04 13:30 UTC, HeahDude commented on src/Symfony/Component/Form/Test/FormIntegrationTestCase.php
> +    protected function getTypeExtensions()
If this line were too be added in favor of:
```php
use Symfony\Component\Form\PreloadedExtension;

// ...

protected function getExtension()
{
    return array(new PreloadedExtension(
        array(new SomeType($this->getDependencyMock())),
        array(new SomeTypeExtension(new SomeService()),
        array(
            new SomeGuesser($this->getDependencyMock2()),
            new SomeOtherGuesser()),
    ));
}
```
We should also add two other protected functions for types and guessers, and add `addTypeGuessers` and `addTypes` call above as well to be consistent.

I would not vote against it, but I would vote for a better doc.

2017-03-06 07:37 UTC, pierredup commented
I created a separate PR (#21886) to address the validate method issue, which can go as a bug fix, and I updated this PR as a new feature to include extra helper methods to register form extensions for unit testing for DX

2017-03-06 07:52 UTC, xabbuh commented
:+1:

Status: Reviewed

2017-03-06 16:17 UTC, fabpot commented
Can you add a note in the CHANGELOG?

2017-03-06 18:22 UTC, fabpot commented
Thank you @pierredup.

2017-03-06 18:22 UTC, closed without merging

2017-03-06 18:23 UTC, fabpot commented
see 638bdc864f

2017-04-15 12:36 UTC, xabbuh commented on src/Symfony/Component/Form/Test/FormIntegrationTestCase.php
> +    protected function getTypedExtensions()
the method should IMO be named `getTypeExtensions()`