[Validator] Create timestamp validator
symfony/symfony pull request #21905
Opened 2017-03-06 21:07 UTC by lepiaf

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | yes?
| Tests pass?   | yes
| Fixed tickets | #11925
| License       | MIT
| Doc PR        | symfony/symfony-docs#7583

[x] create timestamp validator
[x] create documentation for timestamp validator
[] add deprecation on DateValidator, TimeValidator, DateTimeValidator

2017-03-07 12:33 UTC, javiereguiluz commented
Thanks for this contribution!

I've read the related discussion about I'm still not convinced about the `Timestamp` name. It's true that technically speaking, any date + time is a "timestamp" (see https://en.wikipedia.org/wiki/Timestamp) but I'm sure that when a developers see a "TimestampValidator", they are thinking about UNIX timestamps (e.g. `1256953732`).

Don't you think that "DateTime" is a better name? A "DateTime" can be a "date", a "time", a "date + time", a "UNIX timestamp", etc.

2017-03-07 17:54 UTC, HeahDude commented on src/Symfony/Component/Validator/CHANGELOG.md
> +3.4.0
It's still 3.3 :), same for all deprecation notices.

2017-03-11 10:15 UTC, lepiaf commented
I can rework DateTime validator to be more flexible and deprecate Date and Time validators only.

2017-03-30 15:19 UTC, stof requested changes

2017-03-30 15:19 UTC, stof commented on src/Symfony/Component/Validator/Constraints/Time.php
> + * @deprecated Since version 3.3, to be removed in 4.0. Use Symfony\Component\Validator\Constraints\DateTimeValidator instead.
you also need to add the E_USER_DEPRECATED on top of the file

2017-03-30 15:19 UTC, stof commented on src/Symfony/Component/Validator/Constraints/DateTime.php
> +        return array('format');
making it required is a BC break. It should keep the existing default

2017-04-03 17:07 UTC, xabbuh commented on src/Symfony/Component/Validator/CHANGELOG.md
> + * deprecate `DateValidator` in favor of `DateTimeValidator`
deprecated

2017-04-03 17:07 UTC, xabbuh commented on src/Symfony/Component/Validator/CHANGELOG.md
> + * deprecate `TimeValidator` in favor of `DateTimeValidator`
same here

2017-06-21 11:25 UTC, lepiaf commented
any comment about this pr ? should I change to branch 3.4 ?

2017-07-25 11:07 UTC, ro0NL reviewed
Should be 3.4 yes :)

What aboutd deprecating `\DateTime` instances as well? It's weird to use a datetime validator for an already valid datetime object.

Perhaps add constants for pre-defined formats, that be nice :) i.e. FORMAT_DATE/TIME/TIME_WITHOUT_SECONDS

2017-09-24 11:17 UTC, lepiaf commented
As I don't have time to work on this PR, I close it. Feel free to continue it :)

2017-09-24 11:17 UTC, closed without merging