[DependencyInjection] Handle void return types in closure-proxy
symfony/symfony pull request #21937
Opened 2017-03-08 22:57 UTC by pierredup

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | N/A
| License       | MIT
| Doc PR        | N/A

I recently got an error when registering an event listener that specifies a `void` return type. Dumping the container generates a closure proxy that always returns a value, which then conflicts with the return type hint.

E.G the following code is returned (some class names removed for readability)

```
$instance->addListener('kernel.view', /** @closure-proxy ... */ function (...\GetResponseForControllerResultEvent $event): void {
    return ${($_ = isset($this->services[listener']) ? $this->services['listener'] : $this->get('listener')) && false ?: '_'}->onKernelView($event);
}, 128);
```

This then causes the error `A void function must not return a value in ...`

So void return types should be handled by removing the `return` inside the closure

2017-03-09 08:18 UTC, nicolas-grekas reviewed
good catch

2017-03-09 08:18 UTC, nicolas-grekas commented on src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php
> +            $return = !method_exists($r, 'getReturnType') || 'void' !== (string) $r->getReturnType();
we should call `InheritanceProxyHelper::getTypeHint()` here instead

2017-03-09 08:18 UTC, nicolas-grekas commented on src/Symfony/Component/DependencyInjection/Tests/Dumper/PhpDumperTest.php
> +        $container = include self::$fixturesPath.'/containers/container35.php';
please give this file to a meaningful name (we're changing policy here, numbering is conflict prone)

2017-03-09 08:18 UTC, nicolas-grekas commented on src/Symfony/Component/DependencyInjection/Tests/Dumper/PhpDumperTest.php
> +        $this->assertStringEqualsFile(self::$fixturesPath.'/php/services35.php', $dumper->dump());
~~35~~

2017-03-10 06:47 UTC, nicolas-grekas approved these changes
:+1:

2017-03-10 09:05 UTC, stof requested changes

2017-03-10 09:05 UTC, stof commented on src/Symfony/Component/DependencyInjection/Tests/Dumper/PhpDumperTest.php
> +     * @requires PHP 7.0
7.1 actually

2017-03-10 09:11 UTC, nicolas-grekas commented on src/Symfony/Component/DependencyInjection/Tests/Fixtures/containers/container_dump_proxy_with_void_return_type.php
> +namespace Symfony\Component\DependencyInjection\Tests\Fixtures\Container35;
35 > Void ?

2017-03-10 09:24 UTC, nicolas-grekas commented
Thank you @pierredup.

2017-03-10 09:25 UTC, closed without merging