[DoctrineBridge][Routing] Require PSR-11 container instead of Symfony container
symfony/symfony pull request #21978
Opened 2017-03-11 19:20 UTC by enumag

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets |
| License       | MIT
| Doc PR        |

The changed classes can easily use PSR-11 container instead of normal symfony container.

I didn't change any classes that have the `$container` property as protected (for example Symfony\Bundle\FrameworkBundle\Translation\Translator) because I'm unsure whether that would be considered a BC break. Let me know if you want me to change such classes as well.

2017-03-11 19:28 UTC, nicolas-grekas commented
To me, it should be ok to change even when a protected property is involved: existing code won't break all of a sudden because of the less restrictive type hint. In any doubt, just to it in another PR to have this one merged earlier is this needs to be discussed.

2017-03-11 19:47 UTC, enumag commented
Alright, will do it in separate PR.

Also I didn't bother with deprecated classes like ContainerAwareEventDispatcher.

2017-03-12 08:32 UTC, GuilhemN requested changes
:+1: but the Routing component is no longer compatible with the DependencyInjection component <3.3 so it's requirements/conflicts should be updating.

2017-03-12 09:24 UTC, enumag commented
@GuilhemN Like this?

2017-03-12 09:31 UTC, GuilhemN approved these changes
Yes, that's it :+1;

2017-03-12 15:32 UTC, fabpot commented
Thank you @enumag.

2017-03-12 15:33 UTC, closed without merging