[Validator] Allow checkMX() to return false when $host is empty
symfony/symfony pull request #22109
Opened 2017-03-22 14:06 UTC by apetitpa

| Q | A |
| --- | --- |
| Branch? | master |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #22106 |
| License | MIT |
| Doc PR | n/a |

This should fix the email validator issue

2017-03-22 14:23 UTC, apetitpa commented
Sorry for the last commit, I rebased branch with master and didn't notice you already did.

2017-03-22 15:14 UTC, apetitpa commented
The hhvm build failed but it does not seem to be related to this PR.

2017-03-22 20:11 UTC, fabpot commented
The regex should not be changed. But the condition should indeed be added in other methods using checkdnsrr.

2017-03-23 08:38 UTC, apetitpa commented
thank you @fabpot and @jordscream I'll make some modifications, add unit tests and rebase my PR wwith 2.7

2017-03-23 08:41 UTC, xabbuh commented on src/Symfony/Component/Validator/Constraints/EmailValidator.php
> +        if (null === $host || '' === $host) {
`$host` can never be `null`, can it?

2017-03-23 08:41 UTC, xabbuh requested changes
Can you please also add a test to prevent future regressions?

2017-03-23 08:46 UTC, apetitpa commented on src/Symfony/Component/Validator/Constraints/EmailValidator.php
> +        if (null === $host || '' === $host) {
I think you're right, I'll fix this. Thank you

2017-03-23 12:17 UTC, jsamouh reviewed
What about unit test for the main issue ? ^^

2017-03-23 12:17 UTC, jordscream commented on src/Symfony/Component/Validator/Constraints/EmailValidator.php
> +
preferred empty host condition in return statement

2017-03-23 12:17 UTC, jordscream commented on src/Symfony/Component/Validator/Constraints/EmailValidator.php
>          return $this->checkMX($host) || (checkdnsrr($host, 'A') || checkdnsrr($host, 'AAAA'));
preferred empty host condition in return statement

2017-03-23 12:57 UTC, apetitpa commented
About the unit test for the main issue, since checkMX() and checkHost() are both private how can I test it ?

2017-03-23 13:04 UTC, jordscream commented
@apetitpa just test a use case  as "test@test@" or "test@" in the EmailValidator. It should return the appropriate violation

2017-03-23 13:12 UTC, apetitpa commented
Thank you @jordscream I forgot that the original issue was with emails containing @ twice

2017-03-23 13:25 UTC, Nek- commented on src/Symfony/Component/Validator/Constraints/EmailValidator.php
> +        return ('' !== $host) && checkdnsrr($host, 'MX');
why not `empty` check?

2017-03-23 13:32 UTC, apetitpa commented on src/Symfony/Component/Validator/Constraints/EmailValidator.php
> +        return ('' !== $host) && checkdnsrr($host, 'MX');
Well there is a similar check line 45 `if (null === $value || '' === $value)` that does not use the native empty function so I assumed I should do the same but maybe I was wrong ?

2017-03-23 13:42 UTC, fabpot commented on src/Symfony/Component/Validator/Constraints/EmailValidator.php
> +        return ('' !== $host) && checkdnsrr($host, 'MX');
We try to avoid using `empty` in Symfony.

2017-03-23 13:43 UTC, fabpot commented on src/Symfony/Component/Validator/Constraints/EmailValidator.php
> +        return ('' !== $host) && checkdnsrr($host, 'MX');
parentheses can be removed

2017-03-23 13:50 UTC, apetitpa commented on src/Symfony/Component/Validator/Constraints/EmailValidator.php
> +        return ('' !== $host) && checkdnsrr($host, 'MX');
I'll fix this in a minute thank you.

2017-03-23 13:59 UTC, jordscream commented
@apetitpa , it seems your unit test fails cause you do not check the appropriate violation

2017-03-23 14:02 UTC, apetitpa commented
@jordscream I think you're right I should check for MX_CHECK_FAILED_ERROR or HOST_CHECK_FAILED_ERROR

2017-03-23 14:05 UTC, Nek- commented on src/Symfony/Component/Validator/Constraints/EmailValidator.php
> +        return ('' !== $host) && checkdnsrr($host, 'MX');
@fabpot interesting, why? (is the reason documented somewhere?)

2017-03-23 14:12 UTC, fabpot commented on src/Symfony/Component/Validator/Constraints/EmailValidator.php
> +        return ('' !== $host) && checkdnsrr($host, 'MX');
`empty` is just too broad. For instance, it includes the `0` string as being `false`. Sometimes, that not desirable. So, we prefer to be very explicit about our expectations.

2017-03-23 20:17 UTC, ro0NL commented on src/Symfony/Component/Validator/Constraints/UrlValidator.php
> +            if ('' === $host || !checkdnsrr($host, 'ANY')) {
Perhaps switch to `!is_string($host)` due possible `false` or `null` return values.

2017-03-24 15:13 UTC, jordscream commented
@apetitpa . When you think to do it ? ^^. Need this fix for a customer :-P

2017-03-24 15:17 UTC, apetitpa commented on src/Symfony/Component/Validator/Constraints/UrlValidator.php
> +            if ('' === $host || !checkdnsrr($host, 'ANY')) {
I think this is a good idea. I'll do it thank you.

2017-03-24 15:28 UTC, apetitpa commented
@jordscream I hope this week-end but to be honest I'm facing difficulties creating an effective and working test for this issue. Some help would be appreciated.

2017-03-24 15:40 UTC, xabbuh commented
> Dont think it needs to be dns-senstive though, as there will be no network traffic for `foo@bar@`.

Agreed, the issue to fix is that the DNS functions should in fact not be called anymore.

2017-03-24 17:49 UTC, ro0NL commented on src/Symfony/Component/Validator/Constraints/EmailValidator.php
> +        return !empty($host) && checkdnsrr($host, 'MX');
Please avoid `empty` :) We expect a string, and only a empty string (`$host === ''`)  should not be passed to `checkdnsrr`.

2017-03-24 17:49 UTC, ro0NL commented on src/Symfony/Component/Validator/Tests/Constraints/EmailValidatorTest.php
> +    public function getCheckTypes()
Should be `provideCheckTypes` i guess, but it's a tiny semantic ;)

2017-03-24 20:02 UTC, apetitpa commented on src/Symfony/Component/Validator/Constraints/EmailValidator.php
> +        return !empty($host) && checkdnsrr($host, 'MX');
I know but `substr($value, strrpos($value, '@') + 1)` with `$value = foo@bar.fr@` returns `""` with PHP 7.* and `false` with PHP 5.6. So only checking for string emptiness is not enough.

2017-03-24 20:03 UTC, apetitpa commented on src/Symfony/Component/Validator/Tests/Constraints/EmailValidatorTest.php
> +    public function getCheckTypes()
I'll make the modification thank you

2017-03-24 20:08 UTC, ro0NL commented on src/Symfony/Component/Validator/Constraints/EmailValidator.php
> +        return !empty($host) && checkdnsrr($host, 'MX');
Let's cast the substring result above (or perhaps explicitly check for false); as currently we literally get `string('false')` as a replacement for `{{ value }}` in the violations above; due https://github.com/apetitpa/symfony/blob/master/src/Symfony/Component/Validator/ConstraintValidator.php#L139

So we got an extra (tiny) bug here ;-)

2017-03-24 22:12 UTC, apetitpa commented on src/Symfony/Component/Validator/Constraints/EmailValidator.php
> +        return !empty($host) && checkdnsrr($host, 'MX');
It's done, thank you

2017-03-27 10:33 UTC, apetitpa commented
@xabbuh is it ok now ?

2017-03-27 14:13 UTC, fabpot commented on src/Symfony/Component/Validator/Tests/Constraints/EmailValidatorTest.php
> +    public function provideCheckTypes()
Can you move the provider after the test (that's the convention we are using in Symfony).

2017-03-27 14:17 UTC, apetitpa commented on src/Symfony/Component/Validator/Tests/Constraints/EmailValidatorTest.php
> +    public function provideCheckTypes()
Of course, will do in a minute.

2017-03-29 07:07 UTC, xabbuh approved these changes
👍

2017-04-05 18:11 UTC, fabpot commented
Thank you @apetitpa.

2017-04-05 18:13 UTC, closed without merging