[Lock] Scoped Lock
symfony/symfony pull request #22115
Opened 2017-03-22 21:40 UTC by fbourigault

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | N/A
| License       | MIT
| Doc PR        | soon

This add to the just-born Lock component a scoped lock.

A scoped lock is a lock which will get automatically released when destructed.

## Usage

```php
class MyService
{
    private $lockFactory;

    public function __construct(LockFactoryInterface $lockFactory)
    {
        $this->lockFactory = $lockFactory;
    }

    public function run()
    {
        $lock = $this->lockFactory->createLock(__METHOD__);

       // some locked job

        if (/* early return test*/) {
            return; //the lock will be released when leaving the function scope.
        }
        
        try {
             //some other locked job
        } catch (\Exception $e) {
             //no need to release the lock. it will be automatically released when leaving the function scope.
        }
        
    } //lock is automatically released here
}
```

2017-03-22 21:45 UTC, fabpot commented
ping @jderusse

2017-03-22 21:48 UTC, fbourigault commented
Do we include the documentation in the main component PR, or I create a new one based on the first one?

2017-03-22 21:56 UTC, fbourigault commented
Tests are failing for php 7.1 with lowest dependencies. It does not looks related to my PR https://travis-ci.org/symfony/symfony/jobs/214019847#L3293-L3323.

2017-03-22 22:28 UTC, jderusse commented
Trying the solve test failure in https://github.com/symfony/symfony/pull/22119

2017-03-23 00:33 UTC, jderusse commented
LGTM.
This is a clever idea, and would simplify several use case of this component.

2017-03-23 01:55 UTC, robfrawley commented
While I generally think this is a great feature, there are some caveats to relying on the destructor for releasing locks where the Lock Component's destructor will not be called, causing the lock to persist, specifically:

- If `throw` is called in another destructor
- If `exit` is called in another destructor
- If `exit` is called from a shutdown function registered via `register_shutdown_function`
- If there is a fatal error

Depending on the lock `Store` used (for example, the `MemcachedStore` or `RedisStore` implementations, the lock will persist in all the above, and possibly other, cases. We should be clear about these caveats in the documentation for this PR, IMHO.

2017-03-23 02:05 UTC, jderusse commented
Stores are made to avoid to keep a lock for ever (segfault and brutal interrupt are handled) thank to the TTL mechanism (but it's not perfect)

But you're right. We can add to the list:
- if the variable is copied (stored in a kind of cache or whatever)
- after a circular reference assignment of the lock variable, we don't know when the GC will call the destructor

2017-03-23 05:51 UTC, fbourigault commented
@robfrawley, all cases you listed are not specific to the scoped lock. So like @jderusse said, you can only rely on the lock timeout.

What about a warning in the scoped lock dock about the two points @jderusse listed?

2017-03-23 09:33 UTC, greg0ire requested changes
Very nice contribution!

2017-03-23 09:33 UTC, greg0ire commented on src/Symfony/Component/Lock/Factory.php
> +        $lock = $this->createLock($resource, $ttl);
Thoughtless OTV, consider removing it.

2017-03-23 09:33 UTC, greg0ire commented on src/Symfony/Component/Lock/Factory.php
> +     * @param float  $ttl      maximum expected lock duration
In what unit? Please document that.

2017-03-23 09:33 UTC, greg0ire commented on src/Symfony/Component/Lock/ScopedLock.php
> + * ScopedLock encapsulate a LockInterface which is automatically released when destructed.
"encapsulateS"

2017-03-23 09:33 UTC, greg0ire commented on src/Symfony/Component/Lock/ScopedLock.php
> +     * Automatically release the underlying lock when object is destructed.
"when the object"

2017-03-23 09:56 UTC, fbourigault commented
Broken tests are addressed in https://github.com/symfony/symfony/pull/22122

2017-03-23 12:12 UTC, fbourigault commented
@greg0ire I addressed all changes you requested.
I also added parameters description for `Lock`.

2017-03-23 13:30 UTC, greg0ire approved these changes
:ok_hand:

2017-03-23 14:06 UTC, robfrawley commented
@fbourigault I just think we should mention these caveats in the documentation PR, is all.

2017-03-23 15:04 UTC, nicolas-grekas commented
I'm :-1:  here. This makes releasing totally implicit. That's a foot gun to me.
- HHVM doesn't have the same destructing rules than PHP (they can even be *not* called)
- when a custom error handler keeps the $context, the lock will not be released
- same in the cases listed by @robfrawley (gc, stack traces, etc.)

Adding a decorator to provide an unreliable behavior looks like... unreliable, thus my stand.
If you want that, but in a predictable way, just wrap in a try+finally block.

2017-03-23 21:57 UTC, fabpot commented
Closing for the reasons explained by @nicolas-grekas

2017-03-23 21:57 UTC, closed without merging