[Component][Form][ChoiceType] : Add new option to sort group_by value
symfony/symfony pull request #22136
Opened 2017-03-23 23:00 UTC by jordscream

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #21717 
| License       | MIT
| Doc PR        | symfony/symfony-docs

A Proposal PR to have the possibility to define an order for group_by value without create a difficult twig rendering or override buildView Form

2017-03-23 23:09 UTC, jordscream commented
@HeahDude , @stof , a PR proposal : New option group_by_order to manage the group order
Tell me WDYT

2017-03-30 13:32 UTC, stof requested changes

2017-03-30 13:32 UTC, stof commented on src/Symfony/Component/Form/ChoiceList/Factory/DefaultChoiceListFactory.php
> +                uksort($otherViews, function ($key1, $key2) use ($groupByOrder) {
this logic does not seem to support callable values for `$groupByOrder`, while the interface allows it (and callables can be arrays, making things even worse).

2017-03-30 13:32 UTC, stof commented on src/Symfony/Component/Form/ChoiceList/Factory/ChoiceListFactoryInterface.php
> +    public function createView(ChoiceListInterface $list, $preferredChoices = null, $label = null, $index = null, $groupBy = null, $attr = null, $groupByOrder = null);
adding arguments in an interface is forbidden by our BC policy

2017-03-30 13:32 UTC, stof commented on src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php
> +        $resolver->setAllowedTypes('group_by_order', array('null', 'array', '\Traversable'));
this does not match the types supported by the implementation.

2017-03-30 13:32 UTC, stof commented on src/Symfony/Component/Form/ChoiceList/Factory/PropertyAccessDecorator.php
> +     * @param null|array|callable|string|PropertyPath $groupByOrder     The groupBy order
this does not support a PropertyPath, as you don't handle it

2017-03-30 13:33 UTC, stof commented on src/Symfony/Component/Form/ChoiceList/Factory/CachingFactoryDecorator.php
> +    public function createView(ChoiceListInterface $list, $preferredChoices = null, $label = null, $index = null, $groupBy = null, $attr = null, $groupByOrder = null)
The new value must be taken into account when building the cache key, otherwise a list could be reused while it was having a different order

2017-03-31 07:38 UTC, jordscream commented
@stof thanks for your review. If adding a parameter is a BC break, do you have an advice to deal a new parameter ? or do it differently ?

2017-03-31 14:22 UTC, colinodell commented on src/Symfony/Component/Form/ChoiceList/Factory/DefaultChoiceListFactory.php
> +                uksort($otherViews, function ($key1, $key2) use ($groupByOrder) {
I'd like to see this support both callables and predefined arrays.  Something like this should work:

```php
if ($groupByOrder) {
    if (is_callable($groupByOrder)) {
        // TODO
    } elseif (is_array($groupByOrder)) {
        // TODO
    }
}
```

2017-03-31 14:23 UTC, colinodell commented on src/Symfony/Component/Form/ChoiceList/Factory/PropertyAccessDecorator.php
> +     * @param null|array|callable|string|PropertyPath $groupByOrder     The groupBy order
Does `PropertyPath` even make sense here?

2017-04-05 14:18 UTC, jordscream commented on src/Symfony/Component/Form/ChoiceList/Factory/DefaultChoiceListFactory.php
> +                uksort($otherViews, function ($key1, $key2) use ($groupByOrder) {
@colinodell , thanks 
Can you give me an example of callable groupByOrder you need ?
Which parameters you need in the function ?

2017-04-05 14:22 UTC, jordscream commented
@stof a little ping on my comments to continue the PR if you want ^^

Also, same remark as @colinodell , How do you see the callable groupByOrder ? Which parameters we propose in the callable function ?

2017-04-05 15:04 UTC, colinodell commented on src/Symfony/Component/Form/ChoiceList/Factory/DefaultChoiceListFactory.php
> +                uksort($otherViews, function ($key1, $key2) use ($groupByOrder) {
The callable should be compatible with `uksort` - anything that takes two parameters, compares them, and returns an integer.  Your code would then look something like this:

```
if ($groupByOrder) {
    if (is_callable($groupByOrder)) {
        uksort($otherViews, $groupByOrder);
    } elseif (is_array($groupByOrder)) {
        // TODO: Your existing code goes here
    }
}
```

I could then use any type of callable for the `groupByOrder` option:

 - `'strnatcmp'` - Sort them using a "natural order" algorithm via the `strnatcmp()` function
 - `[$this, 'sortGroups']` - Use the `sortGroups()` function on `$this`
 - `[Foo::class, 'sortGroups']` - Use the static `sortGroups()` function from the `Foo` class
 - `function ($a, $b) { return $b <=> $a; }` - Use some anonymous function

2017-04-05 17:56 UTC, jordscream commented on src/Symfony/Component/Form/ChoiceList/Factory/DefaultChoiceListFactory.php
> +                uksort($otherViews, function ($key1, $key2) use ($groupByOrder) {
@colinodell thanks, will do that soon

2017-04-11 09:15 UTC, jordscream commented
ping @stof

2017-10-08 15:54 UTC, nicolas-grekas commented
Moving to 4.1. Rebase on master might be needed, where PHP 7.1 features can be used btw.

2019-04-06 15:25 UTC, webmozart commented
I'm :-1: on this feature. The problem solved here can easily be solved by sorting the choices before passing them to the `choices` option (either with `usort()` or - better - in the database).

2019-04-06 15:34 UTC, closed without merging

2019-04-06 15:57 UTC, webmozart commented
@fabpot https://github.com/symfony/symfony/issues/21717 should be closed as well.