[Console] Support formatted text cutting
symfony/symfony pull request #22225
Opened 2017-03-30 18:02 UTC by ro0NL

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes/no
| Fixed tickets | #... 
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

allows cutting a formatted text to a certain width. Actually needed if we want to support max. column widths (see #22156)

```php
$text = 'pre <error>foo bar baz</error> post';
dump('BEFORE');
$output->writeln(wordwrap($output->getFormatter()->format($text), 3, "\n", true), OutputInterface::OUTPUT_RAW);
dump('AFTER');
$output->writeln($output->getFormatter()->format($text, 3), OutputInterface::OUTPUT_RAW);
```

![image](https://cloud.githubusercontent.com/assets/1047696/24518880/9925dd78-1583-11e7-83b8-54ad79aca1e1.png)

Im considering to separate `cut()` and `format()` so you can also cut it without applying any style.

2017-04-03 08:23 UTC, nicolas-grekas commented on src/Symfony/Component/Console/Formatter/OutputFormatter.php
> +     * {@inheritdoc}
does this patch apply to lower branches? if yes, should be done there

2017-04-03 08:26 UTC, nicolas-grekas requested changes

2017-04-03 08:26 UTC, nicolas-grekas commented on src/Symfony/Component/Console/Formatter/OutputFormatter.php
> +     * {@inheritdoc}
that one is not possible: $width is not in the interface, thus should be documented here

2017-04-03 08:26 UTC, nicolas-grekas commented on src/Symfony/Component/Console/Formatter/OutputFormatterInterface.php
> +    public function format($message/*, $width = 0*/);
Changing an interface like that is a hard BC break. Any one implementing it without extending `OutputFormatter` will get no deprecation warning.

2017-04-03 08:41 UTC, ro0NL commented on src/Symfony/Component/Console/Formatter/OutputFormatter.php
> +     * {@inheritdoc}
Will look into that.

2017-04-03 08:42 UTC, ro0NL commented on src/Symfony/Component/Console/Formatter/OutputFormatterInterface.php
> +    public function format($message/*, $width = 0*/);
Any suggestions? Took this approach from  `LogoutUrlGenerator::registerListener` ;) which is not bound to an interface.

Note that this way is the easiest implementation and avoids double processing the formatted text, which is nice.

2017-04-07 13:39 UTC, ro0NL commented
Approach updated.. not sure this makes sense either :P but im concerning users extending from `OutputFormatter` as well as implementing `OutputFormatterInterface.

Guess i like the `format($message, $width = 0)` api.. but maybe the new interface should simply define `wrapAndFormat($message, $width)` or so.. and let `format()` forward.

2017-10-08 15:58 UTC, nicolas-grekas commented
Moving to 4.1. Rebase on master might be needed, where PHP 7.1 features can be used btw.

2018-03-31 06:09 UTC, fabpot commented
@ro0NL Can you tell us the status of this PR? Looks like it should be rebased.

2018-03-31 08:52 UTC, ro0NL commented
@fabpot is the current upgrade path OK? If so, suggestions for naming `WrappableOutputFormatterInterface` welcome :) 

but i was hoping we eventually dont need this interface and have `OutputInterface::format($message, $width = 0)` API... but the current BC policy doesnt allow that right? Hence we're stuck with this interface.

2018-04-04 12:15 UTC, fabpot requested changes

2018-04-04 12:15 UTC, fabpot commented on src/Symfony/Component/Console/Formatter/OutputFormatter.php
> +                    @trigger_error(sprintf('Method "%s()" will have a 2nd `$width = 0` argument in version 5.0. Not defining it is deprecated since 4.1.', __METHOD__), E_USER_DEPRECATED);
`... in version 5.0, not defining it is deprecated since Symfony 4.1`

2018-04-04 12:15 UTC, fabpot commented on src/Symfony/Component/Console/Formatter/OutputFormatter.php
> +                    @trigger_error(sprintf('Method "%s()" will have a 2nd `$width = 0` argument in version 5.0. Not defining it is deprecated since 4.1.', __METHOD__), E_USER_DEPRECATED);
I don't understand why you want to force people to define the `$width`. Not setting it explicitly seems fine to me.

2018-04-04 16:09 UTC, ro0NL commented
I think the upgrade path is OK now. But i need to have a 2nd look at the fix.. cause im getting different results now as before.

2018-04-04 16:15 UTC, ro0NL commented
OK something spiffy is going on

![image](https://user-images.githubusercontent.com/1047696/38320119-f93ac272-3833-11e8-9622-42a47c8ff947.png)

without any src changes etc. in between.. in PHPstorm it seems to consistently format wrong.

Curious if this can be confirmed on some other terminal also.

2018-04-04 16:16 UTC, ro0NL commented
It seems to break as soon as it breaks out the window, thus creates a scrollbar. WTF :)

2018-09-04 15:41 UTC, fabpot commented
@ro0NL What do we do here?

2018-09-04 16:50 UTC, ro0NL commented
@fabpot rebased. The breaking formatting is unrelated (#27832), so if tests are still passing im :+1: to merge. But let me add some rendering tests tomorrow.

2018-09-04 16:54 UTC, ro0NL commented
And perhaps rethink `WrappableOutputFormatterInterface`, overriding the definition of `OutputFormatterInterface::format()`.

Perhaps more explicit `WrappableOutputFormatterInterface::formatAndWrap(string $message, int $width)` and let the implementation forward to `format($message, $width)`, where `OutputFormatter::format()` still supports the 2nd arg, but not as part of the interface..

2018-09-04 17:06 UTC, ro0NL commented
Updated. Much cleaner IMHO.

2018-09-04 17:14 UTC, fabpot approved these changes
Looks much better to me

2018-09-04 20:06 UTC, chalasr approved these changes

2018-09-04 20:11 UTC, chalasr commented
Nice one!nks Roland.

2018-09-04 20:11 UTC, merged