[HttpKernel] minor: add ability to construct with headers on http exceptions
symfony/symfony pull request #22228
Opened 2017-03-30 22:11 UTC by gsdevme

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        | 

This adds the ability to set the headers for the exception within the constructor.

With alot of the following exceptions its sometimes very useful to be able to set the headers. For example with a reverse proxy cache (Varnish) if you want to match the `Retry-After` with a Varnish cache header to protect the backend. 

I see that `setHeaders()` did get added https://github.com/symfony/symfony/commit/6a1080f899f0661a2724d81f6629d4ca7009f16b but that means the exception needs to be assigned to a variable and set and then thrown, it also doesn't merge with the existing header set in some of the constructors. 

I've chosen to `array_merge()` where key/values were being set within the constructor as I think this is the most useful and 'correct' whereas `setHeaders` is explicit that its setting not amending or adding to.

2017-04-03 08:22 UTC, nicolas-grekas commented
All the array_merge would be replaced by a simple affectation: `$headers['Foo'] = 'bar';`

2017-04-07 10:22 UTC, gsdevme commented
@nicolas-grekas Thanks! Good spot, will update.

2017-04-09 09:09 UTC, Nek- approved these changes
LGTM

2017-04-09 09:34 UTC, stloyd requested changes

2017-04-09 09:34 UTC, stloyd commented on src/Symfony/Component/HttpKernel/Exception/UnauthorizedHttpException.php
> +        $headers = array_merge($headers, array('WWW-Authenticate' => $challenge));
Why merge here & not direct set as in other places?

2017-04-09 09:34 UTC, stloyd commented on src/Symfony/Component/HttpKernel/Exception/TooManyRequestsHttpException.php
> +            $headers = array_merge($headers, array('Retry-After' => $retryAfter));
Again, why merge?

2017-04-09 13:23 UTC, gsdevme commented
An oversight, will fix the others up also.

2017-04-11 06:50 UTC, nicolas-grekas commented
Status: needs work

2017-04-20 15:44 UTC, gsdevme commented
Updated.

2017-10-08 16:00 UTC, nicolas-grekas approved these changes

2017-10-08 18:51 UTC, xabbuh approved these changes

2017-10-08 23:42 UTC, fabpot approved these changes

2017-10-08 23:43 UTC, fabpot commented
Thank you @gsdevme.

2017-10-08 23:43 UTC, merged

2018-03-30 10:09 UTC, gsdevme commented
For future reference although this has a milestone of 3.4, its only in 4.0+