[Yaml] Add support for ::class constants
symfony/symfony pull request #22245
Opened 2017-04-02 22:57 UTC by ostrolucky

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

Current parser doesn't recognize FCQN constants via !php/const prefix, which means users have to define it as a regular string and they loose the checking if class/constant exists. This patch brings Yaml constant support a bit closer to native PHP constant resolving.

2017-04-02 23:56 UTC, phansys requested changes
Status: Needs work.

2017-04-02 23:56 UTC, phansys commented on src/Symfony/Component/Yaml/Inline.php
> +                            if (class_exists($constWithoutClassSuffix = str_replace('::class', '', $const))) {
What if the constant is called `classy`?

2017-04-03 05:03 UTC, GuilhemN commented
The `::class` constant works even if the class doesn't exist, having a different behavior in the yaml parser would be inconsistent.
So I don't see what we gain over a regular string.
I'm :-1: for now.

2017-04-03 06:36 UTC, iltar commented
I agree with @GuilhemN here:
```yml
foo: !php/const:Foo\Bar\Baz::class
# which is exactly the same as
foo: Foo\Bar\Baz
```

2017-04-03 06:50 UTC, ostrolucky commented
You are right

2017-04-03 06:50 UTC, closed without merging

2017-04-03 09:19 UTC, stof commented on src/Symfony/Component/Yaml/Inline.php
> +                            if (class_exists($constWithoutClassSuffix = str_replace('::class', '', $const))) {
if it is named, classy, it is a real constant, so the existing logic applies