[Console] Make SymfonyQuestionHelper::ask optional by default
symfony/symfony pull request #22317
Opened 2017-04-06 16:52 UTC by ro0NL

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | yes
| Tests pass?   | yes (nothing in core depends on it)
| Fixed tickets | #... 
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

i noticed when writing commands i always keep doing

```php
$io = new SymfonyStyle($input, $output);
$answer = $io->ask('...', null, function ($value) { return $value; });

// instead of just
$answer = $io->ask('...');
```

only to bypass a built-in validation, of which im not sure why it's there. Note the base question helper doesnt make this assumption...

2017-04-06 16:57 UTC, chalasr commented
👍  Already pointed out in https://github.com/symfony/symfony/pull/20141 when making it more flexible, I don't know why this default validator has been added, console's Symfony* stuff should only be about output styling, not input filtering.

2017-04-06 17:32 UTC, ro0NL commented on src/Symfony/Component/Console/Helper/SymfonyQuestionHelper.php
> +     * @deprecated since version 3.3, to be removed in 4.0
Not sure about this.. it creates some nasty strikethroughs in IDE's, and the same method call will work in 4.0

2017-04-06 18:01 UTC, chalasr commented on src/Symfony/Component/Console/Helper/SymfonyQuestionHelper.php
> +     * @deprecated since version 3.3, to be removed in 4.0
Indeed, I think I would talk only about the removed validation. Btw this needs to be documented :)

2017-04-28 17:46 UTC, nicolas-grekas commented
Moving to milestone 3.4 as this is not a blocker for 3.3. If you don't agree, please tell :)

2017-04-28 17:50 UTC, ro0NL commented
Just annoying :) :+1: for 3.4, im used doing this already.

2017-07-20 10:18 UTC, chalasr approved these changes

2017-07-20 17:24 UTC, fabpot approved these changes

2017-07-20 17:27 UTC, fabpot requested changes
Target should also be changed to 3.4.

2017-07-20 17:27 UTC, fabpot commented on UPGRADE-3.3.md
> + * The `SymfonyQuestionHelper::ask` default validation has been deprecated and will be removed in 4.0. Apply validation using `Question::setValidator` instead.
should be moved to 3.4.

2017-07-20 17:27 UTC, fabpot commented on src/Symfony/Component/Console/Helper/SymfonyQuestionHelper.php
> +                    @trigger_error('The default question validator is deprecated since Symfony 3.3 and will not be used anymore in version 4.0. Set a custom question validator if needed.', E_USER_DEP
3.4 instead of 3.3

2017-07-22 18:24 UTC, chalasr commented
Thank you @ro0NL

2017-07-22 18:24 UTC, closed without merging

2017-07-26 06:50 UTC, nicolas-grekas commented on src/Symfony/Component/Console/Helper/SymfonyQuestionHelper.php
> +                    @trigger_error('The default question validator is deprecated since Symfony 3.4 and will not be used anymore in version 4.0. Set a custom question validator instead.', E_USER_DEPRE
@ro0NL is this really in the correct code path? Throwing both a deprecation and an exception is suspicious to me.

2017-07-26 07:58 UTC, chalasr commented on src/Symfony/Component/Console/Helper/SymfonyQuestionHelper.php
> +                    @trigger_error('The default question validator is deprecated since Symfony 3.4 and will not be used anymore in version 4.0. Set a custom question validator instead.', E_USER_DEPRE
indeed, the deprecation should be triggered before the if statement.

2017-07-26 08:39 UTC, ro0NL commented on src/Symfony/Component/Console/Helper/SymfonyQuestionHelper.php
> +                    @trigger_error('The default question validator is deprecated since Symfony 3.4 and will not be used anymore in version 4.0. Set a custom question validator instead.', E_USER_DEPRE
We're deprecating the fact this exception is thrown when the value is blank. Meaning in 4.0 ask() is optional by default, whereas now it's required by default.

I actually considered putting the trigger above `if (!is_array($value) && !is_bool($value) && 0 === strlen($value)) {`, but its weird to get the deprecation for a case that doesnt change in 4.0.

2017-07-26 08:47 UTC, ogizanagi commented on src/Symfony/Component/Console/Helper/SymfonyQuestionHelper.php
> +                    @trigger_error('The default question validator is deprecated since Symfony 3.4 and will not be used anymore in version 4.0. Set a custom question validator instead.', E_USER_DEPRE
Indeed, I think it's the right place for this deprecation.