Add check_path option to json_login listener
symfony/symfony pull request #22425
Opened 2017-04-13 18:08 UTC by chalasr

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no, master only
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #21948, ~~#22423~~
| License       | MIT
| Doc PR        | n/a

The listener should not attempt authentication on every requests, but on a predefined route only.

2017-04-13 18:19 UTC, lsmith77 commented
as pointed out in #21948 I think it makes sense to make this feature stateful and then it makes sense to support the check_path properly.

another optional thing one could add to this is a check if the `Content-type` of the request is a json request .. something like:
```
if ('json' !== $request->getRequestFormat()) {
    return;
}
```

2017-04-13 18:25 UTC, chalasr commented
@lsmith77 I just made the `check_path` optional, because people may effectively use this on every request. 

My personal use case is the following:
a) Send username/password to e.g. /login_check (check_path) and if everything is ok, get a token (e.g. JWT)
b) Pass the token for each request which requires one

In this case, I do need to be able to define the path that this listener should cover. I think most use cases for this listener will look like mine. But for those who want their users to resend username/password on each request, why not.

2017-04-13 18:28 UTC, lsmith77 commented
my point above regarding checking the content type is so that one could use `form_login` and `json_login` in parallel on the same routes and within the same firewall

2017-04-13 18:42 UTC, chalasr commented
Sounds good to me. I think it should be discussed separately though, I'll open another PR if you don't do it before.

2017-04-13 18:43 UTC, dmaicher commented on src/Symfony/Component/Security/Http/Firewall/UsernamePasswordJsonAuthenticationListener.php
>          $data = json_decode($request->getContent());
This could be moved below the check? Not that expensive but still.

2017-04-13 18:51 UTC, chalasr commented on src/Symfony/Component/Security/Http/Firewall/UsernamePasswordJsonAuthenticationListener.php
>          $data = json_decode($request->getContent());
indeed, fixed

2017-04-13 18:52 UTC, chalasr commented on src/Symfony/Bundle/SecurityBundle/Tests/Functional/app/JsonLogin/config.yml
> +               check_path:    /chk
looks like the author expected the `check_path` to work already :)

2017-04-13 18:54 UTC, dunglas approved these changes

2017-04-13 18:55 UTC, dmaicher commented on src/Symfony/Bundle/SecurityBundle/Tests/Functional/app/JsonLogin/config.yml
> +               check_path:    /chk
Indeed :blush: I think initially it was not stateless and used the check_path:

https://github.com/symfony/symfony/pull/18952#issuecomment-224635760

2017-04-13 18:57 UTC, dmaicher approved these changes

2017-04-13 19:42 UTC, dunglas commented
I propose to mark this feature as `@experimental` for now.

2017-04-13 19:46 UTC, chalasr commented
If we talk about the whole `json_login` listener, I agree. Shall I do it here?

2017-04-13 20:00 UTC, dunglas commented on src/Symfony/Bundle/SecurityBundle/Tests/Functional/app/JsonLogin/config.yml
> +               check_path:    /chk
Yes, it was the idea.

2017-04-13 20:17 UTC, lsmith77 commented
BTW the constructor signature now looks pretty much like that of `AbstractAuthenticationListener` .. with the main difference left is that the options I guess are not all the same.

2017-04-13 20:22 UTC, chalasr commented
@lsmith77 The abstract one offers a bit too much "stateful" stuff, its main methods couldn't be reused as is. I would keep this one standalone right now, flagging as experimental will give time to factorize as needed anyway.

2017-04-13 20:32 UTC, lsmith77 commented
sure .. thought it might mean the abstract class should maybe be refactored at some point

2017-04-13 20:50 UTC, chalasr commented
@dunglas flag added in e94b5e4cee5d2129d0884ab24d20dd10a4cdda7e

2017-04-14 20:16 UTC, phansys requested changes
Status: Needs work.

2017-04-14 20:16 UTC, phansys commented on src/Symfony/Component/Security/Http/Tests/Firewall/UsernamePasswordJsonAuthenticationListenerTest.php
> +        $this->assertEquals('ok', $event->getResponse()->getContent());
Please, use `assertSame()` instead.

2017-04-15 11:09 UTC, chalasr commented
@phansys fixed.

2017-04-17 08:59 UTC, lsmith77 approved these changes
:+1:

I will propose a content type check in another PR

2017-04-17 12:23 UTC, phansys approved these changes

2017-04-18 22:21 UTC, fabpot commented
Thank you @chalasr.

2017-04-18 22:22 UTC, closed without merging

2017-04-19 20:24 UTC, lsmith77 commented
as promised here is the follow up https://github.com/symfony/symfony/pull/22477