[VarDumper] Add date caster
symfony/symfony pull request #22431
Opened 2017-04-14 01:17 UTC by maidmaid

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | /
| License       | MIT
| Doc PR        | /

I propose next fields:
- ``literal``: gives day of week and simplify date readability,
- ``timestamp``: gives date in useful unix format,
- ``timezone``: combines name, country code and diff to GMT and without useless ``timezone_type``,
- ``Δnow``: is the delta compared to now, usefull to a birthdate or a deadline.

![screenshot from 2017-04-14 03-01-00](https://cloud.githubusercontent.com/assets/4578773/25029530/9fdfd7f4-20be-11e7-83cb-b416b87baee7.png)

Todo:
- [x] cast date
- [ ] cast date interval
- [ ] add tests
- [ ] update doc

2017-04-14 14:51 UTC, fabpot commented
/cc @nicolas-grekas

2017-04-14 16:57 UTC, ro0NL commented
Btw.. about the timezone. Maybe put the offset in front, this is the part i usually care about;

```
timezone: '+02:00 (Europe/Amsterdam)'
```

2017-04-14 17:43 UTC, ro0NL commented on src/Symfony/Component/VarDumper/Caster/DateCaster.php
> +            $prefix.'Δnow' => (new DateTime())->diff($d)->format('%R %yy %mm %dd %H:%I:%S'),
Needs a `setTimezone($d->getTimezone())` right?

2017-04-14 19:31 UTC, maidmaid commented on src/Symfony/Component/VarDumper/Caster/DateCaster.php
> +            $prefix.'Δnow' => (new DateTime())->diff($d)->format('%R %yy %mm %dd %H:%I:%S'),
Good catch!

2017-04-14 20:33 UTC, maidmaid commented
![screenshot from 2017-04-14 22-30-46](https://cloud.githubusercontent.com/assets/4578773/25055279/1b570968-2162-11e7-8a33-68dc5c0da776.png)
WDYT of this variant?

2017-04-16 08:30 UTC, ro0NL commented
Not sure.. it looks a bit more chaotic imo.

2017-04-30 13:14 UTC, maidmaid commented
``literal`` and ``timestamp`` are not visible if they are nested or if we flag with ``EXCLUDE_VERBOSE``. I have too add tests.

2017-04-30 16:09 UTC, stof requested changes

2017-04-30 16:09 UTC, stof commented on src/Symfony/Component/VarDumper/Caster/DateCaster.php
> +class DateCaster
should be named `DateTimeCaster` IMO

2017-04-30 16:09 UTC, stof commented on src/Symfony/Component/VarDumper/Caster/DateCaster.php
> +use DateTimeInterface;
We never add use statements for global classes

2017-04-30 16:15 UTC, robfrawley commented
@maidmaid I was a fan of the first proposal. The unix time is almost always the most important field to me (though this could depend on the operating system one uses, I guess).

2017-05-01 13:51 UTC, maidmaid commented on src/Symfony/Component/VarDumper/Caster/DateCaster.php
> +class DateCaster
In a next PR, I would cast other date classes like ``DateInterval``. It's why a generic ``DateCaster`` is better IMO.

2017-05-01 14:08 UTC, maidmaid commented
@robfrawley Yes, unix time can be usefull, but it's a machin format and we should favor human representation, IMO.

2017-05-01 14:12 UTC, ogizanagi commented
@maidmaid : It depends on the situation, but you might be happy to have the unix time while debugging. And I'm mainly using the var-dumper component for debugging purpose 😄

2017-05-01 19:01 UTC, maidmaid commented on src/Symfony/Component/VarDumper/Caster/DateCaster.php
> +use DateTimeInterface;
Removed

2017-05-01 19:04 UTC, maidmaid commented
We have lots of different interesting opinions. @nicolas-grekas, can you give your opinion?

2017-05-02 10:11 UTC, nicolas-grekas commented
May I propose something different:
always display a single line that represents 100% of the state of the objects: `'Y-m-d H:i:s.u e'`
then lets provide more details on hover (... from now, literal, etc as a single "title" line).
This is doable with a single virtual propery holding a ConstStub I think.

2017-05-02 10:42 UTC, maidmaid commented
> then lets provide more details on hover

But works it with ``CliDumper``?

2017-05-02 10:43 UTC, nicolas-grekas commented
CliDumper will display only `Y-m-d H:i:s.u e`, but this LGTM, that's still 100% of the state.

2017-05-02 10:57 UTC, nicolas-grekas commented
For the reader: when I saw that, I first thought "hey, this is hiding the actual internal structure of DateTime objects" (by not telling about these existing public props.)
The I ran this: https://3v4l.org/uWc54
I looks like doing var_dump/array-cast actually *creates* the 3 props...
So I'm even more in favor of doing something here, and I would add DateTimeZone, etc. to the list of classes that should display only virtual props.

2017-05-02 11:20 UTC, maidmaid commented
When we var_dump a ``DateTime`` object, we can see 3 props in all but 2 distinct props: date and timezone. So, ``DateCaster`` should cast a ``date`` prop that represents 100% of date/time infos (with more details on hover), and a ``timezone`` prop that shows a ``DateTimeZone`` thanks to an other caster (that is already in WIP [here](https://github.com/maidmaid/symfony/compare/master...datecaster-datezone#diff-959db3511f6175d0172b859e897e62dbR113)). Right?

2017-05-02 11:26 UTC, nicolas-grekas commented
worth a try yes :)

2017-05-02 11:53 UTC, maidmaid commented
As discussed:

![screenshot from 2017-05-02 13-40-00](https://cloud.githubusercontent.com/assets/4578773/25616582/fd6129d6-2f3d-11e7-842c-d7f96fb39af5.png)

Too bad it is not possible to copy timestamp and to see extra info in CLI with this version. More, I find it strange to use ``ConstStub`` to shows extra in hover, it seems as a hack.

2017-05-02 12:02 UTC, nicolas-grekas commented
Personally, I like compact formats, that give me everything in a snap.
I would also remove the timezone prop in fact, and add the "e" modifier at the end of the date string.
Nesting is an opportunity to be hit by depth limitings, better not.
Copy/pasting the timestamp looks like something I wouldn't do very often to me (especially since it's destructive compared to a DateTime object).
Of course, that's only my personal PoV :)

2017-05-02 12:11 UTC, nicolas-grekas commented
What about displaying the timestamp could be displayed next to the class name `DateTime @123456789 { ... }`? Should be just a matter of appending it to the `$stub->class` prop.

2017-05-02 12:13 UTC, nicolas-grekas commented on src/Symfony/Component/VarDumper/Caster/DateCaster.php
> +                (new \DateTime('now', $d->getTimezone()))->diff($d)->format('%R %yy %mm %dd %H:%I:%S')
`$d->getTimezone()` is not required in this context

2017-05-02 14:04 UTC, maidmaid commented
I putted timestamp in ``$stub->class`` and display timezone in ``date`` virtual prop (used ``P`` instead ``e`` because ``+02:00`` is more informative that ``Europe/Zurich``):

![screenshot from 2017-05-02 15-56-31](https://cloud.githubusercontent.com/assets/4578773/25620953/49e8155a-2f50-11e7-9f73-d40ed0e0866e.png)

2017-05-02 14:04 UTC, maidmaid commented on src/Symfony/Component/VarDumper/Caster/DateCaster.php
> +                (new \DateTime('now', $d->getTimezone()))->diff($d)->format('%R %yy %mm %dd %H:%I:%S')
Removed

2017-05-02 14:09 UTC, nicolas-grekas commented
Do you like it? I think I do :)

> used P instead e because +02:00 is more informative

in fact, that's not true: `Europe/Zurich` contains geographical/political info that makes it very different from `+02:00`.
See http://stackoverflow.com/questions/17694894/different-timezone-types-on-datetime-object

2017-05-02 14:21 UTC, maidmaid commented
Yes, I find this version quite elegant :)

About timezone, I think that we have to know difference to GMT when we debug a date but not its geographical/political infos. Are you agree?

My only little remark rests on ``ConstStub`` hack usage to showing extra infos when ``[ConstStub] Represents a PHP constant and its value``.

2017-05-02 14:27 UTC, nicolas-grekas commented
> know difference to GMT when we debug a date but not its geographical/political infos

but this prevents knowing if the timezone of a DateTime is of type 3 or not. And since this is of significant importance (see SO), I think we should use "e".

About ConstStub, I'd say we don't really care :)

2017-05-02 14:41 UTC, maidmaid commented
What about to have ``P (e)`` format, like ``+02:00 (Europe/Zurich)``? We have diff to GMT + geo info + type; everybody is happy like that :smile:

2017-05-02 15:49 UTC, nicolas-grekas commented
Not sure:
```php
$a = new \DateTime('now');
$a->setTimezone(new DateTimezone('GMT+2'));
echo $a->format('P e');
// output: +02:00 +02:00
```

2017-05-02 16:01 UTC, maidmaid commented
This kind of notation (``GMT+n`` and others) is not recommanded by PHP; only the ``Europe/Zurich``-like is the good way. See warnings here http://php.net/manual/en/timezones.others.php. Following these recommendations, ``P (e)`` format displays fine all the time.

2017-05-02 16:03 UTC, nicolas-grekas commented
But we don't code for the ideal case only :)

2017-05-02 17:39 UTC, robfrawley commented
Can we not display `P (e)` when they are different and only `e` when the are the same value, thereby providing a more robust result if the `DateTime` object is a "type 3" and not showing duplicate values when it is a "type 1" or "type 2" (re [SO@17694894](http://stackoverflow.com/questions/17694894/different-timezone-types-on-datetime-object)).

```php
<?php

function timezoneToString(\DateTime $dateTime)
{
    $p = $dateTime->format('P');
    $e = $dateTime->format('e');

    return $e === $p ? $e : sprintf('%s (%s)', $p, $e);
}

$date = new \DateTime('now', new DateTimezone('GMT+2'));
echo sprintf("@%d: timezone %s\n", $date->format('U'), timezoneToString($date));

$date = new \DateTime('now', new \DateTimezone('America/New_York'));
echo sprintf("@%d: timezone %s\n", $date->format('U'), timezoneToString($date));
```

Results (the important part being after the `timezone` string, obviously):

```
@1493746514: timezone +02:00
@1493746514: timezone -04:00 (America/New_York)
```

2017-05-02 17:41 UTC, ogizanagi commented
What about https://3v4l.org/uqc19 ?

2017-05-02 17:42 UTC, robfrawley commented
@ogizanagi That looks great to me!

2017-05-02 17:54 UTC, ro0NL commented
Agree. but i still prefer `P (e)` format though... https://3v4l.org/sWptM

2017-05-02 18:08 UTC, nicolas-grekas commented
I like Maxime's output

2017-05-02 18:09 UTC, nicolas-grekas commented
Alternatively, provide P on hover? (Only when different than e?)

2017-05-02 18:23 UTC, ro0NL commented
for me the offset adds more value then a location name... hiding it on CLI sounds ike a bad idea :/ in that case i prefer @ogizanagi version as well. It's just a tiny detail after all.. :)

2017-05-03 16:30 UTC, maidmaid commented
Updated:

![screenshot from 2017-05-03 18-27-01](https://cloud.githubusercontent.com/assets/4578773/25670826/3cf96c16-302e-11e7-86d6-7dee9ac6b3b1.png)

2017-05-03 16:35 UTC, maidmaid commented
Convinced? I do :)

2017-05-04 14:46 UTC, maidmaid commented
Strange errors in tests... Could you help me?

2017-05-04 14:53 UTC, ro0NL commented
I think you're applying a timezone convesion (from system value to Europe/Zurich). Meaning the timestamp is going to differ...?

Just a guess :))

2017-05-04 14:57 UTC, ro0NL commented
```diff
-DateTime @1493503200 {
-  date: 2017-04-30 00:00:00.000000 +02:00
+DateTime @1493535600 {
+  date: 2017-04-30 09:00:00.000000 +02:00
```

i.e. a 9 hours difference..., on appvoyer the default TZ is America/Los_Angeles (utc-8), Europe/Zurich is utc+1..

there's our 9 hours difference :)

2017-05-04 15:12 UTC, ogizanagi commented
Indeed @ro0NL is right. Just use the second `\DateTime::construct()` argument to init the timezone (beware it will be ignore in case the time offset is already part of the provided string, like when providing a timestamp (http://php.net/manual/en/datetime.construct.php#refsect1-datetime.construct-parameters)).

I like the new output 😃 , but I may advocate `e (P)` is probably better, because it allows to copy/paste the string (stopped just right before the first parenthesis) to re-create a `\DateTime` instance from it, without loosing information.
I.e:

```php
>>> new \DateTime('2017-04-30 00:00:00.000000 Europe/Zurich'); # <-- 👍
=> DateTime {#167
     +"date": "2017-04-30 00:00:00.000000",
     +"timezone_type": 3,
     +"timezone": "Europe/Zurich",
   }

>>> new \DateTime('2017-04-30 00:00:00.000000 +02:00'); # <-- loosing the geo info
=> DateTime {#171
     +"date": "2017-04-30 00:00:00.000000",
     +"timezone_type": 1,
     +"timezone": "+02:00",
   }

>>> new \DateTime('2017-04-30 00:00:00.000000 Europe/Zurich (+02:00)'); # <-- doesn't even work
Exception with message 'DateTime::__construct(): Failed to parse time string (2017-04-30 00:00:00.000000 Europe/Zurich (+02:00)) at position 41 ((): Unexpected character'
```

I guess it can be useful sometimes.

2017-05-04 15:16 UTC, nicolas-grekas commented
Same opinion on e (P) :)

2017-05-04 15:33 UTC, ro0NL commented
Given we have a full date string now... :+1: for e (P). I liked the offset in front if prefixed by a `timezone:` key; the first proposal that is.

2017-05-04 15:49 UTC, maidmaid commented
Green tests and `` e (P)`` used now :)

2017-05-04 16:06 UTC, ro0NL commented on src/Symfony/Component/VarDumper/Caster/DateCaster.php
> +                (new \DateTime())->diff($d)->format('%R %yy %mm %dd %H:%I:%S')
https://github.com/symfony/symfony/pull/22431#discussion_r111608243 :)

2017-05-04 16:34 UTC, ro0NL commented
May i do one last suggestion; in the tooltip inform about DST yes/no

https://3v4l.org/BaOcs

2017-05-05 08:57 UTC, maidmaid commented on src/Symfony/Component/VarDumper/Caster/DateCaster.php
> +                (new \DateTime())->diff($d)->format('%R %yy %mm %dd %H:%I:%S')
I'am rather favor of https://github.com/symfony/symfony/pull/22431#discussion_r114303969

Explanation: if it's 12:00 in Mali (+00:00) and 14:00 in Zurich (+02:00), it's the same moment in the **T**ime, there is no interval of time between. But if we set Zurich's tz, we will have 2h of interval:

```php
>>> (new \DateTime('12:00+00:00'))->diff(new \DateTime('14:00+02:00'))->format('%R %yy %mm %dd %H:%I:%S')
=> "+ 0y 0m 0d 00:00:00" // Ok

>>> (new \DateTime('12:00+02:00'))->diff(new \DateTime('14:00+02:00'))->format('%R %yy %mm %dd %H:%I:%S')
=> "+ 0y 0m 0d 02:00:00" // Ko
```

2017-05-05 09:13 UTC, maidmaid commented
Added DST info:
![screenshot from 2017-05-05 11-11-24](https://cloud.githubusercontent.com/assets/4578773/25739789/ba823522-3183-11e7-95b6-e4bd1759b5b9.png)

2017-05-05 11:13 UTC, nicolas-grekas commented
Just a few suggestions here: https://gist.github.com/nicolas-grekas/d645a474490b9b00a4f9a55b420ff8d2

- display DST only for geographical times
- tweak the title: remove "literal" and replace Δnow prefix by "from now" suffix
- remove leading zeros from "from now"
- add a test case for the title
- (fixes a bug in StubCaster found while doing so - separate PR coming)

2017-05-05 11:24 UTC, ro0NL commented on src/Symfony/Component/VarDumper/Caster/DateCaster.php
> +                (new \DateTime())->diff($d)->format('%R %yy %mm %dd %H:%I:%S')
You're right!

2017-05-05 15:51 UTC, maidmaid commented
Patched (thank you @nicolas-grekas):
![screenshot from 2017-05-05 17-48-24](https://cloud.githubusercontent.com/assets/4578773/25753313/4b25c1ca-31bb-11e7-8804-cf282235e7d1.png)

2017-05-05 17:08 UTC, ro0NL approved these changes
Awesome!

2017-05-05 17:08 UTC, ro0NL commented on src/Symfony/Component/VarDumper/Caster/DateCaster.php
> +    public static function castDate(\DateTimeInterface $d, array $a, Stub $stub, $isNested, $filter)
`castDateTime` (same for tests)?

2017-05-05 17:18 UTC, ro0NL commented
Not sure about the literal format though.. shouldnt this show `Saturday, April 3, 2021`? ie. US standard.

2017-05-05 18:18 UTC, maidmaid commented on src/Symfony/Component/VarDumper/Caster/DateCaster.php
> +    public static function castDate(\DateTimeInterface $d, array $a, Stub $stub, $isNested, $filter)
In fact, it casts all DateTimeInterface implementations. It's why I choosed the generic castDate method name. castDateTime seems only cast DateTime.

2017-05-05 18:20 UTC, maidmaid commented
Rigth about literal format. I will change that.

2017-05-05 18:22 UTC, ro0NL commented on src/Symfony/Component/VarDumper/Caster/DateCaster.php
> +    public static function castDate(\DateTimeInterface $d, array $a, Stub $stub, $isNested, $filter)
i'd qualify all those variants a datetime value :) but that's my pov; fine either way :)

2017-05-05 19:16 UTC, robfrawley commented
The US standard is the worst... and this is coming from a US citizen. Shouldn't we use what programmers prefer, which is what was already used, ie: `[day] [month] [year]`?

2017-05-07 09:19 UTC, ro0NL commented
Not sure what programmers prefer.. :) tbh in programming im quite used to US standards.

Note im fine either way.. i just mentioned it because i believe SF (and PHP) follow this locale in the codebase.

2017-05-08 15:30 UTC, maidmaid commented
More, the plus-value of literal format is to show day of week and named month. With U.S. standard, these 2 items are in the front.

2017-05-08 18:30 UTC, FabienPapet commented
Shouldn't the 'from now' be 'from server time' , using 'now' can be confusing if the server time is not the developer time

WDYT ?

2017-05-08 19:09 UTC, maidmaid commented
@FabienPapet I think that dump a date is in most cases a debug step that is realized on our local machine whose time we known.

2017-05-08 23:10 UTC, maidmaid commented
@nicolas-grekas I think this version is quite conclusive. What about merge this and open new PR if we have tweaks?

2017-05-09 08:25 UTC, nicolas-grekas approved these changes
:+1: (To be merged when the feature freeze is over)

2017-06-26 21:03 UTC, ogizanagi commented
This should be ready to be merged now :)

2017-06-27 05:19 UTC, Nek- commented on src/Symfony/Component/VarDumper/Caster/DateCaster.php
> +class DateCaster
why waiting?

2017-06-28 07:10 UTC, fabpot commented on src/Symfony/Component/VarDumper/Caster/DateCaster.php
> +class DateCaster
I agree, it would be better to have everything in the same PR.

2017-06-28 07:12 UTC, fabpot commented
If we want to support DateInterval, I think it should be done in this PR.

2017-06-28 12:24 UTC, maidmaid commented
Ok, I added DateInterval caster.

| Before        | After           |
| ------------- | ------------- |
| ![screenshot from 2017-06-28 14-17-40](https://user-images.githubusercontent.com/4578773/27636630-b14def4c-5c0c-11e7-895f-aff37abb13d8.png) | ![screenshot from 2017-06-28 14-17-54](https://user-images.githubusercontent.com/4578773/27636629-b14a4e8c-5c0c-11e7-86ca-61d27367f24d.png) |

2017-07-03 07:16 UTC, nicolas-grekas commented
Hum, let's remove the DateInterval caster, at least from this PR. The issue I have is accuracy and teaching. Dump should be informational about how things actually works or can be used. On a DateInterval, the listed values are actual public properties. VarDumper is about showing actual facts about objects, not alternate ones ;)
The issue does not exist with DateTime objects because there is no properties there.

BTW, I agree with the comment on the name of the caster method: should be `castDateTime` also IMHO.

2017-07-03 08:10 UTC, maidmaid commented
Ok, I removed DateInterval caster and I renamed caster method to ``castDateTime``.

2017-07-03 08:35 UTC, nicolas-grekas commented
Thank you @maidmaid.

2017-07-03 08:36 UTC, merged