[Console] Review console.ERROR related behavior
symfony/symfony pull request #22441
Opened 2017-04-14 20:06 UTC by nicolas-grekas

| Q             | A
| ------------- | ---
| Branch?       | 3.3
| Bug fix?      | yes
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | yes
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

This PR is a follow up of #18140 that I wanted to do since a few weeks.
It enhances this work with fixes and behavior changes.
It embeds #22435 and resolves issues like the one described in #20808.

2017-04-15 10:56 UTC, chalasr commented on src/Symfony/Component/Console/EventListener/ExceptionListener.php
> + * @deprecated since version 3.3, to be removed in 4.0. Use ErrorListener instead.
This listener has been added in 3.3 (https://github.com/symfony/symfony/pull/21003), can be renamed directly :)

2017-04-15 12:00 UTC, nicolas-grekas commented on src/Symfony/Component/Console/EventListener/ExceptionListener.php
> + * @deprecated since version 3.3, to be removed in 4.0. Use ErrorListener instead.
fixed, thanks

2017-04-25 15:06 UTC, nicolas-grekas commented
:+1: also :)

2017-04-25 16:23 UTC, stof requested changes

2017-04-25 16:23 UTC, stof commented on src/Symfony/Component/Console/Event/ConsoleErrorEvent.php
> +        $r->setValue($this->error, $this->exitCode);
why altering the exception ?

2017-04-25 16:23 UTC, stof commented on src/Symfony/Component/Console/Event/ConsoleExceptionEvent.php
> +        $this->setException($exception);
useless change

2017-04-25 20:46 UTC, nicolas-grekas commented on src/Symfony/Component/Console/Event/ConsoleErrorEvent.php
> +        $r->setValue($this->error, $this->exitCode);
because the other part of the exception handling uses getCode as the way to set the exit status code from an exception

2017-04-26 01:33 UTC, fabpot commented
Thank you @nicolas-grekas.

2017-04-26 01:34 UTC, merged