[WebProfilerBundle] Fix exception rendering
symfony/symfony pull request #22448
Opened 2017-04-15 16:25 UTC by e-moe

| Q             | A
| ------------- | ---
| Branch?       | master 
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #22442
| License       | MIT
| Doc PR        | none

2017-04-16 15:25 UTC, aitboudad requested changes

2017-04-16 15:25 UTC, aitboudad commented on src/Symfony/Bundle/WebProfilerBundle/Controller/ExceptionController.php
> +        return '@Twig/Exception/'.($this->debug ? 'exception_full' : 'error').'.html.twig';
Not sure if this is the correct fix because it includes the hole HTML page!

2017-04-16 16:53 UTC, sustmi commented on src/Symfony/Bundle/WebProfilerBundle/Controller/ExceptionController.php
> +        return '@Twig/Exception/'.($this->debug ? 'exception_full' : 'error').'.html.twig';
Note that `error.html.twig` (that is used when `debug` is `false`) contains HTML page too.

2017-04-19 13:52 UTC, stof commented
This looks wrong to me. The `exception` panel is using inline rendering of a subcontroller, so it should not return something containing the `<html>` and `<body>` tags.
this actually means that the code is currently broken when using the WebProfilerBundle in non-debug mode (which probably nobody is doing, and so nobody noticed it) or when the TwigBundle template does not exist (which may happen when using Silex).

The right fix for the symfony full-stack case would be to fix the `cssAction` to return the right CSS instead (the new one)

2017-04-19 13:54 UTC, e-moe commented
thanks for your review. I will try to update this PR in order to apply your suggestions

2017-04-20 07:59 UTC, e-moe commented
updated. css taken from `src/Symfony/Bundle/TwigBundle/Resources/views/layout.html.twig` with small modifications (e.g. remove `.container` styling)

2017-04-20 20:01 UTC, javiereguiluz commented
@e-moe thanks for contributing this bug fix. However, the current solution has some problems (see #22491) so I've opened a new PR to fix this. That's why I'm closing this. Thanks!

2017-04-20 20:02 UTC, closed without merging