Fix Framework UPGRADE notice about trusted proxies
symfony/symfony pull request #22507
Opened 2017-04-24 09:06 UTC by sstok

| Q             | A
| ------------- | ---
| Branch?       | master 
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #22506
| License       | MIT
| Doc PR        | 

The `framework.trusted_proxies` configuration is not really removed (it gives an error) but that's only to help with the upgrade process. So I think mentioning it's removed is enough.

2017-04-24 09:43 UTC, chalasr commented
👍 
Status: reviewed

2017-04-24 10:03 UTC, stof requested changes

2017-04-24 10:03 UTC, stof commented on UPGRADE-3.3.md
> + * The "framework.trusted_proxies" configuration option and the corresponding "kernel.trusted_proxies"
this needs to be prefixed by `[BC BREAK]` actually

2017-04-25 12:07 UTC, sstok commented on UPGRADE-3.3.md
> + * The "framework.trusted_proxies" configuration option and the corresponding "kernel.trusted_proxies"
Done 👍

2017-04-25 13:36 UTC, nicolas-grekas commented
Thank you @sstok.

2017-04-25 13:36 UTC, closed without merging