[WIP] Add strict option for http url in asset
symfony/symfony pull request #22510
Opened 2017-04-24 13:27 UTC by RedBoool

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no / TODO: updating UPGRADE-*.md files
| Tests pass?   | yes
| Fixed tickets | #21249
| License       | MIT
| Doc PR        | # / Todo: symfony/symfony-docs

2017-04-24 13:37 UTC, GromNaN requested changes

2017-04-24 13:37 UTC, GromNaN commented on src/Symfony/Component/Asset/UrlPackage.php
> +    protected function splitBaseUrl(array $urls, $isStrictHttp)
Should be private.

2017-04-24 13:37 UTC, GromNaN commented on src/Symfony/Component/Asset/UrlPackage.php
> +        if (!empty($urlList['httpsUrl']) && $this->getContext()->isSecure()) {
The context is stateful, you must check `isSecure` in `getBaseUrl`

2017-04-24 14:24 UTC, RedBoool commented on src/Symfony/Component/Asset/UrlPackage.php
> +    protected function splitBaseUrl(array $urls, $isStrictHttp)
Done

2017-04-24 14:24 UTC, RedBoool commented on src/Symfony/Component/Asset/UrlPackage.php
> +        if (!empty($urlList['httpsUrl']) && $this->getContext()->isSecure()) {
Done

2017-04-25 07:57 UTC, GromNaN commented on src/Symfony/Component/Asset/Tests/UrlPackageTest.php
> +            array(true, array('http://example.com', 'http://example.net', 'https://example.com', 'https://example.net'), '', 'fooa', 'https://example.net/fooa?v1'),
You should add a test case with a protocol-relative URL.

2017-04-25 08:00 UTC, GromNaN commented on src/Symfony/Component/Asset/UrlPackage.php
> +        $urlList = array('httpUrl' => array(), 'httpsUrl' => array(), 'fullUrl' => array());
Instead of this array of arrays, having 2 private properties `baseSecureUrls` and `baseUnsecureUrls`.

2017-04-25 13:13 UTC, RedBoool commented on src/Symfony/Component/Asset/Tests/UrlPackageTest.php
> +            array(true, array('http://example.com', 'http://example.net', 'https://example.com', 'https://example.net'), '', 'fooa', 'https://example.net/fooa?v1'),
Done

2017-04-25 13:13 UTC, RedBoool commented on src/Symfony/Component/Asset/UrlPackage.php
> +        $urlList = array('httpUrl' => array(), 'httpsUrl' => array(), 'fullUrl' => array());
Done

2017-06-19 09:19 UTC, GromNaN approved these changes

2017-08-07 06:52 UTC, javiereguiluz commented
@RedBoool thanks for contributing this feature!

I'd like to ask you a question:

Is really a technical issue to use HTTPS on HTTP pages? Will browsers display any warning message or will it affect your application or your end users in any other way? *I know it's an issue the other way (using HTTP on HTTPS pages).*

* If it's not a problem, I'd say let's not add this config option and keep the existing behavior.
* If it's a problem, I'd recommend to not add this config option, but change the existing behavior as if we were setting `$isStrictProtocol` to `true`.

What do others think?

2017-08-07 09:19 UTC, RedBoool commented
This is not a technical issue, it's a financial issue.
Some CDN charge you more for https than for http.

The aim of this PR is to help us pay the right price, no more, no less

2017-09-26 14:17 UTC, nicolas-grekas commented
> not add this config option, but change the existing behavior as if we were setting $isStrictProtocol to true

@RedBoool would that fit your request? ping @symfony/deciders would that be OK to you?

2017-09-26 14:42 UTC, RedBoool commented
That perfectly match my needs.
My first thought was to do it this way, but didn't want to introduce a breaking change.

2017-09-27 15:28 UTC, weaverryan commented
> not add this config option, but change the existing behavior as if we were setting $isStrictProtocol to true
> RedBoool would that fit your request? ping symfony/deciders would that be OK to you?

It makes me a bit nervous... if your protocol is `http`, and you have a mixture of `http` and `https` base URLs... right now, they will "round robin". After this PR, it will only round robin in the `http` base URLs. That doesn't seem horrible, but it will be really hard to notice.

2017-10-08 16:07 UTC, nicolas-grekas commented
Moving to 4.1 as it looks like the discussion is not over.

2018-07-04 07:10 UTC, javiereguiluz commented
Maybe it's time to rethink this feature proposal. HTTPS is no longer optional for the web. Google and others are pushing hard to make it mandatory. According to Google's data (https://transparencyreport.google.com/https/overview) more than 70% of web traffic is now encrypted. So I guess CDNs charging more for HTTPS traffic will be soon out of the market.

2018-07-04 09:31 UTC, dunglas commented
👎 on my side. Mixed content should be avoided, and using HTTPS everywhere is a best practice we must encourage.

2018-07-04 15:33 UTC, closed without merging