[DI] Throw useful exception on bad XML argument tags
symfony/symfony pull request #22527
Opened 2017-04-26 01:37 UTC by nicolas-grekas

| Q             | A
| ------------- | ---
| Branch?       | 3.3
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #22525
| License       | MIT
| Doc PR        | -

I still think that the feature request in #22525 would make things better.
But at least, let's make thing fail loudly, instead of silently today, with the associated usual wtfs :)

2017-04-26 02:00 UTC, nicolas-grekas commented
Needs #22529 to be green.

2017-04-26 07:16 UTC, GuilhemN commented on src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php
> +                    if (!$arg->getAttribute('id')) {
`hasAttribute`?

2017-04-26 11:02 UTC, nicolas-grekas commented on src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php
> +                    if (!$arg->getAttribute('id')) {
An empty attribute is also invalid, so better as is IMHO

2017-04-26 11:06 UTC, stof requested changes

2017-04-26 11:06 UTC, stof commented on src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php
> +                        throw new InvalidArgumentException(sprintf('Tag "<%s>" with type="service" is missing an "id" attribute in "%s".', $name, $file));
wrong type

2017-04-26 11:06 UTC, stof commented on src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php
> +                        throw new InvalidArgumentException(sprintf('Tag "<%s>" with type="service" is missing a "method" attribute in "%s".', $name, $file));
wrong type

2017-04-26 11:52 UTC, nicolas-grekas commented on src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php
> +                        throw new InvalidArgumentException(sprintf('Tag "<%s>" with type="service" is missing an "id" attribute in "%s".', $name, $file));
fixed thanks

2017-04-26 14:25 UTC, nicolas-grekas commented
rebased

2017-04-26 16:49 UTC, GuilhemN approved these changes

2017-04-26 16:49 UTC, GuilhemN commented on src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php
> +                    if (!$arg->getAttribute('id')) {
Ok :+1:

2017-04-29 16:02 UTC, fabpot commented on src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php
> +                        throw new InvalidArgumentException(sprintf('Tag "<%s>" with type="service" is missing an "id" attribute in "%s".', $name, $file));
is missing or is empty?

2017-04-29 16:31 UTC, nicolas-grekas commented on src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php
> +                        throw new InvalidArgumentException(sprintf('Tag "<%s>" with type="service" is missing an "id" attribute in "%s".', $name, $file));
fixed

2017-04-29 16:34 UTC, fabpot commented
Thank you @nicolas-grekas.

2017-04-29 16:34 UTC, merged