[Asset] Starting slash should indicate no basePath wanted
symfony/symfony pull request #22528
Opened 2017-04-26 01:52 UTC by weaverryan

| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | yes-ish... and no-ish
| New feature?  | no
| BC breaks?    | yes
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | n/a

**Important** View the second commit for an accurate diff. The first commit just renames some strings in a test for clarity.

When we moved `PathPackage` from `Templating` to `Asset`, we actually changed its behavior. Assume that we're deployed under a `/subdir` subdirectory:

**Before** `{{ asset('/main.css') }}` would *not* have the base path prefixed -> `/main.css`

**After** `{{ asset('/main.css') }}` *does* have the base path prefixed -> `/subdir/main.css`

https://github.com/symfony/symfony/blob/3adff11d729ccdfc4eb4b189417ec04491c6eaad/src/Symfony/Component/Templating/Asset/PathPackage.php#L61-L63

This PR simply reverses that, to the *previous* behavior. This *is* a BC break... and also arguably a bug fix :). Interestingly, when we changed the behavior the first time (i.e. broke BC), I don't think that anyone noticed. It should only affect users deployed under a subdirectory.

Why do I care? I'm using the new `JsonManifestVersionStrategy` with a library that is outputting paths that *already* include my subdirectory:

```json
{
    "build/main.css": "/subdir/build/main.abc123.css"
}
```

So, I do not want Symfony to detect the `/subdir` and apply it a second time.

2017-04-26 06:00 UTC, stof commented
thus, it only affects users deploying in a subdirectory *and* using leading slashes. And the recommendation was to avoid leading slashes precisely to allow deploying in subdirectories easily.

2017-04-26 06:22 UTC, javiereguiluz approved these changes
:+1:

To me the real BC break was the first one which changed the original behavior. Besides, as you said, we didn't receive issue reports about this break, so it could be safe to reverse it now.

2017-04-26 14:06 UTC, nicolas-grekas commented
rebase needed

2017-04-26 20:54 UTC, fabpot commented
@weaverryan Can you rebase?

2017-04-26 21:12 UTC, weaverryan commented
Rebased!

2017-04-27 06:47 UTC, stloyd requested changes

2017-04-27 06:47 UTC, stloyd commented on src/Symfony/Component/Asset/PathPackage.php
> +        if ($this->isAbsoluteUrl($versionedPath) || '/' === substr($versionedPath, 0, 1)) {
`0 === strpos($versionedPath, '/')`

2017-04-27 11:32 UTC, fabpot commented on src/Symfony/Component/Asset/PathPackage.php
> +        if ($this->isAbsoluteUrl($versionedPath) || '/' === substr($versionedPath, 0, 1)) {
👍

2017-04-27 15:26 UTC, stof commented on src/Symfony/Component/Asset/PathPackage.php
> +        if ($this->isAbsoluteUrl($versionedPath) || 0 === strpos($versionedPath, '/')) {
using `'/' === $versionedPath[0]` is even faster (and already used above). We just need to handle the case of the empty string.
strpos still requires looking at the whole string for the common case of needing the base path

2017-04-27 22:28 UTC, weaverryan commented
@stof I should have your implementation in there now :)

2017-04-28 23:08 UTC, fabpot commented
Thank you @weaverryan.

2017-04-28 23:09 UTC, closed without merging

2017-05-05 16:25 UTC, ambroisemaupate commented
BC break in a hotfix version release… hum hum

>  It should only affect users deployed under a subdirectory.

…And unit tests that mimic a subdirectory setup. 😞 

https://github.com/roadiz/roadiz/issues/257

2017-05-05 16:49 UTC, stof commented
@ambroisemaupate which is reverting a BC break in a non-major version too