[Validator] Allow to use a property path to get value to compare in comparison constraints
symfony/symfony pull request #22576
Opened 2017-04-28 14:57 UTC by ogizanagi

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | N/A
| License       | MIT
| Doc PR        | todo

So we can simply declare something like:

```php
class Activity 
{
    /**
     * @var \DateTime
     *
     * @Assert\DateTime()
     */
    private $startDate;

    /**
     * @var \DateTime
     *
     * @Assert\DateTime()
     * @Assert\GreaterThan(valuePath="startDate")
     */
    private $endDate;

    // [...]

    public function getStartDate(): \DateTime
    {
        return $this->startDate;
    }

    public function getEndDate(): \DateTime
    {
        return $this->startDate;
    }
}
```

Of course, this is actually already possible by using an `Expression` constraint (or a callable), but it feels more natural to me to use proper comparison constraints for this.

2017-04-28 15:02 UTC, ro0NL commented
`propertyPath`?

2017-04-28 15:08 UTC, ogizanagi commented
@ro0NL: I hesitated. It should be obvious it's the property path to the value to use in comparison, and not anything else. I can't really explain why I had some reservations on this naming. Let's see what people do prefer.

2017-06-25 16:35 UTC, ogizanagi commented
Updated back to use `propertyPath`, as it's the common naming we've got in the core for this (original proposition was `valuePath`). Unless there is a debate about another naming, this should be ready.

2017-06-29 07:59 UTC, xabbuh commented
Can you add a new entry to the changelog please?

2017-06-29 08:01 UTC, xabbuh commented on src/Symfony/Component/Validator/Constraints/AbstractComparison.php
> +        if (is_array($options) && !isset($options['value']) && !isset($options['propertyPath'])) {
We should also error if both the `value` and the `propertyPath` option are given.

2017-06-29 08:02 UTC, xabbuh commented on src/Symfony/Component/Validator/Constraints/AbstractComparisonValidator.php
> +            $object = $this->context->getObject();
we need to account for the case where `$object` is `null`

2017-06-29 08:04 UTC, xabbuh commented on src/Symfony/Component/Validator/Constraints/AbstractComparisonValidator.php
> +            if (!class_exists(PropertyAccess::class)) {
What about failing earlier instead when the constraint definition is evaluated (i.e. in the constructor of `AbstractComparison`)?

2017-06-29 08:16 UTC, xabbuh commented on src/Symfony/Component/Validator/Constraints/AbstractComparisonValidator.php
> +    public function __construct(PropertyAccess $propertyAccessor = null)
`PropertyAccessor`

2017-06-29 12:39 UTC, ogizanagi commented on src/Symfony/Component/Validator/Constraints/AbstractComparisonValidator.php
> +            $object = $this->context->getObject();
Hmm. Indeed. What should we do in such case? I guess we can only `return;` as there is no way to get the value to compare to from `null` and should not create a violation (it's the `NotNull` constraint role). Right?

2017-06-29 12:39 UTC, ogizanagi commented on src/Symfony/Component/Validator/Constraints/AbstractComparisonValidator.php
> +            if (!class_exists(PropertyAccess::class)) {
Done.

2017-06-29 12:39 UTC, ogizanagi commented on src/Symfony/Component/Validator/Constraints/AbstractComparisonValidator.php
> +    public function __construct(PropertyAccess $propertyAccessor = null)
Oops. Good catch.

2017-06-29 12:39 UTC, ogizanagi commented on src/Symfony/Component/Validator/Constraints/AbstractComparison.php
> +        if (is_array($options) && !isset($options['value']) && !isset($options['propertyPath'])) {
Done.

2017-07-03 18:01 UTC, ogizanagi commented
Rebased and green.

2017-07-04 09:42 UTC, xabbuh approved these changes

2017-07-04 10:42 UTC, fabpot requested changes

2017-07-04 10:42 UTC, fabpot commented on src/Symfony/Component/Validator/Constraints/AbstractComparison.php
> +                throw new ConstraintDefinitionException(sprintf('The %s constraint requires the Symfony PropertyAccess component to use the "propertyPath" option.', get_class($this)));
Missing `"` around the class name (same above)

2017-07-04 10:42 UTC, fabpot commented on src/Symfony/Component/Validator/Tests/Constraints/EqualToValidatorTest.php
> +        yield array(5);
Why not use `return array(5);`. That would be more similar to what we already have and would avoid questions about why the new ones are different.

2017-07-04 10:59 UTC, ogizanagi commented on src/Symfony/Component/Validator/Constraints/AbstractComparison.php
> +                throw new ConstraintDefinitionException(sprintf('The %s constraint requires the Symfony PropertyAccess component to use the "propertyPath" option.', get_class($this)));
No double quotes were used in the existing one. (Fixed though)

2017-07-04 10:59 UTC, ogizanagi commented on src/Symfony/Component/Validator/Tests/Constraints/EqualToValidatorTest.php
> +        yield array(5);
Done.

2017-07-04 11:39 UTC, fabpot approved these changes

2017-07-12 12:11 UTC, merged