Di fix vars
symfony/symfony pull request #22581
Opened 2017-04-29 17:22 UTC by nicolas-grekas

| Q             | A
| ------------- | ---
| Branch?       | 3.3
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | ~
| License       | MIT
| Doc PR        | ~

Folow up of #22511, from @iltar:

> Currently, when having a service definition which has more than 1 usage of that service, it will put the argument in `$a` for example. By doing so, it will also use `$a` in the callable of the `ServiceLocator`, which result in an undefined variable `$a`.

> I managed to trigger this with the translator service, where I have my own loader, that I add for NL and EN, causing 2 method calls to turn the direct getter into a variable. I've added 2 test cases, 1 with only 1 method call and 1 with 2 method calls.

2017-04-29 17:25 UTC, nicolas-grekas commented
Diff best reviewed ignoring whitespaces: https://github.com/symfony/symfony/pull/22581/files?w=1
Patch made to minimize any future merge conflicts with 3.2.

2017-04-29 17:46 UTC, stof requested changes

2017-04-29 17:46 UTC, stof commented on src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php
> +        } elseif ($scope = $value instanceof ArgumentInterface) {
should just be `if` as the previous if returns

2017-04-29 17:46 UTC, stof commented on src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php
> +            $scope = array($this->definitionVariables, $this->referenceVariables, $this->variableCount);
Reusing the same variable to store a boolean or an array is harder to follow. Can't we put the `try/finally` inside this if instead, which will allow to only store an array in `$scope` ?

2017-04-29 18:19 UTC, nicolas-grekas commented on src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php
> +            $scope = array($this->definitionVariables, $this->referenceVariables, $this->variableCount);
fixed, PR should be OK

2017-04-30 08:39 UTC, stof approved these changes

2017-04-30 10:56 UTC, nicolas-grekas commented
Thank you @iltar.

2017-04-30 10:57 UTC, merged