Add some missing docs for the web server bundle
symfony/symfony pull request #22607
Opened 2017-05-02 01:25 UTC by fabpot

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | n/a

This is an alternative to #22471

2017-05-02 06:36 UTC, ro0NL approved these changes

2017-05-02 06:36 UTC, ro0NL commented on src/Symfony/Bundle/WebServerBundle/Command/ServerStartCommand.php
> +Execute <comment>server:stop</> tp stop it.
`to stop it`

2017-05-02 06:36 UTC, ro0NL commented on src/Symfony/Bundle/WebServerBundle/Command/ServerStatusCommand.php
> +server, such as the address and port where is listening to:
`it's listening to`

2017-05-02 09:22 UTC, nicolas-grekas approved these changes
:+1:

2017-05-03 08:20 UTC, stof approved these changes

2017-05-03 08:21 UTC, stof requested changes

2017-05-03 08:21 UTC, stof commented on src/Symfony/Bundle/WebServerBundle/Command/ServerLogCommand.php
> +Supported values are <comment>port</>, <comment>host</>, and <comment>address</>.
that's wrong actually. `filter` is about filtering logs with the ExpressionLanguage

2017-05-03 19:29 UTC, fabpot commented on src/Symfony/Bundle/WebServerBundle/Command/ServerLogCommand.php
> +Supported values are <comment>port</>, <comment>host</>, and <comment>address</>.
bad copy/paste, fixed

2017-05-03 19:30 UTC, fabpot commented on src/Symfony/Bundle/WebServerBundle/Command/ServerStartCommand.php
> +Execute <comment>server:stop</> tp stop it.
fixed

2017-05-03 19:30 UTC, fabpot commented on src/Symfony/Bundle/WebServerBundle/Command/ServerStatusCommand.php
> +server, such as the address and port where is listening to:
fixed

2017-05-03 19:33 UTC, merged

2017-05-03 21:50 UTC, yceruto commented on src/Symfony/Bundle/WebServerBundle/Command/ServerLogCommand.php
>          ;
missing `)` fixed in https://github.com/symfony/symfony/pull/22626