[SecurityBundle] Fixed a memory leak in SecurityBundle\Security\FirewallMap
symfony/symfony pull request #22605
Opened 2017-05-01 23:00 UTC by udavka

| Q             | A
| ------------- | ---
| Branch?       | 3.2
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

There is a memory leak in Symfony\Bundle\SecurityBundle\Security\FirewallMap, which leads to not autodestroy Symfony\Component\HttpFoundation\Request object after the request has been proceeded. This object is quite big and uses many internal subobjects, and as a result this leads to an essential memory leak, which can affect long-lived applications like php-pm.
How to reproduce: create a default sample Symfony application, add a destructor for the Request class, add unset($request); at the end of web/app.php and make sure that this destructor is not called after unset().
With this fix the destructor is called immediately after unset(), and that means no memory leak for the Request object.

2017-05-02 05:24 UTC, xabbuh requested changes

2017-05-02 05:24 UTC, xabbuh commented on src/Symfony/Component/Security/Http/Firewall.php
> +        $this->map->detachListeners($event->getRequest());
This may not always work (think of other implementations of the `FirewallMapInterface`).

2017-05-02 05:24 UTC, xabbuh commented on src/Symfony/Component/Security/Http/FirewallMapInterface.php
> +    public function detachListeners(Request $request);
Adding a new method to an interface is a BC break and not allowed by our BC promise.

2017-05-02 09:34 UTC, chalasr commented
But doesn't the issue concern only the SecurityBundle map due to its per-request cache? Wouldn't mapping contexts by Request object hash instead of Request instances be enough, changing the `\SplObjectStorage` to an array?

2017-05-02 11:23 UTC, udavka commented
@chalasr: The basic problem is the using of FirewallMapInterface to refer to long-lived services. There is no idea of destroying/detaching of FirewallMap from inside Firewall, because both of them are services and live forever.
Initially the FirewallMapInterface is intended only to get information and has nothing to initialize or to finalize itself. Even if we change the implementation of SecurityBundle\Security\FirewallMap to not have a Request reference, there will be a possibility to add a leak in the future.

2017-05-12 20:44 UTC, ogizanagi commented
@udavka : I don't get how it can improve anything when talking about the SecurityBundle `FirewallMap`. Unsetting the context for a given request won't free anything, as the services are still referenced by the container, right? The only leaking object is the request, indeed due to the `\SplObjectStorage` used for cache purpose. Using `spl_object_hash($request)` instead is the only thing required for solving the issue to me.

> Even if we change the implementation of SecurityBundle\Security\FirewallMap to not have a Request reference, there will be a possibility to add a leak in the future.

Which leak?

Regarding the component `FirewallMap`, I don't get why you'd like to remove the listeners once a request is finished. What about subsequent requests? Are you destroying the listeners and recreating them for each request? If so, why? Aren't they stateless?
Also you don't need new interface methods/new interface nor tweaking the `Firewall` for this I guess: just register the `FirewallMap` as a listener of `KernelEvents::FINISH_REQUEST` in order to call `detachListeners`.

2017-05-12 21:19 UTC, udavka commented
@ogizanagi Symfony is able to process many requests without restarting the whole framework. This idea is used in long-lived applications. Services are not leaks, because they are not recreated on every request. But Request is not a service and must be destroyed after the processing.
Asyou can see in the code, detaching of listeners is dependent on request, so no subsequent requests can be affected.
Using of `spl_object_hash($request)` is not an option, because the resulting hash can be reused later and anyway there will be a small leak in form of an array item [hash => listener].
I seems that the idea about `KernelEvents::FINISH_REQUEST` is the only one possible solution to make this object not leakable without BC breaks, but in this case the whole logic of the `FirewallMap` object will be inverted - it is initialized by another component, but it wants to clean up itself. This is actually the big hole for future problems.

2017-05-12 21:33 UTC, ogizanagi commented
> Using of spl_object_hash($request) is not an option, because the resulting hash can be reused later.

Indeed, as the previous request is destroyed as this point. Good point.

> small leak in form of an array item [hash => listener]

Sure, but not sure how much it can really affect long-living applications, as its one array item just holding references.

> I seems that the idea about KernelEvents::FINISH_REQUEST is the only one possible solution to make this object not leakable without BC breaks, but in this case the whole logic of the FirewallMap object will be inverted - it is initialized by another component, but it wants to clean up itself. This is actually the big hole for future problems.

Looks acceptable to me, and would allow to be merged as a bugfix in lower branches.
Otherwise, creating a new interface would allow doing it your way without BC break, but only as a new feature, so in 3.4.

2017-05-13 18:07 UTC, udavka commented on src/Symfony/Component/Security/Http/FirewallMapInterface.php
> +    public function detachListeners(Request $request);
Fixed by replacing the implementation.

2017-05-13 19:21 UTC, Taluu commented on src/Symfony/Bundle/SecurityBundle/Security/FirewallMap.php
> +    }
IMO you should directly unset the request in the `onKernelFinishRequest` method, that would make one less method call...

2017-05-13 19:58 UTC, ogizanagi approved these changes

2017-05-13 19:58 UTC, ogizanagi commented on src/Symfony/Bundle/SecurityBundle/Security/FirewallMap.php
> +     * @param FinishRequestEvent $event
To remove, as it does not bring anything more than the signature.

2017-05-13 19:58 UTC, ogizanagi commented on src/Symfony/Bundle/SecurityBundle/Security/FirewallMap.php
> +     * @return array Subscribed events
The whole docblock should be replaced by

```php
/**
 * {@inheritdoc}
 */
```

2017-05-13 21:07 UTC, udavka commented on src/Symfony/Bundle/SecurityBundle/Security/FirewallMap.php
> +     * @return array Subscribed events
fixed

2017-05-13 21:07 UTC, udavka commented on src/Symfony/Bundle/SecurityBundle/Security/FirewallMap.php
> +     * @param FinishRequestEvent $event
fixed

2017-05-13 21:07 UTC, udavka commented on src/Symfony/Bundle/SecurityBundle/Security/FirewallMap.php
> +    }
fixed

2017-05-13 21:43 UTC, GromNaN commented
Since the matching context relates to the request, this information should have been cached inside the request parameters. 

The can be done inside the [`getFirewallContext`](https://github.com/symfony/symfony/blob/3.2/src/Symfony/Bundle/SecurityBundle/Security/FirewallMap.php#L68-L76) method.
```php
    private function getFirewallContext(Request $request)
    {
        if ($this->contexts->contains($request)) {
            return $this->contexts[$request];
        }
        foreach ($this->map as $contextId => $requestMatcher) {
            if (null === $requestMatcher || $requestMatcher->matches($request)) {
                return $this->contexts[$request] = $this->container->get($contextId);
            }
        }
    }
```
We can remove the `$contexts` object map and store information inside the request attributes.
```php
    private function getFirewallContext(Request $request)
    {
        if ($request->attributes->has('_security_firewall_context')) {
            return $this->container->get($request->attributes->get('_security_firewall_context'));
        }
        foreach ($this->map as $contextId => $requestMatcher) {
            if (null === $requestMatcher || $requestMatcher->matches($request)) {
                $request->attributes->set('_security_firewall_context', $contextId);
                return $this->container->get($contextId);
            }
        }
    }
```

2017-05-14 08:33 UTC, ogizanagi commented
Indeed, @GromNaN suggestion looks even better to me :)

2017-05-29 08:39 UTC, nicolas-grekas commented
Status: needs work

2017-06-09 00:18 UTC, fabpot commented
Closing in favor of #22943

2017-06-09 00:18 UTC, closed without merging