[FrameworkBundle][Translation] Move translation compiler pass
symfony/symfony pull request #22619
Opened 2017-05-03 11:42 UTC by lepiaf

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | yes
| Tests pass?   | yes
| Fixed tickets | #21284
| License       | MIT
| Doc PR        | n/a

move TranslationDumperPass, TranslationExtractorPass, TranslatorPass to Translation component.

2017-05-03 11:55 UTC, stof requested changes
conflict rules are missing to ensure it does not get installed with an older version of symfony/translation (which would not allow registering it)

2017-05-03 11:55 UTC, stof commented on UPGRADE-3.3.md
> +   class has been deprecated and will be removed in 4.0. Use the
this will have to go in a new UPGRADE-3.4.md file actually. It is too late to include this in 3.3 as we already released the beta

2017-05-03 11:55 UTC, stof commented on src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/TranslationDumperPass.php
> +@trigger_error(sprintf('The %s class is deprecated since version 3.3 and will be removed in 4.0. Use Symfony\Component\Translation\DependencyInjection\TranslationDumperPass instead.', TranslationDump
3.4

2017-05-03 11:59 UTC, chalasr requested changes
The Translator component needs `symfony/dependency-injection:~3.3` as dev requirement and a conflict for `symfony/dependency-injection:<3.3`. Also adding a test case for passes which miss one would be great.

2017-05-03 11:59 UTC, chalasr commented on src/Symfony/Component/Translation/DependencyInjection/TranslationExtractorPass.php
> +        if (!$container->hasDefinition('translation.extractor')) {
the "collector" service id should be configurable through a constructor argument, same for the collected tag e.g. `__construct($extractorServiceId = 'translation.extractor', $extractorTag = 'translation.extractor')`

2017-05-03 11:59 UTC, chalasr commented on src/Symfony/Component/Translation/DependencyInjection/TranslatorPass.php
> +        if (!$container->hasDefinition('translator.default')) {
same here (constructor)

2017-05-03 11:59 UTC, chalasr commented on src/Symfony/Component/Translation/Tests/DependencyInjection/TranslatorPassTest.php
> +namespace Symfony\Component\Translation\Tests\DependencyInjection;
The original test case should be kept in `FrameworkBundle` with `@group legacy` and copied to the component, not moved.

2017-05-03 11:59 UTC, chalasr commented on src/Symfony/Component/Translation/DependencyInjection/TranslationDumperPass.php
> +        if (!$container->hasDefinition('translation.writer')) {
same here (constructor)

2017-05-03 12:02 UTC, chalasr commented
The fixed ticket would not be fixed actually, HttpKernel passes are still missing.

2017-05-03 12:17 UTC, lepiaf commented
@chalasr I'm currently working in another pr to move HttpKernel passes

2017-05-03 12:33 UTC, chalasr requested changes

2017-05-03 12:33 UTC, chalasr commented on src/Symfony/Bundle/FrameworkBundle/CHANGELOG.md
> +     `Symfony\Component\Translation\DependencyInjection\TranslatorPass` instead
2 extra spaces

2017-05-03 12:33 UTC, chalasr commented on src/Symfony/Bundle/FrameworkBundle/CHANGELOG.md
> +    `Symfony\Component\Translation\DependencyInjection\TranslationExtractorPass` instead
1 extra space

2017-05-03 12:34 UTC, chalasr commented
@lepiaf thanks for working on this.

2017-05-05 11:37 UTC, lepiaf commented
I did all requested changes. I will add new test for moved class.

2017-05-07 09:02 UTC, chalasr requested changes
~3.4 can't be used as a constraint yet, that breaks tests. I would let it as is and wait for 3.3 to be stable/ 3.4 branch to be created

2017-05-07 09:02 UTC, chalasr commented on src/Symfony/Component/Translation/composer.json
> +        "symfony/dependency-injection": "~3.3",
you need to add a conflict rule in order to avoid having errors when using 3.3 features (these passes use ones)

2017-05-07 09:02 UTC, chalasr commented on src/Symfony/Component/Translation/DependencyInjection/TranslatorPass.php
> +    ) {
one-line signatures are preferred

2017-05-07 09:02 UTC, chalasr commented on src/Symfony/Component/Translation/DependencyInjection/TranslatorPass.php
> +     */
phpdoc should be removed (same for properties, applies on the 3 passes), it doesn't give anything that an IDE couldn't guess

2017-05-27 07:21 UTC, xabbuh commented
@lepiaf `3.3` and `3.4` branches are a thing now. Can you rebase here?

2017-05-27 10:08 UTC, lepiaf commented
tests are failing but I don't know why. Is `symfony/var-dumper` missing in composer for frameworkbundle ?

2017-05-27 10:14 UTC, chalasr approved these changes
Build failure on deps=high is normal AFAIK. 👍

2017-06-21 12:35 UTC, chalasr commented
ping deciders

2017-07-06 06:47 UTC, fabpot approved these changes

2017-07-06 06:49 UTC, fabpot commented
Thank you @lepiaf.

2017-07-06 06:50 UTC, merged