[Security] Trigger a deprecation when a voter is missing the VoterInterface
symfony/symfony pull request #22629
Opened 2017-05-04 08:48 UTC by iltar

| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | yes
| Tests pass?   | yes/no
| Fixed tickets | ~
| License       | MIT
| Doc PR        | ~

Right now it's possible to add voters to the access decision manager that do not have a `VoterInterface`.
 - No Interface, no `vote()` method, and it will give a PHP error.
 - No Interface, but `vote()` method, it will still work.
 - If I don't implement the interface _and_ have no `vote()` method, I will get weird exception that's not meaningful: `Attempted to call an undefined method named "vote" of class "App\Voter\MyVoter".`

This PR will deprecate the ability to use voters without the interface, it will also throw a proper exception when missing the interface _and_ the `vote()` method. Why when using and not when setting? Due to the fact that the voters can be set lazily via the `IteratorArgument`. The SecurityBundle will trigger a deprecation if the interface is not implemented and an exception if there's not even a `vote()` method present (to prevent exceptions at run-time).

This should have full backwards compatibility with 3.3, but give more meaningful errors. The only behavioral difference, might be that the container will throw an exception instead of maybe succeeding in voting when 1 voter would be broken at the end of the list (based on strategy). This case however, will be detected during development and deployment, rather than run-time.

2017-05-04 09:01 UTC, stof requested changes

2017-05-04 09:01 UTC, stof commented on src/Symfony/Bundle/SecurityBundle/DependencyInjection/Compiler/AddSecurityVotersPass.php
> +            $class = $container->getDefinition($voter->__toString())->getClass();
use a string cast instead.

2017-05-04 09:01 UTC, stof commented on src/Symfony/Bundle/SecurityBundle/DependencyInjection/Compiler/AddSecurityVotersPass.php
> +                throw new LogicException(sprintf('%s should implement the %s class when used as voter.', $class, VoterInterface::class));
it is an interface, not a class

2017-05-04 09:01 UTC, stof commented on src/Symfony/Bundle/SecurityBundle/DependencyInjection/Compiler/AddSecurityVotersPass.php
> +                $container->log($this, sprintf('Detected usage of security.voter for class "%s" without implementing the %s.', $class, VoterInterface::class));
this log should be removed, as the deprecation is logged too already

2017-05-04 09:17 UTC, iltar commented on src/Symfony/Bundle/SecurityBundle/DependencyInjection/Compiler/AddSecurityVotersPass.php
> +            $class = $container->getDefinition($voter->__toString())->getClass();
Are you sure? That's harder to trace back (I'm not sure why toString is used either way)

2017-05-04 10:14 UTC, vamsiikrishna commented
I have got some Voters which are tagged as voters but don't implement ```VoterInterface``` .
 Thanks for addressing this and adhering to  BC promise .

2017-05-04 11:53 UTC, xabbuh commented on UPGRADE-3.4.md
> + * Using voters in the `AccessDecisionManager` without `VoterInterface` is now
[...] that do not implement the `VoterInterface` [...]

2017-05-04 12:29 UTC, xabbuh commented on UPGRADE-3.4.md
> + * Using voters that do not implement the `VoterInterface`, are now deprecated
"is" and you can remove the comma

2017-05-04 18:12 UTC, ro0NL commented on src/Symfony/Component/Security/Core/Authorization/AccessDecisionManager.php
> +        throw new \BadMethodCallException(sprintf('%s should implement the %s interface when used as voter.', get_class($voter), VoterInterface::class));
I would still qualify it a `\LogicException` :) it's only possible by violating the contract. So technically this is a safeguard.. do we need it? Given the validation during compilation. :+1: for that.

2017-05-04 20:12 UTC, iltar commented on src/Symfony/Component/Security/Core/Authorization/AccessDecisionManager.php
> +        throw new \BadMethodCallException(sprintf('%s should implement the %s interface when used as voter.', get_class($voter), VoterInterface::class));
I would like to have it because it's a component that can be used without the DIC

2017-05-05 07:13 UTC, ro0NL commented on src/Symfony/Component/Security/Core/Authorization/AccessDecisionManager.php
> +        throw new \BadMethodCallException(sprintf('%s should implement the %s interface when used as voter.', get_class($voter), VoterInterface::class));
It's still a safeguard :) sure it adds some DX value, but nowhere near the value added by the pass (validation at compile time). Practically for the component this is just creating cosmetic errors, which we dont do elsewhere really.

2017-05-05 14:13 UTC, fabpot approved these changes

2017-05-05 14:13 UTC, fabpot commented on src/Symfony/Component/Security/Core/Authorization/AccessDecisionManager.php
> +     */
I would add a note to remove this method in 4.0 (to avoid forgetting about it).

2017-05-05 14:17 UTC, iltar commented on src/Symfony/Component/Security/Core/Authorization/AccessDecisionManager.php
> +     */
I could make the method itself deprecated with a full-fledged warning, even though it's private. Would make it easier to detect.

2017-05-07 00:07 UTC, ogizanagi approved these changes

2017-05-07 00:07 UTC, ogizanagi commented on src/Symfony/Bundle/SecurityBundle/Tests/DependencyInjection/Compiler/AddSecurityVotersPassTest.php
> +            $this->expectExceptionMessage($message);
What about using the annotations?

2017-06-14 21:10 UTC, fabpot approved these changes

2017-06-14 21:13 UTC, closed without merging

2017-06-15 06:56 UTC, iltar commented
@fabpot while you approved it, you also closed it but I don't see another commit in the list for 3.4 (as it usually does), I think something went wrong

2017-06-15 14:21 UTC, fabpot commented
@iltar Weird, not sure what happened. Merging now!

2017-06-15 14:23 UTC, fabpot commented
Thank you @iltar.