[PropertyInfo] Fixed static property references in ReflectionExtractor
symfony/symfony pull request #22696
Opened 2017-05-12 11:58 UTC by neemzy

| Q             | A
| ------------- | ---
| Branch?       | 2.8
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| License       | MIT

This PR allows inheriting from `ReflectionExtractor` just to customize its behavior regarding accessor/mutator prefixes. This is currently impossible to do because of references to `self::`.

2017-05-12 12:02 UTC, Gregoire-M commented
:+1:

2017-05-12 12:17 UTC, neemzy commented
I don't think the failing test on Travis is related to this changeset in any way.

2017-05-15 07:31 UTC, nicolas-grekas commented
I don't think it's a good idea to allow this kind of global configuration. All instances will be impacted by this overriding.
Instead, what about turning these into regular properties?
This should be done on master as a new feature btw.

2017-05-15 08:03 UTC, neemzy commented
Fair enough! I'll be working on this.

2017-05-15 10:52 UTC, neemzy commented
@nicolas-grekas Does this look good to you? I left the static properties untouched (apart from their name) because they are referenced in `PhpDocExtractor`.

2017-05-15 13:39 UTC, nicolas-grekas reviewed
ping @dunglas for "domain" review

2017-05-15 13:39 UTC, nicolas-grekas commented on src/Symfony/Component/PropertyInfo/Extractor/PhpDocExtractor.php
> +        if (!in_array($prefix, ReflectionExtractor::$defaultArrayMutatorPrefixes)) {
I guess this also should be turned into `$this->arrayMutatorPrefixes`

2017-05-15 13:39 UTC, nicolas-grekas commented on src/Symfony/Component/PropertyInfo/Extractor/PhpDocExtractor.php
> +        $prefixes = $type === self::ACCESSOR
using $this also here
please revert the code style change

2017-05-15 13:54 UTC, neemzy commented on src/Symfony/Component/PropertyInfo/Extractor/PhpDocExtractor.php
> +        if (!in_array($prefix, ReflectionExtractor::$defaultArrayMutatorPrefixes)) {
No can do, this is the other class, cf. my last reply

2017-05-15 14:00 UTC, nicolas-grekas commented on src/Symfony/Component/PropertyInfo/Extractor/PhpDocExtractor.php
> +        if (!in_array($prefix, ReflectionExtractor::$defaultArrayMutatorPrefixes)) {
I mean your edit yes: if ReflectionExtractor needs this, why shouldn't PhpDocExtractor?
But note that I'd suggest to wait for some feedback from @dunglas before spending more time on code here, just to not waste yours :)

2017-05-15 14:01 UTC, dunglas commented on src/Symfony/Component/PropertyInfo/Extractor/ReflectionExtractor.php
> +    public function getMutatorPrefixes()
Why not passing those values in the constructor to make this class immutable?

2017-05-15 14:03 UTC, neemzy commented on src/Symfony/Component/PropertyInfo/Extractor/PhpDocExtractor.php
> +        if (!in_array($prefix, ReflectionExtractor::$defaultArrayMutatorPrefixes)) {
Duly noted. Do you think default values for these instance properties should come from `ReflectionExtractor::$default*Prefix`?

2017-05-15 14:03 UTC, dunglas requested changes

2017-05-15 14:03 UTC, dunglas commented on src/Symfony/Component/PropertyInfo/Extractor/ReflectionExtractor.php
> +    public function setMutatorPrefixes(array $mutatorPrefixes)
Why not passing those values in the constructor to make this class immutable?

2017-05-15 15:36 UTC, neemzy commented
@nicolas-grekas @dunglas Thanks for the feedback!

2017-05-16 12:26 UTC, neemzy commented
@nicolas-grekas @dunglas Is that better?

2017-05-16 14:01 UTC, nicolas-grekas reviewed
a few test cases and might be good :)

2017-05-16 14:01 UTC, nicolas-grekas commented on src/Symfony/Component/PropertyInfo/Extractor/PhpDocExtractor.php
> +        $this->mutatorPrefixes = $mutatorPrefixes ?: ReflectionExtractor::$defaultMutatorPrefixes;
I think we should allow empty arrays, which means we should compare with null here

2017-05-16 14:01 UTC, nicolas-grekas commented on src/Symfony/Component/PropertyInfo/Extractor/ReflectionExtractor.php
> +    public function __construct(array $mutatorPrefixes = array(), array $accessorPrefixes = array(), array $arrayMutatorPrefixes = array())
same: null as default, then compare with null below

2017-05-16 14:01 UTC, nicolas-grekas commented on src/Symfony/Component/PropertyInfo/Extractor/ReflectionExtractor.php
> +    public function getMutatorPrefixes()
not sure we need any accessor, do we?

2017-05-16 14:39 UTC, neemzy commented
@nicolas-grekas There you go ;)

2017-05-16 14:39 UTC, neemzy commented on src/Symfony/Component/PropertyInfo/Extractor/PhpDocExtractor.php
> +        $this->mutatorPrefixes = $mutatorPrefixes ?: ReflectionExtractor::$defaultMutatorPrefixes;
Good point

2017-05-16 14:39 UTC, neemzy commented on src/Symfony/Component/PropertyInfo/Extractor/ReflectionExtractor.php
> +    public function getMutatorPrefixes()
No, actually we don't

2017-05-16 14:40 UTC, nicolas-grekas commented on src/Symfony/Component/PropertyInfo/Extractor/PhpDocExtractor.php
> +        $this->mutatorPrefixes = $mutatorPrefixes !== null ? $mutatorPrefixes : ReflectionExtractor::$defaultMutatorPrefixes;
yoda everywhere: null !== ...

2017-05-16 14:41 UTC, nicolas-grekas commented on src/Symfony/Component/PropertyInfo/Extractor/ReflectionExtractor.php
> +        if (!empty($pattern) && preg_match('/^('.$pattern.')(.+)$/i', $methodName, $matches)) {
'' !== ...

2017-05-16 15:11 UTC, neemzy commented
Once again, the CI results are beyond me.

2017-05-22 07:58 UTC, neemzy commented
@nicolas-grekas @dunglas Just fixed conflicts that occurred since the last merges on `master`. May I request a moment of your time to review this changeset for what I reckon will be the last time? :)

2017-05-22 08:29 UTC, nicolas-grekas commented
this should be rebased on 3.4 in fact (I already changed the base branch)

2017-05-22 09:20 UTC, neemzy commented
@nicolas-grekas Alright, done!

2017-05-27 07:24 UTC, xabbuh commented on src/Symfony/Component/PropertyInfo/Extractor/PhpDocExtractor.php
> +     * @param string[]                 $mutatorPrefixes
`string[]|null` in fact

2017-05-27 07:30 UTC, xabbuh commented on src/Symfony/Component/PropertyInfo/Extractor/PhpDocExtractor.php
> +     * @var string[]
docblocks are actually not needed when private properties are initialised in the constructor

2017-05-27 07:31 UTC, xabbuh commented
`PhpDocExtractor` tests should probably be updated too.

2017-05-29 07:50 UTC, neemzy commented on src/Symfony/Component/PropertyInfo/Extractor/PhpDocExtractor.php
> +     * @var string[]
They were present for existing properties, so I added them for consistency's sake.

2017-05-29 08:19 UTC, neemzy commented
@xabbuh Thanks for the feedback, I took it into account.
@nicolas-grekas @dunglas Anything left to do in your opinion?

2017-05-29 08:27 UTC, nicolas-grekas approved these changes
:+1:

2017-05-29 08:33 UTC, xabbuh approved these changes

2017-05-31 07:30 UTC, neemzy commented
@dunglas Is that OK for you? :)

2017-06-07 10:02 UTC, dunglas approved these changes

2017-06-07 12:14 UTC, fabpot commented
Thank you @neemzy.

2017-06-07 12:15 UTC, merged