Fix compatibility issue
symfony/symfony pull request #22725
Opened 2017-05-16 22:41 UTC by trsteel88

Fix compatibility issue with egulias/email-validator ~2.0

This is an alternative to https://github.com/symfony/symfony/pull/22724

| Q             | A
| ------------- | ---
| Branch?       | 2.8
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| License       | MIT

2017-05-16 22:50 UTC, stof requested changes

2017-05-16 22:50 UTC, stof commented on composer.json
> +        "egulias/email-validator": "~1.2,>=1.2.1,<2.0",
`~1.2` already includes a restriction to <2.0. But as this is the dev requirement, it does not apply for projects using Symfony.
What you need to do is adding a conflict rule (to make it conflict with `>=2.0`), both in symfony/symfony and symfony/validator.

2017-05-16 23:27 UTC, trsteel88 commented on composer.json
> +        "egulias/email-validator": "~1.2,>=1.2.1,<2.0",
Updated. Thanks for the help.

2017-05-17 06:21 UTC, xabbuh commented
I am not sure if this change is a good idea. The email validator library is widely used and it is completely fine to install it without using it with the Symfony Email validation constraint. Adding the conflict rule would forbid that.

2017-05-17 06:46 UTC, trsteel88 commented
@xabbuh when I try to use ~2.0 it throws this [Exception](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Validator/Constraints/EmailValidator.php#L60) though.

2017-05-17 07:00 UTC, ro0NL commented
Agree with @xabbuh if you dont use strict validation you are free to use 2.0 in your own code, you just get compatibility issues. Not sure SF should conflict on this...

2017-05-17 07:30 UTC, xabbuh commented
@trsteel88 That's true, but IMO the message is descriptive enough so that one can fix their project accordingly.

2017-06-14 20:48 UTC, fabpot commented
Closing for the reasons given by @xabbuh

2017-06-14 20:48 UTC, closed without merging