Remove deprecated container injections and compiler passes
symfony/symfony pull request #22749
Opened 2017-05-18 08:11 UTC by chalasr

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | ~~#21451 #21625 #21284~~
| License       | MIT
| Doc PR        | n/a

2017-05-18 14:05 UTC, nicolas-grekas commented
rebase needed to see tests green

2017-05-18 15:00 UTC, chalasr commented
done, thanks

2017-05-18 16:58 UTC, stof requested changes

2017-05-18 16:58 UTC, stof commented on src/Symfony/Bundle/FrameworkBundle/Translation/Translator.php
> -        // BC 3.x, to be removed in 4.0 along with the $defaultLocale default value
you forgot to remove the default value

2017-05-18 17:05 UTC, chalasr commented on src/Symfony/Bundle/FrameworkBundle/Translation/Translator.php
> -        // BC 3.x, to be removed in 4.0 along with the $defaultLocale default value
fixed

2017-05-20 09:39 UTC, nicolas-grekas commented
missing CHANGELOG updates in components (please check any your other PRs also if any)

2017-05-20 10:05 UTC, chalasr commented
CHANGELOG entries added

2017-05-21 09:18 UTC, nicolas-grekas commented on src/Symfony/Bundle/FrameworkBundle/Translation/Translator.php
> +    public function __construct(ContainerInterface $container, MessageSelector $selector, $defaultLocale, array $loaderIds = array(), array $options = array())
it looks like the docblock is not up to date - and we could add a "string" type hint meanwhile here

2017-05-21 09:19 UTC, nicolas-grekas commented on src/Symfony/Bundle/FrameworkBundle/CHANGELOG.md
> + * [BC BREAK] removed `AddConsoleCommandPass`, `AddConstraintValidatorsPass`,
i'm not sore we need all these bc break prefixes, I'd remove them

2017-05-21 09:47 UTC, chalasr commented
@nicolas-grekas comments addressed

2017-05-21 09:54 UTC, nicolas-grekas commented
@chalasr would you mind opening a PR to fix that doc block in 3.3 (I guess)?

2017-05-21 09:57 UTC, nicolas-grekas commented
Thank you @chalasr.

2017-05-21 09:58 UTC, merged

2017-05-21 10:01 UTC, chalasr commented
@nicolas-grekas see https://github.com/symfony/symfony/pull/22822