[TwigBridge] remove deprecated features
symfony/symfony pull request #22783
Opened 2017-05-19 17:51 UTC by xabbuh

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | yes
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        |

2017-05-19 18:10 UTC, stof requested changes

2017-05-19 18:10 UTC, stof commented on src/Symfony/Bridge/Twig/Form/TwigRenderer.php
> +    public function __construct(TwigRendererEngine $engine, CsrfTokenManagerInterface $csrfTokenManager = null)
shouldn't the typeint be in FormRendererEngineInterface ?

2017-05-19 18:10 UTC, stof commented on src/Symfony/Bridge/Twig/Form/TwigRenderer.php
>          $this->engine = $engine;
you don't actually need this property, as it is now unused.

2017-05-19 20:28 UTC, xabbuh commented on src/Symfony/Bridge/Twig/Form/TwigRenderer.php
> +    public function __construct(TwigRendererEngine $engine, CsrfTokenManagerInterface $csrfTokenManager = null)
Not sure, shouldn't the Twig extension be sure that the underlying renderer engine supports Twig? By the way, if we did that change, that would mean that we could entirely drop the `TwigRenderer` class and use the parent `AbstractRendererEngine` class instead.

2017-05-20 10:33 UTC, Tobion requested changes

2017-05-20 10:33 UTC, Tobion commented on src/Symfony/Bridge/Twig/Form/TwigRenderer.php
> +class TwigRenderer extends FormRenderer
This class has no value anymore. `Symfony\Component\Form\FormRenderer` can be used directly now. So TwigRenderer  should be deprecated and removed IMO.

2017-07-06 13:22 UTC, Tobion commented on src/Symfony/Bridge/Twig/Form/TwigRenderer.php
> +class TwigRenderer extends FormRenderer
https://github.com/symfony/symfony/pull/23437

2017-07-17 09:43 UTC, nicolas-grekas commented
@xabbuh would be great to finish this one, that's one of the two last PR removing deprecated features. Thanks!

2017-07-17 11:15 UTC, xabbuh commented
@nicolas-grekas I think we should wait for #23437 to be able to remove the `TwigRenderer` class too.

2017-07-17 12:26 UTC, fabpot commented
#23437 merged now :)

2017-07-17 15:37 UTC, nicolas-grekas commented
rebase unlocked :)

2017-07-18 11:05 UTC, nicolas-grekas commented
Thank you @xabbuh.

2017-07-18 11:06 UTC, merged