[EventDispatcher] remove deprecated features
symfony/symfony pull request #22796
Opened 2017-05-20 06:47 UTC by xabbuh

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | yes
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        |

2017-05-20 09:37 UTC, chalasr requested changes
The following assignment https://github.com/symfony/symfony/blob/79bc3275db946f0ad816b3e04339eabc3f737ea5/src/Symfony/Component/DependencyInjection/ContainerBuilder.php#L1081 should be removed with usage below (see https://github.com/symfony/symfony/pull/22223)

2017-05-20 09:55 UTC, Koc commented on src/Symfony/Bundle/FrameworkBundle/Resources/config/services.xml
>              <argument type="service" id="service_container" />
does this argument not require changes?

2017-05-20 14:12 UTC, nicolas-grekas commented
Looks like 3.4 doesn't like this change - forward layer missing?

2017-05-21 07:53 UTC, xabbuh commented
see #22814

2017-05-21 09:35 UTC, xabbuh commented
builds are green, ready to be reviewed

2017-05-21 09:35 UTC, chalasr approved these changes
👍

2017-05-21 09:37 UTC, nicolas-grekas commented on src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php
> -                'Symfony\\Component\\EventDispatcher\\ContainerAwareEventDispatcher',
I think you should revert this line: it will only create a conflict with that other PR removing the block

2017-05-21 09:49 UTC, Koc commented on src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php
> -                'Symfony\\Component\\EventDispatcher\\ContainerAwareEventDispatcher',
without this change it would add to class cache non-existent class. Maybe better #22786 first

2017-05-21 09:52 UTC, nicolas-grekas commented
Thank you @xabbuh.

2017-05-21 09:52 UTC, nicolas-grekas commented on src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php
> -                'Symfony\\Component\\EventDispatcher\\ContainerAwareEventDispatcher',
ok merged, asis, #22786 already has conflicts to fix

2017-05-21 09:52 UTC, merged

2017-05-21 10:59 UTC, xabbuh commented on src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php
> -                'Symfony\\Component\\EventDispatcher\\ContainerAwareEventDispatcher',
@Koc Actually, that would not have been an issue. This part of the code is never executed on PHP 7 (which is a requirement for Symfony 4).