Cache ipCheck
symfony/symfony pull request #22819
Opened 2017-05-21 08:54 UTC by gonzalovilaseca

In our app we use trusted proxies. Using Blackfire we found `IpUtils::checkIp` was being called 454 times taking 3.15ms. 
Caching the result saves those 3ms.

| Q             | A
| ------------- | ---
| Branch?       | 2.8
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        |

2017-05-21 09:30 UTC, sstok requested changes

2017-05-21 09:30 UTC, sstok commented on src/Symfony/Component/HttpFoundation/Request.php
> +     * @var boolean
This needs to be `bool`, see fabbot.io patch

2017-05-21 09:30 UTC, sstok commented on src/Symfony/Component/HttpFoundation/Request.php
> +        if (!isset($this->validTrustedProxyIP)) {
It is possible that `self::$trustedProxies` is changed between method calls. Make sure to reset the cached result in `setTrustedProxies` and that this is tested.

2017-05-21 13:07 UTC, nicolas-grekas commented
shouldnt this fix be submitted against the 2.8 branch?

2017-05-21 15:40 UTC, gonzalovilaseca commented
Don't review yet please, I'll make tests pass first.

2017-05-21 16:35 UTC, gonzalovilaseca commented
I don't like leaking logic out of `isFromTrustedProxy`, ideally `validTrustedProxyIP` should be indexed by `trustedProxies` too, but hashing `trustedProxies` may be slower than actually calling `IpUtils::checkIp`.

I'll profile and report back.

2017-05-21 16:37 UTC, gonzalovilaseca commented
BTW, `REMOTE_ADDR` also seems to be mutable, in which cases does this value change during a single request?

2017-06-04 15:57 UTC, tgalopin commented
I stumbled upon the same issue in Blackfire. Shouldn't the cache be stored statically in `IpUtils` instead of in the request? It makes more sense to me, as the request is a representation of a HTTP object, using it to store cache feels wrong. Moreover, using a cache in IpUtils ensure a usage outside of the Request would still be cached.

WDYT?

2017-06-04 16:28 UTC, fabpot commented
Indeed, a cache in `IpUtils` seems a better idea.

2017-06-04 16:51 UTC, tgalopin commented
@gonzalovilaseca do you want to do it? I can if you don't have time right now.

2017-06-04 19:07 UTC, robfrawley commented on src/Symfony/Component/HttpFoundation/Tests/RequestTest.php
> +        $this->assertEquals(true, $request->isFromTrustedProxy());
```php
$this->assertTrue($this->isFromTrustedProxy());
```

2017-06-04 19:56 UTC, gonzalovilaseca commented
@tgalopin Sure, I'll do it, will be ready by tuesday

2017-06-05 05:54 UTC, stloyd requested changes

2017-06-05 05:54 UTC, stloyd commented on src/Symfony/Component/HttpFoundation/Tests/RequestTest.php
> +        $this->assertEquals(false, $request->isFromTrustedProxy());
`assertFalse()`

2017-06-05 05:54 UTC, stloyd commented on src/Symfony/Component/HttpFoundation/Tests/RequestTest.php
> +        $this->assertEquals(false, $request->isFromTrustedProxy());
`assertFalse()`

2017-06-05 05:54 UTC, stloyd commented on src/Symfony/Component/HttpFoundation/Request.php
> +        if (!array_key_exists($remoteAddr, self::$validTrustedProxyIP) || null === self::$validTrustedProxyIP[$remoteAddr]) {
Can be simply: `!isset(self::$validTrustedProxyIP[$remoteAddr])` cause you do check for `null` anyway.

2017-06-06 18:00 UTC, gonzalovilaseca commented
I've updated the PR moving the cache to `IpUtils`, I think that an `IpUtils` decorator would be a better solution, but being called statically from other places it would mean a bit of refactoring, should I go the `decorator` way or is this ok?

Feel free to improve the naming of the new methods, naming is not my strength, even less with jet lag :-).

2017-06-06 18:12 UTC, fabpot requested changes

2017-06-06 18:12 UTC, fabpot commented on src/Symfony/Component/HttpFoundation/IpUtils.php
> +    protected static $checkedIps = array();
Should be private

2017-06-06 18:12 UTC, fabpot commented on src/Symfony/Component/HttpFoundation/IpUtils.php
> +        return self::checkIpInternal($requestIp, $ip, 'self::checkIp4Internal');
I would not delegate to another method but just copy/paste the cache logic in the methods directly.

2017-06-06 18:22 UTC, fabpot commented on src/Symfony/Component/HttpFoundation/IpUtils.php
> +            self::$checkedIps[$cacheKey] = self::checkIp4Internal($requestIp, $ip);
I would inline the checkIp4Internal method as well.

2017-06-06 18:46 UTC, fabpot requested changes

2017-06-06 18:46 UTC, fabpot commented on src/Symfony/Component/HttpFoundation/IpUtils.php
> +     */
phpdoc should be removed

2017-06-06 18:46 UTC, fabpot commented on src/Symfony/Component/HttpFoundation/IpUtils.php
> +        if (!array_key_exists($cacheKey, self::$checkedIps)) {
I would return early:

```php
if (array_key_exists($cacheKey, self::$checkedIps)) {
    return self::$checkedIps[$cacheKey];
}
```

I would even change `arra_key_exists()` to `isset()`

2017-06-06 19:08 UTC, fabpot commented on src/Symfony/Component/HttpFoundation/IpUtils.php
> +        if (isset($cacheKey, self::$checkedIps)) {
Looks wrong to me

2017-06-06 19:14 UTC, fabpot commented
@gonzalovilaseca Can you change the branch of the PR to 2.7?

2017-06-06 19:22 UTC, gonzalovilaseca commented
@fabpot 2.7 or 2.8? (nicolas mentioned 2.8)

2017-06-06 19:25 UTC, fabpot commented
I would say 2.7.

2017-06-06 19:38 UTC, gonzalovilaseca commented
@fabpot `IpUtils` changed from 2.7 to 2.8, should I do a PR for each branch?

2017-06-06 22:13 UTC, fabpot commented
That would be wonderful, thanks.

2017-06-07 19:34 UTC, gonzalovilaseca commented
2.7 version here: https://github.com/symfony/symfony/pull/23098

2017-06-08 23:54 UTC, closed without merging