[Process] remove deprecated features
symfony/symfony pull request #22836
Opened 2017-05-21 18:34 UTC by xabbuh

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | yes
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        |

2017-05-21 19:13 UTC, nicolas-grekas commented
tests are failing :)

2017-06-09 00:32 UTC, fabpot requested changes
Tests still do not pass apparently.

2017-06-09 00:32 UTC, fabpot commented on src/Symfony/Component/Process/Process.php
> +            } else  {
extra space here

2017-06-21 07:35 UTC, stof requested changes

2017-06-21 07:35 UTC, stof commented on src/Symfony/Component/Process/CHANGELOG.md
> +   `ProcessBuilder` class have been removed
Wrong changelog entry. The whole class is gone

2017-06-26 08:05 UTC, xabbuh commented
I have removed the sigchild compatibility part as I did not manage to make it work properly. If someone wants to give it a try, you can just base your work on this PR or create a new one.

2017-06-28 07:16 UTC, fabpot approved these changes

2017-06-28 07:17 UTC, fabpot commented
Let's merge this one as is then.

2017-06-28 07:24 UTC, fabpot commented
Thank you @xabbuh.

2017-06-28 07:24 UTC, merged