Changed name of variables where variable name shortest
symfony/symfony pull request #22868
Opened 2017-05-23 08:47 UTC by imanalopher

2017-05-23 08:50 UTC, stof requested changes

2017-05-23 08:50 UTC, stof commented on src/Symfony/Bundle/FrameworkBundle/Controller/ControllerNameParser.php
> +        foreach ($allBundles as $bundle) {
this is not good. It overwrite the `$bundle` variable defined earlier, while it is still necesaary after to build the error message

2017-05-23 16:42 UTC, nicolas-grekas commented
Thank you @imanalopher but as Stof pointed out, a $bundle variable already exists into the scope.
Waiting for your second PR now :)

2017-05-23 16:42 UTC, closed without merging

2017-05-25 05:05 UTC, imanalopher commented
Thank you @nicolas-grekas!!!