[DI] Check for privates before shared services
symfony/symfony pull request #22866
Opened 2017-05-23 07:38 UTC by ro0NL

| Q             | A
| ------------- | ---
| Branch?       | 3.2
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | https://github.com/symfony/symfony/pull/22801/files#r117732213, https://github.com/symfony/symfony/pull/22801/files#r117732599
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

cc @stof

2017-05-23 07:47 UTC, nicolas-grekas commented
CI is red :)

2017-05-23 08:27 UTC, stof commented
@nicolas-grekas this is because of https://github.com/composer/composer/issues/6342

2017-05-23 08:29 UTC, ro0NL commented
Kinda clueless here... trying to fix `WebProfilerExtensionTest::testToolbarConfig`

patched `assertSaneContainer` so it skips private id's (hardcoded locally to test :)

however these 2 assertions pass for all provided debug modes, _indiviudally_;

```php
        $this->assertSaneContainer($this->getDumpedContainer(), '', array('web_profiler.csp.handler'));

        if ($listenerInjected) {
            $this->assertSame($listenerEnabled, $this->container->get('web_profiler.debug_toolbar')->isEnabled());
        }
```

the combination seems to trigger a deprecation :confused:

2017-05-23 08:31 UTC, ro0NL commented
first patch.. lets see what happens :)

2017-05-23 08:39 UTC, ro0NL commented
`testStopwatchExtensionAvailability` actually gets a private service :angry: 

`$container->get('twig.extension.debug.stopwatch')->getTokenParsers()`

is there a clean way to silence expected deprecations.. or should we do something else here.

2017-05-23 09:06 UTC, stof commented
well, the test should either not access a private service, or be marked as legacy. If the test is not meant to be removed in 4.0, marking it as legacy is not an option, and the test should be rewritten instead.
This is good that I catched the mistake in the deprecation trigger in the other PR, as this allowed us to catch mistakes in our own testsuite which was using deprecated APIs without getting the notice...

2017-05-23 09:10 UTC, ro0NL commented
Updated.. this should do. But i dont like it really :) but i guess we have no choice as we never decided how privates reflects a compiled containerbuilder.

2017-05-23 09:12 UTC, stof commented on src/Symfony/Bundle/TwigBundle/Tests/DependencyInjection/TwigExtensionTest.php
> +        $tokenParsers = $container->get('test_debug_stopwatch')->stopwatch->getTokenParsers();
a better solution would be to use `$container->get('twig')->getExtension(StopwatchExtension::class)` to access the extension, which avoids registering an extra service

2017-05-23 09:14 UTC, stof requested changes

2017-05-23 09:14 UTC, stof commented on src/Symfony/Component/DependencyInjection/Container.php
> +            if (isset($this->privates[$id]) && !$this instanceof ContainerBuilder) {
why the check on ContainerBuilder ? this is useless (`$this->privates` will be empty for them anyway)

2017-05-23 09:17 UTC, ro0NL commented on src/Symfony/Bundle/TwigBundle/Tests/DependencyInjection/TwigExtensionTest.php
> +        $tokenParsers = $container->get('test_debug_stopwatch')->stopwatch->getTokenParsers();
fixed

2017-05-23 09:17 UTC, ro0NL commented on src/Symfony/Component/DependencyInjection/Container.php
> +            if (isset($this->privates[$id]) && !$this instanceof ContainerBuilder) {
not sure.. https://github.com/symfony/symfony/blob/v3.2.8/src/Symfony/Component/DependencyInjection/ContainerBuilder.php#L577

but this definitely fixes tests :)

2017-05-23 09:19 UTC, ro0NL commented on src/Symfony/Component/DependencyInjection/Container.php
> +            if (isset($this->privates[$id]) && !$this instanceof ContainerBuilder) {
i think `ContainerBuilder` needs to behave the same as `Container`, _after_ compilation. But that could be a separate PR i guess. The changelog doesnt mention `ContainerBuilder` really...

2017-05-23 09:29 UTC, ro0NL commented on src/Symfony/Bundle/TwigBundle/Tests/DependencyInjection/TwigExtensionTest.php
> +        $tokenParsers = $container->get('test_debug_stopwatch')->stopwatch->getTokenParsers();
seems to break stuff :/

2017-05-23 09:32 UTC, nicolas-grekas commented
I think we should move this to 3.3: it will trigger more notices in 3.2 apps and break some strict CI for no real benefit.

2017-05-23 09:43 UTC, stof commented on src/Symfony/Component/DependencyInjection/Container.php
> +            if (isset($this->privates[$id]) && !$this instanceof ContainerBuilder) {
well, once compiled, the array is not empty anymore, but we *do* want the deprecation in this case. So please remove the extra check you added there (which was not there before moving the notice btw, so you are the one adding a difference in the behavior)

2017-05-23 09:45 UTC, ro0NL commented
3.2 is truly buggy though.. (@stof's comment in previous PR) i think the `ContainerBuilder` check will prevent those unexpected notices actually; while fixing `Container`.

otherwise, could you just commit the changelog against 3.2 :)) but you probably prefer a separate PR for that :P

2017-05-23 09:55 UTC, stof commented
@ro0NL the ContainerBuilder check does not solve anything in 3.2.
The issue was that we were missing deprecations when getting a private service which was already instantiated previously (due to being a dependency of another service you got earlier). This happens both for a ContainerBuilder and the dumped container.
Your check fixes the testsuite only because the testsuite does not do any such bad `get` calls on a dumped container (as most tests don't bother about dumping the container and then loading the dumped container to run assertions)

2017-05-23 15:09 UTC, ro0NL commented
@stof im still a bit confused.. (ive reverted the containerbuilder checks).

moving the private check up (above checking for shared services), truly fixes your comments from #22801, i.e. https://github.com/symfony/symfony/pull/22866/files#diff-8aeba2b88d0347062017ee160a6beb49R408 fails otherwise.

imo. it needs a fix for 3.2 (properly deprecating private services), but im missing something regarding the container builder. AFAIK the issue is `ContainerBuilder::get()` => `parent::get()`.

Updating [this](https://github.com/symfony/symfony/pull/22866/files#diff-00bc5ea153482178966f6617538a8e2eR217) call to `get()` still triggers the deprecation for private service `twig.extension.debug.stopwatch`. Im curious whats the root issue here, or at least what the proper fix is for either 3.2 or 3.3.

2017-05-23 15:20 UTC, ro0NL commented
Think this approach https://github.com/symfony/symfony/blob/v3.2.8/src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php#L1488 needs to be done in container builder after compilation... ie. bypasssing `get()` internally for privates.

2017-05-23 16:17 UTC, nicolas-grekas commented
My 2 cts: `ContainerBuilder` should not care about private or not. Thus, calling `parent::get()` shouldn't matter because `$this->privates` should not be populated.
I don't know where things fail right now but if we stick to this policy and tests fail, then I'd say these tests are broken, nothing else.

2017-05-23 16:20 UTC, nicolas-grekas commented
For me, https://github.com/symfony/symfony/blob/7fbda2eb6dbff31b864d5fff4ceb42c2c87857b3/src/Symfony/Component/DependencyInjection/ContainerBuilder.php#L577 should be removed, that's the bug.
ContainerBuilder is a bootstrap-stage thing, and private/public is a "compiled-container" only thing.

2017-05-23 17:02 UTC, ro0NL commented
Agree. I figured it out ;) i tend to qualify it a bug though.. as my perception is `compiled containerbuilder === compiled container === dumped  compiled container`, but for now we're good.

would be nice if `ContainerBuilder::compile()` returns a new (prepped) `Container`, that would allow to even further simplify (killing `isCompiled` and such), but that's quite a step though.

Squahsed&rebased. Ready for review :)

Sorry for the inconvenience, but this should do.

2017-05-23 17:14 UTC, stof commented
@nicolas-grekas currently, you can keep using a ContainerBuilder after compilation (which is what some projects do as they don't dump the container to the cache, for instance Behat)

2017-05-23 17:38 UTC, ro0NL commented
may i recall #20643 :) as containerbuilder is open for anything keeping privates empty is in line with that, and so a bugfix.

but the behavior is still wrong, however currently it's half right, half wrong.

2017-05-23 17:56 UTC, ro0NL commented on src/Symfony/Bundle/TwigBundle/Tests/DependencyInjection/TwigExtensionTest.php
> +        $tokenParsers = $container->get('test_debug_stopwatch')->stopwatch->getTokenParsers();
reverted the whole change, as with privates being empty it keeps working :)

this test should fail whenever we decide to change behavior.

2017-05-23 21:20 UTC, nicolas-grekas approved these changes
:+1:

2017-05-24 11:19 UTC, stof commented
We discussed this with @nicolas-grekas and here is the summary of changes we would want to get:

- add a hidden argument in `getServiceIds` to allow getting only public ids (i.e. opting in for the new behavior), and trigger a deprecation notice when getting the list with private ids in it (we have some existing code adding similar hidden arguments)
- retarget the PR to 3.3 (due to the above previous deprecation)
- try to keep the existing code filling the `privates` array in the ContainerBuilder, and debug test failures instead. As the 3.4 branch will allow using 4.0 deps, accessing private services in tests will be forbidden anyway. I suspect several failures are related to `getServiceIds` and so could be solved by the first point.

@ro0NL can you work on it ? Otherwise, I can take this PR over this evening to finish it

2017-05-24 11:38 UTC, ro0NL commented
@stof i will finish it tonight :) so no changes for 3.2 right?

> try to keep the existing code filling the privates array in the ContainerBuilder

so we dont allow fetching privates using containerbuilder right (after compiling). `getServiceIds` will be the least problem :) it needs to bypass `get()` for references etc. internally. ie. what the phpdumper does.

2017-05-24 11:46 UTC, ro0NL commented
@stof `Allow edits from maintainers` is enabled.. so feel free to add commits though :)

2017-05-24 14:23 UTC, fabpot commented
Thank you @ro0NL.

2017-05-24 14:25 UTC, merged

2017-05-24 14:40 UTC, nicolas-grekas commented
3.2 now merged into 3.3 so that next steps can happen on 3.3