[Yaml] Deprecate tags using colon
symfony/symfony pull request #22913
Opened 2017-05-25 10:23 UTC by GuilhemN

| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no 
| BC breaks?    | no
| Deprecations? | yes
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        | 

Using a colon in a tag doesn't look like yaml and causes trouble (see https://github.com/symfony/symfony/pull/22878), so I propose to just deprecate these tags in favor of more natural tags.

2017-05-25 10:35 UTC, xabbuh commented
👍 (we will probably still need some special handling for the `!php/const` tag though as referring to class constants still requires us to use colons inside a mapping key)

2017-05-25 10:37 UTC, GuilhemN commented
The handling won't be dedicated, the value will just need to be quoted:
```yml
!php/const "Foo::BAR": quz
```

2017-05-29 20:22 UTC, GuilhemN commented
PR broken for now, will fix it later.

2017-06-28 04:39 UTC, teohhanhui commented on src/Symfony/Component/Yaml/Inline.php
> +                            @trigger_error('The !!php/object: tag to indicate dumped PHP objects is deprecated since version 3.1 and will be removed in 4.0. Use the !php/object (without the colon) ta
3.4

2017-06-28 08:09 UTC, stof requested changes

2017-06-28 08:09 UTC, stof commented on UPGRADE-3.4.md
> +>>>>>>> [Yaml] Deprecate tags using colon
this line must be removed. You messed some conflict resolution

2017-06-29 11:46 UTC, GuilhemN commented on UPGRADE-3.4.md
> +>>>>>>> [Yaml] Deprecate tags using colon
indeed

2017-06-29 11:46 UTC, GuilhemN commented
Rebased on 3.4, it should be ok now.

2017-07-06 10:20 UTC, fabpot approved these changes

2017-07-06 10:20 UTC, fabpot commented
@xabbuh Can you check this one please?

2017-07-24 09:10 UTC, GuilhemN commented
The build failure is because this is not yet in master.

2017-07-26 19:04 UTC, chalasr approved these changes

2017-07-31 17:46 UTC, chalasr commented
Needs rebase

2017-08-01 08:47 UTC, GuilhemN commented
@chalasr rebased.

2017-08-04 09:02 UTC, xabbuh approved these changes
just a few minor comments

2017-08-04 09:02 UTC, xabbuh commented on src/Symfony/Component/Yaml/CHANGELOG.md
> + * Deprecated the tag`!php/object:` tag which will be replaced by the
the "tag" in front of `!php/object:` should be removed

2017-08-04 09:02 UTC, xabbuh commented on src/Symfony/Component/Yaml/CHANGELOG.md
> + * Deprecated the tag`!php/const:` tag which will be replaced by the
the "tag" in front of `!php/const:` should be removed

2017-08-04 09:02 UTC, xabbuh commented on src/Symfony/Component/Yaml/Inline.php
> +
no need for this blank line

2017-08-04 09:11 UTC, GuilhemN commented
@xabbuh fixed

2017-08-04 12:55 UTC, stof approved these changes

2017-08-04 13:31 UTC, xabbuh commented
Thank you @GuilhemN.

2017-08-04 13:32 UTC, closed without merging