[SecurityBundle] Move cache of the firewall context into the request parameters
symfony/symfony pull request #22943
Opened 2017-05-29 17:16 UTC by GromNaN

Following [this proposal](https://github.com/symfony/symfony/pull/22605#issuecomment-301276639). Since the matching context relates to the request, this information should have been cached inside the request parameters.

| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #22605
| License       | MIT
| Doc PR        | n/a

* Avoid memory leak when handling multiple requests
* Adding the new request parameter `_firewall_context` might be considered as a breaking change.

2017-05-29 17:22 UTC, stof requested changes

2017-05-29 17:22 UTC, stof commented on src/Symfony/Bundle/SecurityBundle/Security/FirewallMap.php
> +        if ($request->attributes->has('_firewall_context')) {
you should validate that `$request->attributes->get('_firewall_context')` is a valid key of `$this->map`

2017-05-29 17:23 UTC, stof commented
why is it opened against the master branch if you want it for 3.4 ? master is 4.0

2017-05-29 17:37 UTC, GromNaN commented on src/Symfony/Bundle/SecurityBundle/Security/FirewallMap.php
> +        if ($request->attributes->has('_firewall_context')) {
Done. And added test assertions on the value of this attribute.

2017-05-29 17:59 UTC, ogizanagi approved these changes

2017-05-30 09:29 UTC, chalasr requested changes

2017-05-30 09:29 UTC, chalasr commented on src/Symfony/Bundle/SecurityBundle/Security/FirewallMap.php
> +            if (array_key_exists($contextId, $this->map)) {
`$this->map` can be `Traversable` (and [it is](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php#L255))

2017-05-31 10:39 UTC, chalasr approved these changes
Build failures unrelated

2017-06-05 20:30 UTC, GromNaN commented
Is it possible that a sub-request get created with all the attributes of its master request? In that case, using the request attributes as a cache would be wrong.

2017-06-09 00:18 UTC, fabpot requested changes
Why does it target 3.4. Looks like a bug fix to me, so it should be done in earliest branches as well.

2017-06-09 00:18 UTC, fabpot commented on src/Symfony/Bundle/SecurityBundle/Security/FirewallMap.php
> +     * @param Request $request
should be removed

2017-06-09 00:18 UTC, fabpot commented on src/Symfony/Bundle/SecurityBundle/Security/FirewallMap.php
> +     * @return \Symfony\Bundle\SecurityBundle\Security\FirewallContext
You should add a `use` statement and use `FirewallContext` here instead.

2017-06-09 12:24 UTC, GromNaN commented
@fabpot The cache was introduced in 3.2. I've updated the PR.

2017-06-10 15:14 UTC, fabpot requested changes

2017-06-10 15:14 UTC, fabpot commented on src/Symfony/Bundle/SecurityBundle/Security/FirewallMap.php
> +use Symfony\Bundle\SecurityBundle\Security\FirewallContext
missing `;` at then end

2017-06-10 16:35 UTC, GromNaN commented on src/Symfony/Bundle/SecurityBundle/Security/FirewallMap.php
> +use Symfony\Bundle\SecurityBundle\Security\FirewallContext
Sorry, fixed.

2017-06-10 17:56 UTC, fabpot commented
Tests are broken.

2017-06-10 22:17 UTC, GromNaN commented on src/Symfony/Bundle/SecurityBundle/Tests/Security/FirewallMapTest.php
> +        $firewallContext->expects($this->once())->method('getContext')->willReturn(array('LISTENERS', 'EXCEPTION LISTENER'));
While merging into 3.3, [`getContext` is replaced by `getListeners` and `getExceptionListener`](https://github.com/symfony/symfony/blob/3.3/src/Symfony/Bundle/SecurityBundle/Security/FirewallContext.php#L40-L58):
```php
$firewallContext->expects($this->once())->method('getListeners')->willReturn('LISTENERS');
$firewallContext->expects($this->once())->method('getExceptionListener')->willReturn('EXCEPTION LISTENER');
```

2017-06-10 22:38 UTC, GromNaN commented on src/Symfony/Bundle/SecurityBundle/Security/FirewallMap.php
> +     * @return \Symfony\Bundle\SecurityBundle\Security\FirewallContext
After this change, fabbot reports is as an unused import and removes the `use` statement.

2017-06-14 20:21 UTC, fabpot approved these changes

2017-06-14 20:22 UTC, fabpot commented
Thank you @GromNaN.

2017-06-14 20:28 UTC, chalasr commented
should be closed

2017-06-14 20:33 UTC, fabpot commented on src/Symfony/Bundle/SecurityBundle/Tests/Security/FirewallMapTest.php
> +        $firewallContext->expects($this->once())->method('getContext')->willReturn(array('LISTENERS', 'EXCEPTION LISTENER'));
Done, thanks

2017-06-14 20:33 UTC, closed without merging