[2.8][TwigBundle] Fix kernel bootability even if a twig extension fails on constructor
symfony/symfony pull request #23014
Opened 2017-06-01 12:43 UTC by romainneutron

| Q             | A
| ------------- | ---
| Branch?       | 2.8
| Bug fix?      | yes
| New feature?  | no 
| BC breaks?    | no
| Deprecations? | no 
| Tests pass?   | yes
| Fixed tickets | N/A
| License       | MIT
| Doc PR        | N/A

Since version 2.8, if a Twig extension throws an exception in constructor, then the Kernel can not boot anymore because a service used by the Twig cache warmer instantiates Twig. As Twig cache warmer is optional, Twig should not be loaded at Kernel boot, and this patch fixes the issue

2017-06-01 12:45 UTC, romainneutron commented
For the record, passing a Twig_Environment on constructor might be deprecated on 3.4. Are you okay with this ? In this case i'd do the PR once this one is merged

2017-06-01 12:51 UTC, nicolas-grekas approved these changes
:+1:

2017-06-01 13:07 UTC, stof commented
Isn't it true for any cache warmer though ? As soon as a cache warmer has deps, booting requires to instantiate the object graph

2017-06-01 13:18 UTC, romainneutron commented
@stof I don't know. What I'm sure is that is a regression from Symfony 2.7

2017-06-01 13:20 UTC, romainneutron commented
FYI here are the services that are instanciated on cache warm: 
router / translator / doctrine manager registry

2017-06-01 13:33 UTC, romainneutron commented
FYI the Symfony\Bridge\Doctrine\CacheWarmer\ProxyCacheWarmer is not optional, so there's no optimization to do here.
However, the same patch can be applied to 
`Symfony\Bundle\FrameworkBundle\CacheWarmer\RouterCacheWarmer` and 
`Symfony\Bundle\FrameworkBundle\CacheWarmer\TranslationsCacheWarmer`

2017-06-01 16:01 UTC, romainneutron commented
PR updated, I've fixed the three optional cache warmers

2017-06-01 17:35 UTC, fabpot requested changes
For the two additional cache warmers, you forgot to update the XML definitions.

2017-06-01 20:04 UTC, romainneutron commented
Woops ! It's now fixed

2017-06-01 20:13 UTC, fabpot commented
Can you add a note on each cache warmer class to explain why we want to inject the Container instead of the real service? That would avoid PRs that remove that later on.

2017-06-01 20:13 UTC, nicolas-grekas commented on src/Symfony/Bundle/FrameworkBundle/CacheWarmer/RouterCacheWarmer.php
>      protected $router;
Let's revert changes on this file, it's a BC break because of this protected property.

2017-06-01 20:13 UTC, fabpot commented on src/Symfony/Bundle/FrameworkBundle/CacheWarmer/RouterCacheWarmer.php
> +    public function __construct($container)
I would had a phpdocs with the 2 possible classes

2017-06-01 20:29 UTC, romainneutron commented
PR updated comments addressed

2017-06-01 20:33 UTC, fabpot requested changes

2017-06-01 20:33 UTC, fabpot commented on src/Symfony/Bundle/FrameworkBundle/CacheWarmer/TranslationsCacheWarmer.php
> +        /**
fabbot is right :-)

2017-06-01 20:33 UTC, fabpot commented on src/Symfony/Bundle/FrameworkBundle/CacheWarmer/TranslationsCacheWarmer.php
> +         */
What about:

As this cache warmer is optional, dependencies should be lazy-loaded, that's why a container should be injected.

2017-06-01 20:33 UTC, fabpot commented on src/Symfony/Bundle/FrameworkBundle/CacheWarmer/TranslationsCacheWarmer.php
> +    public function __construct($container)
Can you add the phpdoc about the possible classes accepted for $container?

2017-06-02 07:56 UTC, romainneutron commented
PR Updated comments addressed

2017-06-02 09:15 UTC, nicolas-grekas commented
Thank you @romainneutron.

2017-06-02 09:15 UTC, merged