Parse the _controller format in sub-requests
symfony/symfony pull request #23013
Opened 2017-06-01 10:48 UTC by weaverryan

| Q             | A
| ------------- | ---
| Branch?       | 3.3
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | possibly (edge case)
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #22966 
| License       | MIT
| Doc PR        | n/a

As mentioned on the issue (https://github.com/symfony/symfony/issues/22966#issuecomment-305289227), the new "controller service args" functionality relies on the `_controller` attribute to be in either the service format `App\Controller\Foo:bar` or at least the final parsed format `App\Controller\Foo::bar`. But when you make a sub-request with the `App:Foo:bar` format, the `ControllerResolver` correctly parses this, but the `_controller` request attribute will always contain the original `App:Foo:bar` format. That causes the `ServiceValueResolver` to fail. 

The only way I can think to fix this - reliably - is to parse the `_controller` attribute in a listener. And this, works great! Notes:

A) There is a small chance for a BC break: if you were relying on the `_controller` old format in a `kernel.request` format in the framework, in a listener between the priority of 25 and 31 for sub-requests (because normal requests have `_controller` normalized during routing)... then you will see a behavior change.

B) We could load the `ControllerNameParser` lazily via a service locator.

C) We could deprecate calling the parser in the FW's `ControllerResolver`. Along with (B), I think it would (in 4.0) mean that the `ControllerNameParser` is not instantiated at runtime (except for sub-requests).

If someone can think of a different/better solution, please let me know!

Cheers!

2017-06-01 11:01 UTC, jvasseur commented
Another solution would be to calls the resolve the controller name with the `ControllerNameParser` in the `ServiceValueResolver`.

This would remove the BC break.

2017-06-01 12:20 UTC, stof requested changes

2017-06-01 12:20 UTC, stof commented on src/Symfony/Bundle/FrameworkBundle/Resources/config/web.xml
> +        <service id="resolve_controller_name_subscriber" class="Symfony\Bundle\FrameworkBundle\EventListener\ResolveControllerNameSubscriber" public="true">
should not be public. Listeners can be private now, and there is no BC issue about making this one private as it is new

2017-06-01 12:20 UTC, stof commented on src/Symfony/Bundle/FrameworkBundle/EventListener/ResolveControllerNameSubscriber.php
> +            KernelEvents::REQUEST => array(array('onKernelRequest', 24)),
you can simplify this as `array('onKernelRequest', 24)`

2017-06-01 14:01 UTC, weaverryan commented
@jvasseur I really like that idea... but the `ServiceValueResolver` is in the component, and the `ControllerNameParser` is in the framework only. So, this approach *is* still a valid alternative. Specifically, instead of a subscriber, we would sub-class the `ServiceValueResolver` in the FW to parse the controller string. Do people like that better?

In the mean time, I've made updates from Stof's comments!

2017-06-02 19:01 UTC, nicolas-grekas approved these changes
:+1:

2017-06-02 21:53 UTC, fabpot commented
Thank you @weaverryan.

2017-06-02 21:53 UTC, merged