[WebProfilerBundle] Add user impersonation info and exit action
symfony/symfony pull request #23026
Opened 2017-06-02 00:21 UTC by yceruto

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| License       | MIT

Toolbar result:

![impersonated_user](https://cloud.githubusercontent.com/assets/2028198/26705857/eb045bb0-4706-11e7-9a82-1878e62b0750.png)

I'm no sure if more information should be displayed from source token, wdyt?

Security profile panel result:

![security_token_profile_panel](https://cloud.githubusercontent.com/assets/2028198/26705860/f7a64054-4706-11e7-9eef-6cd6b7365738.png)

2017-06-02 03:26 UTC, yceruto commented
AppVeyor fails unrelated

2017-06-02 07:30 UTC, iltar commented on src/Symfony/Bundle/SecurityBundle/Resources/views/Collector/security.html.twig
> +                    <span>{{ collector.impersonatedSourceUser }}</span>
What about "Impersonator" instead? When reading this (at least as non-native English speaker), it sounds to me as if I'm impersonating as this person, while I am this person, impersonating as someone else.

2017-06-02 08:10 UTC, ogizanagi commented on src/Symfony/Bundle/SecurityBundle/Resources/views/Collector/security.html.twig
> +                    <span>{{ collector.impersonatedSourceUser }}</span>
I had the same feeling. So 👍 for this suggestion.

2017-06-02 08:23 UTC, ogizanagi commented on src/Symfony/Bundle/SecurityBundle/DataCollector/SecurityDataCollector.php
> +                    $exitPath .= false === strpos($exitPath, '?') ? '?' : '&';
```diff
- $exitPath .= false === strpos($exitPath, '?') ? '?' : '&';
+ $exitPath .= null === $request->getQueryString() ? '?' : '&';
```

?

2017-06-02 08:23 UTC, ogizanagi commented on src/Symfony/Bundle/SecurityBundle/Security/FirewallConfig.php
> +    public function __construct($name, $userChecker, $requestMatcher = null, $securityEnabled = true, $stateless = false, $provider = null, $context = null, $entryPoint = null, $switchUser = null, $a
The class is final, but I guess it's still a BC break to change the arguments order if someone is instantiating this class himself somewhere.

Also, considering you don't really need the `switch_user` config, but simply know if it's enabled or not, I think you can avoid adding this and simply search for `switch_user` in the array of listeners.

2017-06-02 08:24 UTC, ogizanagi commented on src/Symfony/Bundle/SecurityBundle/Security/FirewallConfig.php
> +    public function __construct($name, $userChecker, $requestMatcher = null, $securityEnabled = true, $stateless = false, $provider = null, $context = null, $entryPoint = null, $switchUser = null, $a
Oh, NVM. You actually need the config details to get the parameter...

2017-06-02 09:08 UTC, stof commented on src/Symfony/Bundle/SecurityBundle/Security/FirewallConfig.php
> +    public function __construct($name, $userChecker, $requestMatcher = null, $securityEnabled = true, $stateless = false, $provider = null, $context = null, $entryPoint = null, $switchUser = null, $a
Adding a new argument must indeed be done at the end, to avoid BC breaks

2017-06-02 09:10 UTC, stof commented on src/Symfony/Bundle/SecurityBundle/DataCollector/SecurityDataCollector.php
> +                    $exitPath .= $switchUserConfig['parameter'].'=_exit';
missing `urlencode` on the parameter name

2017-06-02 09:18 UTC, nicolas-grekas commented
Should be for 3.4

2017-06-02 11:51 UTC, yceruto commented on src/Symfony/Bundle/SecurityBundle/Security/FirewallConfig.php
> +    public function __construct($name, $userChecker, $requestMatcher = null, $securityEnabled = true, $stateless = false, $provider = null, $context = null, $entryPoint = null, $switchUser = null, $a
Indeed, done!

2017-06-02 11:52 UTC, yceruto commented on src/Symfony/Bundle/SecurityBundle/DataCollector/SecurityDataCollector.php
> +                    $exitPath .= false === strpos($exitPath, '?') ? '?' : '&';
Much better, thanks :)

2017-06-02 11:52 UTC, yceruto commented on src/Symfony/Bundle/SecurityBundle/DataCollector/SecurityDataCollector.php
> +                    $exitPath .= $switchUserConfig['parameter'].'=_exit';
fixed

2017-06-02 11:54 UTC, yceruto commented on src/Symfony/Bundle/SecurityBundle/Resources/views/Collector/security.html.twig
> +                    <span>{{ collector.impersonatedSourceUser }}</span>
I also felt insecure with these names, thanks!

2017-06-02 11:57 UTC, yceruto commented
Comments addressed and I've updated the screenshot with "Impersonator" label, thanks!

2017-06-02 12:00 UTC, ogizanagi commented
You forgot to change the targeted branch for 3.4 😉

2017-06-02 14:26 UTC, yceruto commented
Sorry for the (base branch) mess :) I was not on the PC and I needed to resolve a conflict.

Rebased!

2017-06-09 12:36 UTC, yceruto commented on src/Symfony/Bundle/SecurityBundle/DataCollector/SecurityDataCollector.php
> +                    $exitPath .= urlencode($switchUserConfig['parameter']).'=_exit';
We should add/use a `const EXIT = '_exit'` into `SwitchUserListener` to avoid relying on "magic strings"? It's worth?

2017-06-20 20:23 UTC, noniagriconomie commented on src/Symfony/Bundle/SecurityBundle/DataCollector/SecurityDataCollector.php
> +                    $exitPath .= urlencode($switchUserConfig['parameter']).'=_exit';
At least an @see comment pointing the code where _exit is used

2017-06-21 15:14 UTC, yceruto commented
The failure occurs in [`deps=high`](https://travis-ci.org/symfony/symfony/jobs/245388903#L2545) because the new `const` does not exists in `master` yet.

I've finished here, ready for final review!

2017-06-21 16:46 UTC, fabpot requested changes
deps in composer.json should be updated as well as the bundle requires the constant to be available.

2017-06-21 16:46 UTC, fabpot commented on src/Symfony/Bundle/SecurityBundle/DataCollector/SecurityDataCollector.php
> +     */
This phpdoc block and the two next ones can be removed and they don't bring much additional value.

2017-06-21 16:46 UTC, fabpot commented on src/Symfony/Bundle/SecurityBundle/Security/FirewallConfig.php
> +     * @return array|null The switch_user config if enabled, null otherwise
I don't understand the description

2017-06-21 17:37 UTC, yceruto commented
@fabpot the `composer.json` of the bundle was already updated [in other PR](https://github.com/symfony/symfony/pull/23105/files#diff-2f921a4ac8ad70d0453786e1099c3f9fR20) to the top available `~3.4` ([Btw same case of failure (see comment)](https://github.com/symfony/symfony/pull/23105#issuecomment-307324818)) and the constant was introduced here too, so I don't understand what I should do to avoid the failure on `deps=high` which loads `dev-master` (`~4.0`) of the Security Component?

I guess this failure will be solved when this commit is merged into `master` branch?

2017-06-21 17:39 UTC, yceruto commented on src/Symfony/Bundle/SecurityBundle/DataCollector/SecurityDataCollector.php
> +     */
Removed

2017-06-21 19:27 UTC, fabpot approved these changes

2017-06-21 19:59 UTC, fabpot commented
Thank you @yceruto.

2017-06-21 20:00 UTC, closed without merging