[DoctrineBridge][PropertyInfo] Added support for Doctrine Embeddables
symfony/symfony pull request #23023
Opened 2017-06-01 20:52 UTC by vudaltsov

| Q             | A
| ------------- | ---
| Branch?       | 2.8 and higher
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        | 

Note that [Embeddables appeared only in doctrine/orm 2.5](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/changelog/migration_2_5.html). I added class_exists checks for that.

2017-06-01 21:01 UTC, nicolas-grekas commented on src/Symfony/Bridge/Doctrine/Tests/PropertyInfo/DoctrineExtractorTest.php
> +        $expectedTypes = [new Type(
please use array() instead of []

2017-06-01 21:08 UTC, vudaltsov commented on src/Symfony/Bridge/Doctrine/Tests/PropertyInfo/DoctrineExtractorTest.php
> +        $expectedTypes = [new Type(
thank you, changed PHP version to 5.3 in PhpStorm for this project and fixed declaration

2017-06-01 21:40 UTC, vudaltsov commented
Suddenly I faced another problem with embeddables.

When an entity has properties with embeddables, `Doctrine\Common\Persistence\Mapping\ClassMetadata::getFieldNames()` returns property paths for them. Example:

```php
/**
 * @ORM\Entity
 */
class DoctrineWithEmbedded
{
    /**
     * @Id
     * @Column(type="smallint")
     */
    public $id;

    /**
     * @Embedded(class="DoctrineEmbeddable")
     */
    protected $embedded;
}

/**
 * @ORM\Embeddable
 */
class DoctrineEmbeddable
{
    /**
     * @Column(type="string")
     */
    protected $field;
}

$container->get('doctrine.orm.default_entity_manager.metadata_factory')
    ->getMetadataFor('DoctrineWithEmbedded')
    ->getFieldNames();

// returns
[
    'id',
    'embedded.field',
];
```

Fixed this in the next commit.

2017-06-02 07:46 UTC, stloyd requested changes

2017-06-02 07:46 UTC, stloyd commented on src/Symfony/Bridge/Doctrine/Tests/PropertyInfo/DoctrineExtractorTest.php
> +            return;
You should put `$this->markTestSkipped()` with message that embedded is not available.

2017-06-02 07:46 UTC, stloyd commented on src/Symfony/Bridge/Doctrine/Tests/PropertyInfo/DoctrineExtractorTest.php
> +            return;
Same here.

2017-06-02 09:29 UTC, vudaltsov commented on src/Symfony/Bridge/Doctrine/Tests/PropertyInfo/DoctrineExtractorTest.php
> +            return;
Thank you, fixed this!

2017-06-02 09:33 UTC, stloyd approved these changes

2017-06-11 14:38 UTC, vudaltsov commented
@nicolas-grekas, anything else needed here? could it be merged?

2017-06-14 18:30 UTC, dunglas commented
This should be merged in 3.4 (it's a new feature, not a bug fix).

2017-06-14 18:35 UTC, dunglas requested changes
Nice improvement! I just left some minor comments.

2017-06-14 18:35 UTC, dunglas commented on src/Symfony/Bridge/Doctrine/PropertyInfo/DoctrineExtractor.php
> +            if ($metadata instanceof ClassMetadataInfo && count($metadata->embeddedClasses) > 0) {
`&& $metadata->embeddedClasses` will be faster.

2017-06-14 18:35 UTC, dunglas commented on src/Symfony/Bridge/Doctrine/PropertyInfo/DoctrineExtractor.php
> +        if (class_exists('Doctrine\ORM\Mapping\Embedded')) {
As we'll merge this PR in 3.4, you can import this class and do `class_exists(Embedded::class)`.

2017-06-14 18:35 UTC, dunglas commented on src/Symfony/Bridge/Doctrine/PropertyInfo/DoctrineExtractor.php
> +        if (class_exists('Doctrine\ORM\Mapping\Embedded')) {
same here, same in tests.

2017-06-14 18:55 UTC, vudaltsov commented
@dunglas, the problem is that now when you do
```php
$container
    ->get('doctrine.orm.default_entity_manager.property_info_extractor')
    ->getProperties(DoctrineWithEmbedded::class); // the class from my example above
```
you receive 
```php
[
    'id',
    'embedded.field', // not embedded
];
```
which is not what developer might expect.

So it appears that currently 2.8 doesn't fully support ORM, which might lead to unexpected behaviour. Isn't it a bug?

2017-06-29 12:17 UTC, dunglas commented
Ok to consider it a bug fix then. 👍 

ping @symfony/deciders

2017-06-29 12:17 UTC, dunglas approved these changes

2017-07-13 12:42 UTC, vudaltsov commented
@symfony/deciders, anything else needed here?

2017-07-13 17:14 UTC, xabbuh approved these changes

2017-07-22 13:54 UTC, dunglas commented on src/Symfony/Bridge/Doctrine/PropertyInfo/DoctrineExtractor.php
> +        if (class_exists('Doctrine\ORM\Mapping\Embedded') && $metadata instanceof ClassMetadataInfo && $metadata->embeddedClasses) {
Can you call class_exists after the other tests (for perf, function calls cost more than other checks)?

2017-07-22 14:34 UTC, vudaltsov commented on src/Symfony/Bridge/Doctrine/PropertyInfo/DoctrineExtractor.php
> +        if (class_exists('Doctrine\ORM\Mapping\Embedded') && $metadata instanceof ClassMetadataInfo && $metadata->embeddedClasses) {
@dunglas, when class `Doctrine\ORM\Mapping\Embedded` doesn't exist, `$metadata->embeddedClasses` is not defined. I can only move `instanceof` check to the first place.

2017-07-22 15:06 UTC, dunglas commented on src/Symfony/Bridge/Doctrine/PropertyInfo/DoctrineExtractor.php
> +        if (class_exists('Doctrine\ORM\Mapping\Embedded') && $metadata instanceof ClassMetadataInfo && $metadata->embeddedClasses) {
Ok can you do that? Then I'll merge :)

2017-07-22 15:51 UTC, vudaltsov commented on src/Symfony/Bridge/Doctrine/PropertyInfo/DoctrineExtractor.php
> +        if (class_exists('Doctrine\ORM\Mapping\Embedded') && $metadata instanceof ClassMetadataInfo && $metadata->embeddedClasses) {
@dunglas, done!

2017-07-22 16:46 UTC, dunglas commented
Thank you @vudaltsov.

2017-07-22 16:47 UTC, closed without merging