Automatically enable the routing annotation loader
symfony/symfony pull request #23044
Opened 2017-06-02 18:09 UTC by GuilhemN

| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | yes 
| BC breaks?    | no
| Deprecations? | no 
| Tests pass?   | yes
| Fixed tickets | I think there's one but I didn't find it
| License       | MIT
| Doc PR        | 

Thanks to fqcn services, most of the time, we don't need the SensioFrameworkExtraBundle for `@Route` anymore.
So I suggest to automatically enable it when annotations are enabled. This way we could simplify https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/3.3/etc/routing.yaml#L5.

Note: I added priority support on routing loaders to make sure sensio loaders are loaded before ours.

2017-06-06 18:16 UTC, fabpot requested changes
How does that play with framework extra bundle when installed?

2017-06-06 18:16 UTC, fabpot commented on src/Symfony/Bundle/FrameworkBundle/Routing/AnnotatedRouteControllerLoader.php
> +        $routeName = parent::getDefaultRouteName($class, $method);
Could be inlined

2017-06-07 10:11 UTC, GuilhemN commented
> How does that play with framework extra bundle when installed? 

Sensio's loaders take precedence over these loaders because of [their priority](https://github.com/symfony/symfony/pull/23044/files#diff-0e793081ceb720201745c982a568903fR701).

2017-06-07 10:21 UTC, GuilhemN commented on src/Symfony/Bundle/FrameworkBundle/Routing/AnnotatedRouteControllerLoader.php
> +        $routeName = parent::getDefaultRouteName($class, $method);
done

2017-06-09 00:11 UTC, fabpot approved these changes

2017-06-09 00:12 UTC, fabpot commented
Thank you @GuilhemN.

2017-06-09 00:12 UTC, merged