[HttpFoundation] add back support for legacy constant values
symfony/symfony pull request #23074
Opened 2017-06-05 20:57 UTC by xabbuh

| Q             | A
| ------------- | ---
| Branch?       | 3.3
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        | 

Due to the data type change of the `Request::HEADER_` constants in Symfony 3.3 #23067 introduced a small BC break if someone used the old constant values statically instead of referring to the constants themselves.

2017-06-06 04:47 UTC, nicolas-grekas commented
I'm not sure we should go that far in BC, especially since this is non serializable data (since we're talking about consts used in static props only.)
I'd suggest to wait for an actual bug report before adding this.

2017-06-06 07:26 UTC, xabbuh commented
The thing is we even advised to use these strings in the previous docblocks of [`getClientIp()`](https://github.com/symfony/symfony/blob/3.2/src/Symfony/Component/HttpFoundation/Request.php#L823-L825), [`getPort()`](https://github.com/symfony/symfony/blob/3.2/src/Symfony/Component/HttpFoundation/Request.php#L930-L931), [`isSecure()`](https://github.com/symfony/symfony/blob/3.2/src/Symfony/Component/HttpFoundation/Request.php#L1147-L1149) and [`getHost()`](https://github.com/symfony/symfony/blob/3.2/src/Symfony/Component/HttpFoundation/Request.php#L1172-L1173).

2017-06-06 14:43 UTC, apetitpa requested changes

2017-06-06 14:43 UTC, apetitpa commented on src/Symfony/Component/HttpFoundation/Request.php
> +        if ('forwared' === $key) {
forwarded ?

2017-06-09 00:10 UTC, fabpot requested changes

2017-06-09 00:10 UTC, fabpot commented on src/Symfony/Component/HttpFoundation/Request.php
> +        if ('forwared' === $key) {
indeed

2017-06-14 19:38 UTC, fabpot approved these changes

2017-06-14 19:40 UTC, fabpot commented
Thank you @xabbuh.

2017-06-14 19:40 UTC, merged