[Security] Fix annotation
symfony/symfony pull request #23107
Opened 2017-06-08 13:38 UTC by enumag

| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        |

2017-06-08 18:09 UTC, dmaicher commented on src/Symfony/Component/Security/Core/Authentication/Token/UsernamePasswordToken.php
> +     * @param mixed                    $credentials This usually is the password of the user
why would it not be a `string`?

2017-06-08 18:13 UTC, enumag commented on src/Symfony/Component/Security/Core/Authentication/Token/UsernamePasswordToken.php
> +     * @param mixed                    $credentials This usually is the password of the user
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Security/Core/Authentication/Token/TokenInterface.php#L40-L45

In my app it is null in some cases like impersonation.

2017-06-09 00:06 UTC, fabpot requested changes

2017-06-09 00:06 UTC, fabpot commented on src/Symfony/Component/Security/Core/Authentication/Token/UsernamePasswordToken.php
> +     * @param mixed                    $credentials This usually is the password of the user
Then string|null?

2017-07-03 07:26 UTC, fabpot approved these changes

2017-07-03 07:26 UTC, fabpot commented
Thank you @enumag.

2017-07-03 07:27 UTC, merged