Revert the change in b4201810 with respect to Routing/Route.php
symfony/symfony pull request #23121
Opened 2017-06-09 19:17 UTC by Gribnif

...because it breaks BC. Refers to https://github.com/symfony/symfony/pull/21090 and https://github.com/symfony/symfony/issues/23109.

2017-06-10 11:48 UTC, xabbuh approved these changes

2017-06-10 15:08 UTC, fabpot requested changes
Can you add a comment explaining why we cannot restrict the allowed classes in this case? And add a test to avoid any regression in the future?

2017-06-12 18:28 UTC, Gribnif commented
As requested, I have amended the comment in the pull request and added a test. Let me know if you'd like anything else.

2017-06-12 18:54 UTC, fabpot requested changes

2017-06-12 18:54 UTC, fabpot commented on src/Symfony/Component/Routing/Tests/RouteTest.php
> +     * arbitrary classes.
Does not seem to be why we are doing it. We only want to ensure that the compiled route can be different from CompiledRoute, not that you can use any object on the route definition, which is not supported.

2017-06-13 16:26 UTC, fabpot approved these changes

2017-06-13 16:26 UTC, fabpot commented on src/Symfony/Component/Routing/Tests/Fixtures/CustomRouteCompiler.php
> +    /**
extra space

2017-06-13 16:26 UTC, fabpot commented on src/Symfony/Component/Routing/Tests/RouteTest.php
> +        } catch (\Exception $except) {
should be `$e`

2017-06-13 17:12 UTC, fabpot commented
Thank you @Gribnif.

2017-06-13 17:12 UTC, closed without merging