[FrameworkBundle] Remove depdnency on Doctrine cache
symfony/symfony pull request #23131
Opened 2017-06-11 00:57 UTC by fabpot

| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | yes
| Deprecations? | yes
| Tests pass?   | yes
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | n/a

In our quest to remove hard dependencies, I propose to remove `doctrine/cache` from the default dependencies on the Framework bundle. That's possible now as we have PSR6 cache support in Symfony and because Doctrine cache is only used for the validator mapping cache.

2017-06-11 08:53 UTC, xabbuh commented on UPGRADE-3.3.md
> +   require doctrine/cache` if you are using Doctrine cache in your project.
this should be part of the `UPGRADE-4.0.md` file

2017-06-11 11:42 UTC, xabbuh commented
I think we also need check for the existence of the Doctrine Cache package when annotation support is enabled in the config as by default we use a caching annotation reader.

2017-06-12 14:50 UTC, stof requested changes

2017-06-12 14:50 UTC, stof commented on src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php
> +                                    if ('validator.mapping.cache.apc' === $v && !class_exists('Doctrine\Common\Cache\ApcCache')) {
shouldn't this be `validator.mapping.cache.doctrine.apc` ?

2017-06-12 14:50 UTC, stof commented
@xabbuh is right about the annotation reader

2017-06-12 15:02 UTC, fabpot commented on UPGRADE-3.3.md
> +   require doctrine/cache` if you are using Doctrine cache in your project.
fixed

2017-06-12 15:02 UTC, fabpot commented on src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php
> +                                    if ('validator.mapping.cache.apc' === $v && !class_exists('Doctrine\Common\Cache\ApcCache')) {
fixed

2017-06-12 15:03 UTC, fabpot commented
check on annotations added

2017-06-12 16:04 UTC, stof requested changes

2017-06-12 16:04 UTC, stof commented on src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php
> +        if (!class_exists('Doctrine\Common\Cache\ApcCache')) {
I would check the existence of the interface rather than loading a particular implementation (which will not be the one we will use).

2017-06-12 16:04 UTC, stof commented on src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php
> +            throw new LogicException('Annotations cannot be enabled as the Doctrine Cache library is not installed.');
this exception must be inside the `if ('none' !== $config['cache']) {`. We don't need the doctrine/cache library when disabling the annotation caching.

2017-06-12 16:09 UTC, fabpot commented on src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php
> +            throw new LogicException('Annotations cannot be enabled as the Doctrine Cache library is not installed.');
fixed

2017-06-12 16:10 UTC, fabpot commented on src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php
> +        if (!class_exists('Doctrine\Common\Cache\ApcCache')) {
fixed

2017-06-12 17:53 UTC, merged