[WebServerBundle] Fix router script option BC
symfony/symfony pull request #23173
Opened 2017-06-14 11:52 UTC by 1ed

| Q             | A
| ------------- | ---
| Branch?       | 3.3
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

Server commands does not work with router script given by a relative path eg.:
```
bin/console server:run -r router.php 
```
but, this was working before and was removed (by accident I guess) in https://github.com/symfony/symfony/pull/21039/files#diff-b915f83f99a4166eb34eab581a92501bL187

2017-06-14 12:47 UTC, stof requested changes

2017-06-14 12:47 UTC, stof commented on src/Symfony/Bundle/WebServerBundle/WebServerConfig.php
> +        if (false === $this->router || !file_exists($this->router)) {
I think the file existence validation could be skipped  when using the built-in one. We already know it exists:

```php
if (null !== $router) {
    $absoluteRouterPath = realpath($router);

    if (false === $absoluteRouterPath || !file_exists($absoluteRouterPath)) {
        throw new \InvalidArgumentException(sprintf('Router script "%s" does not exists.', $router));
    }

    $this->router = $absoluteRouterPath;
} else {
    $this->router = __DIR__.'/Resources/router.php';
}

2017-06-15 11:09 UTC, nicolas-grekas commented on src/Symfony/Bundle/WebServerBundle/WebServerConfig.php
> +        if (false === $this->router || !file_exists($this->router)) {
I think that realpath returns false when the file dont not exist anyway. That'd means the file_exists check is useless, isn't it?

2017-06-16 13:26 UTC, fabpot approved these changes

2017-06-16 13:26 UTC, fabpot commented on src/Symfony/Bundle/WebServerBundle/WebServerConfig.php
> +                throw new \InvalidArgumentException(sprintf('Router script "%s" does not exists.', $router));
does not exist.

2017-06-16 13:28 UTC, 1ed commented on src/Symfony/Bundle/WebServerBundle/WebServerConfig.php
> +                throw new \InvalidArgumentException(sprintf('Router script "%s" does not exists.', $router));
Fixed

2017-06-16 13:29 UTC, 1ed commented on src/Symfony/Bundle/WebServerBundle/WebServerConfig.php
> +        if (false === $this->router || !file_exists($this->router)) {
Fixed

2017-06-16 13:30 UTC, nicolas-grekas approved these changes

2017-06-16 13:30 UTC, fabpot commented
Thank you @1ed.

2017-06-16 13:35 UTC, closed without merging