[FrameworkBundle] call setContainer() for autowired controllers
symfony/symfony pull request #23239
Opened 2017-06-20 17:05 UTC by xabbuh

| Q             | A
| ------------- | ---
| Branch?       | 3.3
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #23200
| License       | MIT
| Doc PR        | 

Previously, you either did not use controllers as services or you explicitly wired everything yourself. In case of a non-service controller the FrameworkBundle took care of calling `setContainer()` inside the `instantiateController()` method:

```php
protected function instantiateController($class)
{
    $controller = parent::instantiateController($class);

    if ($controller instanceof ContainerAwareInterface) {
        $controller->setContainer($this->container);
    }
    if ($controller instanceof AbstractController && null !== $previousContainer = $controller->setContainer($this->container)) {
        $controller->setContainer($previousContainer);
    }

    return $controller;
}
```

With the new autowired controllers as services this is no longer happening as controllers do not need to be instantiated anymore (the container already returns fully built objects).

2017-06-20 18:04 UTC, GuilhemN commented
Isn't this missing `AbstractController` support?

2017-06-20 18:35 UTC, jvasseur commented
IMO it should be the role of the DI component to call the `setContainer` method, maybe by adding this magic method call behind the `autoconfigure` option.

2017-06-20 18:36 UTC, robfrawley commented
Why doesn't `AbstractController` implement `ContainerAwareInterface`?

2017-06-20 18:56 UTC, nicolas-grekas commented
Because PSR 11 isn't compatible with it.

2017-06-20 20:25 UTC, xabbuh commented
The PR now handles the `AbstractController` class too now.

2017-06-20 21:01 UTC, ogizanagi commented
Have you already tried with the DI Extra Bundle ? 
I doubt it'll work (for those using the bundle. I don't really get other broken cases), unless I missed something, as it [replaces the controller resolver used](https://github.com/schmittjoh/JMSDiExtraBundle/blob/master/DependencyInjection/Compiler/IntegrationPass.php#L37) and the [implementation](https://github.com/schmittjoh/JMSDiExtraBundle/blob/master/HttpKernel/ControllerResolver.php) does not make use of the parent. Perhaps @bogdaniel could confirm.

2017-06-20 21:09 UTC, robfrawley commented
I did not; I had an issue unrelated to DIExtraBundle.

2017-06-21 04:47 UTC, mvrhov commented
Why do we need to inject container if the controller is autowired? If one is changing the controllers to new autowired way it should expect to remove the direct access to the container along the way.
IMO it this should be marked as deprecated since 3.4 and removed in 4.0

2017-06-21 06:18 UTC, ogizanagi commented
I agree. It also feels weird injecting it at runtime in a service. In https://github.com/symfony/symfony/issues/23200#issuecomment-309032985 I suggested another fix allowing the `setContainer` call to be properly autowired, which I guess should also work for those using the JMSDIExtraBundle. Having a controller as service with the whole container injection kind of defeat the purpose of defining it as a service. But there are still issues which needs to be fixed, as proven in the related issue.

2017-06-21 07:48 UTC, vincentpazeller commented
I think the container can still be useful in a controller even with autowiring. For instance autowiring cannot be used when the service to be called is only known at runtime (from the db for instance):

```
public function myAction(){
$dynamicServiceName = ... 
$dynamicService = $this->container->get($dynamicServiceName)
...
}
```

Of course, using the container that way is not usually a good practice, but I believe that in some situations it can help reduce code size...

2017-06-21 08:46 UTC, xabbuh commented
I just checked again and this is only an issue I was able to reproduce with routes registered by FOSRestBundle. The routes that are being registered then reference the controller with a pattern like `AppBundle\Controller\UserController:getAction` while routes registered with Symfony's annotation loader have two colons (and only in this case `instantiateController()` will be called and thus injecting the container).

2017-06-21 09:00 UTC, trappar commented
@ogizanagi I am 99% sure you're right about this not fixing the issues with the DI Extra Bundle, but that's probably something that needs to be addressed in that bundle, not here.

2017-06-21 09:03 UTC, stof commented
yeah, if JMSDIExtraBundle replaces the whole resolver without reusing the Symfony implementation through decoration or inheritance, it means they have to update their bundle each time Symfony adds a new feature. This is their issue.

2017-06-21 09:06 UTC, ogizanagi commented
But the same goes for fos rest: is it normal to use the single dot notation usually used for controller as services ?

2017-06-21 09:12 UTC, stof commented
@ogizanagi IIRC, maybe they wanted to define the route for container as a service.

2017-06-21 09:16 UTC, xabbuh commented
@ogizanagi Actually it's two colons for services and one for controller classes that must be instantiated by the controller resolver.

2017-06-21 09:19 UTC, stof commented
@xabbuh no. 2 colons is not for services. It is for normal callables (as it is the syntax used for callables in PHP)

2017-06-21 09:19 UTC, xabbuh commented
see FriendsOfSymfony/FOSRestBundle#1721 which *could* also be a fix

However, I still think that the main inconsistency is that the `ControllerResolver` from the FrameworkBundle is sometimes calling `setContainer()` even if the controller is registered as a service, but that whether or not this is done depends on the notation of the `_controller` attribute.

2017-06-21 09:20 UTC, xabbuh commented
@stof good catch, I fixed my comment accordingly

2017-06-26 18:00 UTC, GuilhemN approved these changes
I think this is the right fix. `ContainerAwareInterface` is here for something, `setContainer` must be called by the resolver when it is detected like what does the serializer when detecting `NormalizerAwareInterface` for instance.

2017-07-03 07:10 UTC, nicolas-grekas approved these changes

2017-07-03 12:14 UTC, stof requested changes

2017-07-03 12:14 UTC, stof commented on src/Symfony/Bundle/FrameworkBundle/Controller/ControllerResolver.php
> +        if (1 === substr_count($controller, ':') && is_array($resolvedController)) {
shouldn't this be done in the parent class instead, which is the one supporting container injection ?

2017-07-03 13:05 UTC, xabbuh commented on src/Symfony/Bundle/FrameworkBundle/Controller/ControllerResolver.php
> +        if (1 === substr_count($controller, ':') && is_array($resolvedController)) {
IMO that would be inconsistent as the parent class isn't doing this for instances it creates itself either.

2017-07-03 13:22 UTC, stof commented on src/Symfony/Bundle/FrameworkBundle/Controller/ControllerResolver.php
> +        if (1 === substr_count($controller, ':') && is_array($resolvedController)) {
hmm indeed. I missed the fact that injection was done in this class in a separate method

2017-07-03 13:22 UTC, stof approved these changes

2017-07-03 13:22 UTC, stof commented
hmm, actually, can we have a test covering this case to prevent regressions ?

2017-07-03 13:36 UTC, xabbuh commented
I'll check

2017-07-03 14:16 UTC, xabbuh commented
tests added

2017-07-03 14:52 UTC, nicolas-grekas commented
Thank you @xabbuh.

2017-07-03 14:52 UTC, merged

2022-01-25 08:24 UTC, draconianbg commented
Is this relevant for the new Symfony versions ? Because I use Symfony 5 and I have the same issue ..