[FrameworkBundle] Add configuration for profiler log channels
symfony/symfony pull request #23247
Opened 2017-06-21 09:43 UTC by maff

[FrameworkBundle] Add configuration for profiler log channels

| Q             | A
| ------------- | ---
| Branch?       | 3.4 or master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets |
| License       | MIT
| Doc PR        | 

In larger projects, the amount of logs stored in the profiler can grow quickly and the web profiler takes quite some time to render the logs screen when having hundreds of event and db log entries. This PR adds a configuration entry to exclude/include certain log channels from the profiler. The format follows the `channels` configuration entry from the monolog bundle:

```
framework:
    profiler:
        log_channels: ["!event", "!doctrine"]

# more verbose
framework:
    profiler:
        log_channels:
            channels: ["!event", "!doctrine"]

# or profile only certain channels
framework:
    profiler:
        log_channels:
            channels: ["event", "doctrine"]
```

I'll be happy to add a doc PR if this is accepted.

2017-08-16 16:31 UTC, nicolas-grekas commented
Adding configuration is always adding complexity for the end user. If we can do otherwise (including doing nothing), i think that might be better. I all depends on the current "brokenness" status.

2017-08-17 07:19 UTC, stloyd requested changes

2017-08-17 07:19 UTC, stloyd commented on src/Symfony/Bridge/Monolog/Processor/DebugProcessor.php
> +        if ($this->channelsExclusive && !in_array($record['channel'], $this->channels)) {
```php
         if ($this->channelsExclusive && !in_array($record['channel'], $this->channels, true)) {
             return false;
         }
 
         return in_array($record['channel'], $this->channels, true);
     }

2017-08-17 07:19 UTC, stloyd commented on src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php
> +                                    if (!count($channels)) {
```php
if (!$channels) {
}

2017-08-23 12:29 UTC, fabpot commented
I agree with @nicolas-grekas. What about truncating the logs when there are too important instead?

2017-10-08 16:24 UTC, nicolas-grekas commented
Moving to 4.1. Rebase on master might be needed, where PHP 7.1 features can be used btw.

2017-10-09 07:24 UTC, maff commented
Sorry, I missed this conversation somehow. Regarding "brokenness": it really depends on the project, but we've seen issues with large profiler data and profiler not being able to load when lots of events and/or doctrine queries are logged during a request. At that time the profiler still popped up the alert window which really made it a problem, now with the toolbar just showing an error it's way better.
For me it's also fine to not include this change as long as I can override this on a project level when really needed (e.g. by decorating the DebugProcessor).

Regarding truncating: could work as well, but I don't really have an idea how to decide what and when to truncate.

2019-04-07 07:54 UTC, stof commented
Decorating the `debug.log_processor` service is already possible if the project actually needs to filter logs to avoid storing them in the profiler:

```php
class FilteredDebugProcessor implements DebugLoggerInterface
{
    private $innerProcessor;

    public function __construct(DebugLogProcessor $processor)
    {
        $this->innerProcessor = $processor;
    }


    public function __invoke(array $record)
    {
        if (/* condition to exclude*/) {
            return $record;
        }

        return $this->innerProcessor->__invoke($record);
    }

    /**
     * {@inheritdoc}
     */
    public function getLogs(Request $request = null)
    {
        return $this->innerProcessor->getLogs($request);
    }

    /**
     * {@inheritdoc}
     */
    public function countErrors(Request $request = null)
    {
        return $this->innerProcessor->countErrors($request);
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->innerProcessor->clear();
    }
}
```

```yaml
services:
    filtered_debug_processor:
        class: FilteredDebugProcessor
        arguments: filtered_debug_processor.inner
        decorates: debug.log_processor
```

2019-04-07 07:55 UTC, stof commented
I'm closing this PR, as I don't think that this additional complexity is needed in the core (and @fabpot and @nicolas-grekas already said the same a long time ago).

2019-04-07 07:55 UTC, closed without merging