[Security] Lazy load user providers
symfony/symfony pull request #23295
Opened 2017-06-25 11:57 UTC by chalasr

| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | n/a

2017-06-25 12:45 UTC, chalasr commented
build failure with high deps is normal

2017-06-25 15:50 UTC, ogizanagi approved these changes

2017-06-25 20:25 UTC, dunglas approved these changes

2017-07-03 09:12 UTC, nicolas-grekas commented on src/Symfony/Component/Security/Core/User/ChainUserProvider.php
> +    public function __construct(/* iterable */ $providers)
the comment should be removed

2017-07-03 09:13 UTC, nicolas-grekas commented on src/Symfony/Component/Security/Http/Firewall/ContextListener.php
> +    public function __construct(TokenStorageInterface $tokenStorage, /* iterable */ $userProviders, $contextKey, LoggerInterface $logger = null, EventDispatcherInterface $dispatcher = null, Authentic
comment to be removed, that's the job of a docblock, we should not follow this practice IMHO

2017-07-03 09:13 UTC, nicolas-grekas approved these changes
with minor comments

2017-07-03 13:22 UTC, chalasr commented
@nicolas-grekas comments addressed. build failure unrelated (see #23360)

2017-07-03 13:30 UTC, stof requested changes

2017-07-03 13:30 UTC, stof commented on src/Symfony/Component/Security/Http/Tests/Firewall/ContextListenerTest.php
> -     * @expectedExceptionMessage User provider "stdClass" must implement "Symfony\Component\Security\Core\User\UserProviderInterface
we should still have a test covering this case. You have not removed the exception entirely. You just moved it later in the usage.

2017-07-03 13:40 UTC, chalasr commented on src/Symfony/Component/Security/Http/Tests/Firewall/ContextListenerTest.php
> -     * @expectedExceptionMessage User provider "stdClass" must implement "Symfony\Component\Security\Core\User\UserProviderInterface
test readded

2017-07-05 07:40 UTC, chalasr commented
ready.

2017-07-05 14:08 UTC, fabpot approved these changes

2017-07-09 11:04 UTC, chalasr commented on src/Symfony/Component/Security/Http/Firewall/ContextListener.php
> +    public function __construct(TokenStorageInterface $tokenStorage, $userProviders, $contextKey, LoggerInterface $logger = null, EventDispatcherInterface $dispatcher = null, AuthenticationTrustResol
full docblock to be removed + `iterable` typehint to be added to the `$userProviders` arg when merging into master.

2017-07-09 11:04 UTC, chalasr commented on src/Symfony/Component/Security/Core/User/ChainUserProvider.php
> +    public function __construct($providers)
same, docblock to typehint when merging into master

2017-07-11 13:48 UTC, nicolas-grekas commented
Thank you @chalasr.

2017-07-11 13:48 UTC, merged