[Workflow] Added more events to the announce function
symfony/symfony pull request #23299
Opened 2017-06-25 18:10 UTC by Nyholm

| Q             | A
| ------------- | ---
| Branch?       | 3.2
| Bug fix?      | yes/no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #23275
| License       | MIT
| Doc PR        | n/a

This PR will fix #23275

I documentation states that we dispatch events `workflow.announce` and `workflow.[name].announce`. It was me who wrongly added it to the docs... sorry about that. 

We could either: Change the docs or add these events. I choose to add these event to the source since the same events are dispatched for "guard", "leave", "transition", "enter" and "entered".

2017-06-25 20:05 UTC, lyrixx approved these changes

2017-06-25 22:50 UTC, ostrolucky requested changes
Even if you chose the code change, remember that docs need to be updated, because they currently state "announce: Triggered once for each workflow that now is available for the object."

2017-06-26 03:43 UTC, xabbuh approved these changes

2017-06-26 07:38 UTC, Nyholm commented
Thank you @ostrolucky for your review. I will send a PR to the docs. 

Also, we need to make sure we do not "announce" before the guard events. The guard events may block the transition.

2017-06-26 08:13 UTC, Nyholm commented
Sorry, I was wrong in my last comment and commit. I reverted it, the PR is now unchanged since you reviewed it. 

I made a small PR to the docs to address the issue @ostrolucky highlighted.

2017-06-26 12:40 UTC, lyrixx commented
Thanks for fixing this bug @Nyholm.

2017-06-26 12:41 UTC, lyrixx commented
I merged this PR in the 3.2 branch instead of master.

2017-06-26 12:42 UTC, closed without merging

2017-06-26 13:06 UTC, Nyholm commented
Thank you for merging.