[Component][Serializer][Normalizer] : Deal it with Has Method for the Normalizer/Denormalizer
symfony/symfony pull request #23337
Opened 2017-06-30 14:38 UTC by jordscream

| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | ?
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #23314 
| License       | MIT
| Doc PR        | symfony/symfony-docs

Deal it with Has Method for the Normalizer/Denormalizer

2017-06-30 14:43 UTC, jordscream commented
@Aliance , I stole this mini practice to exercise my Symfony PR ;-) (I'm a newbie)
I will be very interresting if you can comment this PR
Note: For unit test, I did not want to change the existing unit test to add has test method. I prefered to create new unit test with new class

2017-07-03 21:42 UTC, dunglas requested changes
Thanks for this fix! I left some minor comments.

2017-07-03 21:42 UTC, dunglas commented on src/Symfony/Component/Serializer/Tests/Normalizer/GetSetMethodNormalizerTest.php
> +        $obj = $this->normalizer->denormalize(array('foo' => true), __NAMESPACE__.'\ObjectWithHasGetterDummy');
You can use `ObjectWithHasGetterDummy::class`

2017-07-03 21:42 UTC, dunglas commented on src/Symfony/Component/Serializer/Tests/Normalizer/GetSetMethodNormalizerTest.php
> +        $this->assertEquals(true, $obj->hasFoo());
`$this->assertTrue($obj->hasFoo())`

2017-07-03 21:42 UTC, dunglas commented on src/Symfony/Component/Serializer/Tests/Normalizer/GetSetMethodNormalizerTest.php
> +    private $foo = null;
`= null` is useless, it's the default value.

2017-07-05 19:49 UTC, jordscream commented
@dunglas , you can check :-)

2017-07-05 19:53 UTC, Aliance approved these changes
Rebase should be done right before merging, not while code review. Otherwise reviewers can not see only made changes.

2017-07-05 20:28 UTC, dunglas approved these changes

2017-07-06 05:54 UTC, fabpot approved these changes

2017-07-06 06:04 UTC, fabpot commented
Thank you @jordscream.

2017-07-06 06:04 UTC, merged