[VarDumper] Add interval caster
symfony/symfony pull request #23357
Opened 2017-07-03 11:32 UTC by maidmaid

| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | /
| License       | MIT
| Doc PR        | /

 cf https://github.com/symfony/symfony/pull/22431#issuecomment-312567747

2017-07-03 11:32 UTC, maidmaid commented
First proposal:

- the main public properties (``y``, ``m``, ``d``, ``h``, ``i``, ``s``, and ``f`` on PHP 7.1) are merged in oneline ``interval`` virtual property;
- the others public properties (``invert`` and ``days``) are unmodified;
- and the public properties not officially documentated (``weekday``, ``weekday_behavior``, ``first_last_day_of``, ``special_type``, ``special_amount``, ``have_weekday_relative``, ``have_special_relative``) are removed (see http://php.net/manual/en/class.dateinterval.php#dateinterval.synopsis).

| Before        | After           |
| ------------- | ------------- |
| ![](https://user-images.githubusercontent.com/4578773/27791061-8e85424a-5ff3-11e7-8c1d-525a30c3defd.png) | ![](https://user-images.githubusercontent.com/4578773/27791062-8e85538e-5ff3-11e7-8eb1-bd7c8b5681f2.png) |

2017-07-03 12:05 UTC, stof requested changes

2017-07-03 12:05 UTC, stof commented on src/Symfony/Component/VarDumper/Caster/DateCaster.php
> +        $prefix = Caster::PREFIX_VIRTUAL;
no need to define a variable, as it is used only once

2017-07-03 12:05 UTC, stof commented on src/Symfony/Component/VarDumper/Caster/DateCaster.php
> +        if (PHP_VERSION_ID >= 70100) {
please use `\PHP_VERSION_ID`, to let the version comparison be applied at compile time (not qualifying the constant requires doing it at runtime to check the constant first in the current namespace)

2017-07-03 12:05 UTC, stof commented on src/Symfony/Component/VarDumper/Tests/Caster/DateCasterTest.php
> +        $ms = function () { return PHP_VERSION_ID >= 70100 ? '.000000' : ''; };
no need to use a function. Use a simple variable, as this is purely static.

2017-07-03 12:18 UTC, maidmaid commented on src/Symfony/Component/VarDumper/Caster/DateCaster.php
> +        $prefix = Caster::PREFIX_VIRTUAL;
Fixed

2017-07-03 12:19 UTC, maidmaid commented on src/Symfony/Component/VarDumper/Caster/DateCaster.php
> +        if (PHP_VERSION_ID >= 70100) {
``\`` added

2017-07-03 12:19 UTC, maidmaid commented on src/Symfony/Component/VarDumper/Tests/Caster/DateCasterTest.php
> +        $ms = function () { return PHP_VERSION_ID >= 70100 ? '.000000' : ''; };
Updated

2017-07-04 18:44 UTC, ogizanagi commented
I agree with @nicolas-grekas's original comment (https://github.com/symfony/symfony/pull/22431#issuecomment-312567747), so I'm not convinced by the new suggested output. 
Perhaps we could just exclude non-officially documented public properties and add your `interval` virtual property. Then, potentially exclude public properties merged in the `interval` virtual properties when used with the `EXCLUDE_VERBOSE` filter, so it won't be shown within the form and validator data collectors for instance, but still shown when dumping around elsewhere.

Also, why showing the `invert` field when it's already part of the `interval`? According to the above suggestions, I'll hide it too when using `EXCLUDE_VERBOSE`.

Would it be interesting to also output it as the [time_interval spec](http://php.net/manual/en/dateinterval.construct.php)?
https://github.com/jaroslavtyc/granam-date-interval/blob/master/Granam/DateInterval/DateInterval.php#L175-L200

WDYT?

2017-07-04 20:00 UTC, maidmaid commented
Thank you for your thoughts @ogizanagi. I would say this:

- Why do not you like removing time properties? This deletion is in favor of ``interval`` that is a full representation of this props.
- About ``invert`` prop, you are right. 
- About ``time_interval`` spec, I think that ``interval`` virtual prop is a good replacement and more intuitive to read (``P1Y2M3DT4H5M6S`` vs ``+ 1y 2m 3d 04:05:06``). Moreover, it does not handle milliseconds and the negative intervals.

2017-07-04 20:14 UTC, ogizanagi commented
> Why do not you like removing time properties? This deletion is in favor of interval that is a full representation of this props.

Just quoting @nicolas-grekas:

> Dump should be informational about how things actually works or can be used. On a DateInterval, the listed values are actual public properties. VarDumper is about showing actual facts about objects, not alternate ones

I'm using [psysh](http://psysh.org/) quite often, to quickly test or demonstrate things, and despite built-in introspection/doc commands like `ls -al`, `show`, ... I like the usage of the var-dumper component to output everything and the fact it shows real internals, not representations. I wish it stay this way, but I'm not against adding some helpful representation in addition.

2017-07-11 06:29 UTC, nicolas-grekas commented
Same opinion as @ogizanagi.
Maybe display the short output when the EXCLUDE_VERBOSE flag is set (the default on psysh)?

2017-07-11 10:24 UTC, maidmaid commented
Ok, here the new result according to your comments:
 
| normal        | ``EXCLUDE_VERBOSE``           |
| ------------- | ------------- |
| ![](https://user-images.githubusercontent.com/4578773/28063954-333052ea-6633-11e7-903e-fcfe19897798.png) | ![](https://user-images.githubusercontent.com/4578773/28063953-332d4488-6633-11e7-91ea-7d1a6cdf18e3.png) |

2017-07-11 13:39 UTC, nicolas-grekas commented
"normal" should display all existing properties, even undocumented ones. Also, why keep "days" in compact mode?

2017-07-11 17:08 UTC, maidmaid commented
It's updated: "normal" displays all, and only ``interval`` prop is keeped in compact mode.

2017-07-11 20:58 UTC, nicolas-grekas approved these changes
with some suggestions

2017-07-11 20:58 UTC, nicolas-grekas commented on src/Symfony/Component/VarDumper/Tests/Caster/DateCasterTest.php
> +    public function testCastInterval($interval_spec, $invert, $expected)
should be `$intervalSpec`

2017-07-11 20:58 UTC, nicolas-grekas commented on src/Symfony/Component/VarDumper/Caster/DateCaster.php
> +        $i = array(Caster::PREFIX_VIRTUAL.'interval' => self::formatInterval($interval));
what about using a ConstStub here that gives the number of seconds on hover (html mode):
`new ConstStub(self::formatInterval($interval), $numberOfSeconds);`

2017-07-12 09:37 UTC, maidmaid commented on src/Symfony/Component/VarDumper/Tests/Caster/DateCasterTest.php
> +    public function testCastInterval($interval_spec, $invert, $expected)
Fixed (in [official doc](http://php.net/manual/fr/dateinterval.construct.php), this argument is named ``$interval_spec``).

2017-07-12 09:38 UTC, maidmaid commented on src/Symfony/Component/VarDumper/Caster/DateCaster.php
> +        $i = array(Caster::PREFIX_VIRTUAL.'interval' => self::formatInterval($interval));
Good idea. Number of seconds added.

2017-07-12 10:19 UTC, maidmaid commented
How to fix kind of HHVM failure?
```
1) Symfony\Component\VarDumper\Tests\Caster\DateCasterTest::testDumpInterval with data set #0 ('PT0S', 0, '0s', '0s')
Failed asserting that format description matches text.
--- Expected
+++ Actual
@@ @@
 DateInterval {
   interval: 0s
 }
-}
```

2017-07-12 11:17 UTC, nicolas-grekas commented
```diff
diff --git a/src/Symfony/Component/VarDumper/Caster/DateCaster.php b/src/Symfony/Component/VarDumper/Caster/DateCaster.php
index c9edc10..1ecd962 100644
--- a/src/Symfony/Component/VarDumper/Caster/DateCaster.php
+++ b/src/Symfony/Component/VarDumper/Caster/DateCaster.php
@@ -58,7 +58,7 @@ class DateCaster
             .($i->d ? '%dd ' : '')
         ;
 
-        if (\PHP_VERSION_ID >= 70100) {
+        if (isset($i->f)) {
             $format .= $i->h || $i->i || $i->s || $i->f ? '%H:%I:%S.%F' : '';
         } else {
             $format .= $i->h || $i->i || $i->s ? '%H:%I:%S' : '';
diff --git a/src/Symfony/Component/VarDumper/Tests/Caster/DateCasterTest.php b/src/Symfony/Component/VarDumper/Tests/Caster/DateCasterTest.php
index 9db333e..c4c1263 100644
--- a/src/Symfony/Component/VarDumper/Tests/Caster/DateCasterTest.php
+++ b/src/Symfony/Component/VarDumper/Tests/Caster/DateCasterTest.php
@@ -97,8 +97,7 @@ EODUMP;
         $xDump = <<<EODUMP
 DateInterval {
   interval: $expected
-%a
-}
+%A}
 EODUMP;
 
         $this->assertDumpMatchesFormat($xDump, $interval);
@@ -162,7 +161,8 @@ EODUMP;
 
     public function provideIntervals()
     {
-        $ms = \PHP_VERSION_ID >= 70100 ? '.000000' : '';
+        $interval = new \DateInterval('PT0S');
+        $ms = isset($interval->f);
 
         return array(
             array('PT0S', 0, '0s', '0s'),
```

2017-07-12 12:50 UTC, maidmaid commented
Mmh, ``isset($interval->f)`` triggers a notice in 7.0, see https://3v4l.org/hJB5A. I use ``PHP_VERSION_ID``?

2017-07-12 12:53 UTC, nicolas-grekas commented
but my HHVM fails when PHP_VERSION_ID is used...

2017-07-12 12:53 UTC, nicolas-grekas commented
you should report the notice as a bug I guess

2017-07-12 12:55 UTC, nicolas-grekas commented
using both PHP_VERSION_ID and the isset check should do it

2017-07-12 13:59 UTC, maidmaid commented
There was no error related with ``PHP_VERSION_ID`` [previously](https://github.com/symfony/symfony/pull/23357#issuecomment-314719651). Tests seems fine now (failure seems unrelated).

2017-07-12 14:03 UTC, maidmaid commented
> you should report the notice as a bug

https://bugs.php.net/bug.php?id=74911 ;)

2017-07-12 14:16 UTC, nicolas-grekas commented
> was no error related with PHP_VERSION_ID previously

that's because the behavior of hhvm changes fro mversion to version and Travis doesn't have the latest. But trust me, this check is not enough, you need the isset one also :)

2017-07-12 14:16 UTC, nicolas-grekas commented
(or install hhvm to see by yourself ;) )

2017-07-12 18:03 UTC, maidmaid commented
Updated: used ``PHP_VERSION_ID`` and the isset check.

2017-07-18 09:08 UTC, maidmaid commented
Time to merge? :)

2017-07-19 05:50 UTC, nicolas-grekas commented
Thank you @maidmaid.

2017-07-19 05:50 UTC, merged