[Process] Remove enhanced sigchild compatibility
symfony/symfony pull request #23380
Opened 2017-07-04 11:13 UTC by maidmaid

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | yes
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | https://github.com/symfony/symfony/pull/23376#issuecomment-312842538
| License       | MIT
| Doc PR        | /

In 4.0, enhanced sigchild compatibility is always enabled.

2017-07-04 11:27 UTC, xabbuh requested changes
tests are failing

2017-07-04 13:57 UTC, maidmaid commented
Could you help me to fix tests?

2017-07-04 14:08 UTC, xabbuh commented
I am afraid I will not be of much help here (I tried to do that before in #22836 but then excluded this part as I didn't manage to make the tests pass)

2017-07-04 14:21 UTC, maidmaid commented
Ok, I see your previous comment here https://github.com/symfony/symfony/pull/22836#issuecomment-310990838. I'll try more...

2017-07-11 09:50 UTC, nicolas-grekas commented on src/Symfony/Component/Process/Process.php
> +        if ($this->isSigchildEnabled()) {
this if block should be removed (and the annotation above)

2017-07-11 09:50 UTC, nicolas-grekas commented on src/Symfony/Component/Process/Process.php
> +        if ($this->isSigchildEnabled()) {
to be remove, also the related line in the docblock

2017-07-11 09:50 UTC, nicolas-grekas commented on src/Symfony/Component/Process/Process.php
> +        if ($this->isSigchildEnabled()) {
to be removed

2017-07-11 10:12 UTC, stof requested changes

2017-07-11 10:12 UTC, stof commented on src/Symfony/Component/Process/Tests/ProcessTest.php
> +            if (method_exists($this, 'expectException')) {
this is wrong. All the logic setting an expected exception was triggered only inside a `self::$notEnhancedSigchild`. And now, sigchild compat is *always* enhanced. So this if must become a `if (false)`, not a `if (true)`

2017-07-11 10:14 UTC, stof commented
Tests are failing because half of the places removing the usage of the field in conditionals performed the wrong replacement, making the code equivalent to *disabling* enhanced compat all the time instead of enabling it all the time.

2017-07-11 10:15 UTC, nicolas-grekas commented
@maidmaid could you please also remove all the other deprecated features of this class in this PR?

2017-07-11 10:16 UTC, nicolas-grekas commented
never mind, I was on the wrong branch...

2017-07-11 11:11 UTC, maidmaid commented on src/Symfony/Component/Process/Tests/ProcessTest.php
> +            if (method_exists($this, 'expectException')) {
Ok but... I'm not sure I'll be able to fix this alone... Could you show me what I need to do more exactly please?

2017-07-11 11:11 UTC, maidmaid commented on src/Symfony/Component/Process/Process.php
> +        if ($this->isSigchildEnabled()) {
Removed.

2017-07-11 11:11 UTC, maidmaid commented on src/Symfony/Component/Process/Process.php
> +        if ($this->isSigchildEnabled()) {
Removed.

2017-07-11 11:11 UTC, maidmaid commented on src/Symfony/Component/Process/Process.php
> +        if ($this->isSigchildEnabled()) {
Removed.

2017-07-12 11:40 UTC, nicolas-grekas commented on src/Symfony/Component/Process/Tests/ProcessTest.php
> +        $this->skipIfSigchildEnabled();
all these should be just removed

2017-07-12 11:40 UTC, nicolas-grekas commented on src/Symfony/Component/Process/Tests/ProcessTest.php
> +    private function skipIfSigchildEnabled($expectException = true)
this method should be removed

2017-07-12 11:44 UTC, nicolas-grekas commented on src/Symfony/Component/Process/Process.php
>       * @throws LogicException   In case the process is not terminated
cs fix required, see fabbot

2017-07-12 13:02 UTC, maidmaid commented
Green tests!

2017-07-12 13:12 UTC, nicolas-grekas commented
Thank you @maidmaid.

2017-07-12 13:13 UTC, merged