[Validator] Remove support of boolean value for the checkDNS option
symfony/symfony pull request #23391
Opened 2017-07-04 15:01 UTC by maidmaid

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | yes
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | /
| License       | MIT
| Doc PR        | /

Initial PR https://github.com/symfony/symfony/pull/23076

2017-07-04 16:42 UTC, xabbuh requested changes
please update the changelog too

2017-07-04 17:23 UTC, maidmaid commented
Updated.

2017-07-04 19:07 UTC, xabbuh commented on src/Symfony/Component/Validator/CHANGELOG.md
> + * setting the `checkDNS` option of the `Url` constraint to `true` is deprecated in favor of `Url::CHECK_DNS_TYPE_*` constants values and will throw an exception in Symfony 4.0
this should be done in the `3.4` branch

2017-07-04 19:10 UTC, xabbuh commented on src/Symfony/Component/Validator/CHANGELOG.md
> + * removed the support for setting the `checkDNS` option of the `Url` constraint to `true`
removed support [...]

2017-07-04 19:11 UTC, xabbuh commented on UPGRADE-4.0.md
> + * Setting the `checkDNS` option of the `Url` constraint to `true` is deprecated
support ist dropped in 4.0, not deprecated

2017-07-04 19:18 UTC, maidmaid commented on src/Symfony/Component/Validator/CHANGELOG.md
> + * setting the `checkDNS` option of the `Url` constraint to `true` is deprecated in favor of `Url::CHECK_DNS_TYPE_*` constants values and will throw an exception in Symfony 4.0
Removed. Is this change worth opening a new PR?

2017-07-04 19:18 UTC, maidmaid commented on src/Symfony/Component/Validator/CHANGELOG.md
> + * removed the support for setting the `checkDNS` option of the `Url` constraint to `true`
Updated

2017-07-04 19:19 UTC, maidmaid commented on UPGRADE-4.0.md
> + * Setting the `checkDNS` option of the `Url` constraint to `true` is deprecated
Oops, it's updated now.

2017-07-04 19:33 UTC, xabbuh commented on src/Symfony/Component/Validator/CHANGELOG.md
> + * setting the `checkDNS` option of the `Url` constraint to `true` is deprecated in favor of `Url::CHECK_DNS_TYPE_*` constants values and will throw an exception in Symfony 4.0
see ac107ba6b253af9d217cf511ceb10f1d47d91ed8

2017-07-04 19:35 UTC, xabbuh approved these changes

2017-07-05 06:40 UTC, fabpot approved these changes

2017-07-05 06:42 UTC, fabpot commented
Thank you @maidmaid.

2017-07-05 06:42 UTC, merged

2017-07-05 06:51 UTC, javiereguiluz commented
I don't like this change being merged. I'd prefer to keep the current behavior (when using `true`, you mean `ANY`) because that's the common case. In fact, the example you showed with the before/after differences is nice ... but that's PHP. However, most people define these constraints with annotations or YAML files. It won't be that easy for them :(

```php
/** @Assert\Url(checkDNS = true) */
protected $bioUrl;
```

```yaml
AppBundle\Entity\Author:
    properties:
        bioUrl:
            # before
            - Url: { checkDNS: true }

            # after ("the right way")
            - Url: { checkDNS: !php/const:Symfony\Component\Validator\Constraints\Url::CHECK_DNS_TYPE_ANY }

            # after (with "magic" strings)
            - Url: { checkDNS: 'ANY' }
```

By the way, `checkDNS: 'ANY'`, may look like, "anything" will work for me, I don't care about this value.

2017-07-05 06:58 UTC, fabpot commented
I tend to agree with Javier but would go even one step further and remove this option altogether. It's not really that useful IMHO to check DNS.

2017-07-05 08:43 UTC, maidmaid commented
@javiereguiluz Only `Url::CHECK_DNS_TYPE_*` constants values are accepted. ``checkDNS: 'ANYTHING'`` [throws an exception]( https://github.com/symfony/symfony/pull/23076/files#diff-c152f2b5c9ff3db02b5270f3e6be2995R96). Thus, ``checkDNS: 'ANY'`` is maybe to recommend in annotations/YAML case.