Don't display the Symfony debug toolbar when printing the page
symfony/symfony pull request #23460
Opened 2017-07-09 17:52 UTC by javiereguiluz

| Q             | A
| ------------- | ---
| Branch?       | 2.8
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #23303
| License       | MIT
| Doc PR        | -

2017-07-10 00:16 UTC, ostrolucky commented on src/Symfony/Bundle/WebProfilerBundle/Resources/views/Profiler/toolbar.css.twig
> +        visibility: hidden;
what's the reason for this if there is already `display: none`?

2017-07-10 07:23 UTC, javiereguiluz commented on src/Symfony/Bundle/WebProfilerBundle/Resources/views/Profiler/toolbar.css.twig
> +        visibility: hidden;
It was in the original CSS rule ... but you are right and this is no longer needed (Bootstrap v4 doesn't use that either. See https://github.com/twbs/bootstrap/blob/v4-dev/scss/_print.scss)

2017-07-10 09:12 UTC, xabbuh approved these changes

2017-07-10 09:36 UTC, stof commented
Actually, the issue is that the media query hiding the whole toolbar (error one or normal one) is missing now.
the 2.7 branch has this code before the error toolbar:

```css
/***** Media query print: Do not print the Toolbar. *****/
@media print {
    .sf-toolbar {
        display: none;
        visibility: hidden;
    }
}
```

But the 2.8 branch does not seem to have it anymore.

I suspect a bad conflict resolution when merging branches

2017-07-10 09:38 UTC, stof requested changes

2017-07-10 09:38 UTC, stof commented on src/Symfony/Bundle/WebProfilerBundle/Resources/views/Profiler/toolbar.css.twig
> +    .sf-toolbar, .sf-error-toolbar {
`.sf-error-toolbar` is useless here, as the error toolbar also has the `sf-toolbar` class

2017-07-11 06:55 UTC, nicolas-grekas commented
Thank you @javiereguiluz.

2017-07-11 07:23 UTC, closed without merging