[Config] extracted the xml parsing from XmlUtils::loadFile into XmlUtils::parse
symfony/symfony pull request #23485
Opened 2017-07-12 13:13 UTC by Basster

| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| License       | MIT

I needed the xml parsing for an XML string generated in memory, so I extracted the actual parsing from XmlUtils::loadFile into XmlUtils::load.

Re-opened after I messed some things up in #23482

2017-07-12 13:49 UTC, iltar commented on CONTRIBUTORS.md
> + - Ole Rößner (basster)
As far as I know, this file is auto-generated, so doesn't need to be manually modified

2017-07-13 13:40 UTC, nicolas-grekas commented on src/Symfony/Component/Config/Util/XmlUtils.php
> +        } catch (\InvalidArgumentException $ex) {
the convention is to name this var `$e`

2017-07-13 13:40 UTC, nicolas-grekas commented on src/Symfony/Component/Config/Util/XmlUtils.php
> +            throw new \InvalidArgumentException(
I propose this:
```php
if ('The XML is not valid.' !== $ex->getMessage()) {
    throw $e;
}
throw new \InvalidArgumentException(sprintf('The XML file "%s" is not valid.', $file), 0, $e->getPrevious());
```

2017-07-13 14:42 UTC, nicolas-grekas approved these changes

2017-07-16 20:58 UTC, Basster commented
@nicolas-grekas Is there any way, besides pushing changes, to retrigger the builds? I don't see how the failing test is related to my changes.

2017-07-17 10:44 UTC, fabpot requested changes

2017-07-17 10:44 UTC, fabpot commented on src/Symfony/Component/Config/Util/XmlUtils.php
> +            if ('The XML is not valid.' !== $e->getMessage()) {
Logic sounds very fragile to me. Can we instead add a code to the exception and check the code here?

2017-07-17 12:29 UTC, Basster commented on src/Symfony/Component/Config/Util/XmlUtils.php
> +            if ('The XML is not valid.' !== $e->getMessage()) {
sure, sounds comprehensible.

2017-07-17 12:48 UTC, fabpot commented on src/Symfony/Component/Config/Util/XmlUtils.php
> +            if ('The XML is not valid.' !== $e->getMessage()) {
No guidelines. I think we don't have any other examples in the framework. Another option would be to create a dedicated exception class.

2017-07-17 13:15 UTC, Basster commented on src/Symfony/Component/Config/Util/XmlUtils.php
> +            if ('The XML is not valid.' !== $e->getMessage()) {
Sounds even cleaner to me.

2017-07-17 15:17 UTC, nicolas-grekas commented on src/Symfony/Component/Config/Util/XmlUtils.php
> +            if ('The XML is not valid.' !== $e->getMessage()) {
a dedicated exception class would have my preference

2017-08-24 15:32 UTC, Basster commented
friendly ping

2017-08-24 15:55 UTC, nicolas-grekas commented
@Basster can you rebase (and squash meanwhile if you want) please so that the merge commit disappears?

2017-08-24 16:09 UTC, Basster commented
> Moderators earlier asked you to "squash" your commits. This means you will convert many commits to one commit. This is no longer necessary today, because Symfony project uses a proprietary tool which automatically squashes all commits before merging.

From https://symfony.com/doc/current/contributing/code/patches.html, should I do so, anyways?

2017-09-04 21:18 UTC, chalasr commented
Not if you don't want :)

> (and squash meanwhile if you want)

But rebasing is needed as there is a conflict.

2017-09-26 14:50 UTC, nicolas-grekas commented
@Basster would you have some time to rebase before the end of the week?

2017-09-26 16:09 UTC, Basster commented
@nicolas-grekas *done* (hopefully correct)

2017-09-26 16:30 UTC, nicolas-grekas commented
ping @symfony/deciders

2017-09-26 16:31 UTC, ogizanagi approved these changes

2017-09-26 19:46 UTC, xabbuh approved these changes

2017-09-26 19:49 UTC, ogizanagi commented
Thank you @Basster.

2017-09-26 19:50 UTC, closed without merging