[FrameworkBundle] Fix default public directory on install assets
symfony/symfony pull request #23513
Opened 2017-07-14 22:46 UTC by yceruto

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

After https://github.com/symfony/flex/pull/122 and https://github.com/symfony/recipes/pull/106 I guess the default directory to install assets is `public` now.

2017-07-15 06:27 UTC, xabbuh commented
This will break applications that are using the old directory structure and just update their dependencies using `composer update`.

2017-07-15 11:55 UTC, yceruto commented
@xabbuh right, but this is about default value for default directory structure 4.0, still you can use the `target` argument for old structures, no? or this kind of BC break is not allowed?

2017-07-15 12:56 UTC, yceruto commented
Upgrade note added, but still I'm not sure if we should add a warning messages on 3.4 on `assets:install`, WDYT?

2017-07-15 19:16 UTC, ro0NL commented
4.0 can provide the target path as well ;-) it's not like we _must_ update on this side.

It does makes sense though :) however you need to trigger a deprecation in 3.4 first (if the argument is not given) i guess.

2017-07-16 13:11 UTC, fabpot commented
What about doing something similar to what I did in #23535?

2017-07-16 14:32 UTC, yceruto commented
@fabpot I've rebased to `3.3` base branch as a bugfix, also added BC for web directory :)

2017-07-17 10:37 UTC, fabpot requested changes

2017-07-17 10:37 UTC, fabpot commented on UPGRADE-4.0.md
> + * The `assets:install` command does not install assets into `web` directory by default, but into `public` directory.
That's not true anymore. It will install under `public` or `web`.

2017-07-17 11:48 UTC, fabpot commented
Thank you @yceruto.

2017-07-17 11:50 UTC, closed without merging