Disable inlining deprecated services
symfony/symfony pull request #23540
Opened 2017-07-16 19:59 UTC by alekitto

| Q             | A
| ------------- | ---
| Branch?       | 2.8
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #23536
| License       | MIT

Deprecation errors are not triggered for inlined services.
Disabling inlining for those services will fix this issue.

2017-07-16 20:37 UTC, ro0NL approved these changes

2017-07-16 20:37 UTC, ro0NL commented on src/Symfony/Component/DependencyInjection/Compiler/InlineServiceDefinitionsPass.php
>          if ($definition->isPublic() || $definition->isLazy()) {
Why not add `|| isDeprecated()` here?

2017-07-16 20:40 UTC, alekitto commented on src/Symfony/Component/DependencyInjection/Compiler/InlineServiceDefinitionsPass.php
>          if ($definition->isPublic() || $definition->isLazy()) {
Right. Fixed.

2017-07-17 07:32 UTC, nicolas-grekas approved these changes

2017-07-17 07:38 UTC, fabpot requested changes

2017-07-17 07:38 UTC, fabpot commented on src/Symfony/Component/DependencyInjection/Tests/ContainerBuilderTest.php
> +     * @group legacy
As this test and the other one should not be removed in 4.0, I suggest to add a comment to make it clear.

2017-07-17 09:11 UTC, Taluu approved these changes

2017-07-17 09:59 UTC, alekitto commented on src/Symfony/Component/DependencyInjection/Tests/ContainerBuilderTest.php
> +     * @group legacy
Added.

2017-07-17 10:14 UTC, fabpot commented
Thank you @alekitto.

2017-07-17 10:15 UTC, merged