[PropertyInfo] Use rawurlencode to escape PSR-6 keys
symfony/symfony pull request #23595
Opened 2017-07-19 19:38 UTC by dunglas

| Q             | A
| ------------- | ---
| Branch?       | 3.2
| Bug fix?      | no
| New feature?  |no 
| BC breaks?    | no
| Deprecations? | no 
| Tests pass?   | yes
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | n/a

Use `rawurlenode` instead of my custom escaper as suggested by @nicolas-grekas: https://twitter.com/nicolasgrekas/status/887728384469590016

2017-07-19 19:40 UTC, nicolas-grekas approved these changes

2017-07-19 20:19 UTC, ogizanagi approved these changes

2017-07-20 07:47 UTC, fabpot requested changes

2017-07-20 07:47 UTC, fabpot commented on src/Symfony/Component/PropertyInfo/PropertyInfoCacheExtractor.php
> +        $key = rawurlencode($method.'.'.$serializedArguments);
Can you add a comment above to explain why we need to encode (that's not trivial to understand now that the comment on the escape method is not here anymore)

2017-07-20 07:53 UTC, dunglas commented on src/Symfony/Component/PropertyInfo/PropertyInfoCacheExtractor.php
> +        $key = rawurlencode($method.'.'.$serializedArguments);
done

2017-07-20 07:54 UTC, fabpot approved these changes

2017-07-20 07:55 UTC, fabpot commented
Thank you @dunglas.

2017-07-20 07:55 UTC, merged