[DI][ProxyManager] Pass the full call to DumperInterface::getProxyFac…
symfony/symfony pull request #23693
Opened 2017-07-27 12:58 UTC by nicolas-grekas

…toryCode()

| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | yes
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

Passing the full code to call the factory is more flexible, as spotted while working on #23678.

2017-07-27 15:47 UTC, stof requested changes

2017-07-27 15:47 UTC, stof commented on src/Symfony/Bridge/ProxyManager/LazyProxy/PhpDumper/ProxyDumper.php
> +    public function getProxyFactoryCode(Definition $definition, $id, $methodCall = null)
I would name it `instantiationExpression` instead, as it may not even be a method call.

2017-07-27 17:12 UTC, nicolas-grekas commented on src/Symfony/Bridge/ProxyManager/LazyProxy/PhpDumper/ProxyDumper.php
> +    public function getProxyFactoryCode(Definition $definition, $id, $methodCall = null)
updated to $factoryCode

2017-07-28 07:30 UTC, fabpot approved these changes

2017-07-28 07:31 UTC, fabpot commented
Thank you @nicolas-grekas.

2017-07-28 07:31 UTC, merged