[Workflow] Fix #23695: add getter for workflow
symfony/symfony pull request #23700
Opened 2017-07-28 09:48 UTC by Simperfit

2017-07-28 11:07 UTC, nicolas-grekas commented
retargeted for 3.4 as 3.3 is for bugfixes only

2017-07-28 13:30 UTC, Simperfit commented
@nicolas-grekas rebase done

2017-08-04 06:13 UTC, lyrixx requested changes

2017-08-04 06:13 UTC, lyrixx commented on src/Symfony/Component/Workflow/Workflow.php
> +     * @return MultipleStateMarkingStore
`MarkingStoreInterface`

2017-08-04 09:59 UTC, Simperfit commented on src/Symfony/Component/Workflow/Workflow.php
> +     * @return MultipleStateMarkingStore
done

2017-08-04 10:13 UTC, lyrixx approved these changes

2017-08-04 10:14 UTC, lyrixx commented
:+1:

2017-08-05 14:27 UTC, nicolas-grekas commented
ping @Nyholm ;)

2017-08-05 14:36 UTC, Nyholm approved these changes
Thank you for the ping. 

Also @Guite, real nice tool =)

2017-08-05 17:31 UTC, fabpot approved these changes

2017-08-05 17:32 UTC, fabpot commented
Thank you @Simperfit.

2017-08-05 17:32 UTC, merged