[DependencyInjection] Deprecate autowiring service auto-registration
symfony/symfony pull request #23712
Opened 2017-07-29 13:30 UTC by GuilhemN

| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no 
| BC breaks?    | no
| Deprecations? | yes 
| Tests pass?   | yes
| Fixed tickets | https://github.com/symfony/symfony/issues/23350
| License       | MIT
| Doc PR        | 

Fix https://github.com/symfony/symfony/issues/23350, to make autowiring more predictable.

2017-07-29 18:36 UTC, GuilhemN commented
@nicolas-grekas the cs issue reported by fabpot.io was done on purpose, right?

2017-07-29 18:46 UTC, nicolas-grekas commented
Right

2017-08-01 06:19 UTC, fabpot requested changes

2017-08-01 06:19 UTC, fabpot commented on UPGRADE-3.4.md
> +   whose ids are their fully-qualified class name.
An example with `before`/`after` would probably help people understand what that means. For anybody not familiar with the container, this is cryptic :)

2017-08-01 08:56 UTC, GuilhemN commented on UPGRADE-3.4.md
> +   whose ids are their fully-qualified class name.
Indeed, that's a deprecation that is hard to illustrate but I added an example that I tried to make as familiar as possible :)

2017-08-01 11:03 UTC, ogizanagi approved these changes

2017-08-01 13:42 UTC, xabbuh requested changes
the changelog file of the DependencyInjection component needs to be updated too

2017-08-01 19:59 UTC, GuilhemN commented
@xabuh done

2017-08-01 20:13 UTC, chalasr approved these changes

2017-08-03 09:15 UTC, nicolas-grekas commented
Thank you @GuilhemN.

2017-08-03 09:15 UTC, closed without merging