[Lock] Deprecate Filesystem/LockHandler
symfony/symfony pull request #23724
Opened 2017-07-31 07:35 UTC by jderusse

| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | yes
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        | TODO

This PR deprecate the `Filesystem\LockHandler` in favor of `Lock\SemaphoreStore` and `Lock\FlockStore`.

2017-07-31 08:11 UTC, chalasr requested changes
The console composer.json needs an update (replacing the `filesystem` requirement by `lock`)

2017-07-31 08:11 UTC, chalasr commented on src/Symfony/Component/Filesystem/LockHandler.php
>  /**
`* @deprecated since ...`

2017-07-31 08:11 UTC, chalasr commented on src/Symfony/Component/Filesystem/LockHandler.php
> +@trigger_error(sprintf('The %s class is deprecated since version 3.4 and will be removed in 4.0. Use the SemaphoreStore or FlockStore class instead.', LockHandler::class), E_USER_DEPRECATED);
getting this notice while using the standalone filesystem, I would try to find the SemaphoreStore in the filesystem component. I would use FQCNs or prepend `Lock` here

2017-07-31 08:11 UTC, chalasr commented on UPGRADE-3.4.md
> +
should be reverted

2017-07-31 08:26 UTC, jderusse commented on src/Symfony/Component/Filesystem/LockHandler.php
> +@trigger_error(sprintf('The %s class is deprecated since version 3.4 and will be removed in 4.0. Use the SemaphoreStore or FlockStore class instead.', LockHandler::class), E_USER_DEPRECATED);
right

2017-07-31 09:21 UTC, chalasr commented
fabbot needs some love

2017-07-31 10:57 UTC, chalasr approved these changes
👍

2017-08-01 05:25 UTC, fabpot approved these changes

2017-08-01 05:26 UTC, fabpot commented
Thank you @jderusse.

2017-08-01 05:27 UTC, merged