Fixed UPGRADE-4.0 about Container::set
symfony/symfony pull request #23821
Opened 2017-08-07 16:05 UTC by lyrixx

| Q             | A
| ------------- | ---
| Branch?       | 3.3
| Bug fix?      | no (doc fix)
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

2017-08-07 16:19 UTC, nicolas-grekas approved these changes

2017-08-07 16:58 UTC, Simperfit approved these changes

2017-08-07 17:03 UTC, stof requested changes

2017-08-07 17:03 UTC, stof commented on UPGRADE-4.0.md
>   * Setting or unsetting a private service with the `Container::set()` method is
`private` here does not make sense anymore either. Public services are forbidden too when not synthetic

2017-08-07 17:06 UTC, lyrixx commented on UPGRADE-4.0.md
>   * Setting or unsetting a private service with the `Container::set()` method is
:+1: Good catch. Fixed.

2017-08-08 06:24 UTC, nicolas-grekas commented
Thank you @lyrixx.

2017-08-08 06:24 UTC, merged