[DI] Fix merging of env vars in configs
symfony/symfony pull request #23903
Opened 2017-08-16 21:17 UTC by nicolas-grekas

| Q             | A
| ------------- | ---
| Branch?       | 3.3
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #22561
| License       | MIT
| Doc PR        | -

2017-08-17 13:06 UTC, nicolas-grekas commented
Because processing configuration is done internally in `Extension::load()`, we have no proper way to get the processed configuration from the outside.

I didn't find any better implementation than the one in this PR, which consist of storing processed configs when `Extension::processConfiguration()` is being called, then fetching these with a new `Extension::getProcessedConfigs()` method.

This works only if extensions do call `processConfiguration()` of course.
I'd expect this to be a common enough situation to consider the issue fixed.
If the expectation is not met, the outcome is that overridden env vars are tracked again, which is not a huge issue anyway, and is just the current situation.

Decoupling config processing from loading is another possibility, but that'd be asking for big changes for all bundle authors. Not worth it IMHO.

PR is ready (failures are false positives.)

2017-08-18 08:30 UTC, fabpot requested changes
I think we need copious comments so that we can still understand the logic in 2 years :)

2017-08-18 08:30 UTC, fabpot commented on src/Symfony/Component/DependencyInjection/Extension/Extension.php
> +    final public function getProcessedConfigs()
/** @internal */?

2017-08-18 11:26 UTC, nicolas-grekas commented on src/Symfony/Component/DependencyInjection/Extension/Extension.php
> +    final public function getProcessedConfigs()
so it is

2017-08-18 11:26 UTC, nicolas-grekas commented
comments added, should be ready

2017-08-18 12:20 UTC, Taluu commented on src/Symfony/Component/DependencyInjection/ParameterBag/EnvPlaceholderParameterBag.php
> +    public function resolveEnvReferences(array $value)
isn't this a BC break ?

2017-08-18 12:22 UTC, nicolas-grekas commented on src/Symfony/Component/DependencyInjection/ParameterBag/EnvPlaceholderParameterBag.php
> +    public function resolveEnvReferences(array $value)
this is not released yet, 3.3@dev only

2017-08-18 14:04 UTC, nicolas-grekas commented
Merging to unlock another PR to come fixing a bug in 3.3 also.
If you have further comments please still add them.

2017-08-18 14:06 UTC, merged