[Console] Add "symfony/polyfill-php70" to require-dev
symfony/symfony pull request #23934
Opened 2017-08-18 18:03 UTC by siwinski

| Q             | A
| ------------- | ---
| Branch?       | 3.3 
| Bug fix?      | no
| New feature?  | no 
| BC breaks?    | no
| Deprecations? | no 
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        | 

Since [ApplicationTest](https://github.com/symfony/symfony/blob/3.3/src/Symfony/Component/Console/Tests/ApplicationTest.php) uses the `Error` class, this component should require-dev `symfony/polyfill-php70`

2017-08-21 08:17 UTC, nicolas-grekas commented
I suggest to use an `@requires PHP 7` annotation on the test case instead.

2017-08-23 20:55 UTC, siwinski commented
Changes made per request above.  Branch rebased.

2017-08-23 20:57 UTC, chalasr requested changes

2017-08-23 20:57 UTC, chalasr commented on src/Symfony/Component/Console/Tests/ApplicationTest.php
> + * @requires PHP 7
Only methods which use PHP7 features should be annotated

2017-08-23 21:45 UTC, siwinski commented on src/Symfony/Component/Console/Tests/ApplicationTest.php
> + * @requires PHP 7
Updated and rebased

2017-08-23 22:26 UTC, chalasr approved these changes

2017-08-23 22:36 UTC, chalasr commented
Good catch, thanks @siwinski.

2017-08-23 22:36 UTC, merged