[PhpUnitBridge] install PHPUnit 6 on PHP 7.2
symfony/symfony pull request #23952
Opened 2017-08-22 16:45 UTC by xabbuh

| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #23943
| License       | MIT
| Doc PR        |

2017-08-22 16:51 UTC, dmaicher commented
phpunit 6 itself is not really backwards compatible due to the namespace changes. Does the phpunit bridge add any backwards compat layer for it? Or will my tests just fail if my testsuite is running on phpunit 5 without any namespaced classes?

2017-08-22 21:17 UTC, stof requested changes

2017-08-22 21:17 UTC, stof commented on src/Symfony/Bridge/PhpUnit/bin/simple-phpunit
> +    $PHPUNIT_VERSION = getenv('SYMFONY_PHPUNIT_VERSION') ?: '4.8';
This changes the existing behavior. For PHP < 5.6, the env variable was ignored before, forcing to use 4.8, as this is the only usable version there:

- newer versions are not supported on these PHP runtimes
- older versions than 4.8 are not supported by the bridge.

I would keep this behavior (anyway, changing it is a BC break).

2017-08-22 21:48 UTC, stof commented
@dmaicher if you run your testsuite on PHPUnit 6 while using `PHPUnit_Framework_TestCase` as base class, things will break totally.
However, using the PHPUnit bridge with PHPUnit 5.7 on PHP 7.2 will also make your CI red: the bridge makes the run fail when encountering deprecations, and PHPUnit 5.7 triggers a deprecation coming from PHP 7.2.

However, making your testsuite compatible with several PHPUnit versions is possible. PHPUnit 4.8.35 and 5.4.3+ are providing the `PHPUnit\Framework\TestCase` class as a forward compatibility layer, allowing you to migrate to the namespace API in your `extends` clause. This is the way to go.
And note that PHPUnit 6 is the only actively maintained version of PHPUnit, so migrating to it is a must-have IMO.
And the migration to namespaced base testcase can be done easily. If you don't care about getting `extends \PHPUnit\Framework\TestCase` instead of using a use statement, it is a simple search&replace.

2017-08-23 11:30 UTC, xabbuh commented on src/Symfony/Bridge/PhpUnit/bin/simple-phpunit
> +    $PHPUNIT_VERSION = getenv('SYMFONY_PHPUNIT_VERSION') ?: '4.8';
You are right. I misread the nested ternary operators.

2017-08-23 15:19 UTC, nicolas-grekas approved these changes

2017-08-24 07:02 UTC, Simperfit commented
Maybe it will help for #23671, 👍

2017-08-24 07:03 UTC, Simperfit approved these changes

2017-08-24 10:23 UTC, Tobion approved these changes

2017-08-24 11:45 UTC, fabpot approved these changes

2017-08-24 11:46 UTC, fabpot commented
I think this should be merged in 3.3 instead.

2017-08-28 09:16 UTC, nicolas-grekas commented
:+1: for 3.3

2017-08-28 10:44 UTC, xabbuh commented
rebased on 3.3

2017-08-28 11:33 UTC, fabpot commented
Thank you @xabbuh.

2017-08-28 11:33 UTC, merged

2017-08-28 11:33 UTC, fabpot commented on src/Symfony/Bridge/PhpUnit/CHANGELOG.md
> +3.4.0
removed after the merge (2230e31727)

2017-08-28 12:58 UTC, xabbuh commented on src/Symfony/Bridge/PhpUnit/CHANGELOG.md
> +3.4.0
thanks