[Cache] Use options from Memcached DSN
symfony/symfony pull request #23978
Opened 2017-08-24 19:09 UTC by Bukashk0zzz

| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #23962 
| License       | MIT
| Doc PR        | -

This PR allows to pass options in cache config.
Example:
```yaml
framework:
    cache:
        app: cache.adapter.memcached
        default_memcached_provider: 'memcached://%env(MEMCACHE_HOST)%?socket_recv_size=1&socket_send_size=2'
```

2017-08-25 06:32 UTC, Bukashk0zzz commented
There are needed any work on this PR from me? 
I saw that tests failed in 3.4 with php 7.1 already.
Haven't any idea why 'Class 'Memcached' not found' in AppVeyor tests

2017-08-25 07:33 UTC, nicolas-grekas commented on src/Symfony/Component/Cache/Tests/Adapter/MemcachedAdapterTest.php
> +    public function provideDSNWithOptions()
should be `provideDsnWithOptions`
the provider should do a class_exists check on Memcached and yield nothing when not, in order to allow skipping the tests when Memcached is not installed

2017-08-25 08:23 UTC, Bukashk0zzz commented
@nicolas-grekas fixed.

2017-08-26 13:27 UTC, fabpot commented on src/Symfony/Component/Cache/CHANGELOG.md
> + * added Using options from Memcached DSN
`using` without capital U

2017-08-27 09:27 UTC, Bukashk0zzz commented
Updated

2017-09-02 14:40 UTC, nicolas-grekas commented on src/Symfony/Component/Cache/Traits/MemcachedTrait.php
> +                    $options += $query;
this means that the precedence is:
1. options provided as 2nd argument
2. win over options provided as part of the DSN
3. who then win over defaults.

But in RedisTrait, 1. and 2. are swapped:
1. options provided as part of the DSN
2. win over options provided as 2nd arg
3. who then win over defaults.

This allows "the infrastructure" to take over the app config.
I think it also makes sense to do the same here.

2017-09-02 14:41 UTC, nicolas-grekas requested changes
see comment about precedence

2017-09-05 06:18 UTC, Bukashk0zzz commented
@nicolas-grekas Fixed. Also updated tests for this case.

2017-09-05 08:04 UTC, nicolas-grekas approved these changes

2017-09-05 18:44 UTC, fabpot approved these changes

2017-09-05 18:44 UTC, fabpot commented
Thank you @Bukashk0zzz.

2017-09-05 18:44 UTC, merged