Use new configuration depreciation method
symfony/symfony pull request #24025
Opened 2017-08-29 16:39 UTC by sanpii

| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | no
| Fixed tickets | N/A
| License       | MIT
| Doc PR        | N/A

In keeping with #22382

2017-08-29 18:03 UTC, chalasr requested changes

2017-08-29 18:03 UTC, chalasr commented on src/Symfony/Bundle/FrameworkBundle/FrameworkBundle.php
> -            @trigger_error('The "kernel.trusted_proxies" parameter is deprecated since version 3.3 and will be removed in 4.0. Use the Request::setTrustedProxies() method in your front controller ins
this change should be reverted as the notice is not about the `framework.trusted_proxies` config option but the corresponding kernel parameter, triggering is still relevant. If you think it should be rediscussed, that should be done on 3.3 where it has been introduced.

2017-09-01 19:40 UTC, sanpii commented
I don’t understand why the tests failed on travis. I can’t reproduce the problem on my computer (with php 7.0 and `--prefer-lowest`).

2017-09-03 19:39 UTC, chalasr commented
Should be better after #24083.

2017-09-04 07:43 UTC, nicolas-grekas commented
rebase needed to account for #24083.

2017-09-04 08:02 UTC, sanpii commented
Done, thank you @chalasr.

It’s better but it still failed with hhvm and php 5.5 due to deprecation notices.

2017-09-04 09:11 UTC, chalasr commented
@sanpii Looks like this triggers extra deprecations, I suspect that we trigger when we should not (e.g. because the node has a default value, we trigger even if not explicitly set). I'll look into later today.

2017-09-04 13:45 UTC, chalasr submitted a review, later dismissed
That was the case (https://github.com/symfony/symfony/pull/24025#issuecomment-326909876), added a commit that makes nodes trigger deprecations only if the value is explicitly set. PR looks good to me.

2017-09-04 17:08 UTC, chalasr commented
VariableNode (= all nodes which are not `ArrayNode`) should not trigger the deprecation itself, as it is always the child of a rootNode which is responsible for triggering when a child is marked as deprecated. PR ready (fixing the implementation)

2017-09-04 18:00 UTC, nicolas-grekas commented
Thank you @sanpii and @chalasr

2017-09-04 18:00 UTC, merged