[Serializer] Change visibility of getNormalizer and getDenormalizer
symfony/symfony pull request #24206
Opened 2017-09-14 16:40 UTC by welcoMattic

| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        | 

I'm currently working on a projet that have many normalizers. Enough to get almost 20sec in `getDenormalizer` method:

![capture d ecran 2017-09-14 a 15 04 35](https://user-images.githubusercontent.com/773875/30441844-dd81d924-997a-11e7-9d8e-210fb423653c.png)

I would like to write my own Serializer, and I figure out that `getNormalizer` and `getDenormalizer` methods are private.

Here what I would like to do:

```php
<?php

class ChainSerializer extends Serializer
{
    public function __construct(array $normalizers = [], array $encoders = [])
    {
        $indexedNormalizers = [];

        foreach ($normalizers as $normalizer) {
            /* Little workaround to get clean indices */
            $normalizerClassName = get_class($normalizer);
            $modelClassName = str_replace('Normalizer', '', $normalizerClassName);
            $modelClassName = str_replace('\\\\', '\\Model\\', $modelClassName);
            $indexedNormalizers[$modelClassName] = $normalizer;
        }

        parent::__construct($indexedNormalizers, $encoders);
    }

    protected function getNormalizer($data, $format, array $context)
    {
        return $this->normalizers[get_class($data)];
    }

    protected function getDenormalizer($data, $class, $format, array $context)
    {
        return $this->normalizers[$class];
    }
}
```

I figure out too these `$normalizers` are `protected` which enforce me to submit this PR.

Ping @dunglas @lyrixx

2017-09-14 16:43 UTC, lyrixx commented
I found this use case legit and right now I don't see an easy way to achieve this perf optim (quite huge in this project)

2017-09-15 16:57 UTC, ogizanagi approved these changes
It looks sensible to me.

2017-09-15 17:07 UTC, dunglas commented
It used to have a cache for this method, it has been removed in #17140. But the removal of this cache introduce a huge performance penalty (the one you suffered).
Maybe would can it be a good idea to reintroduce this cache but make it disabled by default?

2017-09-15 17:27 UTC, nicolas-grekas commented
The reason why we remove the cache would be still valid, so that this option would be a foot gun I guess.
Instead, what about adding an interface that would provide a method that would return a cache key? Then if it is implemented, we use the cache.

2017-09-15 17:48 UTC, dunglas commented
@welcoMattic, can you share your profile publicly?

2017-09-15 17:51 UTC, dunglas commented
@nicolas-grekas I think it won't help, the previous cache allowed to skip the whole loop. Here we still need to loop and to call `supports*`. `supports*` is usually lightweight. Calling a method to get a cache key instead will have no gain.

Another proposal: introduce a `NonCacheableSupportsReturnInterface` interface and use the cache if no normalizer implements it.

2017-09-15 18:58 UTC, nicolas-grekas commented
we talked with @dunglas and might have found an idea:
we could add an new interface with a `getProvidedTypes`
this method would return an array keyed by PHP-type/class, valued by a bitfield of "vary" consts: DATA | CONTEXT, which when set,
this would tell the outside what the "supports*" methods vary on, so that good enough cache/optimizations strategies could be implemented with that info.

2017-09-15 20:12 UTC, ro0NL commented
is the vary strategy worth it? It's nice.. but feels a bit over-engineered =/ Eventually the `Serializer` is simple chain implementation, which is fine to me.

Exposing here is the easiest no? Or introduce a new abstraction layer?

While at it; `Serializer::denormalizeObject()` can be inlined i guess.

2017-09-15 20:18 UTC, dunglas commented
@ro0NL exposing only fix partially the problem, from my experience, this performance problem occurs often when you use the serializer intensively (yes I've API Platform in mind).

Unlike exposing, fixing this problem would benefit to every users without requiring custom developments.

2017-09-15 20:31 UTC, ro0NL commented
What about a new `AbstractKnownObjectNormalizer` :scream: or so. It would have `final` supports method and exposes it supported object types.

So kinda following the same path proposed by @nicolas-grekas, but perhaps easier to implement.

2017-09-15 21:44 UTC, nicolas-grekas commented
I'd be interested in knowing if a simple approach like #24206 could be enough?
Can any of you measure any significant improvement with it?

2017-09-15 22:32 UTC, ro0NL commented
Also `extends Serializer` might not be the right trade-off. If `$normalizerClassName = get_class($normalizer);` is your convention, perhaps implement the required interfaces directly? Most would be simple method forwarding anyway.

Yet i understand you prefer this extension point, in favor to copy/pasting `Serializer::__construct` or so. A new abstraction layer effectively is the same as this PR, probably not worth it.

2017-09-18 07:46 UTC, welcoMattic commented
@dunglas hmm, sorry it's a private application. But I can make a new simple Sf app with as many normalizers.

Thanks all for discussing about this performance issue. I'll try @nicolas-grekas PR soon.

2017-09-18 09:43 UTC, lyrixx commented
Hi

> I'd be interested in knowing if a simple approach like #24228 could be enough?

In our case it's not enough. It's logical because our normalizers don't have this cache layer. The only way to make it faster in our case is to allow us to override the `getDenormalize` / `getNormalize` method.

2017-09-18 14:32 UTC, nicolas-grekas requested changes
Just blocking merge until https://github.com/symfony/symfony/pull/24206#issuecomment-329871105 has been addressed as OK or KO as a more generic fix for the perf issue.

2017-09-26 10:25 UTC, nicolas-grekas commented
@welcoMattic @lyrixx @dunglas any OK/KO about https://github.com/symfony/symfony/pull/24206#issuecomment-329871105?

Status: waiting feedback

2017-09-26 12:57 UTC, lyrixx commented
> we talked with @dunglas and might have found an idea:
> we could add an new interface with a getProvidedTypes
> this method would return an array keyed by PHP-type/class, valued by a bitfield of "vary" consts: DATA | CONTEXT.
> this would tell the outside what the "supports*" methods vary on, so that good enough cache/optimizations strategies could be implemented with that info.

I'm not sure to follow you. Because how would you generated a cache-id when the normalizer vary on the the data? If it's an object it's quite simple (spl_object_hash) but if it's an array ...

2017-09-26 12:59 UTC, nicolas-grekas commented
> how would you generated a cache-id when the normalizer vary on the the data

We would not. That'd then be the responsibility of the normalizer class. But in you example, you don't vary by "data", but only by "type(data)", which would be covered by the interface so caching would happen.

2017-09-26 13:05 UTC, lyrixx commented
Ok, so you cache layer will only cache something based on the context ?

2017-09-26 13:17 UTC, nicolas-grekas commented
Almost like http vary yes, with 3 vary-by possible: type(data) and/or context yes, state inside data cannot be considered from this layer

2017-09-26 13:18 UTC, nicolas-grekas commented
Oh, but there would still be a benefit when the data is considered: if you say "for this type, it varies by data", then the cache layer will still be able to skip the normalizer for any other non specified type.

2017-09-26 13:35 UTC, lyrixx commented
It looks good to me. We will try to update this PR as soon as possible.

2017-09-26 13:41 UTC, welcoMattic commented
Thanks for all tour ideas, I'll see with @lyrixx to update the PR before the feature freeze

2017-10-05 10:49 UTC, nicolas-grekas commented
I think it's too late for 3.4, adding this vary-by cache should be done for 4.1 now.
I'm closing this PR as we figured out a way to not open these methods, which is always the solution we prefer for maintenance purpose, and replacing it by an issue with a description of what we discussed.

2017-10-05 10:49 UTC, closed without merging

2017-10-05 10:55 UTC, nicolas-grekas commented
See https://github.com/symfony/symfony/issues/24436