[Fix] Serializer XmlEncoder unicode encoding
symfony/symfony pull request #24376
Opened 2017-09-29 13:36 UTC by orions

| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | yes
| New feature?  | no 
| BC breaks?    | no
| Deprecations? | no 
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        | 

If you are storing multi-byte characters in XML (as UTF8 unicode), then saving the XML using saveXML() will create problems. It will spit out the characters converted in encoded format.

2017-09-29 14:06 UTC, ro0NL commented
What's your document encoding; this seems to work fine..

https://3v4l.org/P3UWF

Also passing the document root; we lose the XML header. That's a side effect.

2017-09-29 14:24 UTC, orions commented
Hi @ro0NL ,

when i try to encode 

> Un contrat aidé c’est 20h semaine et 687€...pas glorieux ! Préserver ça ? On vaut mieux !
 
i got this

`Un contrat aid&#xE9; c&#x2019;est 20h semaine et 687&#x20AC;...pas glorieux ! Pr&#xE9;server &#xE7;a ? On vaut mieux !`

2017-09-29 14:36 UTC, ro0NL commented
Same https://3v4l.org/tuEqH :)

Looking at `XmlSerializationVisitor` the default encoding is UTF-8. So im curious whats happening on your side.

2017-09-30 16:23 UTC, orions commented
This string is utf8 unicode encoded and when i try this fix, it's solve my issue.

I saw this solution in a comment on this official php documentation => http://php.net/manual/fr/domdocument.savexml.php

2017-10-06 08:37 UTC, 20uf approved these changes

2017-10-12 06:09 UTC, dunglas requested changes

2017-10-12 06:09 UTC, dunglas commented on src/Symfony/Component/Serializer/Tests/Encoder/XmlEncoderTest.php
> +        $expected = '<?xml version="1.0" encoding="UTF-8"?>'."\n".
Please don't touch those tests as they don't contain unicode data, and anyway `encoding="UTF-8"` is the default value. If it doesn't work without this change, it's a BC break.

2017-10-12 06:11 UTC, dunglas commented
`Un contrat aid&#xE9; c&#x2019;est 20h semaine et 687&#x20AC;...pas glorieux ! Pr&#xE9;server &#xE7;a ? On vaut mieux !`. is a valid XML-encoded string btw. It should not cause issue with most XML parsers.

2018-01-21 17:52 UTC, nicolas-grekas commented
Closing as there seem to be no issue on Symfony's side.
Please open an issue with a reproducer ideally if you think something is broken.

2018-01-21 17:52 UTC, closed without merging