Added support for deprecating aliases
symfony/symfony pull request #24707
Opened 2017-10-27 14:48 UTC by j92

| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes/no
| New feature?  | yes 
| BC breaks?    | no
| Deprecations? | no 
| Tests pass?   | yes
| Fixed tickets | #24507 
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

This pr adds support for deprecating aliases. I am looking for feedback if I am on the right track with this feature.

2017-10-27 17:27 UTC, greg0ire requested changes
Thanks for implementing this, great job so far!

2017-10-27 17:27 UTC, greg0ire commented on src/Symfony/Component/DependencyInjection/Alias.php
> +    private static $defaultDeprecationTemplate = 'The "%service_id%" service is deprecated. You should stop using it, as it will soon be removed.';
Maybe "service alias" instead of just "service"?

2017-10-27 17:27 UTC, greg0ire commented on src/Symfony/Component/DependencyInjection/Tests/AliasTest.php
> +            'message not containing require %service_id% variable' => array('this is deprecated'),
"required"

2017-10-28 14:40 UTC, nicolas-grekas commented
This PR needs to be rebase on master and target 4.1, it's too late to merge in into 3.4.
Note also that there is a big missing part (it's a non-trivial topic): the dumper container also needs to trigger the deprecation notice.

2017-10-28 15:17 UTC, j92 commented
@nicolas-grekas Thanks for the feedback. I will add the missing part, do some more testing and target 4.1.

2017-11-03 15:32 UTC, j92 commented
I am currently figuring out how to handle the trigger of the deprecation notice in the dumped container. Especially with deprecated private aliases, which are removed from the container in the `RemovePrivateAliasesPass` compiler pass. So after compiling, I have no reference to these aliases anymore. 

For public aliases I had the idea to deprecate the actual definition in the `ReplaceAliasByActualDefinitionPass` compiler pass, but I'm also not sure if thats the correct way to go. 

@greg0ire Maybe you have an idea that will push me in the right direction here?

2017-11-03 16:02 UTC, greg0ire commented
> Especially with deprecated private aliases, which are removed from the container in the RemovePrivateAliasesPass compiler pass. So after compiling, I have no reference to these aliases anymore.

Not sure if this is an issue. IMO, the deprecations should be triggered when compiling the container, because that is when they are used. You don't want deprecations to be triggered for every unrelated http requests.

> For public aliases I had the idea to deprecate the actual definition in the ReplaceAliasByActualDefinitionPass compiler pass, but I'm also not sure if thats the correct way to go.

If you do that, people will not be able to get rid of the deprecation by referencing the actual service definition, will they?

2017-11-17 08:10 UTC, j92 commented
@greg0ire Sorry for the late reply, I didn't have a lot of time to work on this issue.

Are you sure that the deprecations should be triggered when compiling the container? As far as I can see and understand it, the notices are added in the dumper classes like the `PhpDumper` and the `XmlDumper`. Then the dumped container is loaded and the real errors are triggered in the `ContainerBuilder`. So every time the container is loaded, the deprecation error is triggered, which makes it possible to show it in the Symfony Profile for example.

2017-11-17 09:24 UTC, greg0ire commented
That's my point. Wouldn't that make a lot of deprecations, irrelevant to the current page? Not sure what's best.

2017-11-17 09:56 UTC, j92 commented
That makes a lot of deprecations indeed, but that's also how it's done for services at the moment. Deprecating a service, triggers a notice on every request. So my guess is that we want the same behaviour for service aliases right?

2017-11-17 09:56 UTC, greg0ire commented
Correct. Go with it then.

2017-11-17 10:09 UTC, j92 commented
Okay, I will then.

To come back to my original question, I am wondering about the comment of @nicolas-grekas :

> Note also that there is a big missing part (it's a non-trivial topic): the dumper container also needs to trigger the deprecation notice.

Is it enough to implement the deprecation notices in the several dumpers like the PhpDumper and the XmlDumper, so that when they are loaded, the ContainerBuilder triggers the deprecation notice? Or I am missing other places which should trigger the deprecation notice as well?

2018-01-25 08:45 UTC, kiler129 commented
Ok, I think there is a time to take a dust from this issue ;) First of all I don’t believe it’s enough to implement them in dumpers, this will lead to poor DX.

I spent some time with the code and I have few ideas. Two steps are necessary regardless of the solution choosen:
1. Rebase onto master
2. Modify `ReplaceAliasByActualDefinition` to ignore not just public aliases but also deprecated ones

Then we get into interesting part - how to trigger deprecation on runtime?
  - **[A]** Change aliases array to contain deprecation flag
    - We change `aliastName => (string)target` to `aliasName => [target, (bool)isDeprecated]`
    - We change internal yet public `$this->aliases` (correct me if I’m wrong?).
    - This requires modification of all calls to `$this->aliases[$id]` to use `$this->aliases[$id][0]`
    - Generally I will say it's no-no solution due to a real BC break
  - **[B]** Save two maps side by side
    - First map stays as it is in `$this->aliases`
    - Second map has structure exactly like `$this->aliases` **but** it’s checked after normal map and triggers deprecation notice as needed
    - This requires additional element and changes in base container class. Instead of having something like this (example from `get()`):
      ```php
      if (isset($this->aliases[$id])) {
          $id = $this->aliases[$id];
      }
      ```
      we will end up with:
      ```php
      if (isset($this->aliases[$id])) {
          $id = $this->aliases[$id];
      } elseif (isset($this->aliasesDeprecated[$id])) {
          $id = $this-> aliasesDeprecated[$id];
          @trigger_error(...);
      }
      ```
    - This solution has almost no BC break. The only small thing I see is we no longer guarantee that `$this->aliases` contains all not inlined aliases, but personally I'm not concerned
    - I don't like this solution since it introduces additional overhead to **every** lookup when service is not an alias nor a deprecated alias
    - This solution doesn't let us give a good DX by suggesting a replacement
  - **[C]** Save deprecation map
    - Map in `$this->aliases` stays as is
    - We add list under `$this-> aliasesDeprecated` containing an array with alias name as the key and target alias as value (which gives us option to provide suggestion of new service/alias name)
    - Again we have to change lookups in base container. The lookup will look like so:
      ```php
      if (isset($this->aliases[$id])) {
          $id = $this->aliases[$id];
          if (isset($this->aliasesDeprecated[$id])) {
              @trigger_error(...);
          }
      }
      ```
    - This solution has almost zero BC break
    - I slightly dislike it. It's better than **[B]** since we get overhead only on call to aliases, but the overhead is added to all aliased - deprecated or not...
  - **[D]** Generate alias methods
    - Modify `PhpDumper::addMethodMap()` to include methods for deprecated aliases (this of course has to be done after targets)
    - Skip deprecated aliases in `PhpDumper::addAlises()`
    - Modify *(scary)* `PhpDumper::addService()` to generate method like so:
       ```php
       protected function get[AliasName]AliasTo[TargetName]() {
           @trigger_error(...);

           return get[TargetName]();
       }
       ```
    - This will be hard to implement (at least form my point of view)
    - This will introduce performance loss only on deprecated aliases, nothing else

WYDYT @nicolas-grekas? @fabpot?

2018-01-25 09:34 UTC, nicolas-grekas commented
@kiler129 thanks for the heads up. I think we should go for D, but of course only for public aliases that cannot be inlined. Thus, the current state of the PR looks good to me. It just need to handle two more cases:
- non-inlined public deprecated aliases should generate a method like suggested here. That's mean they'd be listed in the "methodMaps" property, and not in "aliases" anymore of course.
- we need a new logic at compilation time that would trigger a deprecation whenever a deprecated symbol is referenced (either an alias or a service, doesn't matter).

As a general design note, I don't think it matter that the symbol being deprecated is an alias or a service: that's an implementation detail of the service graph. What matters is that a symbol that is being planned for removal triggers a warning. This may mean that we don't need to put the word "alias" in the messages, and use "service" all the time. WDYT?

@j92 does that make sense for you? Ok to continue?

2018-01-25 09:58 UTC, kiler129 commented
I think we're on the right track.

- For inlined aliases (so in practice all private ones, right?) we will get a deprecation notice during build and it will stay in compilation log which is easily accessible now
- Non-inlined ones will become pseudo-services carrying method triggering deprecation and listed in map and will not be present in aliases array
- For the reference logic across compilation process if I understood your intention correctly you want to trigger deprecation everywhere deprecated symbol is used. I quickly searched DIC component code and found possible targets:
  - `Compiler\AnalyzeServiceReferencesPass::getDefinitionId`
  - `Compiler\AutoAliasServicePass`
  - `Compiler\DecoratorServicePass`
  - `Compiler\ResolveReferencesToAliasesPass::getDefinitionId`

After thinking for a while I believe the idea of treating services and aliases equally is right - it's an implementation detail after all. Other messages in DIC component (except obvious places like `hasAlias()` also doesn't handle aliases any special in terms of messages.

@j92 Are you willing to rebase onto master and implement additional logic discussed?

2018-01-25 10:43 UTC, nicolas-grekas commented
ResolveReferencesToAliasesPass looks like the good place to me for now

2018-01-26 08:28 UTC, j92 commented
@kiler129 Thanks for dusting of this issue;) Yes, I am willing to rebase this branch and will start to implement the additional logic asap.

2018-03-13 17:09 UTC, kiler129 commented
@j92: Any news? Sorry for poking you, but I just periodically visit PRs which are relevant to what I do ;)

2018-04-04 12:27 UTC, fabpot commented
@nicolas-grekas Can you review this one again?

2018-04-04 13:02 UTC, j92 commented
Sorry for not finishing this PR in time. I got stuck a while ago and was not progressing at all. Unfortunately the next few weeks I won't have free time, so: 

Is there someone who can takeover the work?

2018-04-18 19:08 UTC, weaverryan commented
It's ok @j92 :). Let's just finish this PR when you have time. I'm here because we just had a use-case for this in DoctrineBundle. But, no need to rush - we're after the 4.1 feature freeze. But, yes, let's *definitely* try to get this in there for 4.2!

2018-08-02 11:44 UTC, artursvonda commented on src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php
>                      throw new InvalidArgumentException(sprintf('The configuration key "%s" is unsupported for the service "%s" which is defined as an alias in "%s". Allowed configuration keys for ser
Should the message be updated, too? Now it includes hardcoded `keys for service aliases are "alias" and "public"`.

2019-01-24 17:02 UTC, nicolas-grekas commented
Continued in #29968, thank you @j92!

2019-01-24 17:02 UTC, closed without merging