Config: mark builder property deprecated
symfony/symfony pull request #24701
Opened 2017-10-26 19:47 UTC by bburnichon

| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | yes
| Tests pass?   | yes
| Fixed tickets | none
| License       | MIT
| Doc PR        | 

`builder` protected property is not used at all in class. Mark as deprecated to enable removing asap. This is to avoid keeping dead code up to symfony `5.0` and still having this dead code in the `4.4` LTS version

2017-10-27 06:01 UTC, ro0NL approved these changes

2017-10-27 16:50 UTC, Tobion requested changes

2017-10-27 16:50 UTC, Tobion commented on src/Symfony/Component/Config/Definition/Builder/TreeBuilder.php
> +     * @deprecates since 3.4. To be removed in 4.0
typo deprecated

2017-10-27 20:30 UTC, bburnichon commented
@tobion I fixed the typo. Good catch by the way. Sorry for the ping but I don't know whether pushes trigger a request for a new review.

2017-10-28 00:19 UTC, Tobion approved these changes

2017-10-28 16:09 UTC, nicolas-grekas approved these changes

2017-10-28 16:10 UTC, nicolas-grekas commented
Thank you @bburnichon.

2017-10-28 16:54 UTC, closed without merging