[DoctrineBridge] Add decimal form type
symfony/symfony pull request #24793
Opened 2017-11-02 13:11 UTC by fancyweb

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

Currently, when an entity field is mapped as a `decimal`, the guessed form type for this field is the `NumberType`. I guess it's also the one that comes naturally to everyone's mind.

The `NumberType` uses the view transformer `NumberToLocalizedStringTransformer` which always transform the submitted string value to an int or a float.

As stated in the Doctrine documentation for the `decimal` type : 
> Values retrieved from the database are always converted to PHP’s string

So when you use the `NumberType`, the string value of your `decimal` field is replaced by its float value. The big issue is that this change of type if detected when Doctrine computes the change sets (strict comparison is done ofc). That mean a lot of unnecessary updates are made.

The new form type I introduce simply extends the `NumberType` but it transform the value back to a string (the model value).

2018-03-13 15:20 UTC, fancyweb commented
I have found a new case that was not handled correctly by my first implementation and that was not detected in the tests because it depends on the database platform.

Fields mapped as "decimal" will always be returned as string. But on some platform the values are rounded when the number of decimals is inferior to the "scale" option.

Eg with inserted float value 8.000 (scale 3) :
- On SQLite => fetched as "8"
- On PostgreSQL => fetched as "8.000"

My solution is to add an option to the new form type to correctly format the number in the model transformer.

- [ ] TODO : automatically set the options in the `DoctrineOrmTypeGuesser`

2019-04-06 09:12 UTC, chalasr commented
@xabbuh @stof @webmozart maybe you can help moving forward here?

2019-04-06 09:22 UTC, Ocramius requested changes

2019-04-06 09:22 UTC, Ocramius commented on src/Symfony/Bridge/Doctrine/Form/DataTransformer/NumberToStringTransformer.php
> +     * @param bool $forceFullScale
Needs documentation

2019-04-06 09:22 UTC, Ocramius commented on src/Symfony/Bridge/Doctrine/Form/DataTransformer/NumberToStringTransformer.php
> +            throw new TransformationFailedException('Expected a string.');
Should probably be reflected in the `@param`

2019-04-06 09:22 UTC, Ocramius commented on src/Symfony/Bridge/Doctrine/Form/DataTransformer/NumberToStringTransformer.php
> +            throw new TransformationFailedException();
Previous exception should be passed on here

2019-04-06 09:22 UTC, Ocramius commented on src/Symfony/Bridge/Doctrine/Form/DataTransformer/NumberToStringTransformer.php
> +        } catch (\Exception $e) {
Should be `\Throwable` IMO

2019-04-06 09:22 UTC, Ocramius commented on src/Symfony/Bridge/Doctrine/Form/Type/DecimalType.php
> +    public function buildForm(FormBuilderInterface $builder, array $options)
`force_full_scale` option to be documented above

2019-04-06 09:22 UTC, Ocramius commented on src/Symfony/Bridge/Doctrine/Form/Type/DecimalType.php
> +    public function buildForm(FormBuilderInterface $builder, array $options)
`scale` too

2019-04-06 12:43 UTC, Ocramius commented
About https://github.com/symfony/symfony/pull/24793#issuecomment-372703184, I just discussed it with @webmozart and it is not fixable in `doctrine/dbal` without introducing a BC break in [`DecimalType`](https://github.com/doctrine/dbal/blob/799085fac21c9759c1fcef828586418723ad063f/lib/Doctrine/DBAL/Types/DecimalType.php#L28-L34).

There is a solution, which is making the `AbstractPlatform` configurable, but that's a whole lot of additions for a very edge-case scenario.

If the whole issue drills down to avoiding superfluous updates at DB level, I don't think that problem should be tackled here, and instead a change in `doctrine/dbal` is to be proposed.

2019-04-06 13:07 UTC, webmozart commented
Working on finishing this as part of EUFOSSA.

2019-04-06 13:12 UTC, fancyweb commented
I agree that Doctrine should return coherent values between platforms for this case.

I think we can just use my initial commit with the new Form type, it will still be better than now and will be perfect once Doctrine is ready.

@webmozart Do you mean you are gonna work on a fix on Doctrine side?

2019-04-06 13:41 UTC, fancyweb commented
Closing for https://github.com/symfony/symfony/pull/30893.

2019-04-06 13:41 UTC, closed without merging

2019-04-06 14:10 UTC, webmozart commented
@webmozart No, I provided some thoughts on how to implement this in #30893 though. :)

2019-04-07 19:44 UTC, fancyweb commented
Was an issue opened on Doctrine side to track this problem?

2019-04-08 08:41 UTC, webmozart commented
@fancyweb Not yet, I'd appreciate if you could do so!