[Console] ProgressBar displays incorrectly after clear.
symfony/symfony pull request #24834
Opened 2017-11-06 07:09 UTC by Simperfit

| Q             | A
| ------------- | ---
| Branch?       | 3.3
| Bug fix?      | yes
| New feature?  | yesish ?
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #24224
| License       | MIT
| Doc PR        | has to be done to explains this behaviour.

I'm adding `setFirstRunAndClear` to change that behaviour and to have the right output.

I'm not changing the clear method, because if the output changes (which will be the case), it should considered as a BC Break.

2017-11-06 17:31 UTC, iltar commented on src/Symfony/Component/Console/Helper/ProgressBar.php
> +    public function setFirstRunAndClear()
Isn't this more of a reset?

2017-11-13 15:56 UTC, chalasr commented
I do think `clear()` needs to be updated for fixing the ticket, the behavior is just buggy when the format contains newlines (last lines get erased when calling `clear()`).
Adding `reset()` is another topic so anyway, if it's interesting (dunno yet), it should be discussed on 4.1. 
As an user you should not have to change your code for getting bug fixes.

2017-11-14 06:40 UTC, Simperfit commented
@chalasr done, ill create a new PR for the reset, it could be useful.

2017-11-20 07:30 UTC, fabpot commented on src/Symfony/Component/Console/Tests/Helper/ProgressBarTest.php
> +
this change and the one above should reverted

2017-11-30 09:22 UTC, dunglas approved these changes
👍 when @fabpot's comments will be resolved.

2017-11-30 10:05 UTC, chalasr requested changes
The fix seems invalid, with these changes and the reproducer provided in the report, the progress bar doesn't get cleared anymore

2018-01-16 19:12 UTC, nicolas-grekas commented
ping @Simperfit

2018-01-29 15:22 UTC, xabbuh commented
moving to the 3.4 milestone as the last bugfix release for 3.3 was published today

2018-02-16 09:21 UTC, Simperfit commented
I'm going to rebase it and to look for a better fix today.

2018-03-31 11:15 UTC, ostrolucky commented
ping @Simperfit

2018-07-19 07:10 UTC, fabpot commented
Closing as there is no more activity here. @Simperfit Feel free to reopen whenever you have time to finish it. Thank you.

2018-07-19 07:10 UTC, closed without merging