[TwigBundle][FrameworkBundle] Remove the internals from debug autowiring
symfony/symfony pull request #25011
Opened 2017-11-18 08:31 UTC by Simperfit

| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no 
| BC breaks?    | no
| Deprecations? |no 
| Tests pass?   | yes
| Fixed tickets | #24986
| License       | MIT
| Doc PR        |

2017-11-18 08:59 UTC, nicolas-grekas commented
Test don't pass yet :)
Wondering two things:

- does ConsoleCommandPass prefer a specific naming scheme?
- running debug:autowiring on a 3.4 standard edition, I get this list. Looks like there could me more FQCN ids removed (not only on symfony/symfony, would you mind cleaning them also?)

```
  Sensio\Bundle\FrameworkExtraBundle\EventListener\ControllerListener                 
  Sensio\Bundle\FrameworkExtraBundle\EventListener\HttpCacheListener                  
  Sensio\Bundle\FrameworkExtraBundle\EventListener\IsGrantedListener                  
  Sensio\Bundle\FrameworkExtraBundle\EventListener\ParamConverterListener             
  Sensio\Bundle\FrameworkExtraBundle\EventListener\SecurityListener                   
  Sensio\Bundle\FrameworkExtraBundle\EventListener\TemplateListener                   
  Sensio\Bundle\FrameworkExtraBundle\Request\ArgumentNameConverter                    
  Sensio\Bundle\FrameworkExtraBundle\Request\ParamConverter\DateTimeParamConverter    
  Sensio\Bundle\FrameworkExtraBundle\Request\ParamConverter\DoctrineParamConverter    
  Sensio\Bundle\FrameworkExtraBundle\Request\ParamConverter\ParamConverterManager     
  Sensio\Bundle\FrameworkExtraBundle\Routing\AnnotatedRouteControllerLoader           
  Sensio\Bundle\FrameworkExtraBundle\Security\ExpressionLanguage                      
  Sensio\Bundle\FrameworkExtraBundle\Templating\TemplateGuesser                       
  Symfony\Bridge\Twig\Command\DebugCommand                                            
  Symfony\Bundle\FrameworkBundle\Command\AboutCommand                                 
  Symfony\Bundle\FrameworkBundle\Command\AssetsInstallCommand                         
  Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand                            
  Symfony\Bundle\FrameworkBundle\Command\CachePoolClearCommand                        
  Symfony\Bundle\FrameworkBundle\Command\CachePoolPruneCommand                        
  Symfony\Bundle\FrameworkBundle\Command\CacheWarmupCommand                           
  Symfony\Bundle\FrameworkBundle\Command\ConfigDebugCommand                           
  Symfony\Bundle\FrameworkBundle\Command\ConfigDumpReferenceCommand                   
  Symfony\Bundle\FrameworkBundle\Command\ContainerDebugCommand                        
  Symfony\Bundle\FrameworkBundle\Command\DebugAutowiringCommand                       
  Symfony\Bundle\FrameworkBundle\Command\EventDispatcherDebugCommand                  
  Symfony\Bundle\FrameworkBundle\Command\RouterDebugCommand                           
  Symfony\Bundle\FrameworkBundle\Command\RouterMatchCommand                           
  Symfony\Bundle\FrameworkBundle\Command\XliffLintCommand                             
  Symfony\Bundle\FrameworkBundle\Command\YamlLintCommand                              
  Symfony\Bundle\FrameworkBundle\Controller\RedirectController                        
  Symfony\Bundle\FrameworkBundle\Controller\TemplateController                        
  Symfony\Bundle\SecurityBundle\Command\UserPasswordEncoderCommand                    
  Symfony\Bundle\TwigBundle\Command\LintCommand                                       
  Symfony\Component\Config\Resource\SelfCheckingResourceChecker                       
  Symfony\Component\DependencyInjection\Config\ContainerParametersResourceChecker     
  Symfony\Component\ExpressionLanguage\ExpressionLanguage                             
  Symfony\Component\Form\Command\DebugCommand                                         
  Symfony\Component\Routing\Loader\AnnotationDirectoryLoader                          
  Symfony\Component\Routing\Loader\AnnotationFileLoader                               
```

2017-11-18 15:13 UTC, nicolas-grekas commented on src/Symfony/Bundle/FrameworkBundle/Resources/config/console.xml
> +        <service id="console.debug_command" class="Symfony\Component\Form\Command\DebugCommand">
suffix command here, but not on the other ones, should it be always here?

2017-11-18 15:14 UTC, nicolas-grekas commented on src/Symfony/Bundle/FrameworkBundle/Tests/DependencyInjection/FrameworkExtensionTest.php
> +        $this->assertTrue($container->hasDefinition('console.workflow_dump'));
`console.command.workflow_dump`? other convention

2017-11-18 17:13 UTC, nicolas-grekas commented on src/Symfony/Bundle/FrameworkBundle/Resources/config/routing.xml
> +        <service id="framework.controller.redirect" class="Symfony\Bundle\FrameworkBundle\Controller\RedirectController" public="true">
I think we need to keep this and the next one, not for autowiring, but to ease routing

2017-11-19 07:52 UTC, Simperfit commented
The review has been taken into account.

2017-11-19 07:56 UTC, ro0NL commented on src/Symfony/Bundle/FrameworkBundle/Resources/config/console.xml
> +        <service id="console.command.debug" class="Symfony\Component\Form\Command\DebugCommand">
`console.command.form_debug` id say

2017-11-19 07:56 UTC, ro0NL commented on src/Symfony/Bundle/FrameworkBundle/Tests/DependencyInjection/FrameworkExtensionTest.php
> +        $this->assertTrue($container->hasDefinition('console.workflow_dump'));
`console.command.<underscored_name>` :+1:

2017-11-19 07:56 UTC, ro0NL commented on src/Symfony/Bundle/TwigBundle/Resources/config/console.xml
> +        <service id="twig.debug_command" class="Symfony\Bridge\Twig\Command\DebugCommand">
`twig.commmand.*`?

2017-11-19 08:12 UTC, stof requested changes

2017-11-19 08:12 UTC, stof commented on src/Symfony/Bundle/FrameworkBundle/Resources/config/console.xml
> +        <service id="console.command.error_listener" class="Symfony\Component\Console\EventListener\ErrorListener">
renamig is not good. This service is not a command

2017-11-19 08:12 UTC, stof commented on src/Symfony/Bundle/FrameworkBundle/Resources/config/console.xml
> +        <service id="console.command.debug" class="Symfony\Component\Form\Command\DebugCommand">
agreed

2017-11-19 08:12 UTC, stof commented on src/Symfony/Bundle/FrameworkBundle/Resources/config/console.xml
> +        <service id='console.workflow_dump' class="Symfony\Bundle\FrameworkBundle\Command\WorkflowDumpCommand">
missing `.command` for consistency

2017-11-19 08:12 UTC, stof commented on src/Symfony/Bundle/TwigBundle/Resources/config/console.xml
> +        <service id="twig.debug_command" class="Symfony\Bridge\Twig\Command\DebugCommand">
would make sense for consistency.

2017-11-19 16:36 UTC, chalasr commented
> does ConsoleCommandPass prefer a specific naming scheme?

@nicolas-grekas if that's what you wonder, AddConsoleCommandPass should process correctly no matter the service id

2017-11-20 07:10 UTC, Simperfit commented
done @stof

2017-11-20 08:16 UTC, dunglas requested changes

2017-11-20 08:16 UTC, dunglas commented on src/Symfony/Bundle/FrameworkBundle/Resources/config/console.xml
> +        <service id='console.command.workflow_dump' class="Symfony\Bundle\FrameworkBundle\Command\WorkflowDumpCommand">
double quote

2017-11-20 09:25 UTC, nicolas-grekas commented
There are two remaining service when testing this with the standard edition:
- Symfony\Component\Routing\Loader\AnnotationDirectoryLoader
- Symfony\Component\Routing\Loader\AnnotationFileLoader

looking more precisely with @Simperfit, we discovered that these classes are actually registered twice: first with a class as id, second with a regular id. Needs to be understood and fixed.

2017-11-20 18:12 UTC, nicolas-grekas approved these changes
(the remaining two services are declared by SensioFrameworkExtraBundle)

2017-11-20 18:15 UTC, nicolas-grekas commented
Thank you @Simperfit.

2017-11-20 18:15 UTC, merged