[DI] turn $private to protected in dumped container, to make cache:cl…
symfony/symfony pull request #25268
Opened 2017-12-02 10:38 UTC by nicolas-grekas

…ear BC

| Q             | A
| ------------- | ---
| Branch?       | 4.0
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

Turning this property to protected changes nothing to its visibility in practice as the class is final anyway,
but when migrating to SF4.0 from 3.4, the `cache:clear` command chokes with "Compile Error: Access level to srcDevDebugProjectContainer::$privates must be protected".

Let's make it protected to remove this WTF.

2017-12-02 10:48 UTC, dunglas approved these changes

2017-12-02 13:42 UTC, chalasr approved these changes

2017-12-02 16:33 UTC, fabpot requested changes

2017-12-02 16:33 UTC, fabpot commented on src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php
> +    protected \$privates = array();
A small comment should be added to explain why this specific one is not private.

2017-12-03 13:10 UTC, nicolas-grekas commented
Comment added.

Status: needs review

2017-12-03 13:19 UTC, sroze commented on src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php
> +    private function addInlineRequires(): string
fabbot is correct 😉

2017-12-03 13:20 UTC, sroze commented on src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php
> +    private function addInlineRequires(): string
is... not 😅

2017-12-03 14:27 UTC, Simperfit approved these changes

2017-12-04 16:39 UTC, fabpot approved these changes

2017-12-04 16:45 UTC, stof approved these changes

2017-12-04 16:51 UTC, fabpot commented
Thank you @nicolas-grekas.

2017-12-04 16:51 UTC, merged