[Form] DateTimeImmutable norm data in DateTime form types
symfony/symfony pull request #25273
Opened 2017-12-02 16:57 UTC by vudaltsov

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | yes
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

This PR suggests a way to use `\DateTimeImmutable` objects for norm data in `DateTimeType`, `DateType` and `TimeType`.

A complete BC layer for transformers is provided. All protected calls are also taken into account.

If this PR gets merged, we can then easily add `input=datetimeimmutable` with no model transformers to support `\DateTimeImmutable` model data.

2017-12-02 17:04 UTC, vudaltsov commented
ping @xabbuh , @stof, @HeahDude

2017-12-03 14:25 UTC, Simperfit requested changes
You need to add tests for all the new classes you created.

2017-12-03 14:25 UTC, Simperfit commented on src/Symfony/Component/Form/Extension/Core/DataTransformer/DateTimeImmutableToArrayTransformer.php
> +
no need for this empty line

2017-12-03 14:25 UTC, Simperfit commented on src/Symfony/Component/Form/Extension/Core/DataTransformer/DateTimeImmutableToLocalizedStringTransformer.php
> +
same

2017-12-03 14:55 UTC, vudaltsov commented on src/Symfony/Component/Form/Extension/Core/DataTransformer/DateTimeImmutableToArrayTransformer.php
> +
thanx, done

2017-12-03 14:56 UTC, vudaltsov commented
Added tests.

2017-12-04 15:01 UTC, stof commented
I'm not sure about the BC impact of changing the type of the norm data. I suggest adding the new input type first, without changing the norm data.

2017-12-04 15:12 UTC, vudaltsov commented
[Here](https://github.com/symfony/symfony/pull/19889#issuecomment-283394385) @HeahDude posted:

> If a new major version of Symfony bumps the requirement to PHP 5.5+, the normalized data could then be switched to the DateTimeImmutable class to simplify the logic (which is currently cloning the DateTime to avoid modifying the original one.

That's what I tried to do in my PR. My change is pretty straightforward: I copied and renamed transformers and their tests and removed `clone`.

If we really want to make norm data immutable than I think we should do it first. If we don't - than yes, just add `input=datetimimmutable` and a corresponding transformer.

But with what I suggest immutable dates will be supported in the first place. Only `DateTime`s will be converted. In this way immutable norm data helps to follow the trend of replacing `DateTime` with `DateTimeImmutable`.

2017-12-04 15:49 UTC, stof commented
you need to add the new allowed value for `input` option. Otherwise, immutable datetime are **not** supported (they are used as norm data, but cannot be used as model data, which is the requested feature)

2017-12-04 15:56 UTC, vudaltsov commented
Sure! I planned to do that in a separate PR. Because it's gonna have a couple of new tests.
In this PR I just provide a ground for that by changing the norm data.

If you wish, I can add commits right here.

2017-12-13 08:58 UTC, vudaltsov commented
@Simperfit, could you please review my tests?

2017-12-13 11:05 UTC, Simperfit reviewed
The tests looks good to me,

2017-12-13 11:05 UTC, Simperfit commented on src/Symfony/Component/Form/Tests/Extension/Core/DataTransformer/DateTimeImmutableToTimestampTransformerTest.php
> +        $this->{method_exists($this, $_ = 'expectException') ? $_ : 'setExpectedException'}('Symfony\Component\Form\Exception\TransformationFailedException');
maybe you should add a new var for this.

2017-12-22 14:13 UTC, vudaltsov commented
Closed in favor of https://github.com/symfony/symfony/pull/25273.

2017-12-22 14:13 UTC, closed without merging