[HttpFoundation] Send cookies using header() to fix "SameSite" ones
symfony/symfony pull request #25348
Opened 2017-12-06 09:32 UTC by nicolas-grekas

| Q             | A
| ------------- | ---
| Branch?       | 3.3
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #25344
| License       | MIT
| Doc PR        | -

2017-12-06 18:12 UTC, ThomHurks commented on src/Symfony/Component/HttpFoundation/Response.php
> +        foreach ($this->headers->allPreserveCase() as $name => $values) {
The current cookie code distinguishes between urlencoding the cookie value and not doing that (raw), the ```setcookie()``` function also performs some filtering and escaping as I understand it. As far as I can see in the code, the ```allPreserveCase()``` function doesn't do that but just casts the ```Cookie``` object to ```string``` and as such isn't a 1-to-1 substitute for ```setcookie()``` and ```setrawcookie()```, right?

2017-12-06 20:36 UTC, sroze commented
Nop, the Cookie now understands how to stringify itself differently based
the raw or not raw. Therefore, we don't need PHP's `set*cookie`
On Wed, 6 Dec 2017 at 18:13, Thom Hurks <notifications@github.com> wrote:

> *@ThomHurks* commented on this pull request.
> ------------------------------
>
> In src/Symfony/Component/HttpFoundation/Response.php
> <https://github.com/symfony/symfony/pull/25348#discussion_r155316254>:
>
> > @@ -337,7 +337,7 @@ public function sendHeaders()
>          }
>
>          // headers
> -        foreach ($this->headers->allPreserveCaseWithoutCookies() as $name => $values) {
> +        foreach ($this->headers->allPreserveCase() as $name => $values) {
>
> The current cookie code distinguishes between urlencoding the cookie value
> and not doing that (raw), the setcookie() function also performs some
> filtering and escaping as I understand it. As far as I can see in the code,
> the allPreserveCase() function doesn't do that but just casts the Cookie
> object to string and as such isn't a 1-to-1 substitute for setcookie()
> and setrawcookie(), right?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/symfony/symfony/pull/25348#pullrequestreview-81616344>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAxHETp-qltXfQNc_xmHHXVlwKnmRftaks5s9tkdgaJpZM4Q3nK_>
> .
>

2017-12-06 20:42 UTC, ThomHurks commented
@sroze Yes, I realized that after examining the code more closely and so I edited my comment. Still, cross-referencing the code with PHP's implementation may be a good thing to do to prevent regression in behaviour. I'm not sure how new the Cookie code is, and the code that is currently there is not actually used to generate the final cookie at the moment, so it may be incomplete/untested?

2017-12-06 21:13 UTC, nicolas-grekas commented
@ThomHurks here is the native implem:
https://github.com/php/php-src/blob/master/ext/standard/head.c#L84

everything looks fine to me.

2017-12-07 09:02 UTC, ThomHurks commented
@nicolas-grekas Not the case, there are some differences that I can spot:
- Symfony does not check the value of ```value``` against the characters ```=,; \t\r\n\013\014``` whereas PHP does. Symfony only checks it against ```name``` and PHP checks it agains ```name``` and ```value```.
- When a cookie needs to be deleted, Symfony sets the ```max-age``` to ```31536001``` and the ```expiry``` to ```now - max-age``` but PHP just passes in ```expiry = 1``` and ```max-age = 0```.
- PHP checks if the expiry date has a year greater than 9999.
- Symfony also ```urlencode```'s ```name```, I don't see PHP do that.
- Symfony uses ```urlencode``` for the ```name``` vs ```rawurlencode``` for the ```value```, not sure why that difference is there.

2017-12-07 09:07 UTC, sroze commented
I understand your concerns, and agree a bit. We will add integration
testing to this PR very soon. Highlighting the important scenarios that you
believe needs to be tested would be a very nice input from you! Could you
do so?
On Thu, 7 Dec 2017 at 09:02, Thom Hurks <notifications@github.com> wrote:

> @nicolas-grekas <https://github.com/nicolas-grekas> Not the case, there
> are some differences that I can spot:
>
>    - Symfony does not check the value of value against the characters =,;
>    \t\r\n\013\014 whereas PHP does. Symfony only checks it against name
>    and PHP checks it agains name and value.
>    - When a cookie needs to be deleted, Symfony sets the max-age to
>    31536001 and the expiry to now - max-age but PHP just passes in expiry
>    = 1 and max-age = 0.
>    - PHP checks if the expiry date has a year greater than 9999.
>    - Symfony also urlencode's name, I don't see PHP do that.
>    - Symfony uses urlencode for the name vs rawurlencode for the value,
>    not sure why that difference is there.
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/symfony/symfony/pull/25348#issuecomment-349905192>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAxHEcCjAYcpYVxNkRxVfnFdeovGgsknks5s96nCgaJpZM4Q3nK_>
> .
>

2017-12-07 19:51 UTC, nicolas-grekas commented
I'd like to propose a plan:
- @sroze would you like to submit a testing infra for this? Could be heavily inspired by `AbstractSessionHandlerTest` on 3.4
- @ThomHurks would you like to submit a separate PR on 3.3 to align the behavior with native PHP?

2017-12-07 20:13 UTC, sroze commented
I like this plan 👍
On Thu, 7 Dec 2017 at 19:51, Nicolas Grekas <notifications@github.com>
wrote:

> I'd like to propose a plan:
>
>    - @sroze <https://github.com/sroze> would you like to submit a testing
>    infra for this? Could be heavily inspired by AbstractSessionHandlerTest
>    on 3.4
>    - @ThomHurks <https://github.com/thomhurks> would you like to submit a
>    separate PR on 3.3 to align the behavior with native PHP?
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/symfony/symfony/pull/25348#issuecomment-350075636>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAxHEbIHdt80LKCThXK49tqP3kTEwUoKks5s-EHXgaJpZM4Q3nK_>
> .
>

2017-12-07 22:02 UTC, ThomHurks commented
@nicolas-grekas I will likely have time tomorrow to create a PR.

2017-12-22 21:33 UTC, nicolas-grekas commented
@sroze @ThomHurks any progress?

2018-01-12 14:27 UTC, halaei commented
Regarding [spectre attack](https://meltdownattack.com/) and [suggested mitigations](https://www.chromium.org/Home/chromium-security/ssca) should this be considered as a critical security fix?

2018-01-12 14:48 UTC, sroze commented
I don't think it has anything to do with the attacks you've mentioned. I did not get time to get ahead with this so if anybody would like until I get back to it, you're welcome 😉

2018-01-12 15:08 UTC, halaei commented
@sroze I quote the part from https://www.chromium.org/Home/chromium-security/ssca that seems to imply this is actually relevant:

> Where possible, prevent cookies from entering the renderer process' memory by using the SameSite and HTTPOnly cookie attributes, and by avoiding reading from document.cookie.

2018-01-29 15:24 UTC, xabbuh commented
moving to the 3.4 milestone as the last bugfix release for 3.3 was published today

2018-04-20 20:00 UTC, nicolas-grekas commented
Back on here, this PR now contains a second commit provided by @cvilleger, thank to him for working on it.

The Response + Cookie classes are now functionnally tested, and their behavior is a bit more aligned to PHP native one:

> Symfony does not check the value of value against the characters =,; \t\r\n\013\014 whereas PHP does. Symfony only checks it against name and PHP checks it agains name and value.

It does for the name, but doesn't care for the value. HTTP allows anything so no reason to restrict like PHP.

> When a cookie needs to be deleted, Symfony sets the max-age to 31536001 and the expiry to now - max-age but PHP just passes in expiry = 1 and max-age = 0.

Aligned

> PHP checks if the expiry date has a year greater than 9999.

I don't see any reason, kept as is (and tested.

> Symfony also urlencode's name, I don't see PHP do that.

PHP should encode. Symfony does, that's OK.

> Symfony uses urlencode for the name vs rawurlencode for the value, not sure why that difference is there.

Unrelated to the PHP vs Symfony delta, kept as is.

Status: needs review

2018-04-21 05:43 UTC, phansys requested changes

2018-04-21 05:43 UTC, phansys commented on src/Symfony/Component/HttpFoundation/Tests/CookieTest.php
> +        $this->assertEquals('foo=bar; expires=Fri, 20-May-2011 15:25:52 GMT; Max-Age=0; path=/; domain=.myfoodomain.com; secure; httponly', (string) $cookie, '->__toString() returns string representa
Could you please update `assertEquals()` calls to `assertSame()`? (as done at `ClientTest`).

2018-04-22 06:00 UTC, fabpot approved these changes

2018-04-22 06:01 UTC, fabpot commented
Thank you @nicolas-grekas.

2018-04-22 06:01 UTC, merged

2018-05-02 03:25 UTC, reatang commented
Added the RFC document：rfc6265 
The Set-Cookie Header：
https://tools.ietf.org/html/rfc6265#section-5.2.2

2018-07-02 07:32 UTC, Seldaek commented
@nicolas-grekas you said:

>> Symfony also urlencode's name, I don't see PHP do that.
> PHP should encode. Symfony does, that's OK.

This might be correct from a spec point of view, but FYI upgrading our app broke cookies with names "foo:bar:baz" as the : gets encoded and CloudFront's cookie whitelist does not recognize the encoded `foo%3Abar` as being the same cookie as `foo:bar` so the cookie gets dropped before reaching our servers. We could work around it but I wonder if this should be considered a regression or not.

2018-07-02 08:52 UTC, Seldaek commented
Also a related issue, clearCookie does not allow clearing cookies without urlencoding, so a cookie set without urlencoding can not be cleared.

2018-07-03 12:16 UTC, nicolas-grekas commented
@Seldaek I think we can fix these. WOuld you mind opening an issue?