[Console] Commands with an alias should not be recognized as ambiguous
symfony/symfony pull request #25357
Opened 2017-12-06 12:48 UTC by Simperfit

| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #25355 
| License       | MIT
| Doc PR        | 

I think when passing an alias, it should not be treated as a ambiguous command since it's configured to response to it.

I've [pushed a commit](https://github.com/Simperfit/symfony-reproducer/commit/2f5209a6876101a5f47ed589baa392d37e55aa40) that reproduce the bug and with this patch it does work.

2017-12-06 12:49 UTC, Simperfit commented
![img_2934](https://user-images.githubusercontent.com/3451634/33662495-3b901ce0-da8c-11e7-8a7e-0e014f738980.jpeg)

2017-12-07 12:42 UTC, chalasr commented
The issue here is that `Application::register()` does not allow to set aliases for the registered command (hence your test passes). Aliases registration happens in `Application::add()`, which is called by `register()` (before that `setAliases()` is even called) thus aliases are never added as keys of `Application::$commands`.

We can probably fix it by moving aliases registration to `find()/get()...`, I did not try to find a good implem yet but, to give a direction, the following patch fixes the issue:

```diff
diff --git a/src/Symfony/Component/Console/Application.php b/src/Symfony/Component/Console/Application.php
index 6ab9f01..1994712 100644
--- a/src/Symfony/Component/Console/Application.php
+++ b/src/Symfony/Component/Console/Application.php
@@ -499,7 +499,20 @@ class Application
     {
         $this->init();
 
+        foreach ($this->commands as $command) {
+            foreach ($command->getAliases() as $alias) {
+                if (!isset($this->commands[$alias])) {
+                    $this->commands[$alias] = $command;
+                }
+            }
+        }
+
         $allCommands = array_keys($this->commands);
+
+        if (\in_array($name, $allCommands, true)) {
+            return $this->get($name);
+        }
+
         $expr = preg_replace_callback('{([^:]+|)}', function ($matches) { return preg_quote($matches[1]).'[^:]*'; }, $name);
         $commands = preg_grep('{^'.$expr.'}', $allCommands);
 

```

Hope we can end up with something better :)

2018-01-21 16:41 UTC, nicolas-grekas commented
Status: needs work

2018-04-14 14:37 UTC, nicolas-grekas commented on src/Symfony/Component/Console/Application.php
> +        if (\in_array($name, $allCommands, true)) {
`if (isset($this->commands[$name]))`?

2018-04-20 08:44 UTC, nicolas-grekas requested changes

2018-04-20 08:44 UTC, nicolas-grekas commented on src/Symfony/Component/Console/Tests/ApplicationTest.php
> +        require_once self::$fixturesPath.'/TestTiti.php';
is this used at all? shouldn't the fixture be removed?

2018-04-20 08:44 UTC, nicolas-grekas commented on src/Symfony/Component/Console/Tests/ApplicationTest.php
> +        require_once self::$fixturesPath.'/TestToto.php';
a more descriptive name might be useful :)

2018-04-20 08:44 UTC, nicolas-grekas commented on src/Symfony/Component/Console/Tests/ApplicationTest.php
> +    public function testRegisterAmbiugous()
typo

2018-05-28 06:00 UTC, fabpot commented
Closing as there is no more activity.

2018-05-28 06:00 UTC, closed without merging

2019-04-26 06:25 UTC, Simperfit commented
@fabpot can you reopen it ? I will finish this, didn't had the time back then.

2019-04-26 06:29 UTC, nicolas-grekas commented
Please resubmit and link here.

2019-04-26 06:35 UTC, Simperfit commented
see https://github.com/symfony/symfony/pull/31261