[TwigBridge] Fix layout of submit_row in bootstrap_4_layout
symfony/symfony pull request #25668
Opened 2018-01-03 13:32 UTC by ttskch

| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

Fix default layout of submit button in `bootstrap_4_layout.html.twig` just like below.

| Before | After |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/4360663/34511237-5db35f9a-f09d-11e7-953a-f9820ab87f83.png) | ![image](https://user-images.githubusercontent.com/4360663/34511245-6aa830ae-f09d-11e7-9c84-29d9cfd8b2a3.png) |

2018-01-03 14:40 UTC, ostrolucky requested changes
Can you provide example code for reproducing this issue? We use this template with submit buttons and don't have such issue.

2018-01-16 19:17 UTC, nicolas-grekas commented
ping @ttskch

2018-01-26 13:54 UTC, xabbuh commented
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

2018-01-26 13:54 UTC, closed without merging

2018-02-13 14:38 UTC, ttskch commented
Sorry, I understood that it was my mistake. 
My twig.yaml was like below. In this is case, `submit_row` block is only in 'bootstrap_4_horizontal_layout.html.twig' so it was used contrary to expectation.

```
twig:
    form_themes:
        - 'bootstrap_4_horizontal_layout.html.twig'
        - 'bootstrap_4_layout.html.twig' # <- I expected only this is used
```

Thanks for your reviewing :pray: