Remove randomness from dumped containers
symfony/symfony pull request #25671
Opened 2018-01-03 16:17 UTC by nicolas-grekas

| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

With this PR, the generated container is immutable by cache clearing: it doesn't contain any random string anymore (well, third parties bundles can add random things back, but at least core doesn't).

Since the class+file name of the container is based on a hash of its content, it means that they are now stable also. This should help some fix some edge cases/race conditions during cache clears/rebuilds.

2018-01-03 22:09 UTC, nicolas-grekas commented on src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php
> +            (new Definition())->setFactory('filemtime')->addArgument($version),
hum actually this incurs unwanted IO, I need to look for something else

2018-01-04 11:01 UTC, nicolas-grekas commented
PR ready ((fabbot failure is false positive.)
This adds build metadata to dumped containers, that then can be and is referenced by bundles that need build time related entropy.

2018-01-04 12:36 UTC, nicolas-grekas commented
(failure caused by bug in Composer, see https://github.com/composer/composer/pull/6973)

2018-01-04 14:04 UTC, sroze commented
Could be retried now with the new release then :)

2018-01-04 14:28 UTC, nicolas-grekas commented
PR green (deps=high failure will be fixed by merging to upper branches)

2018-01-04 15:04 UTC, fabpot requested changes

2018-01-04 15:04 UTC, fabpot commented on src/Symfony/Bundle/FrameworkBundle/composer.json
> +        "symfony/dependency-injection": "~3.4.3|~4.0.3",
Shoudn't it be `^3.4.3|^4.0.3`

2018-01-04 15:07 UTC, nicolas-grekas commented on src/Symfony/Bundle/FrameworkBundle/composer.json
> +        "symfony/dependency-injection": "~3.4.3|~4.0.3",
oups, fixed

2018-01-04 15:31 UTC, fabpot approved these changes

2018-01-04 15:34 UTC, fabpot commented
Thank you @nicolas-grekas.

2018-01-04 15:42 UTC, fabpot commented
Thank you @nicolas-grekas.

2018-01-04 15:42 UTC, merged

2018-01-05 09:25 UTC, mcnilz commented
After updating to symfony 3.4.3 I get the following error:

```
In ParameterBag.php line 102:

  You have requested a non-existent parameter "container.build_id".
```

2018-01-05 09:27 UTC, nicolas-grekas commented
@mcnilz can you share a reproducer please? does this happen if you clear the cache manually?

2018-01-05 09:42 UTC, mcnilz commented
@nicolas-grekas yes on cache:clear and each request.
The stack trace is:

```

Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException: You have requested a non-existent parameter "container.build_id". in 
/app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php:102 
Stack trace: 
#0 /app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/EnvPlaceholderParameterBag.php(57): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->get('container.build...')
#1 /app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(133): Symfony\Component\DependencyInjection\ParameterBag\EnvPlaceholderParameterBag->get('container.build...') 
#2 /app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php(1243): Symfony\Component\DependencyInjection\Container->getParameter('container.build...') 
#3 /app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php(1196): Symfony\Component\DependencyInjection\ContainerBuilder-> in /app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php on line 102```

2018-01-05 09:44 UTC, nicolas-grekas commented
A service is used at compile time... Can you share the full stack trace please?

2018-01-05 09:51 UTC, mcnilz commented
```
In ParameterBag.php line 102:
                                                                                
  [Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException]  
  You have requested a non-existent parameter "container.build_id".             
                                                                                
Exception trace:
 Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->get() at /app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/EnvPlaceholderParameterBag.php:57
 Symfony\Component\DependencyInjection\ParameterBag\EnvPlaceholderParameterBag->get() at /app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:133
 Symfony\Component\DependencyInjection\Container->getParameter() at /app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:1243
 Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices() at /app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:1196
 Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices() at /app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:1109
 Symfony\Component\DependencyInjection\ContainerBuilder->createService() at /app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:1241
 Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices() at /app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:1196
 Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices() at /app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:1109
 Symfony\Component\DependencyInjection\ContainerBuilder->createService() at /app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:598
 Symfony\Component\DependencyInjection\ContainerBuilder->doGet() at /app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:1239
 Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices() at /app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:1196
 Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices() at /app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:1109
 Symfony\Component\DependencyInjection\ContainerBuilder->createService() at /app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:1241
 Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices() at /app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:1196
 Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices() at /app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:1109
 Symfony\Component\DependencyInjection\ContainerBuilder->createService() at /app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:1241
 Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices() at /app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:1196
 Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices() at /app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:1109
 Symfony\Component\DependencyInjection\ContainerBuilder->createService() at /app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:598
 Symfony\Component\DependencyInjection\ContainerBuilder->doGet() at /app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:1239
 Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices() at /app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:1196
 Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices() at /app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:1109
 Symfony\Component\DependencyInjection\ContainerBuilder->createService() at /app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:1241
 Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices() at /app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:1196
 Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices() at /app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:1196
 Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices() at /app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:1109
 Symfony\Component\DependencyInjection\ContainerBuilder->createService() at /app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:598
 Symfony\Component\DependencyInjection\ContainerBuilder->doGet() at /app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:563
 Symfony\Component\DependencyInjection\ContainerBuilder->get() at /app/vendor/jms/metadata/src/Metadata/Driver/LazyLoadingDriver.php:23
 Metadata\Driver\LazyLoadingDriver->loadMetadataForClass() at /app/vendor/jms/metadata/src/Metadata/MetadataFactory.php:103
 Metadata\MetadataFactory->getMetadataForClass() at /app/vendor/jms/security-extra-bundle/Security/Authorization/Interception/SecurityPointcut.php:84
 JMS\SecurityExtraBundle\Security\Authorization\Interception\SecurityPointcut->matchesMethod() at /app/vendor/jms/aop-bundle/DependencyInjection/Compiler/PointcutMatchingPass.php:149
 JMS\AopBundle\DependencyInjection\Compiler\PointcutMatchingPass->processDefinition() at /app/vendor/jms/aop-bundle/DependencyInjection/Compiler/PointcutMatchingPass.php:65
 JMS\AopBundle\DependencyInjection\Compiler\PointcutMatchingPass->process() at /app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/Compiler.php:141
 Symfony\Component\DependencyInjection\Compiler\Compiler->compile() at /app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:753
 Symfony\Component\DependencyInjection\ContainerBuilder->compile() at /app/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:634
 Symfony\Component\HttpKernel\Kernel->initializeContainer() at /app/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:137
 Symfony\Component\HttpKernel\Kernel->boot() at /app/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:63
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /app/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:148
 Symfony\Component\Console\Application->run() at /app/bin/console:28
```

maybe the JMS stuff

2018-01-05 09:54 UTC, mcnilz commented
Yes. If I disable JMSSecurityExtraBundle (just for testing) it works again.

2018-01-05 10:51 UTC, nicolas-grekas commented
ok, I can reproduce it.
@mcnilz can you please open a dedicated issue? comments on closed PRs cannot be tracked correctly.

2018-01-21 21:01 UTC, Tobion commented
@nicolas-grekas the proxy-manager uses deterministic proxy properties since https://github.com/Ocramius/ProxyManager/pull/385 but the proxy class name is still random between cache clears. This is because https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/ProxyManager/LazyProxy/PhpDumper/ProxyDumper.php#L105 uses `spl_object_hash` which does not stay the same between runs.  I tried to replace it with `\Symfony\Component\DependencyInjection\ContainerBuilder::hash` which indeed makes the container hash consistent. But something is still strange. The cache warmer get executed twice. So https://github.com/doctrine/DoctrineBundle/issues/763 might actually be a problem.