[TwigBundle] Register TwigBridge extensions first
symfony/symfony pull request #25756
Opened 2018-01-10 18:11 UTC by fancyweb

| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | https://github.com/symfony/symfony/issues/25610
| License       | MIT
| Doc PR        | -

The only extension that is really needed to display the current exception page is the `CodeExtension` so we could only prepend this one. However, prepending all of them seems safer to me in the long term.

Also I deeply looked into why this problem only appeared in 3.4 and found the reason. Before 3.4 it actually never reaches the `ExceptionController` for this kind of error because it cannot be resolved because it needs a twig instance in its constructor. This instance is directly taken from the container. Before 3.4 when an exception is thrown when you try to get a service from the container, the instance stored in the `$services` array is unset which is not the case in further versions. So in 3.4+, the `ExceptionController` can be resolved because the instance of twig is still in the container even after the initial exception.

It also means these kind of exceptions are displayed with bugs on all versions before 3.4 I guess. Actually it shows the message 2 times : one for the initial exception and the other one when it tries to resolve the `ExceptionController`.

Maybe another solution might be to use a dedicated twig instance with the right settings just for the exception page ?

2018-01-10 20:42 UTC, fabpot commented
I really like the idea of having a "safe" instance of Twig just for the profiler.

2018-01-11 08:11 UTC, xabbuh commented
I am not sure if having a safe Twig instance for the profiler is actually doable. We do not know what panels added by third-party libraries do require. The same is true for the exception controller. As soon as someone creates a custom exception page we cannot know anymore which Twig features they require there.

2018-02-04 15:05 UTC, nicolas-grekas requested changes
can you add a test case please?

2018-02-04 15:05 UTC, nicolas-grekas commented on src/Symfony/Bundle/TwigBundle/DependencyInjection/Compiler/TwigEnvironmentPass.php
> +            $methodCall = array(
I'd suggest to put this declaration on one line

2018-02-07 05:31 UTC, fabpot approved these changes

2018-02-07 05:32 UTC, fabpot commented
Thank you @fancyweb.

2018-02-07 05:34 UTC, closed without merging