[DependencyInjection] always call the parent class' constructor
symfony/symfony pull request #25762
Opened 2018-01-11 07:09 UTC by xabbuh

| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #25343
| License       | MIT
| Doc PR        |

2018-01-11 08:07 UTC, nicolas-grekas requested changes
This is a risky change: let's say the parent is customized: what if it has no constructor? or any args (less likely?)

2018-01-11 08:13 UTC, xabbuh commented
Could happen, but right now we already call the parent constructor if the container is not compiled. Not doing this for compiled containers leads to inconsistencies and to issues as described in the linked issue.

2018-01-11 08:21 UTC, nicolas-grekas commented
On the other hand, uncompiled container are not a thing, so their code path is mostly dead (we even removed it in 4.0.)

2018-01-11 08:25 UTC, xabbuh commented
Hm indeed, you are right about that. Should we do some reflection then and try to find out if there is a constructor that could be called instead?

2018-01-11 08:34 UTC, nicolas-grekas commented
Looks great yes. We should ensure that there is a constructor, and that it has zero mandatory args.

2018-01-11 08:35 UTC, nicolas-grekas commented
On 3.4 only? I'd prefer not change any behavior on 2.*

2018-01-18 12:03 UTC, nicolas-grekas commented on src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php
> +                $r = new \ReflectionClass($baseClassWithNamespace);
$container->getReflectionClass()?

2018-01-18 12:04 UTC, nicolas-grekas commented on src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php
> +                if ((null !== $constructor = $r->getConstructor()) && 0 === $constructor->getNumberOfRequiredParameters()) {
&& $baseClassWithNamespace !== Container::class

2018-01-18 12:05 UTC, nicolas-grekas commented on src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php
> +                if ((null !== $constructor = $r->getConstructor()) && 0 === $constructor->getNumberOfRequiredParameters()) {
`if (($constructor = $r->getConstructor()) && !$constructor->getNumberOfRequiredParameters() && $baseClassWithNamespace !== Container::class) {`?

2018-01-22 14:09 UTC, nicolas-grekas approved these changes

2018-01-29 20:31 UTC, 20uf approved these changes

2018-01-29 23:20 UTC, Taluu approved these changes

2018-02-04 11:00 UTC, nicolas-grekas commented
Thank you @xabbuh.

2018-02-04 11:00 UTC, merged