Fixed Request::__toString ignoring cookies
symfony/symfony pull request #25799
Opened 2018-01-15 15:23 UTC by Toflar

| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        | 

`Request::__toString()` ignored cookie values which caused me some headaches during a debugging session 😄

2018-01-15 15:28 UTC, phansys requested changes
Status: Needs work.

2018-01-15 15:28 UTC, phansys commented on src/Symfony/Component/HttpFoundation/Request.php
> +        if (0 !== count($cookies)) {
Please, use `!empty()` instead.

2018-01-15 15:30 UTC, Toflar commented on src/Symfony/Component/HttpFoundation/Request.php
> +        if (0 !== count($cookies)) {
Ah, I like type safety but fixed :-)

2018-01-15 15:35 UTC, stof approved these changes

2018-01-15 16:11 UTC, phansys approved these changes

2018-01-15 17:27 UTC, dunglas commented on src/Symfony/Component/HttpFoundation/Request.php
> +        foreach ($this->cookies as $k => $v) {
Maybe can yo do the concatenation directly instead of calling `implode later`?

2018-01-15 17:27 UTC, dunglas approved these changes

2018-01-16 07:04 UTC, fabpot commented
Thank you @Toflar.

2018-01-16 07:04 UTC, closed without merging