Update Repository Symlink Helper
symfony/symfony pull request #26091
Opened 2018-02-08 14:29 UTC by zanbaldwin

The `link` script is super-useful (thanks @dunglas!) for development - but for some it's unusable in its current form due to the use of `GLOB_BRACE` which is [unavailable on certain platforms](https://github.com/zendframework/zend-stdlib/issues/58#issue-147689568) (such as Alpine).

| Q             | A
| ------------- | ---
| Branch?       | `3.3`
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | No tests for `/link`
| Fixed tickets | 
| License       | MIT
| Doc PR        | can't find documentation for `/link`

2018-02-08 14:30 UTC, zanbaldwin commented on link
> +$directories = call_user_func_array('array_merge', array_values(array_map(function ($part) {
On the `4.0` branch and onwards (where PHP 5.6 support has been dropped) this line could be rewritten as:

```php
$directories = array_merge(...array_values(array_map(function (string $part): array {
```

2018-02-08 14:47 UTC, dunglas requested changes

2018-02-09 21:40 UTC, dunglas approved these changes

2018-02-11 11:15 UTC, nicolas-grekas commented
Thank you @zanbaldwin.

2018-02-11 11:15 UTC, closed without merging