[HttpFoundation] [WIP] Added a migrating session handler
symfony/symfony pull request #26096
Opened 2018-02-08 16:40 UTC by rossmotley

| Q             | A
| ------------- | ---
| Branch?       | master 
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no 
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        | n/a

- [ ] gather feedback for my changes
- [ ] submit changes to the documentation
- [ ] update the changelog

When migrating to a new session handler on a live system, it's useful to be able to do it with no loss of session data. This migrating handler allows the sessions to be written to an additional handler to enable a migration workflow like:

* Switch to migrating handler, with your new handler as the 'write only' one. The old handler behaves as usual and sessions get written to the new one.
* After verifying the data in the new handler (and after the session gc period), switch the migrating handler to use your old handler as the 'write only' one instead, so the sessions will now be read from the new handler. This step allows easier rollbacks.
* After verifying everything, switch from the migrating handler to the new handler

2018-02-11 19:04 UTC, Tobion commented
This sounds interesting. But this will only migrate sessions that are accessed. How do you deal with session data from currently inactive users? I guess you still need to manually transfer the data from the old storage to the new one for those. Or you just let them expire after the migration phase.

2018-02-11 23:01 UTC, rossmotley commented
Hi @Tobion, we leave the migrating handler running for at least the session garbage collection period, as any sessions which have not been written to during that time are considered stale and may be removed by the session handlers themselves.

2018-02-13 11:19 UTC, joshlopes approved these changes

2018-03-22 16:11 UTC, nicolas-grekas commented
@rossmotley is this PR ready on your side?

2018-03-26 08:45 UTC, rossmotley commented
@nicolas-grekas If there isn't anything to change with the code, then I think it's just adding something to the changelog and documentation. Should the changelog changes be added to this PR?

2018-03-26 08:48 UTC, nicolas-grekas commented
The changelog of the component yes (not the root changelog as it is autogenerated)
If you could start a documentation PR, that'd be awesome.
ping @Tobion if you have some time for the review

2018-03-28 16:27 UTC, 20uf approved these changes

2018-03-31 23:03 UTC, Tobion requested changes
Some CS error but otherwise looks ok

2018-03-31 23:03 UTC, Tobion commented on src/Symfony/Component/HttpFoundation/Session/Storage/Handler/MigratingSessionHandler.php
> +     * @param \SessionHandlerInterface $writeOnlyHandler
this doc useless and should be removed

2018-03-31 23:03 UTC, Tobion commented on src/Symfony/Component/HttpFoundation/Session/Storage/Handler/MigratingSessionHandler.php
> +        $result = $this->currentHandler->read($session_id);
no need for `$result` variable

2018-03-31 23:03 UTC, Tobion commented on src/Symfony/Component/HttpFoundation/Tests/Session/Storage/Handler/MigratingSessionHandlerTest.php
> +    public function setUp()
this should be protected

2018-03-31 23:03 UTC, Tobion commented on src/Symfony/Component/HttpFoundation/Tests/Session/Storage/Handler/MigratingSessionHandlerTest.php
> +        $this->currentHandler = $this->getMockBuilder(\SessionHandlerInterface::class)
you can just use `createMock` here

2018-03-31 23:03 UTC, Tobion commented on src/Symfony/Component/HttpFoundation/Session/Storage/Handler/MigratingSessionHandler.php
> +    public function destroy($session_id)
we use camelCase naming. please change the variable names

2018-03-31 23:03 UTC, Tobion commented on src/Symfony/Component/HttpFoundation/Tests/Session/Storage/Handler/MigratingSessionHandlerTest.php
> +        $data = array('zfa' => 'hwq');
the data passed to `write` is not meant to be an array, but a string

2018-04-05 17:18 UTC, rossmotley commented
@Tobion I have made the requested changes

2018-04-06 05:58 UTC, fabpot approved these changes

2018-04-06 05:59 UTC, fabpot commented
Thank you @rossmotley.

2018-04-06 05:59 UTC, merged