Add watch option to lint commands
symfony/symfony pull request #26120
Opened 2018-02-09 14:49 UTC by pierredup

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no 
| Tests pass?   | yes
| Fixed tickets | N/A
| License       | MIT
| Doc PR        | TDB

This PR actually has 2 parts:

* Add a `watch` method to the Filesystem component to monitor the filesystem for changes, and executing a callback function whenever a change is detected

The watch method can take any parameter and uses a resource locator to transform a path to a resource. The resource can then be monitored for any changes. When a directory is monitored, you can get changed events when a file in the directory changes, when a new file is created or when an existing file is deleted. It also tried to make usage of Inotify is the extension is installed.

Example usage:

```php
$fs = new Filesystem();

$fs->watch('/path/to/some/directory', function ($file, $event) {
    if ($event === FileChangeEvent::FILE_CREATED) {
        echo $file.' was created!';
    }
});
```

* Add a watch option to all the lint commands

When he `watch` option is used, the process will monitor the filesystem for any changes. When a change is detected, the changed file will be re-validated and the output printed to the console.

2018-02-09 15:17 UTC, Simperfit commented on src/Symfony/Component/Filesystem/Tests/Watcher/Resource/ArrayResourceTest.php
> +/*
this should be changed

2018-02-09 15:18 UTC, Simperfit commented on src/Symfony/Component/Filesystem/Tests/Watcher/Resource/ArrayResourceTest.php
> +declare(strict_types=1);
we don't use strict_types atm in the codebase ATM

2018-02-09 15:19 UTC, Simperfit commented on src/Symfony/Bridge/Twig/Command/LintCommand.php
> +        $io->note('Watching files for changes');
Maybe a final dot or a `...` ?

2018-02-09 15:25 UTC, sroze commented
It might be worth opening an RFC issue to identify whether this makes sense to include this in Symfony. I would argue it is but still, it needs to be discussed :)

2018-02-11 13:53 UTC, Koc commented
What about splitting PR to two parts: first for adding watching for filesystem, second for lint commands?

2018-02-14 12:19 UTC, nicolas-grekas commented on src/Symfony/Component/Translation/CHANGELOG.md
> + * Added `--watch` option to the `lint:twig` command to watch the filesystem for changes and re-lint any changed files
lint:xliff

2018-02-19 12:31 UTC, nicolas-grekas commented
Would it make sense to have a single new `lint` command that would look at extensions to decide the format of the file, and would be the only one having --watch, to make things simpler?

2018-03-20 10:02 UTC, ostrolucky commented
I'm for having single command, but what's the best location to have it in? FileSystem component?

2018-03-20 10:08 UTC, ostrolucky requested changes
composer.json files need to be changed

2018-03-20 10:13 UTC, pierredup commented
> composer.json files need to be changed

@ostrolucky What must be changed?

2018-03-20 10:18 UTC, ostrolucky commented
they miss symfony/filesystem dependency requirement

2019-05-10 09:56 UTC, pierredup commented
Going through this PR again, I don't think adding a watch option for lint commands is a good use case. But the `watch` method in the Filesystem component is still very useful, so I rather extracted that to a separate PR in #31462

2019-05-10 09:56 UTC, closed without merging