Add ControllerTrait::createNamedFormBuilder method
symfony/symfony pull request #26162
Opened 2018-02-13 10:08 UTC by Soullivaneuh

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | N/A
| License       | MIT

A long time ago, you merged #2936 to allow empty root form name with the builder.

The issue is, if we want to do that from the controller, we can't use `createFormBuilder` because it will create a named form with the form type block prefix.

So we currently have to use the FactoryService.

This PR adds a `createNamedFormBuilder` to allows empty root form name builder with simplicity.

2018-02-13 10:54 UTC, jakzal requested changes

2018-02-13 10:54 UTC, jakzal commented on src/Symfony/Bundle/FrameworkBundle/Controller/ControllerTrait.php
> +    protected function createNamedFormBuilder(string $name, $data = null, array $options = array()): FormBuilderInterface
`$name` is not used anywhere.

2018-02-13 11:00 UTC, Soullivaneuh commented on src/Symfony/Bundle/FrameworkBundle/Controller/ControllerTrait.php
> +    protected function createNamedFormBuilder(string $name, $data = null, array $options = array()): FormBuilderInterface
Ooops!

2018-02-13 11:01 UTC, Soullivaneuh commented on src/Symfony/Bundle/FrameworkBundle/Controller/ControllerTrait.php
> +    protected function createNamedFormBuilder(string $name, $data = null, array $options = array()): FormBuilderInterface
@jakzal Fixed.

2018-02-14 12:32 UTC, Simperfit approved these changes

2018-02-14 12:36 UTC, nicolas-grekas commented on src/Symfony/Bundle/FrameworkBundle/Controller/ControllerTrait.php
> +     * @final since version 4.1
just `@final` (we should add the version only for existing methods that are *made* final)

2018-02-14 12:37 UTC, nicolas-grekas approved these changes
(with minor comment)

2018-02-14 14:46 UTC, Tobion commented
I'm rather -1 on adding this. The use-case is very special and most people don't need it. But adding such a method will confuse people which method to use. Also the method does not provide any logic expect adding one layer of indirection.

2018-02-15 13:04 UTC, Soullivaneuh commented
> The use-case is very special and most people don't need it

I do not really agree. No prefix form are usual, especially for GET methods.

2018-03-19 17:23 UTC, nicolas-grekas commented
Closing here as this did not reach consensus. Sorry @Soullivaneuh

2018-03-19 17:23 UTC, closed without merging

2018-05-31 08:48 UTC, Soullivaneuh commented
Well, I still think the usage is justified, but ok. You have the diff if you change your mind. :+1: