[Translation] Process multiple segments within a single unit.
symfony/symfony pull request #26247
Opened 2018-02-20 17:55 UTC by timewasted

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        | 

Xliff 2.0 supports multiple segments within a single unit, but the
loader was only processing the first segment.  The loader will now
correctly process all segments within a unit.

2018-02-20 20:34 UTC, phansys requested changes
Status: Needs work.

2018-02-20 20:34 UTC, phansys commented on src/Symfony/Component/Translation/Tests/Loader/XliffFileLoaderTest.php
> +        $this->assertEquals('en', $catalog->getLocale());
Please, whenever possible, use `assertSame()` instead.

2018-02-21 10:49 UTC, nicolas-grekas commented
Best review [ignoring whitespace](https://github.com/symfony/symfony/pull/26247/files?w=1).
@Nyholm OK for you?

Status: needs review

2018-02-21 11:09 UTC, Nyholm approved these changes
According to [specification](http://docs.oasis-open.org/xliff/xliff-core/v2.0/os/xliff-core-v2.0-os.html#unit) you may have one or more segments in a `unit`. The implementation looks good.

2018-02-21 11:11 UTC, phansys approved these changes

2018-02-21 11:19 UTC, phansys requested changes

2018-02-21 18:21 UTC, Simperfit approved these changes

2018-02-22 06:27 UTC, fabpot approved these changes

2018-02-22 06:28 UTC, fabpot commented
Thank you @timewasted.

2018-02-22 06:28 UTC, closed without merging