Document the container.autowiring.strict_mode option
symfony/symfony pull request #26251
Opened 2018-02-21 08:03 UTC by B-Galati

| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | https://github.com/symfony/symfony-docs/issues/8561
| License       | MIT
| Doc PR        | no

Hello,

Let me know for any misunderstanding from my part  or rewording

2018-02-21 10:39 UTC, nicolas-grekas approved these changes

2018-02-21 12:58 UTC, ro0NL commented on UPGRADE-4.0.md
> +     container.autowiring.strict_mode: true
indent by 4 spaces for consistence :)

2018-02-21 14:35 UTC, dunglas approved these changes

2018-02-21 17:46 UTC, fabpot requested changes

2018-02-21 17:46 UTC, fabpot commented on UPGRADE-4.0.md
> +   In 3.4, you can activate this behavior instead of having deprecation messages by setting the following parameter :
extra space before `:` to be removed.

2018-02-21 17:46 UTC, fabpot commented on UPGRADE-4.0.md
> +   From 4.0, you can remove it as it's the default behavior and the parameters is not handled anymore.
typo: parameter instead of parameters.

2018-02-21 17:46 UTC, fabpot commented on UPGRADE-4.0.md
> +   It will only look for an alias or a service id that matches a given FQCN. Rename (or alias) your services to their FQCN id to make them autowirable.
Can you wrap at 80 chars?

2018-02-21 21:16 UTC, B-Galati commented
@fabpot @ro0NL Done, thank you !

2018-02-21 23:03 UTC, Tobion approved these changes

2018-02-22 06:16 UTC, fabpot approved these changes

2018-02-22 06:17 UTC, fabpot commented
Thank you @B-Galati.

2018-02-22 06:17 UTC, merged