[Security][Profiler] Display the original expression in 'Access decision log'
symfony/symfony pull request #26273
Opened 2018-02-22 17:18 UTC by lyrixx

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #24127
| License       | MIT
| Doc PR        |

2018-02-22 17:30 UTC, stof commented
I suggest *also* adding my patch from https://github.com/symfony/symfony/issues/24127#issuecomment-367317851 (the second one), to use `profiler_dump(first)` when `first` represents a non-string value, instead of displaying the string-casting of the Data object (the class name with the number of property in it is totally useless).

We might even consider this as a bugfix.

2018-02-22 17:31 UTC, stof requested changes

2018-02-22 17:31 UTC, stof commented on src/Symfony/Bundle/SecurityBundle/Resources/views/Collector/security.html.twig
> +                                    Expression: <code><pre>{{ first.expression }}</pre></code>
should be `<pre><code></code></pre>` as `<code>` is an inline element while `<pre>` is a block element.

2018-02-22 17:44 UTC, lyrixx commented
@stof  I addressed your comments.

2018-02-23 06:53 UTC, Simperfit approved these changes

2018-02-25 12:58 UTC, fabpot commented
Looks like a bug fix to me, no?

2018-02-28 08:34 UTC, lyrixx commented
I have rebased my branch onto 3.4, and changed the base branch for this PR in order to merge it as a bug fix.

2018-03-02 14:19 UTC, chalasr approved these changes

2018-03-19 17:02 UTC, nicolas-grekas approved these changes

2018-03-19 17:03 UTC, nicolas-grekas commented
Thank you @lyrixx.

2018-03-19 17:03 UTC, merged