[FrameworkBundle] show the unregistered command warning at the end of the list command
symfony/symfony pull request #26288
Opened 2018-02-23 14:13 UTC by Simperfit

| Q             | A
| ------------- | ---
| Branch?       | 4.1
| Bug fix?      | no
| New feature?  | yes   
| BC breaks?    | no     
| Deprecations? | no   
| Tests pass?   | yes    
| Fixed tickets | #26203  
| License       | MIT
| Doc PR        | I don't think we need one.

2018-02-23 14:50 UTC, chalasr requested changes

2018-02-23 14:50 UTC, chalasr commented on src/Symfony/Bundle/FrameworkBundle/Console/Application.php
> +        $parentRun = parent::doRunCommand($command, $input, $output);
this actually runs the command thus writes to the output no matter which command is ran, not good, should be called at the right place

2018-02-23 15:50 UTC, Simperfit commented
Status: Needs Review

2018-02-24 19:43 UTC, chalasr approved these changes

2018-03-02 12:19 UTC, Simperfit commented
PR rebased

2018-03-10 20:23 UTC, fabpot commented
Looks like some tests do not pass as a consequence of this change.

2018-03-14 14:17 UTC, chalasr approved these changes

2018-03-15 16:34 UTC, fabpot approved these changes

2018-03-15 16:36 UTC, fabpot commented
Thank you @Simperfit.

2018-03-15 16:36 UTC, merged