Update ProgressBar.php
symfony/symfony pull request #26426
Opened 2018-03-06 10:44 UTC by CurvesFR

Fix unexpected character on windows systems, fix https://github.com/symfony/symfony/issues/23920

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no 
| BC breaks?    | no     
| Deprecations? | no 
| Fixed tickets | #23920   
| License       | MIT

This line cause an unexpected character on windows systems, and doesn't seems to be needed, because the progress line is already deleted (tested on MacOS 10.13.3, Windows 7 and Windows 10)

2018-03-06 11:34 UTC, Simperfit commented
Could you please look why the tests are failing it seems linked to this change.

2018-03-07 19:12 UTC, ostrolucky requested changes
Deleted code is necessary to make sure line is erased in case output before was lengthier than output in following steps. See following example

```php
$bar = new ProgressBar($output, 100);
        $bar->setFormat("%bar%\n%custom%");
        ProgressBar::setPlaceholderFormatterDefinition('custom', function(ProgressBar $progressBar) {
        	if ($progressBar->getProgress() < 50) {
        		return 'loremipsumloremipsun';
			}

			return 'foo';
		});
        $bar->start();

        for ($i=0; $i<=100; $i++) {
			$bar->advance();
			usleep(100000);
		}
```

Result with your patch would result into following output https://asciinema.org/a/PJRuVEAAEb3EnNDAPzvHb9ftg

2018-03-08 09:18 UTC, chalasr commented
we need to find the right equivalent on windows

2018-03-08 11:44 UTC, Destroy666x commented
AFAIK Windows < 10 doesn't have a built-in solution. It could be done with `\r` and overwriting the whole bar though.

2018-03-14 16:31 UTC, nicolas-grekas commented
> It could be done with \r and overwriting the whole bar though

@CurvesFR could you try this solution, on Windows only?

2018-03-30 23:25 UTC, ostrolucky commented
This is not a correct solution, referenced issue is unconfirmed and OP does not respond. I suggest closing...

2018-03-31 05:16 UTC, fabpot commented
I'm going to close this pull request as removing this code is not possible and from reading the comments, the bug does not seem confirmed (or at least, we don't know yet when this issue occurs precisely).

2018-03-31 05:16 UTC, closed without merging