[Debug] Allow flatten throwable
symfony/symfony pull request #26447
Opened 2018-03-07 20:11 UTC by instabledesign

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #26429
| License       | MIT

Allow Throwable to be Flatten.

2018-03-07 20:24 UTC, ostrolucky requested changes
This is BC break. Please read Symfony BC promise. Correct solution is to create new class and deprecate this one.

2018-03-12 20:58 UTC, nicolas-grekas commented
Is this required? The Debug component converts `Error` to FatalErrorException`, so that this has never been required before. What's your use case?

2018-03-12 21:38 UTC, instabledesign commented
I have a consumer with `try` `catch(\Throwable)` and i want to send by mail the flatten exception.
For the moment i'll add 
```php
if (!$exception instanceof \Exception) {
    $exception = new FatalThrowableError($exception);
}
$flattenException = FlattenException::create($exception)->toArray();
```

but why dont allow?

2018-03-13 11:00 UTC, derrabus commented
I already felt like doing this when working on #26028, but I decided against it because of the BC break @ostrolucky mentioned. Right now, `Error` objects are converted to `FatalThrowableError` in order to not break the interface of the `FlattenException` class. But apart from that, there are no technical reasons to perform that conversion.

Allowing `FlattenException` to work with `Throwable` instances would improve the overall utility of that class and remove technical debt.

2018-03-13 11:06 UTC, derrabus requested changes
This block can probably be simplified now:

https://github.com/instabledesign/symfony/blob/d79c528b400eaeecc53e97cc4c5f3cbf7df33650/src/Symfony/Component/Debug/Exception/FlattenException.php#L60-L66

2018-03-13 11:06 UTC, derrabus commented on src/Symfony/Component/Debug/Exception/FlattenException.php
> +    public static function create(\Throwable $exception, $statusCode = null, array $headers = array())
This change will break applications that extend this class and override the `create` method.

2018-03-13 11:06 UTC, derrabus commented on src/Symfony/Component/Debug/Exception/FlattenException.php
> +    public function setTraceFromException(\Throwable $exception)
This is a BC break for the same reasons.

2018-03-13 11:10 UTC, derrabus commented
Backwards-compatible solutions could be:

* Deprecate `FlattenException` in favor of a new `FlattenThrowable` class. That's a lot of work because `FlattenException` is used quite often.
* Remove the `\Exception` type-hints and add `\Throwable` type-hints in Symfony 5.

2018-03-14 16:27 UTC, nicolas-grekas commented
Closing in favor of #26528, which is more advanced now. Thank you @instabledesign for raising the topic.

2018-03-14 16:27 UTC, closed without merging

2018-03-15 14:20 UTC, instabledesign commented
pwned my first contribution :'(

2018-03-15 14:27 UTC, sroze commented
Don't give up, next time will be better 😉

2018-03-15 14:32 UTC, derrabus commented
I'm really sorry for that, @instabledesign. I should've waited a couple more days, I suppose. 😓

I just wanted to slip this in before the feature freeze.