[FrameworkBundle] add a parameter for the debug production log level
symfony/symfony pull request #26504
Opened 2018-03-13 08:33 UTC by Simperfit

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes 
| BC breaks?    | no     
| Deprecations? | no 
| Tests pass?   | yes    
| Fixed tickets | #26267   
| License       | MIT
| Doc PR        |  todo 

We are adding a new paremeter `debug.error_handler.log_at` (set the value of the log level you want).
This fixes #26267, so it gives a way to not log some level on production.

2018-03-13 10:01 UTC, nicolas-grekas commented
would be great to turn the `framework.php_errors.log` config entry into a "bool|int", and when an "int" is provided, use the value to set the parameter

2018-03-14 11:34 UTC, Simperfit commented
@nicolas-grekas I have changed this PR, could you please guide me on how to write test for this ?

2018-03-14 16:17 UTC, nicolas-grekas requested changes
for tests, please check the existing ones, I don't have specific ideas on the topic sorry

2018-03-14 16:17 UTC, nicolas-grekas commented on src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php
> +        if (\is_bool($config['log']) && !$config['log']) {
`if (!$config['log']) {` is enough: `0` also disables the logger

2018-03-14 16:17 UTC, nicolas-grekas commented on src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php
> +        if (\is_int($config['log'])) {
if (\is_int($config['log']) && $config['log']) {

2018-03-14 16:17 UTC, nicolas-grekas commented on src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php
> +                        ->scalarNode('log')
maybe forbid anything else than a bool|int?

2018-03-26 06:33 UTC, Simperfit commented
Status: Needs Review

2018-03-26 06:33 UTC, Simperfit commented on src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php
> +                        ->scalarNode('log')
done

2018-03-26 06:47 UTC, nicolas-grekas approved these changes

2018-03-26 15:08 UTC, Simperfit commented
Tests Fixed.

2018-03-27 07:40 UTC, fabpot requested changes

2018-03-27 07:40 UTC, fabpot commented on src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php
> +                            ->thenInvalid('The "php_errors.log" parameter should be either a int or a boolean.')
`either an integer or a boolean`?

2018-03-27 07:47 UTC, Simperfit commented on src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php
> +                            ->thenInvalid('The "php_errors.log" parameter should be either a int or a boolean.')
@fabpot updated.

2018-03-27 07:47 UTC, fabpot requested changes

2018-03-27 07:47 UTC, fabpot commented on src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php
> +                            ->thenInvalid('The "php_errors.log" parameter should be either a integer or a boolean.')
an integer :)

2018-03-27 14:40 UTC, Simperfit commented on src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php
> +                            ->thenInvalid('The "php_errors.log" parameter should be either a integer or a boolean.')
This is good now :p.

2018-03-27 18:28 UTC, fabpot commented
Thank you @Simperfit.

2018-03-27 18:28 UTC, merged

2018-05-29 09:49 UTC, bendavies commented on src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php
>                              ->info('Use the app logger instead of the PHP logger for logging PHP errors.')
is this really descriptive now?

2019-05-23 08:48 UTC, mathieu-pousse commented
Hi, 

This PR looks great to me, but I am not sure to ensure the aim.
Does  the log level behind the scene correspond to something like 'E_ALL & ~E_DEPRECATED & ~E_USER_DEPRECATED & ~E_STRICT' or to DEVUG, INFO, WARN, ?

In any case, I think this should be explain in the documentation

2020-01-09 04:50 UTC, SublimeRaiser commented
> This PR looks great to me, but I am not sure to ensure the aim.
> Does the log level behind the scene correspond to something like 'E_ALL & ~E_DEPRECATED & ~E_USER_DEPRECATED & ~E_STRICT' or to DEVUG, INFO, WARN, ?
> 
> In any case, I think this should be explain in the documentation

Here is a link to the docs: [https://symfony.com/doc/current/reference/configuration/framework.html#log](https://symfony.com/doc/current/reference/configuration/framework.html#log)