[HttpFoundation] Replace private static variable with private constan…
symfony/symfony pull request #26511
Opened 2018-03-13 15:46 UTC by a-s-y-n-c

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no 
| BC breaks?    | no     
| Deprecations? | no 
| Tests pass?   | yes    
| Fixed tickets | 
| License       | MIT
| Doc PR        | 

Hi. I am completely new so sorry for any inconvenience I might have caused.

Now that private constants are allowed since PHP 7.1, I thought they might be better suited for the job of storing an array of file keys.

If you disagree, feel free to close the PR. In such case, I would like to learn why you consider private static variables a better solution.

Thank you very much for your replies and feedback.

2018-03-13 16:43 UTC, ostrolucky requested changes
this can be done only when support for php < 7.1 is dropped. There is still support for older symfony versions and this change complicates merging process for no real benefit

2018-03-14 07:32 UTC, iltar commented
Considering this change is in the master:

https://github.com/symfony/symfony/blob/9e82562948253bf547243aa1c4cf6ec734d608da/composer.json#L19

So it looks good to me. Perhaps it's even possible to do this for 4.0?

2018-03-14 09:29 UTC, derrabus commented
@iltar This change would be okay for master, but as @ostrolucky pointed out, changes like this would give whoever merges the LTS branches upwards a hard time. For instance, we still use the traditional array syntax in the Symfony codebase for the same reason. Considering that we don't gain anything but more php7ish code, I'd be careful with that change.

> Perhaps it's even possible to do this for 4.0?

👍 If the change is accepted, it should go to the 4.0 branch.

2018-03-14 09:32 UTC, iltar commented
@derrabus 4.0 is not an LTS and supports `7.1.3` as minimum version. Also, it's not about the short array syntax, this hasn't changed, it's about a private static property (that doesn't change its value) being changed to a private constant, which should provide some micro optimizations.

2018-03-14 09:49 UTC, derrabus commented
@iltar But 2.7 is an LTS and the class contains the very same line in that branch. We can neither use array constants nor private constants in 2.7.

If we decide to refactor private static array fields to private constants, we create differences that might conflict when merging later changes from 2.7/2.8/3.4 to 4.x and master.

I'm not opposing this PR is general since I'd always prefer private constants over private static array fields when writing new code. But to keep merging easy, my suggestion would be: Introducing private constants in new code is fine, but don't refactor static array fields (yet).

2018-03-14 09:52 UTC, iltar commented
While you are right about that and it will make merging an issue, imo it should not be a reason to keep the code-base dated.

2018-03-14 10:51 UTC, nicolas-grekas commented
Hello, thanks for your proposal. Yet, I'm going to close it, for the reason given by @derrabus: this would create merge conflicts we'd better avoid. Note also that we prefer doing such changes for the full code base at once - vs class by class or component by component. Waiting your next PR :)

2018-03-14 10:51 UTC, closed without merging