[Bridge\PhpUnit] Fix #26430 Cannot autoload class "\Symfony\Bridge\Ph…
symfony/symfony pull request #26562
Opened 2018-03-16 12:49 UTC by yakobe

…pUnit\SymfonyTestsListener"

| Q             | A
| ------------- | ---
| Branch?       | 3.4 
| Bug fix?      | yes
| New feature?  | no 
| BC breaks?    | no     
| Deprecations? | no 
| Tests pass?   | yes    
| Fixed tickets | #26430
| License       | MIT
| Doc PR        | - 

Allows composer to discover the class for autoloading when using `composer install --classmap-authoritative`

2018-03-16 13:41 UTC, derrabus approved these changes

2018-03-16 15:38 UTC, nicolas-grekas requested changes

2018-03-16 15:38 UTC, nicolas-grekas commented on src/Symfony/Bridge/PhpUnit/SymfonyTestsListener.php
> +if (false){
missing space after closing bracket

2018-03-16 15:38 UTC, nicolas-grekas commented on src/Symfony/Bridge/PhpUnit/SymfonyTestsListener.php
> +    class SymfonyTestsListener{}
please put `{}` on separate lines
```
class SymfonyTestsListener
{
}
```

2018-03-16 15:39 UTC, nicolas-grekas commented
`CoverageListener` also should get the same fix

2018-03-16 16:31 UTC, yakobe commented
Updated

2018-03-16 16:47 UTC, nicolas-grekas approved these changes

2018-03-19 10:29 UTC, yakobe commented
The build failed with `appveyor`, so i rebased with latest changes and built again. Now it fails with `travis-ci`. The fails have nothing to do with this change.
@nicolas-grekas are they just a bit fragile? Do i need to do anything else?

2018-03-19 14:48 UTC, nicolas-grekas commented
Thank you @yakobe.

2018-03-19 14:48 UTC, merged

2018-03-19 15:03 UTC, yakobe commented
Thank you @nicolas-grekas ! Now i can use it :)