[Console] Set `box` style table as default
symfony/symfony pull request #26596
Opened 2018-03-19 10:07 UTC by maidmaid

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | https://github.com/symfony/symfony/pull/25456#pullrequestreview-103410254
| License       | MIT
| Doc PR        | /

2018-03-19 12:50 UTC, nicolas-grekas submitted a review, later dismissed

2018-03-19 12:50 UTC, ogizanagi approved these changes

2018-03-19 12:52 UTC, nicolas-grekas commented
Can anyone actually try on Windows? Because here, this is UTF-8, but these require CP437, which we do not output AFAIK.

2018-03-19 12:55 UTC, ogizanagi commented
I thought it was [already tested on Windows](https://github.com/symfony/symfony/pull/25456#issuecomment-372977133). But indeed, a confirmation would be great.

2018-03-21 09:43 UTC, nicolas-grekas requested changes
I confirm unicode characters are not supported on `cmd.com`. It works with the xterm one. What could work on both Linux and Windows is using `box` when `preg_match('/utf-?8/i', getenv('LANG'))`.

2018-03-21 09:43 UTC, nicolas-grekas commented on src/Symfony/Component/Console/Helper/Table.php
> +            @trigger_error(sprintf('Style symfony-style-guide is deprecated since Symfony 4.1.', __METHOD__), E_USER_DEPRECATED);
The "box" style doesn't work on Windows `cmd.com` terminal, so we cannot deprecate `symfony-style-guide`.

2018-03-22 08:24 UTC, nicolas-grekas commented
No need to deprecate IMHO, the symfony-style-guide is still visually nice.

2018-03-22 08:27 UTC, fabpot commented
Ah, I didn't realize that the default Symfony theme is not the console default. I would say that we don't need to change anything then. The current default looks great as is and works everywhere. Sorry for asking for a change, I should have checked what we were using first.

2018-03-22 08:51 UTC, maidmaid commented
IMO, the `box` style allows the best readability of a table thanks to full lines. It would be nice to use it when possible (as suggested by @nicolas-grekas).

My new suggestion is to use the `box` style when possible, and use `symfony-style-guide` as a workaround when this first one can't work.

2018-03-25 08:44 UTC, fabpot commented
I like consistency. So, I'd recommend to close this PR. Sorry for making you work on this one. My mistake.

2018-03-28 12:19 UTC, chalasr commented
👍 to close

2018-03-28 14:01 UTC, closed without merging