Improved the lint:xliff command
symfony/symfony pull request #26682
Opened 2018-03-27 09:23 UTC by javiereguiluz

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #26537
| License       | MIT
| Doc PR        | -

This is how it looks:

![lint-xliff-output](https://user-images.githubusercontent.com/73419/37958502-fd8732e0-31b0-11e8-8688-8644ca930daf.png)

2018-03-27 09:29 UTC, stloyd requested changes

2018-03-27 09:29 UTC, stloyd commented on src/Symfony/Component/Translation/Command/XliffLintCommand.php
> +    private function getTargetLanguageFromFile($xliffContents)
```php
    private function getTargetLanguageFromFile(\DOMDocument $xliffContents): ?string
    {
        foreach ($xliffContents->getElementsByTagName('file')[0]->attributes ?? array() as $attribute) {
            if ('target-language' === $attribute->nodeName) {
                return $attribute->nodeValue;
            }
        }

        return null;
    }
```

2018-03-27 10:36 UTC, stof requested changes

2018-03-27 10:36 UTC, stof commented on src/Symfony/Component/Translation/Command/XliffLintCommand.php
> +            $errors[] = array_map(function ($error) {
are you sure about it ? This will add an array of errors a a single entry in `$errors`. This looks weird to me

2018-03-27 10:36 UTC, stof commented on src/Symfony/Component/Translation/Command/XliffLintCommand.php
> +            $errors[] = array_map(function ($error) {
btw, your new test does not seem to cover this code path

2018-03-28 06:11 UTC, fabpot requested changes

2018-03-28 06:11 UTC, fabpot commented on src/Symfony/Component/Translation/Command/XliffLintCommand.php
> +        return array('file' => $file, 'valid' => empty($errors), 'messages' => $errors);
Can you avoid using `empty()` here?

2018-03-29 08:44 UTC, stof requested changes

2018-03-29 08:44 UTC, stof commented on src/Symfony/Bundle/FrameworkBundle/Tests/Command/XliffLintCommandTest.php
> +class XliffLintCommandTest extends TestCase
This test should go in the component, as the command is in the component (well, we may need to have 2 different tests). This should fix the deps=low build too, by having the test for the new feature in the same package than the feature itself.

2018-03-29 15:03 UTC, stof approved these changes

2018-03-30 08:38 UTC, fabpot approved these changes

2018-03-30 08:39 UTC, fabpot commented
Thank you @javiereguiluz.

2018-03-30 08:40 UTC, merged