[MonologBridge] Added WebSubscriberProcessor to ease processor configuration
symfony/symfony pull request #26832
Opened 2018-04-06 10:21 UTC by lyrixx

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets |
| License       | MIT
| Doc PR        |

---

Side note: I could be nice to have an interface to act as the marker to AutoConfigure processors

2018-04-22 06:39 UTC, fabpot requested changes

2018-04-22 06:39 UTC, fabpot commented on src/Symfony/Bridge/Monolog/CHANGELOG.md
> + * Added `WebSubscriberProcessor` to be easily autoconfigured
I don't understand the meaning of this sentence. What is easily configured?

2018-04-22 06:39 UTC, fabpot commented on src/Symfony/Bridge/Monolog/Processor/WebSubscriberProcessor.php
> + * WebProcessor override to read from the HttpFoundation's Request and to be autoconfigured.
Sorry, but I don't understand what that means as well (I see that you copy/pasted the one from WebProcessor, but the second part is quite cryptic to me).

2018-04-23 09:38 UTC, fabpot approved these changes
minor CS comment

2018-04-23 09:55 UTC, lyrixx commented
> minor CS comment

@fabpot I don't see your comments :/

2018-04-23 09:58 UTC, fabpot commented on src/Symfony/Bridge/Monolog/CHANGELOG.md
> + * `WebProcessor` now implements EventSubscriberInterface in order to be easily autoconfigured
missing quotes around EventSubscriberInterface

2018-04-23 10:08 UTC, lyrixx commented on src/Symfony/Bridge/Monolog/CHANGELOG.md
> + * `WebProcessor` now implements EventSubscriberInterface in order to be easily autoconfigured
Fixed

2018-04-23 11:44 UTC, fabpot commented
Thank you @lyrixx.

2018-04-23 11:45 UTC, merged