Add d-block to bootstrap 4 alerts
symfony/symfony pull request #26870
Opened 2018-04-09 13:01 UTC by normisg

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no     
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 26869
| License       | MIT
| Doc PR        | symfony/symfony-docs#...

2018-04-11 08:48 UTC, chapterjason commented
Is there any reason why a `span` is used to display the alerts? When I look at the docs of bootstrap, I can clearly see that the `div` tag are used for that.

https://getbootstrap.com/docs/4.0/components/alerts/

Using `d-block` is for me really odd.

2018-04-11 09:01 UTC, normisg commented
Yes, it was changed in https://github.com/symfony/symfony/commit/5dcaaadb5e8c01148b67d009c95a5118849f9a55 to "Make sure form errors is valid HTML".
Seems unnecessary to me too.

2018-04-11 22:26 UTC, vudaltsov commented
The reason for this is that now error blocks might appear inside `<label>` tags. You cannot have `<div>` inside a label.

2018-04-11 22:28 UTC, vudaltsov requested changes

2018-04-11 22:28 UTC, vudaltsov commented on src/Symfony/Bridge/Twig/Resources/views/Form/bootstrap_4_layout.html.twig
> +        <span class="{% if form is not rootform %}invalid-feedback d-block{% else %}alert alert-danger d-block{% endif %}">
Let's move the `d-block` class outside the `{% if %}` statement to have it only once in the line

2018-04-14 14:57 UTC, nicolas-grekas commented
Thank you @normisg.

2018-04-14 14:57 UTC, merged