[Messenger] Add tests for ValidationMiddleware
symfony/symfony pull request #26913
Opened 2018-04-13 03:19 UTC by yceruto

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

2018-04-13 08:52 UTC, sroze requested changes

2018-04-13 08:52 UTC, sroze commented on src/Symfony/Component/Messenger/Tests/Middleware/ValidationMiddlewareTest.php
> +        (new ValidationMiddleware($validator))->handle($message, $next);
Could you also test the return value?

2018-04-13 12:28 UTC, yceruto commented on src/Symfony/Component/Messenger/Tests/Middleware/ValidationMiddlewareTest.php
> +        (new ValidationMiddleware($validator))->handle($message, $next);
Done.

2018-04-13 13:17 UTC, yceruto commented
Status: Needs Review

2018-04-14 10:53 UTC, ogizanagi approved these changes

2018-04-14 13:36 UTC, nicolas-grekas approved these changes
with minor comment

2018-04-14 13:36 UTC, nicolas-grekas commented on src/Symfony/Component/Messenger/composer.json
> +        "symfony/validator": "~4.0"
would 3.4 work (same for process?)
can you fix the alpha order also? (this is a new component so it's still time to fix this)

2018-04-14 14:04 UTC, nicolas-grekas commented
Thank you @yceruto.

2018-04-14 14:05 UTC, merged