[WebProfilerBundle] Display uploaded files in the profiler
symfony/symfony pull request #26946
Opened 2018-04-16 11:40 UTC by javiereguiluz

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #26926
| License       | MIT
| Doc PR        | -

![profiler_files](https://user-images.githubusercontent.com/73419/38807087-ac1e9bac-417b-11e8-99e0-317b437c986e.png)

2018-04-16 12:08 UTC, phansys approved these changes

2018-04-21 19:12 UTC, chapterjason commented
Looks awesome, as I watched in the `UploadedFile` I saw the `
getError()` and `getErrorMessage()` what happens if there is just an error with one file?

2018-06-19 11:58 UTC, chapterjason commented on src/Symfony/Bundle/WebProfilerBundle/Resources/views/Collector/request.html.twig
> +                                <th scope="col">Temporary Location</th>
You're right.

```
The file will be deleted from the temporary directory at the end of the request if it has not been moved away or renamed.
```
http://php.net/manual/en/features.file-upload.post-method.php

2018-06-25 11:10 UTC, fabpot requested changes

2018-06-25 11:10 UTC, fabpot commented on src/Symfony/Bundle/WebProfilerBundle/Resources/views/Collector/request.html.twig
> +                                <th scope="col">Temporary Location</th>
@javiereguiluz Can you remove this column?

2018-06-25 13:43 UTC, fabpot approved these changes

2018-06-25 17:10 UTC, fabpot commented
Thank you @javiereguiluz.

2018-06-25 17:11 UTC, merged

2018-06-26 07:44 UTC, xabbuh commented
Wouldn't it make sense to also display the error (possibly human readable) if any occurred during uploading?