Redirect to proper Symfony version documentation
symfony/symfony pull request #27104
Opened 2018-04-30 21:43 UTC by noniagriconomie

| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | none
| License       | MIT
| Doc PR        | 

Just a small improvement
I think this can make some dev target the right documentation instead of reading an other version that the one they are developing on

2018-05-01 08:12 UTC, sroze approved these changes

2018-05-02 05:55 UTC, fabpot requested changes

2018-05-02 05:55 UTC, fabpot commented on src/Symfony/Bundle/TwigBundle/Resources/views/layout.html.twig
> +                    <a href="https://symfony.com/support" target="_blank">
Not adding `_blank` was done on purpose. It's up to the user (here developers) to choose what to do; adding `_blank` forces the opening of a new tab/window. @pborreli can probably give a better explanation than me on this topic.

This should be reverted (same above).

2018-05-02 17:06 UTC, noniagriconomie commented
@fabpot understood, target blank removed

2018-05-02 17:07 UTC, lyrixx commented
The target branch is not good. It should be either 2.7 (bug fix) or master (new feature).
I don't know what is it though

2018-05-02 18:09 UTC, noniagriconomie commented
This code does not exists on 2.x
And as 3.4 is an lts and it is code on dev only, i think it should be discussed/acceptes
What do you think?

2018-05-03 06:12 UTC, dunglas approved these changes

2018-05-03 06:28 UTC, fabpot approved these changes
for master

2018-05-03 06:29 UTC, fabpot commented
Thank you @noniagriconomie.

2018-05-03 06:30 UTC, merged