[DI] Display previous error messages when throwing unused bindings
symfony/symfony pull request #27191
Opened 2018-05-07 22:26 UTC by nicolas-grekas

| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | n
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

As reported by @jvasseur, confirmation + review welcome.

2018-05-08 10:19 UTC, jvasseur requested changes

2018-05-08 10:19 UTC, jvasseur commented on src/Symfony/Component/DependencyInjection/Compiler/ResolveBindingsPass.php
> +                    $message .= sprintf("\nCould be related to%s:", 1 < \count($errors) ? ' one of' : '');
This should be `$this->errors`

2018-05-08 10:19 UTC, jvasseur commented on src/Symfony/Component/DependencyInjection/Compiler/ResolveBindingsPass.php
> +                foreach ($this->errors as $serviceId => $mesage) {
Not sure if the missing `s` is voluntary here, but we can't use `$message` since it's used in the parent scope, maybe `$error` ?

2018-05-08 10:19 UTC, jvasseur commented on src/Symfony/Component/DependencyInjection/Compiler/ResolveBindingsPass.php
> +                    $message .= sprintf("\n - \"%s\": %s", $serviceId, $message);
I don't think we need to put the service id here since it's already in the exception message thrown by `getConstructor`.

2018-05-08 23:41 UTC, nicolas-grekas commented
Thank you @jvasseur, comments addressed. Do you confirm it fixed your issue?

2018-05-09 07:13 UTC, jvasseur approved these changes
This works at solving the issue.

2018-05-09 13:44 UTC, sroze commented
@nicolas-grekas could you add a test for that?

2018-05-09 18:50 UTC, nicolas-grekas commented
Test added.

2018-05-09 18:54 UTC, sroze approved these changes

2018-05-12 09:31 UTC, fabpot approved these changes

2018-05-12 09:35 UTC, fabpot commented
Thank you @nicolas-grekas.

2018-05-12 09:35 UTC, merged