[Messenger] Make sure default receiver name is set on command configuration
symfony/symfony pull request #27224
Opened 2018-05-10 16:45 UTC by yceruto

| Q             | A
| ------------- | ---
| Branch?       | 4.1
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #
| License       | MIT
| Doc PR        | -

2018-05-10 16:57 UTC, sroze requested changes
Can you add a test to prove it fixed it?

2018-05-10 17:40 UTC, yceruto commented
Status: Needs Review

2018-05-10 21:25 UTC, nicolas-grekas approved these changes

2018-05-10 22:52 UTC, sroze approved these changes

2018-05-11 06:26 UTC, ogizanagi approved these changes

2018-05-11 07:44 UTC, sroze commented
Thank you @yceruto.

2018-05-11 07:44 UTC, merged