Update UPGRADE-4.0.md
symfony/symfony pull request #27406
Opened 2018-05-29 13:36 UTC by DonCallisto

| Q             | A
| ------------- | ---
| Branch?       | 4.0
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | yes
| Tests pass?   |
| Fixed tickets |
| License       | MIT
| Doc PR        | 

This https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/Security/Guard/Firewall/GuardAuthenticationListener.php#L127 was not reported.

2018-05-29 13:49 UTC, nicolas-grekas commented
Should we tell about any corresponding deprecation in UPGRADE-3.4.md also?

2018-05-29 13:52 UTC, DonCallisto commented
I'm not sure what you mean but to me it's pretty fine to enhance the upgrade document from this major version.

2018-05-29 17:49 UTC, linaori requested changes

2018-05-29 19:47 UTC, nicolas-grekas commented
This should be merged on branch 3.4, where we advertise for changes needed to prepare for 4.0.
I'm surprised there is no corresponding changes on UPGRADE-3.4.md. Could anyone have a look?

2018-05-30 09:37 UTC, nicolas-grekas commented
So, following the link in the description gives the answer: the depreciation should be advertised in UPGRADE-3.4.md for sure.

2018-05-30 09:41 UTC, DonCallisto commented
I'm still not sure as this is deprecated since 3.4 but I should not care about this *unless* upgrading to 4.
However if that's the practice followed here, I'll be happy to change the base of this PR, _just let me know_.
After this I'll change what @iltar reviewed in order to make the docs consistent.

2018-05-30 09:44 UTC, nicolas-grekas commented
I do confirm this should be on 3.4 :)

2018-05-30 09:59 UTC, DonCallisto commented
@nicolas-grekas I've changed the PR base branch
@iltar I've fixed what you've requested

2018-05-30 10:00 UTC, nicolas-grekas commented
Thank you @DonCallisto 
Can you please also update UPGRADE-3.4.md?
I invite you to compare both files (4.0 and 3.4) to figure out what I'm talking about since my first comment :)

2018-05-30 10:02 UTC, nicolas-grekas commented
And src/Symfony/Component/Security/CHANGELOG.md also should be updated BTW!

2018-05-30 10:02 UTC, DonCallisto commented
Ok, thank you for this advices. I'll take a look at them ASAP.

2018-05-30 11:15 UTC, DonCallisto commented
@nicolas-grekas updated. Please check if fits well and let me know if anything else has to be changed.

2018-05-30 11:18 UTC, nicolas-grekas commented on CHANGELOG-3.4.md
> + * feature #16835 [Security] When extending `AbstractGuardAuthenticator` it's no longer allowed to return `null` from `getCredentials()` (Amo)
I really meant `src/Symfony/Component/Security/CHANGELOG.md`
this one is autogenerated so this should be reverted :)

2018-05-30 11:19 UTC, nicolas-grekas commented on UPGRADE-3.4.md
> + * When extending `AbstractGuardAuthenticator` it's no longer allowed to return `null` from `getCredentials()`.
~it's no longer allowed~
it's deprecated

2018-05-30 12:06 UTC, DonCallisto commented
Now it's hopefully fine

2018-05-30 12:08 UTC, nicolas-grekas approved these changes
all good on my side :)

2018-05-30 12:35 UTC, fabpot requested changes

2018-05-30 12:35 UTC, fabpot commented on UPGRADE-4.0.md
> + * When extending `AbstractGuardAuthenticator` it's deprecated to return `null` from `getCredentials()`.
In 4.0, it's not deprecated anymore. So, it should probably be something like "When extending `AbstractGuardAuthenticator`,  `getCredentials()` cannot return `null` anymore, return `false` from `supports()` if no credentials available instead."

2018-05-30 12:35 UTC, fabpot commented on src/Symfony/Component/Security/CHANGELOG.md
> + * deprecated to return `null` from `getCredentials()` in classes that extend `AbstractGuardAuthenticator`. Return `false`
CS: should be wrapper at around 80 chars.

2018-05-31 07:30 UTC, DonCallisto commented
@fabpot fixed

2018-05-31 07:34 UTC, fabpot approved these changes

2018-05-31 07:42 UTC, fabpot commented
Thank you @DonCallisto.

2018-05-31 07:42 UTC, merged