Add support for error ouput in the CommandTester
symfony/symfony pull request #27434
Opened 2018-05-30 19:51 UTC by cdekok

Move initialization of the streams to the trait so the `capture_stderr_separately` also works in the CommandTester.

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no     
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #27422 
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

Make it possible to test seperate stderr output.

```$tester = new CommandTester($command);
$tester->execute(
    array('foo' => 'bar'),
    array('capture_stderr_separately' => true)
);

$this->assertEquals('foo', $tester->getErrorOutput());
````

2018-06-06 13:17 UTC, chalasr requested changes

2018-06-06 13:17 UTC, chalasr commented on src/Symfony/Component/Console/Tester/TesterTrait.php
> +     * @return self
this one is not true and returning void is fine. Both `@param` and `@return` annotations should be removed as they do not provide any information that is not already provided by the method signature.

2018-06-11 06:41 UTC, OskarStark commented on src/Symfony/Component/Console/Tester/CommandTester.php
> +     *  * capture_stderr_separately: Make output of stdOut and stdErr separately available
should be aligned

2018-06-12 18:53 UTC, cdekok commented on src/Symfony/Component/Console/Tester/TesterTrait.php
> +    public function getErrorOutput($normalize = false)
Am not sure what you mean by this, do you mean add the internal docblock to each method except the getErrorOutput?
Am not really a big fan of putting properties and methods which keep some sort of state in a trait but it was done there already and I can't see anyway to fix it without changing the interface or code duplication.

2018-06-26 09:11 UTC, chalasr commented on src/Symfony/Component/Console/Tester/TesterTrait.php
> +    public function getErrorOutput($normalize = false)
> do you mean add the internal docblock to each method except the getErrorOutput?

Yes, to would avoid making some public methods internal in the next minor version.

> Am not really a big fan of putting properties and methods which keep some sort of state in a trait

me either but we have similar traits elsewhere in the codebase, it should be fine as is.

2018-06-26 09:12 UTC, chalasr commented on src/Symfony/Component/Console/Tester/TesterTrait.php
> +     * Initialize the output property.
this comment is still relevant, we use the 3rd person form to describe methods

2018-09-05 12:13 UTC, chalasr requested changes
@cdekok Would you mind addressing the remaining minor comments and rebase your branch?

2018-09-05 12:13 UTC, chalasr commented on src/Symfony/Component/Console/Tests/Tester/ApplicationTesterTest.php
> +        $this->assertEquals('foo', $tester->getErrorOutput());
`assertSame`

2018-09-23 11:43 UTC, chalasr approved these changes

2018-09-23 11:46 UTC, chalasr commented
Nice first contribution! Thank you @cdekok

2018-09-23 11:47 UTC, merged