Improved an error message related to controllers
symfony/symfony pull request #27499
Opened 2018-06-05 06:49 UTC by javiereguiluz

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

This proposal is irrelevant for experienced users but it may be useful for newcomers. After having delivered several introductory Symfony training, I can say that when someone adds `return "some string...";` in their controller, the error message is confusing:

![before](https://user-images.githubusercontent.com/73419/40959468-0faf790a-689d-11e8-9ce1-f6e0caf4b113.png)

Maybe we can reword it a bit? (I'm open for suggestions to improve the error message)

![after](https://user-images.githubusercontent.com/73419/40959505-29747070-689d-11e8-834e-92bf18760469.png)

2018-06-05 07:10 UTC, ScullWM commented
Great for newcomers!
Just guessing, expect giving bad habbit to newcomers, why don't Symfony create a Response with this given string ?

2018-06-05 07:14 UTC, javiereguiluz commented
@ScullWM allowing to return strings was discussed in the past (specially because "some frameworks" allow to do that). But it was decided to keep requiring `Response` objects. At first it might be like a bad decision, but it helps newcomers realize that Symfony apps are always about HTTP Request/Response workflow. No matter if it's a silly "Hello World" app or the most complex app ever created. It's always the same: you are given a Request object and you must return a Response object.

That's why I think we should keep the current behaviour: if people learn about Request/Response soon, they will understand Symfony easier.

2018-06-05 07:32 UTC, javiereguiluz commented
@lyrixx the code change and the screenshot were done in a Symfony 4.1 app and then I copied the code to the master branch 🙈

2018-06-05 08:02 UTC, iltar commented
You can always create your own listener that transforms the string into a response. The SensioFrameworkExtraBundle does this for arrays with the `@Template` annotation.

2018-06-05 08:33 UTC, nicolas-grekas commented on src/Symfony/Component/HttpKernel/HttpKernel.php
> +                $msg = sprintf('The controller must return a Symfony\Component\HttpFoundation\Response object but it returned: %s.', is_string($response) ? sprintf('"%s" string', $response) : $this->
I'd suggest moving the `is_string` check inside the `varToString` method

2018-06-19 10:37 UTC, nicolas-grekas approved these changes

2018-06-25 17:00 UTC, fabpot requested changes

2018-06-26 14:52 UTC, javiereguiluz commented
I've updated this feature to trim long strings.

Before:

![before](https://user-images.githubusercontent.com/73419/41920523-35a5237e-7961-11e8-823a-174d326919ea.png)

After:

![after](https://user-images.githubusercontent.com/73419/41920529-38534100-7961-11e8-85c5-90dff62451d1.png)

-----

About this other comment from Fabien (https://github.com/symfony/symfony/pull/27499#discussion_r196375525) I'm not sure how to solve it. Thanks!

2018-06-27 06:45 UTC, javiereguiluz commented
Thanks to Twig's automatic escaping, I think we're good here. I've tested with some of the examples given by OWASP to prevent XSS (https://www.owasp.org/index.php/Testing_for_Reflected_Cross_site_scripting_(OTG-INPVAL-001)) and it looks like it's working:

![xss-error-page](https://user-images.githubusercontent.com/73419/41957154-4d71d9c2-79e6-11e8-89f3-7f60f238b081.png)

Can anyone spot other "attack vectors" in this code? Thanks"

2018-06-27 06:52 UTC, nicolas-grekas approved these changes

2018-06-27 06:52 UTC, nicolas-grekas commented on src/Symfony/Component/HttpKernel/HttpKernel.php
> +                $msg = sprintf('The controller must return a Symfony\Component\HttpFoundation\Response object but it returned %s.', $this->varToString($response));
Maybe add double quotes around the ...\Request

2018-06-27 09:24 UTC, fabpot approved these changes

2018-06-27 09:34 UTC, fabpot commented
Thank you @javiereguiluz.

2018-06-27 09:35 UTC, merged