Enhance the twig not found exception
symfony/symfony pull request #27535
Opened 2018-06-07 09:57 UTC by behnoushnorouzi

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no 
| Deprecations? | no 
| Tests pass?   | yes 
| Fixed tickets | #27468
| License       | MIT
| Doc PR        | -

Improve error message to make it clear to developer what mistake they have made.

2018-06-07 10:10 UTC, stof commented on src/Symfony/Bundle/TwigBundle/Loader/NativeFilesystemLoader.php
> +            if ($e instanceof \Twig_Error_Loader && preg_match('/^([^:]*?)(?:Bundle)?:([^:]*+):(.+\.[^\.]+\.[^\.]+)$/', $template, $m) && 0 !== strpos($template, '@')) {
the `instanceof` will always be true. `Twig\Error\LoaderError` is a class alias of `Twig_Error_Loader`.

2018-06-07 10:10 UTC, stof commented on src/Symfony/Bundle/TwigBundle/Loader/NativeFilesystemLoader.php
> +            if ($e instanceof \Twig_Error_Loader && preg_match('/^([^:]*?)(?:Bundle)?:([^:]*+):(.+\.[^\.]+\.[^\.]+)$/', $template, $m) && 0 !== strpos($template, '@')) {
You should switch the regex match in the `strpos`. Checking the first char is faster.

Btw, you could optimize it even more:

```php
if ('' !== $template && '@' !== $template[0] && preg_match(...)) {
```

Using strpos to check only the first char is not the fastest way.

2018-06-07 15:47 UTC, nicolas-grekas approved these changes

2018-06-08 06:28 UTC, fabpot requested changes

2018-06-08 06:28 UTC, fabpot commented on src/Symfony/Bundle/TwigBundle/Tests/Loader/NativeFilesystemLoaderTest.php
> +    const DS = DIRECTORY_SEPARATOR;
I would remove this const and use the PHP one instead.

2018-06-08 06:28 UTC, fabpot commented on src/Symfony/Bundle/TwigBundle/Loader/NativeFilesystemLoader.php
> +            if ('' === $template || '@' === $template[0] || !preg_match('/^([^:]*?)(?:Bundle)?:([^:]*+):(.+\.[^\.]+\.[^\.]+)$/', $template, $m)) {
Can we use named patterns to make the code using `$m` more easily understandable?

2018-06-08 10:27 UTC, behnoushnorouzi commented
Thank you for the reviews it's done.

Status: needs review

2018-06-08 11:56 UTC, sstok approved these changes

2018-06-08 12:43 UTC, xabbuh commented on src/Symfony/Bundle/TwigBundle/Loader/NativeFilesystemLoader.php
> +class NativeFilesystemLoader extends FilesystemLoader
you may want to add yourself as the author of this class :)

2018-06-09 10:03 UTC, Lewiscowles1986 commented
Should this emit a notice or warning if used in production? 

It seems like a development pattern, and can be switched out for the extended class. Once the suggestion is implemented it seems like switching to the standard class might be more helpful.

2018-06-09 15:45 UTC, xabbuh approved these changes

2018-06-14 07:45 UTC, 20uf approved these changes

2018-06-14 07:54 UTC, stof commented
We don't even need to do it in a compiler pass. The debug parameter can be accessed in the DI extension (the `kernel.*` params can be accessed there safely, as they are set early)

2018-06-19 10:58 UTC, nicolas-grekas commented
Thank you @behnoushnorouzi.

2018-06-19 10:59 UTC, merged