Fix bad method call with guard authentication + session migration
symfony/symfony pull request #27581
Opened 2018-06-11 22:52 UTC by weaverryan

| Q             | A
| ------------- | ---
| Branch?       | 2.8
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no (but there needs to be on master)
| Tests pass?   | yes
| Fixed tickets | #27577 
| License       | MIT
| Doc PR        | n/a

I messed up #27452 :/. Guard is the one class where the session migration is not on the listener, it's on the handler. The tricky part is that there is only ONE handler (unlike listeners where there is 1 listener per firewall). That means that implementing a session migration strategy that avoids stateless firewalls was a bit more tricky: I could only think to inject a map into `GuardAuthenticationHandler`. On the bright side, this also fixes session migration (not happening) when people call the `authenticateUserAndHandleSuccess()` method directly.

On master, we'll need to add a deprecation to make the 3rd argument of `authenticateWithToken()` required - it's optional now for BC. We may also need to re-order the constructor args.

I DID test this in a real 2.8 project, to make sure that things were properly wired up. Apologies for not doing that for the other PR.

Cheers!

2018-06-11 23:13 UTC, chalasr requested changes

2018-06-11 23:13 UTC, chalasr commented on src/Symfony/Component/Security/Guard/GuardAuthenticatorHandler.php
> +    public function authenticateWithToken(TokenInterface $token, Request $request, $providerKey = null)
even optional, this would break a child (signature mismatch). `func_get_arg()` should be used here :)

2018-06-12 00:03 UTC, weaverryan commented
Thanks @chalasr! Made the change

2018-06-12 00:45 UTC, chalasr approved these changes

2018-06-12 04:19 UTC, nicolas-grekas approved these changes
With minor cs comments.

2018-06-12 04:19 UTC, nicolas-grekas commented on src/Symfony/Component/Security/Guard/GuardAuthenticatorHandler.php
> +     * @param EventDispatcherInterface|null $eventDispatcher
We're ok with partial docblocks, so these 2 above lines can be removed.

2018-06-12 04:19 UTC, nicolas-grekas commented on src/Symfony/Component/Security/Guard/GuardAuthenticatorHandler.php
> +        $providerKey = func_num_args() > 2 ? func_get_arg(2) : null;
\func_num_args()
The new argument should be added on the signature between /**/, and on the docblock.

2018-06-12 04:19 UTC, nicolas-grekas commented on src/Symfony/Component/Security/Guard/GuardAuthenticatorHandler.php
> +        if (!$this->sessionStrategy || !$request->hasSession() || !$request->hasPreviousSession() || in_array($providerKey, $this->statelessProviderKeys)) {
\in_array(..., true)

2018-06-12 12:39 UTC, weaverryan commented
Let's try this :) - not 100% sure I got that format for the documented new arg right 😇

2018-06-12 12:54 UTC, nicolas-grekas approved these changes

2018-06-12 13:23 UTC, chalasr commented
Thank you @weaverryan.

2018-06-12 13:24 UTC, closed without merging