Added support for translation files with other filename patterns
symfony/symfony pull request #27655
Opened 2018-06-20 13:12 UTC by javiereguiluz

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #27644
| License       | MIT
| Doc PR        | -

This implements the #27644 feature request in case we accept it.

My vote is 👍 because the changes required are tiny and the resulting code is even more robust thanks to the new `preg_match()` call.

2018-06-20 14:33 UTC, stof requested changes

2018-06-20 14:33 UTC, stof commented on src/Symfony/Component/Translation/Command/XliffLintCommand.php
> +            $expectedFilenamePattern = sprintf('/^(.*\.%s\.xlf|%s\..*\.xlf)/', $normalizedLocale, $normalizedLocale);
missing `preg_quote` on the 2 variables you inject in the regex

2018-06-20 14:35 UTC, stof commented
In a FrameworkBundle-based project, the file name format must always be `<domain>.<locale>.<format>`. Anything else is unsupported (because the bundle needs to be able to extract the domain and the locale from the file name). So having the convention configurable in the command (using a constructor argument) would be better to me than supporting having the locale anywhere in the file name (which would not report all issues for Symfony projects)

2018-06-20 14:51 UTC, javiereguiluz commented
@stof I've made some changes. Please tell me if that's what you were proposing. Thanks.

2018-06-20 15:21 UTC, stof commented on src/Symfony/Component/Translation/Command/XliffLintCommand.php
> +            // when used outside Symfony, allow '____.locale.xlf' and 'locale.____.xlf'
comments should be talking about strict vs not strict, not about `inside Symfony`. Other projects may put the command in strict mode too.

2018-06-20 15:21 UTC, stof commented on src/Symfony/Component/Translation/Command/XliffLintCommand.php
> +    public function __construct(string $name = null, callable $directoryIteratorProvider = null, callable $isReadableProvider = null, bool $requireStrictFileNames = false)
Shouldn't we keep using `true` as default, to keep the same behavior than today by default ?

2018-06-20 15:22 UTC, stof commented on src/Symfony/Component/Translation/Command/XliffLintCommand.php
> +            $normalizedLocale = preg_quote(str_replace('-', '_', $targetLanguage));
you need to pass the regex delimiter as second argument to `preg_quote` as it needs to be escaped too.

2018-06-22 06:08 UTC, fabpot reviewed
Can we add some more tests , especially when `requireStrictFileNames` is false?

2018-06-25 10:20 UTC, fabpot approved these changes

2018-06-25 10:24 UTC, merged