Updates DocBlock to a mixed param type
symfony/symfony pull request #27663
Opened 2018-06-20 20:13 UTC by andrewnclark

| Q             | A
| ------------- | ---
| Branch?       | 4.1
| Bug fix?      |  Yes
| New feature?  |  No
| BC breaks?    | No
| Deprecations? | Non added.
| Tests pass?   | Yes , no new tests added.
| Fixed tickets | #27457 
| License       | MIT

The JSON serializers make use of the JsonSerializable interface and return arrays to the NormalizerInterface. This PR updates the DocBlock to reflect that.

Moving towards PHP 7.2 and the use of object type-hints would require changes to the [JsonSerializableNormalizer@L41](https://github.com/symfony/symfony/blob/92c37b9711b3e296ad427d590ac49488c73d71b2/src/Symfony/Component/Serializer/Normalizer/JsonSerializableNormalizer.php#L41) at a minimum.

Truly not much of a PR I'm afraid!

2018-06-20 22:07 UTC, vudaltsov approved these changes

2018-06-20 22:08 UTC, vudaltsov requested changes

2018-06-20 22:08 UTC, vudaltsov commented on src/Symfony/Component/Serializer/Normalizer/NormalizerInterface.php
> +     * @param mixed $object  Object to normalize
Add a space after `mixed` to align argument names and satisfy Symfony Code Style rules.

2018-06-20 22:54 UTC, vudaltsov commented
I think this PR can be targeted against 2.8 since it's not a new feature.

2018-06-20 23:17 UTC, vudaltsov commented
@andrewnclark, looks like you have accidentally changed the base twice and now it's again 4.1 :)

2018-06-20 23:20 UTC, andrewnclark commented
All the additional commits scared me so I rolled it back. Is changing the base in this way the correct way to do it?

2018-06-20 23:22 UTC, vudaltsov commented
You should also rebase it in git so that the commit starts from the tip of the 2.8 branch.

2018-06-21 10:57 UTC, nicolas-grekas approved these changes
(rebased)

2018-06-21 11:05 UTC, vudaltsov approved these changes

2018-06-21 16:26 UTC, maxhelias approved these changes

2018-06-21 16:45 UTC, fabpot approved these changes

2018-06-21 16:45 UTC, fabpot commented
Good catch, thanks @andrewnclark.

2018-06-21 16:46 UTC, merged