[Console] Add interface for command class
symfony/symfony pull request #27666
Opened 2018-06-20 22:30 UTC by HeathNaylor

| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #27665 
| License       | MIT
| Doc PR        | No documentation change

Not sure this constitutes as a feature. This is simply adding an interface for the Command class. I was also a little confused, the contribution documentation says to target version 2.7 and on, so this PR is for 2.7.

2018-06-20 22:51 UTC, HeathNaylor commented
The checks are failing for fabbot.io on common typos that are outside the scope of my PR.

2018-06-21 07:14 UTC, linaori requested changes

2018-06-21 07:14 UTC, iltar commented on CHANGELOG-2.7.md
> + * feature #27665 [Console] Add contract for Command class
This file does not need to be updated, it's autogenerated on release I believe

2018-06-21 07:14 UTC, iltar commented on src/Symfony/Component/Console/Command/CommandInterface.php
> +interface CommandInterface
Doc above here is incorrect now. 

I also think this interface has far too many methods that are not relevant to implementing your command, they are merely a detail within Symfony. I would love to see this interface only define the methods you'd need to implement for a simple executable command. Perhaps multiple interfaces if you wish to implement additional features? But several of these methods are very specific to the architecture of the Command as implemented by Symfony.

2018-06-21 07:14 UTC, iltar commented on src/Symfony/Component/Console/Command/CommandInterface.php
> +     * @see execute()
The references to execute are no longer  valid, as this is a detail of the abstract command

2018-06-21 07:14 UTC, iltar commented on src/Symfony/Component/Console/Command/CommandInterface.php
> +     * @deprecated since version 2.3, to be removed in 3.0.
It see you've based your PR on 2.7. 2.7 is not supported anymore and new features go into the master. Can you change your PR to be against the master instead? Github will let you change it, but you will still need to change the base branch in your git branch.

2018-06-21 08:20 UTC, stof commented
New features are never going into a maintenance branch. This cannot go anywhere else than master.

2018-06-21 08:31 UTC, nicolas-grekas commented
> contribution documentation says to target version 2.7 and on, so this PR is for 2.7.

can you link to the page telling so please? This is a mistake we need to fix.

About the proposed change, I'm :-1: as it doesn't make sense to add this interface which does so many things and breaks e.g. SRP, etc. Just use the class instead.

2018-06-21 10:48 UTC, chalasr commented
I’m -1 for the proposed change, you probably don’t want to implement this interface :)
Closing, thank you for the PR.

2018-06-21 10:48 UTC, closed without merging

2018-06-21 14:14 UTC, HeathNaylor commented
@nicolas-grekas https://symfony.com/doc/current/contributing/code/patches.html References 2.7 as the branch to use.