Added new methods submitForm and clickLink to Client class
symfony/symfony pull request #27807
Opened 2018-07-02 18:26 UTC by nowiko

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| License       | MIT

Added new methods to BrowserKit/Client to simplify work with links and forms.
Related to https://github.com/symfony/symfony/issues/27627

2018-07-02 18:29 UTC, linaori requested changes

2018-07-02 18:29 UTC, iltar commented on src/Symfony/Component/BrowserKit/Tests/ClientTest.php
> +        $client->submitForm('Register', array(), 'POST');
I think it would be nice to add a test case where actual values are submitted along, this case is not covered right now.

2018-07-02 18:54 UTC, nowiko commented
@iltar Please review that applied changes are suitable.

2018-07-02 21:02 UTC, iltar commented
Added test looks good to me 👍

2018-07-03 06:51 UTC, fabpot commented
I think we also tests for when the link/form is not found.

2018-07-03 17:57 UTC, nowiko commented
@fabpot 
I have added test cases if link or form cannot be found. Please, let me know if this should be modified, or additional check for form/link existence should be performed on the method level.

2018-07-12 07:03 UTC, fabpot approved these changes

2018-07-12 07:05 UTC, fabpot commented
Thank you @nowiko.

2018-07-12 07:06 UTC, merged

2018-09-13 12:17 UTC, stof commented
these 2 methods will trigger a fatal error if you call them before calling `request`, as `getCrawler` will return `null` in that case (that's a deprecated usage, but it does not throw yet).
As these are new APIs, we should forbid them already when we don't have a crawler (thus, doing separate checks would allow to have a better exception message, as it would talk about the right method being used)