Update Security.php
symfony/symfony pull request #27943
Opened 2018-07-13 14:39 UTC by ro0NL

| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no-ish
| Deprecations? | no
| Tests pass?   | yes    
| Fixed tickets | #...   
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

`$user` can also be an object implementing `__ toString`. Here we want only true user objects...

2018-07-13 16:19 UTC, ro0NL commented
Im also wondering if it's better to throw, rather then silently ignoring "non users" by returning null. To clarify the intend here.

2018-07-13 17:21 UTC, xabbuh approved these changes
a test would be nice

2018-07-13 18:16 UTC, stof commented
well, throwing for anonymous token would be a big BC break, and would make this API much less developer-friendly

2018-07-13 20:03 UTC, weaverryan commented
I’m following the logic. But, was this to solve some specific issue?

It’s looks like a BC break to me, unfortunately.

2018-07-13 20:13 UTC, ro0NL commented
We had some discussion on slack about the inconsistency between the documented `@return` and the actual return (any object). Basically it causes confusion about the intend...

But no real issue :) it will just crash if this class is (ever) updated to have type declarations (#27944).

And yes, we can do an upgrade path with deprecations but i also think it qualifies a bugfix (otherwise the bugfix would be to update to `@return object|null`, which AFAIK was not the intend here ...)

2018-07-14 14:40 UTC, weaverryan commented
Bug fix: that’s a good argument for the behavior change. I’d still prefer a deprecation and a merge into 4.2... after all, the bug isn’t currently hurting any functionality. So, waiting until 4.2 does not cause any issues.

2018-07-14 19:07 UTC, chalasr commented
+1 for a BC layer

2018-07-15 09:14 UTC, ro0NL commented
Done.

2018-07-15 09:17 UTC, fabpot requested changes

2018-07-15 09:17 UTC, fabpot commented on src/Symfony/Component/Security/Core/Security.php
> +            @trigger_error(sprintf('Accessing the user object "%s" that is not an instance of "%s" from "%s()" is deprecated since Symfony 4.2. Use "getToken()->getUser()" instead.', get_class($user)
...is deprecated since Symfony 4.2, use...

2018-07-15 16:34 UTC, weaverryan approved these changes
Changelog entries could use a period at the end, but just that nit pick :)

2018-07-15 17:45 UTC, chalasr approved these changes

2018-07-16 14:21 UTC, xabbuh commented on src/Symfony/Component/Security/Core/Security.php
> +            @trigger_error(sprintf('Accessing the user object "%s" that is not an instance of "%s" from "%s()" is deprecated since Symfony 4.2, use "getToken()->getUser()" instead.', get_class($user)
`$user` may not be an object here: `is_object($user) ? get_class($user) : $user`

2018-07-16 14:38 UTC, lyrixx commented
I like the idea :+1:

2018-07-18 03:36 UTC, fabpot approved these changes

2018-07-18 03:37 UTC, fabpot commented
Thank you @ro0NL.

2018-07-18 03:38 UTC, merged