[Cache] leverage Contracts\Cache
symfony/symfony pull request #28097
Opened 2018-08-01 08:11 UTC by nicolas-grekas

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

Implementing #28096

2018-08-30 13:01 UTC, Nyholm requested changes
This needs to be updated

2018-08-30 13:01 UTC, Nyholm commented on src/Symfony/Bundle/FrameworkBundle/Resources/config/cache.xml
> +        <service id="Symfony\Contracts\Cache\ExtendedCacheInterface" alias="cache.app" />
Please remove this line.

2018-08-30 13:01 UTC, Nyholm commented on src/Symfony/Bundle/FrameworkBundle/Resources/config/cache.xml
> +        <service id="Symfony\Contracts\Cache\ExtendedTagAwareCacheInterface" alias="cache.app.taggable" />
It should be `TagAwareCacheInterface`

2018-08-30 13:07 UTC, nicolas-grekas commented
thanks fixed

2018-09-02 19:45 UTC, Nyholm approved these changes
Thank you. 👍

2018-09-02 19:45 UTC, Nyholm commented on src/Symfony/Component/Cache/CacheInterface.php
> -interface CacheInterface
For the record: This interface has never been released, so it is okey to remove it.

2018-09-04 06:50 UTC, fabpot approved these changes
With one small comment

2018-09-04 06:50 UTC, fabpot commented on src/Symfony/Contracts/Cache/CacheInterface.php
> + * Gets and stores items from a cache.
`Gets/Stores items from/to a cache`

2018-09-04 07:06 UTC, nicolas-grekas commented on composer.json
> +        "symfony/translation-contracts": "1.0"
I realized we should add this. OK to you?

2018-09-04 08:08 UTC, merged