VarDumper closure fix
symfony/symfony pull request #28196
Opened 2018-08-13 07:43 UTC by fchris82

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| License       | MIT
| Doc PR        | 

If the `ClassStub` needs to work with a class closure, it will throw a `FatalErrorException`. I got this:

```
FatalErrorExceptionError: __debuginfo() must return an array
--
in ClassStub.php line 56
at ReflectionMethod->__construct('\'eZ\\\\Publish\\\\Core\\\\Base\\\\Container\\\\ApiLoader\\\\Storage\\\\ExternalStorageRegistryFactory\'', '\'eZ\\\\Publish\\\\Core\\\\Base\\\\Container\\\\ApiLoader\\\\Storage\\\\{closure}\'') in ClassStub.php line 56
at ClassStub->__construct('identifier' => '\'eZ\\\\Publish\\\\Core\\\\Base\\\\Container\\\\ApiLoader\\\\Storage\\\\ExternalStorageRegistryFactory->eZ\\\\Publish\\\\Core\\\\Base\\\\Container\\\\ApiLoader\\\\Storage\\\\{closure}\'', 'callable' => '???') in ExceptionCaster.php line 163
...
```

This bugfix handles this situation.

2018-08-14 14:57 UTC, nicolas-grekas submitted a review, later dismissed

2018-08-14 14:58 UTC, nicolas-grekas requested changes
Hello, thank you for the PR, good catch.

Since this is a bug fix, it should target the lowest maintained branch where it applies. That's 3.4 here. Can you please rebase+retarget on 3.4?

I think the tests are not working: when I revert your patch and keep them, they still pass...

2018-09-04 17:11 UTC, fabpot commented
@fchris82 Can you take into account @nicolas-grekas comments? Or do you need help?

2018-12-17 15:39 UTC, nicolas-grekas commented
> FatalErrorExceptionError: __debuginfo() must return an array

This is unrelated to the patched code. Re-reading the code, it should already handle this situation in the catch block. Closing due to lack of feedback also.

Feel free to give a reproducer if I missed something. Thanks for the PR.

2018-12-17 15:39 UTC, closed without merging