[HttpKernel][FrameworkBundle] Fix escaping of serialized payloads passed to test clients
symfony/symfony pull request #28344
Opened 2018-09-03 14:45 UTC by nicolas-grekas

| Q             | A
| ------------- | ---
| Branch?       | 2.8
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #28125
| License       | MIT
| Doc PR        | -

2018-09-03 20:18 UTC, fabpot approved these changes

2018-09-03 20:19 UTC, fabpot requested changes

2018-09-03 20:36 UTC, nicolas-grekas commented on src/Symfony/Bundle/FrameworkBundle/Client.php
> +    require_once autoloader;
oups, fixed thx

2018-09-04 05:10 UTC, fabpot commented
Looks like tests are broken with this change.

2018-09-04 06:43 UTC, nicolas-grekas commented
Fixed, should be green soon.

2018-09-04 08:14 UTC, fabpot approved these changes

2018-09-04 08:15 UTC, fabpot commented
Thank you @nicolas-grekas.

2018-09-04 08:15 UTC, merged