[DI] configure inlined services before injecting when dumping the container
symfony/symfony pull request #28385
Opened 2018-09-06 22:08 UTC by nicolas-grekas

| Q             | A
| ------------- | ---
| Branch?       | 3.4 (WIP on 4.1 for now)
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #28304
| License       | MIT
| Doc PR        | -

#28060 introduced a change in the way inline services are dumped: these instances could end up being configured *after* being injected. This breaks e.g. using Doctrine's Configuration instances, which are expected to be fully defined before being injected into their consumers.

Fixing this required a significant refactorization because I was just unable to reason with the heavily scrambled logic in place right now. The new logic is still non-trivial, but at least it's manageable, thus easier to get correct.

(I'll see if I can figure out a way to remove the whitespace differences also.)

To be retargeted at 3.4 once validated.

2018-09-06 22:10 UTC, nicolas-grekas commented on src/Symfony/Component/DependencyInjection/Tests/Fixtures/php/services_deep_graph.php
> +        return $this->services['foo'] = new \c1($a, $b);
The effect of the fix is visible here: $b is now fully configured when it is injected, where previously its p2 property was set after the injection.

2018-09-07 09:16 UTC, stof requested changes

2018-09-07 09:18 UTC, stof commented
it would also be great to add a test reproducing the use case of Doctrine, to ensure that such instantiation works (and I mean a functional test actually *using* the compiled container to instantiate the service, not a test only asserting the output of the dumper)

2018-09-07 11:46 UTC, nicolas-grekas commented
Replaced by #28388 on 3.4 (ready).

2018-09-07 11:46 UTC, closed without merging