[HttpFoundation] make cookies auto-secure by passing them $secure = null
symfony/symfony pull request #28447
Opened 2018-09-11 16:26 UTC by nicolas-grekas

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #26731
| License       | MIT
| Doc PR        | -

By creating Cookie instances using `null` for the `$secure` argument, this PR allows making cookies inherit their "secure" attribute from the request.

(needs tests for sure)

2018-09-11 20:26 UTC, nicolas-grekas commented
This PR now goes one step further and creates a path to change the default "secure" setting on `new Cookie` instances. The goal is to make it go from the current `false` to the new `null`, so that cookies are secure by default in 5.0, when they're created on an HTTPS connection.
Makes sense?

2018-09-11 22:54 UTC, DavidGarciaCat approved these changes
This PR makes sense to me, although I must say that this is the 1st PR that I review on this repository. Thanks, @nicolas-grekas to consider this update after discuss it on the issue.

2018-09-12 05:09 UTC, fabpot requested changes
Missing some new tests

2018-09-12 05:09 UTC, fabpot commented on src/Symfony/Component/HttpFoundation/Cookie.php
> +     * @param bool|null                     $secure   Whether the cookie should only be transmitted over a secure HTTPS connection from the client or null to set it later using {@see setSecureDefault
If think the most interesting bit to add is the auto-enabling feature (the `setSecureDefault()` is not that interesting if you ask me)

2018-09-17 17:59 UTC, rpkamp commented on src/Symfony/Component/HttpKernel/EventListener/AbstractTestSessionListener.php
> +                        $params[substr($k, 7)] = $v;
Nice :100:

2018-09-26 05:42 UTC, fabpot approved these changes

2018-09-26 05:44 UTC, fabpot commented
Thank you @nicolas-grekas.

2018-09-26 05:45 UTC, merged