[SecurityBundle] make remember-me cookies auto-secure + inherit their default config from framework.session.cookie_*
symfony/symfony pull request #28446
Opened 2018-09-11 16:21 UTC by nicolas-grekas

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #28338
| License       | MIT
| Doc PR        | -

Let's make it easier to have a good default security level, now for the remember-me cookie.

2018-09-11 18:20 UTC, leofeyer approved these changes

2018-09-11 18:35 UTC, chalasr approved these changes

2018-09-11 18:36 UTC, chalasr commented on src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php
> +        foreach ($container->getExtensions() as $name => $extension) {
`if (isset($container->getExtensions()['framework'])) {` instead?

2018-09-12 05:11 UTC, fabpot requested changes
Missing some notes in the changelog files.

2018-09-12 13:00 UTC, stof commented
As you add support in BrowserKit, shouldn't you also not send the cookie in the request if it is a samesite=strict one and we don't have a request to the same site as the last one in the history ? Otherwise, we don't actually support them.

2018-09-18 19:32 UTC, nicolas-grekas commented
Comments addressed.

Status: needs review

2018-09-18 19:41 UTC, chalasr commented on src/Symfony/Bundle/SecurityBundle/CHANGELOG.md
> +
extra blank line

2018-09-18 19:48 UTC, nicolas-grekas commented on src/Symfony/Bundle/SecurityBundle/CHANGELOG.md
> +
fixed thanks :)

2018-09-18 21:16 UTC, leofeyer approved these changes
Except the two unrelated changes (`src/Symfony/Component/DomCrawler/CHANGELOG.md` and `src/Symfony/Component/Finder/CHANGELOG.md`), this look good to me.

2018-09-26 05:38 UTC, fabpot approved these changes

2018-09-26 05:38 UTC, fabpot commented
Thank you @nicolas-grekas.

2018-09-26 05:39 UTC, merged