[Translator] WIP: Intl message converter
symfony/symfony pull request #28486
Opened 2018-09-17 01:43 UTC by Nyholm

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no 
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        | 

As discussed in #28375, we need a command to convert from "Symfony 3" plural format to Intl message format. 

### Before

```xml
<trans-unit id="xx0" resname="simple_key">
  <source>simple_key</source>
  <target>Hello %name%</target>
</trans-unit>
<trans-unit id="xx1" resname="plural_key">
  <source>plural_key</source>
  <target>{0} %name%, there are no apples|{1} %name%, there is one apple|]1,Inf] %name%, there are %count% apples</target>
</trans-unit>
```
        
```twig
Before: 
{{ 'simple_key|trans({"%name%": "foo"}) }} <br>
{{ 'plural_key|transchoice(2, {"%name%": "foo"}) }}
```
### After

```xml
<trans-unit id="xx0" resname="simple_key">
  <source>simple_key</source>
  <target>Hello {name}</target>
</trans-unit>
<trans-unit id="xx1" resname="plural_key">
  <source>plural_key</source>
  <target>{ COUNT, plural,
    =0 {{name}, there are no apples}
    =1 {{name}, there is one apple}
    other {{name}, there are # apples}
}</target>
```

```twig
After: 
{{ 'simple_key'|trans({"%name%": "foo"}) }} <br>
{{ 'plural_key'|trans({"COUNT":2, "%name%": "foo"}) }}
```

As you can see, the user needs to modify their twig templates, "`%name%`" => "`name`". To use "`{%name%}`" in the translation message is not valid syntax. 

## TODO

I need to add more tests of plural messages. Feel free to add a comment with a "Symfony style" plural string and I'll add it to the tests. 

We also need a way to modify the the `%name%` placeholder. Users may use `#name#` or any other arbitrary string.

2018-09-21 14:10 UTC, Killium commented on src/Symfony/Component/Translation/Command/IntlConvertCommand.php
> +        $transPaths = $kernel->getProjectDir().'/translations';
`$transPaths = $kernel->getProjectDir().'/translations';`
🔽 
`$transPaths = $kernel->getProjectDir().DIRECTORY_SEPARATOR.'translations';`
WDYT ?

2018-09-21 14:10 UTC, Killium commented on src/Symfony/Component/Translation/Util/IntlMessageConverter.php
> +        foreach ($parts as $part) {
What if `$parts` is empty ? I would have add a check not to continue if `empty($parts)` is true

2018-10-01 19:48 UTC, nicolas-grekas commented
If #28375 goes well, we *might* close this one and save us some work. \o/

2018-10-10 09:59 UTC, fabpot commented
Why could we close this one? We still need a way to move old messages to the new format, right?

2018-10-10 10:31 UTC, fabpot commented
I get that, but I think people will want to migrate to the new format as it is more powerful.

2018-10-11 13:17 UTC, stof commented
@nicolas-grekas at least for pluralized message, it **is** deprecated currently (as APIs consuming it are deprecated)

2018-10-11 13:32 UTC, nicolas-grekas commented
@stof not really, see https://github.com/symfony/symfony/pull/28375#issuecomment-426036192

2019-01-27 14:40 UTC, nicolas-grekas reviewed
please rebase and move to short arrays.

2019-12-03 06:54 UTC, fabpot commented
@Nyholm Do you have any plans to finish this one? I think it would be a very nice and useful addition.

2019-12-03 07:35 UTC, Nyholm commented
Yes, I will make sure to complete this PR. 

Thank you for the ping

2020-07-01 09:27 UTC, welcoMattic commented
This PR could be very useful alongside #37462 to automate intl conversion of messages stored in a translation SaaS. 
@Nyholm do you plan to finish it before 5.2 release (which is the release we target for #37462)?

2020-07-01 10:30 UTC, Nyholm commented
Yes. I will

2020-08-19 06:52 UTC, fabpot requested changes
Quick review (mostly about style) as a nice ping/reminder :)

2020-08-19 06:52 UTC, fabpot commented on src/Symfony/Bundle/FrameworkBundle/Resources/config/console.xml
> +        </service>
Should be moved to the new PHP config file.

2020-08-19 06:52 UTC, fabpot commented on src/Symfony/Component/Translation/Command/IntlConvertCommand.php
> +            ->setDescription('Convert from Symfony 3 plural format to ICU message format.')
I would remove 3 here.

2020-08-19 06:52 UTC, fabpot commented on src/Symfony/Component/Translation/Command/IntlConvertCommand.php
> +    protected function execute(InputInterface $input, OutputInterface $output)
`: int`

2020-08-19 06:52 UTC, fabpot commented on src/Symfony/Component/Translation/Command/IntlConvertCommand.php
> +        $this->writer->write(new MessageCatalogue($locale, $updated), $input->getOption('output-format'), array('path' => $transPaths));
return 0;

2020-08-19 06:52 UTC, fabpot commented on src/Symfony/Component/Translation/Util/IntlMessageConverter.php
> +     * Get an ICU like array.
Gets

2020-08-19 06:52 UTC, fabpot commented on src/Symfony/Component/Translation/Util/IntlMessageConverter.php
> + * Convert from Symfony 3's plural syntax to Intl message format.
I would remove the reference to 3 here as well.

2020-08-19 06:52 UTC, fabpot commented on src/Symfony/Component/Translation/Util/IntlMessageConverter.php
> +        if (empty($array)) {
We try to avoid using `empty` in Symfony. `if (!$array)` seems enough here.

2020-08-19 06:52 UTC, fabpot commented on src/Symfony/Component/Translation/Util/IntlMessageConverter.php
> +        $icu = self::buildIcuString($array, $variableDelimiter);
temp var could be removed

2020-08-19 06:52 UTC, fabpot commented on src/Symfony/Component/Translation/Util/IntlMessageConverter.php
> +        $regex = sprintf('|%s(.*?)%s|s', $variableDelimiter, $variableDelimiter);
I would inline the regexp

2020-09-07 08:55 UTC, closed without merging