[FrameworkBundle] Deprecate the "--env" and "--no-debug" console options
symfony/symfony pull request #28653
Opened 2018-09-30 18:00 UTC by chalasr

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | n/a
| Deprecations? | yes
| Tests pass?   | yes
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | n/a

2018-10-01 20:38 UTC, dunglas approved these changes

2018-10-01 20:47 UTC, fabpot requested changes
You should add a note in the UPGRADE/CHANGELOG files

2018-10-01 21:27 UTC, OskarStark approved these changes

2018-10-01 21:42 UTC, chalasr commented
@fabpot done, thanks for the reminder.
Also moved to FrameworkBundle, I've been confused by the console recipe relying on them.

2018-10-01 21:45 UTC, jvasseur commented on UPGRADE-4.2.md
> +   set the "APP_DEBUG" environment variable to "0" instead.
`-no-debug` instead of `--env` :wink:

2018-10-01 21:48 UTC, chalasr commented on UPGRADE-4.2.md
> +   set the "APP_DEBUG" environment variable to "0" instead.
fixed thanks

2018-10-02 05:59 UTC, Koc commented on UPGRADE-5.0.md
> + * The `--env` console option and its "-e" shortcut have been deprecated,
In 5.0 this option would removed.

2018-10-02 09:07 UTC, chalasr commented on UPGRADE-5.0.md
> + * The `--env` console option and its "-e" shortcut have been deprecated,
good catch, fixed

2018-10-03 08:44 UTC, fabpot approved these changes

2018-10-03 08:46 UTC, fabpot commented
Thank you @chalasr.

2018-10-03 08:46 UTC, merged

2018-10-07 14:07 UTC, weaverryan commented
Can you open a docs issue / or?

2018-10-07 14:45 UTC, chalasr commented
@weaverryan sorry, forgot about it. Just opened https://github.com/symfony/symfony-docs/issues/10444

2018-10-08 12:06 UTC, ogizanagi commented
@gnugat : This was discussed a bit a long time ago. Here is a Fabien's https://github.com/symfony/symfony/issues/23343#issuecomment-345609612 mentioning this.
Note there is no BC break here, as it's still supported until 5.0. It'll be considered a BC break when removing it at time `master` becomes the v5 branch. For now, this is only a deprecation.

2018-10-08 15:50 UTC, chalasr commented
@gnugat link added to the PR body, sorry about that

2018-10-24 20:15 UTC, c33s commented
this is really a bad decision, it makes the use on windows much more complicated. this is really a very bad DX.

```
php bin/console --env=dev
Symfony 3.4.12 (kernel: src, env: dev, debug: true)
(fully working symfony console with no errors)
```
vs
```
APP_ENV=dev php bin\console
'APP_ENV' is not recognized as an internal or external command,
operable program or batch file.
```
vs
```
λ cmd /V /C "set APP_ENV=dev&& php bin\console"
 [WARNING] Some commands could not be registered:
In EnvVarProcessor.php line 76:
  Environment variable not found: "DATABASE_URL_LEGACY".
Symfony 3.4.12 (kernel: src, env: dev, debug: true)
---snip---
In EnvVarProcessor.php line 76:
  Environment variable not found: "APP_SECRET".
```
also the handy autocomplete possibility with clink on windows and bash-completion on linux is gone with this change. environment variables are cool but not the holy grail for everything. there is a reason for having flags on commands. imagine you have to call all commands like this:

```
URL=http://example.com RECURSIVE=true OUTPUT_FILE=foo.html wget
```
please revert this.

2018-10-24 20:34 UTC, nicolas-grekas commented
@c33s can you please open a separate issue? Commenting on anything closed is likely going to get low traction.

2018-11-13 19:15 UTC, nicolas-grekas commented
Reverted in #29204