[Messenger] WIP: Add a redis transport
symfony/symfony pull request #28681
Opened 2018-10-02 10:35 UTC by soyuka

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes 
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | not yet added!
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | TODO symfony/symfony-docs#... 

Hi!

This patch adds a redis transport to the Messenger component by using the official php redis-ext (https://github.com/phpredis/phpredis). It's a port of https://github.com/soyuka/symfony-messenger-redis to be included directly in symfony.

### How it works

Relevant discussion: https://twitter.com/jderusse/status/980768426116485122

The sender uses a `List` with `RPUSH` (add value to the tail of the list). 
The receiver uses `BRPOPLPUSH` which reads the last element of the list and adds in to the head of another list (`queue_processing`). If no elements are present it'll block the connection until a new element shows up or the timeout is reached. When timeout is reached it works like a "ping" of some sort (calls `$handler(null)`). 

On every iteration, we will check the `queue_processing` list. For every items in this queue we have a corresponding `key` in redis with a given `ttl`. 
If the key has expired, the item is `LREM` (removed) from `queue_processing` and put back in the origin queue to be processed again. This workaround helps to avoid loosing messages.

### Difference with AmqpExt

I'm proposing this feature as a Work In Progress because I'm not sure how I should handle the queue.
Indeed, in AmqpExt the queue is tight to the Connection whereas here, a queue should be linked to a message. 
It can work by using the same queue for different messages but I'd not advise to do this because it's messy if you need to maintain your queues afterwards (for example if you want to remove only the queue for message `X` you should just remove queue `X`).

What do you think? I can make the queue resilient inside the `Connection` class so that the code is closer to `AMQPExt\Connection` (means opening 1 connection per messages) or keep the queue inside the `Receiver`/`Sender` (one connection only).

When we find an agreement about this I'll add some tests and remove my WIP flag.

Thanks!

2018-10-02 14:50 UTC, ragboyjr commented
@soyuka This isn't necessarily directed at you, but I think just re-queing failed items or items that have been left in processing too long isn't a very safe way to go about this.

In my experience, when a message/task fails, it almost always fails again when re-run, and you end up just having 6 failed attempts instead of the one. And in some cases, if your system is connecting to external systems, it could end up causing unwanted duplicate data.

Not saying that retrying isn't a useful feature, but I think it should be something that should at least have the option to be turned off or maybe put into a failed jobs log or table.

2018-10-02 15:07 UTC, ragboyjr commented
https://github.com/krakphp/symfony-messenger-redis Here is the redis bundle I made and I admittedly copied several aspects of the redis part between the https://github.com/krakphp/job and your bundle.

2018-10-02 15:10 UTC, soyuka commented on src/Symfony/Component/Messenger/Transport/RedisExt/Connection.php
> +    public function waitAndGet(string $queue, int $processingTtl = 10000, int $blockingTimeout = 1000): ?array
Cool, are you suggesting that we should add some kind of test to ensure that the ttl is < 60 seconds? Do you set the `\Redis::OPT_READ_TIMEOUT` to `-1`?

2018-10-02 15:14 UTC, soyuka commented
>  but I think it should be something that should at least have the option to be turned off or maybe put into a failed jobs log or table.

Definitely! 

I see that in your bundle you're using one queue per connection, therefore you are storing different kinds of messages on the same queue. Isn't this an issue while debugging or maintaining these lists? Do you have an opinion about this?
Thanks for the early comments!

2018-10-02 15:21 UTC, ragboyjr commented
@soyuka Well no because it's more like one queue per transport.

```
framework:
  messenger:
    transports:
      main:
        dsn: '%env(TRANSPORT_DSN)%'
        options:
          queue: queue_main
      secondary:
        dsn: '%env(TRANSPORT_DSN)%'
        options:
          queue: queue_secondary
    routing:
      App\MainMessage: main
      App\SecondaryMessage: secondary
```

That would be an example configuration. This definitely allows multiple types of messages for a single queue/transport, but that just depends on how you want to scale out your transports. Some not so frequent messages can go on the main queue, but maybe a heavy traffic message might go on it's own so it can have a dedicated consumer and not get blocked.

2018-10-03 22:27 UTC, ragboyjr commented on src/Symfony/Component/Messenger/Transport/RedisExt/Connection.php
> +        $queue = isset($parsedUrl['path']) ? trim($parsedUrl['path'], '/') : 'messages';
Curious if it'd be better to put the queue apart of the DSN vs the options? Personally I prefer to use one DSN configured in the .env, and then re use it across multiple transports while changing the queue parameter in options.

Maybe we could support both? allow queue in the query param, but allow it to be overridden via the options?

2018-10-03 22:28 UTC, ragboyjr commented
@soyuka Extension looks great! Thanks for the hard work!

2018-10-03 22:39 UTC, ragboyjr commented
@soyuka in regards to Requeing the message by default and Rejecting if it implements a RejectMessageExceptionInterface

I think it would make more sense to default to Reject, and requeue if they implement a RequeueMessageExceptionInterface; however, that's my opinion for reasons as stated previously in this thread. If we end up sticking with defaulting to Requeue, do you think it would make sense to add a middleware/option in the messenger config to basically wrap all exceptions into a RejectMessageExceptionInterface?

2018-10-08 07:59 UTC, soyuka commented on src/Symfony/Component/Messenger/Transport/RedisExt/Connection.php
> +        );
Connect doesn't seem to support the db though: https://github.com/phpredis/phpredis#connect-open

2018-10-08 08:00 UTC, soyuka commented on src/Symfony/Component/Messenger/Transport/RedisExt/Exception/RejectMessageExceptionInterface.php
> +}
Would make sense, especially if we want to switch from one transport to another without changing the code.

2018-10-08 08:15 UTC, soyuka commented
> do you think it would make sense to add a middleware/option in the messenger config to basically wrap all exceptions into a RejectMessageExceptionInterface?

Looks a bit too magic to me. I definitely get your concerns about requeuing though, and I'd be in favor of having a `RequeueMessageExceptionInterface`, with the default behavior set to rejecting messages that fail.

2018-11-06 21:08 UTC, Siregacvek commented on src/Symfony/Component/Messenger/Transport/RedisExt/Connection.php
> +        );
@soyuka may be Im wrong, but phpRedis can deal with databases. Look here how snc_redis do this:
https://github.com/snc/SncRedisBundle/blob/863a063114c68e62fea811c127f093a1ecd5ba9a/Factory/PhpredisClientFactory.php#L73

2018-11-06 21:15 UTC, Siregacvek commented on src/Symfony/Component/Messenger/Transport/RedisExt/Connection.php
> +        );
Database selecting in phpRedis doc https://github.com/phpredis/phpredis#select

2018-12-09 04:30 UTC, ragboyjr commented
@soyuka with the release of redis streams in redis 5.0, i'm wondering if we should target that data structure for a more robust implementation. We also could possibly implement two different redis connections one for streams and one with lists.

2019-03-23 14:15 UTC, weaverryan commented
Ping @soyuka! If you're still willing to work in this, we just merged #30557, which clarifies what a transport needs to do / behave (should simplify the receiver a bit). I would love to see this PR updated!

2019-03-25 11:50 UTC, soyuka commented
Will definitely work on this thanks for the heads up, any idea if the related documentation is going to be updated?

2019-03-25 16:35 UTC, weaverryan commented
@soyuka Awesome!

> I've looked at the PR, messenger is improving that's nice! I've an issue with the new interface though, because my Connection doesn't uses a Enveloppe for now (in receive I'm working on a message, not an Envelope).

Can you tell me more about this? Or you can ping me on Slack. Do you mean the methods like `ReceiverInterface::ack(Envelope $envelope)`? If that's true, it shouldn't be a problem because your receiver is not responsible for calling this anymore - the `Worker` will call this and it will pass you the Envelope. If you need some sort of "identifier" so you know which message to ack (you will), you should add a stamp to the Envelope before passing it to `$handler`. Check out the AmqpReceiver. We wrap in a custom stamp (https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Messenger/Transport/AmqpExt/AmqpReceiver.php#L73) then use that in `ack()` and `reject()` to know which message was received, so we can ack/reject it.

2019-03-27 10:09 UTC, alexander-schranz commented
Maybe interesting we did build redis using Symfony Messenger some time ago it uses the redis 5 stream feature: https://github.com/handcraftedinthealps/RedisTransportBundle

2019-03-27 10:25 UTC, soyuka commented
I'm really not sure that we need the redis streams complexity here, do you have pros/cons compared to the solution here?

2019-03-27 10:37 UTC, alexander-schranz commented
@soyuka I don't think that streams are complex in case of the php implementation as most things is handled by redis itself and groups are awesome if you have multiple systems receiving the same messages. For I see no cons for streams as they are build more for messages the only con is that it only works with redis 5 and ext-redis 4.2. But I'm nobody so I can't do a decision here, just wanted to mention it here, thought the implemtation could maybe help.

2019-03-27 12:02 UTC, sroze commented
> groups are awesome if you have multiple systems receiving the same messages

I have no idea what these streams are all about, what is the awesomeness of them in this use-case? When you say that "most things is handled by redis itself" that sounds appealing... but what do you mean exactly? What are the use-cases/logic we wouldn't have to implement anymore?

> the only con is that it only works with redis 5 and ext-redis 4.2.

`ext-redis` 4.2 has been released on the 2018-11-20 so I don't see this as an issue. The 4.3 has also been released and is considered as stable. Though, do you know what's the Redis 5 availability in most of the cloud providers?

2019-03-27 13:34 UTC, soyuka commented
> I don't think that streams are complex in case of the php implementation

I just looked at the [redis introduction](https://redis.io/topics/streams-intro) and it seems to have more features compared to using a normal list. This was the complexity I was talking about, not the one from the php implementation.
  
> But I'm nobody so I can't do a decision here, just wanted to mention it here, thought the implemtation could maybe help.

Everyone's thought is appreciated! I wasn't even aware that redis had implemented this feature, so thanks for the discovery and I'll definitely take a look at your implementation!

2019-03-27 15:17 UTC, ragboyjr commented
My only concern with using streams (other than the additional complexity), is that forcing the use of the ext-redis extension can be an issue under heavier workloads. 

We were getting intermittent errors and failures on redis consumer with sf messenger and after some investigation, it looks like they are just related to the redis-ext and those errors don't occur on predis.

https://github.com/phpredis/phpredis/issues/831
https://github.com/nrk/predis/issues/524#issuecomment-434774559

After we switched, those intermittent errors all went away..., However, predis doesn't seem actively maintained, It's a good library and seems to be more reliable than phpredis, but nrk/predis hasn't touched that repo in forever. Makes me think that a reliable fork or a new maintainer might be necessary for that library.

2019-03-27 15:59 UTC, soyuka commented
@ragboyjr if we want this to get merged into symfony we have to use the official `ext-redis`, we can't introduce a dependency to a third party because of maintenance issues.

2019-03-27 21:08 UTC, alexander-schranz commented
> I have no idea what these streams are all about, what is the awesomeness of them in this use-case? When you say that "most things is handled by redis itself" that sounds appealing... but what do you mean exactly? What are the use-cases/logic we wouldn't have to implement anymore?

Lets say you have 3 Systems. System A is sending messages and System B and C want to receive this messages. When you want that B and C receive both all messages without redis streams you need to implement that logic yourself or sending them into 2 lists or something (correct me if I'm wrong). With redis streams you can just create 2 groups. one for system b and one for system c and redis will give you the messages which you did not receive yet. 

I personally found it really simple adding a new messages to a stream can be done with: 

```php
$this->redis->xAdd('STREAMNAME', '*', ['content' => json_encode($encodedMessage)]);
```

Reading the message can be done with:

```php
$messages = $this->redis->xReadGroup('GROUPB', 'CONSUMER1', [$this->stream => 0], 1, 45);
```

Redis automatically sets the read messages into a pending state for this group so if you example have for the same group multiple consumer they will not get the same message again.

And after you did successfully process the message you mark it in your group as acked:

```php
$this->redis->xAck('STREAMNAME', 'GROUPB', [$messageId]);
```

So if you later need a System D also receiving all messages you just create in redis a GroupD and so system D is also starting to receive all messages.

So streams will shine if you have multiple systems receiving messages. If you just have 2 Systems a Sender and a Receiver there will be no differents. But if you have multiple receivers Redis will handle you which group/system did receive a message and which one doesn't. 

The following is also a interesting block post about streams: https://brandur.org/redis-streams.

But maybe I have to less knowledge about the current implementation and maybe it makes sense to have 2 redis transports one using the redis list's and one using redis streams.

2019-03-28 01:41 UTC, sroze commented
Indeed, if there is this logic of parking the messages until they are acknowledged, this sounds very interesting because the less we have to deal with these distributed system issues, the better 🙃

2019-03-28 15:42 UTC, soyuka commented
@alexander-schranz many thanks about this detailed explanation, it helped me to understand better why redis streams may be good for this use case! I'll definitely look into that and use them in this transport implementation!

2019-03-28 23:28 UTC, ragboyjr commented
@soyuka I think the SF Lock and SF Cache component are able to utilize both redis libraries, i'd imagine if we did a redis transport using the list strategy, we should be able to provide some sort of compat layer to using either of the redis libraries.

I'd be willing to help if needed, but as someone who has used a redis transport with messenger at a high volume on both ext-redis and predis, I wouldn't feel comfortable only allowing ext-redis.

2019-04-03 17:03 UTC, weaverryan commented
Ping! Do we have some direction/motivation/time to finish this? We're after feature freeze, though there is some wiggle room probably because this component is experimental.

2019-04-03 21:53 UTC, soyuka commented
> Ping! Do we have some direction/motivation/time to finish this? We're after feature freeze, though there is some wiggle room probably because this component is experimental.

To me, time is an issue, maybe this week-end but definitely not sooner. Also, the streams must be tested they may improve the transport a lot, which means more work.

2019-04-04 11:38 UTC, weaverryan commented
> To me, time is an issue

I hear that :). Good candidate maybe for the hackathon this weekend, if not by you - by someone else? We could check to see if anyone has the expertise & is interested.

Cheers!

2019-04-04 11:43 UTC, soyuka commented
I'd love to work on this this week end but as I'm the Api Platform referent I'm not sure that I'll be able too :p.

2019-04-04 12:21 UTC, alexander-schranz commented
@weaverryan @soyuka I will have a look at the current state at the `EU-FOSSA Hackathon` and will then refractor it to use the redis stream functions.

2019-04-04 16:53 UTC, weaverryan commented
Added the hackathon star - thank you @alexander-schranz!

2019-04-06 10:45 UTC, alexander-schranz commented
Analysed the current state and after also having a look at the new ReceiverInterface and playing around about it my concept will be the following:

```
+-----------R
|    GET    | -> XREADGROUP
+-----------+
      |
      V
+-----------+  No
|  failed?  |---------------------------+
+-----------+                           |
      |                                 |
      | Yes                             |
      V                                 |
+-----------+  No                       |
|   retry?  |---------------------------+
+-----------+                           |
      |                                 |
      | Yes                             |
      V                                 V
+-----------R                    +-----------R
|   REJECT  | -> XACK            |    ACK    | -> XACK
+-----------+                    +-----------+
```

**GET**: Will use `XREADGROUP` to read the one  message from the stream
**REJECT**: Reject will just remove the message with `XACK` from the stream as adding it back to the stream is handled by symfony worker itself
**ACK**: Will use the `XACK` Method to ack the message for the specific group

The sender will still be simple by calling the `XADD` redis function.

#EU-FOSSA

2019-04-06 11:14 UTC, weaverryan commented
I don't know about the Redis streams part, but I can confirm the rest of the diagram is perfect: you're acking/nacking with the correct logic.

2019-04-06 12:37 UTC, sroze commented
@alexander-schranz great. Fancy updating this pull-request (or creating another one)?

2019-04-06 13:23 UTC, alexander-schranz commented
@sroze If I can I will update this PR so we have all discussion about it here.

2019-04-06 14:21 UTC, Nyholm requested changes
Cool. I like this. I will test this later.

2019-04-06 14:21 UTC, Nyholm commented on src/Symfony/Component/Messenger/Transport/RedisExt/Connection.php
> +        $key = md5($value['body']);
`sha1` is quicker. I think we should use that one instead.

2019-04-06 14:21 UTC, Nyholm commented on src/Symfony/Component/Messenger/Transport/RedisExt/Connection.php
> +        $key = md5($message['body']);
`sha1`

2019-04-06 14:21 UTC, Nyholm commented on src/Symfony/Component/Messenger/Transport/RedisExt/Connection.php
> +     * @TODO: log something?
This should be removed or addressed.

2019-04-06 14:21 UTC, Nyholm commented on src/Symfony/Component/Messenger/Transport/RedisExt/Connection.php
> +        $key = md5($message['body']);
`sha1`

2019-04-06 14:21 UTC, Nyholm commented on src/Symfony/Component/Messenger/Transport/RedisExt/Connection.php
> +     * Add item at the tail of list.
This comment is wrong. We are doing a queue and not a stack. =)

We are adding items to the **head** of the list. 

Using `lpush` is correct.

2019-04-06 14:21 UTC, Nyholm commented on src/Symfony/Component/Messenger/Transport/RedisExt/Connection.php
> +            $key = md5($temp['body']);
`sha1`

2019-04-06 14:50 UTC, soyuka commented
Please feel free to update it!

2019-04-06 16:29 UTC, alexander-schranz commented
I'm not able to push into @soyuka's fork so I created a new PR #30917
/cc @Nyholm @sroze

2019-04-06 16:48 UTC, soyuka commented
Closing this one then!

2019-04-06 16:48 UTC, closed without merging