[DependencyInjection] Optimize exporting variables
symfony/symfony pull request #28737
Opened 2018-10-05 12:49 UTC by svandervlugt

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no  
| Deprecations? | no 
| Tests pass?   | yes   
| Fixed tickets | #28292 
| License       | MIT

Store previously resolved variables so that the relatively expensive function [resolveEnvPlaceholders](https://github.com/symfony/symfony/blob/3e7b029524bf724abfd603c17795af39bb289615/src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php#L1776) is not called unnecessarily.

The effect on running ```bin/console``` with an empty cache in a big application (200+ env variables) in seconds:

| Before     | After      |
|------------|------------|
| 24.1       | 15.8       |
| 24.5       | 16.0       |
| 24.7       | 16.3       |
| 24.2       | 16.0       |
|  Avg: 24.4 | Avg:16.0   |

2018-10-05 19:01 UTC, ostrolucky requested changes

2018-10-05 19:01 UTC, ostrolucky commented on src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php
> +        if ($resolveEnv && \is_string($value) && array_key_exists($value, $this->exportedVariables)) {
result of `$resolveEnv && \is_string($value)` can be saved into variable so it doesn't need to be evaluated later again

2018-10-05 19:01 UTC, ostrolucky commented on src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php
> +        if ($resolveEnv && \is_string($value) && \is_string($export)) {
There doesn't seem to be reason to use `\is_string($export)`

2018-10-06 17:47 UTC, nicolas-grekas requested changes
Thanks for the PR, I confirm a 5% improvement (and a 5% peak memory increase on my case)
in addition to @ostrolucky's comment, we should also empty the new property when leaving the dump function.

2018-10-08 09:50 UTC, svandervlugt commented
I don't know why 2 of the 3 travis CI builds suddenly fail. I'm not sure whether this is related to my changes as they are in the Lock-component and the Translator in the FrameworkBundle.

2018-10-08 19:54 UTC, nicolas-grekas commented on src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php
> +        $this->exportedVariables = array();
This should be duplicated L127 above

2018-10-10 08:09 UTC, svandervlugt commented
Another failing build. Still not convinced it is my changes.
appveyor was successful before my last commit, now fails with  ```..KO src\Symfony/Bundle/SecurityBundle```. and no further error.

One of the three travis-builds fails on the FrameworkBundle, Translation component and Validator component. Before each of these a ```  - Installing symfony/dependency-injection (dev-master 88f240c): Loading from cache``` is done. Doesn't this effectively overwrite my changes?

2018-10-10 08:23 UTC, ostrolucky approved these changes

2018-10-16 12:37 UTC, svandervlugt commented
@nicolas-grekas the PR has been updated with the requested changes. 
After the last rebase all checks have passed.

2018-10-16 12:52 UTC, nicolas-grekas approved these changes

2018-10-23 06:16 UTC, dunglas approved these changes

2018-10-23 07:22 UTC, merged