Add a messenger middleware to enforce null results
symfony/symfony pull request #28758
Opened 2018-10-07 10:37 UTC by polc

| Q             | A
| ------------- | ---
| Branch?       | master 
| Bug fix?      | no
| New feature?  | yes 
| BC breaks?    | no     
| Deprecations? | no 
| Tests pass?   | yes    
| Fixed tickets | #27839   
| License       | MIT
| Doc PR        |  

A little middleware to make sure a message bus doesn't return any result.

2018-10-07 10:47 UTC, sroze requested changes
Sounds reasonable to have this in core to me. Can you also send a documentation pull-request? 🙏

2018-10-07 10:47 UTC, sroze commented on src/Symfony/Component/Messenger/Middleware/EnforceNullResultMiddleware.php
> +            throw new NonNullResultException(sprintf('Non null result for message %s.', \get_class($message)));
```patch
- Non null result for message %s.
+ Non null result for message "%s": at least one handler returned something but this is prohibited by this middleware.
```

2018-10-07 11:13 UTC, polc commented
Thanks for the suggestion ! Doc: https://github.com/symfony/symfony-docs/pull/10442

2018-10-07 20:29 UTC, azjezz approved these changes

2018-10-08 17:56 UTC, javiereguiluz commented
@sroze do you like the proposed name? `EnforceNullResultMiddleware`  I find it a bit long and convoluted. What about `NoResultMiddleware` or `NullResultMiddleware` or ...?

2018-10-08 18:38 UTC, ogizanagi commented
@javiereguiluz : For myself, I find `EnforceNullResultMiddleware` really clear about the intention. `NoResultMiddleware` or `NullResultMiddleware` describe facts, not purposes.

2018-10-21 12:50 UTC, sroze commented
This will stay the case, as the messenger bus now returns `null` (see #28909). Closing :)

2018-10-21 12:50 UTC, closed without merging