Feature: [Form] Toggle Displaying Percent Type Symbol
symfony/symfony pull request #28797
Opened 2018-10-09 20:04 UTC by dohpaz42

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #28796
| License       | MIT
| Doc PR        | symfony/symfony-docs#10464 

### PercentType `symbol` option
As of this writing, Symfony will forcibly append a percentage sign (`%`) to all input fields that are of the `PercentType` form type. This PR will introduce a boolean flag called `symbol` that, when `false`, will not display the percentage sign. Each of the default layouts that define `percent_widget` will respect this option.

By default, this new option will be set to `true` so that it maintains backward compatibility. The unit tests have been updated where appropriate, and a new unit test has been added (as appropriate).

2018-10-10 08:15 UTC, xabbuh requested changes
This looks quite good so far. I have just left a few comments.

Can we think of use cases where you would want to display another symbol than the percent character (then it could make sense to allow arbitrary strings for this option)?

2018-10-10 08:15 UTC, xabbuh commented on src/Symfony/Bundle/FrameworkBundle/CHANGELOG.md
> + * Only display `PercentType` percent symbol if the `symbol` option is `true`
I don't think we need a changelog entry for this in the FrameworkBundle.

2018-10-10 08:15 UTC, xabbuh commented on src/Symfony/Bridge/Twig/Resources/views/Form/bootstrap_4_layout.html.twig
> +    {% if symbol == true %}
let's shorten this: `{% if symbol %}` (and everywhere else below too)

2018-10-10 08:15 UTC, xabbuh commented on src/Symfony/Bridge/Twig/Resources/views/Form/bootstrap_4_layout.html.twig
> +    {% if symbol == true %}
It also seems like we need to take whitespace control (`i.e.` the `-` character) into account here too.

2018-10-10 08:15 UTC, xabbuh commented on src/Symfony/Bridge/Twig/CHANGELOG.md
> + * Update `percent_widget` to consider `symbol` option for `PercentType` when displaying the percent symbol
I don't think we need such an entry in the changelog file of the Twig bridge

2018-10-10 08:15 UTC, xabbuh commented on src/Symfony/Component/Form/CHANGELOG.md
> + * add `symbol` to `PercentType` options and make available as `FormView` vars
I would reword this a bit:

> added a `symbol` option to the `PercentType` that allows to disable the output of the percent character

2018-10-10 08:15 UTC, xabbuh commented on src/Symfony/Component/Form/Extension/Core/Type/PercentType.php
> +            'symbol' => true,
we should restrict the allowed types to `bool`:

```php
$resolver->setAllowedTypes('symbol', 'bool');
```

2018-10-10 08:15 UTC, xabbuh commented on src/Symfony/Component/Form/Extension/Core/Type/PercentType.php
> +        $view->vars['symbol'] = isset($options['symbol']) ? $options['symbol'] : true;
Can be shortened as the option will always be set:

```php
$view->vars['symbol'] = $options['symbol'];
```

2018-10-10 12:05 UTC, dohpaz42 commented
> Can we think of use cases where you would want to display another symbol than the percent character (then it could make sense to allow arbitrary strings for this option)?

I missed finding this yesterday, but apparently there are a few [different versions of a percent symbol](https://en.wikipedia.org/wiki/Percent_sign#Encodings):

> U+0025 % Percent sign (HTML &#37;) (&percnt; in HTML5[24]),
> U+2030 ‰ per mille sign (HTML &#8240; · &permil;),
> U+2031 ‱ per ten thousand sign (HTML &#8241;) a.k.a. basis point, and
> U+FF05 ％ fullwidth percent sign (HTML &#65285; · see fullwidth forms)
> U+FE6A ﹪ small percent sign (HTML &#65130; · see Small Form Variants)
> There is also U+066A ٪ ARABIC PERCENT SIGN (HTML &#1642;), which has the circles replaced by square dots set on edge, the shape of the digit 0 in Arabic numerals.

And there are [icons](https://fontawesome.com/v4.7.0/icon/percent). Unless others object, I'll update the PR later today to allow arbitrary text or boolean false.

2018-10-10 19:35 UTC, OskarStark requested changes

2018-10-10 19:35 UTC, OskarStark commented on src/Symfony/Bridge/Twig/Resources/views/Form/bootstrap_4_layout.html.twig
> +    {{- block('form_widget_simple') -}}
could you please add more indention?

2018-10-10 19:35 UTC, OskarStark commented on src/Symfony/Bridge/Twig/Resources/views/Form/bootstrap_4_layout.html.twig
>      <div class="input-group">
could you please add more indention?

2018-10-10 19:35 UTC, OskarStark commented on src/Symfony/Bridge/Twig/Resources/views/Form/bootstrap_4_layout.html.twig
> +    {{- block('form_widget_simple') -}}
Same for the other twig parts

2018-10-12 12:56 UTC, dohpaz42 commented
As for the failed unit tests, I could use some guidance on how to set up an environment and/or execute the tests so that I can reproduce their failures.

2018-11-01 17:09 UTC, xabbuh commented
@dohpaz42 Sorry, I missed your question. I think https://symfony.com/doc/current/contributing/code/tests.html should provide some useful insights.

2019-02-15 18:53 UTC, xabbuh commented
@9ae8sdf76 Do you think you will be able to finish this pull request?

2019-03-04 07:11 UTC, fabpot commented
@xabbuh Can you take over this one?

2019-03-04 07:47 UTC, OskarStark commented
I could overtake this too, I just need to know what’s featurewise missing here?

2019-03-04 08:28 UTC, fabpot commented
@OskarStark Thank you. I think it's ok feature-wise. It's more about rebasing/squashing and fixing tests if needed after that.

2019-03-04 09:22 UTC, OskarStark commented
Done in #30433 

This one can be closed

2019-03-04 09:25 UTC, closed without merging