[Serializer] Normalize constraint violation parameters
symfony/symfony pull request #29130
Opened 2018-11-07 18:01 UTC by ogizanagi

| Q             | A
| ------------- | ---
| Branch?       | master 
| Bug fix?      | no
| New feature?  | yes 
| BC breaks?    | no     
| Deprecations? | yes/no 
| Tests pass?   | yes    
| Fixed tickets | N/A   
| License       | MIT
| Doc PR        | N/A?

Adding violation constraints' parameters to the normalized data, as these are valuable for an API client.

I used `parameters` for now, as it's the name used in `ConstraintViolationInterface::getParameters()`, but what about `placeholders` or `context`?

2018-11-07 21:13 UTC, dunglas approved these changes

2018-11-08 08:29 UTC, juliendufresne approved these changes

2018-11-08 10:39 UTC, ogizanagi commented
Note: adding this by default might break CI testing API endpoint responses, but I don't see much more reasons not to do so. So, better keep adding by default, or add a context option for this?

2018-11-08 20:51 UTC, dunglas commented
We don't guarantee that the output of the normalizers will never change. Especially, we don't guarantee that will not add fields. I'm in favor of adding it by default, but only if at least one parameter exists.

2018-11-08 20:53 UTC, dunglas approved these changes

2018-11-08 20:53 UTC, dunglas commented on src/Symfony/Component/Serializer/Normalizer/ConstraintViolationListNormalizer.php
> +                'parameters' => $violation->getParameters(),
We should only add this key if at least one parameter exists:

```php
if ($parameters = $violation->getParameters()) {
    $violationEntry = $parameters;
}
```

2018-11-08 20:54 UTC, dunglas requested changes

2018-11-08 20:54 UTC, dunglas commented on src/Symfony/Component/Serializer/Normalizer/ConstraintViolationListNormalizer.php
> +                'parameters' => $violation->getParameters(),
We should only add this key if at least one parameter exists:

```php
if ($parameters = $violation->getParameters()) {
    $violationEntry = $parameters;
}
```

2018-11-09 07:57 UTC, lyrixx approved these changes

2019-01-25 09:04 UTC, dunglas approved these changes
Let's merge it as is. Can you rebase please?

2019-02-24 11:07 UTC, ogizanagi commented
Now rebased :)

2019-03-13 15:54 UTC, nicolas-grekas approved these changes

2019-03-13 16:10 UTC, lyrixx approved these changes

2019-03-16 01:03 UTC, lyrixx commented
this one is OK too. let's merge it. /cc @dunglas (easy pick)

2019-03-17 07:12 UTC, fabpot approved these changes

2019-03-17 07:15 UTC, fabpot commented
Thank you @ogizanagi.

2019-03-17 07:15 UTC, merged