[Request] [Documentation] clarify that isMethodCacheable() returns true only for GET & HEAD
symfony/symfony pull request #29295
Opened 2018-11-23 15:48 UTC by tamc

| Q             | A
| ------------- | ---
| Branch?       | 2.8
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no 
| Deprecations? | no 
| Tests pass?   | yes 
| Fixed tickets | na
| License       | MIT

The current documentation points to https://tools.ietf.org/html/rfc7231#section-4.2.3.

The spec says: "this specification defines GET, HEAD, and POST as cacheable, although the overwhelming majority of cache implementations only support GET and HEAD.". 

This fix to the documentation clarifies that Symfony follows majority (excluding POST) rather than the spec (including POST).

2018-11-24 07:28 UTC, fabpot requested changes

2018-11-25 11:27 UTC, nicolas-grekas approved these changes

2018-11-26 06:39 UTC, fabpot approved these changes

2018-11-26 06:40 UTC, fabpot commented
Thank you @tamc.

2018-11-26 06:40 UTC, merged