[Form] filter out invalid language values
symfony/symfony pull request #29500
Opened 2018-12-07 15:34 UTC by xabbuh

| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #23679
| License       | MIT
| Doc PR        |

2018-12-07 16:58 UTC, HeahDude requested changes
We miss other choice fields that rely on the same optimized implementation.

2018-12-08 15:47 UTC, stof approved these changes

2018-12-08 15:49 UTC, HeahDude approved these changes

2018-12-08 16:20 UTC, nicolas-grekas commented
Thank you @xabbuh.

2018-12-08 16:20 UTC, merged