Always display container deprecations in simple phpunit
symfony/symfony pull request #29519
Opened 2018-12-08 12:43 UTC by l-vo

| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets |
| License       | MIT
| Doc PR        |

When the container is not built or not fresh, simple-phpunit may trigger deprecations which occured during container built. If simple-phpunit is launched again, the deprecations are not displayed since the container hasn't be built this time.

Deprecations can make tests fail. So the behavior is currently inconsistent. With the same code base, the tests may pass if the container has been built before and may fail if the container is built during the process.

The suggested fix is to retrieve container compile deprecations from a file created by Symfony. It's the file which is used to display container compile deprecations in Logger data collector.

2018-12-08 15:53 UTC, nicolas-grekas commented
This should be considered as a new feature IMHO.
Since this might be too specific to Symfony functional test cases, would it make sense to move this feature to the KernelTestCase instead of the bridge?

2018-12-10 21:01 UTC, l-vo commented
@nicolas-grekas I'm not sure I fully understand. Do you mean that KernelTestCase should catch container compile deprecation and display it (although other deprecations will be displayed by PHPUnit bridge)  ?

2018-12-10 21:05 UTC, nicolas-grekas commented
KernelTestCase could eg open that file and @trigger_error() them - or call the deprecation handler if possible?

2018-12-10 21:34 UTC, l-vo commented
I can't use trigger_error since I would lose original line number information. But maybe I can deal with registered error handler. I'm going to try that, thank you :)

2018-12-11 15:53 UTC, l-vo commented
status: needs work

2018-12-13 21:00 UTC, l-vo commented
status: needs work

2019-03-31 08:41 UTC, fabpot commented
@l-vo What's the status of your PR?

2019-03-31 09:07 UTC, l-vo commented
@fabpot there is more work than I originally thought. I recently didn't have the time to continue this PR but I didn't forget it :) I'm going back to work on it very soon :)

2019-03-31 09:11 UTC, fabpot commented
@l-vo thanks for the feedback.

2019-05-16 16:16 UTC, l-vo commented
status: needs review

2019-07-08 12:30 UTC, nicolas-grekas commented
Sorry I didn't look close enough before. There is no reason why the phpunit-bridge should know anything about KernelTestCase. Let's find a proper way that would decouple things. There is already some code infrastructure that deals with serialized deprecations passed via messages. Can't we improve this to achieve what is needed here.

2019-07-30 19:38 UTC, nicolas-grekas requested changes
I think this shouldn't be on phpunit-bridge's side.
Let's have some logic in a base test-case (`KernelTestCase`?) that triggers those to load the file and trigger the deprecations there.

2019-08-03 09:41 UTC, l-vo commented
@nicolas-grekas I'm not sure to understand. If we put the logic into KernelTestCase (without coupling with phpunit-bridge), we'll lose the logic of the [Deprecation](https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/PhpUnit/DeprecationErrorHandler/Deprecation.php) class of phpunit-bridge ?

2019-08-03 09:54 UTC, nicolas-grekas commented
You mean: being able to differentiate direct vs indirect deprecations, right? But can't we triggered a serialized message as [allowed by the bridge](https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/PhpUnit/DeprecationErrorHandler/Deprecation.php#L82) to fix that?

2019-08-09 18:48 UTC, l-vo commented
@nicolas-grekas sorry if I miss something... We can trigger a serialized message, but we must determine in the bridge the message source. It's what is done [here](https://github.com/symfony/symfony/blob/bf17514ce7be134804eb80e48ce5b3c9eb977abd/src/Symfony/Bridge/PhpUnit/DeprecationErrorHandler/Deprecation.php#L99), but it's also what introduces the coupling with KernelTestCase.

2020-02-03 15:51 UTC, nicolas-grekas commented
I'm closing because this would apparently add a lot of complexity for a case that happens to be solvable in other ways. There are other strategies to get the deprecations. It would be nice to achieve the goal here, but not at all costs.
Thanks for giving it a try.

2020-02-03 15:51 UTC, closed without merging