[Validator] Added IBAN format for Vatican City State
symfony/symfony pull request #29531
Opened 2018-12-08 15:11 UTC by raulfraile

IBAN for Vatican City State was added to [IBAN registry](https://www.swift.com/sites/default/files/resources/iban_registry.pdf) recently. This PR adds support for this new format in the `Iban` validator.

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| License       | MIT

2018-12-08 15:35 UTC, ostrolucky commented
I think patches like these are treated as bugfixes, so should be targetting 3.4

2018-12-08 21:00 UTC, fabpot requested changes

2018-12-08 21:00 UTC, fabpot commented on src/Symfony/Component/Validator/CHANGELOG.md
> + * added support for Vatican City State IBAN format
Should be removed when rebased on 3.4 (as this should indeed be considered as a bug fix).

2018-12-09 09:58 UTC, raulfraile commented
@fabpot thanks for the comments! It's now rebased and targetting `3.4`

2018-12-09 10:01 UTC, fabpot approved these changes

2018-12-09 10:02 UTC, fabpot commented
Thank you @raulfraile.

2018-12-09 10:02 UTC, merged