[Routing] Allow force-generation of trailing parameters using eg "/exports/news.{!_format}"
symfony/symfony pull request #29599
Opened 2018-12-13 23:57 UTC by luchaninov

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #29593
| License       | MIT

When a route is defined as path: `/exports/news.{!_format}`, we should force `_format` be defined in `defaults` and the generator should generate URLs with that default when none is provided (should work with any parameter of course).

2018-12-14 08:21 UTC, nicolas-grekas approved these changes
awesome! just a minor comment and good on my side!

2018-12-14 08:27 UTC, stloyd requested changes

2018-12-14 08:45 UTC, nicolas-grekas commented on src/Symfony/Component/Routing/Generator/UrlGenerator.php
> +                if ('!' === substr($varName, 0, 1)) {
or better: `'!' === $varName[0]`

2018-12-14 08:46 UTC, nicolas-grekas commented on src/Symfony/Component/Routing/Generator/UrlGenerator.php
> +                    $coalescing = false;
or in one line: `if ($important = '!' === $varName[0]) {`

2018-12-14 10:08 UTC, luchaninov commented on src/Symfony/Component/Routing/Generator/UrlGenerator.php
> +                if ('!' === substr($varName, 0, 1)) {
@stloyd My IDE also suggested changing to strpos but I thought that substr will be faster. 

@nicolas-grekas `$varName[0]` would be awesome but I'm afraid of `PHP Notice:  Uninitialized string offset: 0` if the string happens to be empty.

So I've checked
https://gist.github.com/luchaninov/c8dd1f95aaeb8426f1af3a81c2dda8f6

`$varName[0]` solution wins. Is it safe to use?

2018-12-14 10:12 UTC, nicolas-grekas commented on src/Symfony/Component/Routing/Generator/UrlGenerator.php
> +                if ('!' === substr($varName, 0, 1)) {
yes, per the regexp below: https://github.com/symfony/symfony/pull/29599/files#diff-aeec0cbcb3837463c63c212f50cd860fR114
the varname cannot be empty

2018-12-15 09:50 UTC, luchaninov commented on src/Symfony/Component/Routing/Generator/UrlGenerator.php
> +                    $coalescing = true;
Thanks, that's better. Renamed to `$important`

2018-12-15 09:51 UTC, luchaninov commented on src/Symfony/Component/Routing/Generator/UrlGenerator.php
> +                if (
Made condition oneliner

2018-12-15 09:52 UTC, luchaninov commented
> Would you mind creating a doc issue/PR?

https://github.com/symfony/symfony-docs/pull/10785

2018-12-15 09:52 UTC, nicolas-grekas commented on src/Symfony/Component/Routing/RouteCompiler.php
> +            if ('!' === substr($varName, 0, 1)) {
$varName[0] here (and one more below)

2018-12-15 09:53 UTC, nicolas-grekas commented on src/Symfony/Component/Routing/Tests/Generator/UrlGeneratorTest.php
> +    public function testCoalescingVariable()
testImportantVariable? (same below)

2018-12-15 09:55 UTC, luchaninov commented on src/Symfony/Component/Routing/RouteCompiler.php
> +            if ('!' === substr($varName, 0, 1)) {
thanks, fixed

2018-12-15 09:55 UTC, luchaninov commented on src/Symfony/Component/Routing/Tests/Generator/UrlGeneratorTest.php
> +    public function testCoalescingVariable()
thanks, fixed

2018-12-15 09:57 UTC, luchaninov commented on src/Symfony/Component/Routing/Generator/UrlGenerator.php
> +                    $coalescing = false;
@nicolas-grekas nice one. To make it more understandable added `( )`: 
`$important = ('!' === $varName[0])`

2018-12-15 10:06 UTC, luchaninov commented on src/Symfony/Component/Routing/Generator/UrlGenerator.php
> +                if ('!' === substr($varName, 0, 1)) {
changed to ``$varName[0]``

2018-12-15 14:04 UTC, luchaninov commented on src/Symfony/Component/Routing/Tests/Matcher/UrlMatcherTest.php
> +    public function testMatchCoalescingVariable()
sorry :( 
fixed

2018-12-19 20:51 UTC, OskarStark approved these changes
Nice improvement 👍🏻

2018-12-20 08:15 UTC, stloyd approved these changes

2018-12-24 09:29 UTC, merged

2018-12-24 15:47 UTC, Tobion commented
I think the solution with `!` is good for forcing the generation of urls with default params. This is already something I tried to tacle before in #5180.
But I suggest to also change the matching for `!` prefixed placeholders to not make them optional.
So `/news.{!_format}` does not match `/news`. Otherwise we promote duplicate URIs again. If you need `/news` to also match, you just create a redirect route as explained in https://github.com/symfony/symfony/pull/28633#issuecomment-431766878

2019-01-03 15:10 UTC, nicolas-grekas commented
See #29763, help wanted.