Deprecate using arrays and resources in Filesystem's dumpFile() and appendToFile()
symfony/symfony pull request #29661
Opened 2018-12-21 10:16 UTC by thewilkybarkid

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | yes
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        |

Running PHPStan on my project picked up that passing a resource to `Filesystem::dumpFile()` didn't match the documented type.

I found this has been discussed in #20980 and #28019, without a clear result. But, my reading is that only strings should be supported. While I think that not supporting streams makes this a lot less useful (and I'm going to switch away from it), this does need to be resolved. So, I've deprecated using arrays and resources.

2018-12-23 14:14 UTC, fabpot approved these changes

2018-12-24 08:58 UTC, nicolas-grekas approved these changes

2018-12-26 00:05 UTC, chalasr requested changes
UPGADE-4.3.md needs to be updated

2018-12-26 15:43 UTC, javiereguiluz approved these changes

2018-12-27 21:38 UTC, thewilkybarkid commented
Would need a separate PR, but would you accept a new method that takes a resource?

2018-12-28 09:58 UTC, thewilkybarkid commented
That would be my preference, but this PR was following #20980 and #28019.

2019-02-21 09:44 UTC, fabpot commented
I would be in favor of supporting resources and strings in the existing method.

2019-02-22 08:49 UTC, thewilkybarkid commented
@fabpot Updated to match.

2019-03-03 21:35 UTC, fabpot approved these changes

2019-03-03 21:36 UTC, fabpot commented
Thank you @thewilkybarkid.

2019-03-03 21:37 UTC, merged

2022-03-01 16:58 UTC, tvdijen commented
The current type-hints that were added in 5.x for these methods prevent us from passing resources because the file is type-hinted as `string`.
I'm trying to use `appendToFile` with file `php://stderr` which breaks on the `mkdir()` in the method and passing `fopen('php://stderr', 'w')` as a file break because of the typehint..  Is this a bug, or shouldn't I be doing this at all @fabpot ?

Update: this only breaks on Windows for some reason...  [this](https://github.com/simplesamlphp/simplesamlphp/blob/filesystem/lib/SimpleSAML/Logger/FileLoggingHandler.php#L136-L149) is my workaround to deal with `php://` files on windows right now.