Bump php version of PHPUnit-bridge
symfony/symfony pull request #29718
Opened 2018-12-28 18:09 UTC by gmponos

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no (?)
| Deprecations? | no
| Tests pass?   | yes
| License       | MIT

Related to https://github.com/symfony/symfony/pull/29623#issuecomment-450400625

I checked the BC page I think I couldn't find any related to BC changes... anyway...

As far as I understood from the comment above I must target `master` branch.

2018-12-28 18:10 UTC, nicolas-grekas reviewed
while bumping to phpunit5 & php5.5, there are many opportunities to improve the code (eg $this in closure, and polyfills that we could remove, see "Legacy" namespace.)
Up to do it?

2018-12-28 18:10 UTC, nicolas-grekas commented on src/Symfony/Bridge/PhpUnit/bin/simple-phpunit
> +    throw new \Exception('Symfony phpunit-bridge does not support your current PHP version.');
no need for that part - composer does the job

2018-12-28 18:27 UTC, nicolas-grekas approved these changes

2018-12-29 09:23 UTC, fabpot requested changes

2018-12-29 09:42 UTC, gmponos commented on src/Symfony/Bridge/PhpUnit/CHANGELOG.md
> + * bumped PHP version from 5.5.3 to 5.5.9
🤦‍♂️... Yes it is a type.. fixed.

2018-12-29 15:59 UTC, greg0ire commented
The `Legacy` namespace should stay around for a while, but some simplifications seem indeed possible: https://3v4l.org/MmG7J I'm working on a PR right now.

2019-01-01 18:08 UTC, fabpot approved these changes

2019-01-01 18:15 UTC, fabpot commented
Thank you @gmponos.

2019-01-01 18:16 UTC, merged