Only traverse arrays that are cascaded into
symfony/symfony pull request #29800
Opened 2019-01-06 14:34 UTC by corphi

| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #27090
| License       | MIT
| Doc PR        | -

Previously, array properties were traversed even if they were not annotated `Valid`.

2019-01-06 15:30 UTC, HeahDude requested changes

2019-01-06 15:30 UTC, HeahDude commented on src/Symfony/Component/Validator/Constraints/Collection.php
> +                $this->fields[$fieldName] = new Required($field);
This looks like a legit bug fix nevertheless.

2019-01-06 15:30 UTC, HeahDude commented on src/Symfony/Component/Validator/Validator/RecursiveContextualValidator.php
> +        if (!($cascadingStrategy & CascadingStrategy::CASCADE)) {
This should be reverted.

2019-01-06 15:39 UTC, HeahDude commented on src/Symfony/Component/Validator/Constraints/Collection.php
> +                $this->fields[$fieldName] = new Required($field);
This may be a big BC as well, I'm not sure we should merge such change.

2019-01-06 21:09 UTC, HeahDude commented
I was considering this documentation: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Validator/Validator/RecursiveContextualValidator.php#L357 as the expected behavior. I'm not sure how much we want to follow Java specs here.

2019-01-07 07:37 UTC, HeahDude commented
Ok I got your point in #27090. But still, 2.5 is pretty old now, and breaking BC is not the same in both directions.

I mean with the current code, expectation *may* fail but invalid data *should* not be able to be persisted. With the proposed changes, expectation is *right* but some invalid data *can* be persisted without anyone or anything noticing.

But if the PR were to be merged, I think we should at least update the phpdoc I link above and some inline comment (i.e https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Validator/Validator/RecursiveContextualValidator.php#L372) consistently, even re-introduce this behavior in master with a proper BC layer.

2019-01-07 10:09 UTC, spackmat commented
> I mean with the current code, expectation _may_ fail but invalid data _should_ not be able to be persisted, displaying an invalid message instead.
> With the proposed changes, expectation is _right_ but some invalid data _can_ be persisted without anyone or anything noticing.

@HeahDude In my case, no invalid data is newly persisted (it is only invalid after changes, but legacy data is still in the database that must be updated on next edit). Now I cannot insert a relation to such legacy data elsewhere since the validation is (incorrectly) traversed and I cannot stop that behavior. Only `@Valid` constraints should trigger such traversal.

And to make things worse: In my case, there is no error shown at all unless I configure the `error_mapping`, as shown here https://github.com/symfony/symfony/issues/27090#issuecomment-404419560. (I have a collection field with one or more relations to another entity and for now I cannot use the Count-constraint to ensure at least one relation is persisted, which ist really bad.)

2019-01-07 19:44 UTC, corphi commented
Unfortunately, the inline comments are often outdated. The [comment in line 372](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Validator/Validator/RecursiveContextualValidator.php#L372) is correct, but misleading. It means: Traversal strategies are ignored on arrays. `validateEachObjectIn()` actually executes cascading into the array. So this condition is already met. (And both aspects are covered by test cases. :tada:) But the [line 357 one](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Validator/Validator/RecursiveContextualValidator.php#L357) is plain wrong. I’ll try to improve the comments. And probably the documentation, too.

The way I read it, the Java specification is the single source of truth:
> The Validator component provides tools to validate values following the JSR-303 Bean Validation specification.
> [Symfony Validator documentation](https://symfony.com/doc/current/components/validator.html), first sentence

I linked the current version 2.0 (JSR-380) because of its nicer formatting, but the parts relevant to this issue haven’t changed since 1.0 (JSR-303). We are just lagging behind [on the feature side](https://github.com/symfony/symfony/issues/28608).

About the BC layer: @HeahDude, do you suggest triggering a deprecation notice if the wrong annotation incorrectly causes traversal, and fixing the bug in 5.0? An opt-in for the correct behaviour seems a little over the top. A deprecation notice won’t hurt, though. I’d rather fix it sooner than later.

2019-01-08 22:57 UTC, Kronhyx approved these changes

2019-01-12 18:46 UTC, corphi commented
Adding a deprecation would mean that this fix had to target 4.3 and could only be corrected in 5.0, according to semantic versioning. A quick scan of existing deprecation messages showed that they are concerned with BC breaks according to the [Symfony BC promise](https://symfony.com/doc/current/contributing/code/bc.html). It only covers changes to code structure, not changed behaviour. A message like “you might have been doing this wrong the entire time” didn’t fit the scheme.

Also, this is why I labeled this PR as without a BC; the rules are linked in the PR template.

2019-01-24 20:13 UTC, nicolas-grekas commented
Could you please rebase? That would remove all the short-array related diffs and ease reviews. Thanks!

2019-01-25 10:46 UTC, nicolas-grekas reviewed
minor details, no idea about the main topic sorry :)
more reviewers needed.

2019-01-25 10:46 UTC, nicolas-grekas commented on src/Symfony/Component/Validator/.gitignore
> +phpunit
should be removed

2019-01-25 10:46 UTC, nicolas-grekas commented on src/Symfony/Component/Validator/Tests/Validator/AbstractValidatorTest.php
> +    // https://github.com/symfony/symfony/issues/27090
should be removed

2019-01-25 10:46 UTC, nicolas-grekas commented on src/Symfony/Component/Validator/composer.json
> +        "symfony/phpunit-bridge" : "^3.4 || ^4.0"
should be removed

2019-04-07 07:19 UTC, HeahDude approved these changes

2019-04-07 07:24 UTC, xabbuh approved these changes

2019-04-07 08:20 UTC, fabpot commented
Thank you @corphi.

2019-04-07 08:20 UTC, merged

2019-04-26 12:52 UTC, salv1 commented
In certain situations, changes in RecursiveContextualValidator.php (line 657) can break form validation.
In such case you need to add [Valid constraint](https://symfony.com/blog/new-in-symfony-3-4-groups-support-for-the-valid-constraint).