[FrameworkBundle] xliff-version option to translation update command
symfony/symfony pull request #29850
Opened 2019-01-11 14:29 UTC by andrewwro

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes 
| BC breaks?    | no     
| Deprecations? | no 
| Tests pass?   | no    
| License       | MIT

New 'version' option added to xliff translation update command. Currently xliff version is hardcoded to 1.2.

2019-01-11 14:35 UTC, stof requested changes

2019-01-11 14:35 UTC, stof commented on src/Symfony/Bundle/FrameworkBundle/Command/TranslationUpdateCommand.php
> +            $this->writer->write($operation->getResult(), $input->getOption('output-format'), array('path' => $bundleTransPath, 'default_locale' => $this->defaultLocale, 'xliff-version' => $input->ge
The key used by the dumper is `xliff_version`

2019-01-14 08:49 UTC, javiereguiluz approved these changes
I wondered if we should validate the given version somehow ... but in addition to complicating things, not doing that gives more flexibility for edge-cases where developers may need to use a non-standard looking version. So I think the proposed changes are enough. Thanks!

2019-01-14 09:30 UTC, fabpot approved these changes

2019-01-24 20:08 UTC, nicolas-grekas commented
Thank you @andrewwro.

2019-01-24 20:09 UTC, merged