[Twig][Bootstrap 4 Theme]: Displaying errors like in official compone…
symfony/symfony pull request #29987
Opened 2019-01-25 18:41 UTC by FlashBlack

| Q             | A
| ------------- | ---
| Branch?       | 4.2
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #29986
| License       | MIT
| Doc PR        | —

2019-02-11 09:35 UTC, vudaltsov requested changes

2019-02-11 09:35 UTC, vudaltsov commented on src/Symfony/Bridge/Twig/Resources/views/Form/bootstrap_4_layout.html.twig
> +        <div class="{% if form is not rootform %}invalid-feedback{% else %}alert alert-danger{% endif %} d-block">
```suggestion
        <div class="{% if form is not rootform %}invalid-feedback{% else %}alert alert-danger{% endif %}">
```
`d-block` is not necessary with `<div>`

2019-03-06 11:15 UTC, FlashBlack commented on src/Symfony/Bridge/Twig/Resources/views/Form/bootstrap_4_layout.html.twig
> +        <div class="{% if form is not rootform %}invalid-feedback{% else %}alert alert-danger{% endif %} d-block">
up, this has been fixed.

2019-03-06 12:18 UTC, vudaltsov approved these changes

2019-04-06 09:49 UTC, Nyholm commented
Thank you for this PR. I like that you addressed the issue but we also need to consider accessibility. 

I suggest closing this PR and solve it like described here: https://github.com/symfony/symfony/issues/28086#issuecomment-480490730

I would be more than happy to review a new PR form you.

2019-04-06 09:50 UTC, closed without merging