[Form] be able to specify the input format for times
symfony/symfony pull request #30358
Opened 2019-02-23 10:38 UTC by xabbuh

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        | 

This expands the work started in #29887 to also allow to configure the input format for string inputs in the `TimeType`.

2019-02-23 13:06 UTC, OskarStark requested changes

2019-02-23 13:06 UTC, OskarStark commented on src/Symfony/Component/Form/CHANGELOG.md
> + * added the `input_format` option to `DateType`, `DateTimeType`, and `TimeType` to specify the inpt format when setting
```suggestion
 * added the `input_format` option to `DateType`, `DateTimeType`, and `TimeType` to specify the input format when setting
```

2019-02-23 14:30 UTC, nicolas-grekas approved these changes

2019-02-24 10:22 UTC, ogizanagi approved these changes

2019-03-03 16:53 UTC, sstok approved these changes

2019-03-03 18:04 UTC, fabpot approved these changes

2019-03-03 18:05 UTC, fabpot commented
Thank you @xabbuh.

2019-03-03 18:05 UTC, merged