Serializer: Use the context in supports calls
symfony/symfony pull request #30397
Opened 2019-02-27 16:50 UTC by soyuka

| Q             | A
| ------------- | ---
| Branch?       | 4.1 (4.0 has the correct call)
| Bug fix?      | yes
| New feature?  | no 
| BC breaks?    | no     
| Deprecations? | no 
| Tests pass?   | yes    
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

In both of these calls, `$context` was missing. It was available in 3.4 when @dunglas introduced the `ContextAware(De)NormalizerInterface`. My guess is that we missed this when reviewing the Cache thingy that was added recently (4.1).

2019-02-27 18:09 UTC, dunglas requested changes
The change must also be reintroduced here and here:

* https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Serializer/Serializer.php#L317
* https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Serializer/Serializer.php#L325

2019-02-27 18:10 UTC, dunglas commented
Good catch! This fix is needed for https://github.com/api-platform/core/pull/2566.

2019-02-28 07:42 UTC, soyuka commented
> The change must also be reintroduced here and here:
> 
>     * https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Serializer/Serializer.php#L317
> 
>     * https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Serializer/Serializer.php#L325

Not sure, `context` is already present there?

2019-03-01 08:24 UTC, dunglas approved these changes

2019-03-01 08:25 UTC, dunglas commented
Oops, sorry about that!

2019-03-01 08:27 UTC, dunglas commented
Thank you Antoine.

2019-03-01 08:27 UTC, merged

2019-03-03 18:19 UTC, fabpot commented
@dunglas This PR should never have been merged in 4.1 as the branch is not maintained anymore, and 4.1 won't get merged to 4.2.

2019-03-03 20:05 UTC, dunglas commented
@fabpot sorry about that. I’ll merge cherry-pick this commit in 4.2. Should I revert this commit in 4.1?

2019-03-03 21:21 UTC, fabpot commented
Yes, I think reverting is the best thing to do.

2019-03-04 10:49 UTC, dunglas commented
Done.