[Messenger] Adding MessageCountAwareReceiverInterface to get transport message count
symfony/symfony pull request #30757
Opened 2019-03-28 18:00 UTC by weaverryan

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | none
| License       | MIT
| Doc PR        | symfony/symfony-docs#11236

This adds a new optional interface that receivers should implement to give an approximate number of the messages "waiting" to be handled. Why? Because, with this, you could design a system that dynamically adds/removes worker processes if a specific transport is getting slammed and needs help. Creating that system could be something we discuss for core later, but this at least makes it possible - and means it could be implemented by the user or in a bundle... which I might do if we don't get it in core ;).

2019-03-29 05:27 UTC, OskarStark commented on src/Symfony/Component/Messenger/Transport/Receiver/MessageCountAwareReceiverInterface.php
> +     * @return int
This could be removed

2019-03-31 09:34 UTC, nicolas-grekas commented on src/Symfony/Component/Messenger/CHANGELOG.md
> + * Added optional `MessageCountAwareReceiverInterface` that receivers can implement
maybe name it `MessageCountAwareInterface`? the `Receiver` part is not really needed, is it?

2019-03-31 09:41 UTC, sroze commented
I don't think we should add it to the core without knowing the actually use-case tbh.

2019-03-31 16:27 UTC, weaverryan commented
> I don't think we should add it to the core without knowing the actually use-case tbh.

Very fair. So, let me try to be more specific... even though I admit, I'm "planning ahead" a bit here. One easy thing to look at is Larave's Horizon, which takes advantage of the "size" of a queue for (A) displaying a health dashboard and (B) for automatically spinning up/down more/less workers for each transport, based on the size. Without this feature (which is pretty simple), creating something like that as a 3rd party bundle, for example, will not be possible.

Rebased and comments addressed!

2019-03-31 17:36 UTC, weaverryan commented
@vincenttouzet could you check the Doctrine part of this PR out? There is an integration test, but would love your +1 technically for it.

2019-03-31 17:58 UTC, vincenttouzet reviewed
Except the comment on the fetch / fetchColumn this looks good to me and very promising !

2019-03-31 17:58 UTC, vincenttouzet commented on src/Symfony/Component/Messenger/Transport/Doctrine/Connection.php
> +        $data = $this->executeQuery($queryBuilder->getSQL(), $queryBuilder->getParameters())->fetch();
Maybe you can directly return the result : 

```suggestion
        return $this->executeQuery($queryBuilder->getSQL(), $queryBuilder->getParameters())->fetchColumn();
```

2019-04-01 15:16 UTC, onEXHovia commented on src/Symfony/Component/Messenger/Transport/AmqpExt/AmqpTransport.php
> +        ($this->receiver ?? $this->getReceiver())->getMessageCount();
Missing `return`?

2019-04-01 15:31 UTC, fabpot requested changes

2019-04-01 15:31 UTC, fabpot commented on src/Symfony/Component/Messenger/Transport/Doctrine/Connection.php
> +        return $data['message_count'];
obsolete code?

2019-04-03 11:57 UTC, nicolas-grekas approved these changes
(it'd be nice updating the 1st commit message with the new name of the interface)

2019-04-03 14:44 UTC, fabpot approved these changes

2019-04-03 14:45 UTC, fabpot commented
Thank you @weaverryan.

2019-04-03 14:46 UTC, merged

2019-04-04 08:07 UTC, ro0NL commented on src/Symfony/Component/Messenger/Tests/Transport/AmqpExt/AmqpExtIntegrationTest.php
> +        $sender->send($second = new Envelope(new DummyMessage('Third')));
:thinking:

2019-04-04 11:33 UTC, weaverryan commented on src/Symfony/Component/Messenger/Tests/Transport/AmqpExt/AmqpExtIntegrationTest.php
> +        $sender->send($second = new Envelope(new DummyMessage('Third')));
#30864