[Routing][ObjectRouteLoader] Allow invokable route loader services
symfony/symfony pull request #30933
Opened 2019-04-06 19:21 UTC by fancyweb

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | TODO

Fall back by default on the `__invoke` method when it is not configured.

Using a regex is easier to check that the format is valid, at least for the time we have to supports the single column notation.

TODO :
- [ ] Changelog entry
- [ ] Doc PR

2019-04-06 19:32 UTC, fabpot requested changes

2019-04-06 19:32 UTC, fabpot commented on src/Symfony/Component/Routing/Loader/ObjectRouteLoader.php
> +        $method = 2 === \count($parts) ? $parts[1] : '__invoke';
`$method = $parts[1] ?? '__invoke';`?

2019-04-07 12:47 UTC, nicolas-grekas approved these changes

2019-04-07 12:53 UTC, nicolas-grekas commented
Thank you @fancyweb.

2019-04-07 12:53 UTC, merged