[DoctrineBridge] [DX] Update exception text in ManagerRegistry to avoid confusion.
symfony/symfony pull request #31047
Opened 2019-04-10 05:02 UTC by Simperfit

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yesish 
| BC breaks?    | no     
| Deprecations? | no 
| Tests pass?   | yes    
| Fixed tickets | #29659   
| License       | MIT
| Doc PR        | 

Since the last PR was closed and the ticket is still open, taking it since it was already done by Nicolas in the comments.

2019-04-10 05:45 UTC, Simperfit commented
Failure is not related

2019-04-10 08:49 UTC, jewome62 requested changes

2019-04-10 08:49 UTC, jewome62 commented on src/Symfony/Bridge/Doctrine/ManagerRegistry.php
> +            throw new \LogicException(sprintf('Resetting a non-lazy manager service is not supported. '.(interface_exists(LazyLoadingInterface::class) ? sprintf('Declare the "%s" service as lazy.', $
you can remove the first sprintf, because not argument added

2019-04-10 12:19 UTC, Simperfit commented
Status: Needs Review

2019-04-15 09:42 UTC, nicolas-grekas commented
Thank you @Simperfit.

2019-04-15 09:42 UTC, merged

2020-01-17 09:33 UTC, guilliamxavier commented
@nicolas-grekas: Sorry but that just made the error message even *more* misleading in my case:

> Resetting a non-lazy manager service is not supported. Declare the "doctrine.orm.default_entity_manager" service as lazy.

but it is *already* lazy, says my `bin/console debug:container doctrine.orm.default_entity_manager`. The actual thing to do is `composer require symfony/proxy-manager-bridge` (then there is no error anymore), but that information is no longer in the error message.

The problem is that `ProxyManager\Proxy\LazyLoadingInterface` is defined not by `symfony/proxy-manager-bridge` but by `ocramius/proxy-manager`, and I have `ocramius/proxy-manager` installed _(because required by `doctrine/migrations` required by `doctrine/doctrine-migrations-bundle` required by `symfony/orm-pack` required in my `composer.json`)_ without having `symfony/proxy-manager-bridge` installed, so the interface exists but it is not sufficient.

Couldn't the code check that `symfony/proxy-manager-bridge` is actually installed (given it also requires `ocramius/proxy-manager`)?

2020-01-17 09:35 UTC, nicolas-grekas commented
Nice suggestion, PR welcome :)

2020-01-17 10:15 UTC, guilliamxavier commented
@nicolas-grekas: I'm not sure how to do. Should I replace `interface_exists(LazyLoadingInterface::class)` with `class_exists(RuntimeInstantiator::class)` (adding a `use Symfony\Bridge\ProxyManager\LazyProxy\Instantiator\RuntimeInstantiator;`)? Or maybe keep the first and append the second with `&&`? Or another approach entirely?
Also, PR on branch `4.3`?

2020-01-19 18:47 UTC, nicolas-grekas commented
Please open an issue or a PR so that we can keep track of the discussion.