Make error message more clear
symfony/symfony pull request #31259
Opened 2019-04-26 06:12 UTC by fabpot

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no 
| BC breaks?    | no     
| Deprecations? | no 
| Tests pass?   | yes    
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | n/a

When you get the following error message `No transport supports the given DSN "...".`, you might think that this relates to a mailer transport or a messenger transport. Let's make this real clear.

2019-04-26 06:16 UTC, nicolas-grekas approved these changes

2019-04-26 06:23 UTC, Simperfit approved these changes

2019-04-26 07:17 UTC, jakzal approved these changes

2019-04-26 07:21 UTC, jakzal requested changes
Test failures seem to be legit. Some tests verify exception messages, like this one: https://github.com/symfony/symfony/blob/ee9fe4f9301a31f10950a9ba9b21db0c81ca1135/src/Symfony/Component/Messenger/Tests/Transport/Doctrine/DoctrineTransportFactoryTest.php#L54

2019-04-27 16:38 UTC, fabpot commented
Tests fixed

2019-04-27 16:42 UTC, merged