add custom_service option in remember_me firewall
symfony/symfony pull request #31309
Opened 2019-04-28 21:52 UTC by Pchol

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no  
| Deprecations? | no
| Tests pass?   | yes 
| Fixed tickets | 
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

allow override remember me service

2019-05-07 09:16 UTC, chindit commented
I think that's a nice idea, but why naming it `custom_service` and not just `service`  in config ?

2019-05-08 18:22 UTC, Pchol commented
> I think that's a nice idea, but why naming it `custom_service` and not just `service` in config ?

thank you, i renamed to `service`, it's more accurate

2019-05-09 13:16 UTC, leofeyer commented
We would need this for Contao, too (see #31078), so +1. 😉

2019-05-09 14:43 UTC, leofeyer commented
> > I think that's a nice idea, but why naming it `custom_service` and not just `service` in config ?
> 
> thank you, i renamed to `service`, it's more accurate

I believe that the common name is `id`.

2020-02-04 14:02 UTC, fabpot requested changes

2020-02-04 14:02 UTC, fabpot commented on src/Symfony/Bundle/SecurityBundle/DependencyInjection/Security/Factory/RememberMeFactory.php
> +            ->scalarNode('service')->end()
We would need an update to the XSD file to support the new option.

2020-02-04 14:06 UTC, nicolas-grekas approved these changes
(there is no xsd in the bundle)

2020-02-04 14:06 UTC, nicolas-grekas commented
Thank you @Pchol.

2020-02-04 14:07 UTC, merged