Feature/optiisation getting the command
symfony/symfony pull request #31420
Opened 2019-05-08 10:39 UTC by Simperfit

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no 
| BC breaks?    | no     
| Deprecations? | no 
| Tests pass?   | yes    
| Fixed tickets | none  
| License       | MIT
| Doc PR        |

Following discussion with @chalasr in here https://github.com/symfony/symfony/pull/31261#discussion_r281033178, first commit will be deleted  when the other PR is merged.

2019-05-09 13:57 UTC, nicolas-grekas commented
Time for rebase :)

2019-05-12 05:34 UTC, Simperfit commented
@nicolas-grekas rebased

2019-05-12 06:01 UTC, chalasr requested changes

2019-05-12 06:01 UTC, chalasr commented on src/Symfony/Component/Console/Application.php
> +        return $this->get($name);
`return $this->get(reset($commands));`

2019-05-12 06:04 UTC, Simperfit commented on src/Symfony/Component/Console/Application.php
> +        return $this->get($name);
done

2019-05-12 06:36 UTC, Simperfit commented
Status: Needs Review

2019-05-12 15:44 UTC, chalasr requested changes
Blocking merge for now, I realize that calling `has()` involves to instantiate some lazy commands which might be a problem even for the related bugfix, I'm going to double-check the behavior tonight.

2019-05-14 12:51 UTC, chalasr approved these changes

2019-05-14 12:54 UTC, chalasr commented
Thank you @Simperfit.

2019-05-14 13:00 UTC, merged