POC adding of href link to the dump call location
symfony/symfony pull request #31446
Opened 2019-05-09 15:25 UTC by ktherage

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | not tested yet
| Fixed tickets | #30830
| License       | MIT
| Doc PR        |  

see #30830

2019-05-21 16:41 UTC, nicolas-grekas commented
The implementation relies on a statefull service. This should be avoided.
If we need dumping some context, it should be added to the `Data` object to me.
Then, dumpers could read it and do things appropriately.
See also `SourceContextProvider` which has move intensive logic for extracting the stack trace.

2019-05-24 14:10 UTC, ktherage commented
@nicolas-grekas Thank you for the feed back. I've changed the implementation.

Do you have an idea on how can i insulate this new feature and set her only for CliDumper?

Because currently, without forcing file and line to `null` in `getDump` method of `VarDumperTestTrait` it has impact on all other tests and so maybe on functionnalities.

2019-06-21 21:18 UTC, Simperfit commented
@ktherage can we move forward on this ;) ?

2019-06-25 15:46 UTC, ktherage commented
@Simperfit I'm stuck on unit tests. I this they are to much nested each other. Testing cli dumper makes HtmlDumper, ServerDumper and all the caster crashed.

2019-07-01 13:14 UTC, ktherage commented
@Simperfit @nicolas-grekas, I did some work on that, tests are finally green.
Could you, please, take a sometime to check those changes?

2019-07-11 07:52 UTC, nicolas-grekas requested changes
I'm sorry but I'm not comfortable at all with the way this is implemented. This feels like breaking all semantics to fit the target.
- Data::dump() is about the represented structure. It cannot snif the context.
- CliDumper is about dumping the same structure, not the context.

 I think ServerDumper does it properly:
- the context is collected completly separately, in a flexible way
- the context is dumped separately

Here is a proposal: add a ContextualizedDumper that collects+dumps contexts and dumps using a decorated dumper - very alike ServerDumper. Writting to the output should be done using the decorated dumper too (unlike ServerDumpCommand, which write to Console i/o)

I hope this helps.

2019-07-11 07:52 UTC, nicolas-grekas commented on src/Symfony/Component/VarDumper/Dumper/CliDumper.php
> +        $this->handlesHrefGracefully = 'JetBrains-JediTerm' !== getenv('TERMINAL_EMULATOR');
why moving this up? if not needed, it should be reverted
I suppose you forgot to keep the check for KONSOLE_VERSION? (see removed line)

2019-07-11 07:52 UTC, nicolas-grekas commented on src/Symfony/Component/VarDumper/Dumper/CliDumper.php
> +            return \is_string($fmt) ? strtr($fmt, ['%f' => $file, '%l' => $lineNumber]) : ($fmt->format($file, $lineNumber) ?: 'file://'.$file);
please revert unrelated changes

2019-07-11 07:52 UTC, nicolas-grekas commented on src/Symfony/Component/VarDumper/Dumper/ContextProvider/CliContextProvider.php
> +        ['file' => $file, 'line' => $line] = (new SourceContextProvider())->getContext();
each context provider should do one thing, this cannot be the correct design

2019-07-11 07:52 UTC, nicolas-grekas commented on src/Symfony/Component/VarDumper/Tests/Dumper/CliDumperTest.php
> +            <<<EOTXT
please revert unrelated changes

2019-07-11 07:52 UTC, nicolas-grekas commented on src/Symfony/Component/VarDumper/Dumper/CliDumper.php
> +                $value .= " \033]8;;{$attr['href']}\033\\[^]\033]8;;\033\\";
this breaks the case where the value should be the text of the link

2019-07-11 07:52 UTC, nicolas-grekas commented on src/Symfony/Component/VarDumper/Dumper/CliDumper.php
> +        if (!$result && \PHP_VERSION_ID >= 70200) {
why? if confirmed, this should be submitted separately.

2019-07-12 11:31 UTC, ktherage commented
@nicolas-grekas I've applied your recommendations (hoping i've not misread them). 
Can you review them please ?

2019-07-16 16:39 UTC, nicolas-grekas commented
I push-forced on your fork to rebase+target 4.4, and do some changes.
Can you please try if that works for you?
Also, I think this doesn't work when dump is called from inside console commands.
Can you also check that?

2019-07-18 13:45 UTC, ktherage commented
> I push-forced on your fork to rebase+target 4.4, and do some changes.
> Can you please try if that works for you?
> Also, I think this doesn't work when dump is called from inside console commands.
> Can you also check that?

@nicolas-grekas i've adapter unit test according to your changes and i've added one test for console command. Can you check them and tell me if they are good for you?

2019-07-19 09:15 UTC, ktherage commented
As we talked together, i've adapted tests to a smaller sample an removed the fix i made on CliDumper for tests. 

I've also tried to call dump in a command of a website-skeleton and, as you pre-minded it, it does not worked but i don't know why (see the GIF bellow).

![Peek 18-07-2019 17-03](https://user-images.githubusercontent.com/35264408/61524265-6b6fc400-aa16-11e9-9f67-cdafec1e7752.gif)

2019-07-30 19:05 UTC, nicolas-grekas commented
@ktherage the reason is that we wire a service as a dumper. Looks for cli_dumper/html_dumper I think in the code base

2019-08-05 09:31 UTC, ktherage commented
> @ktherage the reason is that we wire a service as a dumper. Look for cli_dumper/html_dumper I think in the code base

Yes, [here it is](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Bundle/DebugBundle/Resources/config/services.xml#L37). 
Do you mean that i shall add a service definition like that one below :
```xml
        <service id="var_dumper.contextualized_cli_dumper" class="Symfony\Component\VarDumper\Dumper\ContextualizedDumper">
            <argument type="service" id="var_dumper.cli_dumper" />
            <argument type="collection">
                <argument type="service" key="source">
                    <service class="Symfony\Component\VarDumper\Dumper\ContextProvider\SourceContextProvider">
                        <argument>%kernel.charset%</argument>
                        <argument type="string">%kernel.project_dir%</argument>
                        <argument type="service" id="debug.file_link_formatter" on-invalid="null" />
                    </service>
                </argument>
            </argument>
        </service>
```
and use this new service in the debug bundle in place of the `var_dumper.cli_dumper` service ?

2019-09-10 15:28 UTC, ktherage commented
@nicolas-grekas I've worked on that and fixed the error for commands (see bellow).

I also tried to fixe the tests. But for me the CI behave strangely (depending on the php version).

![Peek 10-09-2019 15-05](https://user-images.githubusercontent.com/35264408/64619121-d2d83d80-d3e1-11e9-987b-c31589578f6e.gif)

2019-09-28 16:19 UTC, nicolas-grekas approved these changes
(I tested locally and fixed tests)

2019-09-28 16:21 UTC, nicolas-grekas commented
Thank you @ktherage.

2019-09-28 16:21 UTC, merged

2022-02-11 21:24 UTC, alimranahmed commented
> ![Peek 10-09-2019 15-05](https://user-images.githubusercontent.com/35264408/64619121-d2d83d80-d3e1-11e9-987b-c31589578f6e.gif)

It doesn't work this way in browser.