[FrameworkBundle] Allow dots in translation domains
symfony/symfony pull request #31451
Opened 2019-05-09 20:47 UTC by jschaedl

| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no 
| BC breaks?    | no     
| Deprecations? | no 
| Tests pass?   | yes    
| Fixed tickets | #31400  
| License       | MIT
| Doc PR        | tbd. 

With this fix it is now possible to have `.` in translation domains like `app.security.en.yaml`.

2019-05-11 09:40 UTC, nicolas-grekas commented
That's a new feature to me, it should target master.
Also please add some test cases.

2019-05-12 06:35 UTC, Simperfit commented on src/Symfony/Bundle/FrameworkBundle/Translation/Translator.php
> +                $format = $fileNameParts[\count($fileNameParts) - 1];
$fileNamePartsNb = \count($fileNameParts);

2019-05-12 06:35 UTC, Simperfit requested changes
I think this needs a test case too

2019-05-12 08:56 UTC, jschaedl commented
Changed target branch branch to master and added unit tests.

2019-05-16 08:33 UTC, kevin-verschaeve commented on src/Symfony/Bundle/FrameworkBundle/Translation/Translator.php
> +                $fileNamePartsNb = \count($fileNameParts);
maybe we can use `array_pop` here ?

```
$format = array_pop($fileNameParts);
$locale = array_pop($fileNameParts);
$domain = implode('.', $fileNameParts);
```
No need to `count` and `array_splice`

2019-05-16 13:12 UTC, stof commented
this should indeed target master, as it will require the same kind of changes in any other code dealing with the same convention for translation resources (this will affect https://github.com/willdurand/BazingaJsTranslationBundle for instance). So we should not merge this as a bugfix.

2019-06-09 11:24 UTC, jschaedl commented
Is there anything else I need to do in order to get this PR merged? :-)

2019-06-09 11:30 UTC, Simperfit approved these changes

2019-06-11 06:27 UTC, fabpot approved these changes

2019-06-11 06:42 UTC, fabpot commented
Thank you @jschaedl.

2019-06-11 06:43 UTC, merged