Callable validator
symfony/symfony pull request #31466
Opened 2019-05-10 11:33 UTC by janvernieuwe

| Q             | A
| ------------- | ---
| Branch?       | 4.3
| Bug fix?      | no
| New feature?  | yes/no 
| BC breaks?    | no     
| Deprecations? | no 
| Tests pass?   | yes
| Fixed tickets | #...   
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

This is an initial PR to check/discuss the implementation of a callable validator.
If there is interest in merging this, I will gladly update the docs and such.

The use case is mainly for validation of console questions, since the default validation has been removed in the latest version and i could not find an easy solution to replace it (if there already is some solution for this, i'm not aware of it) and the question helper uses callables.
This small class allows the standard symfony validators to be used in console questions, or any other location that requires a callable validator.

Example use case:
```php
$io = new SymfonyStyle($input, $output);
$required = new CallableValidator([new NotBlank()]);
$wsdl = $io->ask('Wsdl location (URL or path to file)', null, $required);
```

As said before, this is by no means the final version, but I would like to know if there is interest  in merging this (and receive some feedback about the implementation) before I put any more effort into this.

2019-05-12 06:17 UTC, Simperfit requested changes
You should remove the two unrelated commits

2019-05-13 07:32 UTC, janvernieuwe commented
Updated it, guess my fork got out of sync

2019-06-04 09:35 UTC, ro0NL commented
instead of a new CallableValidator, which isn't really a validator from the component pov (as it's not a true ValidatorInterface implementation) ... what about `Validation::createCallable($constraints): Closure`

2019-06-07 12:43 UTC, janvernieuwe commented
@ro0NL that can work too, it should be pretty easy as something like this in the Validation class:

```php
    public static function createCallable(Constraint...$constraints): callable
    {
        $validator = self::createValidator();

        return static function ($value) use ($constraints, $validator) {
            $violations = $validator->validate($value, $constraints);
            if (0 !== $violations->count()) {
                throw new LogicException((string)$violations);
            }

            return $value;
        };
    }
```

Don't know if it is desirable to create a new Validator instance for each new closure though, but it shouldn't be too bad.

2019-07-26 08:33 UTC, janvernieuwe commented
Failures on travis don't seem to be related to any of my code changes as far as i can see...

2019-11-29 08:53 UTC, janvernieuwe commented on src/Symfony/Component/Validator/Validation.php
> +                throw new LogicException((string) $violations);
Added a new exception for this, let me know if you want to change the naming or anything.

2020-01-21 14:15 UTC, janvernieuwe commented
@nicolas-grekas what's the status of this one?
I see lots of activity today :)

2020-01-21 19:17 UTC, ro0NL approved these changes
nice feature :+1:

2020-01-21 21:59 UTC, nicolas-grekas commented
can you please rebase+retarget for master?
if not no worries, we can do it on merger's side.

2020-01-22 08:20 UTC, janvernieuwe commented
I won't immediately have time for retargetting. So if it can be done on the merger's side, that'd be great!

2020-01-27 21:36 UTC, nicolas-grekas approved these changes
(I rebased the PR for master)

2020-02-04 13:38 UTC, fabpot approved these changes

2020-02-04 13:38 UTC, fabpot commented
Thank you @janvernieuwe.

2020-02-04 13:39 UTC, merged

2020-05-18 09:14 UTC, stof commented
I see an issue here: the callable creation always creates a new Validator object instead of allowing to use an existing one. This makes it incompatible with the DI integration, and so forbids using any constraint validator which has some dependency.
And it also makes it incompatible with any mapping configuration.

2020-05-18 09:57 UTC, nicolas-grekas commented
@stof good catch. What's your reco here? Revert? Improving? (in this case, could you work on a PR?)

2020-05-18 10:35 UTC, stof commented
Well, the variadic signature makes it hard to improve, as we cannot add an optional parameter to pass a validator instance.

2020-05-18 10:37 UTC, stof commented
My proposal: change the constraints from a variadic argument to an array argument (or maybe `ConstraintInterface[]|ConstraintInterface` for the case of only one constraint), and add the validator as an optional second argument.

2020-05-18 10:37 UTC, stof commented
Btw, this is the main reason why I don't like variadic arguments: they lock the signature entirely.