suppress warning
symfony/symfony pull request #31470
Opened 2019-05-10 15:33 UTC by Raggok

Add anotation to suppress warning: function name must be callable - a string

| Q             | A
| ------------- | ---
| Branch?       | 4.2
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no     
| Deprecations? |no
| Tests pass?   | yes    
| Fixed tickets | no
| License       | MIT
| Doc PR        | 

Add anotation to suppress warning: function name must be callable - a string

2019-05-10 17:04 UTC, fabpot commented
@Raggok Can you tell us a bit more about what you are trying to fix? `$session` is an object, not a callable.

2019-05-10 17:12 UTC, Raggok commented
if it isnt an  instance of SessionInterface it will be treat as a function, maybe the annotation must be inside the if block

$session = $this->session;
        if (!$session instanceof SessionInterface && null !== $session) {
             /** @var callable $session */
            $this->setSession($session = $session());
        }

2019-05-11 09:30 UTC, nicolas-grekas commented
inside the "if" would work yes

2019-05-11 10:49 UTC, staabm commented on src/Symfony/Component/HttpFoundation/Request.php
> +        /** @var callable $session */
```suggestion
        /** @var callable|null $session */
```

?

2019-05-12 06:10 UTC, Simperfit requested changes

2019-05-12 06:10 UTC, Simperfit commented on src/Symfony/Component/HttpFoundation/Request.php
> +        /** @var callable|null $session */
it should be inside the if ;)

2019-05-13 16:15 UTC, Raggok commented on src/Symfony/Component/HttpFoundation/Request.php
> +        /** @var callable|null $session */
you are right, thx!

2019-05-13 16:16 UTC, closed without merging