[Validator] Add a Length::$allowEmptyString option to reject empty strings
symfony/symfony pull request #31528
Opened 2019-05-17 15:10 UTC by ogizanagi

| Q             | A
| ------------- | ---
| Branch?       | master (4.4) 
| Bug fix?      | no
| New feature?  | yes 
| BC breaks?    | no     
| Deprecations? | yes 
| Tests pass?   | yes    
| Fixed tickets | N/A   
| License       | MIT
| Doc PR        | Todo (change the warning on top of https://symfony.com/doc/current/reference/constraints/Length.html)

which defaults to `true` in 4.4 but will trigger a deprecation if not set explicitly
in order to make the default `false` in 5.0.

While it could be solved now thanks to #29641 by using both `@Length(min=1)` & `@NotBlank(allowNull=true)` constraints, 
as expressed in https://github.com/symfony/symfony/issues/27876#issuecomment-403307783 and following comments, the `@Length(min=1)` behavior doesn't match our expectations when reading it: it feels logical to invalidate empty string, but it actually doesn't.
Hence the proposal of making the behavior of rejecting empty strings the default in 5.0.

In my opinion, the flag could even be removed in 5.0.

2019-05-17 15:36 UTC, ogizanagi commented
Status: Needs work

to only account when a `min` (or `value`, i.e min & max) value is set.

2019-05-22 14:22 UTC, ogizanagi reviewed
Status: Needs Review

2019-06-04 06:43 UTC, fabpot requested changes

2019-06-04 06:43 UTC, fabpot commented on UPGRADE-4.4.md
> + * The `Length` constraint expect the `allowEmptyString` option to be defined
expects

2019-06-04 06:43 UTC, fabpot commented on UPGRADE-4.4.md
> +   Set it to `true` to keep the current behavior and `false` to reject empty string.
empty strings

2019-06-04 17:47 UTC, ogizanagi commented
Rebased & comments fixed

Status: Needs Review

2019-07-03 13:14 UTC, fabpot approved these changes

2019-07-03 13:16 UTC, fabpot commented
Thank you @ogizanagi.

2019-07-03 13:16 UTC, merged