[Monolog] adding the new `$request` argument and remove deprecation
symfony/symfony pull request #31781
Opened 2019-06-01 09:19 UTC by Simperfit

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no 
| BC breaks?    | no     
| Deprecations? | no 
| Tests pass?   | yes    
| Fixed tickets | none   
| License       | MIT
| Doc PR        | none 

This removed the one and only deprecated codes from monolog from 4.x to 5.0.

2019-06-02 07:13 UTC, nicolas-grekas reviewed
Please check test failures.

2019-06-02 07:13 UTC, nicolas-grekas commented on src/Symfony/Bridge/Monolog/Logger.php
>       * @param Request|null $request
please remove all similar lines as they now duplicate the signature.

2019-06-02 08:00 UTC, Simperfit commented
done @nicolas-grekas

2019-06-02 08:03 UTC, nicolas-grekas commented on src/Symfony/Bridge/Monolog/CHANGELOG.md
> +5.0.0
missing blank line

2019-06-04 06:23 UTC, fabpot requested changes

2019-06-04 06:23 UTC, fabpot commented on src/Symfony/Bridge/Monolog/Tests/LoggerTest.php
> +        $this->assertEquals($loggerChild->getLogs(), null);
Should be `$this->assertEquals(null, $loggerChild->getLogs());`

2019-06-04 06:23 UTC, fabpot commented on src/Symfony/Bridge/Monolog/Tests/LoggerTest.php
> +        $this->assertEquals($loggerChild->countErrors(), 0);
Same here

2019-06-04 06:23 UTC, fabpot commented on src/Symfony/Bridge/Monolog/Tests/Processor/DebugProcessorTest.php
> +        $this->assertEquals($debugProcessorChild->getLogs(), null);
and here... and below :)

2019-06-04 07:11 UTC, Simperfit commented
@fabpot PR updated

2019-06-04 07:15 UTC, fabpot approved these changes

2019-06-04 07:18 UTC, fabpot commented
Thank you @Simperfit.

2019-06-04 07:19 UTC, merged