[Security][Http] Remove BC layers
symfony/symfony pull request #31782
Opened 2019-06-01 11:19 UTC by chalasr

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | yes
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | n/a

2019-06-01 13:02 UTC, chalasr commented
Green

2019-06-01 20:37 UTC, OskarStark commented on src/Symfony/Bundle/SecurityBundle/Debug/WrappedListener.php
>          if (\is_callable($this->listener)) {
Is this if check still needed?

2019-06-03 12:31 UTC, chalasr commented on src/Symfony/Bundle/SecurityBundle/Debug/WrappedListener.php
>          if (\is_callable($this->listener)) {
fixed thanks

2019-06-03 20:21 UTC, nicolas-grekas commented on src/Symfony/Component/Security/Http/Firewall.php
> +     * @internal
what about removing `@internal` on methods now? We don't have to keep it, do we?

2019-06-04 06:00 UTC, fabpot requested changes

2019-06-04 13:22 UTC, nicolas-grekas commented
Thank you @chalasr.

2019-06-04 13:26 UTC, merged