[DomCrawler] fixed return annotation
symfony/symfony pull request #31795
Opened 2019-06-02 10:56 UTC by kevinpapst

| Q             | A
| ------------- | ---
| Branch?       | 3.4  
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

I am almost ashamed to send this in as "luxury" PR, but it is blocking me.

The return annotation of the method does not reflect all possible cases, which causes some static code analysis tools (e.g. PHPStan level 4 or Scrutinizer) to error out on test like this:
```
self::assertNull($form->get('myCheckbox')->getValue());
```
complaining something like :
```
Call to method PHPUnit\Framework\Assert::assertNull() with array|string will always evaluate to false.
```
Null values can happen in `DomCrawler/Field/ChoiceFormField.php` [here](https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/DomCrawler/Field/ChoiceFormField.php#L124) and [here](https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/DomCrawler/Field/ChoiceFormField.php#L213)

My branch is current with 3.4, I don't understand why the translations commit shows up.

2019-06-03 20:24 UTC, nicolas-grekas approved these changes

2019-06-03 21:22 UTC, xabbuh approved these changes

2019-06-04 10:21 UTC, fabpot requested changes
Looks wrong to me. A form field value is always a string or an array.

2019-06-04 11:18 UTC, kevinpapst commented
I could very easily fix my test with 
```
self::assertFalse($form->get('user_create[create_more]')->hasValue());
```
as this function also [checks for null](https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/DomCrawler/Field/ChoiceFormField.php#L48) ... but that would obviously not fix the underlying issue. 

The [untick function](https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/DomCrawler/Field/ChoiceFormField.php#L110) sets the value to false, which is then [converted to null](https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/DomCrawler/Field/ChoiceFormField.php#L122). The code involved seems to be 9 years old, so I guess you can't remember why you did that back in 2010 @fabpot 😆 ?

As currently null is returned for unchecked checkboxes in the crawler it can't be fixed without a BC break. Any suggestion on how to proceed?

2019-06-06 14:33 UTC, kevinpapst commented
I fixed my problem already with the workaround mentioned above, but I am still willing to work on this, but not without feedback in which direction that should go. Drop me a comment if there is still interest.

2019-06-06 14:33 UTC, closed without merging