[SecurityBundle] Fix profiler dump for non-invokable security listeners
symfony/symfony pull request #31820
Opened 2019-06-03 14:56 UTC by chalasr

| Q             | A
| ------------- | ---
| Branch?       | 4.3
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | n/a

Listeners can be any callable since 4.3.

2019-06-03 19:50 UTC, nicolas-grekas commented on src/Symfony/Bundle/SecurityBundle/Debug/WrappedListener.php
> +            $this->stub = self::$hasVarDumper ? new ClassStub($this->pretty.'()', $this->listener) : $this->pretty.'()';
Would `ClassStub::wrapCallable()` we applicable here? Would it be better?

2019-07-08 10:36 UTC, nicolas-grekas approved these changes
(I push-forced some tweaks)

2019-07-08 10:38 UTC, stof requested changes

2019-07-08 10:38 UTC, stof commented on src/Symfony/Bundle/SecurityBundle/Debug/WrappedListener.php
> +        } elseif (\is_array($listener)) {
this looks like an undefined variable.

2019-07-08 10:39 UTC, fabpot approved these changes

2019-07-08 10:42 UTC, nicolas-grekas commented on src/Symfony/Bundle/SecurityBundle/Debug/WrappedListener.php
> +        } elseif (\is_array($listener)) {
oops, fixed

2019-07-08 10:54 UTC, stof approved these changes

2019-07-08 11:32 UTC, fabpot commented
Thank you @chalasr.

2019-07-08 11:32 UTC, merged