Add new Form WeekType
symfony/symfony pull request #32061
Opened 2019-06-15 19:36 UTC by dFayet

| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | yes 
| BC breaks?    | no     
| Deprecations? | no 
| Tests pass?   | yes    
| Fixed tickets | #32029 
| License       | MIT
| Doc PR        |  coming soon

2019-06-16 10:58 UTC, staabm commented on src/Symfony/Component/Form/CHANGELOG.md
> +4.3.0
```suggestion
4.4.0
```

2019-06-16 14:00 UTC, ro0NL commented
> Note: input elements with type="week" are not supported in Internet Explorer or Firefox.

Also im wondering if the underlying `DateType` can be used with a format `Y-\WW[-w]` (https://en.wikipedia.org/wiki/ISO_week_date)

2019-06-19 07:26 UTC, xabbuh commented
I wonder if we need to support different input formats for this form type. Right now it only supports a string that is in the same format as  the one supported by the HTML5 week input type. However, I could imagine that some developers would like to have a kind of structure like an array with a week and a year element.

2019-06-19 08:14 UTC, dFayet commented
@ro0NL `DateType` doesn't like date format without `y M d`, I doubt it can be used directly, I thing the `WeekType` will be independant, more like the `TimeType`.

@xabbuh I love the idea, it will behave like the `TimeType`, right?

2019-06-19 08:46 UTC, ro0NL commented
@dFayet maybe compatibility with `DateType` is too far fetched, yet i tend to believe `year-week-weekday` is just as valid as `year-month-day` for a date. Thus we should be able to use `DateTime` as a model... yet, im not sure what PHP is doing at this point: https://3v4l.org/7BMDB

2019-06-19 08:54 UTC, stof commented
If we add a form for `type=week`, I think it would make sense to also add a validator to ensure that a string contains an ISO week. this is especially important given that some browsers will fallback to a text type (which is fine by default; projects could add some JS-based picker as fallback).

If we want to improve the fallback a bit, we could add a `pattern` validation (`\d{4}-W\d{2}`) on the field so that the text fallback has client-side validation too. But I'm not sure we should do it in core (it might interact badly with a JS-based picker added by projects).

Anyway, I think adding a field type rendering a `<input type=week />` makes sense.

2019-06-19 10:32 UTC, dFayet commented
@stof should the validator be in the `Type` itself, or should it be a new  `Constraints`?

2019-07-21 18:00 UTC, xabbuh commented
@dFayet Is this still work in progress or are you waiting for a review? I don't want to pressure on you just ensure that you are not desperately waiting for a review. :)

2019-07-21 18:48 UTC, dFayet commented
Your're right to ask @xabbuh :D

The WIP tag might be too much as, beside the tests, ans the questions added in the edit of this PR  , I think this is good for some reviews.

The subject of the DataTransformers is my main hesitation, should I write the tests now, or wait some feedback?

2019-07-22 13:22 UTC, xabbuh commented
@dFayet Looking at how the updated transformers would look like, it seems to me that having new transformers would be better. We may then also reconsider the idea that the norm data should be `DateTime` objects. IMO that's not really needed and we could use an array with two elements as norm data instead as well.

2019-07-30 14:30 UTC, dFayet commented
@xabbuh Here you go :-)

Note: I think the failing test for depth=high, is normal, as the type does not exists in 5.0, right?

2019-07-31 12:02 UTC, xabbuh commented
@dFayet Adding `$this->requiresFeatureSet(404);` to the new tests should help here.

2019-07-31 12:02 UTC, xabbuh commented
and please take a look at the things fabbot.io complains about :)

2019-07-31 12:32 UTC, dFayet commented
@xabbuh Tests are green now, and fabbot now just complains about a license header in a .php template. (Not added as there is none in all the others templates)

2019-07-31 13:10 UTC, yceruto requested changes

2019-07-31 13:10 UTC, yceruto commented on src/Symfony/Component/Form/Extension/Core/Type/WeekType.php
> +
extra space here can be removed, same a few line bellow

2019-07-31 13:10 UTC, yceruto commented on src/Symfony/Component/Form/Extension/Core/Type/WeekType.php
> +        $view->vars = array_replace($view->vars, [
`$view->vars['widget'] = $options['widget']` ?

2019-08-08 19:55 UTC, dFayet commented
ping @taluu

2019-08-12 07:38 UTC, dFayet commented
Status: Need review

2019-08-12 07:39 UTC, dFayet commented
Status: Needs Review

2019-08-30 08:12 UTC, xabbuh requested changes

2019-08-30 08:12 UTC, xabbuh commented on src/Symfony/Component/Form/Extension/Core/Type/WeekType.php
> +        if ($options['html5'] && 'single_text' === $options['widget']) {
I think we should not allow to choose a different widget than `single_text` if `html5` is enabled for DX (we started to do the for the date related form types).

2019-08-30 08:12 UTC, xabbuh commented on src/Symfony/Component/Form/Extension/Core/Type/WeekType.php
> +        $resolver->setAllowedTypes('years', 'array');
Can we use `'int[]'` here?

2019-08-30 08:12 UTC, xabbuh commented on src/Symfony/Component/Form/Extension/Core/Type/WeekType.php
> +        $resolver->setAllowedTypes('weeks', 'array');
same here

2019-08-30 08:12 UTC, xabbuh commented on src/Symfony/Component/Form/Extension/Core/Type/WeekType.php
> +            if ('array' === $options['input']) {
I would reverse this and use the array representation for the norm data. So we would only need to add the `WeekDateToArrayTransformer` as a model transformer when `input` is `'string'`.

2019-08-30 08:12 UTC, xabbuh commented on src/Symfony/Component/Form/Extension/Core/Type/WeekType.php
> +            $builder->addViewTransformer(new WeekDateToArrayTransformer());
I would remove this here and treat the array representation as the norm data.

2019-08-30 08:12 UTC, xabbuh commented on src/Symfony/Component/Form/Extension/Core/Type/WeekType.php
> +            $builder->addModelTransformer(new WeekDateToArrayTransformer());
The model transformer needs to be added depending on the value of the `input` option (and we should be able to do that independent of the `widget` option.

2019-08-30 08:13 UTC, xabbuh commented
@dFayet Thank you for working on this. I have left you a bunch of comments. But they are actually only about a few details. The overall picture looks quite good to me. 👍

2019-08-30 08:44 UTC, dFayet commented on src/Symfony/Component/Form/Tests/Extension/Core/DataTransformer/WeekDateToArrayTransformerTest.php
> +            'week' => 'W01',
@xabbuh For a developer's view yes, but, I think, we will still need to support and convert the data to the Y-\WW format as 2019-W01 is a valid format, not 2019-1.
I'm not sure we want to convert the input to the allowed format, neither we want to allow "invalid" week date value, your thoughts?

2019-08-30 08:49 UTC, xabbuh commented on src/Symfony/Component/Form/Tests/Extension/Core/DataTransformer/WeekDateToArrayTransformerTest.php
> +            'week' => 'W01',
Yes, but the responsibility to check for the current format of the string representation lies in the data transformer. If only interested in the raw values for year and week, one shouldn't have to care (or even know) about string formats.

2019-08-30 08:51 UTC, xabbuh commented on src/Symfony/Component/Form/Tests/Extension/Core/DataTransformer/WeekDateToArrayTransformerTest.php
> +            'week' => 'W01',
To clarify, validation needs to happen only in two cases:

1. when `input` is `string` to ensure that the model data comes in the correct form
1. when `widget` is `single_string` to ensure that the submitted data is valid

Both cases will go through the `WeekDateToArrayTransformer` and thus should lead to a form error due to the `TransformationFailedException` that will be thrown then.

2019-10-16 16:57 UTC, andreybolonin commented
no chance to merged at 4.4 ?

2019-11-01 14:51 UTC, xabbuh commented
@dFayet I have incorporated the review feedback. This looks ready to me now. Thank you for your work on this. I have kept your commit so you will still get the full credit.

2019-11-01 14:52 UTC, xabbuh approved these changes

2019-11-01 15:34 UTC, dFayet commented
Thank to you @xabbuh but let's not forget that this is at least a 50-50 between us (+1 for you for your quick reaction)

2019-11-03 11:58 UTC, fabpot approved these changes

2019-11-03 11:59 UTC, fabpot commented
Thank you @dFayet.

2019-11-03 11:59 UTC, merged

2019-11-07 15:04 UTC, Hanmac commented
when looking at the [input week](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/week) page, would be a nice idea to have min and max for this too? or maybe as Validator?

the step parameter might be a bit more complicated

2019-11-07 16:35 UTC, xabbuh commented
@Hanmac That's already possible:

```php
$builder->add('week', WeekType::class, [
    'attr' => [
        'min' => '2018-W18',
        'max' => '2018-W26',
    ],
]);
```