[Mailgun Mailer] fixed issue when using html body
symfony/symfony pull request #32131
Opened 2019-06-21 11:59 UTC by alOneh

| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        |

I tested the `symfony/mailgun-mailer` and get an issue when using the `api` scheme with a templated email cause we try to manipulate a stream whereas the `Symfony\Component\Mime\Email::getHtmlBody()` could return also a string (in my case it is one).

The issue : 

```
stream_get_meta_data() expects parameter 1 to be resource, string given
```

2019-06-21 20:09 UTC, Simperfit approved these changes

2019-06-21 20:10 UTC, Simperfit requested changes

2019-06-21 20:10 UTC, Simperfit commented on src/Symfony/Component/Mailer/Tests/TransportTest.php
> +        $message = (new Email())->from('me@me.com')->to('you@you.com')->subject('hello')->html('test');
the test seems still to fail

2019-06-22 09:28 UTC, fabpot commented on src/Symfony/Component/Mailer/Bridge/Mailgun/Http/Api/MailgunTransport.php
> +        if (null !== $html && \is_resource($html)) {
Is it the only provider to do this?

2019-06-22 10:20 UTC, alOneh commented on src/Symfony/Component/Mailer/Bridge/Mailgun/Http/Api/MailgunTransport.php
> +        if (null !== $html && \is_resource($html)) {
yes

2019-06-26 08:47 UTC, fabpot approved these changes

2019-06-26 08:48 UTC, fabpot commented
Thank you @alOneh.

2019-06-26 08:48 UTC, merged