Added type-hint for CsrfTokenMangerInterface
symfony/symfony pull request #32208
Opened 2019-06-27 06:53 UTC by julien57

| Q             | A
| ------------- | ---
| Branch?       | Master
| Bug fix?      | no
| New feature?  | no 
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #32179
| License       | MIT
| Doc PR        | symfony/symfony-docs#..

Add type-hints in PR for CsrfTokenManagerInterface & CsrfTokenManager component.

2019-06-27 07:35 UTC, julien57 commented
__toString method of CsrfToken return a string.

2019-06-27 13:40 UTC, derrabus requested changes

2019-06-27 13:40 UTC, derrabus commented on src/Symfony/Component/Security/Csrf/CsrfTokenManagerInterface.php
> +    public function getToken(string $tokenId): string;
Adding a return type will break current implementations of the interface. Please concentrate on parameter type-hints for now.

2019-06-27 23:20 UTC, derrabus approved these changes

2019-06-29 06:44 UTC, fabpot approved these changes

2019-06-29 06:45 UTC, fabpot commented
Thank you @julien57.

2019-06-29 06:46 UTC, merged