[HttpFoundation] Removed dead code (ApacheRequest)
symfony/symfony pull request #32255
Opened 2019-06-28 12:41 UTC by lyrixx

| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets |
| License       | MIT
| Doc PR        |

`ApacheUrlMatcher` has been [deprecated in 2.7](https://github.com/symfony/symfony/pull/12728) and removed in 3.0
I think we forgot to remove this class too.

This class in never used in symfony, and there are no more reference in
the documentation.

2019-06-28 12:53 UTC, nicolas-grekas commented
Let's do it with BC: 4.4 with deprecation, removal in 5.0. We should play safe.

2019-06-28 13:19 UTC, lyrixx commented
Done :+1:

2019-06-28 13:32 UTC, xabbuh commented on UPGRADE-5.0.md
> +
additional blank line can be removed

2019-06-28 13:33 UTC, xabbuh commented on src/Symfony/Component/HttpFoundation/ApacheRequest.php
> + * @deprecated since Symfony 4.4. Use Request class instead.
[...] Use the Request [...]

2019-06-28 13:36 UTC, lyrixx commented on UPGRADE-5.0.md
> +
Thanks, fixed

2019-06-28 13:38 UTC, nicolas-grekas commented on src/Symfony/Component/HttpFoundation/ApacheRequest.php
> + * @deprecated since Symfony 4.4. Use the Request class instead.
please add a runtime notice too

2019-06-28 14:01 UTC, lyrixx commented on src/Symfony/Component/HttpFoundation/ApacheRequest.php
> + * @deprecated since Symfony 4.4. Use the Request class instead.
Done :+1:

2019-06-28 14:03 UTC, nicolas-grekas approved these changes

2019-06-28 14:19 UTC, norkunas requested changes

2019-06-28 14:19 UTC, norkunas commented on UPGRADE-4.4.md
> + * `ApacheRequest` is depreacted, use `Request` class instead.
`depreacted` -> `deprecated`

2019-06-28 14:19 UTC, norkunas commented on src/Symfony/Component/HttpFoundation/CHANGELOG.md
> + * `ApacheRequest` is depreacted, use the `Request` class instead.
`depreacted` -> `deprecated`

2019-06-28 14:21 UTC, lyrixx commented on UPGRADE-4.4.md
> + * `ApacheRequest` is depreacted, use `Request` class instead.
thanks, fixed :)

2019-06-28 14:31 UTC, ogizanagi approved these changes

2019-06-28 15:30 UTC, fabpot commented on UPGRADE-5.0.md
> + * `ApacheRequest` is deprecated, use the `Request` class instead.
has been removed

2019-06-28 16:00 UTC, lyrixx commented on UPGRADE-5.0.md
> + * `ApacheRequest` is deprecated, use the `Request` class instead.
Fixed thx

2019-06-28 16:14 UTC, Tobion approved these changes

2019-06-28 16:16 UTC, Tobion commented
please fix your commit message

2019-06-28 18:17 UTC, xabbuh approved these changes

2019-06-28 18:17 UTC, xabbuh commented on UPGRADE-5.0.md
> + * `ApacheRequest` is has been removed, use the `Request` class instead.
~is~

2019-07-01 08:07 UTC, lyrixx commented on UPGRADE-5.0.md
> + * `ApacheRequest` is has been removed, use the `Request` class instead.
Oups, Thanks. Fixed.

2019-07-01 08:46 UTC, lyrixx commented
Failures on AppVeyor not related 
> KO src\Symfony/Component/Mime

2019-07-01 09:48 UTC, fabpot approved these changes

2019-07-03 12:15 UTC, fabpot commented
Thank you @lyrixx.

2019-07-03 12:16 UTC, merged