[Process] [5.0] Add parameter type-hints
symfony/symfony pull request #32273
Opened 2019-06-28 22:52 UTC by tigitz

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no 
| Tests pass?   | yes    
| Fixed tickets | #32179 
| License       | MIT
| Doc PR        | N/A

This PR adds type hints to public interfaces and classes of the Process component. Some docblocks without valuable information got also removed.

2019-06-29 06:58 UTC, derrabus requested changes

2019-06-29 06:58 UTC, derrabus commented on src/Symfony/Component/Process/ExecutableFinder.php
> +    public function find(string $name, ?string $default = null, array $extraDirs = [])
```suggestion
    public function find(string $name, string $default = null, array $extraDirs = [])
```

CS: If the parameter has `null` as default value, we omit the `?`.

2019-06-30 21:27 UTC, nicolas-grekas commented on src/Symfony/Component/Process/Process.php
> +    public function stop($timeout = 10, int $signal = null)
`float` works for the timeout

2019-07-01 12:05 UTC, tigitz commented on src/Symfony/Component/Process/Process.php
> +    public function stop($timeout = 10, int $signal = null)
Indeed, good catch

2019-07-01 12:22 UTC, tigitz commented
@derrabus @nicolas-grekas While my initial scope was to take care of new type-hintable params allowed by 5.0, I went a little bit further and took care of others type-hintable params. But fact is, these additional type-hints can already lands in 4.* IMO and be seen as a continuation of https://github.com/symfony/symfony/pull/24722.

So I'll keep this PR exclusively about it's initial 5.0 scope and make another one targeting 4.* version with these additional type-hints.

Sorry for the bother

2019-07-05 05:03 UTC, fabpot approved these changes

2019-07-05 05:05 UTC, fabpot commented
Thank you @tigitz.

2019-07-05 05:06 UTC, merged