Fix multiSelect ChoiceQuestion when answers have spaces
symfony/symfony pull request #32503
Opened 2019-07-11 19:48 UTC by IceMaD

| Q             | A
| ------------- | ---
| Branch?       | 4.3
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #32502 
| License       | MIT
| Doc PR        | N/A

Probleme is explained in the issue

2019-07-11 21:59 UTC, Simperfit commented
If this is really something we want to do, it should be deprecated before doing so, because it will break existing command that rely on this.

2019-07-14 14:50 UTC, chalasr commented
Any bugfix might break someone's behavior. 
I think that this qualifies as a bug, and that no one reported it because usually people rely on keys for choosing multi-words answers.

This should apply to the 3.4 branch. And trimming should be disabled conditionally as of #31626 (4.4), we missed this part.

2019-07-15 20:32 UTC, IceMaD commented
Without the trim on multiple answers, it might break cases where answers don't have spaces but user input have. Exemple :
![break](https://user-images.githubusercontent.com/6181197/61246618-8eb51d80-a74f-11e9-889c-26a7ab94041f.png)

Maybe set all ChoiceQuestion as Trimmable by default on 4.4 for backward compatibility ?

2019-07-19 01:22 UTC, chalasr requested changes

2019-07-19 01:22 UTC, chalasr commented on src/Symfony/Component/Console/Tests/Question/ChoiceQuestionTest.php
> +    public function testSelectUseCases($isMiltiSelect, $answers, $expected, $message)
typo `isMiltiSelect`/`isMultiSelect`

2019-07-19 01:22 UTC, chalasr commented on src/Symfony/Component/Console/Tests/Question/ChoiceQuestionTest.php
> +            $this->assertEquals($actual, $expected, sprintf($message, $answer));
`sprintf()` seems unnecessary

2019-07-19 01:25 UTC, chalasr commented
@IceMad yes, trimming must stay enabled by default.

Can you please rebase against the 3.4 branch and change the PR base branch accordingly?

2019-07-24 15:12 UTC, chalasr approved these changes

2019-07-24 15:13 UTC, chalasr commented
Thank you @IceMaD.

2019-07-24 15:14 UTC, merged

2019-07-24 15:14 UTC, chalasr commented
And thank you for contributing to Symfony for the first time. Well done, congratz :)