[Mailer][DX] Improve exception message for unsupported scheme
symfony/symfony pull request #32608
Opened 2019-07-18 21:54 UTC by Koc

| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | waiting for Travis
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

This PR improves exception message for unsupported schemes by providing list of available. Throw something like: ` 'The "foo" scheme is not supported for mailer "mailgun". Supported schemes are: "api", "http", "smtp".'`

2019-07-19 07:03 UTC, fabpot approved these changes

2019-07-19 07:04 UTC, fabpot requested changes

2019-07-19 07:04 UTC, fabpot commented on src/Symfony/Component/Mailer/Exception/UnsupportedSchemeException.php
> +    public function __construct(Dsn $dsn, array $supported = null)
I would remove the ` = null` here. We can always provide the supported schemes.

2019-07-19 16:38 UTC, Koc commented
Status: needs review

2019-07-22 09:14 UTC, fabpot approved these changes

2019-07-22 09:18 UTC, fabpot commented
Thank you @Koc.

2019-07-22 09:19 UTC, merged