[Form] use a reference date to handle times during DST
symfony/symfony pull request #32718
Opened 2019-07-24 15:20 UTC by xabbuh

| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | yes
| Tests pass?   | yes
| Fixed tickets | #18366
| License       | MIT
| Doc PR        |

2019-07-24 15:26 UTC, stof requested changes

2019-07-24 15:26 UTC, stof commented on UPGRADE-4.4.md
> + * Using different values for the "model_timezone" and "view_timezone" options without configuring a reference date is
you should say `the "model_timezone" and "view_timezone" options of the TimeType`. These options also exist for other types (DateType and DatetimeType) for which there is no such deprecation AFAICT.

2019-07-24 15:29 UTC, stof commented on src/Symfony/Component/Form/Extension/Core/DataTransformer/DateTimeToArrayTransformer.php
> +        $this->referenceDate = $referenceDate ?: new \DateTime('1970-01-01 00:00:00');
should we use a `DateTimeImmutable` by default ?

2019-07-24 19:22 UTC, xabbuh commented
Status: Needs Review

2019-07-25 15:15 UTC, fabpot approved these changes

2019-07-25 15:17 UTC, fabpot commented
Thank you @xabbuh.

2019-07-25 15:18 UTC, merged