[TwigBundle] Remove deprecated templates and service
symfony/symfony pull request #32714
Opened 2019-07-24 14:03 UTC by yceruto

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

Follow up https://github.com/symfony/symfony/pull/32696, 
Require merge 4.4 into master after https://github.com/symfony/symfony/pull/32695 to make WebProfilerBundle work properly in master.

2019-07-24 18:27 UTC, Tobion requested changes

2019-07-25 12:39 UTC, yceruto commented on src/Symfony/Bundle/TwigBundle/Tests/DependencyInjection/TwigExtensionTest.php
> +            [realpath(__DIR__.'/AcmeBundle').'/Resources/views', 'Acme'],
Let's wait for https://github.com/symfony/symfony/pull/32740

2019-07-25 13:30 UTC, Tobion commented on src/Symfony/Bundle/TwigBundle/Tests/DependencyInjection/TwigExtensionTest.php
> +            [realpath(__DIR__.'/AcmeBundle').'/Resources/views', 'Acme'],
merged to master

2019-07-25 13:47 UTC, yceruto commented on src/Symfony/Bundle/TwigBundle/Tests/DependencyInjection/TwigExtensionTest.php
> +            [realpath(__DIR__.'/AcmeBundle').'/Resources/views', 'Acme'],
Rebased.

2019-07-25 13:51 UTC, Tobion commented
Why did you drop the removal of the deprecated /views?

2019-07-25 13:59 UTC, yceruto commented
Because I forgot to send the second commit :)

2019-07-25 14:22 UTC, Tobion approved these changes

2019-07-25 15:03 UTC, Tobion commented
Thank you @yceruto.

2019-07-25 15:04 UTC, merged