[Messenger] Fix redis last error not cleared between calls
symfony/symfony pull request #32726
Opened 2019-07-24 18:05 UTC by chalasr

| Q             | A
| ------------- | ---
| Branch?       | 4.3
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

Not clearing it gives misleading errors coming from previous calls which makes debugging hard.
@alexander-schranz FYI

2019-07-25 08:02 UTC, alexander-schranz requested changes
Else it looks good for me 👍.

2019-07-27 12:22 UTC, chalasr commented on src/Symfony/Component/Messenger/Tests/Transport/RedisExt/ConnectionTest.php
> + * @requires extension redis >= 4.3.0
4.2.0 is buggy on debian, we added a check that requires 4.3+. See #31791

2019-07-27 17:03 UTC, fabpot approved these changes

2019-07-27 17:05 UTC, fabpot commented
Thank you @chalasr.

2019-07-27 17:05 UTC, merged

2019-07-27 20:04 UTC, alexander-schranz commented on src/Symfony/Component/Messenger/Tests/Transport/RedisExt/ConnectionTest.php
> + * @requires extension redis >= 4.3.0
@chalasr thank you! This is good to know.