[Messenger] Fix incompatibility with FrameworkBundle <4.3.1
symfony/symfony pull request #32792
Opened 2019-07-28 20:35 UTC by chalasr

| Q             | A
| ------------- | ---
| Branch?       | 4.3
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #32738 
| License       | MIT
| Doc PR        | -

Aims to fix an edge case where you install (or upgrade to) symfony/messenger >=4.3.1 while having symfony/framework-bundle <4.3.1 installed.

2019-07-29 10:50 UTC, linaori requested changes
I think an extra addition should include a type check on the argument in the command, as it's never enforced. While I don't think this is a common case, using it without the framework bundle should also give a clear error rather than an invalid method call run-time.

```php
if ($routableBus instanceof ContainerInterface) {
    $routableBus = new RoutableMessageBus($routableBus);
} elseif (!$routableBus instanceof RoutableMessageBus) {
    throw new ...;
}
```

https://github.com/symfony/symfony/blob/d7d6d923efbbe7c8a7fd9b5b22b14e737662d47d/src/Symfony/Component/Messenger/Command/ConsumeMessagesCommand.php#L52-L60

2019-08-02 17:15 UTC, chalasr commented
@linaori check added, thanks!

2019-08-05 05:38 UTC, fabpot approved these changes

2019-08-05 05:39 UTC, fabpot commented
Thank you @chalasr.

2019-08-05 05:39 UTC, merged