[Form] type cannot be a FormTypeInterface anymore
symfony/symfony pull request #32934
Opened 2019-08-04 19:27 UTC by Tobion

| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | no 
| BC breaks?    | no     
| Deprecations? | yes/no 
| Tests pass?   | yes    
| Fixed tickets | 
| License       | MIT
| Doc PR        | 

Found in #32237

2019-08-04 20:20 UTC, vudaltsov approved these changes

2019-08-04 20:32 UTC, vudaltsov commented
`Symfony\Component\Form\Tests\FormBuilderTest::testAddFormType` should now go to the legacy group.

2019-08-04 20:33 UTC, vudaltsov requested changes
`Symfony\Component\Form\Tests\FormBuilderTest::testAddFormType` should now go to the legacy group.

2019-08-04 21:48 UTC, Tobion commented
I removed the outdated test.

2019-08-04 22:20 UTC, vudaltsov approved these changes

2019-08-05 02:15 UTC, oliverquynh approved these changes

2019-08-05 05:19 UTC, fabpot approved these changes

2019-08-05 05:21 UTC, fabpot commented
Thank you @Tobion.

2019-08-05 05:22 UTC, merged

2019-08-05 08:54 UTC, vudaltsov commented on src/Symfony/Component/Form/ButtonBuilder.php
> -     * @param string|FormBuilderInterface $child
@Tobion , why have you removed the `$child` phpdoc? It still gives useful information about the argument which cannot be replaced with a declaration.

2019-08-05 08:57 UTC, vudaltsov commented on src/Symfony/Component/Form/ButtonBuilder.php
> -     * @param string|FormBuilderInterface $child
oops, that's the ButtonBuilder, then it's okay, sorry)