[Lock] add type-hint whenever possible
symfony/symfony pull request #33004
Opened 2019-08-07 05:40 UTC by Simperfit

| Q             | A
| ------------- | ---
| Branch?       | 5.0
| Bug fix?      | no
| New feature?  | no 
| BC breaks?    | no     
| Deprecations? |no 
| Tests pass?   | yes    
| Fixed tickets | Contribute to #t32179 
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

Add type-hint in the lock component

2019-08-07 06:05 UTC, OskarStark commented
The fixed ticket should not include “t”

2019-08-07 13:06 UTC, derrabus requested changes

2019-08-07 13:06 UTC, derrabus commented on src/Symfony/Component/Lock/Strategy/StrategyInterface.php
> +    public function isMet(int $numberOfSuccess, int $numberOfItems);
You can remove the corresponding `@param` annotations.

2019-08-08 07:38 UTC, jderusse reviewed
Could you please add `acquire(bool $blocking = false)` in `LockInterface`?

2019-08-08 12:17 UTC, nicolas-grekas approved these changes
(I'm taking care of the comments while merging)

2019-08-08 12:18 UTC, nicolas-grekas commented
Thank you @Simperfit.

2019-08-08 12:19 UTC, closed without merging

2019-08-08 12:39 UTC, Simperfit commented
thanks @nicolas-grekas for taking care of the comments!