[ErrorHandler] Forward \Throwable
symfony/symfony pull request #33038
Opened 2019-08-08 08:33 UTC by fancyweb

| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | https://github.com/symfony/symfony/issues/32605
| License       | MIT
| Doc PR        | -

The goal of this PR is that `ErrorHandler::handleException()` handles `\Throwable` directly and forwards it  without altering it.

2019-08-08 10:44 UTC, derrabus commented on src/Symfony/Component/ErrorHandler/ErrorHandler.php
> +     * @param \Throwable $exception An exception to handle
This `@param` annotation can be removed now.

2019-08-09 17:32 UTC, Tobion commented on src/Symfony/Component/ErrorHandler/Tests/ErrorHandlerTest.php
> +    public function testHandleExceptiossssn(string $expectedMessage, \Throwable $exception)
typo?

2019-08-13 04:24 UTC, Tobion commented on src/Symfony/Component/ErrorHandler/ErrorHandler.php
> +                $type = $log[2]['exception'] instanceof \ErrorException ? $log[2]['exception']->getSeverity() : ThrowableUtils::getSeverity($log[2]['exception']);
you could handle `\ErrorException` inside `ThrowableUtils::getSeverity`. seems cleaner to me.

2019-08-13 04:25 UTC, Tobion commented on src/Symfony/Component/ErrorHandler/ErrorHandler.php
> +        $type = $exception instanceof FatalErrorException ? $exception->getSeverity() : ThrowableUtils::getSeverity($exception);
same: you could handle `FatalErrorException ` inside `ThrowableUtils::getSeverity`

2019-09-10 12:07 UTC, stof requested changes

2019-09-10 12:07 UTC, stof commented on src/Symfony/Component/ErrorHandler/ThrowableUtils.php
> +        } elseif ($throwable instanceof \TypeError) {
should be `if` as the previous code path always returns.

2019-09-27 06:23 UTC, fabpot approved these changes

2019-09-27 06:24 UTC, fabpot commented
Thank you @fancyweb.

2019-09-27 06:24 UTC, merged