Remove unused code
symfony/symfony pull request #33070
Opened 2019-08-08 19:59 UTC by 243083df

| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes 
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

2019-08-09 08:54 UTC, 243083df commented
@nicolas-grekas what to do with exceptions and does we need to keep index from incoming array, because current realization only keep priority?

2019-08-09 09:05 UTC, nicolas-grekas commented
I've no idea what you're trying to achieve and why so I cannot comment sorry...
Usually, failing test cases are the symptom of a BC break, so you'll need to think about what they mean in this regard.

2019-08-09 11:18 UTC, 243083df commented
Yes it break BC on exception class level. But exception now more correct. Second it has minor speedup of cache warmup. Third since denormalizer and normalizer has separate cache, i think separate registered normalizers and denormalizers unify internal code

2019-08-15 11:42 UTC, dunglas approved these changes
I like it, but the change on the cache must be double-checked and profile to be sure there are no performance regressions.

2019-08-30 14:05 UTC, 243083df commented
How can should i do it?

2019-09-27 16:39 UTC, nicolas-grekas requested changes

2019-09-27 16:39 UTC, nicolas-grekas commented on src/Symfony/Component/Serializer/Serializer.php
> -        $this->normalizers = $normalizers;
I think we need to keep all the code infrastructure related to this property to keep BC. Then we'll be able to remove the code in 5.0.

2019-09-27 16:39 UTC, nicolas-grekas commented on src/Symfony/Component/Serializer/Serializer.php
> +     * @internal since Symfony 4.4
let's make the property private then

2020-08-11 10:11 UTC, fabpot commented
Closing as there is no more activities. Feel free to reopen if you have time to finish the work.

2020-08-11 10:11 UTC, closed without merging