[Messenger][DX] Display real handler if handler is wrapped
symfony/symfony pull request #33113
Opened 2019-08-11 13:42 UTC by DavidBadura

| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | none
| License       | MIT
| Doc PR        | none

Before:

<img width="718" alt="Bildschirmfoto 2019-08-11 um 15 35 10" src="https://user-images.githubusercontent.com/470138/62834539-5faaa280-bc4e-11e9-99d6-a7e98822108c.png">

After:

<img width="673" alt="Bildschirmfoto 2019-08-11 um 15 34 27" src="https://user-images.githubusercontent.com/470138/62834540-646f5680-bc4e-11e9-9aa7-c5fb5219204c.png">

2019-08-12 03:27 UTC, Tobion commented
What do you mean by wrapped handler?

2019-08-12 07:30 UTC, DavidBadura commented
If you use the `Symfony\Component\Messenger\Handler\MessageSubscriberInterface` interface and your handler does not use (only) the __invoke method, then Symfony wrapped your service with a callback wrapper. See: https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Messenger/DependencyInjection/MessengerPass.php#L136

This wrapper get an autogenerated service id like `.messenger.method_on_object_wraper.xxxxx`, which is just an internal service. In the `messenger:debug` command is this information not really useful.

2019-08-18 16:06 UTC, sroze requested changes
Can you change the naming of the `realHandlerMapping` variable? It's quite hard to understand what is going on with its current name. Otherwise, I don't see a better way of doing so 👍

2019-08-18 16:06 UTC, sroze commented on src/Symfony/Component/Messenger/DependencyInjection/MessengerPass.php
> +        $realHandlerMapping = [];
```suggestion
        $handlerToOriginalServiceIdMapping = [];
```

2019-08-22 13:12 UTC, DavidBadura commented on src/Symfony/Component/Messenger/DependencyInjection/MessengerPass.php
> +        $realHandlerMapping = [];
@sroze done 👍

2019-08-24 08:58 UTC, DavidBadura commented
Status: Needs Review

2019-09-25 19:11 UTC, fabpot approved these changes

2019-09-25 19:12 UTC, fabpot commented
Thank you @DavidBadura.

2019-09-25 19:12 UTC, merged