[HttpFoundation] Precalculate session expiry timestamp
symfony/symfony pull request #33169
Opened 2019-08-14 14:59 UTC by azjezz

| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no  
| Deprecations? | yes
| Tests pass?   | yes  
| Fixed tickets | #13955, #21423, #14625
| License       | MIT

Continued work from the original PR #21423 / #21857

2019-08-15 07:29 UTC, nicolas-grekas commented
The migration path doesn't work IMHO.
Instead, I propose to keep the name of the column and of the property as is.
Then, the column should be indexed, and we should use it to store absolute expiries.
To have smooth compat with current sessions, to decide when a value in the column is a lifetime or an expiry, we would compare values to `315576000` (10 years): when the number is higher, it's an absolute date, when it's ower, it's a relative date.
GC would be done in two DELETE queries, for >315576000 and <=315576000.
In v6, we would simply drop the <=315576000 one, because in two years we'll be able to consider that all relevant sessions have been migrated to absolute dates.

2019-08-15 09:06 UTC, nicolas-grekas commented on src/Symfony/Component/HttpFoundation/Session/Storage/Handler/PdoSessionHandler.php
> +                $sql = "DELETE FROM $this->table WHERE ($this->lifetimeCol < :time AND $this->lifetimeCol > :min) OR ($this->lifetimeCol + $this->timeCol < :time)";
using `OR` means that the DB engine won't use the index AFAIK
that's why I suggested using two queries

2019-08-15 09:07 UTC, nicolas-grekas commented on src/Symfony/Component/HttpFoundation/Session/Storage/Handler/PdoSessionHandler.php
> +            $stmt->bindValue(':min', 315576000, \PDO::PARAM_INT);
let's use a private const for clarifty

2019-08-15 17:39 UTC, nicolas-grekas approved these changes
LGTM thanks, just one minor comment

2019-08-15 17:39 UTC, nicolas-grekas commented on src/Symfony/Component/HttpFoundation/Session/Storage/Handler/PdoSessionHandler.php
> +            }
bad indentation

2019-08-16 06:25 UTC, nicolas-grekas commented on src/Symfony/Component/HttpFoundation/Session/Storage/Handler/PdoSessionHandler.php
> +            $this->pdo->exec("CREATE INDEX EXPIRY ON $this->table ($this->lifetimeCol)");
we could add this query (with default table+col) in UPGRADE4.4&5.0 files to hint ppl they should add the index

2019-08-16 06:25 UTC, nicolas-grekas commented on src/Symfony/Component/HttpFoundation/Session/Storage/Handler/PdoSessionHandler.php
> +            $stmt = $this->pdo->prepare($legacySql);
with this comment before: `// to be removed in 6.0`

2019-08-17 00:48 UTC, Tobion requested changes

2019-08-17 00:48 UTC, Tobion commented on UPGRADE-4.4.md
> + * `PdoSessionHandler` now precalculates the expiry timestamp in the lifetime column, make sure to run `CREATE INDEX EXPIRY ON sessions (sess_lifetime)` to update your database.
You should add why it's recommended to add the index: to speed up gc of expired sessions

2019-08-17 00:48 UTC, Tobion commented on src/Symfony/Component/HttpFoundation/Session/Storage/Handler/PdoSessionHandler.php
> +                    $expiry += $sessionRows[0][2];
this also means, we do not need to fetch the time column data in the future at all. please add a comment on the select sql so we remember

2019-08-19 09:03 UTC, nicolas-grekas approved these changes

2019-08-20 14:52 UTC, nicolas-grekas commented
Thank you @azjezz.

2019-08-20 14:52 UTC, merged

2019-11-21 13:19 UTC, tseho commented
Hello @nicolas-grekas, I think this is a BC break. On mysql, the lifetime column has been for the last few years a MEDIUMINT column.

The new version with `time() + $maxlifetime` instead of `$maxlifetime` is higher than the MEDIUMINT mysql limit.

When upgrading from symfony 4.3 to 4.4 with an existing database, we have the error `SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'sess_lifetime' at row 1`

I saw the creation of the session table has been fixed 5 days ago in https://github.com/symfony/symfony/pull/34410/files but that does not fix existing databases.

Is it normal we need to create manually a sql migration for a breaking database schema change, which is not really mentioned in UPGRADE-4.4.md ?

2019-11-21 13:24 UTC, nicolas-grekas commented
That's an interesting feedback @tseho but please create an issue: nobody is tracking comments on closed PRs.

2019-11-21 13:52 UTC, tseho commented
Thanks for your response and sorry about that, I just created a new issue : https://github.com/symfony/symfony/issues/34491