[OptionsResolver] Display full nested option hierarchy in exceptions
symfony/symfony pull request #33295
Opened 2019-08-22 16:19 UTC by fancyweb

| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

It kind of improve the DX, especially when you define a lot of nested form options since the file and line cannot be displayed.

```php
$resolver->setDefaults([
    'array' => function (OptionsResolver $arrayResolver): void {
        $arrayResolver->setRequired('foo');
    },
]);

```

Before:
`The required option "foo" is missing.`

After:
`The required option "array[foo]" is missing.`

2019-08-22 16:20 UTC, fancyweb commented on src/Symfony/Component/OptionsResolver/OptionsResolver.php
> +            throw new UndefinedOptionsException(sprintf('The option "%s" does not exist, defined options are: "%s".', $this->formatOptionsForAnException($option), implode('", "', array_keys($this->de
I guess that prefixing all defined options would be too heavy.

2019-08-22 16:52 UTC, yceruto commented
New feature IMO

2019-08-22 17:05 UTC, yceruto requested changes

2019-08-22 17:05 UTC, yceruto commented on src/Symfony/Component/OptionsResolver/OptionsResolver.php
> +        if (!empty($this->parentsOptions)) {
`([] !== $this->parentsOptions)` or just `($this->parentsOptions)`?

2019-08-22 17:36 UTC, yceruto commented on src/Symfony/Component/OptionsResolver/OptionsResolver.php
> +    private function formatOptionsForAnException($options): string
I think `formatOptions()` is clear enough here

2019-08-23 12:59 UTC, yceruto approved these changes

2019-09-04 10:07 UTC, arzzen approved these changes

2019-09-08 06:55 UTC, fabpot approved these changes

2019-09-08 06:56 UTC, fabpot commented
Thank you @fancyweb.

2019-09-08 06:57 UTC, merged