[SecurityGuard] Deprecate returning non-boolean values from checkCredentials()
symfony/symfony pull request #33308
Opened 2019-08-23 16:10 UTC by derrabus

| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | yes
| Tests pass?   | yes
| Fixed tickets | prepares #33228
| License       | MIT
| Doc PR        | TODO

This PR suggests to deprecate implementations of `Symfony\Component\Security\Guard\AuthenticatorInterface::checkCredentials()` that return non-boolean values. This will allow us to add `bool` as return type in the future.

https://github.com/nicolas-grekas/symfony/pull/26#discussion_r317084918

/cc @nicolas-grekas @weaverryan

2019-08-23 16:27 UTC, chalasr requested changes
CHANGELOG/UPGRADE files need to be updated

2019-08-23 16:28 UTC, chalasr commented on src/Symfony/Component/Security/Guard/Tests/Provider/GuardAuthenticationProviderTest.php
> +        $this->expectException('Symfony\Component\Security\Core\Exception\BadCredentialsException');
Please use `::class` for new tests

2019-08-23 18:45 UTC, chalasr approved these changes

2019-08-23 18:45 UTC, derrabus commented
Status: Needs Review

2019-08-25 06:58 UTC, fabpot approved these changes

2019-08-25 06:59 UTC, fabpot commented
Thank you @derrabus.

2019-08-25 07:00 UTC, merged