[Console] Add `cc` alias for `cache:clear`
symfony/symfony pull request #33320
Opened 2019-08-24 10:20 UTC by ruudk

| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| License       | MIT

Instead of typing `bin/console cache:clear` or `bin/console c:c` you can now type `bin/console cc`.

2019-08-24 11:38 UTC, fabpot commented
I didn't had the classic symfony 1 `cc` shortcut as I think that you rarely need to run this command yourself in dev mode (should be almost never).

2019-08-24 11:48 UTC, ruudk commented
We use it from time to time. We have Doctrine metadata cache set-up in a big project to speed things. If you want to create migrations, you first need to clear cache. Also, some libraries sometimes need a cache:clear to get things working. Or for example when you modify things in `vendor` folder, the cache is not immediately re-generated. You might say: why change things in vendor? Most of the time to see if certain tweaks work, so that you can create a PR for it later.

2019-08-24 11:50 UTC, ismail1432 commented
`ca:cl` is not enough ?

2019-08-24 12:53 UTC, ruudk commented
c:c also works, but cc is shorter ;-)

2019-08-24 21:34 UTC, chalasr requested changes
No strong opinion on this one

2019-08-24 21:34 UTC, chalasr commented on src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php
> +            ->setAliases(['cc'])
Because the command is lazy-loaded, the right way to give it an alias is to add an additional `console.command` tag on its service definition.

2019-08-25 07:45 UTC, linaori commented
When installing vendor bundles, it's better to first throw away your entire cache by removing it from the file system, and this is something I will always recommend over running the command. I personally don't see the need for this alias as it's only 1 character shorter. You could do something like this instead:
```sh
alias cc="rm -rf var/cache/*"
```

2019-09-08 06:54 UTC, fabpot commented
Closing as I'm still not convincedr.

2019-09-08 06:54 UTC, closed without merging