[Ldap] Add LDAP error codes to exceptions #28677
symfony/symfony pull request #33339
Opened 2019-08-26 13:36 UTC by dontub

This PR ensures that an LdapException is only used when an LDAP
operations fails. In cases an LdapException was used for non LDAP
operations it is replaced by an appropriate exception.

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | `LdapException` requires error code now. (I wouldn't expect it to be relevant for any component user.)
| Deprecations? | no
| Tests pass?   | yes 
| Fixed tickets | #28677
| License       | MIT

This PR ensures that an `LdapException` is only used when an LDAP operations fails. The constructor of `LdapException` enforces that an error code is specified. In cases an `LdapException` was used for non LDAP operations it is replaced by an appropriate exception.

Additionally silencing is added to ldap functions where missing.

2019-08-26 18:57 UTC, OskarStark commented
I like your work but to me it’s a no break not about the error code (which could be handled and deprecated first) but someone who is catching an LdapException now got a different one and the try catch doesn’t  work as expected anymore...

This could be reworked b extending LdapException by the newly introduced exceptions which would be BC.

2019-08-27 12:34 UTC, dontub commented
> This could be reworked b extending LdapException by the newly introduced exceptions which would be BC.

I first thought about it. Though if any of the new exceptions is thrown, the using software cannot work correctly nowadays (and I wanted to avoid extra work to fix the class hierarchy in Sf 5). Nevertheless, you are right, to completely keep the same behavior they should extend `LdapException`. Do you think this is necessary for `DomainException` as well? This one is thrown here:
https://github.com/symfony/symfony/blob/f8ccd48f09152b75541a4d3a0ad8ee7e31b76ad3/src/Symfony/Component/Ldap/Adapter/ExtLdap/Query.php#L84
Though that we have a valid scope is already ensured by the `OptionsResolver`:
https://github.com/symfony/symfony/blob/f8ccd48f09152b75541a4d3a0ad8ee7e31b76ad3/src/Symfony/Component/Ldap/Adapter/AbstractQuery.php#L41

2019-08-30 10:39 UTC, dontub commented
BC is now ensured (apart from `DomainException`, see comment above). That the checks fail doesn't seem to be my fault.

2019-10-09 11:20 UTC, dontub commented
Let me know if anything is left to change.

2020-02-04 08:54 UTC, fabpot requested changes

2020-02-04 08:54 UTC, fabpot commented on src/Symfony/Component/Ldap/Adapter/ExtLdap/Collection.php
> +                throw LdapException::create('Error while retrieving entry count: [{errorCode}] {errorMsg}.', ldap_errno($con));
We are not doing this in Symfony, can you please revert the `::create()` method?

2020-02-04 09:01 UTC, OskarStark commented
I would take care of this PR if we get no feedback by the author

2020-02-04 16:10 UTC, dontub commented
@OskarStark I'm currently busy with other stuff, so feel free to take it up.

2020-02-04 19:08 UTC, OskarStark commented
Could you please add me as a collaborator to your fork?

2020-02-05 18:39 UTC, dontub commented
> Could you please add me as a collaborator to your fork?

Done

2020-03-02 10:46 UTC, fabpot commented
Closing in favor of #35913

2020-03-02 10:46 UTC, closed without merging