Ticket 33592
symfony/symfony pull request #33642
Opened 2019-09-19 18:22 UTC by mazarini

| Q             | A
| ------------- | ---
| Branch?       | 4.3
| New feature?  | yes 
| License       | MIT

Allow phpunit install --ignore-platform-reqs to test php 8.0

2019-09-19 19:01 UTC, mazarini commented
All seems to work before a bad commit on src/Symfony/Bridge/PhpUnit/DeprecationErrorHandler.php
and a try to resolve conficts.
I can nothing nothing for DeprecationErrorHandler.php (fix php syntax only to test)

I have to look on simple-phpunit.php to understand what append.

You can see https://travis-ci.org/mazarini/demo/builds/587072348 : symfony/demo working with php 8.0

2019-09-19 22:09 UTC, mazarini commented
Now I need to solve the reinstall of phpunit each time. Its come from bad resolving confict.
Second problem is "SYMFONY_PHPUNIT_BRIDGE_PR=ticket_33592".

Note that now symfony/demo is working with php 8.0 on TravisCI.

2019-09-24 11:22 UTC, mazarini commented
I'm not sure that I choose the best solution with using --ignore-platform-reqs. 
Using an EnvVar can do the same and allow what option we want, not only this one.

2019-09-24 11:45 UTC, stof requested changes
Why are you reincluding diff of other features in this PR ? I think you messed the git history of your PR.

2019-09-24 11:45 UTC, stof commented on .travis.yml
> +      SYMFONY_PHPUNIT_BRIDGE_PR=ticket_33592
This change is wrong:

- `ticket_33592` is not a valid PR number
- this PR is a PR editing the bridge itself, not a PR when you want to use a pending PR on the bridge to run tests, so there is no reason to use that feature.

2019-09-24 15:44 UTC, mazarini commented on CHANGELOG-4.3.md
> + * feature #33592 [PhpUnitBridge] allow install of PHPUnit with option --ignore-platform-reqs (mazarini)
I think it's better to do a new PR. I have make to much error (problem with php-cs, apply patch, try to solve conflict). 
Tell me the branch to fork.
And choose between "phpunit --ignore-platform-reqs" or "export PHPUNIT_COMPOSER_FLAG = --ignore-platform-reqs && phpunit"

2019-09-26 21:40 UTC, nicolas-grekas commented on src/Symfony/Bridge/PhpUnit/bin/simple-phpunit.php
> +$defaultEnvs = [
please revert all changes from fabbot, they're not applicable to this particular bridge

2019-09-26 21:41 UTC, nicolas-grekas commented
Note that there is an alternative since this is for early experimentations:
- run `simple-phpunit install` on PHP 7.*
- run it again with proper arguments on PHP 8

2019-09-27 20:17 UTC, mazarini commented
I hope file are well reset now.
I have use an envvar ($SYMFONY_PHPUNIT_COMPOSER_OPTION). 
We can use "--ignore-platform-reqs" or an other option.

2019-10-21 17:54 UTC, alexander-schranz commented
@mazarini are you still working on this? Looking forward to this feature to test agains PHP 8.

2019-10-22 06:06 UTC, mazarini commented
@alexander-schranz I'm waiting feedback to know what I have to do : use flag or envvar, name of flag or anvvar. I prefere envvar.       
I'll probably close it and do a new proposal when 4.4 is ready.
Note I use it on travis, just copy the modified file before test.

2019-11-25 20:56 UTC, mazarini commented
Replace by PR #34615

2019-11-25 20:56 UTC, closed without merging