[FrameworkBundle] encourage installing intl when String is available
symfony/symfony pull request #33825
Opened 2019-10-03 07:59 UTC by nicolas-grekas

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | -

2019-10-03 08:56 UTC, gharlan requested changes

2019-10-03 08:56 UTC, gharlan commented on src/Symfony/Component/String/Slugger/AsciiSlugger.php
> +        if (\array_key_exists($locale, $this->transliterators[$locale]) {
```suggestion
        if (\array_key_exists($locale, $this->transliterators) {
```

2019-10-03 08:57 UTC, nicolas-grekas commented on src/Symfony/Component/String/Slugger/AsciiSlugger.php
> +        if (\array_key_exists($locale, $this->transliterators[$locale]) {
thanks

2019-10-03 09:59 UTC, tgalopin approved these changes

2019-10-03 10:57 UTC, yceruto approved these changes

2019-10-03 11:15 UTC, maxhelias approved these changes

2019-10-03 12:01 UTC, yceruto commented on src/Symfony/Component/String/Slugger/AsciiSlugger.php
> +        if (\array_key_exists($locale, $this->transliterators) {
missing `)`

2019-10-03 13:24 UTC, javiereguiluz approved these changes

2019-10-04 07:51 UTC, merged

2019-10-04 21:44 UTC, jakzal commented
Unfortunately, this makes the `intl` extension required if the String component is present :(

2019-10-04 21:47 UTC, nicolas-grekas commented
We should skip the notice if `\defined('PHPUNIT_COMPOSER_INSTALL')`, that should be enough.

2019-10-05 05:59 UTC, jakzal commented
Won't this only fix the tests? The intl extension will still be required if the String component is present.

2019-10-05 06:09 UTC, nicolas-grekas commented
Not with polyfills - or did you spot something that is not polyfilled?

2019-10-05 06:20 UTC, jakzal commented
Nope, I understand now :)