[DoctrineBridge] Auto-validation must work if no regex are passed
symfony/symfony pull request #33828
Opened 2019-10-03 09:53 UTC by dunglas

| Q             | A
| ------------- | ---
| Branch?       | 4.3
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | n/a
| License       | MIT
| Doc PR        | n/a

Backport of https://github.com/symfony/symfony/pull/32107/files#r295762928.
This behavior if faulty, if no regex are passed, autvalidation must be triggered, [as done in `PropertyInfoLoader`](https://github.com/symfony/symfony/blob/4.3/src/Symfony/Component/Validator/Mapping/Loader/PropertyInfoLoader.php#L50).

2019-10-07 09:12 UTC, xabbuh requested changes
We then need to think about what we do with the loader when no regex is configured in the FrameworkBundle. Otherwise, this change would reopen #31743 again (the change reverted here was part of the bugfix in #31749).

2019-10-15 20:33 UTC, dunglas commented
At least, the behavior must be consistent between `PropertyInfoLoader` and this one don't you think?

2019-10-15 20:44 UTC, dunglas commented
The current behavior makes it harder to use this class when using only the component (without framework bundle). I'm favor of patching FrameworkBundle instead.

2019-10-17 04:45 UTC, xabbuh commented
Deregistering the loader service when no regex is configured would solve that, right?

2019-10-28 21:49 UTC, dunglas commented
@xabbuh implemented, could you check if it's ok for you now?

2019-10-29 08:44 UTC, nicolas-grekas approved these changes

2019-10-29 09:39 UTC, xabbuh approved these changes

2019-10-29 10:03 UTC, merged