Add stdClass support for serializer
symfony/symfony pull request #33869
Opened 2019-10-05 07:29 UTC by henry2778

| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #33047
| License       | MIT
| Doc PR        | --

Hello everyone. Here my suggestion about https://github.com/symfony/symfony/issues/33047 issue. Basically the intention is to handle stdClasses as associaive arrays on serialization. Another option is to create separate normalizer, but I think that is too much.

2019-10-05 07:42 UTC, OskarStark requested changes

2019-10-05 07:42 UTC, OskarStark commented on src/Symfony/Component/Serializer/Tests/Fixtures/EmptyDummy.php
> +}
Missing newline

2019-10-05 08:51 UTC, henry2778 commented on src/Symfony/Component/Serializer/Tests/Fixtures/EmptyDummy.php
> +}
fixed, thanks

2019-10-07 12:00 UTC, dunglas commented
This PR should target 4.4 as it's a new feature.

2019-10-07 18:47 UTC, henry2778 commented
Closing in favor of https://github.com/symfony/symfony/pull/33894

2019-10-07 18:47 UTC, closed without merging