[PropertyAccessor] Add getValues method (like array_column)
symfony/symfony pull request #33876
Opened 2019-10-06 15:58 UTC by soufianZantar

| Q             | A
| ------------- | ---
| Branch?       | master 
| Bug fix?      | no
| New feature?  | yes 
| Deprecations? | yes/no 
| Tickets       | #30647  
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

**getValues** method will return an array of valid values from an array of data/objects.
If an element of array return null will not be added to result or an element of array throw an exception the method will catch the exception and continue the loop.

**I think this method will be very useful to get a specific data from arrays with different data like this example:**

```
$persons = [
    'first_name' => 'Wouter',
    'company' => 'Company Name',
    'first_name' => 'Fabien',
];

var_dump($propertyAccessor->getValues($persons, '[first_name]'));

```
will get:
```
Array
(
    [0] => 'Wouter'
    [1] => 'Fabien'
)
```

2019-10-07 07:35 UTC, medinae requested changes

2019-10-07 07:35 UTC, medinae commented on src/Symfony/Component/PropertyAccess/PropertyAccessor.php
> +            try {
`try/catch` blocks should be as specific as possible.

For eg., in that case, 
```
if (null === $value) {
    continue;
}

$values[] = $value;
```

Don't need to be inside the block.

2019-10-07 07:35 UTC, medinae commented on src/Symfony/Component/PropertyAccess/PropertyAccessorInterface.php
> +     */
`* @return array`

2019-10-07 08:20 UTC, fancyweb requested changes
I personally feel like this new method ain't really worth it since it can be replaced by one `foreach` or `array_map`.

2019-10-07 08:20 UTC, fancyweb commented on src/Symfony/Component/PropertyAccess/PropertyAccessorInterface.php
> +    public function getValues(array $array, $propertyPath): array;
Adding a new method on the interface directly is not backward compatible. I guess the first step would be to add it as a "virtual" `@method` on 4.4 and document it in CHANGELOG and UPGRADE.

2019-10-07 08:20 UTC, fancyweb commented on src/Symfony/Component/PropertyAccess/Tests/PropertyAccessorArrayAccessTest.php
> +    public function getValidPropertyPathsForGetValues()
The test does not seem to cover enough cases. You at least need to add values that should not be returned. Also add values that will cause exceptions for example.

2019-10-07 08:20 UTC, fancyweb commented on src/Symfony/Component/PropertyAccess/PropertyAccessor.php
> +            } catch (ExceptionInterface $e) {
IMHO, catching exceptions silently here is a no go. `getValues` needs to be coherent with `getValue` and with the whole class. Handling those exceptions is userland responsibility.

2019-10-07 08:20 UTC, fancyweb commented on src/Symfony/Component/PropertyAccess/PropertyAccessor.php
> +                if (null === $value) {
`null` can be a perfectly fine domain value.

2019-10-07 09:09 UTC, stof commented
I don't think we need this method in the PropertyAccessorInterface. It brings several concerns (how are errors handled ? Should `null` be ignored ?), which will depend on the use case. And so this method would fit only part of the use cases.
Thus, this method is build on top of the existing public API of the interface, and building separate implementations (generated for specific classes for instance, as was already suggested in the past) would probably need to provide exactly the same implementation for this method. I think such helper is best kept as a higher level API than extending the interface (favoring composition over inheritance). So for now, this gets a -1 vote from me.

2019-10-08 09:00 UTC, soufianZantar commented
I think the method should ignored `null `because she retourn a list of values, but a `null `inside a list of values will not be helpful. In wich use case `null `insed list of values will be used?

I added this method because the issues get 4 👍 . i thought the community need this feature.

My idea is to render multidimensional array search by value more easy using the powerful of property access.

if you think this method not helpful for dev, we must close the issue.
if you think only the way ( add the method to interface) is bad, what is the best way to add this feature?

2020-02-04 14:36 UTC, fabpot commented
Closing for the reason given by @stof.

2020-02-04 14:36 UTC, closed without merging