Fix BC Compatibility to use old FlattenException in ExceptionController
symfony/symfony pull request #33918
Opened 2019-10-08 18:42 UTC by alexander-schranz

| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #... 
| License       | MIT
| Doc PR        | 

If you create a CustomExceptionController and typehinted the showAction with the old FlattenException this will break.

Maybe a better solution would to change that the new extend from the old in https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/ErrorRenderer/Exception/FlattenException.php#L381 instead of the old extending the new.

2019-10-08 18:59 UTC, yceruto requested changes
Same opinion as https://github.com/symfony/symfony/pull/33916#pullrequestreview-298977190 (:-1:)

The solution will be require `symfony/debug` as hard dependecy to avoid BC break.

https://github.com/symfony/symfony/pull/32873#discussion_r309901441
> We provide no guarantee at the dependency level: if ppl use Debug but have it transitively, it's accepted policy to require them to make it an explicit dep as of the next version (minor included)
Said another way: the BC policy covers the API, not the deps.

2019-10-08 19:10 UTC, alexander-schranz commented
@yceruto Sorry this does not work in this case. I change to have symfony/debug as requirement in my library and it is installed but as you see here: https://github.com/symfony/symfony/blob/53bfa04f9bf3ccebcb7d94c143b1f6895d034758/src/Symfony/Component/HttpKernel/EventListener/ExceptionListener.php#L128
Symfony ExceptionListener create a new FlattenException and as that does not extend from the old one. You will get an error that a false FlattenException is given.

2019-10-09 00:16 UTC, alexander-schranz commented
I think its a similiar issue we had with the KernelBrowser and the Client here:

https://github.com/symfony/symfony/issues/31762 which was then later fixed in:
https://github.com/symfony/symfony/pull/31881

The change in this PR is maybe not correct. But think the only way to keep compatibility is that a new added Class extends the old one and not the other way around.

2019-10-09 12:10 UTC, alexander-schranz commented
Want to move this discussion to an issue: #33929

2019-10-09 12:10 UTC, closed without merging