[TwigBridge] Add show-deprecations option to the lint:twig command
symfony/symfony pull request #33961
Opened 2019-10-11 20:17 UTC by yceruto

| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #33957 (partially)
| License       | MIT
| Doc PR        | TODO

![lint-twig-deprecations](https://user-images.githubusercontent.com/2028198/66682028-fe994e00-ec41-11e9-91f3-43885c9ee48b.png)

2019-10-12 06:04 UTC, chalasr requested changes

2019-10-14 12:46 UTC, yceruto commented
@chalasr comments addressed. Thanks!

2019-10-14 13:14 UTC, nicolas-grekas approved these changes

2019-10-14 17:47 UTC, chalasr approved these changes

2019-10-14 19:49 UTC, fabpot approved these changes

2019-10-14 19:50 UTC, fabpot commented
Thank you @yceruto.

2019-10-14 19:50 UTC, merged