[Notifier] Add Firebase bridge
symfony/symfony pull request #33968
Opened 2019-10-12 18:08 UTC by Jeroeny

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | See #33687
| License       | MIT

This would add [Firebase](https://firebase.google.com) integration for the Notifier component. With Firebase you can send push notifications to the users of you Android and iOS app and website (formerly known as Google Cloud messaging).

I'm not sure if it's possible to have this merged, like the other bridges. Or if I should create a stand-alone repository? That'd be fine too.

Also it's now using the `ChatMessage` as implementation of `Symfony\Component\Notifier\Message\MessageInterface`, but I feel like this component could use a `PushMessage` or something similar. Although I'm not sure if it would contain more than `subject` that the `ChatMessage` does.

2019-10-12 20:20 UTC, noniagriconomie commented on src/Symfony/Component/Notifier/Bridge/Firebase/FirebaseTransport.php
> +     * @see https://core.telegram.org/bots/api
typo?

2019-10-12 20:23 UTC, noniagriconomie commented on src/Symfony/Component/Notifier/Bridge/Firebase/Notification/IOSNotification.php
> +    public function androidChannelId(string $androidChannelId): self
IOS but the method is android? is it a typo?

2019-10-14 10:56 UTC, Jeroeny commented on src/Symfony/Component/Notifier/Bridge/Firebase/FirebaseTransport.php
> +     * @see https://core.telegram.org/bots/api
Oops, thanks. Fixed both.

2020-02-05 21:57 UTC, OskarStark commented on src/Symfony/Component/Notifier/Bridge/Firebase/CHANGELOG.md
> +5.0.0
5.1

2020-02-05 21:57 UTC, OskarStark commented on src/Symfony/Component/Notifier/Bridge/Firebase/FirebaseOptions.php
> + * @experimental in 5.0
5.1

2020-02-05 21:57 UTC, OskarStark commented on src/Symfony/Component/Notifier/Bridge/Firebase/FirebaseOptions.php
> + * @internal
AFAIK this is not correct

2020-02-05 21:57 UTC, OskarStark commented on src/Symfony/Component/Notifier/Bridge/Firebase/FirebaseTransport.php
> + * @internal
AFAIK this is not correct

2020-02-05 21:57 UTC, OskarStark commented on src/Symfony/Component/Notifier/Bridge/Firebase/FirebaseTransport.php
> + * @experimental in 5.0
5.1

2020-02-05 21:57 UTC, OskarStark commented on src/Symfony/Component/Notifier/Bridge/Firebase/FirebaseTransportFactory.php
> + * @experimental in 5.0
5.1

2020-02-05 21:57 UTC, OskarStark commented on src/Symfony/Component/Notifier/Bridge/Firebase/Notification/AndroidNotification.php
> +final class AndroidNotification extends FirebaseOptions
Please add experimental

2020-02-05 21:57 UTC, OskarStark commented on src/Symfony/Component/Notifier/Bridge/Firebase/Notification/AndroidNotification.php
> +    public function androidChannelId(string $androidChannelId): self
channelId would be enough as method and variable name

2020-02-05 21:57 UTC, OskarStark commented on src/Symfony/Component/Notifier/Bridge/Firebase/Notification/IOSNotification.php
> +final class IOSNotification extends FirebaseOptions
Please add experimental

2020-02-05 21:57 UTC, OskarStark commented on src/Symfony/Component/Notifier/Bridge/Firebase/Notification/WebNotification.php
> +final class WebNotification extends FirebaseOptions
Please add experimental

2020-02-05 21:57 UTC, OskarStark commented on src/Symfony/Component/Notifier/Bridge/Firebase/composer.json
> +        "php": "^7.2.9",
7.2.5

2020-02-08 07:34 UTC, fabpot requested changes

2020-02-08 07:34 UTC, fabpot commented on src/Symfony/Component/Notifier/Bridge/Firebase/FirebaseTransportFactory.php
> +                ->setPort($port);
should be on one line.

2020-02-10 15:34 UTC, fabpot approved these changes

2020-02-10 15:35 UTC, fabpot commented
Thank you @Jeroeny.

2020-02-10 15:35 UTC, merged

2020-04-17 17:07 UTC, acasademont commented
After seeing fabpot's talk today talking about the Firebase notifier coming in 5.1 I looked at the repo and noticed that this Firebase notifier is based on the old Http API, that allows quite a lot less options than the new one, specifically, the new one allows you to send in 1 message different options for different platforms (iOS, Android, Web) instead of having to send separate messages for each of the platforms.

Not sure @Jeroeny if this is something that should be changed before the 5.1 release?

https://firebase.google.com/docs/cloud-messaging/migrate-v1

2020-04-18 06:47 UTC, fabpot commented
@acasademont I would recommend to open a new issue.