[ErrorRenderer] extend legacy exception for backwards compatibility
symfony/symfony pull request #33981
Opened 2019-10-14 13:13 UTC by xabbuh

| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | 
| License       | MIT
| Doc PR        |

2019-10-14 13:21 UTC, nicolas-grekas approved these changes
We tried hard not doing so but we have to face the truth, that's the only way :)

2019-10-14 13:35 UTC, yceruto requested changes
:+1: we should also update the `HttpKernel\...\ExceptionListener` class according to this approach.

2019-10-14 13:35 UTC, yceruto commented on src/Symfony/Component/ErrorRenderer/Exception/FlattenException.php
> +    public static function create(\Exception $exception, $statusCode = null, array $headers = []): self
`: LegacyFlattenException`?

2019-10-14 13:43 UTC, yceruto commented
Just asking: Did you find another BC break? Won't https://github.com/symfony/symfony/pull/33941 be enough to keep the BC?

2019-10-14 17:41 UTC, nicolas-grekas commented
> Just asking: Did you find another BC break? Won't #33941 be enough to keep the BC?

see 3.4 and 4.3 in https://travis-ci.org/symfony/symfony/builds

2019-10-15 08:00 UTC, xabbuh commented
Status: Needs Review

2019-10-15 13:26 UTC, nicolas-grekas commented
Thank you @xabbuh.

2019-10-15 13:26 UTC, merged