manage Symfony Maker errors when creating entity
symfony/symfony pull request #34091
Opened 2019-10-23 21:19 UTC by mary2501

| Q             | A
| ------------- | ---
| Branch?       | 4.4 for features / 3.4 or 4.3 for bug fixes 
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #... 
| License       | MIT
| Doc PR        | symfony/symfony-docs#...

2019-10-23 21:22 UTC, mary2501 commented
Link Issues: https://github.com/happybottoms/coverd/issues/15

2019-11-13 09:43 UTC, derrabus requested changes

2019-11-13 09:43 UTC, derrabus commented on src/Symfony/Component/Debug/DebugClassLoader.php
> +                } catch (\ErrorException $exception) {
Catching and discarding all kinds of `ErrorException` hides potential problems. We shouldn‘t do this.

2019-11-28 10:55 UTC, nicolas-grekas approved these changes

2019-11-28 10:55 UTC, nicolas-grekas commented
Thank you @mary2501.

2019-11-28 10:55 UTC, merged