[ErrorRenderer] Refactor and delegate serializing responsibility to the Serializer component
symfony/symfony pull request #34288
Opened 2019-11-08 00:19 UTC by yceruto

| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | TODO

By default, the ErrorRenderer component will host only the HTML+JS error page, delegating the serialization of other formats to the Serializer component (if installed). This will simplify the use and integration with other third-party packages like API-Platform and FOSRestBundle.

**Main changes:**
 * Added new `ProblemNormalizer` to the Serializer component ([RFC 7807](https://tools.ietf.org/html/rfc7807) compliant), 
 * Removed `<Format>ErrorRenderer` and registration mechanism in favor of Serializer's normalizers (see `UPGRADE-4.4.md` changes),
 * Removed `debug:error-renderer` command, it's no longer needed, as well as other classes.
 * The response structure was adjusted according to the one implemented in API-Platform https://github.com/api-platform/core/blob/master/src/Problem/Serializer/ErrorNormalizer.php

2019-11-08 00:34 UTC, yceruto commented on UPGRADE-4.4.md
> - * Deprecated the `Debug` class, use the one from the `ErrorRenderer` component instead
[duplicated] the whole component is deprecated (mentioned two lines bellow)

2019-11-08 00:34 UTC, yceruto commented on UPGRADE-5.0.md
> - * Removed the `Debug` class, use the one from the `ErrorRenderer` component instead
same here

2019-11-08 00:34 UTC, yceruto commented on src/Symfony/Component/ErrorRenderer/Exception/FlattenException.php
> -    private $title;
minor refactor for better name (it was introduced in 4.4)

2019-11-08 12:28 UTC, yceruto commented
Ready for review!

(Travis dep=high failures is normal)

2019-11-09 06:54 UTC, fabpot requested changes
Great work!

2019-11-09 06:54 UTC, fabpot commented on src/Symfony/Component/Serializer/Normalizer/ProblemNormalizer.php
> +            $exception = FlattenException::createFromThrowable($exception);
What if ErrorRenderer is not installed?

2019-11-10 10:55 UTC, chalasr commented on UPGRADE-4.4.md
> -  Configure your rendering service tagging it with `error_renderer.renderer`.
Should be removed from:
https://github.com/symfony/symfony/blob/d5ba53547e25036a3473fc33d918c485ff85018b/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/UnusedTagsPass.php#L35

2019-11-10 18:09 UTC, yceruto commented
closing in favor of https://github.com/symfony/symfony/pull/34312

2019-11-10 18:09 UTC, closed without merging