Cache Warmer node_modules bug fixed
symfony/symfony pull request #34321
Opened 2019-11-11 15:04 UTC by appaydin

| Q             | A
| ------------- | ---
| Branch?       | 4.3 bug fixes 
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? |no 
| Tickets       | -
| License       | MIT
| Doc PR        | -

I created a theme structure in the "templates" directory. A different webpack structure is used for each theme.

I get an error while clearing the Symfony cache "bin/console cache:clear". While the cache is warming up, twig is trying to read files in node_modules directory.

There is no problem with "bin/console cache:clear --no-warmup".

Error: 
```
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 815104 bytes) in /Users/apaydin/www/emlakpro/apps/vendor/twig/twig/src/Compiler.php on line 129
```

2019-11-16 15:21 UTC, nicolas-grekas approved these changes
The name is specific enough, I think we can do it.

2019-11-16 15:39 UTC, yceruto requested changes
I'm :-1: on this. I don't think this is the right approach (there are a lot of well known directories that could be applied here) and I'm pretty sure you can solve this problem by moving the folder out of `templates/` in the meantime.

The right approach in my opinion would be adding a new option to exclude directories (e.g. `bundles/` by default) and/or files, using some kind of glob/pattern.

See dicussion about this topic here https://github.com/symfony/symfony/issues/34142

2019-11-16 15:56 UTC, nicolas-grekas commented
> there are a lot of well known directories that could be applied here

I'm not sure about this - I mean: `node_modules` is very very well-known. I can't recall any other directory that well known. That makes it special to me.

> I'm pretty sure you can solve this problem by moving the folder out of templates/ in the meantime.

@appaydin please tell us why you didn't do this in the first place?

> The right approach in my opinion would be adding a new option to exclude directories (e.g. bundles/ by default) and/or files, using some kind of glob/pattern.

That's a lot of additional complexity for a rare case. Excluding just `node_modules` would save us from that complexity. That's a *significant* benefit.

#34142 is far from being solved at all: "non-template files" is undefined. I wouldn't consider this a viable alternative solution in the near term...

2019-11-16 16:36 UTC, yceruto commented
I agree, I would also consider this a rare case, that's why I'm against to add more directories arbitrarily to the hardcoded exclusion list and go ahead with workarounds.

I still don't think this use case (having the `node_modules/` inside the Twig's `templates/` directory) is enough legit and common to exclude it.

2019-11-16 17:22 UTC, yceruto commented
Although I don't feel comfortable telling people where they should put their directories/files due to a problem generated by the framework. That's why also I would want do something about it.

2019-11-16 17:37 UTC, appaydin commented
Keeping the front-end of the site in a single directory does not disturb the theme structure. There are different themes created with Vue, and you cannot move the node_modules directory to a different location.

In order to get node_modules into a different directory, we have to split the theme structure into two.

Alternative options are possible, but the directory structure becomes more complex.

[https://stackoverflow.com/questions/21818701/can-a-custom-directory-name-be-used-instead-of-node-modules-when-installing-no](url)

2019-11-16 22:28 UTC, yceruto commented
> > The right approach in my opinion would be adding a new option to exclude directories (e.g. bundles/ by default) and/or files, using some kind of glob/pattern.

> That's a lot of additional complexity for a rare case. Excluding just node_modules would save us from that complexity. That's a significant benefit.

Please, let's discuss it here https://github.com/symfony/symfony/pull/34416, I don't think there's much additional complexity to it.

2019-11-17 08:13 UTC, fabpot commented
:-1: for me

2019-11-17 09:11 UTC, nicolas-grekas commented
Closing then, thanks for proposing @appaydin

2019-11-17 09:11 UTC, closed without merging