[Messenger] Add HeaderStamp to add custom headers
symfony/symfony pull request #34481
Opened 2019-11-21 10:34 UTC by alanpoulain

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | N/A
| License       | MIT
| Doc PR        | TBD

Add a `HeaderStamp` to add custom headers to an encoded message to be used by the transport.

It's a proposal, maybe there is a better way to do this.

This feature would be useful in my case where I need to add a custom header to deduplicate the messages in an AMQP context. This is the RabbitMQ plugin I would like to use: https://github.com/noxdafox/rabbitmq-message-deduplication.

2019-11-27 09:35 UTC, javiereguiluz commented
@alanpoulain thanks for this contribution and for explaining it in the description of your PR. To allow us better evaluate this (and document it, if merged) could you please add a simple example of this feature in action? Thanks.

2019-12-24 14:56 UTC, alanpoulain commented
@javiereguiluz sorry for the delay! Rebased and example added in the description of this PR.

2020-01-10 10:07 UTC, alanpoulain commented
Any input about this PR?

2020-01-19 20:27 UTC, Nyholm reviewed
We should also deserialize the header stamp, right?
How do we handle message requeue? Should stamps be removed and re-added by a potential second transport?

I know I been speaking with @weaverryan about this. I was in favour of introducing a generic stamp, but Im not sure if Ryan chose to not do it because of a reason or just because there were not obvious use case for it at the time.

2020-01-19 23:50 UTC, alanpoulain commented
Is there an issue with the (de)serialization of this stamp? It seems to me there would be no issue.
For the requeue it seems to be the stamps are kept by default, doesn't it?

2020-01-20 06:07 UTC, Nyholm commented
Will the stamp be present when I get the message back from the queue? 
Oh silly me, I was expecting you to need to modify decodeStamp. 


————

If I put a message on transport A. It uses some headers Foo. Then I consume the message, it fails and goes to the failure transport B. Will it still have the same headers Foo? Should it have the same headers or should headers be cleared?

Could you please elaborate how it will work?

2020-01-20 14:05 UTC, alanpoulain commented
For the second question, currently since the stamp is kept (and serialized), the headers will be kept too.

If we use the `NonSendableStampInterface` for this stamp, then the headers will be cleared if the sending of the message fails (since the header will not be serialized).

I don't see why the headers should be cleared, but if there are some use cases maybe we could introduce another stamp (like a `ResettableHeaderStamp`).

Also I see I've not modified the `PhpSerializer`, I think it should be modified too, doesn't it?

2020-01-20 16:32 UTC, Tobion requested changes
I don't think this is necessary. Adding custom headers to AMQP is already possible by using the AmqpStamp `AmqpStamp::createWithAttributes(['headers' => [ ... ])`. For other transports, adding custom headers is possible by decorating the serializer and returning the custom headers there.
Your solution will duplicate the headers both as serialized data and as headers in the transport.

2020-01-20 16:44 UTC, alanpoulain commented
I didn't see the possibility of using the `AmqpStamp` for this :+1:

For the other transports, if the stamp implements `NonSendableStampInterface` it shouldn't be serialized, right?
But then it would disappear when being requeued, as @Nyholm pointed out.

Feel free to close this PR if this use case is not needed.

2020-01-22 16:14 UTC, mleczakm commented
@Tobion with current implementation of amqp sender overriding already existing header entries (like `type`, which is for no reason hardcoded to message FQCN) is impossible...

2020-01-26 11:36 UTC, Nyholm commented
I guess `AmqpStamp` is the reson we never needed a `GenericHeaderStamp`. 

@alanpoulain, Im happy to close this if `AmqpStamp` solves your problem.

2020-01-26 15:55 UTC, closed without merging