add Notifier Slack bridge tests
symfony/symfony pull request #34549
Opened 2019-11-23 14:04 UTC by Jeroeny

| Q             | A
| ------------- | ---
| Branch?       | 5.0
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | None yet
| License       | MIT

Adds tests for the Slack bridge of the Notifier component.

#SymfonyHackday

2019-11-23 18:55 UTC, OskarStark approved these changes

2019-11-23 18:55 UTC, OskarStark commented on src/Symfony/Component/Notifier/Bridge/Slack/Tests/SlackTransportFactoryTest.php
> +        $token = 'testUser';
One time variable not needed

2019-11-23 19:09 UTC, Jeroeny commented on src/Symfony/Component/Notifier/Bridge/Slack/Tests/SlackTransportFactoryTest.php
> +        $token = 'testUser';
Thanks, fixed and another one as well.

2019-11-30 13:00 UTC, fabpot requested changes
Looks good to me. I've made some minor comments about CS.

2019-11-30 18:13 UTC, fabpot approved these changes

2019-11-30 18:14 UTC, fabpot commented
Thank you @Jeroeny.

2019-11-30 18:14 UTC, merged