add tests for php executable finder if file does not exist
symfony/symfony pull request #34608
Opened 2019-11-25 18:07 UTC by ahmedash95

| Q             | A
| ------------- | ---
| Branch?       | master?
| Bug fix?      | no
| New feature?  | no 
| Deprecations? | no 
| Tickets       | 
| License       | MIT
| Doc PR        | 

regarding Process component, I just noticed there is no tests covers the case when the PHP binary is not valid so I added the test to make sure it works as expected also it increases the coverage of the process component

2019-11-25 21:32 UTC, darielopper approved these changes

2019-11-26 03:52 UTC, fabpot requested changes

2019-11-26 03:52 UTC, fabpot commented on src/Symfony/Component/Process/Tests/PhpExecutableFinderTest.php
> +     */
The phpdoc should be rmoved

2019-11-26 08:30 UTC, ahmedash95 commented on src/Symfony/Component/Process/Tests/PhpExecutableFinderTest.php
> +     */
Done 👍

2019-11-26 09:32 UTC, nicolas-grekas approved these changes
(for 3.4)

2019-11-27 22:47 UTC, nicolas-grekas commented
Thank you @ahmedash95.

2019-11-27 22:47 UTC, merged