[Notifier] added "callback" support for texter transports
symfony/symfony pull request #34629
Opened 2019-11-26 12:59 UTC by imiroslavov

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | n/a 
| License       | MIT
| Doc PR        | n/a

Adding support for Twilio/Nexmo webhook endpoints used to monitor status changes.

- [ ] fix the tests (if there are any)

2019-11-27 08:09 UTC, javiereguiluz commented
@imiroslavov just asking in case this is merged and we need to document it: must the `callback` value be escaped somehow before including it to the DSN?

For example, in some parts of the docs we say this for the `DATABASE_URL` DSN:

> If the username, password, host or database name contain any character 
> considered special in a URI (such as ``+``, ``@``, ``$``, ``#``, ``/``,
> ``:``, ``*``, ``!``), you must encode them.

Thanks.

2019-11-27 08:41 UTC, imiroslavov commented
@javiereguiluz The query parameters of the DSN are passed to `parse_str` so yes. The callback URL can/must be entirely escaped.

2019-11-27 12:04 UTC, imiroslavov commented
If #34654 is merged before this PR it will require additional work.

2020-05-03 16:20 UTC, Nyholm requested changes
Thank you. 

I like this PR. Could you rebase it and add this feature to Sinch too?

And a small tests would be perfect =)

2020-06-29 17:41 UTC, imiroslavov commented
@Nyholm Sorry for the late reply. The idea initially sounded good but right now I see only downsides. 
1) Hard-coding the URL is a bad practice. 
2) In most of the cases you will want to track the result of the callback in a previously created database record (preliminary record). The most adequate way is to generate a callback URL that contains the ID of that record which is not possible in this PR. (e.g create preliminary SMS record with status "pending". Then update it to "sent", "delivered" etc. depending on the callback data)
3) After this PR was submitted an adapter for "ovhcloud" was added which doesn't support different callbacks per request. 

I'm stuck at this point. Maybe a _callback envelope_ will be a better solution.

I will have enough free time to work on this next week so I'm open for suggestions.

2020-08-13 11:18 UTC, fabpot commented
I would add that the payload of the callback wouldn't be the same depending on the provider. I propose to close for now until we have a better idea.

2020-08-13 11:18 UTC, closed without merging

2020-08-13 16:42 UTC, imiroslavov commented
@fabpot The provider can also be added to the callback URL but that would lead to compromises and probably more problems in the user's code, so closing the PR is the best option.