[Console] Fix filtering out identical alternatives when there is a command loader
symfony/symfony pull request #35094
Opened 2019-12-23 20:39 UTC by fancyweb

| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | https://github.com/symfony/symfony/issues/35089
| License       | MIT
| Doc PR        | -

CommandLoader commands needs to be loaded to resolve thier names and filter them.

2019-12-24 04:34 UTC, chalasr requested changes

2019-12-24 04:34 UTC, chalasr commented on src/Symfony/Component/Console/Application.php
> +            $commandList = $this->commandLoader ? array_merge(array_combine($names = $this->commandLoader->getNames(), array_map(function ($name) { return $this->commandLoader->get($name); }, $names)
We don't need to load all commands here, only matches. Can be done inside the `array_filter` callback below:
```diff
- $commandName = $commandList[$nameOrAlias] instanceof Command ? $commandList[$nameOrAlias]->getName() : $nameOrAlias;
+ if (!$commandList[$nameOrAlias] instanceof Command) {
+     $commandList[$nameOrAlias] = $this->commandLoader->get($nameOrAlias);
+ }
+ $commandName = $commandList[$nameOrAlias]->getName();
```

2019-12-24 16:19 UTC, chalasr approved these changes
👍

2019-12-24 20:01 UTC, chalasr commented
Good catch, thanks @fancyweb.

2019-12-24 20:02 UTC, merged

2020-01-24 14:59 UTC, lutzpetzoldt commented
After updating from 4.3.9 to 4.3.10 this change leads to loading of lazy commands even if they are not called. This occurs with commands where the first part of the name matches. For example if you have two lazy commands `app:foo` and `app:foo:bar`, and call `app:foo`, then `app:foo:bar` will also be instantiated, although it is not called. This should not happen according to the documentation ([link](https://symfony.com/doc/4.3/console/commands_as_services.html#console-command-service-lazy-loading)). I think the problem is line 668 in Application.php. Can you please confirm this behavior? Should I create a new issue?

2020-01-24 15:13 UTC, fancyweb commented
Hello, please create a new issue with a reproducer so someone can check it and start working on a fix if there was a regression. Thanks 😃