[FrameworkBundle] TemplateController should accept extra arguments to be sent to the template
symfony/symfony pull request #35257
Opened 2020-01-08 11:02 UTC by Rebolon

| Q             | A
| ------------- | ---
| Branch?       | master for features / 4.4
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no 
| Tickets       | Fix #... 
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

In the official documentation (symfony.com/doc/master/templates.html#rendering-a-template-directly-from-a-route) it says that TemplateController should accept extra arguments. In fact it's not available for instance.
So i added the context argument as an array. Because of deprecation of templating, only the twig instance will apply the context argument.

It will need to be implemented in branch 5.

The following issue has been created in documentation project : https://github.com/symfony/symfony-docs/issues/12897

2020-01-08 14:14 UTC, yceruto requested changes
Hi @Rebolon, thanks for taking care of this. I left some comments to make your "first contribution" happy :)
 1. The target branch must be `master` for new features (future 5.1), `4.4` is already released and must be used for bugfix only. Please, rebase it to `master`.
 2. A functional test case is required for new features like this one.

Don't hesite to ask any question, thanks again.

2020-01-08 14:14 UTC, yceruto commented on src/Symfony/Bundle/FrameworkBundle/CHANGELOG.md
> + * Added php ini session options `sid_length` and `sid_bits_per_character`
please revert these changes, them should be done in lower branch.

2020-01-08 14:14 UTC, yceruto commented on src/Symfony/Bundle/FrameworkBundle/CHANGELOG.md
> + * The `TemplateController` now accepts context argument like described in the official documentation
I think the last part if the sentence is not necessary (rm `like described in the official documentation`)

2020-01-08 14:56 UTC, Rebolon commented
@yceruto thx for help.
Not sure to get time for the Functional Test. I understand the goal, but not sure how to achieve it throught this project in short time (i'm looking for it).

2020-01-08 15:03 UTC, yceruto commented
> Not sure to get time for the Functional Test. I understand the goal, but not sure how to achieve it throught this project in short time (i'm looking for it).

Don't worry about it, I can add it at the end, just let me know when the other comments have been fixed. Thanks!

2020-01-08 17:06 UTC, Rebolon commented
@yceruto it should be ok right now
I added an Integration Test as i needed Twig. If you consider you need a Functional Test, it's up to you, or just give me tips on the wished usage (WebTestCase or Panther, anything else)

2020-01-08 17:16 UTC, yceruto commented
Wow! you were fast :zap: :) 

An unit test is enough for me, but can you confirm that this is the new route config for this feature?
```yaml
# config/routes.yaml
acme_privacy:
    path:          /privacy
    controller:    Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template:  'static/privacy.html.twig'
        maxAge:    86400
        sharedAge: 86400

        # optionally you can define some arguments passed to the template
        context:
            site_name: 'ACME'
            theme: 'dark'
```

2020-01-08 17:19 UTC, yceruto approved these changes
Look good to me after minor comment, thanks!

2020-01-08 17:19 UTC, yceruto commented on src/Symfony/Bundle/FrameworkBundle/Tests/Controller/TemplateControllerTest.php
> +        $loader->setTemplate($templateName, '<h1>{% block title %}{{param}}{% endblock %}</h1>');
for short `'<h1>{{ param }}</h1>'` ? the block tag is not really needed in this test case.

2020-01-08 17:22 UTC, yceruto commented on src/Symfony/Bundle/FrameworkBundle/Tests/Controller/TemplateControllerTest.php
> +
useless ?

2020-01-09 08:01 UTC, Rebolon commented
@yceruto That's it for the yaml config. 
I pushed the last changes following your review.

2020-01-09 20:41 UTC, chalasr approved these changes
with minor comment

2020-01-09 20:41 UTC, chalasr commented on src/Symfony/Bundle/FrameworkBundle/Controller/TemplateController.php
> +     * @param array|null $context   The context (arguments) of the template
should be `array` only

2020-01-10 09:22 UTC, nicolas-grekas approved these changes

2020-01-10 09:23 UTC, nicolas-grekas commented
(please fix fabbot's report)

2020-01-10 12:07 UTC, fabpot approved these changes

2020-01-10 12:08 UTC, fabpot commented
Thank you @Rebolon.

2020-01-10 12:09 UTC, merged