fix empty prio
symfony/symfony pull request #35260
Opened 2020-01-08 12:47 UTC by hjanuschka

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #35259
| License       | MIT

returns `0`  instead of `null`  as it is typ hinted on other places anyway, and leads to exceptions sometimes.

2020-01-08 14:05 UTC, ro0NL commented
https://github.com/symfony/symfony/blob/20bf17f6ad38011f90cfe9b2dc7c30c8901163e5/src/Symfony/Component/EventDispatcher/EventDispatcherInterface.php#L65-L67

should we update the contract then? Or just the wrongful calling sides?

2020-01-08 14:12 UTC, hjanuschka commented
@ro0NL thx, good point, pushed changes

2020-01-08 16:47 UTC, nicolas-grekas commented
This looks suspicious to me. It looks like a BC break.

2020-01-09 12:38 UTC, xabbuh requested changes

2020-01-09 12:38 UTC, xabbuh commented on src/Symfony/Component/EventDispatcher/EventDispatcher.php
> +            return 0;
This looks wrong to me. The interface states this:

> Returns null if the event or the listener does not exist.

Making this change here violates the contract defined by the interface.

2020-01-09 12:38 UTC, xabbuh commented on src/Symfony/Component/EventDispatcher/EventDispatcher.php
> +        return 0;
same above

2020-01-09 12:38 UTC, xabbuh commented on src/Symfony/Component/EventDispatcher/EventDispatcherInterface.php
> +     * @return int The event listener priority, defaults to 0
changing this is a BC break

2020-01-09 13:59 UTC, closed without merging