Simplify UriSigner when working with HttpFoundation's Request
symfony/symfony pull request #35284
Opened 2020-01-09 16:28 UTC by Toflar

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | 
| License       | MIT
| Doc PR        | 

I'm using the `UriSigner` in my own projects from time to time and I've always wondered why I have to manually generate the URI from the `Request` instance in such a way that it is correctly validated.
Let's add a new `checkRequest(Request $request)` method to provide better DX.

2020-01-09 16:45 UTC, Toflar commented
Failing tests look unrelated.

2020-01-10 09:21 UTC, fabpot requested changes
with two minor comments

2020-01-10 09:21 UTC, fabpot commented on src/Symfony/Component/HttpKernel/UriSigner.php
> +    public function sign(string $uri): string
Should be reverted

2020-01-10 09:21 UTC, fabpot commented on src/Symfony/Component/HttpKernel/UriSigner.php
> +    public function check(string $uri): bool
Should be reverted

2020-01-10 09:24 UTC, Toflar commented
Done. Thought they were missing accidentally during the upgrade to 5.0.

2020-01-10 09:25 UTC, fabpot approved these changes

2020-01-10 09:29 UTC, fabpot commented
Thank you @Toflar.

2020-01-10 09:29 UTC, merged