Check if the event is from the contract in legacy dispatcher
symfony/symfony pull request #35325
Opened 2020-01-13 16:16 UTC by Taluu

| Q             | A
| ------------- | ---
| Branch?       | 4.3
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | ~
| License       | MIT
| Doc PR        | ~

This adds in the condition of the traceable event dispatcher, when called in the legacy way (`$dispatcher->dispatch(string, EventContract)`) that it doesn't fail the check if an `Event` from the contract in passed instead of the one from the component.

I wondered if it was not done because the "legacy call" should or should not support the contract ?

2020-01-13 16:43 UTC, Taluu commented
Added tests, but I'm not too sure how to handle exceptions (if it's the new or old way of phpunit ?), so did the best I could with a try catch as I didn't have exemples.

I guess I can use `expectException` ?

2020-01-14 06:23 UTC, xabbuh requested changes

2020-01-14 06:23 UTC, xabbuh commented on src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php
> +            if (!$event instanceof Event && !$event instanceof ContractsEvent) {
This looks wing to me. The legacy signature did not support passing objects as events that do not extend the `Event` class from the component.

2020-01-14 10:47 UTC, derrabus requested changes
I agree with @xabbuh here. That particular piece of code emulates the pre-4.2 behavior of the class. And the old signature only allowed instances of the old `Event` class to be passed. Allowing other classes does not look right to me. Can you elaborate on what problem you're trying to solve with your change?

2020-01-14 10:55 UTC, Taluu commented
We recently migrated from 3.4 to 4.4 (yeay !), but our dispatcher calls remained as legacy (without using the legacy decorator).

We just made a change to use the contracts rather than the event class from the component, and saw that this dispatcher didn't support the contract on the legacy calls...

I do agree that this fix may not be needed, as you should first reverse the order of args and then only use the contract, which is fine by me (we're currently working on that).

Feel free to close. :)

2020-01-14 16:21 UTC, nicolas-grekas commented
Closing then, we don't want to support this upgrade path.

2020-01-14 16:21 UTC, closed without merging

2020-01-14 16:21 UTC, nicolas-grekas commented
Thanks for proposing!