[RFC][DX][OptionsResolver] Allow setting info message per option
symfony/symfony pull request #35400
Opened 2020-01-20 14:02 UTC by yceruto

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | TODO

This is a DX proposal that will help in debugging/errors to better understand the meaning of one defined option.

This is how you'd use it:
```php
$resolver = new OptionsResolver();
$resolver->setDefined('date');
$resolver->setAllowedTypes('date', \DateTime::class);
$resolver->setInfo('date', 'A future date'); // <-- NEW
// ...
```
This information may be useful mainly for those options where their name cannot be intuitive enough, or their purpose is too complex. Here is an example (based on the example above):
```php
// ...
$resolver->setAllowedValues('date', static function ($value): bool {
    return $value >= new \DateTime('now');
});
```
So, if you introduce a date value that does not match the criteria, you will get this error message:

**Before:**
```
The option "date" with value DateTime is invalid.
```
Note that the allowed value is not printable in this case, hence the error message cannot be clear at all.

**After:**
```
The option "date" with value DateTime is invalid. Info: A future date.
```
Although a more accurate error message can be triggered within the "\Closure" if desired.

Also you'll see this info message on `debug:form` command (see tests), then you have in advance the informative description of any option.

What do you think?

2020-01-20 14:09 UTC, javiereguiluz commented
Here's a wild proposal 🙈  to solve this same problem but using the Symfony Validator component:

```php
// Before:
$resolver = new OptionsResolver();
$resolver->setInfo('date', 'A future date');



// After:
use Symfony\Component\Validator\Constraints\GreaterThan;

$resolver = new OptionsResolver();
$resolver->setValidator('date', new GreaterThan([
    'value' => new DateTime('today'),
    'message' => 'This option must be a date in the future.'
]));
```

2020-01-20 14:36 UTC, yceruto commented
Hi @javiereguiluz, thanks for your input :) your proposal would require the integration of the Validator component, isn't it? 

Note that my proposal isn't only about improving the validation error message, but also about debugging information on `debug:form` cmd. It's just like the `setInfo` method in the `BaseNode` of the Config component.

2020-01-20 14:42 UTC, javiereguiluz commented
Thanks for your comments ... I was thinking about an optional dependency with the Validator component (the usual *"You can't use XXXX because YYYY. Try running composer require ..."* message we use in other parts of Symfony). But yes, my comment is completely different from your original proposal. We can ignore it! Thanks.

2020-02-09 07:53 UTC, fabpot requested changes

2020-02-09 07:53 UTC, fabpot commented on src/Symfony/Component/OptionsResolver/OptionConfigurator.php
> +     * @param string $info The info message
Can be removed

2020-02-09 07:53 UTC, fabpot commented on src/Symfony/Component/OptionsResolver/OptionsResolver.php
> +    public function setInfo(string $option, string $info)
missing `: self`

2020-02-09 07:53 UTC, fabpot commented on src/Symfony/Component/OptionsResolver/OptionsResolver.php
> +     * @param string $info   The info message
@param annotations can be removed.

2020-02-09 07:53 UTC, fabpot commented on src/Symfony/Component/OptionsResolver/OptionsResolver.php
> +     * @param string $option The option name
Can be removed

2020-02-09 07:53 UTC, fabpot commented on src/Symfony/Component/OptionsResolver/OptionsResolver.php
> +     * @return string|null The info message of the given option
Can be removed

2020-02-10 00:43 UTC, yceruto commented
Comments addressed, thanks!

2020-02-10 08:05 UTC, fabpot approved these changes

2020-02-10 08:05 UTC, fabpot commented
Thank you @yceruto.

2020-02-10 08:05 UTC, merged