[Messenger][AMQP] Set the delayed queue as lazy
symfony/symfony pull request #35619
Opened 2020-02-06 13:13 UTC by lyrixx

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       |
| License       | MIT
| Doc PR        |

> Since RabbitMQ 3.6.0, the broker has the concept of Lazy Queues - queues that move their contents to disk as early as practically possible, and only load them in RAM when requested by consumers, therefore the lazy denomination.
>
> One of the main goals of lazy queues is to be able to support very long queues (many millions of messages). Queues can become very long for various reasons:
>
> * consumers are offline / have crashed / are down for maintenance
> * there is a sudden message ingress spike, producers are outpacing consumers
> * consumers are slower than normal
>
> By default, queues keep an in-memory cache of messages that is filled up as messages are published into RabbitMQ. The idea of this cache is to be able to deliver messages to consumers as fast as possible. Note that persistent messages can be written to disk as they enter the broker and kept in RAM at the same time.

From: https://www.rabbitmq.com/lazy-queues.html

It's typically the case of lazy queue

---

**WARNING**: This is a BC Break.

An exception similar to the following will happen if the delayed queue
already exist:

```
AMQPQueueException {#664
  #message: "Server channel error: 406, message: PRECONDITION_FAILED - inequivalent arg 'x-queue-mode' for queue 'test.load' in vhost 'joli_redirection': received 'lazy' but current is 'default'"
```

I don't know how to fix that:

1. We could try to create the queue as lazy and if it does not work, as normal.
2. We could add an option in the config, and it's up to the user to do what it should be done

Note: It's possible to change the type at runtime

2020-02-06 21:35 UTC, Tobion requested changes
The PRECONDITION_FAILED error can be solved by either changing the naming structure of delay queues or with a feature flag. Also there is a possiblity to ask rabbitmq if the queue with the arguments already exists which you could use to skip the failing declaration.

2020-02-07 14:17 UTC, lyrixx commented
@Tobion I like naming structure move. (simple, easy)

What's you favorite one?

2020-03-05 14:55 UTC, Tobion commented
Changing the default naming structure is potential bc break since the component is not experimental anymore. So the only safe solution would be a feature flag. But then I don' think the lazy queue should be set on delay queues in general. It's way to use-case dependent like the amount of messages published and the amount of delay configured.
So this could be better solved as user-level using a rabbitmq policy which works better for such cases.

2020-03-05 17:18 UTC, lyrixx commented
There is no BC break here since the queue is not consumed directly.
All message in the old queues will be re published in the original queue, isn't ?
More over all delay queues has an expires: they are are deleted when empty after [10 seconds](https://github.com/symfony/symfony/blob/b470af1d1b91ff700468e99ffdb5a934abcb099a/src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php#L372-L374). It means we will not messed up everything.

> But then I don' think the lazy queue should be set on delay queues in general. It's way to use-case dependent like the amount of messages published and the amount of delay configured.

I totally disagree. delay queues should not store message in RAM. And since messages are published with delivery mode = 2, there are on disk anyway. It's much better to save the RAM, and more over to avoid triggering the GC of Erlang VM.

2020-03-05 17:51 UTC, Tobion commented
We track the amount of messages in the queues which wouldn't work anymore if the queues have different names. So renaming a queue does not break the things directly but people can still rely on the naming in some way.

2020-03-05 17:56 UTC, lyrixx commented
Good catch :+1: I did not thought about that.

I'm gonna close this PR since I don't use messenger (yet?). So I don't need this feature.
I wanted to share my expertise on RabbitMQ... But it's not a big deal

2020-03-05 17:56 UTC, closed without merging

2020-03-05 18:05 UTC, Tobion commented
Thanks for the suggestion. As I said, people can do that very easily with policies.