Di fix check type declaration pass
symfony/symfony pull request #36108
Opened 2020-03-17 10:28 UTC by guillbdx

| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #35863 and #35972
| License       | MIT
| Doc PR        | 

Bug 1: The lint container threw an error if a class buit with a factory was declared as callable while this factory method returne a callabe (#35863)

Bug 2: Sodium Exception was not caught in the CheckTypeDeclarationsPass. We have extended the exception caught to \Exception, instead of EnvNotFoundException and RuntimeException only.

2020-03-17 11:03 UTC, nicolas-grekas reviewed
Thanks.
The 'iterable' case looks similar, we should add `'iterable' === $class` there also

2020-03-17 11:03 UTC, nicolas-grekas commented on src/Symfony/Component/DependencyInjection/Compiler/CheckTypeDeclarationsPass.php
> +        if ('callable' === $type && (\Closure::class === $class || method_exists($class, '__invoke') || 'callable' === $class)) {
let's move it first

2020-03-17 11:18 UTC, stloyd commented on src/Symfony/Component/DependencyInjection/Compiler/CheckTypeDeclarationsPass.php
> +        if ('callable' === $type && (\Closure::class === $class || method_exists($class, '__invoke') || 'callable' === $class)) {
```suggestion
        if (\in_array($type, ['callable', 'callable'], true) && (\Closure::class === $class || method_exists($class, '__invoke'))) {
```

2020-03-17 11:21 UTC, stloyd requested changes

2020-03-17 11:21 UTC, stloyd commented on src/Symfony/Component/DependencyInjection/Compiler/CheckTypeDeclarationsPass.php
> +        if ('callable' === $type && (\Closure::class === $class || method_exists($class, '__invoke') || 'callable' === $class)) {
```suggestion
        if (\in_array($class, ['callable', 'callback', 'iterable'], true) {
            return;
        }

        if ('callable' === $type && (\Closure::class === $class || method_exists($class, '__invoke'))) {
```

2020-03-17 13:22 UTC, guillbdx commented on src/Symfony/Component/DependencyInjection/Compiler/CheckTypeDeclarationsPass.php
> +        if ('callable' === $type && (\Closure::class === $class || method_exists($class, '__invoke') || 'callable' === $class)) {
Done.

2020-03-17 13:22 UTC, nicolas-grekas commented on src/Symfony/Component/DependencyInjection/Compiler/CheckTypeDeclarationsPass.php
> +        if ('callable' === $type && (\Closure::class === $class || method_exists($class, '__invoke') || 'callable' === $class)) {
not the same...

2020-03-17 14:36 UTC, nicolas-grekas commented on src/Symfony/Component/DependencyInjection/Compiler/CheckTypeDeclarationsPass.php
> +        if ('array' === $type && ('array' === $class)) {
let's have a generic case the: `if ($type === $class)`

2020-03-17 14:36 UTC, nicolas-grekas commented on src/Symfony/Component/DependencyInjection/Compiler/CheckTypeDeclarationsPass.php
> +        if ('iterable' === $type && (\is_array($value) || 'iterable' === $class || is_subclass_of($class, \Traversable::class))) {
the new check would be covered by the suggestion I made in the other comment + this should be replaced by `'array' === $class`, which is missing right now.

2020-03-17 15:03 UTC, guillbdx commented
> Thanks.
> The 'iterable' case looks similar, we should add `'iterable' === $class` there also

Done, with a few minor additions.

2020-03-17 16:05 UTC, nicolas-grekas approved these changes

2020-03-17 17:42 UTC, stloyd approved these changes

2020-03-18 07:18 UTC, fabpot approved these changes

2020-03-18 07:19 UTC, fabpot commented
Thank you @guillbdx.

2020-03-18 07:19 UTC, merged

2020-06-13 10:57 UTC, Antek013 commented
I had the same problem with 4.4. 
I created a local repository with secrets then i push on the server and when i done a cache:clear i get the same error. 

!!    keypair size should be SODIUM_CRYPTO_BOX_KEYPAIRBYTES bytes