[Validator] Add invalid datetime message in Range validator
symfony/symfony pull request #36326
Opened 2020-04-02 20:28 UTC by przemyslaw-bogusz

| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | -

When the validated value is invalid (it isn't a number nor a datetime), but `min` or `max` option indicate that the `Range` constraint is being used to validate a datetime, the displayed message will be `This value should be a valid datetime` instead of `This value should be a valid number`. This PR replaces #35998.

2020-04-08 19:28 UTC, HeahDude commented on src/Symfony/Component/Validator/Constraints/RangeValidator.php
> +                    ->setCode(Range::INVALID_CHARACTERS_ERROR)
The error is the same independently from the value, so the code should be the same.

2020-05-16 08:42 UTC, nicolas-grekas commented
> min or max option indicate that the Range

since this is using some heuristic logic, I would suggest to report this is min AND max are can be parsed as dates.

2020-08-12 07:32 UTC, fabpot commented
@przemyslaw-bogusz Any comments about @nicolas-grekas suggestion?

2020-08-16 21:19 UTC, przemyslaw-bogusz commented
@nicolas-grekas I've modified the PR. As I understand, if one of the boundries is null and the other one is parsable DateTime string, this should also return `invalidDateTimeMessage` instead of `invalidMessage`?

2020-09-05 17:11 UTC, fabpot requested changes
This should be rebased on master as this is a new feature.

2020-09-19 07:17 UTC, fabpot commented
@przemyslaw-bogusz I think you're right for your latest question. Still willing to finish this PR for master?

2020-09-24 14:47 UTC, fabpot approved these changes

2020-09-24 14:49 UTC, fabpot commented
Thank you @przemyslaw-bogusz.

2020-09-24 14:49 UTC, merged