[Form] Added `choice_entry`, `checkbox_entry` and `radio_entry` to `ChoiceType` entries
symfony/symfony pull request #36489
Opened 2020-04-18 13:32 UTC by HeahDude

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | ~
| License       | MIT
| Doc PR        | TODO

I had the idea when I started working on #36088, but #36484 lit the fire (ping @ThomasLandauer :)).

2020-04-18 14:12 UTC, ThomasLandauer commented
Does this mean that you can set an option `radio_entry` like at 
https://symfony.com/doc/current/form/form_themes.html#custom-fragment-naming-for-individual-fields
to control the rendering of each individual radio button via a block in a custom form theme?

2020-04-18 14:13 UTC, HeahDude commented
Yes for all choice entries or for specific type of choice entries. A sibling of #36088.

2020-04-18 14:18 UTC, ThomasLandauer commented
Great!! But it will apply to *all* radios belonging to that field?! So https://github.com/symfony/symfony/issues/36484 is still the way to go to manipulate *individual* radios?

2020-04-18 14:23 UTC, HeahDude commented
Ok I've updaded the description to explain what this PR enables exactly.

2020-04-25 08:07 UTC, xabbuh requested changes

2020-04-25 08:07 UTC, xabbuh commented on src/Symfony/Component/Form/Tests/Extension/Core/Type/ChoiceTypeTest.php
> +            'checkbox',
Why do we expect the `checkbox` prefix here?

2020-04-25 08:07 UTC, xabbuh commented on src/Symfony/Component/Form/Util/FormUtil.php
> +    public static function appendStaticBlockPrefix(FormView $view, string $prefix, bool $decreaseOffset): void
I would not add this method. To me it decreases readability a lot to not just see in place how `array_splice()` is used.

2020-08-18 11:46 UTC, fabpot commented
@HeahDude What's the status here? Can you take comments into account?

2020-09-07 05:23 UTC, fabpot commented
Closing for now as the PR is stale. Feel free to reopen when you have time. Thank you.

2020-09-07 05:23 UTC, closed without merging