Improve SQS interoperability
symfony/symfony pull request #36525
Opened 2020-04-22 12:29 UTC by jderusse

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | NA
| License       | MIT
| Doc PR        | NA

The Symfony Messenger component provides a SerializerInterface to encode/decode the `Envelope`, this can be used to improve the Interoperability (see [article from jolicode](https://jolicode.com/blog/symfony-messenger-et-linteroperabilite) (french))

Sadly, the current implementation of SQS adapter json_encode the elements of the `Envelope` (`string body` + `string[] headers`) and store everything in the SQS message `Body`. That partially defect the interoperability: 3rd party have to also wrap (unwrap) message form json_encoded Body. 

This PR leverage the AWS SQS `Body` and `MessageAttribute` properties to store message information:

```yaml
# before
SQS Message:
  Body: {"body": "hello world", "headers": {"foo": "bar"}}
  MessageAttributes: {}

# after
SQS Message:
  Body: hello world
  MessageAttributes:
    foor: bar
```

2020-04-22 12:41 UTC, chalasr approved these changes
👍

2020-04-22 12:46 UTC, chalasr requested changes
Tests are broken :)

2020-04-22 12:47 UTC, fabpot approved these changes

2020-04-22 13:08 UTC, jderusse commented
tests are broken because the FakeSqs service does not support MessageAttributes.... https://github.com/iain/fake_sqs/pull/59

I'm looking for an alternative testing image

2020-04-22 15:45 UTC, chalasr approved these changes
Remaining failures are unrelated

2020-04-23 09:06 UTC, chalasr commented
Thank you @jderusse.

2020-04-23 09:06 UTC, merged

2020-06-01 07:17 UTC, Swahjak commented
@jderusse @chalasr is it possible this introduced the following issue:

```
Error: "HTTP 400 returned for "https://sqs.eu-west-1.amazonaws.com/".\n\nCode:    InvalidParameterValue\nMessage: Message (user) attribute name contains invalid non-alphanumeric character '#x5C'. You can use only alphanumeric characters, hyphens (-), underscores (_), or periods (.).\nType:    Sender\nDetail:  \n
```

When trying to send a message that is serialized (using the Symfony serializer) to:
```
array:2 [
  "body" => "{"id":9948}"
  "headers" => array:3 [
    "type" => "Topper\Bundle\Magento2Bundle\Messenger\Message\ProductUpdatedMessage"
    "X-Message-Stamp-Symfony\Component\Messenger\Stamp\BusNameStamp" => "[{"busName":"event.bus"}]"
    "Content-Type" => "application/json"
  ]
```

Trying to get a proper description going before opening an issue.