Add CustomUserMessageAccountStatusException
symfony/symfony pull request #36656
Opened 2020-05-01 15:42 UTC by VincentLanglet

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| License       | MIT
| Doc PR        | Not really needed

When implementing the `UserCheckerInterface`, we can throw `AccountStatusException`. Similar to `CustomUserMessageAuthenticationException`, this exception allow to throw an `AccountStatusException` with a custom message.

2020-05-04 07:28 UTC, dbrumann commented
Code looks good to me, but I am wondering what this is needed for and if this is the correct way of doing it?

There are a few exceptions that already extend the AccountStatusException, e.g. LockedException, AccountExpiredException or DisabledException. These would not benefit from your change. Is that intended?

That brings me to my other question, these Exceptions already communicate what the status problem was and a custom message could be provided, e.g. via translations. Do you have a use case for when you need a fully customizable message? Maybe that would help me understand better what this is needed for.

2020-05-04 07:53 UTC, VincentLanglet commented
> Code looks good to me, but I am wondering what this is needed for and if this is the correct way of doing it?
>
> There are a few exceptions that already extend the AccountStatusException, e.g. LockedException, AccountExpiredException or DisabledException. These would not benefit from your change. Is that intended?
>
> That brings me to my other question, these Exceptions already communicate what the status problem was and a custom message could be provided, e.g. via translations. Do you have a use case for when you need a fully customizable message? Maybe that would help me understand better what this is needed for.

Yes, it's intended.

In the same way, there are multiple `AuthenticationException`, like `BadCredentialsException`, `AuthenticationCredentialsNotFoundException`, `UsernameNotFoundException`, etc... BUT symfony provide a `CustomUserMessageAuthenticationException` if a custom message is needed. This avoid every developper to create a new custom `Exception`.

For `UserChecker`, there are indeed `LockedException`, `AccountExpiredException`, `DisabledException`, etc... but you can't customize the message. Symfony won't be able to cover every possible case, so providing a `CustomUserMessage` sounds like a nice idea to me.

You can indeed override the error message `Account is locked.` of, let's say, a `LockedException` but the exception are no taking `messageData`. So If my user is temporary locked until some date, I can't pass this date to the `LockedException` and display it in the error message.

Plus, If you override an error message like `Account is disabled.`, I am maybe wrong but you'll can only have one override. If you have multiple reason to disabled the account, you may want different exception and error message.

2020-05-04 11:08 UTC, dbrumann commented
Thanks for the clarification.

2020-05-04 15:33 UTC, wouterj approved these changes
I think this makes sense, given `AccountStatusException`s are handled differently by the Security system (see e.g. [authentication provider manager](https://github.com/symfony/symfony/blob/4dd6e2f0b2daefc2bddd08aa056370afb1c1cb1d/src/Symfony/Component/Security/Core/Authentication/AuthenticationProviderManager.php#L86-L92) and [exception listener](https://github.com/symfony/symfony/blob/4dd6e2f0b2daefc2bddd08aa056370afb1c1cb1d/src/Symfony/Component/Security/Http/Firewall/ExceptionListener.php#L205-L212))

2020-05-04 16:00 UTC, dbrumann approved these changes

2020-05-05 05:33 UTC, fabpot requested changes

2020-05-05 05:33 UTC, fabpot commented on src/Symfony/Component/Security/Core/Exception/CustomUserMessageAccountStatusException.php
> +     * Set a message that will be shown to the user.
Sets

2020-05-05 05:40 UTC, fabpot approved these changes

2020-05-05 05:40 UTC, fabpot commented
Thank you @VincentLanglet.

2020-05-05 05:41 UTC, merged