[Security] Verifying if the password field is null
symfony/symfony pull request #36925
Opened 2020-05-23 14:48 UTC by Shine-neko

| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #... 
| License       | MIT

2020-05-24 18:26 UTC, xabbuh commented
Shouldn't we rather check how the credentials could end up being `null` at all instead?

2020-05-24 21:49 UTC, wouterj commented
I think I agree with @xabbuh here. I think this should be fixed in `UsernamePasswordFormAuthenticationListener` and a `LogicException` should be thrown instead - this is not a user error (like blank password), but a developer error.

2020-05-25 00:38 UTC, Shine-neko commented
> I think I agree with @xabbuh here. I think this should be fixed in `UsernamePasswordFormAuthenticationListener` and a `LogicException` should be thrown instead - this is not a user error (like blank password), but a developer error.

A similar thing ? https://gist.github.com/Shine-neko/76f97ee46950a480074434fa3259f797/revisions

2020-05-25 09:32 UTC, wouterj commented
Yes, seems good. Although I think the error message can be changed, so we can give the developer guidelines on how to fix it (e.g. adding the expected password parameter named - `$this->options['password_parameter']`).

2020-06-23 05:10 UTC, fabpot commented
Any news? It looks the gist code is more in line with what we should do.

2020-06-26 18:22 UTC, Shine-neko commented
@fabpot  done

2020-06-28 07:05 UTC, fabpot requested changes

2020-06-28 07:05 UTC, fabpot commented on src/Symfony/Component/Security/Http/Firewall/UsernamePasswordFormAuthenticationListener.php
> +            throw new \LogicException(sprintf('The key "%s" cannot be empty.', $this->options['password_parameter']));
`The "%s" key cannot be null.`?

2020-08-17 05:53 UTC, fabpot requested changes

2020-08-17 05:53 UTC, fabpot commented on src/Symfony/Component/Security/Http/Firewall/UsernamePasswordFormAuthenticationListener.php
> +            throw new \LogicException(sprintf('The key "%s" cannot be null.', $this->options['password_parameter']));
Maybe try to explain the problem?

`sprintf('The key password cannot be null; check that the password field name of the form matches "%s".', $this->options['password_parameter'], $this->options['password_parameter']);`

2020-08-18 06:31 UTC, fabpot approved these changes

2020-08-18 06:32 UTC, fabpot commented
Thank you @Shine-neko.

2020-08-18 06:32 UTC, merged