[FrameworkBundle] Move session configuration to PHP
symfony/symfony pull request #37217
Opened 2020-06-11 13:07 UTC by cocorambo

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #37186
| License       | MIT

Move session configuration file to php

2020-06-11 13:26 UTC, yceruto requested changes

2020-06-11 13:26 UTC, yceruto commented on src/Symfony/Bundle/FrameworkBundle/Resources/config/session.php
> +            )
Let's consistently put all these arguments in one line (same below)

2020-06-11 13:26 UTC, yceruto commented on src/Symfony/Bundle/FrameworkBundle/Resources/config/session.php
> +};
missing newline

2020-06-11 13:40 UTC, yceruto commented
Please, check the fabbot report, there are other issues to solve: https://fabbot.io/report/symfony/symfony/37217/916dcec7c18845a635e11bb1bf796bbe426ab3f3

2020-06-11 13:49 UTC, yceruto approved these changes
LGTM, thanks!

2020-06-11 14:42 UTC, simivar commented
Shouldn't you remove old `session.xml` file?

2020-06-11 19:35 UTC, simivar approved these changes

2020-06-11 23:27 UTC, Tobion commented on src/Symfony/Bundle/FrameworkBundle/Resources/config/session.php
> +        ->alias('SessionHandlerInterface', 'session.handler')
`\SessionHandlerInterface::class`

2020-06-11 23:38 UTC, Tobion requested changes

2020-06-11 23:38 UTC, Tobion commented on src/Symfony/Bundle/FrameworkBundle/Resources/config/session.php
> +        ->alias('SessionHandlerInterface', 'session.handler')
`\SessionHandlerInterface::class` as it's a php class from the global namespace

2020-06-11 23:38 UTC, Tobion commented on src/Symfony/Bundle/FrameworkBundle/Resources/config/session.xml
> -        <service id="session.marshalling_handler" decorates="session.handler" class="Symfony\Component\HttpFoundation\Session\Storage\Handler\MarshallingSessionHandler">
`decorates="session.handler"` seems to be missing in the php config

2020-06-12 15:26 UTC, Tobion approved these changes

2020-06-12 15:27 UTC, Tobion commented
Thank you @cocorambo.

2020-06-12 15:27 UTC, merged

2020-06-12 15:32 UTC, rvanlaak commented
@Tobion merging this PR did close #37186 because of the description.

FYI same would happen for #37204 , #37208 and #37222