[Validator][FrameworkBundle] Move configurations from XML to PHP
symfony/symfony pull request #37222
Opened 2020-06-11 15:25 UTC by simivar

| Q             | A
| ------------- | ---
| Branch?       | master  
| Bug fix?      | no
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #37186 
| License       | MIT

Move `src/Symfony/Bundle/FrameworkBundle/Resources/config/validator*.xml` configurations to PHP

2020-06-11 16:45 UTC, yceruto approved these changes
LGTM, just minor style issue

2020-06-11 16:45 UTC, yceruto commented on src/Symfony/Bundle/FrameworkBundle/Resources/config/validator.php
> +            ->set('validator', ValidatorInterface::class)
extra indent issue

2020-06-11 19:25 UTC, simivar commented on src/Symfony/Bundle/FrameworkBundle/Resources/config/validator.php
> +            ->set('validator', ValidatorInterface::class)
Resolved

2020-06-12 00:03 UTC, Tobion requested changes

2020-06-12 00:07 UTC, Tobion commented on src/Symfony/Bundle/FrameworkBundle/Resources/config/validator.php
> +        ->set('validator.mapping.cache.prefix', null)
I added a commit to fix this. But now I cannot squash all your commits with our merge tool. So please squash your commits. You can also remove my last commit and apply it yourself if it makes it easier.

2020-06-12 09:20 UTC, simivar commented on src/Symfony/Bundle/FrameworkBundle/Resources/config/validator.php
> +        ->set('validator.mapping.cache.prefix', null)
Done. What merge tool are you using? I see it would be easier then if you wouldn't add your commit and just wait a little but it's fine now ;).

2020-06-12 16:12 UTC, Tobion approved these changes

2020-06-12 16:13 UTC, Tobion commented on src/Symfony/Bundle/FrameworkBundle/Resources/config/validator.php
> +        ->set('validator.mapping.cache.prefix', null)
A symfony internal one automating alot of stuff like changelogs.

2020-06-12 16:13 UTC, Tobion commented
Thank you @simivar.

2020-06-12 16:14 UTC, merged