[DoctrineBridge] Bumps doctrine/persistence to version 2.x
symfony/symfony pull request #37416
Opened 2020-06-25 13:16 UTC by fruitwasp

| Q             | A
| ------------- | ---
| Branch?       | master (bumps to a new major version)
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | 
| License       | MIT
| Doc PR        | 

Adds support for doctrine/persistence version to 2.x. As it's a new major version, I've targeted the master branch. Relates to https://github.com/doctrine/DoctrineBundle/pull/1181

2020-06-26 22:08 UTC, derrabus requested changes

2020-06-26 22:08 UTC, derrabus commented on composer.json
> +        "doctrine/persistence": "^2.0",
Why not `^1.3|^2.0`?

2020-06-28 11:35 UTC, nicolas-grekas commented
This should target branch 3.4 and compat with 1.* should be preserved.

2020-07-23 09:52 UTC, nicolas-grekas commented
Closing as staled, please resubmit when ready.

2020-07-23 09:52 UTC, closed without merging

2020-07-23 10:53 UTC, derrabus commented
I've had a quick look.

> This should target branch 3.4

On the 3.4 branch, we don't have any version constraints for doctrine/persistence.

On 4.4 and above, we're still blocked by `doctrine/data-fixtures`.

https://github.com/doctrine/data-fixtures/blob/ba588dfae2da361e8cb4908d2b2a21d09a47e8af/composer.json#L19

2020-07-23 12:38 UTC, derrabus commented
Continuation: #37639