chore: add redeliveredAt in RedeliveryStamp construct
symfony/symfony pull request #37480
Opened 2020-07-02 09:56 UTC by qkdreyer

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | -

---

this would allows one to correctly unserialise a RedeliveryStamp with a custom serializer not using the php serialize function

2020-07-02 11:19 UTC, qkdreyer commented
Travis failed because of weird `Error: Undefined class constant 'ALIASES'` errors

2020-07-02 16:51 UTC, noniagriconomie commented on src/Symfony/Component/Messenger/Stamp/RedeliveryStamp.php
> +        $this->redeliveredAt = $redeliveredAt instanceof \DateTimeImmutable ? $redeliveredAt : new \DateTimeImmutable();
```suggestion
        $this->redeliveredAt = $redeliveredAt ?? new \DateTimeImmutable();
```

i think you can rewrite like this

2020-07-03 12:35 UTC, nicolas-grekas commented
Can you please add a test case? This will allow spotting a typo ;)

2020-07-06 11:26 UTC, qkdreyer commented
Nicely catch @nicolas-grekas

2020-07-07 07:35 UTC, maxhelias approved these changes

2020-07-11 14:02 UTC, Tobion requested changes

2020-07-11 14:02 UTC, Tobion commented on src/Symfony/Component/Messenger/Stamp/RedeliveryStamp.php
> +    public function __construct(int $retryCount, string $exceptionMessage = null, FlattenException $flattenException = null, \DateTimeImmutable $redeliveredAt = null)
this should typehint `DateTimeInterface` since this is what getRedeliveredAt also typehints

2020-08-02 08:16 UTC, fabpot approved these changes

2020-08-02 08:17 UTC, fabpot commented
Thank you @qkdreyer.

2020-08-02 08:17 UTC, merged