Fix #37740: Cast all ParameterBag values to string
symfony/symfony pull request #37755
Opened 2020-08-06 13:19 UTC by rgeraads

| Q             | A
| ------------- | ---
| Branch?       | 5.1
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #37740| License       | MIT

This fix ensures that all values that are in ParameterBag are received as strings on the receiving end.

2020-08-06 14:29 UTC, stof commented
This is not the right fix for the issue. For instance, `->attributes` is perfectly allowed to hold other types (for instance booleans) and that would be a BC break.

The right fix must be implemented in the conversion layer between BrowserKit and HttpFoundation, for the query and request parameters only.

2020-08-06 14:49 UTC, rgeraads commented
Do you mean here? https://github.com/symfony/symfony/blob/786ba109d0a26b8bf7ada4aeb2d639da6599a586/src/Symfony/Component/HttpFoundation/Request.php#L391-L396

I can put the casting right before the switch/case

2020-08-06 14:57 UTC, stof commented
No. This place is still in the HttpFoundation request object itself (which might add overhead the handling of actual web requests btw).

This should either be done when creating the BrowserKit request (might make sense as other BrowserKit implementations would also not be able to submit non-string values), or when converting from one to the other in https://github.com/symfony/symfony/blob/e1cfbd20feb1fabfa8a691795ee7a8080bced384/src/Symfony/Component/HttpKernel/HttpKernelBrowser.php#L131-L133

2020-08-06 17:29 UTC, rgeraads commented
It would make most sense to put it in BrowserKit\Kernel then.

2020-08-18 11:31 UTC, fabpot requested changes
Should target master.

2020-08-18 11:31 UTC, fabpot commented on src/Symfony/Component/BrowserKit/Request.php
> +    private static function convertAllValuesToString(array $parameters): array
Could be inline.

2020-08-18 14:06 UTC, fabpot approved these changes

2020-08-18 14:08 UTC, fabpot commented
Thank you @rgeraads.

2020-08-18 14:08 UTC, merged

2021-03-13 12:36 UTC, kernio commented
Am I just wondering in addition to fix the "null" issue (that is good), why this modified behavior for parameters I passed as POST request?

Input request parameters 
array:8 [
  "profileId" => 1000
]

After
 array_walk_recursive($parameters, static function (&$value) {
            $value = (string) $value;
        });

array:8 [
  "profileId" => "1000"
]


Input validation for request
    /**
     * @Assert\Type(type="integer")
     * @Assert\NotNull
     */


Response:
Error: profileId should be "int"

2021-03-13 13:06 UTC, kernio commented
> Am I just wondering in addition to fix the "null" issue (that is good), why this modified behavior for parameters I passed as POST request?
> 

And answer to my own question (for anyone who had the same issue) is not using "params" here that used for application/x-www-form-urlencoded, but using a body with JSON encoded parameters and a proper header.