route matching improvement
symfony/symfony pull request #37865
Opened 2020-08-17 18:44 UTC by Angelisium

Before , in the generate() function, if the locale doesn't match with a route a "Route Not Found" error was generated.
Now the function tries all "locales" before failing miserably.

| Q             | A
| ------------- | ---
| Branch?       | 3.4, 4.4 or 5.1 for bug fixes
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       |  Before , in the generate() function, if the locale doesn't match with a route a "Route Not Found" error was generated. Now the function tries all "locales" before failing miserably.
| License       | MIT

Before , in the generate() function, if the locale doesn't match with a route a "Route Not Found" error was generated.
Now the function tries all "locales" before failing miserably.

2020-08-18 13:57 UTC, Tobion requested changes
What's the bug? Please add test cases.

2020-08-18 14:50 UTC, Angelisium commented
```php
/**
 * @Route({
 *      "fr": "/accueil",
 *      "en": "/home",
 *      "es": "/hogar",
 *      "de": "/hause",
 * }, name="home")
 * @return Response
 */
function showhome() {}
/**
 * @Route({
 *      "en": "/forum",
 *      "fr": "/salon"
 * }, name="forum")
 * @return Response
 */
function showforum() {}
```
if a "de" user go to "forum" route, he has a "Route Not Found" because "forum.de" and "forum" route doesn't exist. But it would make more sense to try if the route exists in the default language before return a "Not Route Found" error.
I don't speak English very well, I don't know if it's a bug or a feature 😅

2020-08-18 14:53 UTC, Tobion commented
I see. Seems like a sensible addition. I'd see it as a feature. Could you add unit tests for this?

2020-08-18 17:27 UTC, Angelisium commented
I see, I edit the first message.
This is my first time, I'm not sure which unit tests to perform. It's [this test](https://github.com/symfony/symfony/blob/1b5430bc9f7385a687c02607a3f8e11bcbce66e7/src/Symfony/Component/Routing/Tests/Generator/UrlGeneratorTest.php) ?
If yes, I duty create a test for my update ?
If yes, I think the `testGenerateWithInvalidLocale()` function should return the path of the default locale (instead of the expected error).. Or I would have to duplicate it and add a "defaultLocale" but i don't know how make this (set the defaultLocale outside the translation.yaml file).

Sorry if I say nonsense or ask stupid questions, it's my first time so i'm a little lost 😖

2020-08-28 07:45 UTC, maxhelias commented
Maybe we could add something like a parameter in `framework.router.match_local` with `curent` or `all`, or something else to keep the old behavior and have the new ?

2020-08-31 18:34 UTC, nicolas-grekas commented
I don't know if this a good idea.
We're having an ongoing discussion about trailing slashes, this one looks similar to me: something that fallbacks and that might create unexpected behaviors for some.
Why not list "de" if the route should be supported?
At leas, this should be opt-in (but then, this means something new to teach/learn. To be confirmed it's worth it.)

2020-08-31 20:07 UTC, GromNaN commented
The issue appears to be a misleading exception message when you try to generate an url from a route that actually exists, but does not support the current locale.
The exception could be `Unable to generate a URL for the named route "%s" as it does not support the locale "%s".`

2020-09-01 17:53 UTC, Angelisium commented
I see, it makes sense 🤔

2020-09-03 20:10 UTC, nicolas-grekas commented
>  The exception could be Unable to generate a URL for the named route "%s" as it does not support the locale "%s".

that could be a nice improvement

@Angelisium up to give it a try?

2020-09-03 20:20 UTC, nicolas-grekas commented
Closing meanwhile, thanks for submitting.

2020-09-03 20:20 UTC, closed without merging