[YAML] Unexpected characters using YAML compact syntax
symfony/symfony pull request #37876
Opened 2020-08-18 11:20 UTC by RevZer0

| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #37788
| License       | MIT
| Doc PR        | not available

Issue fix

2020-08-18 11:27 UTC, fabpot requested changes

2020-08-18 11:27 UTC, fabpot commented on src/Symfony/Component/Yaml/Tests/ParserTest.php
> +     * Test that covers #37788 issue.
Can be removed

2020-08-18 11:27 UTC, fabpot commented on src/Symfony/Component/Yaml/Parser.php
> +                    throw new ParseException(sprintf('"%s" keys are not supported. Quote your evaluable mapping keys instead.', is_numeric($key) ? 'Numeric' : 'Non-string'), $this->getRealCurrentLine
To be reverted (same for other changes suggested by fabbot, they are false positives)

2020-08-18 13:41 UTC, xabbuh commented
I think we should investigate if this overlaps with #33763.

2020-08-18 13:59 UTC, RevZer0 commented
> I think we should investigate if this overlaps with #33763.

Haven't seen this pr tbh. As far as I see your update will fix this issue

2020-08-19 11:13 UTC, fabpot commented
Does it mean that we can close this one in favor of #33763?

2020-08-19 11:38 UTC, RevZer0 commented
@fabpot I think yes

2020-08-19 12:20 UTC, closed without merging

2020-11-15 17:12 UTC, xabbuh commented
Thank you for working on this @RevZer0. I have added your test cases to #33763.