[Mailer] Fixed 'verify_peer' option in mailer DSN being ignored
symfony/symfony pull request #37961
Opened 2020-08-27 11:08 UTC by SnakePin

| Q             | A
| ------------- | ---
| Branch?       | 5.1 
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | N/A 
| License       | MIT
| Doc PR        | N/A 

The mailer DSN option 'verify_peer' was being ignored because `$dsn->getOption('verify_peer', true)` was returning a string and thus NOT operator on it was always resulting in false. I propose changing the line where it is used with a `filter_var` call with the `FILTER_VALIDATE_BOOLEAN` as the filter parameter to overcome this issue.

2020-08-27 13:55 UTC, fabpot requested changes
Can you add a test case to cover this fix?

2020-08-27 13:55 UTC, fabpot commented on src/Symfony/Component/Mailer/Transport/Smtp/EsmtpTransportFactory.php
> +        if (!$verify_peer) {
Var could be inlined.

2020-08-27 16:23 UTC, SnakePin commented
> 
> 
> Can you add a test case to cover this fix?

I've added some test cases to cover this fix in my latest commit but I've also added a check to avoid disabling the verification for a DSN like this `smtps://:@example.com?verify_peer=` because it could be misleading to disable it when it clearly doesn't have keywords like no, off or false and is just an empty string.

2020-08-28 07:56 UTC, fabpot requested changes

2020-08-28 07:56 UTC, fabpot commented on src/Symfony/Component/Mailer/Transport/Smtp/EsmtpTransportFactory.php
> +        if ('' !== $verify_peer_raw && !$verify_peer_boolean) {
Can you inline the two expression to get rid of the temp vars?

2020-08-28 07:56 UTC, fabpot commented on src/Symfony/Component/Mailer/Tests/Transport/Smtp/EsmtpTransportFactoryTest.php
> +            Dsn::fromString('smtps://:@example.com?verify_peer=off'),
Not sure we want to support `off` and `no`.

2020-08-31 17:05 UTC, nicolas-grekas approved these changes

2020-08-31 19:52 UTC, fabpot approved these changes

2020-08-31 19:53 UTC, fabpot commented
Thank you @SnakePin.

2020-08-31 19:53 UTC, merged