[HttpClient] fail properly when the server replies with HTTP/0.9
symfony/symfony pull request #38148
Opened 2020-09-10 18:20 UTC by nicolas-grekas

| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #37923
| License       | MIT
| Doc PR        | -

2020-09-10 19:40 UTC, stof commented
what about other client implementations ?

2020-09-10 19:41 UTC, stof commented
and this seems to break the http push tests

2020-09-11 05:38 UTC, fabpot requested changes

2020-09-11 05:38 UTC, fabpot commented on src/Symfony/Component/HttpClient/Response/ResponseTrait.php
> +                                $multi->handlesActivity[$j] = [null, new TransportException(sprintf('Unsupported protocol for "%s"', $response->getInfo('url')))];
missing dot at the end :)

2020-09-11 06:27 UTC, nicolas-grekas commented
> what about other client implementations ?

they already fail properly, only curl knows about HTTP/0.9

> and this seems to break the http push tests and many tests on Travis

fixed hopefuly

2020-09-11 07:06 UTC, merged