Add myself to CODEOWNERS for Form, OptionsResolver and TwigBundle
symfony/symfony pull request #38577
Opened 2020-10-14 23:15 UTC by yceruto

| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | -

I would like to be notified of these packages as well.

2020-10-15 04:46 UTC, fabpot requested changes

2020-10-15 04:46 UTC, fabpot commented on .github/CODEOWNERS
> +/src/Symfony/Component/ErrorHandler/ErrorRenderer/* @yceruto
The path seems wrong

2020-10-15 12:10 UTC, chalasr approved these changes

2020-10-15 20:51 UTC, jderusse approved these changes

2020-10-16 04:53 UTC, fabpot approved these changes

2020-10-16 04:54 UTC, fabpot commented
Thank you @yceruto.

2020-10-16 04:55 UTC, closed without merging