correct default arg
symfony/symfony pull request #38671
Opened 2020-10-21 22:22 UTC by craigh

correct default arg from abstract_arg to empty array. fixes #38615

| Q             | A
| ------------- | ---
| Branch?       | 5.x
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #38615
| License       | MIT
| Doc PR        | n/a

2020-10-22 07:30 UTC, chalasr commented
Should we allow declaring a type on abstract arguments?

2020-10-22 12:19 UTC, maxhelias commented
An abstract argument is not able to reflect the type or default value of the class ?

2020-10-22 12:39 UTC, nicolas-grekas approved these changes

2020-10-22 12:40 UTC, nicolas-grekas commented
> Should we allow declaring a type on abstract arguments?

That wouldn't fix the linked issue. Providing an actual value for the arg is required here.

2020-10-22 12:41 UTC, chalasr commented
Yes ofc, off-topic sorry.

2020-10-22 12:42 UTC, chalasr approved these changes

2020-10-22 16:42 UTC, stof commented
I don't think this will solve the issue. If BazingaJsTranslationBundle accesses the argument before the value is set, it will see an empty array instead of the list of loader ids.

2020-10-22 16:46 UTC, stof commented
Here, the question is whether we have cases where FrameworkBundle does not replace the AbstractArgument with a proper value. If that's the case, defaulting to an empty array is good. If that's not the case, the bug is related to the ordering of the logic between FrameworkBundle and BazingaJsTranslationBundle (and might be an older bug if the ordering is not changing in 5.2)

2020-10-22 18:57 UTC, craigh commented
@stof, it appears to work in my tests. The ordering of the logic seems to work ok but if you have a way for me to check more specifically, I am happy to do so. BazingaJsTranslationBundle doesn't use any priority or step settings in their compiler pass, so they are using all defaults.

BazingaJsTranslationBundle is not checking for values (see [here](https://github.com/willdurand/BazingaJsTranslationBundle/blob/master/DependencyInjection/Compiler/TranslationResourceFilesPass.php#L58)) but just merging in their own.

2020-10-22 19:45 UTC, xabbuh requested changes
It looks like the bundle relies on the constructor signature from Symfony 3 where the `$options` argument was the fourth one. This has changed in 4.0 where the `$defaultLocale` was added in between (meaning that `$options` is now the fifth argument).

:-1: from me as this needs to be fixed in BazingaJsTranslationBundle instead

2020-10-23 04:38 UTC, fabpot commented
Closing for the reason explained by @xabbuh

2020-10-23 04:38 UTC, closed without merging