Fix Preloader exception when having a class with an unknown parent/interface
symfony/symfony pull request #38713
Opened 2020-10-25 11:18 UTC by rgeraads

| Q             | A
| ------------- | ---
| Branch?       | 5.1
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #38693
| License       | MIT

Fixes Preloader exception when having a class with an unknown parent/interface

2020-10-25 11:35 UTC, derrabus commented
Did you check if this problem exists on 4.4 as well? If yes, we need to fix it there.

2020-10-25 11:38 UTC, rgeraads commented
@derrabus looks like it! https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/DependencyInjection/Dumper/Preloader.php#L90-L92

2020-10-25 12:26 UTC, derrabus requested changes
The change looks correct to me. Just some remarks on the test setup.

2020-10-25 12:26 UTC, derrabus commented on src/Symfony/Component/DependencyInjection/Tests/Dumper/PreloaderTest.php
> +
I'd create a separate test for this case instead of merging it into the two existing tests.

2020-10-25 12:26 UTC, derrabus commented on src/Symfony/Component/DependencyInjection/Tests/Fixtures/Preload/DummyWithInterface.php
> +    }
```suggestion
```

This is just noise. What we want to assert is that the preloader does not choke on the missing `NonExistentDummyInterface`, so we don't need the rest of the class body.

2020-10-25 12:28 UTC, derrabus commented
> @derrabus looks like it!

Can you rebase your changes on 4.4 then? If not, that's okay as well. I can do that while merging.

2020-10-25 12:31 UTC, derrabus commented
Oh, and thank you very much for your PR, of course. 😃

2020-10-25 13:06 UTC, rgeraads commented
> > @derrabus looks like it!
> 
> Can you rebase your changes on 4.4 then? If not, that's okay as well. I can do that while merging.

I rebased it now. Will you port the fix to 5.1 then?

2020-10-25 13:12 UTC, derrabus approved these changes

2020-10-25 13:15 UTC, derrabus commented
> Will you port the fix to 5.1 then?

The branches are periodically merged. Changes merged to the 4.4 branch will also shipped with the next 5.1 release.

2020-10-27 08:02 UTC, nicolas-grekas approved these changes

2020-10-27 10:05 UTC, nicolas-grekas commented
Thank you @rgeraads.

2020-10-27 10:06 UTC, merged