[Console] Test degraded true colors
symfony/symfony pull request #38866
Opened 2020-10-28 14:20 UTC by freezy-sk

| Q             | A
| ------------- | ---
| Branch?       | 5.x
| Bug fix?      | no
| New feature?  | no 
| Deprecations? | no 
| Tickets       | 
| License       | MIT
| Doc PR        | symfony/symfony-docs#14494 

Testing hidden feature of hex colors degraded to ANSI named colors for terminals without true color support.

2020-10-28 18:12 UTC, fabpot requested changes

2020-10-28 18:12 UTC, fabpot commented on src/Symfony/Component/Console/Tests/ColorTest.php
> +        putenv('COLORTERM='.$colorterm);
I would put this in a finally clause

2020-10-28 21:37 UTC, derrabus approved these changes

2020-10-28 21:45 UTC, ogizanagi approved these changes

2020-10-29 07:35 UTC, fabpot approved these changes

2020-10-29 07:36 UTC, fabpot commented
Thank you @freezy-sk.

2020-10-29 07:36 UTC, merged