[Messenger] Change defaults name like Doctrine ones
symfony/symfony pull request #38943
Opened 2020-11-01 16:22 UTC by 94noni

| Q             | A
| ------------- | ---
| Branch?       | 5.x 
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | None
| License       | MIT
| Doc PR        | If PR approved, as well as changing recipes

Hi

After playing with messenger, testing doctrine first as sync and then rabbitmq/redis for async, I found it weird that doctrine defaults to storage prefixed with `messenger_` but not others (https://github.com/symfony/symfony/blob/050f3e43a5f01296f48545c7598850311469395a/src/Symfony/Component/Messenger/Bridge/Doctrine/Transport/Connection.php#L41)

That is why I propose this PR

If accepted:
- question: should I target 4.4?
- I will change doc and `manifest.json` inside recipes as well

Thank you

2020-11-01 16:49 UTC, yceruto commented
LGTM for 5.x, but tests are failing because your changes, could you fix them please?

2020-11-01 17:37 UTC, Nyholm requested changes
Event hough I would agree with consistency, this will make unnecessary changes in all applications using Redis or AMQP. 

Im 👎 for only that reason.

2020-11-01 18:03 UTC, 94noni commented
@Nyholm you mean that ppl will need to change their .env values or messenger.yaml value?
or would need to return `setup-transport` cli?

2020-11-01 18:09 UTC, Nyholm commented
Yes. If people want nothing to change in their infrastructure, they are forced to update their environment variables or mesenger.yaml. 

If someone has disabled `auto-setup` and still rely on the default values for the exchange/stream, their application will break. 

The best case scenario is that `auto-setup` is enabled and they will just get an extra stream/exchange in their infrastructure.

This will just cause some headaches for existing users for no benefit at all.

2020-11-02 06:54 UTC, fabpot commented
Let's close for the reasons explained by @Nyholm (the BC break is not worth it)

2020-11-02 06:54 UTC, closed without merging