[FrameworkBundle] Fixed validation of php_errors.log
symfony/symfony pull request #39018
Opened 2020-11-06 14:57 UTC by lyrixx

| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       |
| License       | MIT
| Doc PR        |

It's actually possible to pass a map or PHP errors => Log level like
following

```yaml
    php_errors:
        log:
            !php/const \E_DEPRECATED: !php/const Psr\Log\LogLevel::ERROR
            !php/const \E_USER_DEPRECATED: !php/const Psr\Log\LogLevel::ERROR
            !php/const \E_NOTICE: !php/const Psr\Log\LogLevel::ERROR
            !php/const \E_USER_NOTICE: !php/const Psr\Log\LogLevel::ERROR
            !php/const \E_STRICT: !php/const Psr\Log\LogLevel::ERROR
            !php/const \E_WARNING: !php/const Psr\Log\LogLevel::ERROR
            !php/const \E_USER_WARNING: !php/const Psr\Log\LogLevel::ERROR
            !php/const \E_COMPILE_WARNING: !php/const Psr\Log\LogLevel::ERROR
            !php/const \E_CORE_WARNING: !php/const Psr\Log\LogLevel::ERROR
            !php/const \E_USER_ERROR: !php/const Psr\Log\LogLevel::CRITICAL
            !php/const \E_RECOVERABLE_ERROR: !php/const Psr\Log\LogLevel::CRITICAL
            !php/const \E_COMPILE_ERROR: !php/const Psr\Log\LogLevel::CRITICAL
            !php/const \E_PARSE: !php/const Psr\Log\LogLevel::CRITICAL
            !php/const \E_ERROR: !php/const Psr\Log\LogLevel::CRITICAL
            !php/const \E_CORE_ERROR: !php/const Psr\Log\LogLevel::CRITICAL
```

2020-11-07 07:39 UTC, fabpot commented
Looks like a new feature to me.

2020-11-11 10:43 UTC, nicolas-grekas commented on src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php
> +                            ->example('"true" to use the default configuration: log all errors. "false" to disable. An integer bit field of E_* constants. A mapping from integer (E_* constant) to a l
`An integer bit field of E_* constants, or an array mapping E_* constants to a log levels.`

2020-11-11 10:43 UTC, nicolas-grekas commented on src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php
> +                                ->thenInvalid('The "php_errors.log" parameter should be either an integer, a boolean, or an array.')
the last comma should be removed

2020-11-27 06:43 UTC, fabpot commented
@lyrixx Do you have time to finish this PR and rebase it on 5.x? Thank you

2020-11-27 09:07 UTC, lyrixx commented
Oups, yes. I'll do that ASAP

2020-11-30 19:30 UTC, lyrixx commented
The PR should be ready

2020-12-05 06:58 UTC, fabpot requested changes
Can you also add a test?

2020-12-05 06:58 UTC, fabpot commented on src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php
> +                            ->example('"true" to use the default configuration: log all errors. "false" to disable. An integer bit field of E_* constants, or an array mapping E_* constants to a log l
to log levels?

2020-12-05 06:58 UTC, fabpot commented on src/Symfony/Bundle/FrameworkBundle/CHANGELOG.md
> + * Added support for configuring PHP error level to log level
Missing white line before

2020-12-05 16:27 UTC, lyrixx commented
I added true support for XML (can't wait to remove this :p) + added tests
It should be OK now

BTW, Fabbot seems wrong:
```
in src/Symfony/Bundle/FrameworkBundle/Tests/DependencyInjection/Fixtures/yml/php_errors_log_levels.yml
Non-string keys are not supported. Quote your evaluable mapping keys instead at line 4 (near "!php/const \E_NOTICE: !php/const Psr\Log\LogLevel::ERROR").
```

2020-12-05 16:35 UTC, fabpot approved these changes

2020-12-05 16:36 UTC, fabpot commented
Thank you @lyrixx.

2020-12-05 16:36 UTC, merged

2020-12-18 14:45 UTC, vudaltsov commented
For now one can use a compiler pass like this:

```php
<?php

declare(strict_types=1);

namespace App;

use Psr\Log\LogLevel;
use Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface;
use Symfony\Component\DependencyInjection\ContainerBuilder;

/**
 * @todo move to framework.php_errors.log config after updating to Symfony 5.3
 *       https://github.com/symfony/symfony/pull/39018
 */
final class SetDebugHandlersListenerLogLevelsPass implements CompilerPassInterface
{
    public function process(ContainerBuilder $container): void
    {
        if (!$container->has('debug.debug_handlers_listener')) {
            return;
        }

        $container
            ->findDefinition('debug.debug_handlers_listener')
            ->replaceArgument(2, [
                E_COMPILE_ERROR => LogLevel::CRITICAL,
                E_COMPILE_WARNING => LogLevel::CRITICAL,
                E_CORE_ERROR => LogLevel::CRITICAL,
                E_CORE_WARNING => LogLevel::CRITICAL,
                E_DEPRECATED => LogLevel::NOTICE,
                E_ERROR => LogLevel::CRITICAL,
                E_NOTICE => LogLevel::CRITICAL,
                E_PARSE => LogLevel::CRITICAL,
                E_RECOVERABLE_ERROR => LogLevel::CRITICAL,
                E_STRICT => LogLevel::CRITICAL,
                E_USER_DEPRECATED => LogLevel::NOTICE,
                E_USER_ERROR => LogLevel::CRITICAL,
                E_USER_NOTICE => LogLevel::CRITICAL,
                E_USER_WARNING => LogLevel::CRITICAL,
                E_WARNING => LogLevel::CRITICAL,
            ])
        ;
    }
}
```