Call libxml_disable_entity_loader only for PHP 8
symfony/symfony pull request #39068
Opened 2020-11-12 18:15 UTC by jderusse

| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #39040
| License       | MIT
| Doc PR        | -

The XML entity loader is disabled by default since libxml 2.9, and calling `libxml_disable_entity_loader`
But, since PHP 8.0, calling the method `libxml_disable_entity_loader` triggers a deprecation which has been solved in symfony by calling `libxml_disable_entity_loader` only for libxml < 2.9

The issue is, some dependencies, enable the entity loader and does not restore the initial state afterward, leading to exceptions triggered by Symfony iteself.

In previous versions symfony was resilient by disabling the flag before working, which is not the case anymore to avoid the deprecation.

This PR restore the resiliency of Symfony for PHP < 8.0, which is not yet deprecated.

But we have no way to check the status of the entity loader without triggering a deprecation with Symfony 8.

2020-11-12 18:20 UTC, stof commented
could we suffer from issues on PHP 8 due to other libraries changing such global state too ? Or is PHP 8 turning that into a no-op ?

2020-11-12 18:26 UTC, jderusse commented
@stof I don't think so, we will suffer from the same issue. 

a solution could be to implement a method by our self that check the status of the entity loader and use this instead of checking the version.
note: `libxml_disable_entity_loader` is used in 5 components

2020-11-12 18:42 UTC, derrabus commented
> could we suffer from issues on PHP 8 due to other libraries changing such global state too ?

Yes, this change only buys us some time. The main problem is that php 8 triggers a seprecation without offering us an alternative.

> Or is PHP 8 turning that into a no-op ?

As far as I understood it, the functionality is the same.

@jderusse The PR title tells quite the opposite of what this PR is doing. 😉

2020-11-12 19:03 UTC, stof commented
> Yes, this change only buys us some time. The main problem is that php 8 triggers a seprecation without offering us an alternative.

Then this should be reported to PHP *before* the release of PHP 8. Deprecating an API without an alternative is not OK.

2020-11-12 19:09 UTC, jderusse commented
> > Yes, this change only buys us some time. The main problem is that php 8 triggers a seprecation without offering us an alternative.
> 
> Then this should be reported to PHP _before_ the release of PHP 8. Deprecating an API without an alternative is not OK.

This is deprecated, because nobody should call it in PHP >= 8.
BUT if somebody call it, you have to revert the call, and you can't do it without triggering a deprecation.

2020-11-12 19:13 UTC, stof commented
> This is deprecated, because nobody should call it in PHP >= 8.
> BUT if somebody call it, you have to revert the call, and you can't do it without triggering a deprecation.

That's precisely the issue. As it is deprecated without being a no-op, it still affects the global state for everyone. And so shared libraries (which cannot know what else is running in the project) cannot assume the global state and so are forced to keep calling the deprecated API. And that makes the deprecation warning an issue.
In practice, Symfony on PHP 8 is still not reliably working even after this PR, because it assumes that no other code is using the deprecated API.

2020-11-12 20:03 UTC, jderusse commented on src/Symfony/Component/Config/Tests/Util/XmlUtilsTest.php
> -        if (\LIBXML_VERSION < 20900) {
This is wrong, we should check the version of the LIB when disabling the entity loader (calling with `true`)

same below

2020-11-12 20:03 UTC, jderusse commented
Bug opened https://bugs.php.net/bug.php?id=80357

2020-11-12 20:41 UTC, derrabus approved these changes
I'm okay with the change because it fixes the regression for now. We can iterate further when we have feedback from PHP.

2020-11-12 20:42 UTC, derrabus commented
> Bug opened https://bugs.php.net/bug.php?id=80357

Thank you. 😃

2020-11-12 21:07 UTC, jderusse commented
I changed the patch to 

1. let previous code about `libxml_disable_entity_loader(true)` 

Disabling entity loaded is not needed sin libXml 2.9 (this is the reason on the deprecation in PHP 8 by the way). 
We don't have to disable it on our ide (whether or not it's previously disabled, it won't changed our code).

2. Silent deprecation triggered by `libxml_disable_entity_loader(false)`

`FALSE` is default value, and Symfony need it (cf bug). Given we can't do it without triggering a deprecation we shoud silent it, as suggested in  https://bugs.php.net/bug.php?id=80357

3. Stop calling `libxml_disable_entity_loader(false)` after PHP 9

Because the method is deprecated in 8.0 and we are still calling it with `@` sign, we should prevent calling it afterward.

2020-11-12 21:07 UTC, derrabus commented
So, it's silencing now according to the feedback we've received? Well okay, let's silence the error then.

2020-11-12 21:09 UTC, derrabus requested changes

2020-11-12 21:09 UTC, derrabus commented on src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php
> +        if (\PHP_VERSION_ID < 90000) {
We don't know anything about a potential php 9. I'd either remove the check completely or use `function_exists()` instead.

2020-11-12 23:09 UTC, derrabus approved these changes

2020-11-12 23:19 UTC, derrabus commented
Our deprecation error handler still triggers during tests if the deprecation is silenced. :-(

2020-11-19 22:52 UTC, jderusse commented
I don't know if PHP 8 will fix the issue, I the meantime, I suggest this patch that check if the entity loader is disabled by trying to validate a wellknown document

2020-11-27 06:34 UTC, fabpot approved these changes

2020-11-27 06:34 UTC, fabpot commented
PHP won't fix the issue as PHP 8 is now released. Let's merge this one then.

2020-11-27 06:36 UTC, fabpot commented
Thank you @jderusse.

2020-11-27 06:36 UTC, merged

2020-12-11 17:10 UTC, JarJak commented
There may be more places that require a fix, i.e. https://github.com/symfony/config/blob/5.x/Util/XmlUtils.php#L55

2020-12-11 17:47 UTC, jderusse commented
These 2 lines are about disabling the `entity_loader` which is not needed, because disabled by default since LIBXML_VERSION 2.9

This PR is about enabling the `entity_loader` in case somebody disabled it.