[Browserkit] Add changelog entry for request parameters string cast
symfony/symfony pull request #39060
Opened 2020-11-11 22:56 UTC by chalasr

| Q             | A
| ------------- | ---
| Branch?       | 5.2
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | Fixes #38651, Fixes #38591
| License       | MIT
| Doc PR        | -

2020-11-12 06:45 UTC, derrabus approved these changes

2020-11-14 07:30 UTC, fabpot approved these changes

2020-11-14 07:31 UTC, fabpot requested changes

2020-11-14 07:31 UTC, fabpot commented on src/Symfony/Component/BrowserKit/CHANGELOG.md
> + * [BC BREAK] Request parameters are now casted to string in `Request::__construct()`.
Should be in a new 5.2 section, right?

2020-11-14 11:04 UTC, chalasr commented on src/Symfony/Component/BrowserKit/CHANGELOG.md
> + * [BC BREAK] Request parameters are now casted to string in `Request::__construct()`.
fixed

2020-11-14 15:20 UTC, fabpot approved these changes

2020-11-14 15:21 UTC, fabpot commented
Thank you @chalasr.

2020-11-14 15:21 UTC, merged