[Messenger] Implement MessageCountAwareInterface in RedisTransport
symfony/symfony pull request #39127
Opened 2020-11-20 15:01 UTC by chrishemmings

[Messenger] Implement MessageCountAwareInterface in RedisTransport

| Q             | A
| ------------- | ---
| Branch?       | 5.x 
| Bug fix?      |no
| New feature?  | yes
| Deprecations? |no
| Tickets       | 
| License       | MIT
| Doc PR        | n/a

Implement MessageCountAwareInterface in RedisTransport by providing the getMessageCount() method in the Connection class.  This calls xLen() on the Redis steam to return the number of items left to process.

2020-11-20 19:55 UTC, jderusse approved these changes

2020-11-20 19:56 UTC, jderusse reviewed
could you please add tests?

2020-11-21 05:50 UTC, fabpot approved these changes

2020-11-21 11:12 UTC, chalasr requested changes
This might not be the count we expect. I'm "blocking" this PR until we can confirm it.
See https://github.com/symfony/symfony/pull/31545#discussion_r285447357
https://github.com/symfony/symfony/pull/30917#issuecomment-481790243 for previous attempts.
ping @alexander-schranz

2020-11-21 11:59 UTC, chrishemmings commented
@chalasr I'll check this out.  The queue needs to have `delete_after_ack` otherwise stream count will be completely incorrect, maybe return `null` for the count if `delete_after_ack` is not set on the connection?  I can check some other scenarios around delayed and queued messages as well.  Ultimately, I need to get at least a very close approximation as to the number of messages in the queue, as, without being able to monitor this, for queues that may not be processing correctly, I can't use this in any production platforms.

Any pointers would be appreciated.  Thanks 👍

2020-11-24 09:40 UTC, alexander-schranz commented
As correctly linked by @chalasr the way to get the length would be what I have commented at: https://github.com/symfony/symfony/pull/31545#discussion_r285447357. The problem here is that redis depending on your redis extension version does return the `xinfo` in [different formats](https://github.com/phpredis/phpredis/issues/1559) so this is not easy to parse to get the `last-delivered-id` correctly in all supported versions.

Aslong as `delete_after_ack` was set from the beginning `xlen` would return the correct count but if it was added later to the DSN it and the stream was not manually cleared then it would also not return the correct count for the messages which are expected. So not sure if I would depend on `xlen` in any case.

2021-01-05 06:28 UTC, fabpot commented
@chrishemmings Are you still working on this PR?

2021-01-05 09:12 UTC, chrishemmings commented
> @chrishemmings Are you still working on this PR?

Hi there, for now I don't have time to look at this, it's turned into a more complex problem than I initially though.  Closing.

2021-01-05 09:12 UTC, closed without merging

2022-08-11 15:29 UTC, rvanlaak commented
To try reviving this issue; would the blocker we had earlier for getting this feature still be there?

Could we use a command like XPENDING for checking the Redis stream length? https://redis.io/commands/xpending/

2022-08-11 15:31 UTC, chalasr commented
No more blocker, the message count will be available for redis as of Symfony 6.2 thanks to https://github.com/symfony/symfony/pull/46229