[Mime] Leverage PHP 8's detection of CSV files
symfony/symfony pull request #39252
Opened 2020-11-30 21:43 UTC by derrabus

| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | #39237
| License       | MIT
| Doc PR        | N/A

2020-11-30 22:14 UTC, jderusse approved these changes

2020-12-05 06:24 UTC, fabpot approved these changes

2020-12-05 06:26 UTC, fabpot requested changes
I think you also need to add `application/csv` to the reverse map

2020-12-05 08:28 UTC, derrabus commented
Done!

2020-12-05 08:38 UTC, fabpot approved these changes

2020-12-05 08:49 UTC, fabpot commented
Thank you @derrabus.

2020-12-05 08:49 UTC, merged