[Cache] Fixed incorrect usage of UNLINK with PHPRedis with Redis < 4.0
symfony/symfony pull request #39298
Opened 2020-12-03 10:15 UTC by wickex

| Q             | A
| ------------- | ---
| Branch?       | 5.x
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #39280
| License       | MIT

Currently, deleting cache keys is broken for users using PhpRedis with Redis-server < 4.0.0. The current implementation expects PhpRedis to throw an exception if the 'unlink'-function is used but unavailable, after which it's supposed to switch to using the 'del'-function. Using the 'unlink'-function on lower Redis-server versions seems to not throw an exception, but instead it appears to silently fail.

This pull request changes this behavior and checks the Redis-server version instead. If the version is 4.0 or higher, it uses the unlink function. If not, it uses the del-function.

Also see https://redis.io/commands/unlink > "Available since 4.0.0".

(Footnote: this is one of my first times contributing to an open-source project and my first time contributing to Symfony. I've tried following the guidelines, but please let me know if I missed anything. I'm unsure how I would go about unit testing this specific bugfix due to it being dependent on the Redis version, so I omitted it. Please let me know if a unit test is indeed required for this and if so, let me know if you have any suggestions on how to go about that.)

2020-12-03 11:03 UTC, derrabus commented on src/Symfony/Component/Cache/Traits/RedisTrait.php
> +            $info = $info['Server'] ?? $info;
Can we cache this so we won't execute that code on every delete operation?

2020-12-03 11:05 UTC, derrabus commented
Thank you very much for working on this issue. Because the 5.2 branch is affected by this bug, please base your PR on the 5.2 branch.

2020-12-04 09:47 UTC, jderusse reviewed
From the Redis documentation this is available since Redis 4.0 https://redis.io/commands/unlink

I believe the fix should also be applied to Predis. Right?

Looks like the `Predis\Command\Redis\UNLINK` does not exists. /cc @jonashrem

2020-12-04 10:00 UTC, wickex commented
Here's the pull request that introduced these changes: https://github.com/symfony/symfony/pull/37993.

The UNLINK command is a pending pull request to Predis (see https://github.com/predis/predis/pull/666) and not yet available, but might be in the future if/when it's approved. There's a check to see if that class exists or it will fall back to the DELETE-command, so there currently aren't any negative side effects in keeping it.

2020-12-07 16:57 UTC, nicolas-grekas commented
Which version of phpredis are you using?
On my machine, using v5.3.2, I do get an exception.

2020-12-07 18:41 UTC, nicolas-grekas requested changes
Looking at @jderusse's comment at https://github.com/symfony/symfony/issues/39280#issuecomment-740082057, we should handle the case where the call returns `false` instead.

2020-12-08 11:06 UTC, nicolas-grekas commented
Thank you @wickex.

2020-12-08 11:06 UTC, merged