[DependencyInjection] Add missing parameter type declarations to loader classes
symfony/symfony pull request #39292
Opened 2020-12-02 22:02 UTC by derrabus

| Q             | A
| ------------- | ---
| Branch?       | 5.x
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | N/A
| License       | MIT
| Doc PR        | N/A

This PR adds missing parameter type declarations to the loader classes of the DI component. We initially omitted them in order to stay compatible to the Config component of 4.4. But that compatibility was dropped afterwards and we somehow forgot to add the types here.

2020-12-04 17:06 UTC, jderusse approved these changes

2020-12-05 10:36 UTC, xabbuh approved these changes

2020-12-05 10:37 UTC, xabbuh requested changes
Hm, looks like some tests are failing with this change.

2020-12-05 11:15 UTC, derrabus commented
The tests failed because three fixtures in SecurityBundle use the container as resource type. That does not really make sense. I'm going to backport that fix.

2020-12-05 12:11 UTC, derrabus commented
> I'm going to backport that fix

#39324

2020-12-05 15:44 UTC, fabpot approved these changes

2020-12-05 15:48 UTC, fabpot commented
Thank you @derrabus.

2020-12-05 15:48 UTC, merged