Add Croatian (hr) translations
symfony/symfony pull request #39332
Opened 2020-12-05 14:45 UTC by jseparovic1

| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  |no 
| Deprecations? | no
| Tickets       | Fix #38734 
| License       | MIT

2020-12-05 15:07 UTC, Nyholm commented
Awesome. 

Could I ask @HypeMC @MarioBlazek or @X-Coder264 to review this?

2020-12-05 15:10 UTC, Nyholm reviewed
Awesome. Thank you so much. 

I was using google translate to verify this. I might have been super wrong in my comments, but could you double check?

2020-12-05 15:10 UTC, Nyholm commented on src/Symfony/Component/Form/Resources/translations/validators.hr.xlf
> +                <target>Molom odaberite ispravnu vremensku zonu.</target>
Could you double check this?

2020-12-05 15:10 UTC, Nyholm commented on src/Symfony/Component/Validator/Resources/translations/validators.hr.xlf
> +                <target>Ova vrijednost mora zadovoljiti jedan od sljedećih ograničenja:</target>
Does this say "limit" or "constraints"?

2020-12-05 15:21 UTC, jseparovic1 commented on src/Symfony/Component/Form/Resources/translations/validators.hr.xlf
> +                <target>Molom odaberite ispravnu vremensku zonu.</target>
Good catch!

2020-12-05 15:22 UTC, Nyholm reviewed
Im happy with this PR. But I would be happy if a native speaker double checked.

2020-12-05 15:25 UTC, jseparovic1 commented on src/Symfony/Component/Validator/Resources/translations/validators.hr.xlf
> +                <target>Ova vrijednost mora zadovoljiti jedan od sljedećih ograničenja:</target>
It says constraints in my opinion.

2020-12-06 03:42 UTC, X-Coder264 requested changes
@Nyholm Done. There's just some typos, the rest is fine.

2020-12-06 03:42 UTC, X-Coder264 commented on src/Symfony/Component/Form/Resources/translations/validators.hr.xlf
> +                <target>Polje za potrvrdu sadrži neispravnu vrijednost.</target>
@jseparovic1 "potvrdu"

2020-12-06 03:42 UTC, X-Coder264 commented on src/Symfony/Component/Security/Core/Resources/translations/security.hr.xlf
> +                <target>Link za prijavu je istako ili je neispravan.</target>
@jseparovic1 "istekao"

2020-12-06 03:42 UTC, X-Coder264 commented on src/Symfony/Component/Validator/Resources/translations/validators.hr.xlf
> +                <target>Ova vrijednost ne nije ispravno ime poslužitelja (engl. hostname).</target>
@jseparovic1 "ne" should be deleted from this sentence.

2020-12-06 11:31 UTC, MarioBlazek commented
Looks good. @jseparovic1 did a great job here. Address @X-Coder264 comments and that's it.

2020-12-06 13:31 UTC, Nyholm commented
Awesome. Thank you. 

@jseparovic1 Just some more fixes and we are done here =)

2020-12-06 14:12 UTC, jseparovic1 commented
@MarioBlazek @X-Coder264 Thank you for review. 

@Nyholm Typos are fixed an PR is ready now 🚀

2020-12-06 14:13 UTC, Nyholm approved these changes
Thank you

2020-12-07 09:00 UTC, derrabus commented
Thank you @jseparovic1.

2020-12-07 09:00 UTC, merged