[Notifier] Fix parsing Dsn with empty user/password
symfony/symfony pull request #39538
Opened 2020-12-17 19:29 UTC by OskarStark

| Q             | A
| ------------- | ---
| Branch?       | 5.1
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | ---
| License       | MIT
| Doc PR        | ---

Same like https://github.com/symfony/symfony/pull/39531, but for Notifier component.

I backported the DsnTest from `5.2`

2020-12-17 21:00 UTC, bykclk requested changes

2020-12-17 21:00 UTC, bykclk commented on src/Symfony/Component/Notifier/Tests/Transport/DsnTest.php
> +    public function testFromString(string $string, Dsn $expectedDsn): void
`: void` as usual :)

2020-12-17 21:00 UTC, bykclk commented on src/Symfony/Component/Notifier/Tests/Transport/DsnTest.php
> +    public function testGetOption(): void
`: void` as usual :)

2020-12-17 21:00 UTC, bykclk commented on src/Symfony/Component/Notifier/Tests/Transport/DsnTest.php
> +    public function testInvalidDsn(string $dsn, string $exceptionMessage): void
`: void` as usual :)

2020-12-18 05:22 UTC, OskarStark commented on src/Symfony/Component/Notifier/Tests/Transport/DsnTest.php
> +    public function testFromString(string $string, Dsn $expectedDsn): void
Damn all the time it gets added by the IDE 😛

Thanks

2020-12-18 05:23 UTC, OskarStark commented on src/Symfony/Component/Notifier/Tests/Transport/DsnTest.php
> +    public function testFromString(string $string, Dsn $expectedDsn): void
```suggestion
    public function testFromString(string $string, Dsn $expectedDsn)
```

2020-12-18 05:23 UTC, OskarStark commented on src/Symfony/Component/Notifier/Tests/Transport/DsnTest.php
> +    public function testInvalidDsn(string $dsn, string $exceptionMessage): void
```suggestion
    public function testInvalidDsn(string $dsn, string $exceptionMessage)
```

2020-12-18 05:23 UTC, OskarStark commented on src/Symfony/Component/Notifier/Tests/Transport/DsnTest.php
> +    public function testGetOption(): void
```suggestion
    public function testGetOption()
```

2020-12-18 07:23 UTC, OskarStark commented
Ready to merge from my side 👍

2020-12-18 07:25 UTC, fabpot approved these changes

2020-12-18 07:25 UTC, fabpot commented
Thank you @OskarStark.

2020-12-18 07:26 UTC, merged