Add an easy way to customize "interval" in the default security.login_throttling
symfony/symfony pull request #39927
Opened 2021-01-21 18:43 UTC by damienfa

| Q             | A
| ------------- | ---
| Branch       | 5.2
| Bug fix      |  no
| New feature  | yes
| Deprecations | no
| License       | MIT
| Doc PR        | ⚠️  no doc

The only way to customize the default rate-limiter's options of the login_throttling (means fixed_window / 1 minute / 5 tokens) are through a custom limiter, which implies to declare a rate-limiter factory in the "framework.rate_limiter", a service which use this factory etc. It's really heavy just for changing an interval (moreover, 1 minute can be discutable).
 
In this PullRequest, I just propose to allow an `interval` option. 

Example : 
```
security:
  firewalls:
    main:
       login_throttling:
           max_attempts: 5
           interval: '15 minutes'
```

⚠️   At the time of writing, there is no Symfony documentation about the Login Throttling feature ([only a blog post](https://symfony.com/blog/new-in-symfony-5-2-login-throttling)). Is there a reason to that ? Or may I propose something ?

2021-01-21 23:54 UTC, wouterj commented
Hi @damienfa! Thanks for your time creating this PR. I think such an option makes lots of sense!

Are you willing to add a test for this new feature? (I can help if you are unsure how to do this) Also note the failing CS check in "fabbot.io" is related to this PR (there seems to be a trailing whitespace).

> At the time of writing, there is no Symfony documentation about the Login Throttling feature (only a blog post). Is there a reason to that ? Or may I propose something ?

Lacking time was the main factor (and we have to be careful to mention it only works when using experimental authenticators). I'm happy to review if you propose some docs for this feature.

2021-01-22 00:40 UTC, damienfa commented
Ok, thanks for your answer.
I will take some time this week-end to fix the failing CS check (fabbot.io)
and try to create some unit-test. Is there a test concerning the
login_throttling feature or configuration ? I haven't find anything about
that in the existing tests (and it's why I didn't implement it).
Thanks,

2021-01-22 11:28 UTC, wouterj commented
Hi! We have a functional test for login throttling here: https://github.com/symfony/symfony/blob/5.x/src/Symfony/Bundle/SecurityBundle/Tests/Functional/FormLoginTest.php#L115

2021-02-06 12:29 UTC, damienfa commented
Hello @wouterj , as discussed I've added some functional test (improved the existing one [here](https://github.com/damienfa/symfony/commit/9de6edf8d5bd40083f23cf4bfd36ac0637e65892) with an interval and two more login attempt). Also, [I've fixed](https://github.com/symfony/symfony/pull/39927/commits/752da9b70fa31c02379d3a914bf5fdc6c69c84d1) the fabbot.io check (it was due to a trailing space). 

However, the Integration test (7.4) is failing, but I don't understand which relation it has with my commit 🤷🏻‍♂️   Any help ?

2021-02-06 12:31 UTC, wouterj commented
No worries! The failures also occur in the `5.x` branch: https://github.com/symfony/symfony/runs/1840808458 So they are certainly not your fault :) 

I'll checkout this PR somewhere the coming days. Thanks for your update!

2021-02-16 09:12 UTC, maxhelias approved these changes

2021-02-16 09:53 UTC, wouterj approved these changes
2 minor comments, looks good otherwise!

2021-02-16 09:53 UTC, wouterj commented on src/Symfony/Bundle/SecurityBundle/CHANGELOG.md
> +dev
```suggestion
5.3
```

2021-02-16 09:53 UTC, wouterj commented on src/Symfony/Bundle/SecurityBundle/CHANGELOG.md
> + * Added a `login_throttling.interval` (in `security.firewalls`) to permits easily to change the throttling interval.
```suggestion
 * Add a `login_throttling.interval` (in `security.firewalls`) option to change the default throttling interval.
```

(not really important, but for any future contributions: we recently changed/formalized changelog conventions, see https://symfony.com/doc/current/contributing/code/conventions.html#writing-a-changelog-entry )

2021-02-24 19:25 UTC, Nyholm requested changes
Thank you for this PR. This is great!

Could you fix the minor things so this can be merged in 5.3?

2021-02-24 19:25 UTC, Nyholm commented on src/Symfony/Bundle/SecurityBundle/Tests/Functional/FormLoginTest.php
> +    public function testLoginThrottling(string $username, string $password, int $attempt_index)
Let's use `$attemptIndex` instead.

2021-03-01 06:11 UTC, Nyholm commented
Thank you. 

1. Fabbot needs to be happy. If you rebase your PR on branch 5.x, it should be green. 
2. This is a feature, we do need a changelog entry on the SecurityBundle.

2021-03-01 23:39 UTC, damienfa commented
Sorry, I have to close this merge request. Following [this comment](https://github.com/symfony/symfony/pull/39927#issuecomment-787675178) I needed to rebase on branch 5.x. 
Unfortunately, the "rebase" goes a way I've never experienced (it runs in a loop of conflicts and useless merge). 
To do this, I simply created [a new PR (see here)](https://github.com/symfony/symfony/pull/40339) from this one. It's more readable, clearer.

2021-03-01 23:39 UTC, closed without merging