[DependencyInjection] Add ContainerConfigurator::compilerPass() to al…
symfony/symfony pull request #40355
Opened 2021-03-03 20:37 UTC by jwillp

…low specifying compiler passes

| Q             | A
| ------------- | ---
| Branch?       | 5.x for features
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #35554
| License       | MIT
| Doc PR        |

As discussed in #35554 this PR adds  `ContainerConfigurator::compilerPass()` in order to allow to add compiler passes to the container using the `ContainerConfigurator`.

2021-03-03 21:37 UTC, derrabus requested changes
Thank you for your PR. Can you please add tests for your change?

2021-03-03 22:50 UTC, jwillp commented
@derrabus I would gladly do so but haven't found any tests related to the `ContainerConfigurator`, could you point me out where to find them?

2021-03-10 08:51 UTC, nicolas-grekas commented
The more I read the original issue, the more I think that bundles are the appropriate way to create modules.

In the linked issue, you state that you want defaults: this is done by instantiating a PhpFileLoader in a bundle's load() method (see FrameworkExtension for an example).

You also write that "the bundle approach would not work for projects that use the DI component as a standalone library outside of Symfony.", but you examples all use the HttpKernel component, which is the one that provides the bundle system. It can be used standalone.

I made this proposal to add this method but having taken time to look closer at the code, I think that this ContainerConfigurator should keep its focus on being another format to define DI config, and that it should be very close to what yaml/xml/etc formats provide.

For modules, I don't see why bundles wouldn't be a fit, even in your case.

2021-03-10 16:43 UTC, jwillp commented
@nicolas-grekas  Doing the same in the bundle system requires quite a lot of boilerplate code which gives a tedious DX.
Bundles don't have direct access to the `ContainerConfigurator`, and as you said, in order to be able to use it, one needs
to create an extension for the bundle, then load the configuration in yet a third file using the `PhpFileLoader`.

In essence:
1. Create a Bundle Class and link the extension class
1. Create an Extension Class and implement loading using the `PhpFileLoader`
1. Create a PHP file for the configuration.
1. Register the bundle in the `config/bundles.php` file.

All these steps are only for wiring things up so one can end up configuring the container.

It also means that part of the work of a bundle on the container is inside the `services.php` file for the service definitions
and another part is either in the bundle or the extension for compiler passes.

My experience might be very limited compared to yours, but usually my use of compiler passes and the way the services are defined
often change together, so it makes sense to have them close.

The bundle system makes a lot of sense for reusable code across multiple projects by forcing a standard approach that is easy to comprehend, but not so much for code that is specific to a single project.

The reason I wanted to go with a custom "Module" system instead of bundles was that it is quite a lot of work
for a simple task, i.e. Define the dependencies of an isolated part of the application.

What I had come up with was the following:

1. Create a `ModuleConfigurator` class with a method `configureContainer(ContainerConfigurator $container)`
1. In the kernel, instantiate a ModuleConfigurator class in the configure method and simply: `$module->configureContainer($container)`.

This ends up being a lot simpler and keeps all things container-related grouped together in a single bootstrapping class.

>  made this proposal to add this method but having taken time to look closer at the code, I think that ContainerConfigurator should keep its focus on being another format to define DI config and that it should be very close to what yaml/xml/etc formats provide

I fail to see how this would break this contract of being very close to the other formats.  The container is for specifying dependencies in a unified way, yet, some of its dependencies have to be set up differently (compiler passes) and in another location. Aren't compiler passes still a form of configuration of the container?

2021-04-11 21:02 UTC, nicolas-grekas commented
#40600 will allow getting the container by type-hinting it, wouldn't this solve your usecase?

2021-04-12 09:04 UTC, nicolas-grekas commented
When using the PHP-DSL, the ContainerBuilder is passed as a 2nd argument to the configuration closure:

`return function (ContainerConfigurator $cc, ContainerBuilder $cb) {`

Doesn't that solve your use case?

2021-06-29 19:28 UTC, jwillp commented
@nicolas-grekas Is is it available directly from the Kernel? In my case, I am loading configuration classes from there rather than using closures.

2021-08-01 17:33 UTC, OskarStark commented
friendly ping @nicolas-grekas , thanks

2021-09-08 09:56 UTC, nicolas-grekas commented
> Is is it available directly from the Kernel? In my case, I am loading configuration classes from there rather than using closures.

I don't think so from the kernel: configureContainer should accept either a `ContainerConfigurator` or a `ContainerBuilder`, not both. We could allow passing both objects. PR welcome if you wan to give it a try.

That being said, I had a look at https://github.com/Morebec/orkestra-symfony-bundle/ and I think there might be something to improve in the design there: a bundle should not ship a kernel.

I get that's the way you managed to hook your module system, but I'd suggest looking for another approach instead. I can think of two and can't really decide which one would work or fit in the end:
- load modules in some `config/packages/orkestra.php` file which could be provided by a recipe, there you have the ContainerBuilder
- load modules in the bundle, aka in OrkestraSymfonyExtension, where you have acces to another ContainerBuilder.

An alternative that requires less changes on your side might be to call `$loader->load(function (ContainerBuilder $container) use ($loader) {...` in your `configureContainer()`method, which is already passed with a loader as second argument. See `MicroKernelTrait` for inspiration.

I'm going to close here because I'm not convinced that the described use case fits the purpose of `ContainerConfigurator`, and because I think the module system could be integrated in a more conventional way.

2021-09-08 09:56 UTC, closed without merging

2021-09-13 07:40 UTC, nicolas-grekas commented
For the record, I'm proposing to add a 3rg `ContainerBuilder` argument to `configureContainer` in #42991, that should help with your use case.