[Notifier][OvhCloud] Add "sender"
symfony/symfony pull request #40377
Opened 2021-03-05 12:37 UTC by notFloran

| Q             | A
| ------------- | ---
| Branch?       | 5.x 
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | symfony/symfony-docs#...  (I'm waiting to see if the feature is accepted )

Add "sender" option to the DSN that allows configuring the sender of the message.

OVHCloud manages two cases for sending sms according to the [doc](https://docs.ovh.com/fr/sms/envoyer_des_sms_avec_lapi_ovh_en_php/):

> The senderForResponse parameter will allow the use of a short number, which allows you to send SMS directly without having to create an alphanumeric sender (for example: your name).
> Short numbers also allow you to receive responses from the recipients of your SMS, which can be useful for a satisfaction survey, a voting application, a game, etc. 

![CleanShot 2021-03-05 at 13 26 33](https://user-images.githubusercontent.com/523981/110115554-84c5af80-7db6-11eb-815d-7e8bafa81e5d.png)

This PR introduces the management of these 2 cases with a new option `sender`:
* if `sender` is set, we use it
* if `sender` is not set, we use `senderForResponse` to get a short number (current behavior)

I took the logic implementedin the old official SDK : https://github.com/ovh/php-ovh-sms/blob/52d279e112a7da8f897745acab32a887321e03f1/src/Message.php#L161

2021-03-05 13:19 UTC, OskarStark commented on src/Symfony/Component/Notifier/Bridge/OvhCloud/README.md
> +OVHCLOUD_DSN=ovhcloud://APPLICATION_KEY:APPLICATION_SECRET@default?consumer_key=CONSUMER_KEY&service_name=SERVICE_NAME&SENDER=SENDER
```suggestion
OVHCLOUD_DSN=ovhcloud://APPLICATION_KEY:APPLICATION_SECRET@default?consumer_key=CONSUMER_KEY&service_name=SERVICE_NAME&sender=SENDER
```

2021-03-05 13:19 UTC, OskarStark commented on src/Symfony/Component/Notifier/Bridge/OvhCloud/CHANGELOG.md
> + * Add "sender" option to the DSN that allows configuring the sender
```suggestion
 * Add `sender` option to the DSN that allows configuring the sender
```

2021-03-05 13:20 UTC, OskarStark commented on src/Symfony/Component/Notifier/Bridge/OvhCloud/OvhCloudTransport.php
> +    public function __construct(string $applicationKey, string $applicationSecret, string $consumerKey, string $serviceName, string $sender = null, HttpClientInterface $client = null, EventDispatcher
Unfortunately this is a BC break, so we need to use a `setSender()` method.

2021-03-05 13:20 UTC, OskarStark requested changes
Please see my comments

2021-03-06 08:17 UTC, OskarStark reviewed
Afterwards good to go 👍🏻

2021-03-06 08:17 UTC, OskarStark commented on src/Symfony/Component/Notifier/Bridge/OvhCloud/Tests/OvhCloudTransportTest.php
> +    public function createTransport(?HttpClientInterface $client = null, string $sender = null): TransportInterface
```suggestion
    public function createTransport(?HttpClientInterface $client = null, ?string $sender = null): TransportInterface
```

For consistency

2021-03-06 08:30 UTC, fabpot approved these changes

2021-03-06 08:31 UTC, fabpot commented
Thank you @notFloran.

2021-03-07 11:52 UTC, fabpot approved these changes

2021-03-07 11:53 UTC, closed without merging