Change JsonResponse default encoding options
symfony/symfony pull request #40409
Opened 2021-03-08 00:22 UTC by MrPropre

| Q             | A
| ------------- | ---
| Branch?       | 5.2
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | yes? I'm not sure about that
| License       | MIT

The use of `JSON_HEX_TAG`, `JSON_HEX_APOS`, `JSON_HEX_AMP` and `JSON_HEX_QUOT` flags in the `json_encode` function does not convert <, >, ', &, and " characters into HTML entities but encode them into Unicode characters, which does absolutely not make the JSON safer to be embedded into HTML, but makes it unreadable for a browser.
Example in an HTML page: `&amp;` (HTML entity of "&") outputs `&` but `\u0026` (Unicode translation of "&") outputs `\u0026`.

Also, by using JavaScript to get the data from an API endpoint, the JSON data is parsed and all Unicode characters are automatically converted to normal characters. RFC 7159 allows any character in a JSON string to be escaped, so the JSON parser knows that any character could have been escaped or converted to Unicode.

In this case, these flags are absolutely unnecessary and make the JSON response bigger to load due to the unnecessary added characters.

**If you really want to write JSON data directly to HTML, you can use the `htmlspecialchars` function to make it safe to be embedded.**

These flags have been originally added here to write JSON data directly to JavaScript (and not directly to HTML), which is a bad practice.
Example:
```php
<script>
    var data = <?= json_encode(['data' => 'my data']) ?>
</script>
```
This is very insecure as it could be a potential SQL injection vulnerability. So we need to add flags to escape special characters.
```php
<script>
    var data = <?= json_encode(['data' => '</script>insecure data'], JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT) ?>
</script>
```
But this is still a bad practice and should be replaced by one of these solutions:
- Use AJAX to get the data you need from the server.
- Echo the data into the page somewhere, and use JavaScript to get the information from the DOM.

**If you really want to keep this bad practice with Symfony, you can call the `setEncodingOptions` method of JsonResponse to manually set the flags.**

2021-03-08 08:40 UTC, Nyholm commented
Thank you for this PR. 
If we merge this now, it will break all the existing applications that is relying on this feature. That would be a horrible user experience. Is there a way to achieve the same goals you want to achieve but with no BC breaks?

> This is very insecure as it could be a potential SQL injection vulnerability.

Could you elaborate how this is? As long as you are checking the raw input in your backend, it does not matter to much what a javascript variable in the frontend contains. 

------

Im sorry if I don't really understand this. But what is the benefit of changing this value to zero? I only see that you think the current value is bad.

2021-03-08 09:17 UTC, derrabus requested changes
The problem with defaults is not matter what default you pick, someone won't be happy and suggest a different one. The `JsonResponse` class does have a `setEncodingOptions()` method that allows you to set different flags for the `json_encode()` function.

Changing the default in a backwards compatible way is possible, but it's a bit more complicated than the change you are suggesting here. As @Nyholm sais, we really need a very good reason to do this.

2021-03-08 17:03 UTC, MrPropre commented
I will try to rephrase.
The first problem I saw was the documentation related to the `DEFAULT_ENCODING_OPTIONS` constant. It is written that the flags used allow JSON to be embedded in HTML content in a secure manner. However, to do this, you normally have to encode special characters in HTML entities (cf: htmlspecialchars function), which are recognized by browsers. This is not what these flags do, since they encode special characters in Unicode characters, which are not recognized by browsers and therefore will not be replaced by their associated character when displayed by browsers.
Certainly, the data is secure, since it no longer contains special characters, but the data is no longer transposable to HTML at all, since it contains Unicode characters instead of HTML entities.

> Could you elaborate how this is? As long as you are checking the raw input in your backend, it does not matter to much what a javascript variable in the frontend contains.

The problem here is that the backend verification is done with the json_encode function, while that is not its role. PHP already has its own functions to secure HTML (htmlspecialchars & htmlentities).

> Im sorry if I don't really understand this. But what is the benefit of changing this value to zero? I only see that you think the current value is bad.

Indeed, it is quite possible to keep the flags as such, since the final JSON still respects the RFC.
But, I think you should take into consideration some facts:
- Documentation is wrong
- Flags are used in a wrong way
- Since these flags are not needed here, their use increases the weight of JSON responses and potentially slows down APIs, for example

Also, zero is the default value for the encoding parameter in the json_encode function, and is used by many frameworks as a default encoding option.

2021-03-09 23:28 UTC, jderusse commented
Closing this PR as explained in previous comment, it's a BC break, and would introduce vulnerabilities in applications that relies on this default option.

This default option has been defined on purpose to mitigate XSS. Even if PHP provides functions to protect agains XSS, having this default option is still the best solution:
- It protects the user that forget to escape the output of `json_encode`.
- It provides a valid JSON/Javascript output. While calling `htmlspecialchars(json_encode($data, 0))` would break the application that don't expect to get `&quot;` to delimit strings.
- it escapes NON-ANSI chars and provide a string that don't need to define a charset to be parsed.

> but the data is no longer transposable to HTML at all

IMHO People that need to display JSON to string is the edge case, and these people should use `setEncodingOptions` with the desired options.

Note: I think you mixed SQL Injection and XSS in description/comments, which confused @Nyholm

2021-03-09 23:28 UTC, closed without merging