[Cache] Support a custom serializer in the ApcuAdapter class
symfony/symfony pull request #40602
Opened 2021-03-27 23:07 UTC by ste93cry

| Q             | A
| ------------- | ---
| Branch?       | 5.x
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #40523
| License       | MIT
| Doc PR        | n/a

Unlike some other cache adapters like the one for Redis, the APCu adapter does not support a custom serializer. Even though most things can be stored as-is in this cache, some others like resources cannot

2021-03-27 23:26 UTC, chalasr requested changes

2021-03-27 23:26 UTC, chalasr commented on src/Symfony/Component/Cache/Adapter/ApcuAdapter.php
> +     */
```suggestion
```

We don't add phpdoc on properties, it's inferred from the constructor by static analysers and most IDEs.

2021-03-27 23:26 UTC, chalasr commented on src/Symfony/Component/Cache/CHANGELOG.md
> + * added support for a custom serializer to the `ApcuAdapter` class
```suggestion
 * add support for a custom serializer to the `ApcuAdapter` class
```

that's our new convention

2021-03-27 23:33 UTC, ste93cry commented
Build failure seems unrelated, while I'm not sure what to do with Psalm, while it's definitely right, the code that I added is just mostly a copy-paste from other adapters and it doesn't complain about them 🤔

2021-03-27 23:34 UTC, chalasr approved these changes

2021-03-28 00:02 UTC, Nyholm approved these changes
Awesome. Thank you!

2021-03-28 06:25 UTC, fabpot approved these changes

2021-03-28 06:30 UTC, fabpot commented
Thank you @ste93cry.

2021-03-28 06:30 UTC, merged