[HttpKernel][FrameworkBundle] use TestLogger in test env
symfony/symfony pull request #40621
Opened 2021-03-29 09:07 UTC by GaryPEGEOT

| Q             | A
| ------------- | ---
| Branch?       | 5.x
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | 
| License       | MIT
| Doc PR        | TODO

In test env, use `TestLogger` when available. Allow to easily test if some informations have been logged:
```php
// Inside a WebTestCase:
$this->assertTrue(static::$container->get('logger')->hasWarningThatContains('Foo'));
```

2021-03-29 10:02 UTC, derrabus requested changes
The problem with this change is that HttpKernel does not have an opinion on how you name your environments. Using `test` for testing is merely a recommendation.

Maybe a recipe would be better suited for this kind of feature?

2021-03-30 07:49 UTC, GaryPEGEOT commented
> Maybe a recipe would be better suited for this kind of feature?

What would be the best way inside a recipe ? create a `services_test.yaml` and define a `logger` service inside it ?

2021-03-31 20:20 UTC, Nyholm commented
Sorry if Im a bit slow. 

I undertand that you want to use a logger service in your tests. I assume that you have modified your `services_test.yaml` to achieve that. But what I don't understand is why we need to make any changes to the Symfony core. 

Could you please elaborate on this?

2021-03-31 20:41 UTC, GaryPEGEOT commented
Hi @Nyholm !

I don't think really needed per say, but I do think it would be a nice addition. Assuming the following scenario and that monolog is not installed. (ie fresh install):


```php
<?php

namespace App;

class MyAwesomeService {
     public function __invoke(Request $request): SomeResult
    {
        try {
            //something
        } catch(\Exception) {
            $this->logger->warning('bla bla');
        }
    }
}
```
1. we can see in the phpunit.xml.dist `<server name="SHELL_VERBOSITY" value="-1"/>`, which prevent logs from showing up in the CLI. So default logger is not super useful in test env.
2. Here, if I want to test that something was logged, I have to use the profiler, which is not a big deal, but slows down a bit the test.

So the goal of the PR is to provide a convenient way to test what's logged, out of the box. But I do agree creating a `services_test.yaml` file to achieve this is not super complicated.

2021-03-31 20:55 UTC, Nyholm commented
I think your use case is valid.

I am not known for writing a lot (or good) tests. I have never tested the actual values added to the log. If I would test this I think a unit test would do. 

Nevertheless, I dont think we need to make any changes here. As you say, two extra lines in `services_test.yaml`  will do for any user with this situation. That will also have the added benefit of not hard coding the environment name as @derrabus is pointing out.

2021-03-31 21:17 UTC, GaryPEGEOT commented
OK, I get your points. Thanks for the feedback !

2021-03-31 21:17 UTC, closed without merging