LoginLink create get Request Locale
symfony/symfony pull request #40641
Opened 2021-03-30 14:05 UTC by roromix

| Q             | A
| ------------- | ---
| Branch?       | 5.x
| Bug fix?      | yes
| New feature?  | yes
| Deprecations? | no
| License       | MIT
| Doc PR        | symfony/symfony-docs#15163

While writing the documentation for PR#40153 I noticed that the RequestContext :: fromRequest method does not add the '_locale' parameter automaticaly. This new pull request to set _locale parameter to the RequestContext.

2021-03-30 14:28 UTC, chalasr commented
Thanks for the follow-up @roromix. 
Could you add a test case (or update an existing one) for this?

2021-03-30 14:47 UTC, roromix commented
> Thanks for the follow-up @roromix.
> Could you add a test case (or update an existing one) for this?

I have updated provider

2021-03-31 19:53 UTC, Nyholm requested changes
Thank you. 

You are the best. Writing docs and patching bugs. 

I agree with this PR and I do like the changes in `LoginLinkHandler`. But you need to update the test. I will pass even without any modifications to `LoginLinkHandler`.

2021-04-01 12:23 UTC, Nyholm commented
If I copy the tests you written (without the changes in `LoginLinkHandler`), they will still run an be green. You need to write a test that will only pass if your patch for `LoginLinkHandler` is applied.

2021-04-01 13:19 UTC, roromix commented
> If I copy the tests you written (without the changes in `LoginLinkHandler`), they will still run an be green. You need to write a test that will only pass if your patch for `LoginLinkHandler` is applied.

Sorry, i have no idea how to do that. Need help

2021-04-01 14:05 UTC, chalasr commented
Here is a patch covering this change:
```diff
diff --git a/src/Symfony/Component/Security/Http/Tests/LoginLink/LoginLinkHandlerTest.php b/src/Symfony/Component/Security/Http/Tests/LoginLink/LoginLinkHandlerTest.php
index 03dd0287d7..12b8f7da4a 100644
--- a/src/Symfony/Component/Security/Http/Tests/LoginLink/LoginLinkHandlerTest.php
+++ b/src/Symfony/Component/Security/Http/Tests/LoginLink/LoginLinkHandlerTest.php
@@ -69,7 +69,12 @@ class LoginLinkHandlerTest extends TestCase
         if ($request) {
             $this->router->expects($this->once())
                 ->method('getContext')
-                ->willReturn(new RequestContext());
+                ->willReturn($currentRequestContext = new RequestContext());
+
+            $this->router
+                ->expects($this->exactly(2))
+                ->method('setContext')
+                ->withConsecutive([$this->equalTo((new RequestContext())->fromRequest($request)->setParameter('_locale', $request->getLocale()))], [$currentRequestContext]);
         }
 
         $loginLink = $this->createLinker([], array_keys($extraProperties))->createLoginLink($user, $request);
@@ -78,19 +83,15 @@ class LoginLinkHandlerTest extends TestCase
 
     public function provideCreateLoginLinkData()
     {
-        $request = Request::create('https://example.com');
-        $request->setLocale('en');
-
         yield [
             new TestLoginLinkHandlerUser('weaverryan', 'ryan@symfonycasts.com', 'pwhash'),
             ['emailProperty' => 'ryan@symfonycasts.com', 'passwordProperty' => 'pwhash'],
-            $request,
+            Request::create('https://example.com'),
         ];
 
         yield [
             new TestLoginLinkHandlerUser('weaverryan', 'ryan@symfonycasts.com', 'pwhash'),
             ['emailProperty' => 'ryan@symfonycasts.com', 'passwordProperty' => 'pwhash'],
-            Request::create('https://example.com'),
         ];
 
         yield [
```

2021-04-01 14:48 UTC, roromix commented
I still have a lot to learn about the Tests
Thank you @chalasr

2021-04-01 19:36 UTC, Nyholm approved these changes
Thank you

2021-04-02 06:13 UTC, fabpot approved these changes

2021-04-02 06:14 UTC, fabpot commented
Thank you @roromix.

2021-04-02 06:14 UTC, merged