[PropertyInfo] Make ReflectionExtractor correctly extract nullability
symfony/symfony pull request #40699
Opened 2021-04-03 13:35 UTC by shiftby

| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #40659
| License       | MIT
| Doc PR        | no

When the property had a default value ReflectionExtractor was always returning isNullable: false. After PHP 7.4 we can get isNullable from the typehint.

2021-04-03 22:35 UTC, derrabus requested changes
Thank you for working on this issue.

What bothers me about your solution is that you have taught a method named `extractFromDefaultValue()` how to extract the desired information from the property type declaration. Now, the method doesn‘t do anymore what its name suggests.

Then again, there is a method named `extractFromReflectionType()` that already does what you‘re trying to achieve.

2021-04-04 09:24 UTC, shiftby commented
@derrabus, thank you for the review.

I agree that currently `extractFromDefaultValue()` knows more than only how to get the type from the default value. I did that because after PHP 7.4 it's no longer possible to correctly get property nullability from the default value.

Before this version, I tried to copy nullability from the `extractFromReflectionType()` result, but we can't do it since Type objects are not editable.

Then I was thinking about the following code, but it's harder to understand and we would also need to change `extractFromDefaultValue()` method arguments. And even more, currently, we know that a nullability of all `Type`s in the `$fromReflectionType` is the same, but probably it can change in the future, so using the nullability of the first one is not the best option.
```php
public function getTypes($class, $property, array $context = []): ?array
{
    ...
    $isNullable = false;
    $fromReflectionType = null;
    if (\PHP_VERSION_ID >= 70400) {
        try {
            $reflectionProperty = new \ReflectionProperty($class, $property);
            $type = $reflectionProperty->getType();
            if (null !== $type && $fromReflectionType = $this->extractFromReflectionType($type, $reflectionProperty->getDeclaringClass())) {
                $isNullable = isset($fromReflectionType[0]) && $fromReflectionType[0]->isNullable();
            }
        } catch (\ReflectionException $e) {
            // noop
        }
    }

    if ($fromDefaultValue = $this->extractFromDefaultValue($class, $property, $isNullable)) {
        return $fromDefaultValue;
    }

    if ($fromReflectionType) {
        return $fromReflectionType;
    }

    return null;
}
```


Another solution would be to replace part of the current version of `getTypes()`.
```php
...
if ($fromDefaultValue = $this->extractFromDefaultValue($class, $property)) {
    return $fromDefaultValue;
}

if (\PHP_VERSION_ID >= 70400) {
    ...
    return $this->extractFromReflectionType($type, $reflectionProperty->getDeclaringClass())) {
    ...
}

return null;
```
With
```php
...
if ($fromPropertyDeclaration = $this->extractFromPropertyDeclaration($class, $property)) {
    return $fromPropertyDeclaration;
}

return null;
```
and
```php
public function extractFromPropertyDeclaration(string $class, string $property) {
    // calculate nullability
    // try to get from the default value
    // try to get from the property type, if PHP >= 7.4
    // else null
}
```

What do you think about these solutions?

2021-04-04 12:41 UTC, derrabus commented
Okay, but if we have a typed property – why would we want to look at the default value at all? Wouldn't it be enough to prioritize the property type over the default value when extracting type information? Or am I missing something?

2021-04-04 14:32 UTC, shiftby commented
I did some research on why typehint extraction is at the end. Typehint support was initially added in #34557, and it had the highest priority. And then in #38041 it was moved to the end of the method. After this issue was merged, in one of the comments, issue #38416 was mentioned.

I'm not sure if in this issue we should focus on property type priority versus constructor, mutator, and accessor. But I believe we can change the code so it uses property typehint on PHP 7.4 and a default value for older versions.

2021-04-05 09:13 UTC, derrabus approved these changes

2021-04-05 11:19 UTC, dpinheiro commented
> I did some research on why typehint extraction is at the end. Typehint support was initially added in #34557, and it had the highest priority. And then in #38041 it was moved to the end of the method. After this issue was merged, in one of the comments, issue #38416 was mentioned.
> 
> I'm not sure if in this issue we should focus on property type priority versus constructor, mutator, and accessor. But I believe we can change the code so it uses property typehint on PHP 7.4 (and default value if there's no typehint) and a default value for older versions.
> 
> I don't think we're missing something, it's not possible to have a default value different from typehint.

I would like to take this opportunity to discuss this priority if possible. In my point of view #38041 introduced a BC break as serializer started having a different behaviour, and currently this in an impediment for me to update some of my projects, as described in https://github.com/symfony/symfony/issues/38416 would say that pretty "normal" classes stopped working due to that change. Do you think we could change this order? I'm available to help with that

2021-04-07 15:32 UTC, derrabus commented
@dpinheiro I understand that the issue you've mentioned is important to you. But please let's leave the discussion on that ticket.

2021-05-07 13:22 UTC, nicolas-grekas approved these changes

2021-05-07 13:22 UTC, nicolas-grekas commented
Thank you @shiftby.

2021-05-07 13:22 UTC, merged