[Cache] [FrameworkBundle] Fix logging for TagAwareAdapter
symfony/symfony pull request #40740
Opened 2021-04-08 12:15 UTC by fancyweb

| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | https://github.com/symfony/symfony/issues/40108
| License       | MIT
| Doc PR        | -

2021-04-08 12:40 UTC, fancyweb commented
Do we want to bump the required minimum symfony/cache version in FWB for this or add a runtime check?

2021-04-09 14:44 UTC, v-m-i requested changes
Hi @fancyweb, thank you for this PR. 

Kudos for detailed and readable tests.
 
I have added one typo-fix suggestion. Everything else looks good :)

Besides code, I see that some builds have failed so I would suggest looking into that.

2021-04-09 14:44 UTC, v-m-i commented on src/Symfony/Component/Cache/Tests/Adapter/TagAwareAdapterTest.php
> +        // Computing will produces at least one log
```suggestion
        // Computing will produce at least one log
```

2021-04-09 17:36 UTC, nicolas-grekas approved these changes
(once the typo is fixed)

2021-04-11 17:12 UTC, fancyweb commented on src/Symfony/Component/Cache/LockRegistry.php
> +        $key = self::$files ? abs(crc32($item->getKey())) % \count(self::$files) : -1;
> Because PHP's integer type is signed many crc32 checksums will result in negative integers on 32bit platforms.

2021-04-11 17:14 UTC, fancyweb commented
Tests are green :tada:

2021-04-11 17:20 UTC, nicolas-grekas commented
Thank you @fancyweb.

2021-04-11 17:20 UTC, merged

2021-05-14 03:48 UTC, glensc commented on src/Symfony/Component/Cache/LockRegistry.php
> +        $key = self::$files ? abs(crc32($item->getKey())) % \count(self::$files) : -1;
I find it better to use `sprintf('%u')`