[Form] Don't directly cast objects to string from choice_label callable result
symfony/symfony pull request #40759
Opened 2021-04-10 13:46 UTC by alexandre-daubois

It leads to loss of information because it'll use `__toString` to cast, which is incompatible with newly added `TranslatableMessage`, for example.

| Q             | A
| ------------- | ---
| Branch?       | 5.2 
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #40622 
| License       | MIT
| Doc PR        | _none_

So this one's a bit tricky in my mind. I didn't want to check if `$dynamicLabel instanceof TranslatableMessage`, because of course it doesn't belong to the same component.

Aside, it would sound so strange to me to add `|object` to `$label` here: https://github.com/symfony/symfony/blob/bb1e1e58aea5318e96d1c22cc8a91668ed7baaaa/src/Symfony/Component/Form/ChoiceList/View/ChoiceView.php#L40

But maybe that's the way to go? Requiring your help here. I'm fully open to your ideas, as we're loosing a big feature here by losing `TranslatableMessage` translation parameters.

If the passed object doesn't implement `__toString`, it'll lead to an exception during template rendering, as expected.

2021-04-10 17:12 UTC, yceruto requested changes
Adding a specific check against TranslatableMessage wouldn't a problem from my point of view and it would be better than allowing non-stringable objects from here.

2021-04-10 17:12 UTC, yceruto commented on src/Symfony/Component/Form/ChoiceList/Factory/DefaultChoiceListFactory.php
> +            $label = false === $dynamicLabel ?: (\is_object($dynamicLabel) ? $dynamicLabel : (string) $dynamicLabel);
Nested ternary operator should not be used (maintainability issues)

2021-04-10 17:12 UTC, yceruto commented on src/Symfony/Component/Form/ChoiceList/Factory/DefaultChoiceListFactory.php
> +            $label = false === $dynamicLabel ?: (\is_object($dynamicLabel) ? $dynamicLabel : (string) $dynamicLabel);
```suggestion
            if (false === $dynamicLabel) {
                $label = false;
            } elseif ($dynamicLabel instanceof TranslatableMessage) {
                $label = $dynamicLabel;
            } else {
                $label = (string) $dynamicLabel;
            }
```

2021-04-10 17:17 UTC, yceruto commented
https://github.com/symfony/symfony/blob/bb1e1e58aea5318e96d1c22cc8a91668ed7baaaa/src/Symfony/Component/Form/ChoiceList/View/ChoiceView.php#L40

and yes, I would update the docblock to add TranslatableMessage too.

2021-04-11 18:08 UTC, alexandre-daubois commented
Thank you so much @yceruto for your advice. I updated the code thanks to your suggestions and edited the PR title as well.

2021-05-07 14:02 UTC, nicolas-grekas approved these changes
(I fixed deps=low tests by skipping the test case there)

2021-05-07 14:02 UTC, nicolas-grekas commented
Thank you @alexandre-daubois.

2021-05-07 14:02 UTC, merged