[PasswordHasher] fix copy paste typos from UserPasswordEncoderInterface
symfony/symfony pull request #40915
Opened 2021-04-22 21:00 UTC by mhujer

| Q             | A
| ------------- | ---
| Branch?       | 5.x
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no 
| License       | MIT

Fix typos introduced when extracting the PasswordHasher component from `UserPasswordEncoderInterface` https://github.com/symfony/symfony/blob/abeb8e4ca9adfcc1494df22af9fd9a1c0181b532/src/Symfony/Component/Security/Core/Encoder/UserPasswordEncoderInterface.php#L36

Discovered in 5.3.0BETA1.

2021-04-23 08:08 UTC, chalasr requested changes
Good catch!

2021-04-23 08:08 UTC, chalasr commented on src/Symfony/Component/PasswordHasher/Hasher/UserPasswordHasherInterface.php
> + * @method bool   needsRehash(PasswordAuthenticatedUserInterface $user)                            Checks if an encoded password would benefit from rehashing.
```suggestion
 * @method bool   needsRehash(PasswordAuthenticatedUserInterface $user)                            Checks if a hashed password would benefit from rehashing.
```

2021-04-24 06:12 UTC, OskarStark approved these changes

2021-04-24 14:04 UTC, chalasr approved these changes

2021-04-25 06:41 UTC, fabpot approved these changes

2021-04-25 06:41 UTC, fabpot commented
Thank you @mhujer.

2021-04-25 06:41 UTC, merged