expose references detected in inline notation structures
symfony/symfony pull request #40989
Opened 2021-04-29 15:01 UTC by nicolas-grekas

| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #40835
| License       | MIT
| Doc PR        | -

Google decided that FLoC should be opt-out, but web communities are opposing this idea.

Instead, I think we should make FLoC opt-in in Symfony. Since FLoC did not exist before, this PR doesn't change anything in terms of BC from the HTTP pov for Symfony apps. I'm therefor submitting this as a bugfix: to keep things working as always.

Ppl that want to opt-in for FLoC can easily do so by writing a listener.

2021-04-29 15:03 UTC, fabpot approved these changes

2021-04-29 15:05 UTC, derrabus approved these changes

2021-04-29 15:13 UTC, dunglas approved these changes

2021-04-29 15:18 UTC, Kleinast commented
> Google decided that FLoC should be opt-out, but web communities are opposing this idea.

Isn't it opt-int by default that google decided ?

> Instead, I think we should make FLoC opt-in in Symfony. Since FLoC did not exist before, this PR doesn't change anything in terms of BC from the browser-side pov for Symfony apps. I'm therefor submitting this as a bugfix: to keep things working as always.

Isn't it opt-out that you want by default ?

2021-04-29 15:19 UTC, wouterj commented
I'm definitely -1 here. It's not up to us to determine how our users should consider privacy or how internet standards should be done. Symfony has always been great to *not* force any opinion and to follow internet standards everywhere we can.

Doing so can also lead to quite some confusion: "Online docs tell me that this is opt-out. We haven't opt-out from it, why isn't our site using it?!"

> Since FLoC did not exist before, this PR doesn't change anything in terms of BC from the browser-side pov for Symfony apps.

I don't agree here either. It does change "disable floc" to "enable floc" (that's the whole point of this PR). Doing so needs to be documented clearly to any users of the framework. In that regard, it is breaking BC.

Also, nobody knows if this has other side-effects (like lowering your google ranking). Unless this is fully known, we cannot make this decision for our users.

---

The only leftover thing would be an option to configure this header. But that doesn't make sense, why this header but not others?

There is the [NelmioSecurityBundle](https://github.com/nelmio/NelmioSecurityBundle) adding tons of best-practice headers for security reasons. Ignoring our personal views of the world, I fail to see why Symfony needs to do this for this header, but ignores other "more security-critical" headers.

2021-04-29 15:29 UTC, javiereguiluz commented
I agree with Wouter and I'm `-1` too. Let me explain:

* I'm very happy that all *.symfony.com websites have enabled this feature to block FLoC. It's the right thing to do for Symfony community people and it's OK that we make the decision for them...
* ... but I'm not happy that Symfony framework proposes to make this decision on behalf of all developers and all apps. We don't know what's best for all apps/developers (e.g. some kind of applications such as e-commrece sites probably need to not block FLoC).

2021-04-29 15:46 UTC, dunglas commented
> Symfony has always been great to not force any opinion and to follow internet standards everywhere we can.

Google is the actor forcing the opinion here. FLoC is **not** an internet standard (at least yet, and I hope that it will never become one). It has been rejected by most of the web community (GitHub, Wordpress, Drupal, Svelte, Caddy, Mozilla, Brave, the EFF and many other prominent actors). We are far away from a "rough consensus and running code".

The thing is that the community at large is right to fight to force Google to respect the core values behind the web (which doesn't include tracking and mass surveillance, quite the opposite actually).

> We don't know what's best for all apps/developers (e.g. some kind of applications such as e-commrece sites probably need to not block FLoC).

But we know that tracking and surveillance hurt the fundamental liberties of the end users of Symfony, and are totally opposed to the values of the free software movement.

We also know that FLoC is currently just an experiment, so we don't "hurt" any website by enabling this header. What we do is mostly symbolic, we send a clear message to Google that - as part of the community of the makers of the web - we don't want our tools to hurt the privacy and security of people.

If an e-commerce website want to track its users using FLoC, as free software advocates, we should discourage it. Anyway, with the current patch proposer by Nicolas, do it's very easy to enable FLoC if needed, so I don't see any issue to merge this patch. We just provide sane defaults for the society at whole.

2021-04-29 15:51 UTC, nicolas-grekas commented
From my understanding, this FLoC thing is not a standard in any way. Instead, because Google owns the most-used browser, it's able to skip standard bodies and force a new behavior onto end users. They're basically abusing their dominant position.

The day FLoC will be an approved standard supported by eg Firefox, we might consider respecting the default of the standard web platform. FLoC is not part of it yet.

As such, and as very well explained in [RFC8890](https://tools.ietf.org/html/rfc8890), we should make our decision in the interest of end users.

Mark Nottingham did a fantastic keynote on the topic at last SymfonyCon in December. If you can afford the ticket, I'd really encourage anyone to watch the replay.

2021-04-29 15:52 UTC, mbabker commented
I'm somewhat torn here.  @wouterj and @javiereguiluz said it better than I probably ever can, but I honestly believe that this isn't the type of decision that's appropriate to make at a framework level (if the Sylius team wants to disable it by default, or Drupal, or API Platform, I'm a bit more comfortable with it because that should be an application-level decision and hopefully one that comes with some form of configuration for those who do want FLoC on their site; I don't quite agree with the calls that some have put out suggesting that application frameworks like Symfony, or web server software, should disable it by default).  I don't even run ads or anything that would trigger FLoC on any of my own systems and I've disabled it for my own reasons.

I haven't fully consumed the conversation yet, but there were folks from Google at WordPress's dev chat last week discussing the FLoC topic after their initial proposal went up.  One of the things that I was able to take away from what I've read is that FLoC is only being enabled when a site requests resources that use FLoC, which if that remains true (and as one of their team members said, the code for this is in the OSS Chromium engine so it can be independently audited) means the need to opt-out of FLoC only comes up if your site is shipping resources that use FLoC in the first place.  So a part of me feels like this is a massively premature decision to make at this stage of the FLoC implementation. The people who are going to be hurt the most from a decision this deep in the application stack are going to be folks who can't "just" write an event listener to reverse the framework's decision.

2021-04-29 15:58 UTC, alcaeus commented
I believe that platforms and frameworks have an obligation to protect user privacy. Such a Setting should be an opt-in in the browser. The fact that google wants to exploit people's private data like that calls for big players to push back and oppose such behaviour. Adding this header by default and letting developers decide whether they want to keep it or expose their users to this behaviour is the right way to go here.

2021-04-29 16:00 UTC, t-richard commented
IMHO it shouldn't be a bugfix and should be editable through semantic config instead of having to write a custom listener to override Symfony's own listener.

It's not about whether FLoC is good or bad, it's just about not making it hard for people to enable a feature that would otherwise be enabled by default.

I understand and agree with the opinion and would love to see Symfony making it easy to optin/optout and suggest you to disable it (be it by default, in a Flex recipe or otherwise) but not in a hidden manner like this.

2021-04-29 16:01 UTC, javiereguiluz commented
@mbabker yes, in [this document from WordPress](https://wptavern.com/floc-blocking-discussion-continues-on-wordpress-trac) summarizes it well:

> A page will only be included in the browser’s FLoC computation for one of two reasons:
>
> * The FLoC API document.interestCohort() is used on the page.
> * Chrome detects that the page loads ads or ads-related resources.

To activate FLoC, a website must consciously call `document.interestCohort()` using JavaScript. That makes it "opt-in" to me (neither Google nor users decide if FLoC is used; only the website can decide that).

2021-04-29 16:05 UTC, javiereguiluz commented
@dunglas let me use another example:

* PHP 7.3 ends support (bug and security) [on December 6, 2021](https://www.php.net/supported-versions.php)
* Symfony 5.3 will require `>=7.2.5`

So, in order to protect our users from security threats, let's add a PR that adds a listener in Symfony to do this:

```
if ($today > 'December 6, 2021' and $phpVersion < 7.4.0) {
    throw new \Exception(
        You cannot run Symfony in your app because you are using
        an unsupported PHP version and we\'ve decided to protect
        you and your users.
    );
}
```

We cannot make this decision on behalf of our users ... that's why I think we shouldn't make other decisions, such as the ones related to user privacy.

2021-04-29 16:13 UTC, stof commented
@javiereguiluz Calling `document.interestCohort()` makes you access the cohort identifier. But there is a second part to FLoC: the fact that your browsing activity on the website feeds the algorithm putting you in a cohort.

2021-04-29 16:15 UTC, nicolas-grekas commented
> A page will only be included in the browser’s FLoC computation for one of two reasons: [...]

That is interesting info. Yet this is not binding Google in any way. That's maybe true, and maybe it won't last true.

The `permissions-policy` header is described at https://www.w3.org/TR/permissions-policy-1/ It was written before `interest-cohort` was a thing so of course it describes a generic mechanism, not FLoC. Yet, it's interesting to note that the feature exists to help sites reclaim permissions over modules (eg ad-modules) that they've enabled *by themselves*.

To me, this means that adding a module to a page (eg Google analytics, or any ad-provider) can certainly not be considered enough "opt-in" for website that add these modules. Otherwise, the `permissions-policy` header wouldn't be needed.

With all this considered, and since user privacy is a risk here, I wouldn't be satisfied with the "opt-in" argument.

> there is a second part to FLoC: the fact that your browsing activity on the website feeds the algorithm putting you in a cohort.

:100: what we should prevent: letting Google enable to collect browsing habits by default. Unless a broad consensus is reached on the topic.

2021-04-29 16:24 UTC, wouterj commented
> As such, and as very well explained in RFC8890, we should make our decisions in the interest of end users.

AFAICS (and please correct me if I'm wrong), this RFC is explicitly discussing how IETF should make decisions when there is a conflict. While I think it's a very interesting document to read, it does not add any real backing in decisions like this in Symfony.

> Instead, because Google owns the most-used browser, it's able to skip standard bodies and force a new behavior onto end users. They're basically abusing their dominant position.

It's not clear to me how this change differs from Google's (keeping the privacy thing aside). Bluntly said: isn't this change abusing Symfony's dominant position to fight some conflicting ideological views with Google?

---

Don't get me wrong, I'm personally against FLoC as it's currently described; I'm a strong user of Firefox; and I greatly care about the privacy of users of products I'm working on. However, I think it's wrong to approach this on a framework level. It feels like we're jumping the gun here, following the hype of the moment, rather than keeping in line with the principles and scope of frameworks.

2021-04-29 16:31 UTC, nicolas-grekas commented
@t-richard 

> IMHO it shouldn't be a bugfix and should be editable through semantic config instead of having to write a custom listener to override Symfony's own listener.

I think it should be a bugfix, because this is about preserving the current behavior of the web-platform. Similarly, our policies consider supporting newer PHP versions as a bugfix and this is also about changes in the outer platform Symfony runs (same for the OS.)

About making this simple to disable, I think that's a good idea. I think a DI parameter might be the easiest:
```yaml
parameters:
    kernel.interest_cohort_permissions: * # would be the empty string by default
```

Makes sense?

2021-04-29 16:41 UTC, nicolas-grekas commented
@wouterj 

>AFAICS (and please correct me if I'm wrong), this RFC is explicitly discussing how IETF should make decisions when there is a conflict. While I think it's a very interesting document to read, it does not add any real backing in decisions like this in Symfony.

Let's change that: https://github.com/symfony/symfony-docs/issues/15299

> isn't this change abusing Symfony's dominant position to fight some conflicting ideological views with Google?

Symfony doesn't have any dominant position, I'm sorry to say that :P

2021-04-29 17:31 UTC, t-richard commented
@nicolas-grekas 

> I think it should be a bugfix, because this is about preserving the current behavior of the web-platform. Similarly, our policies consider supporting newer PHP versions as a bugfix and this is also about changes in the outer platform Symfony runs on (same for the OS.)

The other way to see it is that releasing this PR will end-up in adding a new header to the response so it's a new feature  :slightly_smiling_face: 

> A DI parameter might be the easiest

No strong opinion on this, the proposed syntax seems good to me (would need some documentation though)

2021-04-29 17:57 UTC, r-ichard commented
IMO as a framework Symfony is a tool that should be as agnostic as possible. This means that we should not take a stand on whatever or not FloC should be activated by default. There is no binary answer to this question, final users have to answer it for themselves based on their use cases. This means it should be a mandatory parameter that allows opt-in/out on FLoC, not a built-in behavior.

Therefore, I think that as suggested by @t-richard  this should be a new feature.

2021-04-29 17:59 UTC, nicolas-grekas commented
PR updated to handle a new `kernel.permissions_policy` parameter, which defaults to `interest-cohort=()` by default when using FrameworkBundle.

2021-04-29 18:05 UTC, wouterj commented
> Symfony doesn't have any dominant position on the web, I'm sorry to say that :P

Comment edited, "dominant" removed. The question still stands imho 😉

2021-04-29 20:44 UTC, chalasr approved these changes

2021-04-29 21:52 UTC, drupol commented
In order to deal with that I made a bundle: https://github.com/loophp/go-unfloc-yourself-bundle

And I'm glad that Symfony is going to deal with it directly, in a good way.

Thanks !

2021-04-30 06:27 UTC, noniagriconomie commented
Can Symfony propose a response subscriber class, not registred (like some other commands already inside the codebase), and let enduser register it or not as will?
This way, Symfony shows that this important subject matters but do not take over enduser decision

nice read btw :)

2021-04-30 08:16 UTC, pbowyer commented
-1 on the change. FLoC isn't finalized yet and until it is it's premature to make a move.

Done well it would be a net positive for privacy; done badly it needs stopping. This knee-jerk reaction across the web is going to make it dead before it can be tried, which is not good. 

Targeted ads are not going away (however much you or I may want them to) and the proposal looks to have some merit.

tl;dr: Wait and see before acting.

2021-04-30 08:33 UTC, beberlei commented
I am against this, because you are making a decision that can potentially impact how Google rates a site with respect to search engine results and this could affect their business. Obviously that means giving a monopolist power, but every site should decide themselves if they want to do this or not. In addition this header would be sent on APIs and other sites that maybe don't even need it, increasing the payload size.

2021-04-30 09:53 UTC, Deuchnord commented
Completely +1 on this change as a bugfix, since the goal here is to (try to) keep the current behavior of the sites we create.

AFAIK, it is also still unclear if this new feature of Google's complies with the data protection laws (GDPR, CCPA…) - and I would not be surprised if it would not. It seems logical to me, that the tools we use to build our software provide by default features to be fully-compliant with them without any action required from us.

At least until the data privacy organizations answer to these interrogations (which could take a lot of time), I think it's a good thing that Symfony adds this new header by default.

> that can potentially impact how Google rates a site with respect to search engine results

There are a lot of objectively much more important things that can impact the rate of your site on Google's search engine (like its accessibility, for instance). And if FLoC is really a preoccupation for you, you can still activate it on your side.

2021-04-30 10:19 UTC, wouterj commented
Reading this thread, there are a lot of unknowns yet. Set aside our opinions, do we want to merge something like this with so many unknowns? Do we want to make a decision with so many unknowns (both unknown pros and cons) for all businesses build on top of Symfony, including the ones that are not actively maintained and using a LTS release for this specific reason?

Btw, a definitive must-read for participating in this discussion is https://seirdy.one/2021/04/16/permissions-policy-floc-misinfo.html The main concept of FLoC (actually: the "C" of its name) is using cohort IDs instead of unique user IDs. No unique user is tracked, only cohorts of similar users are tracked. Blocking your website from being part of the cohort doesn't really change the cohort entropy that much.

2021-04-30 10:29 UTC, nicolas-grekas commented
> potentially impact how Google rates a site

This would be very unwise from Google, as it would completely defeat their own statements saying that this is an experiment. This argument cannot be part of the decision IMHO.

> this header would be sent on APIs and other sites that maybe don't even need it, increasing the payload size.

Good point. This permissions policy is defined in relation with a JavaScript API, it should be safe to consider that the header is needed only on resources that can embed JS. PR updated: the header will be sent only for content-types that contain either `html` or `pdf`.

> Reading this thread, there are a lot of unknowns yet. Set aside our opinions, do we want to merge something like this with so many unknowns?

I think that providing a safe-by-default approach is a decision we can make yes.

Most unknown are about how FLoC really works. We don't need to answer all these unknowns to know that anything related to privacy should be opt-in.

> No unique user is tracked, only cohorts of similar users are tracked.

The danger is when the boundaries of cohorts align with segregation.

But as just stated, we don't need to decide whether we're fine with FLoC or not. Leaking even bits of privacy should not be opt-out IMHO.

2021-04-30 11:51 UTC, mdeboer commented
I agree with @nicolas-grekas, this should be opt-in. This makes sure that nothing changes for people that upgrade and might not even find out they are "supporting" FLoC.

People that actively want to use FLoC can look in the documentation or the reference where it should be clearly documented what it does and what concerns there are.

*If it were any other company, I would have given it some more thought but guys, it's Google and they greatly benefit from it, of course they say it's opt-out.*

@beberlei 
> I am against this, because you are making a decision that can potentially impact how Google rates a site with respect to search engine results and this could affect their business. Obviously that means giving a monopolist power, but every site should decide themselves if they want to do this or not. In addition this header would be sent on APIs and other sites that maybe don't even need it, increasing the payload size.

No, Google themself do this all the time. Their ranking is a mystery and SEO experts make a great deal of money off it by finding and applying tricks to get websites up in their rankings. See this as just another SEO trick to potentially get a higher ranking in Google, except this trick has a potential drawback with regards to privacy. Do we really want to trade in privacy just because Google said it's opt-out? I for sure don't, ever.

2021-04-30 14:03 UTC, neclimdul commented
The last set of comments on this seem to be a mix of "we shouldn't accept this because its not final" and "we shouldn't accept it because google will punish sites"

IMHO that seems to miss the point of accepting it and gives cedes all our power to Google. For me the point is for us as the people that are trying to be build a safe and secure web to tell Google "this is not ok and going forward it will trash your result quality"

2021-04-30 14:13 UTC, wouterj commented
I'm 100% behind making the statement that opt-out is not the way to go for FLoC. However, every business should make their own decision whether they want to make the statement or whether they don't want it.

Symfony has decided to make this statement by publicly announcing they added this header to all their websites (https://twitter.com/fabpot/status/1387777376898228232).

Adding this header, hidden in some required listener, in an LTS release as "bugfix" does add nothing to the statement. It's the same couple individuals making the same statement. All people that unknowingly join the statement by a change deep in the framework don't add value to the statement. And even if it does, it means that a couple individuals is misusing the users of their framework to strengthen their personal statement. I really fail to see how so many people feel like that is the best way forward for Symfony.

2021-04-30 14:54 UTC, maartendekeizer commented
I totaly agree with @wouterj every business should make their own decissions. In Symfony we either don't block the use of insecure cookies, plain passwords or running http instead of https.

Since Symfony 2, Symfony is a framework, providing tools for us, developers, not a tool for end users (I think Symfony 1 was more closer to end users). For me as a developer I like Symfony 2+ becuase the framework does not make any decissions for me as developers.

Adding a header for FLoC by default will break that way of working. I think we should not go in this direction, because when we added a header for FLoC, we should also add other headers like STS, frame options, referer policy, etc...

I totaly agree with the statement made on Twitter and disabling/opt out from FLoC on the Symfony websites. I think the next step should be a Cookbook article where we tell developers how they can implement the opt out on theire own sites/projects.

2021-04-30 15:40 UTC, kevinpapst commented
I feel this is going in a wrong direction and vote with @wouterj @beberlei and others against this change: you are forcing your own political opinion onto every user of Symfony. No matter how good the reasons, this is still the wrong way IMO. Please don't (mis-)use your position as core developer to add such a hidden setting to a framework.

Don't call this a bugfix. This is really a bad argument to get it in more releases and circumvent your own release rules. 
Only the end businesses should decide if they want this header or not. 

I would propose: add it as an opt-in feature (you can even activate it via a flex recipe). This way everyone has to think about it once and you still make a strong statement for privacy.

2021-04-30 19:03 UTC, neclimdul commented
Everything is political if someone makes it political I guess but that doesn't make this the wrong thing to do. If a site maintainer can disable this much like they could disable other hardening features in symfony it seems like it should be included.

2021-04-30 19:06 UTC, neclimdul commented
Additionally, all the arguments that business should make the decision, agree 100%. They should be able to make the decision to allow google to do this, not have google do it and then have to force they're way out. The whole argument by the EFF and everyone else is this is changing the status quo of the internet and _not_ letting businesses opt in to the process. Adding this features seems like it gives the power _to_ the business not the other way around.

2021-04-30 19:38 UTC, XWB commented
> It has been rejected by most of the web community (GitHub, Wordpress, Drupal, Svelte, Caddy, Mozilla, Brave, the EFF and many other prominent actors). We are far away from a "rough consensus and running code".

>The thing is that the community at large is right to fight to force Google to respect the core values behind the web (which don't include tracking and mass surveillance, quite the opposite actually).

And while it may be a good thing the Symfony community rejects FLoC, why does it have to be part of the framework? 

So far I haven't read any valid arguments why Symfony **framework** would have to make the calls. This smells like pushing a political agenda and feels wrong IMO.

If you are against FLoc, feel free to add the header to your Apache/nginx/whatever server, but please don't add this proprietary stuff to the framework.

2021-05-01 06:21 UTC, maartendekeizer commented
Found a situation where this 'bugfix' leads to a problem. One of my clients is managing headers like the feature-policy/permission-policy-header in his reverse proxy layer. The header is set but only when the application did not send the header. When we apply this bugfix to the application it may change the headers an end-user will receive, because the reverse proxy layer will no longer insert this header.

2021-05-01 10:34 UTC, nicolas-grekas commented
> Additionally, all the arguments that business should make the decision, agree 100%. They should be able to make the decision to allow google to do this, not have google do it and then have to force they're way out. The whole argument by the EFF and everyone else is this is changing the status quo of the internet and not letting businesses opt in to the process. Adding this features seems like it gives the power to the business not the other way around.

I'm 100% aligned with this analyze. Saying that site maintainers can decide to opt out is presupposing that the knowledge about this FLoC thing reaches them all and that they're able to make an informed decision about this. There are numerous examples that make be seriously doubt that this will even happen in a statistically significant way. Of course, Google will greatly benefit from this - changing the status quo.

> I would propose: add it as an opt-in feature (you can even activate it via a flex recipe).

I would be happy with a solution that makes at least new Symfony projects send this header by default. A recipe might be a good idea. The plan would then be:
1. make the parameter be `null` by default in this very PR
2. add `kernel.permissions_policy: "interest-cohort=()"` in the recipe of FrameworkBundle >= 4.4.

Another idea might be to add support for `Permissions-Policy` to eg `nelmio/security-bundle` it that fits it, and make `nelmio/security-bundle` part of eg the `website-skeleton`.

My preference is for the proposal based on a recipe.

2021-05-01 11:18 UTC, beberlei commented
Symfony also did not set the do not track header by default or made it configurable, none of the actually important security headers are part of the framework. Starting to handle one proprietary header will take the framework down a rabbit hole of things to control, specifically given this is only a test.

2021-05-01 11:30 UTC, maartendekeizer commented
Adding an extra bundle (that implements this header) to the `website-skeleton` would be my prefered choice. In that way Symfony can make a statement, it is not part of the framework, it is default on for new website projects, it is easy to remove and will not popup on other projects (pure api projects for example).

2021-05-01 11:41 UTC, GromNaN commented
There is other response headers that needs to be set by default for security reasons (then privacy).

```
X-Content-Type-Options: nosniff
Content-Security-Policy: upgrade-insecure-requests; connect-src * https:; img-src * data: https:; font-src * data:; script-src * 'unsafe-inline' 'unsafe-eval'; style-src * 'unsafe-inline'; media-src * blob: data:; worker-src * blob: data:
Strict-Transport-Security: max-age=604800
```

I would enhance [Nicolas' proposition](#issuecomment-830609504) with a more generic parameter called `kernel.default_response_headers`.

2021-05-14 22:40 UTC, ostrolucky commented
Just echoing the post from https://github.com/symfony/symfony/pull/40989#issuecomment-830562597 which proves this is a breaking change and cannot go as a bug fix.

And also https://github.com/symfony/symfony/pull/40989#issuecomment-830615762 which highlights that Symfony didn't do similar things till now.

All in all, I'm also against this change. Can be reconsidered in a year or so when we know more about how the market will react. But really, this is something that should be solved on client side, like every other privacy option. Not users relying on all 982935290384 websites that they visit to decide for them.

2021-05-14 22:41 UTC, ostrolucky requested changes
Just echoing the post from https://github.com/symfony/symfony/pull/40989#issuecomment-830562597 which proves this is a breaking change and cannot go as a bug fix.

And also https://github.com/symfony/symfony/pull/40989#issuecomment-830615762 which highlights that Symfony didn't do similar things till now.

All in all, I'm also against this change. Can be reconsidered in a year or so when we know more about how the market will react. But really, this is something that should be solved on client side, like every other privacy option. Not users relying on all 982935290384 websites that they visit to decide for them.

2021-06-12 09:29 UTC, nicolas-grekas commented
Thank you all for the discussion.
Closing in favor of https://github.com/nelmio/NelmioSecurityBundle/issues/240
Help wanted!

2021-06-12 09:29 UTC, closed without merging