[HttpClient] Avoid installation of latest contracts as it's not compatible
symfony/symfony pull request #41001
Opened 2021-04-30 10:25 UTC by lyrixx

| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       |>
| License       | MIT
| Doc PR        |

To be reverted on 5.x

2021-04-30 10:39 UTC, OskarStark commented
I added a Fixes... for the open ticket to the PR header

2021-04-30 10:39 UTC, OskarStark approved these changes

2021-04-30 11:55 UTC, stof requested changes

2021-04-30 11:55 UTC, stof commented on src/Symfony/Component/HttpClient/composer.json
> +        "symfony/http-client-contracts": "^1.1.10|<2.4",
should be `^1.1.10|>=2,<2.4`. Otherwise, the `<2.4` constraint allows to install `1.0.0`

2021-04-30 13:27 UTC, nicolas-grekas commented
HttpClient *is* compatible with Contracts 2.4. It "just" triggers a deprecation when used with it, but that can be ignored.

I think we should try patching `DebubClassLoader` instead.

2021-04-30 13:32 UTC, lyrixx commented
It just trigger deprecation notice because we ensure to not break BC. That's why we added `@method` annotation, and not the method directly. So indeed it's compatibly because ut "just" trigger deprecation. On there is no way to avoid them on 4.4

2021-05-02 17:37 UTC, nicolas-grekas commented
Closing in favor of #41075
Thanks for the patch!

2021-05-02 17:37 UTC, closed without merging