[Security] Added missing Polish translations.
symfony/symfony pull request #41079
Opened 2021-05-02 21:40 UTC by ShiroRyokoshi

| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix ##41061
| License       | MIT
| Doc PR        | N/A

The translations added were based off the english ones.
This is my first PR ever, I hope I didn't do any mistakes.

2021-05-02 22:59 UTC, skmedix requested changes

2021-05-02 22:59 UTC, skmedix commented on src/Symfony/Component/Security/Core/Resources/translations/security.pl.xlf
> +                <target>Zbyt wiele nieudanych prób logowania, spróbuj ponownie po upływie %minutes% minut.</target>
Please fix formatting.

```suggestion
            </trans-unit>
            <trans-unit id="19">
                <source>Too many failed login attempts, please try again in %minutes% minute.</source>
                <target>Zbyt wiele nieudanych prób logowania, spróbuj ponownie po upływie %minutes% minut.</target>
            </trans-unit>
            <trans-unit id="20">
                <source>Too many failed login attempts, please try again in %minutes% minutes.</source>
                <target>Zbyt wiele nieudanych prób logowania, spróbuj ponownie po upływie %minutes% minut.</target>
```

2021-05-03 06:34 UTC, Nyholm approved these changes
Thank you. It looks great!

Could @pamil give this a quick review too?

2021-05-05 15:58 UTC, ShiroRyokoshi commented
@Nyholm Hey, can I close this request or are we still waiting for some extra review?

2021-05-06 11:03 UTC, fabpot commented
Thank you @ShiroRyokoshi.

2021-05-06 11:03 UTC, merged