Override recipient with mailer.envelope.recipients configuration
symfony/symfony pull request #41150
Opened 2021-05-09 21:43 UTC by arnolem

https://github.com/symfony/symfony/issues/41149

| Q             | A
| ------------- | ---
| Branch?       | 5.2
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #41149
| License       | MIT
| Doc PR        | https://symfony.com/doc/current/mailer.html#always-send-to-the-same-address

Symfony/Mailer : The recipients feature ("Always Send to the same Address") does not work with sendmail

2021-08-26 07:47 UTC, fabpot requested changes

2021-08-26 07:47 UTC, fabpot commented on src/Symfony/Component/Mailer/Transport/SendmailTransport.php
> +                $originalMessage->to($recipient->getAddress());
For once, I'm going to agree with Psalm! The original message can be a RawMessage for which we don't have any of these conventional methods. In any case, the envelope should never alter the message directly.
This is controlled by line 199 instead.

2021-12-11 11:52 UTC, trsteel88 commented
Any update on this bug?

2021-12-12 21:40 UTC, arnolem commented
> Any update on this bug?

https://github.com/symfony/symfony/issues/41149#issuecomment-991975440

2022-03-18 08:06 UTC, fabpot commented
Closing in favor of #45690

2022-03-18 08:06 UTC, closed without merging