[Security] Added Ukrainian translations
symfony/symfony pull request #41192
Opened 2021-05-12 12:56 UTC by andrii-bodnar

| Q             | A
| ------------- | ---
| Branch?       | 4.4 
| Bug fix?      | no
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #41088 
| License       | MIT
| Doc PR        | 

Added some missing Ukrainian translations.

2021-05-13 09:12 UTC, Comrade42 requested changes

2021-05-13 09:12 UTC, Comrade42 commented on src/Symfony/Component/Security/Core/Resources/translations/security.uk.xlf
> +                <target>Забагато невдалих спроб входу. Будь ласка, спробуйте через %minutes% хвилину.</target>
```suggestion
                <target>Забагато невдалих спроб входу. Будь ласка, спробуйте знову через %minutes% хвилину.</target>
```

2021-05-13 09:12 UTC, Comrade42 commented on src/Symfony/Component/Security/Core/Resources/translations/security.uk.xlf
> +                <target>Забагато невдалих спроб входу. Будь ласка, спробуйте через %minutes% хв.</target>
```suggestion
                <target>Забагато невдалих спроб входу. Будь ласка, спробуйте знову через %minutes% хвилин.</target>
```

2021-05-13 09:19 UTC, andrii-bodnar commented on src/Symfony/Component/Security/Core/Resources/translations/security.uk.xlf
> +                <target>Забагато невдалих спроб входу. Будь ласка, спробуйте через %minutes% хв.</target>
@Comrade42, I used "хв." here, due to a possible situation of incorrect translation at some values of `%minutes%`.

For example:
`%minutes%` = 10: should be `... спробуйте через 10 хвилин.`
`%minutes%` = 21: should be `... спробуйте через 21 хвилину.`

`хв.` will be correct in both cases. Also, for Russian translations, the same approach is used.

2021-05-13 10:05 UTC, Comrade42 commented on src/Symfony/Component/Security/Core/Resources/translations/security.uk.xlf
> +                <target>Забагато невдалих спроб входу. Будь ласка, спробуйте через %minutes% хв.</target>
Good, it sounds reasonable to me.

2021-05-13 11:57 UTC, andrii-bodnar commented
@Comrade42 I've addressed all the comments. Thanks for the review.

Status: need review

2021-05-13 12:31 UTC, Comrade42 commented
Looks good to me, thank you 👍

2021-05-13 13:54 UTC, andrii-bodnar commented
@chalasr @wouterj please review this PR :slightly_smiling_face:

2021-05-13 14:54 UTC, chalasr approved these changes

2021-05-15 06:44 UTC, Nyholm approved these changes
Thank you

2021-05-15 06:45 UTC, merged