6.0
symfony/symfony pull request #41586
Opened 2021-06-07 14:13 UTC by antoinemaschi

| Q             | A
| ------------- | ---
| Branch?       | 6.0
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | -

PhpStorm helped a lot

2021-06-07 14:44 UTC, jderusse requested changes
Hello, thank you for your help. 

From https://github.com/symfony/symfony/pull/41424#issuecomment-855662517

> Please DO NOT add return types nor types to properties

2021-06-07 14:44 UTC, jderusse commented on src/Symfony/Component/Ldap/Adapter/AbstractConnection.php
> +    protected array $config;
revert

2021-06-07 14:44 UTC, jderusse commented on src/Symfony/Component/Ldap/Adapter/AdapterInterface.php
> +    public function getConnection(): ConnectionInterface;
revert

2021-06-23 11:28 UTC, fabpot commented
@antoinemaschi Do you have time to finish this PR?

2021-06-28 07:47 UTC, nicolas-grekas commented
Closing as this now contains only changes that we're not ready to make yet. Thanks for opening.

2021-06-28 07:47 UTC, closed without merging