Fix incorrect parameter type
symfony/symfony pull request #41621
Opened 2021-06-08 16:06 UTC by bch36

In the affected line of code, fclose() should ONLY be passed a parameter of type resource, but fopen() can return a value of type bool (if the fopen() fails). This results in a fatal error under PHP 8: Fatal error: Uncaught TypeError: fclose(): Argument #1 ($stream) must be of type resource, bool given.

| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | 
| License       | MIT
| Doc PR        |

2021-06-08 17:22 UTC, derrabus requested changes

2021-06-08 17:22 UTC, derrabus commented on src/Symfony/Component/Process/Pipes/WindowsPipes.php
> +                    if (false === $fopen_result || !fclose($fopen_result) || !$h = fopen($file, 'r')) {
We don't use underscores in variable names. Also, let's keep the code compact here.

```suggestion
                    if (!($fileHandle = fopen($file, 'w')) || !fclose($fileHandle) || !$h = fopen($file, 'r')) {
```

2021-06-08 17:25 UTC, derrabus commented
You've submitted the PR against the 5.4 branch, but apparently you wanted to target 4.4. Can you please rebase?

2021-06-09 14:59 UTC, nicolas-grekas commented
Thank you @bch36.

2021-06-09 14:59 UTC, merged