BUG: revert negatable ansi
symfony/symfony pull request #41723
Opened 2021-06-16 11:13 UTC by batenburg

When I create a command and configure it with the addOption 'no-ansi', the current 5.3 is throwing an exception.

The reason behind it is, that it is configure as negatable. When it is adding it check if the no-ansi is exists. Then it throws an exception.
In the 5.2 situation it then checked if the options equals. If not throw an exception.

https://github.com/symfony/console/blob/5.3/Input/InputDefinition.php#L255 part where the check is coming for the negatable and throws an exception.
https://github.com/symfony/console/blob/5.3/Input/InputDefinition.php#L233 The equals check where in the past the error was prevented.

Reverting the option to two values, seems like the right solution.

| Q             | A
| ------------- | ---
| Branch?       | 5.4 for features / 4.4, 5.2 or 5.3 for bug fixes 
| Bug fix?      | yes/no
| New feature?  | yes/no 
| Deprecations? | yes/no 
| Tickets       | Fix #... 
| License       | MIT
| Doc PR        | symfony/symfony-docs#...

2021-06-16 11:27 UTC, YaFou commented
I understand your issue but I think this is not the best solution to revert changes to the `ansi` option. In my opinion, you should apply the same check as [here](https://github.com/symfony/console/blob/5.3/Input/InputDefinition.php#L233) with the negatable options.
Please provide also a test for this issue.

2021-06-16 11:34 UTC, derrabus commented
I'd also prefer to not revert the change.

I understand that on Symfony 5.2, adding a `--no-ansi` option was kind-of a valid thing to do because the component did not specify it. Can we find a way to gracefully allow commands to do that and maybe trigger a deprecation in that case?

2021-06-16 11:54 UTC, batenburg commented
@YaFou I had also checked to add the check (https://github.com/symfony/console/blob/5.3/Input/InputDefinition.php#L233), beacuse I add an option with the name no-ansi it is comparing with the name ansi and then the check will return false, That is not working, 

Reproduce the bug. Create a command class, in the configure method set `$this->addOption('no-ansi', null, InputOption::VALUE_NONE, 'Disable ANSI output')`, you can also try it with the negatable, will be the same result.

2021-06-16 12:23 UTC, batenburg commented
@YaFou and @derrabus another solution which comes to my mind is removing the check if it exists on negatable. What do you think?

2021-06-16 12:40 UTC, stof commented
Well, creating the same option in a command and in the application is something we should forbid, as things will break in subtle ways if the 2 places don't apply the same config on the option.

2021-06-16 13:01 UTC, batenburg commented
@stof true point, that is why I would propose a revert, becasue then I can add someting twice with the same settings. which aint possible for a negetable

2021-06-16 13:17 UTC, stof commented
I agree with the revert in 5.3, but I think 5.4 should deprecated overriding application-level options (and 6.0 should forbid it), to avoid such subtle breakages.

2021-06-16 13:22 UTC, YaFou commented
Why not deprecate it now @stof? Maybe because it is on a maintenance branch?

2021-06-16 13:31 UTC, stof commented
>  Maybe because it is on a maintenance branch?

yes. Deprecations cannot be introduced in patch releases

2021-06-16 17:07 UTC, derrabus commented
> I agree with the revert in 5.3, but I think 5.4 should deprecated overriding application-level options (and 6.0 should forbid it), to avoid such subtle breakages.

If we do this, I'd also like to switch back to negatable on 6.0.

2021-06-16 19:17 UTC, derrabus requested changes
The tests need some love after your change.

2021-06-21 09:22 UTC, jderusse commented
Before merging this PR in 5.4, could you please open a PR in 5.4 that deprecate overriding an option, and allow us to revert this PR in 6.0?

2021-06-22 12:15 UTC, GrahamCampbell commented
👍 for merging this. This issue is causing a lot of issues for Laravel users, which make up a large number of monthly downloads of this component.

2021-06-22 12:16 UTC, GrahamCampbell commented
Better to break code that's only been here for a few weeks, than to break code that's been here for years.

2021-06-22 18:32 UTC, jderusse commented
Hmm.. I dug into the issue and started working on a fix (#41792), but I realized that this does not make sense.

1. In Symfony <5.3, You were not allowed to redefine an option UNLESS the options are exactly identical. The single change that is allowed is the description.
2. The `ansi` and `no-ansi` are defined in the Command's definition, which means these are applied AFTER the user's command option (see https://github.com/symfony/symfony/blob/f12a4190e174a8efa1830083729e0b1761a83c82/src/Symfony/Component/Console/Command/Command.php#L360-L361), which means they override the user's definition

Both previous points leads to: in symfony < 5.3, adding an option `ansi` or `--no-ansi` has no effect.

> This issue is causing a lot of issues for Laravel users, which make up a large number of monthly downloads of this component.

Do you have such issue  @GrahamCampbell ? because https://github.com/laravel/tinker/issues/127 is not related. 
in https://github.com/laravel/tinker/issues/127 the issue is: previously both `ansi` and `--no-ansi` return false. While now `no-ansi` returns true. 

This issue should be addressed by #41794

2021-11-22 10:38 UTC, closed without merging