Fix Class AmqpReceivedStamp does not exist
symfony/symfony pull request #41749
Opened 2021-06-19 16:07 UTC by Warxcell

| Q             | A
| ------------- | ---
| Branch?       | 5.2
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | yes
| Tickets       | Fix #41748
| License       | MIT
| Doc PR        |

2021-06-19 17:33 UTC, xabbuh commented
Can you show the stack trace of the error that you receive? I do not really see why the current code should trigger it.

2021-06-19 17:58 UTC, Warxcell commented
> Can you show the stack trace of the error that you receive? I do not really see why the current code should trigger it.

Sure, https://travis-ci.org/github/Warxcell/files/jobs/773978302#L785

2021-06-19 19:29 UTC, xabbuh commented
I think we should prevent the use of `ReflectionClass` instead if the given class does not exist: #41751

2021-06-19 20:28 UTC, Warxcell commented
Why? To me it's looks like this middleware is tighly coupled to AMQP package, why not ship it inside it, rather than ship it globally in symfony and check if it exists or not?

2021-06-19 21:19 UTC, xabbuh commented
We can think about adding a new middleware in another namespace and deprecate the other one. But such a change must not happen in a patch release and would have to target the `5.4` branch.

2021-06-20 06:42 UTC, Warxcell commented
Ok, so I will redirect this to 5.4 and your fix will be patches in 5.2 ?

2021-06-21 12:09 UTC, nicolas-grekas commented
Please fix commit+PR title
and add a line in the changelog of the component, and in UPGRADE files for 5.4 and 6.0.

2021-06-27 07:13 UTC, kozlice commented
I'm working on an alternative AMQP transport for messenger based on [bunny](https://github.com/jakubkulhan/bunny) library.

Moving this class will complicate dependency tree. Can we choose the way @xabbuh proposes to avoid that?

2022-08-07 09:54 UTC, fabpot commented
@Warxcell Looks good to me. Can you rebase on 6.2 and update the code accordingly? Thank you.

2023-10-11 08:12 UTC, fabpot requested changes

2023-10-11 08:12 UTC, fabpot commented on UPGRADE-5.4.md
> +* Deprecate `Middleware\RejectRedeliveredMessageMiddleware`. Install `symfony/amqp-messenger` and use same class from there.
Missing blank line above

2023-10-11 08:12 UTC, fabpot commented on UPGRADE-5.4.md
> +=======
To be removed

2023-10-11 08:12 UTC, fabpot commented on UPGRADE-6.0.md
> + * Removed `Middleware\RejectRedeliveredMessageMiddleware`.  Use same class from `symfony/amqp-messenger`.
To be moved to a 6.4 section.

2023-10-11 08:12 UTC, fabpot commented on UPGRADE-5.4.md
> +Messenger
To be moved to the 6.4 UPGRADE file

2023-10-11 16:34 UTC, nicolas-grekas commented
On closer look, I think we should close this PR. The linked issue has been fixed, which means that in practice, this is change is just a nice to have. Yes, the implementation knows only about some amqp stamp at the moment, but we could also imagine a day where it manages other kind of stamps.

2023-10-11 16:38 UTC, closed without merging

2023-10-11 16:38 UTC, fabpot commented
Thanks for having a look Nicolas. Let's close then.