[FrameworkBundle] fix removing "action" from route names
symfony/symfony pull request #41782
Opened 2021-06-22 11:44 UTC by nicolas-grekas

| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #40024
| License       | MIT
| Doc PR        | -

2021-06-22 13:52 UTC, ro0NL commented
should we change default names in a patch release?

2021-06-22 13:53 UTC, stof commented
This will break all URL generation that uses the existing names. So it might indeed be dangerous in a patch release

2021-06-22 13:55 UTC, ro0NL commented
also, from my experience, dereferencing virtual route names is pure pain :D

2021-06-22 20:34 UTC, nicolas-grekas commented
> This will break all URL generation that uses the existing names. So it might indeed be dangerous in a patch release

Only when an action method doesn't end with `Action` nor `_action`, but still ends with "action", in a case-sensitive way.

I'm fine doing this on 5.4...

2021-06-23 18:45 UTC, nicolas-grekas commented
Now targetting 5.4

2021-07-04 13:48 UTC, Tobion requested changes

2021-07-04 13:48 UTC, Tobion commented on src/Symfony/Bundle/FrameworkBundle/Tests/Functional/Bundle/TestBundle/Controller/AnnotatedController.php
> +    public function createTransaction($value)
$value can be removed. it is irrelevant in this action

2021-07-04 13:48 UTC, Tobion commented on src/Symfony/Bundle/FrameworkBundle/Routing/AnnotatedRouteControllerLoader.php
> +        if ('Action' === substr($method->name, -6) || '_action' === substr($method->name, -7)) {
IMO we should require the php 8 polyfill and use str_ends_with here. Ref. #41576

2021-07-04 17:31 UTC, Tobion commented on src/Symfony/Bundle/FrameworkBundle/Routing/AnnotatedRouteControllerLoader.php
> +        if ('Action' === substr($method->name, -6) || '_action' === substr($method->name, -7)) {
I've opened a PR to do this in the whole codebase: #41973

2021-07-06 07:52 UTC, nicolas-grekas commented
@Tobion comments addressed, thanks for the review!

2021-07-06 14:19 UTC, Tobion approved these changes

2021-07-06 17:56 UTC, chalasr approved these changes

2021-07-07 15:04 UTC, Tobion commented
Thank you @nicolas-grekas.

2021-07-07 15:04 UTC, merged