#41959 - Prevent FormLoginAuthenticator from responding to requests that should be handled by JsonLoginAuthenticator
symfony/symfony pull request #41993
Opened 2021-07-05 14:15 UTC by abunch

| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | No
| New feature?  | No
| Deprecations? | No
| Tickets       | 41959
-->
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 
<!--
Prevent FormLoginAuthenticator from responding to requests that should be handled by JsonLoginAuthenticator

2021-07-06 09:54 UTC, wouterj requested changes
Hi! Thanks for starting the PR!

I think we should change the implementation a bit. Relying on "not JSON" means this authenticator is suddenly aware of other authenticators in the system and, more importantly, it will fail as soon as someone adds an `XmlLoginAuthenticator`. I also think this is a BC break: Some people use `form_login` in API requests (i.e. not form submissions), see for instance https://github.com/lexik/LexikJWTAuthenticationBundle/issues/123 and https://github.com/api-platform/core/issues/563

What do you think about changing this PR to add a new option `form_only`, defaulting to `false`, in `FormLoginFactory` and then doing `$this->options['form_only'] && 'application/x-www-form-urlencoded' === $request->getContentType()`?

Less important: please remove the `CHANGELOG.md` file you've added. The one in the root is automatically generated by the release tool (based on the PR title). If you don't add any class or option, you don't need to edit any CHANGELOG manually. If you implement my suggestion above, you should add a "Add `form_login.form_only` option" to the changelog in the SecurityBundle directory. Thanks!

2021-07-06 13:04 UTC, abunch commented
> What do you think about changing this PR

I think your suggestions make much more sense. 👍 

Changes implemented.

2021-07-06 13:06 UTC, chalasr requested changes
Please add a test for this.

2021-07-06 14:21 UTC, abunch commented
> Please add a test for this.

Ugh..I'm not very strong at writing tests but I'll give it a go this evening once I'm off for the day.

> How Do You Get To Carnegie Hall? Practice, practice, practice.

2021-07-06 14:24 UTC, wouterj commented
If you have an account in the [Symfony Slack](https://symfony.com/slack), feel free to hop in `#contribs` and ask for help writing a test for this. Contributors (and I) will probably be around this evening or any time to offer some help :)

2021-09-16 11:50 UTC, chalasr commented
friendly ping @abunch :) Do you want us to add a test for you?

2021-10-27 17:15 UTC, fabpot commented
@chalasr Do you want to take over this one?

2021-10-27 18:33 UTC, chalasr commented
@fabpot done

2021-10-27 18:34 UTC, chalasr approved these changes

2021-10-29 16:43 UTC, fabpot approved these changes

2021-10-29 16:44 UTC, fabpot commented
Thank you @abunch.

2021-10-29 16:44 UTC, merged