[Console] Fix save correct name in setDefaultCommand() for PHP8
symfony/symfony pull request #42009
Opened 2021-07-06 19:49 UTC by a1812

| Q             | A
| ------------- | ---
| Branch?       | 5.3
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #41942 | License       | MIT
| Doc PR        | symfony/symfony-docs#... 

Fix save correct name in setDefaultCommand() for PHP8

2021-07-07 08:31 UTC, duboiss commented
I don't feel that this is fixing #41942 after testing on my local project ([duboiss/sfcommand](https://github.com/duboiss/sfcommand), php8 branch) your modifications.

2021-07-07 09:13 UTC, a1812 commented
> I don't feel that this is fixing #41942 after testing on my local project ([duboiss/sfcommand](https://github.com/duboiss/sfcommand), php8 branch) your modifications.

and nevertheless my test shows that everything is in order :)
![image](https://user-images.githubusercontent.com/42714329/124732480-e68c5680-df1b-11eb-926a-ce58b47fe411.png)

2021-07-07 20:01 UTC, duboiss commented
My bad, I think I made a mistake between two `git clone`. It's ok from my side too, nice job!

2021-07-08 09:26 UTC, chalasr approved these changes

2021-07-08 09:29 UTC, fabpot requested changes

2021-07-08 09:29 UTC, fabpot commented on src/Symfony/Component/Console/Application.php
> +
Could we inline everything below:

```php
$this->defaultCommand = explode('|', ltrim($commandName, '|'))[0];
```

2021-07-08 11:17 UTC, a1812 commented on src/Symfony/Component/Console/Application.php
> +
ok

2021-07-08 13:25 UTC, fabpot approved these changes

2021-07-08 13:26 UTC, fabpot commented
Thank you @a1812.

2021-07-08 13:27 UTC, merged