[WIP] [HttpFoundation] Fix deleteFileAfterSend on client abortion
symfony/symfony pull request #42033
Opened 2021-07-08 12:07 UTC by nerg4l

| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #27538 
| License       | MIT
| Doc PR        | 

**Description**

If someone sets `deleteFileAfterSend` to `true` for a `BinaryFileResponse` instance they expect the file to be deleted when the response finished. This is not the case when the response is cancelled because PHP won't continue running the code. `ignore_user_abort` can be used to allow it to finish but this means `stream_copy_to_stream` will also continue to run regardless of the abort. To fix this later problem it can be a solution to run the copy in a loop and detect the connect abort manually with `connection_aborted`.

**Tests**

I don't know how can I simulate connection abort in PHPUnit. I would appreciate if I could get some guidance if it is possible.

**Todo**

- [ ] add tests if connection abort can be simulated
- [ ] gather feedback for my changes

2022-07-10 18:54 UTC, fabpot requested changes

2022-07-10 18:54 UTC, fabpot commented on src/Symfony/Component/HttpFoundation/BinaryFileResponse.php
> +    public function setChunkSize(int $chunkSize)
```suggestion
    public function setChunkSize(int $chunkSize): self
```

2022-07-12 11:43 UTC, fabpot approved these changes

2022-07-15 08:59 UTC, fabpot commented
Thank you @nerg4l.

2022-07-15 08:59 UTC, closed without merging

2022-07-15 16:19 UTC, nerg4l commented
@fabpot I'm glad I was able help.

Additional info: The chunk size in this PR is 8 KiB (8 * 1024 byte) at the moment which is the same as the default stream chunk size in PHP. As far as I know, the only way to read the default chunk size is to call [`stream_set_chunk_size`](https://www.php.net/manual/en/function.stream-set-chunk-size.php) and see the previous value of it. However, a year ago when I opened the PR I set it to 1 MiB but I don't remember why I did that.