[PropertyInfo] Support for intersection types
symfony/symfony pull request #42098
Opened 2021-07-14 13:19 UTC by derrabus

| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | N/A
| License       | MIT
| Doc PR        | N/A

I was a bit unsure how to fix this one. PropertyInfo does not know about the concept of intersection types yet. With this PR, the component will behave exactly the same for an intersection type as for a union: You will get an array of all atomic types.

2021-07-14 14:13 UTC, chalasr approved these changes

2021-07-15 07:36 UTC, nicolas-grekas requested changes
I suppose we need a way to differentiate unions from intersections.
Putting a preemptive "changes requested" until e figure out what we need here.
(I've no idea yet :) )

2021-07-27 20:29 UTC, derrabus commented
@nicolas-grekas Have you made up your mind yet?

2021-07-28 04:59 UTC, nicolas-grekas commented
Nope. Maybe @dunglas has? Otherwise can you make a proposal? I'm AFK right now 😅

2021-07-28 10:50 UTC, derrabus commented
My proposal is this PR. Our current strategy of returning an array of types does not really work well anymore if we want to distinguish union from intersection types. I think, we can find a better representation for 5.4, but for 4.4, I just want PropertyInfo to not fall apart if we encounter an intersection.

2021-08-26 06:20 UTC, fabpot commented
This should probably be for 5.4 instead.

2021-08-26 13:04 UTC, derrabus commented
> This should probably be for 5.4 instead.

I tend to disagree here. The component would currently throw cryptic errors if presented with an intersection type. We can certainly argue about _what_ it should do instead, but I don't think we should leave it as is in 4.4.

2021-08-26 13:13 UTC, ro0NL commented
i think a list of types fits our semantic generally;
https://github.com/symfony/symfony/blob/2bf839d65c38fa407e0d43766d4cc1151580245b/src/Symfony/Component/PropertyInfo/PropertyTypeExtractorInterface.php#L22

can we think of something that would conflict in practice?

ref #37971 also :) i agree about the compat issue.

2021-08-26 13:34 UTC, fabpot commented
ok, fair enough.

2021-08-26 18:13 UTC, ro0NL commented on src/Symfony/Component/PropertyInfo/Tests/Extractor/ReflectionExtractorTest.php
> +            ['collection', [new Type(Type::BUILTIN_TYPE_OBJECT, false, 'Traversable'), new Type(Type::BUILTIN_TYPE_OBJECT, false, 'Countable')]],
i tend to believe the intersection type should be preserved as a single type;

```
[new Type(Type::BUILTIN_TYPE_OBJECT, false, 'Traversable&Countable')]
```

2021-08-27 07:53 UTC, dunglas approved these changes

2021-09-07 07:30 UTC, nicolas-grekas commented
Thank you @derrabus.

2021-09-07 07:30 UTC, merged

2021-09-07 07:31 UTC, nicolas-grekas commented on src/Symfony/Component/PropertyInfo/Tests/Extractor/ReflectionExtractorTest.php
> +            ['collection', [new Type(Type::BUILTIN_TYPE_OBJECT, false, 'Traversable'), new Type(Type::BUILTIN_TYPE_OBJECT, false, 'Countable')]],
Maybe on a higher branch, since this PR is motivated by the need to generate a proper message.
Follow up welcome.