Simplify some code with null coalesce operator
symfony/symfony pull request #42165
Opened 2021-07-17 18:13 UTC by javiereguiluz

| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | -

For your consideration. There are many other possible usages of null coalesce operator, but the result is not very readable ... so this PR only contains the changes where the result is clearly better.

2021-07-17 18:24 UTC, Tobion approved these changes

2021-07-18 12:31 UTC, derrabus requested changes
The CI job of the PHPUnit bridge fails. Keep in mind that we cannot use PHP 7 syntax there.

2021-07-18 15:07 UTC, javiereguiluz commented
@derrabus thanks for the notice. I've reverted all changes on PhpUnit Bridge component.

2021-07-18 16:06 UTC, derrabus approved these changes

2021-07-18 16:24 UTC, derrabus commented
Thank you Javier.

2021-07-18 16:24 UTC, merged