Readd missing php-doc parameter for constructor
symfony/symfony pull request #42281
Opened 2021-07-27 07:15 UTC by brosenberger

| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  |no 
| Deprecations? |no 
| Tickets       | no
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

partly revert the php constroctur php doc (readd missing php-doc for $name and $description) even if they not that meaningfull

This is needed as Magento2 uses this library and needs all php-doc parameter for interception compilation. if there are any missing parameters (in this case $name and $description) break compile step as the parameters are missmatching the actual parameters:
![image](https://user-images.githubusercontent.com/2969243/127111853-671d0f70-e44e-4465-9d2b-54ec80b934ff.png)
(AbstractConfigOption extends InputOption)

2021-07-27 09:05 UTC, kassner commented
The change was introduced in #41992

2021-07-27 10:13 UTC, derrabus requested changes
This looks like an issue of the tool that you are using there. I'm very much against re-introducing redundant doc block annotations.

2021-07-27 10:13 UTC, derrabus commented on src/Symfony/Component/Console/Input/InputOption.php
> +     * @param string|array|null                $shortcut.   The shortcuts, can be null, a string of shortcuts delimited by | or an array of shortcuts
```suggestion
     * @param string|array|null                $shortcut    The shortcuts, can be null, a string of shortcuts delimited by | or an array of shortcuts
```

2021-07-27 10:27 UTC, brosenberger commented
@derrabus i agree that those comments are not really usefull, nethertheless all magento2 builds use this module and do generate interceptors (for a precompiled aop solution) which uses the method parameter php-doc (if present) - therefore many shops have to update their versions either to fixate it to v4.4.26 or add a patch where the @params are added again to gain a green build again

2021-07-27 13:38 UTC, derrabus commented
Okay and why can't this be fixed on Magento's side?

2021-07-27 13:48 UTC, hostep commented
@derrabus: Magento really needs to fix this, but the release cycle of Magento is super slow and upgrades from one version of Magento to another are very tedious and take a lot of time, even for minor releases. So even if Magento released a new version (next one is scheduled for 2022, they will only release security fixes in 2021 anymore), it would take people a lot of time and effort to upgrade to it.

2021-07-27 14:25 UTC, alcaeus commented
@brosenberger There are multiple packages that do the same thing, including many Doctrine packages. These two parameters are self-explanatory through the signature and the documentation adds no value (especially since Symfony no longer publishes this documentation IIRC).

Slow release process aside, I don't think this issue should be fixed anywhere but in Magento itself.

2021-07-27 14:30 UTC, derrabus commented
So Magento is basically not doing bugfix releases?

2021-07-27 14:42 UTC, fascinosum commented
@alcaeus IMHO, using a mixed approach for DocBlock annotation may be not the best. At least when you read reduced DocBlock, it does not contribute to a better understanding. I would say it can be confusing
Speaking of best practices: https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc-tags.md#59-param

2021-07-27 15:23 UTC, nicolas-grekas commented
Are you completely sure this is the only phpdoc that Magento needs? We removed much more, that's why I'm asking.
I'm fine reverting in 4.4, but we should keep that change in 5.4 IMHO.

2021-07-27 16:15 UTC, viktym commented
@Nicals currently Magento has dependency on "symfony/console": "~4.4.0". 
Do you have any ETA when symfony/console:4.4.29 with this fix for Magento can be released?

2021-07-27 16:27 UTC, mortenbirkelund commented
> So Magento is basically not doing bugfix releases?

Magento make quarterly releases, and anything else has to be patched manually on each shops either by using magentos patch tool (with a limited amount of patches) ; by using patch command on Linux or a library like cweagans.
https://devdocs.magento.com/guides/v2.4/comp-mgr/patching.html

So this is possible, but as stated by @hostep it will require alot of work by alot of people (all shops individually)
A bug fix release of symfony/console would be the easiest solution by far, and then hopefully magento will fix the actual problem in next release.

2021-07-27 16:42 UTC, derrabus commented
> and then hopefully magento will fix the actual problem in next release.

They'll have to. We really cannot anticipate which doc block change might break this little Magento tool again.

> Do you have any ETA when symfony/console:4.4.29 with this fix for Magento can be released?

The next regular release would be by the end of August.

2021-07-27 18:22 UTC, IbrahimS2 commented
@derrabus I fully agree with you, Why in the world is Magento not reading the "variables type properly", **it is already defined in the construct itself!** if not then and only then can fall back to PHP variables annotations.

Anyhow, I think the point here is to be part of the solution; if we can let this one slide so not everyone gets into this problem until a proper fix is presented in Magento would be highly appreciated.

2021-07-27 18:24 UTC, derrabus approved these changes
Agreed.

2021-07-27 19:05 UTC, derrabus commented
Thank you @brosenberger.

2021-07-27 19:05 UTC, merged

2021-07-27 19:09 UTC, derrabus commented
To be extra-sure: Can you please test your Magento installations with:
```JSON
{
    "symfony/console": "^4.4.29@dev"
}
```
… and confirm that the issue is gone and that there is no other doc block that breaks that tool?

2021-07-27 19:13 UTC, derrabus commented
As suggested by @nicolas-grekas, I have reverted the change while merging to the 5.4 branch.

2021-07-27 19:55 UTC, thomas-kl1 commented
@nicolas-grekas you shouldn't pay the Magento debt :(

2021-07-27 21:36 UTC, chernenm commented
> To be extra-sure: Can you please test your Magento installations with:
> 
> ```json
> {
>     "symfony/console": "^4.4.29@dev"
> }
> ```
> 
> … and confirm that the issue is gone and that there is no other doc block that breaks that tool?

hi @derrabus, Thank you for your help with this. We can confirm that everything works on Magento side with this change.

2021-07-29 06:35 UTC, ihor-sviziev commented
Hi @derrabus,
Could you release a stable version of the symfony/console as a hotfix for the Magento?

2021-07-29 08:30 UTC, derrabus commented
> Could you release a stable version of the symfony/console as a hotfix for the Magento?

@fabpot just did that.

2021-09-21 13:58 UTC, ihor-sviziev commented
FYI The original issue in the `laminas-code` with incorrect argument type detection when `@param` is not declared for all parameters got fixed in https://github.com/laminas/laminas-code/pull/95 and released https://github.com/laminas/laminas-code/releases/tag/4.4.3