Fix HttpClientInterface::withOptions declaration
symfony/symfony pull request #42358
Opened 2021-08-03 17:00 UTC by B-Galati

| Q             | A
| ------------- | ---
| Branch?       | 5.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| License       | MIT

Hello :handshake: 

I am opening the PR after noticing a warning in my IDE about method `\Symfony\Contracts\HttpClient\HttpClientInterface::withOptions` that should be used statically:
![image](https://user-images.githubusercontent.com/895123/128055674-08040e94-a649-443e-8fe0-18e5b8d19e0c.png)

I found weird, then check [the doc](https://symfony.com/doc/current/http_client.html#configuration) and noticed it was because of `@method` annotation.

Here is my analysis from my commit message:
>This method is not static and thus should not be declared as static.
>The return type is dynamic though. I don't know how it could be declared
>as a dynamic return type but it looks enough to me as the caller knows
>the type of object it manipulates. Using this method should not break
>the original typing detected by the IDE or static analysis tools.

2021-08-03 17:04 UTC, derrabus requested changes
This rather looks like a bug in the EA Extended plugin. `static` is the correct return type.

2021-08-03 17:13 UTC, ro0NL commented
i think `static` as return breaks the spec :D https://docs.phpdoc.org/3.0/guide/references/phpdoc/tags/method.html

the method is definitively non-static

2021-08-03 17:19 UTC, derrabus commented
> If the intended method is static, the static keyword can be placed before the return type to communicate that. In that case, a return type MUST be provided, as static on its own would mean that the method returns an instance of the child class which the method is called on.

2021-08-03 17:27 UTC, B-Galati commented
Thanks for the quick feedback @ro0NL and @derrabus!

@derrabus What do you mean in your last message?

For me, it looks like `static` is not a valid return type with `@method`. I guess it's because PHP does not allow `static` keyword as a return type.

2021-08-03 17:32 UTC, derrabus commented
> For me, it looks like `static` is not a valid return type with `@method`. I guess it's because PHP does not allow `static` keyword as a return type.

PHP does and so does the PHPDoc spec. I've quoted the passage from the spec.

2021-08-03 19:36 UTC, B-Galati commented
Indeed, it's working since PHP 8 :+1: thank!

https://3v4l.org/JeoB3

2021-08-03 19:46 UTC, derrabus commented
Closing because this is not a Symfony bug.

2021-08-03 19:46 UTC, closed without merging

2021-08-04 07:21 UTC, B-Galati commented
Thank you all for your help :+1: 

I will do more research and open an issue to EA extension if needed.