[Ldap] Make LdapAuthenticator an EntryPoint
symfony/symfony pull request #42354
Opened 2021-08-03 13:54 UTC by dcp-dev

| Q             | A
| ------------- | ---
| Branch?       | 5.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #42346
| License       | MIT
| Doc PR        | N/A

I added @chalasr's recommandations given in https://github.com/symfony/symfony/issues/42346#issuecomment-891188282

2021-08-05 12:35 UTC, chalasr requested changes
Thanks for the PR. 1 minor comment.
Sadly we don't have much tests for ldap-based authenticators so I'm ok to merge the patch without additional tests. But if you want to have a look and try to add some, that would be great.

2021-08-05 12:35 UTC, chalasr commented on src/Symfony/Component/Ldap/Security/LdapAuthenticator.php
> +            throw new LogicException(sprintf('Decorated authenticator must implement inerface "%s".', AuthenticationEntryPointInterface::class));
```suggestion
            throw new LogicException(sprintf('Decorated authenticator "%s" must implement interface "%s".', get_debug_type($this->authenticator), AuthenticationEntryPointInterface::class));
```

2021-08-06 13:36 UTC, derrabus approved these changes

2021-08-06 13:37 UTC, chalasr approved these changes

2021-08-06 14:16 UTC, wouterj commented
Hi! I guess this is a question for @chalasr as he proposed this solution, but I don't think the `LogicException` works/is nice. This means that if the internal authenticator isn't an entry point, a user will get a 500 instead of the default authentication entry point behavior. It's perfectly valid for an authenticator to not be an entry point (e.g. see the `JsonLoginFactory`, which also has a `json_login_ldap` variant). Am I missing something or should we find a different way of approaching this? (maybe a special exception class that we catch when calling the `start()` method?)

2021-08-06 15:47 UTC, chalasr requested changes
Just blocking merge to give us some time to address Wouter’s concerns :)

2021-09-17 09:02 UTC, chalasr commented
> maybe a special exception class that we catch when calling the start() method?

That's the best approach AFAICT. I just pushed a commit doing that.
Review needed :)

2021-09-26 12:14 UTC, chalasr commented
PR ready (I need this for #42582)

2021-09-26 16:34 UTC, fabpot approved these changes

2021-09-26 16:35 UTC, fabpot commented
Thank you @dcp-dev.

2021-09-26 16:35 UTC, merged

2021-09-26 16:35 UTC, fabpot commented
@chalasr Merged now :)

2021-09-26 16:35 UTC, chalasr commented
Great, thanks!