[serializer] Save missing arguments in MissingConstructorArgumentsException
symfony/symfony pull request #42712
Opened 2021-08-24 17:09 UTC by BafS

| Q             | A
| ------------- | ---
| Branch?       | 6.0 (but it could maybe be 5.4?)
| Bug fix?      | no
| New feature?  | not really
| Deprecations? | no
| Tickets       | Fix #... 
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

It's currently not possible to get the information about which constructor argument is missing (except by doing regex in the exception message string). Having this information is useful when we want to have an input transformer without the need to set every fields to nullable.

For example if we have this flow: `[request payload] -> [normalizer/unserializer] -> [dto] -> [validation]`, each field must be nullable to not have exception during the normalization and then we still need to validate, instead we could catch `MissingConstructorArgumentsException`, handle it and make a nice http exception.

2021-09-07 11:13 UTC, nicolas-grekas commented
That'd be for 5.4 yes. Can you please retarget?

2021-09-21 06:42 UTC, fabpot requested changes
Looks good to me, can you rebase on current 5.4?
Can you also add a note in the CHANGELOG of the component?

2021-09-21 13:24 UTC, BafS commented
Thanks. Rebased + readme updated, let me know if it's ok

2021-09-21 13:31 UTC, fabpot approved these changes

2021-09-21 13:32 UTC, fabpot commented
Thank you @BafS.

2021-09-21 13:32 UTC, merged