[Mailer] Added OhMySMTP Bridge
symfony/symfony pull request #42710
Opened 2021-08-24 15:53 UTC by paul-oms

This adds the https://ohmysmtp.com bridge to enable sending over the [OhMySMTP](https://ohmysmtp.com) API.

| Q             | A
| ------------- | ---
| Branch?       | 5.4 for features / 4.4 or 5.3 for bug fixes 
| Bug fix?      | no
| New feature?  | yes 
| Deprecations? | no 
| Tickets       | none 
| License       | MIT
| Doc PR        | symfony/symfony-docs#15747...

2021-08-24 20:14 UTC, paul-oms commented
Hi Core team - from what I can tell the failing tests are all failing on the 5.4 branch as well as here. So I assume I don't need to try to fix any more of these. Let me know if that's not correct. Would love to get this into the 5.4 release, thanks!

2021-08-24 22:23 UTC, derrabus commented
> Hi Core team - from what I can tell the failing tests are all failing on the 5.4 branch as well as here. So I assume I don't need to try to fix any more of these.

You don't need to fix tests you didn't break. 😃

2021-08-25 06:05 UTC, OskarStark reviewed
Thanks for providing a new bridge, this is much appreciated 👍🏻

I left some comments

2021-08-25 06:05 UTC, OskarStark commented on src/Symfony/Component/Mailer/Bridge/Ohmysmtp/CHANGELOG.md
> + * Added the bridge
```suggestion
5.4
---

 * Add the bridge
```

2021-08-25 06:05 UTC, OskarStark commented on src/Symfony/Component/Mailer/Bridge/Ohmysmtp/README.md
> +OhMySMTP Bridge
Please rename the folder to OhMySmtp

2021-08-25 06:05 UTC, OskarStark commented on src/Symfony/Component/Mailer/Bridge/Ohmysmtp/README.md
> +
Please add a DSN example, you can check a README from the Notifier bridges, thanks

2021-08-25 06:05 UTC, OskarStark commented on src/Symfony/Component/Mailer/Bridge/Ohmysmtp/Tests/Transport/OhmysmtpApiTransportTest.php
> +class OhmysmtpApiTransportTest extends TestCase
final please

```suggestion
class OhMySmtpApiTransportTest extends TestCase
```

Please rename all classes accordingly, thanks

2021-08-25 06:05 UTC, OskarStark commented on src/Symfony/Component/Mailer/Bridge/Ohmysmtp/Tests/Transport/OhmysmtpTransportFactoryTest.php
> +class OhmysmtpTransportFactoryTest extends TransportFactoryTestCase
final please, same for the other test classes

2021-08-25 06:05 UTC, OskarStark commented on src/Symfony/Component/Mailer/Bridge/Ohmysmtp/Transport/OhmysmtpApiTransport.php
> +class OhmysmtpApiTransport extends AbstractApiTransport
Final please

2021-08-25 06:05 UTC, OskarStark commented on src/Symfony/Component/Mailer/Bridge/Ohmysmtp/Transport/OhmysmtpApiTransport.php
> +                'Accept' => 'application/json',
Can be removed, as you are using the json key below, which send the header automatically

2021-08-25 06:05 UTC, OskarStark commented on src/Symfony/Component/Mailer/Bridge/Ohmysmtp/Transport/OhmysmtpApiTransport.php
> +                'Content-Type' => 'application/json',
Can be removed, as you are using the json key below, which send the header automatically

2021-08-25 06:05 UTC, OskarStark commented on src/Symfony/Component/Mailer/Bridge/Ohmysmtp/Transport/OhmysmtpSmtpTransport.php
> +class OhmysmtpSmtpTransport extends EsmtpTransport
Final please

2021-08-25 06:05 UTC, OskarStark commented on src/Symfony/Component/Mailer/Bridge/Ohmysmtp/Transport/OhmysmtpTransportFactory.php
> +        $user = $this->getUser($dsn);
Let's copy this inside the ifs and duplicate it to first make sure the scheme matches, in case sth goes wrong when extracting the user

2021-08-25 06:05 UTC, OskarStark commented on src/Symfony/Component/Mailer/Bridge/Ohmysmtp/composer.json
> +    "authors": [
You can add yourself as an author here, thanks

2021-08-25 18:31 UTC, paul-oms commented on src/Symfony/Component/Mailer/Bridge/Ohmysmtp/Transport/OhmysmtpApiTransport.php
> +                'Content-Type' => 'application/json',
Hi @OskarStark I tested this end to end and the content-type and accept headers were not set on the outbound request, so the OhMySMTP API rejected the request - so I think we do need to leave this in?

2021-08-25 18:31 UTC, paul-oms commented on src/Symfony/Component/Mailer/Bridge/Ohmysmtp/Transport/OhmysmtpApiTransport.php
> +                'Accept' => 'application/json',
Hi @OskarStark I tested this end to end and the content-type and accept headers were not set on the outbound request, so the OhMySMTP API rejected the request - so I think we do need to leave this in?

2021-08-25 19:03 UTC, OskarStark commented on src/Symfony/Component/Mailer/Bridge/Ohmysmtp/Transport/OhmysmtpApiTransport.php
> +                'Accept' => 'application/json',
cc @nicolas-grekas am I missing sth? It should set the headers, right?

2021-08-25 19:46 UTC, paul-oms commented
@OskarStark  regarding the class names, it seems Fabbot is enforcing lowercase e.g. OhmysmtpTransportFactory over OhMySmtpTransportFactory

Which way should it be?

2021-08-25 20:10 UTC, OskarStark commented
To me it should be the second one

cc @fabpot

2021-08-25 20:10 UTC, OskarStark commented
Maybe it is because the folder is named lowercase?

2021-08-25 20:38 UTC, paul-oms commented
> Maybe it is because the folder is named lowercase?

You were right, took me a bit of wrestling with git to get it right but it's there now. Thanks!

2021-08-26 01:08 UTC, OskarStark commented on src/Symfony/Component/Mailer/Bridge/OhMySmtp/CHANGELOG.md
> +-----
Underline should match the length of the headline

2021-08-26 01:08 UTC, OskarStark commented on src/Symfony/Component/Mailer/Bridge/OhMySmtp/Tests/Transport/OhMySmtpApiTransportTest.php
> +class OhMySmtpApiTransportTest extends TestCase
```suggestion
final class OhMySmtpApiTransportTest extends TestCase
```

2021-08-26 01:08 UTC, OskarStark commented on src/Symfony/Component/Mailer/Bridge/OhMySmtp/Tests/Transport/OhMySmtpSmtpTransportTest.php
> +class OhMySmtpSmtpTransportTest extends TestCase
```suggestion
final class OhMySmtpSmtpTransportTest extends TestCase
```

2021-08-26 01:08 UTC, OskarStark commented on src/Symfony/Component/Mailer/Bridge/OhMySmtp/Tests/Transport/OhMySmtpTransportFactoryTest.php
> +class OhMySmtpTransportFactoryTest extends TransportFactoryTestCase
```suggestion
final class OhMySmtpTransportFactoryTest extends TransportFactoryTestCase
```

2021-08-26 01:08 UTC, OskarStark commented on src/Symfony/Component/Mailer/Bridge/OhMySmtp/Transport/OhMySmtpApiTransport.php
> +class OhMySmtpApiTransport extends AbstractApiTransport
```suggestion
final class OhMySmtpApiTransport extends AbstractApiTransport
```

2021-08-26 01:08 UTC, OskarStark commented on src/Symfony/Component/Mailer/Bridge/OhMySmtp/Transport/OhMySmtpSmtpTransport.php
> +class OhMySmtpSmtpTransport extends EsmtpTransport
```suggestion
final class OhMySmtpSmtpTransport extends EsmtpTransport
```

2021-08-26 05:35 UTC, fabpot commented
> @OskarStark regarding the class names, it seems Fabbot is enforcing lowercase e.g. OhmysmtpTransportFactory over OhMySmtpTransportFactory
> 
> Which way should it be?

`OhMySmtpTransportFactory` is the one to use to be consistent with the Symfony class naming convention.

2021-08-26 05:38 UTC, fabpot requested changes

2021-08-26 05:38 UTC, fabpot commented on src/Symfony/Component/Mailer/Bridge/OhMySmtp/composer.json
> +    "name": "symfony/ohmysmtp-mailer",
must be:

```suggestion
    "name": "symfony/oh-my-smtp-mailer",
```

2021-08-26 05:38 UTC, fabpot commented on src/Symfony/Component/Mailer/Exception/UnsupportedSchemeException.php
> +            'package' => 'symfony/ohmysmtp-mailer',
```suggestion
            'package' => 'symfony/oh-my-smtp-mailer',
```

2021-08-26 05:38 UTC, fabpot commented on src/Symfony/Component/Mailer/Tests/Exception/UnsupportedSchemeExceptionTest.php
> +        yield ['ohmysmtp', 'symfony/ohmysmtp-mailer'];
```suggestion
        yield ['ohmysmtp', 'symfony/oh-my-smtp-mailer'];
```

2021-08-26 08:05 UTC, paul-oms commented
Thanks @fabpot and @OskarStark for the review. All requested changes have been completed.

2021-08-26 11:28 UTC, OskarStark commented on src/Symfony/Component/Mailer/Bridge/OhMySmtp/CHANGELOG.md
> +---------
Underline too long

2021-08-26 11:28 UTC, OskarStark commented on src/Symfony/Component/Mailer/Bridge/OhMySmtp/Tests/Transport/OhMySmtpApiTransportTest.php
> +    public function getTransportData()
```suggestion
    public function getTransportData(): array
```

2021-08-26 11:29 UTC, OskarStark commented on src/Symfony/Component/Mailer/Bridge/Ohmysmtp/Transport/OhmysmtpApiTransport.php
> +                'Accept' => 'application/json',
I double checked and only Content-Type can be removed, Accept is needed if needed by the API 

![image](https://user-images.githubusercontent.com/995707/130955131-82441ad9-0bdc-4b45-b59a-73bf7f659293.jpeg)

2021-08-26 11:29 UTC, OskarStark commented
After my comments we are good to go

2021-08-26 11:54 UTC, fabpot approved these changes

2021-08-26 11:55 UTC, fabpot commented
Thank you @paul-oms.

2021-08-26 11:59 UTC, closed without merging