[Form] Add a hash_mapping option to PasswordType
symfony/symfony pull request #42883
Opened 2021-09-04 05:54 UTC by Seb33300

| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #29066
| License       | MIT
| Doc PR        | TODO

Following https://github.com/symfony/symfony/pull/42807 with a different implementation.

This PR adds a new `hash_mapping` option to `PasswordType`.

The `hash_mapping` option can be set with a property path where we want to store the hashed password.

Some questions I have:
- Is it better to move this out from the `Core` to a dedicated extension? (same as Csrf, Validator ... ?)
- Not sure if this can be made generic (not only for `PasswordAuthenticatedUserInterface` entities)
- Should we generate a salt if the entity is using a legacy algorithm?

I am submitting this PR to get feedback for now, and if they are positive, I will continue the work to add tests and documentation.

2021-09-04 09:07 UTC, OskarStark commented on src/Symfony/Component/Form/CHANGELOG.md
> + * Added a `hash_mapping` option to `PasswordType`
```suggestion
 * Add `hash_mapping` option to `PasswordType`
```

2021-09-04 17:50 UTC, yceruto requested changes
I continue thinking that this hashing process does not belong to the Form flow (at least under the current possibilities it gives us) because this must be done after validation passed successfully (and not only validations linked to this password field itself but the entire form must be valid). Doing this before it causes security issues and doing this after it looks out of Form's responsibility to modify directly the underlying data without any standard Form's mechanism (data mapper, etc).

2021-09-04 17:50 UTC, yceruto commented on src/Symfony/Component/Form/Extension/Core/EventListener/PasswordHasherListener.php
> +            FormEvents::SUBMIT => ['hashPassword', -256],
if `hash_mapping` is referring to the same property path as the mapped field then we are hashing the plain password before validating it, which looks wrong.

2021-09-04 17:50 UTC, yceruto commented on src/Symfony/Component/Form/Extension/Core/Type/PasswordType.php
> +            'hash_mapping' => null,
In this new approach `hash_mapping` must be different from `property_path` to avoid the issue explained above.

2021-09-04 17:50 UTC, yceruto commented on src/Symfony/Component/Form/Extension/Core/EventListener/PasswordHasherListener.php
> +            FormEvents::SUBMIT => ['hashPassword', -256],
Also, if something goes wrong during plain password validation you can end up with a wrong hashed password (from https://github.com/symfony/symfony/pull/42807#pullrequestreview-746314402 `in the DB if your object is a Doctrine entity and you flush changes, but also potentially when serializing the user in the session if the edited user is the currently authenticated user`)

2021-09-05 03:53 UTC, Seb33300 commented on src/Symfony/Component/Form/Extension/Core/Type/PasswordType.php
> +            'hash_mapping' => null,
Yes you are right, and this is also the reason we cannot use the previous PR.

2021-09-05 04:06 UTC, Seb33300 commented on src/Symfony/Component/Form/Extension/Core/EventListener/PasswordHasherListener.php
> +            FormEvents::SUBMIT => ['hashPassword', -256],
The purpose of this PR is to store the password hash in a different property. Ideally using an unmapped PasswordType to request the password.
So even if the hash is generated before validating the plain password, the plain password is not lost and will still be validated normally during the validation process.

Also, if some validation constraints are put on the entity password property (the hashed one), for example a `NotBlank`, the hash needs to be populated before the validation to work.

And regarding your second comment, if something goes wrong during the validation, "the issue" you described is not really specific to this feature.
All others fields of the form are also already populate in the entity before validation. The same behavior already happens event if we don't use this new feature.

2021-09-07 04:24 UTC, Seb33300 commented on src/Symfony/Component/Form/Extension/Core/Type/PasswordType.php
> +            'hash_mapping' => null,
Fixed

2021-09-07 09:35 UTC, Seb33300 commented on src/Symfony/Component/Form/Extension/Core/Type/PasswordType.php
> +                throw new InvalidConfigurationException('The hash_mapping property must be a different.');
Not sure if I had to use `InvalidConfigurationException` or `InvalidOptionsException`

2021-09-29 07:28 UTC, Seb33300 commented
I created the documentation PR.

2022-05-01 13:39 UTC, Seb33300 commented
Closed for https://github.com/symfony/symfony/pull/46224

2022-05-01 13:39 UTC, Seb33300 commented
Closed for https://github.com/symfony/symfony/pull/46224

2022-05-01 13:39 UTC, closed without merging