[Mailer] Adding support for TagHeader and MetadataHeader to the Sendgrid API transport
symfony/symfony pull request #43018
Opened 2021-09-14 11:03 UTC by gnito-org

| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | None
| License       | MIT
| Doc PR        | https://github.com/symfony/symfony-docs/pull/15816

I added support for tags and metadata to the Mailer Sendgrid API transport, in response to this discussion: https://github.com/symfony/symfony/discussions/42481

The relevant Sendgrid API documentation is located at:

- https://docs.sendgrid.com/for-developers/tracking-events/event#custom-arguments
- https://docs.sendgrid.com/api-reference/mail-send/mail-send

2021-09-14 11:48 UTC, gnito-org commented
I don't think the two failing tests were caused by this pull request. The 8.0, low deps test complains about `Error: Class "Symfony\Component\Mailer\Header\TagHeader" not found`, which makes no sense. The PHPUnit tests pass on my local machine with PHP 8.

2021-09-14 19:27 UTC, OskarStark commented on src/Symfony/Component/Mailer/Bridge/Sendgrid/CHANGELOG.md
> +* Adding support for `TagHeader` and `MetadataHeader` to the Sendgrid API transport
```suggestion
 * Add support for `TagHeader` and `MetadataHeader` to the Sendgrid API transport
```

2021-09-14 19:27 UTC, OskarStark commented on src/Symfony/Component/Mailer/CHANGELOG.md
> + * Adding support for `TagHeader` and `MetadataHeader` to the Sendgrid API transport
This line can be removed here

2021-09-15 05:32 UTC, OskarStark commented on src/Symfony/Component/Mailer/Bridge/Sendgrid/CHANGELOG.md
> +5.3
```suggestion
5.4
```

2021-09-15 06:18 UTC, fabpot requested changes

2021-09-15 06:18 UTC, fabpot commented on src/Symfony/Component/Mailer/CHANGELOG.md
> +
To be reverted

2021-09-15 06:18 UTC, fabpot commented on src/Symfony/Component/Mailer/Bridge/Sendgrid/Transport/SendgridApiTransport.php
> +                if (\count($categories) < 10) {
I would throw an exception if we reach the maximum instead of silently ignoring the tag.

2021-09-15 06:18 UTC, fabpot commented on src/Symfony/Component/Mailer/Bridge/Sendgrid/Transport/SendgridApiTransport.php
> +                continue;
can you use an `elseif` instead?

2021-09-15 06:18 UTC, fabpot commented on src/Symfony/Component/Mailer/Bridge/Sendgrid/Transport/SendgridApiTransport.php
> +                continue;
and an `else` here

2021-09-15 10:51 UTC, gnito-org commented
@fabpot Thank you for your suggested changes. I coded it that way because I thought I was following Symfony standards by replicating the way that the [Mailchimp](https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Mailer/Bridge/Mailchimp/Transport/MandrillApiTransport.php), [Postmark](https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Mailer/Bridge/Postmark/Transport/PostmarkApiTransport.php), and [Sendinblue](https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Mailer/Bridge/Sendinblue/Transport/SendinblueApiTransport.php) API transports were coded.

2021-09-15 11:38 UTC, fabpot approved these changes

2021-09-15 11:39 UTC, fabpot commented
Thank you @gnito-org.

2021-09-15 11:39 UTC, merged