Update FirebaseTransport.php
symfony/symfony pull request #43073
Opened 2021-09-17 09:06 UTC by dima-gr

prevent setting null value from firebase response, previous pull request - https://github.com/symfony/symfony/pull/43040

| Q             | A
| ------------- | ---
| Branch?       | 5.4 for features / 4.4 or 5.3 for bug fixes 
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #... 
| License       | MIT
| Doc PR        | symfony/symfony-docs#...

2021-09-17 09:52 UTC, fabpot requested changes

2021-09-17 09:52 UTC, fabpot commented on src/Symfony/Component/Notifier/Bridge/Firebase/FirebaseTransport.php
> +        $sentMessage->setMessageId(isset($success['results'][0]['message_id']) ?: '');
```suggestion
        $sentMessage->setMessageId($success['results'][0]['message_id'] ?? '');
```

2021-09-17 11:38 UTC, OskarStark commented on src/Symfony/Component/Notifier/Bridge/Firebase/FirebaseTransport.php
> +        $sentMessage->setMessageId($success['results'][0]['message_id'] ?? '');
Let's wrap this in an if Statement and do not call the setMessageId method

2021-09-19 13:11 UTC, fabpot approved these changes

2021-09-19 13:12 UTC, fabpot commented
Thank you @dima-gr.

2021-09-19 13:12 UTC, merged

2021-09-19 19:49 UTC, OskarStark commented
Now one need to check for null and empty string.

I am still in favor of not calling the method to only return a string when it is a valid message id.

WDYT @fabpot