[FrameworkBundle] Avoid secrets:decrypt-to-local command to fail
symfony/symfony pull request #43137
Opened 2021-09-22 16:13 UTC by 94noni

| Q             | A
| ------------- | ---
| Branch?       | 5.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix https://github.com/symfony/symfony/issues/42038
| License       | MIT
| Doc PR        | .

Small PR to fix this issue I encounter as well
For now I've not opted for solutions exposed in the issue, please discuss here
Thank you,

2021-09-23 05:55 UTC, fabpot requested changes
Made a small suggestion for the error message

2021-09-23 05:55 UTC, fabpot commented on src/Symfony/Bundle/FrameworkBundle/Command/SecretsDecryptToLocalCommand.php
> +                $io->error($this->vault->getLastMessage() ?? \sprintf('An error occured for secret "%s" and it will be skipped.', $k));
```suggestion
                $io->error($this->vault->getLastMessage() ?? \sprintf('Secret "%s" has been skipped as there was an error reading it.', $k));
```

2021-09-23 07:38 UTC, 94noni commented
@fabpot comment addressed, thx

2021-09-24 16:07 UTC, nicolas-grekas commented
Thank you @94noni.

2021-09-24 16:07 UTC, merged