[Notifier] Add sms77 Notifier Bridge
symfony/symfony pull request #43134
Opened 2021-09-22 09:36 UTC by matthiez

| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| License       | MIT
| Doc PR        | [symfony/symfony-docs/pull/15840](https://github.com/symfony/symfony-docs/pull/15840)
| Recipe PR | [symfony/recipes/pull/1003](https://github.com/symfony/recipes/pull/1003)

Add sms77 bridge to Symfony Notifier.
A Germany based SMS provider established in 2003.

2021-09-23 07:06 UTC, qdequippe approved these changes

2021-09-25 07:14 UTC, OskarStark commented on src/Symfony/Component/Notifier/Bridge/Sms77/README.md
> +SMS//_DSN=sms77://APIKEY@default?from=FROM
```suggestion
SMS77_DSN=sms77://APIKEY@default?from=FROM
```

2021-09-25 07:15 UTC, OskarStark commented on src/Symfony/Component/Notifier/Bridge/Sms77/README.md
> + - `APIKEY` is your sms77 API key
```suggestion
 - `API_KEY` is your sms77 API key
```

2021-09-25 07:17 UTC, OskarStark commented on src/Symfony/Component/Notifier/Bridge/Sms77/Tests/Sms77TransportFactoryTest.php
> +        yield 'missing auth token' => ['sms77://host?from=TEST'];
```suggestion
        yield 'missing api key' => ['sms77://host?from=TEST'];
```

2021-09-25 07:18 UTC, OskarStark requested changes
Only some minor things

2021-09-25 07:18 UTC, OskarStark commented on src/Symfony/Component/Notifier/Bridge/Sms77/README.md
> +sms77 Notifier
```suggestion
Sms77 Notifier
```

2021-09-29 02:33 UTC, OskarStark approved these changes

2021-09-29 02:34 UTC, OskarStark commented
Please check fabbot and fix the coding standards. Thanks

2021-10-11 14:59 UTC, javiereguiluz approved these changes

2021-10-13 06:15 UTC, fabpot approved these changes

2021-10-13 06:16 UTC, fabpot commented
Thank you @matthiez.

2021-10-13 06:19 UTC, closed without merging