[Cache] Split PdoAdapter into DoctrineDbalAdapter
symfony/symfony pull request #43362
Opened 2021-10-07 14:57 UTC by GromNaN

| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | yes
| Tickets       | Fix #42962
| License       | MIT
| Doc PR        | symfony/symfony-docs#15903

2021-10-08 09:37 UTC, stof commented on src/Symfony/Component/Cache/Adapter/DoctrineDbalAdapter.php
> +class DoctrineDbalAdapter extends AbstractAdapter implements PruneableInterface
I suggest making the new class final

2021-10-08 09:37 UTC, stof commented on src/Symfony/Component/Cache/Adapter/DoctrineDbalAdapter.php
> +     * @throws \DomainException When an unsupported PDO driver is used
this one looks wrong. There is no PDO driver involved

2021-10-08 09:37 UTC, stof commented on src/Symfony/Component/Cache/Adapter/DoctrineDbalAdapter.php
> +            $deleteSql .= " AND $this->idCol LIKE :namespace";
should be `LIKE ?`

2021-10-08 09:37 UTC, stof commented on src/Symfony/Component/Cache/Adapter/DoctrineDbalAdapter.php
> +        $sql = str_pad('', (\count($ids) << 1) - 1, '?,');
This can be simplified. DBAL supports `Connection::PARAM_STR_ARRAY` and `Connection::PARAM_STR_INT` which do that for you

2021-10-08 09:37 UTC, stof commented on src/Symfony/Component/Cache/Adapter/DoctrineDbalAdapter.php
> +                throw new \LogicException(sprintf('The adapter "%s" does not support the mysqli driver, use pdo_mysql instead.', static::class));
is it still unsupported as you switched almost all parameters to use `?` ?

2021-10-08 09:37 UTC, stof commented on src/Symfony/Component/Cache/Adapter/DoctrineDbalAdapter.php
> +    private function getDriver(): string
Naming that `getDriver` when it should instead look at the DBAL platform (see the Lock component) looks weird to me.

2021-10-08 09:37 UTC, stof commented on src/Symfony/Component/Cache/Adapter/DoctrineDbalAdapter.php
> +        // How does it works? $id & $data are used but not defined outside the loop, and they are not used inside the loop.
does it actually work ? Do we have tests reaching this code ?

2021-10-08 10:00 UTC, GromNaN commented on src/Symfony/Component/Cache/Adapter/DoctrineDbalAdapter.php
> +                throw new \LogicException(sprintf('The adapter "%s" does not support the mysqli driver, use pdo_mysql instead.', static::class));
There is some complex query composition in `doSave` method that uses named params. I need to rework this part.

2021-10-08 12:45 UTC, GromNaN commented on src/Symfony/Component/Cache/Adapter/DoctrineDbalAdapter.php
> +        $sql = str_pad('', (\count($ids) << 1) - 1, '?,');
Thanks for the tip.

2021-10-08 12:45 UTC, GromNaN commented on src/Symfony/Component/Cache/Adapter/DoctrineDbalAdapter.php
> +    private function getDriver(): string
Renamed to `getPlatformName`.

2021-10-08 12:45 UTC, GromNaN commented on src/Symfony/Component/Cache/Adapter/DoctrineDbalAdapter.php
> +        // How does it works? $id & $data are used but not defined outside the loop, and they are not used inside the loop.
It works. Thanks to binding done by reference 🤓

2021-10-08 12:45 UTC, GromNaN commented on src/Symfony/Component/Cache/Adapter/DoctrineDbalAdapter.php
> +                throw new \LogicException(sprintf('The adapter "%s" does not support the mysqli driver, use pdo_mysql instead.', static::class));
Fixed.

2021-10-08 13:57 UTC, GromNaN commented on src/Symfony/Component/Cache/Adapter/DoctrineDbalAdapter.php
> +class DoctrineDbalAdapter extends AbstractAdapter implements PruneableInterface
The final class cannot be mocked for `DoctrineDbalCacheAdapterSchemaSubscriberTest`. I added an interface to cover this specific feature.

2021-10-08 20:59 UTC, GromNaN commented
Tests are green.
Tested locally with mysql & postgres.

2021-10-11 10:33 UTC, derrabus commented on src/Symfony/Bridge/Doctrine/Tests/SchemaListener/DoctrineDbalCacheAdapterSchemaSubscriberTest.php
> +        }
You've bumped the `doctrine/cache` dependency to 5.4, so this block should not be needed.

2021-10-11 14:24 UTC, derrabus commented on src/Symfony/Component/Cache/Adapter/DoctrineSchemaConfiguratorInterface.php
> +interface DoctrineSchemaConfiguratorInterface
This interface has been added for testing purposes only, correct? In that case, we should flag it as `@internal`. It should not become part of the public API of the cache component.

2021-10-11 14:28 UTC, derrabus commented on src/Symfony/Component/Cache/Adapter/DoctrineDbalAdapter.php
> +     * Compatible with in doctrine/dbal ^2.13 and ^3.0.
```suggestion
     * Compatible with in doctrine/dbal ^2.13 and ^3.1.
```

2021-10-11 14:30 UTC, derrabus commented on src/Symfony/Component/Cache/Adapter/DoctrineDbalAdapter.php
> +                    ][$driver->getDatabasePlatform()->getName()] ?? \get_class($driver);
We have changed the lock component to perform `instanceof` checks on `$driver->getDatabasePlatform()` instead because the driver might be decorated and `AbstractPlatform::getName()` will go away eventually. We should do the same here – either now or in a follow-up.

2021-10-11 14:31 UTC, derrabus requested changes

2021-10-11 14:31 UTC, derrabus commented on src/Symfony/Component/Cache/composer.json
> +        "symfony/phpunit-bridge": "*@dev"
Must be reverted.

2021-10-11 14:39 UTC, derrabus commented on src/Symfony/Bridge/Doctrine/composer.json
> +        "doctrine/dbal": "^2.13.1|^3.0",
Can you please apply this bump to the root composer.json as well?

2021-10-11 19:36 UTC, GromNaN commented on src/Symfony/Component/Cache/Adapter/DoctrineDbalAdapter.php
> +                    ][$driver->getDatabasePlatform()->getName()] ?? \get_class($driver);
Thanks for the note, I switched to use the platform classes. The default value doesn't matter since it leads to a default portable behavior.

2021-10-12 12:30 UTC, derrabus commented on composer.json
> +        "doctrine/dbal": "^2.13.1|^3.0",
Please also update the `conflict` block in this file.

2021-10-12 12:31 UTC, derrabus commented on src/Symfony/Bridge/Doctrine/SchemaListener/DoctrineDbalCacheAdapterSchemaSubscriber.php
> +     * @param iterable|DoctrineDbalAdapter[] $dbalAdapters
```suggestion
     * @param iterable<mixed, DoctrineSchemaConfiguratorInterface> $dbalAdapters
```

2021-10-12 12:32 UTC, derrabus approved these changes

2021-10-12 12:34 UTC, derrabus requested changes

2021-10-12 12:34 UTC, derrabus commented on src/Symfony/Component/Cache/Adapter/DoctrineDbalAdapter.php
> +            case $platform instanceof \Doctrine\DBAL\Driver\PDO\PgSQL\Driver:
```suggestion
            case $platform instanceof \Doctrine\DBAL\Platforms\PostgreSQLPlatform:
```

`$platform` should never be a driver.

2021-10-14 18:26 UTC, GromNaN commented on src/Symfony/Component/Cache/Adapter/DoctrineDbalAdapter.php
> +            case $platform instanceof \Doctrine\DBAL\Driver\PDO\PgSQL\Driver:
Thanks for the review. I applied the patches and rebased the branch.

2021-10-16 16:37 UTC, fabpot requested changes

2021-10-16 16:37 UTC, fabpot commented on src/Symfony/Component/Cache/CHANGELOG.md
> + * made `LockRegistry` use semaphores when possible
Shoudl be reverted, we are now using `Make ...` instead of `made ...`.

2021-10-16 16:37 UTC, fabpot commented on src/Symfony/Component/Cache/CHANGELOG.md
> + * deprecated usage of `PdoAdapter` with `Doctrine\DBAL\Connection` or DBAL url
URL instead of url

2021-10-16 16:37 UTC, fabpot commented on UPGRADE-5.4.md
> + * Deprecate usage of `PdoAdapter` with a `Doctrine\DBAL\Connection` or a DBAL url. Use the new `DoctrineDbalAdapter` instead
URL

2021-10-17 08:31 UTC, GromNaN commented on src/Symfony/Bridge/Doctrine/Tests/SchemaListener/DoctrineDbalCacheAdapterSchemaSubscriberTest.php
> +        }
Removed this check, but the test will fail till the PR get merged into 5.4

```
Symfony\Bridge\Doctrine\Tests\SchemaListener\DoctrineDbalCacheAdapterSchemaSubscriberTest::testPostGenerateSchema
PHPUnit\Framework\MockObject\UnknownTypeException: Class or interface "Symfony\Component\Cache\Adapter\DoctrineSchemaConfiguratorInterface" does not exist
```

2021-10-18 08:43 UTC, derrabus commented on src/Symfony/Component/Cache/Adapter/DoctrineDbalAdapter.php
> +                $result = $stmt->executeQuery();
We prefer use `executeStatement()` here because we're executing an INSERT or UPDATE statement and we don't expect a result set to be returned.

2021-10-18 08:44 UTC, derrabus commented on src/Symfony/Component/Cache/Adapter/DoctrineDbalAdapter.php
> +                $result = $stmt->executeQuery();
Same here.

2021-10-18 10:02 UTC, stof commented on src/Symfony/Component/Cache/Adapter/DoctrineDbalAdapter.php
> +                $result = $stmt->executeQuery();
and this will make the code compatible with PrimaryReadReplicaConnection without issues

2021-10-18 10:43 UTC, GromNaN commented on src/Symfony/Component/Cache/Adapter/DoctrineDbalAdapter.php
> +                $result = $stmt->executeQuery();
That's right, fixed in https://github.com/symfony/symfony/pull/43362/commits/a44a730223e3cdebaa1dc95a1c665d610d7d238e

2021-10-18 20:27 UTC, derrabus approved these changes

2021-10-19 06:47 UTC, fabpot commented
Thank you @GromNaN.

2021-10-19 06:47 UTC, merged

2021-11-14 11:44 UTC, ostrolucky commented
Would be great if someone changed this in DoctrineBundle. I think that currently this functionality is silently broken with Symfony 6, because in bundle we use class_exists checks for deprecated class that was removed from Symfony 6. This is why I didn't make it easy for symfony folks to declare symfony 6 compatibility btw. This change came after we declared compatibility with Symfony 6 and now constraints are wrong because this is most likely broken.