[HttpFoundation] Deprecate passing null as $requestIp in IpUtils
symfony/symfony pull request #43411
Opened 2021-10-12 14:19 UTC by W0rma

| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | yes
| Tickets       | https://github.com/symfony/symfony/issues/43350#issuecomment-936951604
| License       | MIT
| Doc PR        |

2021-10-13 11:09 UTC, derrabus requested changes
Thank you for working on this topic!

Let's avoid the `checkIp()` if the IP to check is `null`. We already know the result.

2021-10-13 11:09 UTC, derrabus commented on UPGRADE-5.4.md
> + * Deprecate passing `null` as `$requestIp` to `IpUtils::__checkIp()`, `IpUtils::__checkIp4()` or `IpUtils::__checkIp6()`, pass an empty string instead.
```suggestion
 * Deprecate passing `null` as `$requestIp` to `IpUtils::checkIp()`, `IpUtils::checkIp4()` or `IpUtils::checkIp6()`, pass an empty string instead.
```

2021-10-13 11:09 UTC, derrabus commented on src/Symfony/Component/HttpClient/NoPrivateNetworkHttpClient.php
> +                if (IpUtils::checkIp($info['primary_ip'] ?? '', $subnets ?? self::PRIVATE_SUBNETS)) {
```suggestion
                if ($info['primary_ip'] && IpUtils::checkIp($info['primary_ip'], $subnets ?? self::PRIVATE_SUBNETS)) {
```

2021-10-13 11:09 UTC, derrabus commented on src/Symfony/Component/HttpKernel/HttpCache/SubRequestHandler.php
>          if (!IpUtils::checkIp($remoteAddr, $trustedProxies)) {
```suggestion
        $remoteAddr = $request->server->get('REMOTE_ADDR');
        if (!$remoteAddr || !IpUtils::checkIp($remoteAddr, $trustedProxies)) {
```

2021-10-13 11:09 UTC, derrabus commented on src/Symfony/Component/HttpFoundation/Tests/IpUtilsTest.php
> -            [false, null, '1.2.3.4/1'],
Please move the deprecated test cases into a new test that also checks if the deprecation has been triggered.

2021-10-15 17:24 UTC, W0rma commented on src/Symfony/Component/HttpFoundation/Tests/IpUtilsTest.php
> -            [false, null, '1.2.3.4/1'],
done

2021-10-16 09:46 UTC, derrabus approved these changes

2021-10-16 10:12 UTC, fabpot approved these changes

2021-10-16 10:12 UTC, fabpot commented
Thank you @W0rma.

2021-10-16 10:12 UTC, merged