[VarDumper] Fix error with uninitialized XMLReader
symfony/symfony pull request #43413
Opened 2021-10-12 15:34 UTC by villfa

| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #42581
| License       | MIT
| Doc PR        | n/a

When XMLReader is not initialized,  getParserProperty() throws an error (or emits a warning, depending on the PHP version).
Now the error is caught and the properties are set to false.

2021-10-13 14:44 UTC, villfa commented
Hi @fabpot,
The error from *fabbot.io* is a false positive, so I'm wondering if the code of this bot is open in order to fix it.
Or maybe it relies on open tools?

2021-10-13 14:56 UTC, derrabus requested changes

2021-10-13 14:56 UTC, derrabus commented on src/Symfony/Component/VarDumper/Caster/XmlReaderCaster.php
> +use Error;
CS: We don't import classes from the global scope.

2021-10-13 14:56 UTC, derrabus commented on src/Symfony/Component/VarDumper/Caster/XmlReaderCaster.php
> +        } catch (Error $e) {
```suggestion
        } catch (\ValueError $e) {
```

2021-10-13 14:58 UTC, derrabus commented
Thank you for your PR, @villfa. The open source tool that fabbot relies on is PHP CS Fixer. Since the failure is a false positive as you already discovered, you can simply ignore it. 🙂

2021-10-13 18:43 UTC, villfa commented on src/Symfony/Component/VarDumper/Caster/XmlReaderCaster.php
> +        } catch (Error $e) {
I've used `Error` instead of `ValueError` on purpose because of this fix in PHP: https://github.com/php/php-src/commit/53f89219abdea49099805562d5020d4e21785d55

2021-10-13 18:46 UTC, villfa commented on src/Symfony/Component/VarDumper/Caster/XmlReaderCaster.php
> +use Error;
It's fixed.

2021-10-13 19:39 UTC, derrabus commented on src/Symfony/Component/VarDumper/Caster/XmlReaderCaster.php
> +        } catch (Error $e) {
That makes total sense. I can confirm that an `Error` is triggered on the latest PHP snapshot.

That makes me wonder: Is there a better way to detect an uninitialized `XMLReader` than to catch a generic `Error`?

2021-10-13 19:54 UTC, villfa commented on src/Symfony/Component/VarDumper/Caster/XmlReaderCaster.php
> +        } catch (Error $e) {
I've double-checked the XMLReader [documentation](https://www.php.net/manual/en/class.xmlreader.php) and [source code](https://github.com/php/php-src/blob/master/ext/xmlreader/php_xmlreader.c), and I couldn't find another way to check if an instance is not yet initialized :(

2021-10-13 20:00 UTC, derrabus approved these changes

2021-10-14 05:59 UTC, fabpot approved these changes

2021-10-14 06:00 UTC, fabpot commented
Thank you @villfa.

2021-10-14 06:00 UTC, merged