[Security] translations for Tagalog (tl)
symfony/symfony pull request #43470
Opened 2021-10-13 14:37 UTC by shreyadenny

| Q             | A
| ------------- | ---
| Branch?       | 4.4 
| Bug fix?      | no
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #42473 
| License       | MIT

Added translations for Tagalog(tl)

2021-10-13 16:56 UTC, fabpot commented
Thank you for working on this. I can see that you've improved the current translations, but can you also add the missing ones?

2021-10-14 04:23 UTC, shreyadenny commented
> Thank you for working on this. I can see that you've improved the current translations, but can you also add the missing ones?

Hey @fabpot

I have added all translations after comparing with <a href="https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Security/Core/Resources/translations/security.en.xlf">this</a>

Could you tell me which are the missing translations that you are referring to?

2021-10-14 05:42 UTC, fabpot commented
There is another file here: https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Validator/Resources/translations/validators.en.xlf

2021-10-14 06:30 UTC, shreyadenny commented
> There is another file here: https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Validator/Resources/translations/validators.en.xlf

Sure thanks. I'm on it.

2021-10-14 08:53 UTC, shreyadenny commented
@fabpot I've added the missing translations. Please check and suggest changes if needed.

2021-10-15 08:42 UTC, fabpot commented
Thank you for the work, but I think there was a misunderstanding. There are 2 different files for each language. Here, you've mixed up the 2 files into 1.

2021-10-15 09:31 UTC, shreyadenny commented
Sorry I may have made a mistake. I still don't unserstand this clearly.. which are the two files you're referring to?

2021-10-15 14:53 UTC, shreyadenny commented
I have made some corrections. Hopes it's okay now. @fabpot

2021-10-16 10:16 UTC, fabpot requested changes

2021-10-16 10:16 UTC, fabpot commented on src/Symfony/Component/Security/Core/Resources/translations/security.tl.xlf
> +                    </body>
Can you revert this change?

2021-10-16 10:16 UTC, fabpot commented on src/Symfony/Component/Validator/Resources/translations/validators.th.xlf
> +
Can you revert this change?

2021-10-16 11:58 UTC, shreyadenny commented
@fabpot Yes I've don the changes

2021-10-18 07:23 UTC, closed without merging