[Validator] Add missing validator polish translation
symfony/symfony pull request #43488
Opened 2021-10-14 00:08 UTC by chikaldirick

| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #43449
| License       | MIT
| Doc PR        | N/A

2021-10-14 06:50 UTC, hywak requested changes

2021-10-14 06:50 UTC, hywak commented on src/Symfony/Component/Validator/Resources/translations/validators.pl.xlf
> +                <target>Ta wartość nie jest prawidłową CSS kolor.</target>
This translation isn't grammatically correct. It should be something like: `Ta wartość nie jest prawidłowym/poprawnym kolorem CSS`

2021-10-14 09:05 UTC, IonBazan requested changes

2021-10-14 09:05 UTC, IonBazan commented on src/Symfony/Component/Validator/Resources/translations/validators.pl.xlf
> +                <target>Ta wartość nie jest prawidłową CSS kolor.</target>
```suggestion
                <target>Ta wartość nie jest prawidłowym kolorem CSS.</target>
```

@hywak Let's stick to "prawidłowym" as it's used in other messages too.

EDIT: Not sure how this initial message was translated but Google Translate does pretty good job:
![image](https://user-images.githubusercontent.com/1985514/137286700-6110fd20-a6b6-4240-8061-a3d04ee6333e.png)

2021-10-14 09:44 UTC, hywak commented on src/Symfony/Component/Validator/Resources/translations/validators.pl.xlf
> +                <target>Ta wartość nie jest prawidłową CSS kolor.</target>
No idea either 🤷🏼  `prawidłowym` sounds good. Thank you.

2021-10-14 09:56 UTC, chikaldirick commented on src/Symfony/Component/Validator/Resources/translations/validators.pl.xlf
> +                <target>Ta wartość nie jest prawidłową CSS kolor.</target>
Thanks for the suggestion, updated message according to it!

2021-10-15 08:48 UTC, fabpot commented
Thank you @chikaldirick.

2021-10-15 08:48 UTC, merged