[Validator] Deprecated email validation mode `loose`
symfony/symfony pull request #43505
Opened 2021-10-14 12:06 UTC by ThomasLandauer

| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | yes
| Tickets       | Fix #41855
| License       | MIT
| Doc PR        | TODO

Closes https://github.com/symfony/symfony/issues/41855

Don't know what else needs to be done... ;-)

2021-10-14 18:35 UTC, ro0NL commented on src/Symfony/Component/Validator/Constraints/EmailValidator.php
> +            trigger_deprecation('symfony/validator', '5.4', 'The email validation mode "loose" is deprecated; in Symfony 6.0 the default mode will be "html5".');
this will trigger by default, not sure it's ideal.

instead what about compile-time deprecations, eg. here:

https://github.com/symfony/symfony/blob/21cc2b6bde3e0883543dad753360833730e2a0bf/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php#L894

and here:

https://github.com/symfony/symfony/blob/0c73136f6239879b42636e7fdc049902c61f654a/src/Symfony/Component/Validator/Constraints/Email.php#L62-L65

2021-10-15 19:31 UTC, ThomasLandauer commented on src/Symfony/Component/Validator/Constraints/EmailValidator.php
> +            trigger_deprecation('symfony/validator', '5.4', 'The email validation mode "loose" is deprecated; in Symfony 6.0 the default mode will be "html5".');
Sorry, don't know what you mean :-( If I'm completely on the wrong track, please close it - I'm doing this for the first time...

2021-10-27 13:49 UTC, nicolas-grekas reviewed
a similar notice is needed in `validate()`, isn't it?

2021-10-27 13:49 UTC, nicolas-grekas commented on src/Symfony/Component/Validator/Constraints/EmailValidator.php
> +            trigger_deprecation('symfony/validator', '5.4', 'The email validation mode "loose" is deprecated; in Symfony 6.0 the default mode will be "html5".');
deprecating by default is fine, and that's the only way to tell ppl they should opt-in for html5|strict in v6

2021-10-27 13:49 UTC, nicolas-grekas commented on src/Symfony/Component/Validator/Constraints/Email.php
> +    /** @deprecated since Symfony 5.4; will be removed in Symfony 6.0; use email validation mode "html" instead */
in order to ease the transition, I would keep the const on v6 and make "loose" behave like "html5"
we could deprecate it in v6.1

2021-10-27 13:49 UTC, nicolas-grekas commented on UPGRADE-6.0.md
> +  * Removed email validation mode `loose`; default is now `html5`.
please also update the changelog of the component and the upgrade file for 5.4

2021-10-27 13:51 UTC, nicolas-grekas commented on UPGRADE-6.0.md
> +  * Removed email validation mode `loose`; default is now `html5`.
please remove the final dot also

2021-10-27 15:42 UTC, ThomasLandauer commented on src/Symfony/Component/Validator/Constraints/Email.php
> +    /** @deprecated since Symfony 5.4; will be removed in Symfony 6.0; use email validation mode "html" instead */
> make "loose" behave like "html5"

Regarding DX, I'd rather like to see an exception that informs me that something has changed, rather than get some change "under the hood".

2021-10-27 15:47 UTC, stof requested changes

2021-10-27 15:47 UTC, stof commented on src/Symfony/Component/Validator/Constraints/Email.php
>      public const VALIDATION_MODE_LOOSE = 'loose';
To actually be deprecated, the constraint should also trigger a deprecation when you instantiate it with a config putting it in loose mode. It should not be deprecated only for the _default_ mode

2021-10-27 15:47 UTC, ThomasLandauer commented
Should I commit the actual removal of "loose" to the 6.0 branch already, or when is the "usual" time to do this?

2021-10-27 15:53 UTC, ThomasLandauer commented on src/Symfony/Component/Validator/Constraints/EmailValidator.php
> +            trigger_deprecation('symfony/validator', '5.4', 'The email validation mode "loose" is deprecated; in Symfony 6.0 the default mode will be "html5".');
OK, so I'm doing nothing!?

2021-10-27 15:56 UTC, ThomasLandauer commented on src/Symfony/Component/Validator/Constraints/Email.php
> +    /** @deprecated since Symfony 5.4; will be removed in Symfony 6.0; use email validation mode "html" instead */
> a similar notice is needed in `validate()`, isn't it?

OK, I added it there too, please take a look.

2021-10-27 15:58 UTC, ThomasLandauer commented on src/Symfony/Component/Validator/Constraints/Email.php
>      public const VALIDATION_MODE_LOOSE = 'loose';
Yeah sure, but I thought this line would take care of this!?:
https://github.com/symfony/symfony/blob/67a2150c11f02b2d974cb48ca04577c218063cdf/src/Symfony/Component/Validator/Constraints/EmailValidator.php#L43

2021-10-27 16:00 UTC, nicolas-grekas commented on src/Symfony/Component/Validator/CHANGELOG.md
> + * Deprecated email validation mode `loose`; will be removed in Symfony 6 in favor of `html5` (= new default)
` * Deprecate email validation mode `loose`, use `html5` instead`

2021-10-27 16:00 UTC, nicolas-grekas commented on src/Symfony/Component/Validator/Constraints/EmailValidator.php
> +        if ($defaultMode === Email::VALIDATION_MODE_LOOSE) {
please swap operands (yoda rulez)

2021-10-27 16:00 UTC, nicolas-grekas commented on src/Symfony/Component/Validator/Constraints/EmailValidator.php
> +            trigger_deprecation('symfony/validator', '5.4', 'The email validation mode `loose` is deprecated since Symfony 5.4, and will be removed in Symfony 6.0 in favor of `html5` (= new default)'
`The "loose" email validation mode is deprecated, use "html5" instead.`

2021-10-27 16:00 UTC, nicolas-grekas commented on src/Symfony/Component/Validator/Constraints/EmailValidator.php
> +            trigger_deprecation('symfony/validator', '5.4', 'The email validation mode "loose" is deprecated; in Symfony 6.0 the default mode will be "html5".');
`The "loose" email validation mode is deprecated, use "html5" instead.`

2021-10-27 16:06 UTC, ThomasLandauer commented on src/Symfony/Component/Validator/Constraints/EmailValidator.php
> +        if ($defaultMode === Email::VALIDATION_MODE_LOOSE) {
Yeah, right you are :-)

2021-10-27 16:10 UTC, stof commented on src/Symfony/Component/Validator/Constraints/Email.php
>      public const VALIDATION_MODE_LOOSE = 'loose';
this line is only about the *default* mode of the validator, not about the mode configured in the constraint (which wins over the default mode)

2021-10-27 16:10 UTC, nicolas-grekas approved these changes
> the constraint should also trigger a deprecation when you instantiate it with a config putting it in loose mode

Not sure this is required to me. Not doing that would prevent triggering two very similar deprecations instead, thus reducing confusion.

2021-10-27 16:12 UTC, stof requested changes

2021-10-27 16:12 UTC, stof commented on src/Symfony/Component/Validator/Constraints/EmailValidator.php
> +        if (Email::VALIDATION_MODE_LOOSE === $constraint->mode) {
should be done before the null check, to avoid re-triggering a deprecation for each constraint using `null` as mode if the default mode is not updated (as those constraint won't have to be changed once you change the configured default mode).

2021-10-27 16:24 UTC, ThomasLandauer commented on src/Symfony/Component/Validator/Constraints/Email.php
>      public const VALIDATION_MODE_LOOSE = 'loose';
But isn't the actual mode being passed to `__construct()`? I thought `$defaultMode` was just a somewhat misleading name for the argument...

2021-10-27 16:31 UTC, stof commented on src/Symfony/Component/Validator/Constraints/Email.php
>      public const VALIDATION_MODE_LOOSE = 'loose';
`$defaultMode` is in the constructor of the validator, not of the constraint. It is the mode used by default when the constraint does not configure its mode (see the `null === $constraint->mode` check in the validator)

2021-10-27 16:33 UTC, stof commented
The tests covering the loose mode must be tagged as `@group legacy` (and probably also assert that they expect the deprecation). Otherwise, the deprecations in them are forbidden (which is why the CI is red right now)

2021-10-27 16:41 UTC, ThomasLandauer commented on src/Symfony/Component/Validator/Constraints/Email.php
>      public const VALIDATION_MODE_LOOSE = 'loose';
OK, but isn't the line we just moved upwards doing what you're asking for?:
https://github.com/symfony/symfony/blob/fd6741c4288f0d29a782030c3baa2959a65dfbdc/src/Symfony/Component/Validator/Constraints/EmailValidator.php#L76

Or do you suggest a similar check here?:
https://github.com/symfony/symfony/blob/fd6741c4288f0d29a782030c3baa2959a65dfbdc/src/Symfony/Component/Validator/Constraints/Email.php#L71

... but wouldn't this then raise *two* deprecation warnings, as @nicolas-grekas said below?

Sorry guys, I'm a little confused... ;-)

2021-10-27 18:29 UTC, ThomasLandauer commented
I'm stuck with the tests - they're failing with and without `$this->expectDeprecation();` - please help!

2021-10-28 11:43 UTC, xabbuh commented
There seem to be a lot tests where this constraint is used. They all need to be updated to use the `html5` mode instead of the default one I guess.

2021-10-28 12:19 UTC, ThomasLandauer commented
When switching the tests to `html5`, they're failing because of the sample addresses they're testing ;-) So what's the plan? "Upgrade" those tests now? Then there wouldn't be any tests for `loose` in 5.4 anymore...

2021-10-28 12:25 UTC, stof commented
Well, it is still expected to have some legacy tests for the loose mode.

The issue is probably that most tests are instantiating the EmailValidator with a loose default mode, even when they test other modes. That's what needs to be fixed. Tests that are not covering the loose mode must instantiate the validator with `html5` as default mode.

2021-10-28 15:16 UTC, ThomasLandauer commented
> The issue is probably that most tests are instantiating the EmailValidator with a loose default mode, even when they test other modes.

I'm not sure that this is the main problem...

This is the result I got *originally*:

> OK, but incomplete, skipped, or risky tests!
Tests: 4088, Assertions: 6372, Skipped: 289.
Remaining self deprecation notices (98)
  98x: Since symfony/validator 5.4: The "loose" email validation mode is deprecated, use "html5" instead
    94x in EmailValidatorTest::setUp from Symfony\Component\Validator\Tests\Constraints
    1x in ValidationTest::testCreateCallableValid from Symfony\Component\Validator\Tests
    1x in ValidationTest::testCreateCallableInvalid from Symfony\Component\Validator\Tests
    1x in ValidationTest::testCreateIsValidCallableValid from Symfony\Component\Validator\Tests
    1x in ValidationTest::testCreateIsValidCallableInvalid from Symfony\Component\Validator\Tests
Legacy deprecation notices (6)
Error: KO src/Symfony/Component/Validator

So from what you said above ("and probably also assert that they expect the deprecation") I figured I had to add `$this->expectDeprecation();`. But the result is:

> There was 1 failure:
> 1) Symfony\Component\Validator\Tests\Constraints\EmailValidatorTest::testModeLoose
> Failed asserting that exception of type "PHPUnit\Framework\Error\Deprecated" is thrown.

So am I right that (at least as a first step) those 98 "self deprecation notices" need to get fixed? But how?

2021-10-28 15:17 UTC, xabbuh commented
> So am I right that (at least as a first step) those 98 "self deprecation notices" need to get fixed? But how?

You need to update these tests to use the `html5` mode instead of the implicit `loose` default mode.

2021-10-28 15:18 UTC, stof commented
> So from what you said above ("and probably also assert that they expect the deprecation") I figured I had to add `$this->expectDeprecation();`. But the result is:
> 
> > There was 1 failure:
> > 
> > 1. Symfony\Component\Validator\Tests\Constraints\EmailValidatorTest::testModeLoose
> >    Failed asserting that exception of type "PHPUnit\Framework\Error\Deprecated" is thrown.
> 
> So am I right that (at least as a first step) those 98 "self deprecation notices" need to get fixed? But how?

you need to use the `ExpectDeprecationTrait` from the PHPUnit bridge, not the API defined in PHPUnit 8+ (which does not work for our silenced deprecations)

2021-10-28 20:06 UTC, ThomasLandauer commented
At least I managed to get rid of the 4 coming from `ValidationTest.php`. But I'm stuck with the 94 from `EmailValidatorTest.php` :-(

> 94x in EmailValidatorTest::setUp from Symfony\Component\Validator\Tests\Constraints

Don't even know what `setUp` refers to - there is no such method in that file.

2021-10-28 20:44 UTC, xabbuh commented on src/Symfony/Component/Validator/Tests/Constraints/EmailValidatorTest.php
>          return new EmailValidator(Email::VALIDATION_MODE_LOOSE);
The `createValidator()` method is called in `setUp()` in the base `ConstraintValidatorTestCase` class. That call will lead to the deprecation being triggered here.

2021-10-28 20:45 UTC, xabbuh commented on src/Symfony/Component/Validator/Tests/Constraints/EmailValidatorTest.php
> +     * @group legacy
`testNullIsValid()` should not trigger a deprecation

2021-10-28 20:45 UTC, xabbuh commented on src/Symfony/Component/Validator/Tests/ValidationTest.php
> +     * @group legacy
all the tests in this class should not depend on deprecated features

2021-10-28 21:12 UTC, ThomasLandauer commented on src/Symfony/Component/Validator/Tests/ValidationTest.php
> +     * @group legacy
OK, so that's what you meant above at https://github.com/symfony/symfony/pull/43505#issuecomment-953765526 ? I should instantiate them with "html5", like so?:
https://github.com/symfony/symfony/blob/a44a14c7e581139df04ad652eadf9346c733a75c/src/Symfony/Component/Validator/Tests/ValidationTest.php#L32
=> becomes this:
```php
$validator = Validation::createCallable(new Email(Email::VALIDATION_MODE_HTML5));
```

Just asking, cause if I change it this way, they won't be testing anymore which mode is the default.

2021-10-28 21:19 UTC, xabbuh commented on src/Symfony/Component/Validator/Tests/ValidationTest.php
> +     * @group legacy
Well, as these tests are not about testing the `Email` constraint that's not an issue.

2021-10-28 21:21 UTC, ThomasLandauer commented on src/Symfony/Component/Validator/Tests/Constraints/EmailValidatorTest.php
>          return new EmailValidator(Email::VALIDATION_MODE_LOOSE);
So I need to add `@group legacy` and `$this->expectDeprecation` at [ConstraintValidatorTestCase::setUp](https://github.com/ThomasLandauer/symfony/blob/patch-2/src/Symfony/Component/Validator/Test/ConstraintValidatorTestCase.php#L65)?

Cause I'm sure I already tried it here at `EmailValidatorTest::createValidator()` and it didn't work...

2021-10-28 21:38 UTC, xabbuh commented on src/Symfony/Component/Validator/Tests/Constraints/EmailValidatorTest.php
>          return new EmailValidator(Email::VALIDATION_MODE_LOOSE);
No, you need to update this method to not pass `loose` but `html5` as the mode instead. The legacy `loose` mode needs to be tested explicitly in legacy test methods instead.

2021-10-28 22:50 UTC, ThomasLandauer commented
The purpose of [EmailValidatorTest::testValidNormalizedEmails()](https://github.com/ThomasLandauer/symfony/blob/patch-2/src/Symfony/Component/Validator/Tests/Constraints/EmailValidatorTest.php#L95) seems to be to test the normalizer. So should I just delete all "html5-failing" email addresses from the data provider?

2021-10-28 23:02 UTC, ThomasLandauer commented on src/Symfony/Component/Validator/Tests/Constraints/EmailValidatorTest.php
>          return new EmailValidator(Email::VALIDATION_MODE_LOOSE);
I think since we changed this, the deprecation warning is gone:
```
1) Symfony\Component\Validator\Tests\Constraints\EmailValidatorTest::testValidEmailsLoose with data set #0 ('fabien@symfony.com')
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
 @expectedDeprecation:
-%A  Since symfony/validator 5.4: The "loose" email validation mode is deprecated, use "html5" instead
+
```
So do I need to `trigger_deprecation()` in `createValidator()` too? But wouldn't this result in what @nicolas-grekas said he doesn't want? https://github.com/symfony/symfony/pull/43505#pullrequestreview-790866569

> Not sure this is required to me. Not doing that would prevent triggering two very similar deprecations instead, thus reducing confusion.

2022-07-23 13:11 UTC, fabpot commented
Closing as it has been finished in #46518

2022-07-23 13:11 UTC, closed without merging