fix: Improve FR validators translation
symfony/symfony pull request #43564
Opened 2021-10-18 13:53 UTC by NathanDid

| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| License       | MIT

Improve fr form validators.

2021-10-18 13:54 UTC, stof approved these changes

2021-10-18 15:50 UTC, chalasr approved these changes

2021-10-18 16:02 UTC, fabpot approved these changes

2021-10-18 16:03 UTC, fabpot requested changes

2021-10-18 16:03 UTC, fabpot commented on src/Symfony/Component/Form/Resources/translations/validators.fr.xlf
> +                <target>Ce formulaire ne doit pas contenir de champ supplémentaire.</target>
```suggestion
                <target>Ce formulaire ne doit pas contenir de champs supplémentaires.</target>
```

2021-10-19 08:13 UTC, fabpot approved these changes

2021-10-19 08:14 UTC, fabpot commented
Thank you @NathanDid.

2021-10-19 08:14 UTC, merged