[Validator] Add CidrValidator to allow validation of CIDR notations
symfony/symfony pull request #43593
Opened 2021-10-19 15:28 UTC by popsorin

| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no 
| Tickets       | Fix #36526
| License       | MIT
| Doc PR        | https://github.com/symfony/symfony-docs/pull/15974

This PR will add a CIDR Constraint Validator that will check if a string is a valid CIDR notation.

2021-10-19 15:41 UTC, stof commented on src/Symfony/Component/Validator/Constraints/Cidr.php
> +        array $options = null,
@symfony/mergers For the new constraints, do we want to support that associative array of options or only the separate arguments ? Is this argument required by the XML and Yaml loaders ?
For the annotation reader, we can tell it to use the constructor arguments instead of an associative array by adding `@NamedArgumentConstructor` in the phpdoc alongside the `@Annotation` and `@Target`

2021-10-19 15:42 UTC, stof commented on src/Symfony/Component/Validator/Resources/translations/validators.ro.xlf
> +                <target>Această valoare nu este o culoare CSS validă.</target>
should not be in this PR, but in a separate PR (that will for sure be merged in the 5.4 release, while the current PR might not be accepted for 5.4 as we are reaching the feature freeze)

2021-10-19 15:42 UTC, CalinBolea commented on src/Symfony/Component/Validator/Resources/translations/validators.ro.xlf
>              </trans-unit>
editing this file causes the pipeline to break with common typos when in fact there is no typo (in romanian address is "adresă" and the recommandation is to change it into "addressă", which is incorrect.)

2021-10-19 15:50 UTC, stof commented on src/Symfony/Component/Validator/Resources/translations/validators.ro.xlf
>              </trans-unit>
yeas, that's a known issue of fabbot. It does not properly ignore translation files when checking for common English typos.

2021-10-19 15:51 UTC, stof commented on src/Symfony/Component/Validator/Resources/translations/validators.en.xlf
> +                <target>This value is not a valid CIDR notation.</target>
We probably need different messages when the value is a valid CIDR range, but `netmaskMin` and/or `netmaskMax` are adding additional restrictions about the accepted values.

2021-10-19 20:53 UTC, derrabus commented on src/Symfony/Component/Validator/Constraints/Cidr.php
> +        array $options = null,
So far, all constraints can still be instantiated with an array of options because annotations/attributes are not the only way to create a constraint. For instance, when you attach a constraint to a form field, you directly call the constructor. Without the ability to use a options array here, you'd have a hard time crafting a constructor call on PHP 7.

2021-10-19 21:03 UTC, derrabus requested changes

2021-10-19 21:03 UTC, derrabus commented on src/Symfony/Component/Validator/Constraints/Cidr.php
> +    protected static $netmaskMaxes = [
Should be a `private const` instead.

2021-10-19 21:03 UTC, derrabus commented on src/Symfony/Component/Validator/CHANGELOG.md
> + * Add a `Cidr` constraint to validate Cidr notations
```suggestion
 * Add a `Cidr` constraint to validate CIDR notations
```

2021-10-20 09:32 UTC, stof commented on src/Symfony/Component/Validator/Constraints/Cidr.php
> +        array $options = null,
indeed. Reconsidering the `$options` argument for new constraint is something we might defer until we drop support for PHP 7 (i.e. once we start adding new constraints in Symfony 6.x)

2021-10-21 10:26 UTC, derrabus approved these changes

2021-10-22 11:48 UTC, popsorin commented
Hey, @stof could you please take a look at the changes requested by your code review ? Thanks!

2021-10-22 19:23 UTC, stof approved these changes

2021-10-25 10:51 UTC, derrabus commented
Thank you @popsorin.

2021-10-25 10:52 UTC, merged

2021-10-25 10:55 UTC, Adambean commented
Thank you @popsorin, looking forward to trying this out later. :)