[Console] add suggestions for debug commands: firewall, form, messenger, router
symfony/symfony pull request #43598
Opened 2021-10-20 03:52 UTC by IonBazan

| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | #43594
| License       | MIT
| Doc PR        | -

Adding Bash completion for following commands:

- `debug:firewall`
- `debug:form`
- `debug:messenger`
- `debug:router`

~Waiting for #43596 to be merged first as it adds testing utilities and `DescriptorHelper::getFormats()`.~

2021-10-21 11:01 UTC, TimoBakx commented
The `DebugFirewallCommand` part looks good. 👍

2021-10-22 11:41 UTC, GromNaN requested changes
Very nice, especially on `debug:form`.

Namespace backslash are missing from completion. 

```console
$ bin/console debug:form 
AppFormCommentType                                     SymfonyComponentFormExtensionCoreTypeCheckboxType      SymfonyComponentFormExtensionCoreTypeEmailType         SymfonyComponentFormExtensionCoreTypePasswordType      SymfonyComponentFormExtensionCoreTypeTextType
AppFormPostType                                        SymfonyComponentFormExtensionCoreTypeChoiceType        SymfonyComponentFormExtensionCoreTypeFileType          SymfonyComponentFormExtensionCoreTypePercentType       SymfonyComponentFormExtensionCoreTypeTextareaType
AppFormTypeChangePasswordType                          SymfonyComponentFormExtensionCoreTypeCollectionType    SymfonyComponentFormExtensionCoreTypeFormType          SymfonyComponentFormExtensionCoreTypeRadioType         SymfonyComponentFormExtensionCoreTypeTimeType
AppFormTypeDateTimePickerType                          SymfonyComponentFormExtensionCoreTypeColorType         SymfonyComponentFormExtensionCoreTypeHiddenType        SymfonyComponentFormExtensionCoreTypeRangeType         SymfonyComponentFormExtensionCoreTypeTimezoneType
AppFormTypeTagsInputType                               SymfonyComponentFormExtensionCoreTypeCountryType       SymfonyComponentFormExtensionCoreTypeIntegerType       SymfonyComponentFormExtensionCoreTypeRepeatedType      SymfonyComponentFormExtensionCoreTypeUrlType
AppFormUserType                                        SymfonyComponentFormExtensionCoreTypeCurrencyType      SymfonyComponentFormExtensionCoreTypeLanguageType      SymfonyComponentFormExtensionCoreTypeResetType         SymfonyComponentFormExtensionCoreTypeWeekType
SymfonyBridgeDoctrineFormTypeEntityType                SymfonyComponentFormExtensionCoreTypeDateIntervalType  SymfonyComponentFormExtensionCoreTypeLocaleType        SymfonyComponentFormExtensionCoreTypeSearchType        
SymfonyComponentFormExtensionCoreTypeBirthdayType      SymfonyComponentFormExtensionCoreTypeDateTimeType      SymfonyComponentFormExtensionCoreTypeMoneyType         SymfonyComponentFormExtensionCoreTypeSubmitType        
SymfonyComponentFormExtensionCoreTypeButtonType        SymfonyComponentFormExtensionCoreTypeDateType          SymfonyComponentFormExtensionCoreTypeNumberType        SymfonyComponentFormExtensionCoreTypeTelType           
```

Option completion is very accurate with a class:
```console
$ bin/console debug:form App\Form\CommentType 
action                        block_name                    csrf_message                  disabled                      getter                        invalid_message               label_html                    priority                      trim                          
allow_extra_fields            block_prefix                  csrf_protection               empty_data                    help                          invalid_message_parameters    label_translation_parameters  property_path                 upload_max_size_message       
allow_file_upload             by_reference                  csrf_token_id                 error_bubbling                help_attr                     is_empty_callback             legacy_error_messages         required                      validation_groups             
attr                          compound                      csrf_token_manager            error_mapping                 help_html                     label                         mapped                        row_attr                      
attr_translation_parameters   constraints                   data                          extra_fields_message          help_translation_parameters   label_attr                    method                        setter                        
auto_initialize               csrf_field_name               data_class                    form_attr                     inherit_data                  label_format                  post_max_size_message         translation_domain            
```

But fails if backslashes are escaped. I don't know if that should be supported:
```console
$ bin/console debug:form App\\Form\\CommentType 


```
```
RuntimeException: The autoloader expected class "App\\Form\\CommentType" to be defined in file "src//Form//CommentType.php". The file was found but the class was not in it, the class name or namespace probably has a typo.
```

2021-10-22 11:41 UTC, GromNaN commented on src/Symfony/Component/Form/Tests/Command/DebugCommandTest.php
> +        yield 'option for short name' => [
You inverted descriptions "short name" vs "FQCN".

2021-10-22 11:41 UTC, GromNaN commented on src/Symfony/Component/Form/Tests/Command/DebugCommandTest.php
> +            ['Symfony\\Component\\Form\\Extension\\Core\Type\\ButtonType', ''],
Is this double backslash missing?
```suggestion
            ['Symfony\\Component\\Form\\Extension\\Core\\Type\\ButtonType', ''],
```

2021-10-22 11:58 UTC, IonBazan commented on src/Symfony/Component/Form/Tests/Command/DebugCommandTest.php
> +            ['Symfony\\Component\\Form\\Extension\\Core\Type\\ButtonType', ''],
Good catch, thanks!

2021-10-22 12:03 UTC, IonBazan commented
@GromNaN these missing backslashes seem like an issue with the completion command escaping itself and input escaping. The suggestions provided by the `debug:form` do contain the backslashes so it must be something wrong with the terminal or the completion engine. Are there any similar issues in other commands too?

2021-10-22 12:10 UTC, GromNaN commented
Same issue with backslashes in #43653.

2021-10-22 19:24 UTC, wouterj commented
I've proposed a (quite ugly) fix for the backslashes: https://github.com/symfony/symfony/pull/43664 I welcome more testers of this script, as I'm not sure how well this actually works (it works on my machine™)

2021-10-25 01:34 UTC, IonBazan commented on src/Symfony/Component/Form/Tests/Command/DebugCommandTest.php
> +        yield 'option for short name' => [
Fixed 👍🏻

2021-10-27 03:19 UTC, IonBazan commented
@GromNaN please review again

2021-10-27 06:16 UTC, GromNaN commented
LGTM. I used this PR to test https://github.com/symfony/symfony/pull/43665 and it worked very well.

Regarding class types, the short names could have been completed in case someone type "ButtonType" for example. But name conflicts can appear and the completion made the FQCN  lot easier to type.

2021-10-29 13:28 UTC, wouterj approved these changes

2021-10-29 15:00 UTC, fabpot requested changes

2021-10-29 15:00 UTC, fabpot commented on src/Symfony/Component/Messenger/Tests/Command/DebugCommandTest.php
> +    {
if (!class_exists(CommandCompletionTester::class)) {
            $this->markTestSkipped('Test command completion requires symfony/console 5.4+.');
        }

2021-10-30 02:53 UTC, IonBazan commented on src/Symfony/Component/Messenger/Tests/Command/DebugCommandTest.php
> +    {
Resolved and squashed the commits.

2021-10-30 08:21 UTC, fabpot approved these changes

2021-10-30 08:23 UTC, fabpot commented
Thank you @IonBazan.

2021-10-30 08:23 UTC, merged