uzb translation
symfony/symfony pull request #43633
Opened 2021-10-21 10:01 UTC by shokhaa

| Q             | A
| ------------- | ---
| Branch?       | 5.4 for features / 4.4 or 5.3 for bug fixes 
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #... 
| License       | MIT
| Doc PR        | symfony/symfony-docs#...

2021-10-21 11:33 UTC, IonBazan requested changes

2021-10-21 11:33 UTC, IonBazan commented on src/Symfony/Component/Security/Core/Resources/translations/security.uz.xlf
> +                <target>Kirish uchun muvaffaqiyatsiz urinishlar, %minutes% daqiqadan so`ng qayta urinib ko`ring.</target>
```suggestion
                <target>Kirish uchun muvaffaqiyatsiz urinishlar, %minutes% daqiqadan so'ng qayta urinib ko'ring.</target>
```

`'` should be used instead of `

2021-10-21 11:33 UTC, IonBazan commented on src/Symfony/Component/Security/Core/Resources/translations/security.uz.xlf
> +                <target>Kirish uchun muvaffaqiyatsiz urinishlar, %minutes% daqiqadan so`ng qayta urinib ko`ring.</target>
```suggestion
                <target>Kirish uchun muvaffaqiyatsiz urinishlar, %minutes% daqiqadan so'ng qayta urinib ko'ring.</target>
```

2021-10-22 13:46 UTC, shokhaa commented on src/Symfony/Component/Security/Core/Resources/translations/security.uz.xlf
> +                <target>Kirish uchun muvaffaqiyatsiz urinishlar, %minutes% daqiqadan so`ng qayta urinib ko`ring.</target>
@IonBazan done

2021-10-23 07:04 UTC, fabpot commented
@shokhaa Can you add translations for id 100 and 101 in src/Symfony/Component/Validator/Resources/translations/validators.uz.xlf as well?

2021-10-23 07:39 UTC, shokhaa commented
@fabpot done

2021-10-23 07:49 UTC, fabpot commented
Thank you @shokhaa.

2021-10-23 07:49 UTC, merged