[PasswordHasher] Add autocompletion for security commands
symfony/symfony pull request #43653
Opened 2021-10-22 11:52 UTC by 94noni

| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Ref https://github.com/symfony/symfony/issues/43594
| License       | MIT
| Doc PR        | 

Related to https://github.com/symfony/symfony/issues/43594#issuecomment-949503331
I have a question regarding @wouterj 's comment on the issue
Also, the `password` is the first argument right now, should we swap it to be after `user-class`?

Still WIP, I am using `fish` and want to test as well https://github.com/symfony/symfony/pull/43641

2021-10-22 12:42 UTC, wouterj requested changes
That was quick, thanks!

> I have a question regarding @wouterj 's comment on the issue

Ignore my comment, I didn't know about this `$userClasses` property.

> Also, the password is the first argument right now, should we swap it to be after user-class?

No, it's fine like this (autocompletion should support it this way).

---

Can you please also add tests? (see the other completion PRs for examples)

2021-10-22 12:42 UTC, wouterj commented on src/Symfony/Bundle/SecurityBundle/Command/UserPasswordEncoderCommand.php
> +        $suggestions->suggestValues($this->userClasses);
```suggestion
        if (!$input->mustSuggestArgumentValuesFor('user-class')) {
            $suggestions->suggestValues($this->userClasses);

            return;
        }
```

While we usually favor early return in Symfony, let's not do that here (to reduce the diff and thus merge conflicts when adding new completion suggestions in the future).

2021-10-22 12:42 UTC, wouterj commented on src/Symfony/Component/PasswordHasher/Command/UserPasswordHashCommand.php
> +        $suggestions->suggestValues($this->userClasses);
```suggestion
        if (!$input->mustSuggestArgumentValuesFor('user-class')) {
            $suggestions->suggestValues($this->userClasses);

            return;
        }
```

2021-10-22 14:42 UTC, chalasr commented on src/Symfony/Bundle/SecurityBundle/Command/UserPasswordEncoderCommand.php
> +    public function complete(CompletionInput $input, CompletionSuggestions $suggestions): void
A deprecated class should not receive enhancements (one more reason to switch to the new one)

2021-10-22 14:46 UTC, 94noni commented on src/Symfony/Bundle/SecurityBundle/Command/UserPasswordEncoderCommand.php
> +    public function complete(CompletionInput $input, CompletionSuggestions $suggestions): void
oki I'll revert changes related to `UserPasswordEncoderCommand*`

2021-10-22 14:47 UTC, 94noni commented on src/Symfony/Component/PasswordHasher/Command/UserPasswordHashCommand.php
> +            return;
seems weird to me but added according to your [original review](https://github.com/symfony/symfony/pull/43653#discussion_r734503950)

2021-10-22 15:43 UTC, wouterj approved these changes

2021-10-22 15:45 UTC, wouterj requested changes
Wait, let's block this for a bit as we first need to handle the backslashes properly in the completion feature: https://github.com/symfony/symfony/pull/43598

2021-10-29 12:32 UTC, chalasr approved these changes
Unlocked

2021-10-29 13:25 UTC, wouterj approved these changes

2021-10-29 14:52 UTC, fabpot approved these changes

2021-10-29 14:53 UTC, fabpot commented
Thank you @94noni.

2021-10-29 14:53 UTC, merged

2021-10-30 15:48 UTC, derrabus commented
Tests are failing on 5.4: https://github.com/symfony/symfony/runs/4055700364?check_suite_focus=true#step:8:2615

2021-10-30 15:57 UTC, derrabus commented
#43843