[Validator] Edit and add missing translations for Persian (fa)
symfony/symfony pull request #43666
Opened 2021-10-22 20:46 UTC by BahmanMehrdad

| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #43490
| License       | MIT

This PR is for edit and add missing translations for Persian (fa)

2021-10-23 18:02 UTC, ErfanBahramali commented
Converting half-space (semi-space) to space is wrong

2021-10-23 18:19 UTC, BahmanMehrdad commented
No half-space (semi-space) converted to space !!!!
Did you check the file changed?

2021-10-23 21:11 UTC, ErfanBahramali requested changes

2021-10-23 21:11 UTC, ErfanBahramali commented on src/Symfony/Component/Validator/Resources/translations/validators.fa.xlf
> +                <target>این یک پست الکترونیکی (ایمیل) معتبر نمی‌باشد.</target>
This is not wrong, but there is no reason for this change and I do not see the need to do so

2021-10-23 21:11 UTC, ErfanBahramali commented on src/Symfony/Component/Validator/Resources/translations/validators.fa.xlf
> +                <target>این مقدار با کاراکتر مورد انتظار {{ charset }} مطابقت ندارد.</target>
This is charset, not character

This is wrong

2021-10-23 21:11 UTC, ErfanBahramali commented on src/Symfony/Component/Validator/Resources/translations/validators.fa.xlf
> +                <target>این مجموعه باید فقط شامل عناصر منحصر به فرد باشد.</target>
This is not wrong, but there is no reason for this change and I do not see the need to do so

2021-10-23 21:11 UTC, ErfanBahramali commented on src/Symfony/Component/Validator/Resources/translations/validators.fa.xlf
> +                <target>این رمزعبور در یک رخنه‌ی اطلاعاتی نشت کرده اس، نباید از آن استفاده کرد. لطفا از یک رمزعبور دیگری استفاده کنید.</target>
This is wrong

2021-10-23 21:11 UTC, ErfanBahramali commented on src/Symfony/Component/Validator/Resources/translations/validators.fa.xlf
> +                <target>این مقدار یک نام میزبان (hostname) معتبر نیست.</target>
I don't think this translation is correct

2021-10-23 21:11 UTC, ErfanBahramali commented on src/Symfony/Component/Validator/Resources/translations/validators.fa.xlf
> +                <target>این مقدار یک شماره شناسایی معتبر اوراق بهادار بین المللی (ISIN) نیست.</target>
I don't agree with this change

2021-10-23 21:21 UTC, BahmanMehrdad commented on src/Symfony/Component/Validator/Resources/translations/validators.fa.xlf
> +                <target>این مقدار با کاراکتر مورد انتظار {{ charset }} مطابقت ندارد.</target>
Charset means character set. I add set to this translation

2021-10-23 22:00 UTC, ErfanBahramali commented on src/Symfony/Component/Validator/Resources/translations/validators.fa.xlf
> +                <target>این مقدار با کاراکتر مورد انتظار {{ charset }} مطابقت ندارد.</target>
it's wrong
You just changed it to finglish and did not translate

The previous translation is correct
No need to change

2021-10-23 22:04 UTC, ErfanBahramali commented on src/Symfony/Component/Validator/Resources/translations/validators.fa.xlf
> +                <target>این یک پست الکترونیکی (ایمیل) معتبر نمی‌باشد.</target>
The previous translation is correct
No need to change

2021-10-23 22:05 UTC, ErfanBahramali commented on src/Symfony/Component/Validator/Resources/translations/validators.fa.xlf
> +                <target>این مجموعه باید فقط شامل عناصر منحصر به فرد باشد.</target>
The previous translation is correct
No need to change

2021-10-23 22:05 UTC, ErfanBahramali commented on src/Symfony/Component/Validator/Resources/translations/validators.fa.xlf
> +                <target>این رمزعبور در یک رخنه‌ی اطلاعاتی نشت کرده اس، نباید از آن استفاده کرد. لطفا از یک رمزعبور دیگری استفاده کنید.</target>
The previous translation is correct
No need to change

2021-10-23 22:06 UTC, ErfanBahramali commented on src/Symfony/Component/Validator/Resources/translations/validators.fa.xlf
> +                <target>این مقدار یک شماره شناسایی معتبر اوراق بهادار بین المللی (ISIN) نیست.</target>
The previous translation is correct
No need to change

2021-10-23 22:07 UTC, ErfanBahramali commented on src/Symfony/Component/Validator/Resources/translations/validators.fa.xlf
> +                <target>این مقدار یک نام میزبان (hostname) معتبر نیست.</target>
The previous translation is correct
No need to change

2021-10-23 22:23 UTC, BahmanMehrdad commented on src/Symfony/Component/Validator/Resources/translations/validators.fa.xlf
> +                <target>این یک پست الکترونیکی (ایمیل) معتبر نمی‌باشد.</target>
"رایانامه" is not common in Persian

2021-10-23 22:26 UTC, BahmanMehrdad commented on src/Symfony/Component/Validator/Resources/translations/validators.fa.xlf
> +                <target>این مقدار با کاراکتر مورد انتظار {{ charset }} مطابقت ندارد.</target>
In Persian we say "کاراکترست". This translation is for Persian languages and Finglish does not make sense

2021-10-23 22:27 UTC, BahmanMehrdad commented on src/Symfony/Component/Validator/Resources/translations/validators.fa.xlf
> +                <target>این مجموعه باید فقط شامل عناصر منحصر به فرد باشد.</target>
"حاوی" is wrong and "شامل" is correct. And "منحصر به فرد" is better than "یکتا"

2021-10-23 22:29 UTC, BahmanMehrdad commented on src/Symfony/Component/Validator/Resources/translations/validators.fa.xlf
> +                <target>این رمزعبور در یک رخنه‌ی اطلاعاتی نشت کرده اس، نباید از آن استفاده کرد. لطفا از یک رمزعبور دیگری استفاده کنید.</target>
The previous translation is incorrect and does not match the English text

2021-10-23 22:31 UTC, BahmanMehrdad commented on src/Symfony/Component/Validator/Resources/translations/validators.fa.xlf
> +                <target>این مقدار یک نام میزبان (hostname) معتبر نیست.</target>
"hostname" in Persian means "نام میزبان" and must be translated, but it was not translated in the previous translation and its English word is inserted.

2021-10-23 22:32 UTC, BahmanMehrdad commented on src/Symfony/Component/Validator/Resources/translations/validators.fa.xlf
> +                <target>این مقدار یک شماره شناسایی معتبر اوراق بهادار بین المللی (ISIN) نیست.</target>
The previous translation was incomplete and did not convey the exact meaning

2021-10-23 22:36 UTC, BahmanMehrdad reviewed
Review

2021-10-23 22:37 UTC, ErfanBahramali commented on src/Symfony/Component/Validator/Resources/translations/validators.fa.xlf
> +                <target>این مقدار با کاراکتر مورد انتظار {{ charset }} مطابقت ندارد.</target>
This is wrong

2021-10-23 22:41 UTC, ErfanBahramali commented on src/Symfony/Component/Validator/Resources/translations/validators.fa.xlf
> +                <target>این مجموعه باید فقط شامل عناصر منحصر به فرد باشد.</target>
This is wrong

2021-10-23 22:44 UTC, BahmanMehrdad commented on src/Symfony/Component/Validator/Resources/translations/validators.fa.xlf
> +                <target>این مقدار با کاراکتر مورد انتظار {{ charset }} مطابقت ندارد.</target>
See this:
https://www.w3schools.com/html/html_charset.asp

2021-10-23 22:45 UTC, BahmanMehrdad commented on src/Symfony/Component/Validator/Resources/translations/validators.fa.xlf
> +                <target>این مجموعه باید فقط شامل عناصر منحصر به فرد باشد.</target>
Are you familiar with the principles and rules of Persian language?

2021-10-23 22:46 UTC, ErfanBahramali commented on src/Symfony/Component/Validator/Resources/translations/validators.fa.xlf
> +                <target>این رمزعبور در یک رخنه‌ی اطلاعاتی نشت کرده اس، نباید از آن استفاده کرد. لطفا از یک رمزعبور دیگری استفاده کنید.</target>
Your translation is not accurate
correct:

این رمزعبور در یک رخنه‌ی اطلاعاتی نشت کرده است، نباید از آن استفاده کرد. لطفاً از رمزعبور دیگری استفاده کنید.

2021-10-23 22:53 UTC, BahmanMehrdad commented on src/Symfony/Component/Validator/Resources/translations/validators.fa.xlf
> +                <target>این رمزعبور در یک رخنه‌ی اطلاعاتی نشت کرده اس، نباید از آن استفاده کرد. لطفا از یک رمزعبور دیگری استفاده کنید.</target>
"it must not be used" means "نباید از آن استفاده کرد", and this sentence did not exist in the previous translation

2021-10-23 22:54 UTC, ErfanBahramali commented
It is as if there is disagreement and there is a need to discuss these issues

@BahmanMD 
Contact me on Telegram or Discord
Or you can raise issues in the topic so that other friends can participate

2021-10-23 22:57 UTC, BahmanMehrdad commented
> It is as if there is disagreement and there is a need to discuss these issues
> 
> @BahmanMD Contact me on Telegram or Discord Or you can raise issues in the topic so that other friends can participate

Unfortunately, most of the objections to the translation indicate that you are not fluent in Persian, because the meanings of the words in Persian may be the same, but the time and place of their use are very important.

2021-10-23 23:01 UTC, ErfanBahramali commented on src/Symfony/Component/Validator/Resources/translations/validators.fa.xlf
> +                <target>این رمزعبور در یک رخنه‌ی اطلاعاتی نشت کرده اس، نباید از آن استفاده کرد. لطفا از یک رمزعبور دیگری استفاده کنید.</target>
Adding that section is correct, but the first and last item is incorrect
Means 'است' and 'دیگر'
The first case was corrected ( اس ) => ( است )
But the second 
' لطفاً از رمزعبور دیگری استفاده کنید' is correct

2021-10-23 23:07 UTC, BahmanMehrdad commented on src/Symfony/Component/Validator/Resources/translations/validators.fa.xlf
> +                <target>این رمزعبور در یک رخنه‌ی اطلاعاتی نشت کرده اس، نباید از آن استفاده کرد. لطفا از یک رمزعبور دیگری استفاده کنید.</target>
"This password has been leaked in a data breach" means "این  رمزعبور در یک رخنه‌ی اطلاعاتی نشت کرده است"
"it must not be used" means "نباید از آن استفاده کرد"
"Please use another password" means "لطفا از یک رمزعبور دیگری استفاده کنید"
Why is this translation wrong !!!!!?

2021-10-23 23:10 UTC, ErfanBahramali commented
> > It is as if there is disagreement and there is a need to discuss these issues
> > @BahmanMD Contact me on Telegram or Discord Or you can raise issues in the topic so that other friends can participate
> 
> Unfortunately, most of the objections to the translation indicate that you are not fluent in Persian, because the meanings of the words in Persian may be the same, but the time and place of their use are very important.

I just say my opinion
In this case, you can also get help from the previous translator ( Before me )

2021-10-23 23:13 UTC, ErfanBahramali commented on src/Symfony/Component/Validator/Resources/translations/validators.fa.xlf
> +                <target>این رمزعبور در یک رخنه‌ی اطلاعاتی نشت کرده اس، نباید از آن استفاده کرد. لطفا از یک رمزعبور دیگری استفاده کنید.</target>
'یک' is extra

"Please use another password" means "لطفا از رمزعبور دیگری استفاده کنید"

2021-10-23 23:14 UTC, ErfanBahramali commented on src/Symfony/Component/Validator/Resources/translations/validators.fa.xlf
> +                <target>این مقدار با کاراکتر مورد انتظار {{ charset }} مطابقت ندارد.</target>
'کاراکترست' is not a Persian word
You just converted it to Finglish

2021-10-23 23:17 UTC, ErfanBahramali commented on src/Symfony/Component/Validator/Resources/translations/validators.fa.xlf
> +                <target>این یک پست الکترونیکی (ایمیل) معتبر نمی‌باشد.</target>
Because 'پست الکترونیک' is English and 'رایانامه' is the official translation of 'email'

2021-10-23 23:17 UTC, BahmanMehrdad commented
> > > It is as if there is disagreement and there is a need to discuss these issues
> > > @BahmanMD Contact me on Telegram or Discord Or you can raise issues in the topic so that other friends can participate
> > 
> > 
> > Unfortunately, most of the objections to the translation indicate that you are not fluent in Persian, because the meanings of the words in Persian may be the same, but the time and place of their use are very important.
> 
> I just say my opinion In this case, you can also get help from the previous translator ( Before me )

Thank you for your opinion. Considering that my main language is Persian and also the previous translations seem to have been translated by Google Translate, it is better to translate them fluently and slang.

2021-10-23 23:19 UTC, ErfanBahramali commented on src/Symfony/Component/Validator/Resources/translations/validators.fa.xlf
> +                <target>این مجموعه باید فقط شامل عناصر منحصر به فرد باشد.</target>
'حاوی' is not wrong

'یکتا' is a simpler and shorter word

No need to change

2021-10-23 23:21 UTC, BahmanMehrdad commented on src/Symfony/Component/Validator/Resources/translations/validators.fa.xlf
> +                <target>این یک پست الکترونیکی (ایمیل) معتبر نمی‌باشد.</target>
It is exactly like saying "بالگرد" instead of "هلیکوپتر", which is never expressed in this way in fluent Persian. You know that "رایانامه" is only used for some office correspondence and is by no means popular

2021-10-23 23:21 UTC, ErfanBahramali commented
> > > > It is as if there is disagreement and there is a need to discuss these issues
> > > > @BahmanMD Contact me on Telegram or Discord Or you can raise issues in the topic so that other friends can participate
> > > 
> > > 
> > > Unfortunately, most of the objections to the translation indicate that you are not fluent in Persian, because the meanings of the words in Persian may be the same, but the time and place of their use are very important.
> > 
> > 
> > I just say my opinion In this case, you can also get help from the previous translator ( Before me )
> 
> Thank you for your opinion. Considering that my main language is Persian and also the previous translations seem to have been translated by Google Translate, it is better to translate them fluently and slang.

I declare what I think is right according to the documents

2021-10-23 23:24 UTC, BahmanMehrdad commented on src/Symfony/Component/Validator/Resources/translations/validators.fa.xlf
> +                <target>این مقدار با کاراکتر مورد انتظار {{ charset }} مطابقت ندارد.</target>
Finglish is not our official language and our official language is Persian, the meaning of this word is correct in the form of "کاراکترست" and the writing in Finglish has no meaning.

2021-10-23 23:27 UTC, BahmanMehrdad commented on src/Symfony/Component/Validator/Resources/translations/validators.fa.xlf
> +                <target>این مجموعه باید فقط شامل عناصر منحصر به فرد باشد.</target>
"حاوی" and "شامل" are semantically different.
"منحصر به فرد" means smoother than "یکتا".
It is better to change them for a proper translation.

2021-10-23 23:32 UTC, BahmanMehrdad commented
> > > > > It is as if there is disagreement and there is a need to discuss these issues
> > > > > @BahmanMD Contact me on Telegram or Discord Or you can raise issues in the topic so that other friends can participate
> > > > 
> > > > 
> > > > Unfortunately, most of the objections to the translation indicate that you are not fluent in Persian, because the meanings of the words in Persian may be the same, but the time and place of their use are very important.
> > > 
> > > 
> > > I just say my opinion In this case, you can also get help from the previous translator ( Before me )
> > 
> > 
> > Thank you for your opinion. Considering that my main language is Persian and also the previous translations seem to have been translated by Google Translate, it is better to translate them fluently and slang.
> 
> I declare what I think is right according to the documents

I guess you are not familiar with the rules and principles of the Persian language

2021-10-23 23:34 UTC, ErfanBahramali commented
Your words are not convincing at all
I also mentioned the reason for every problem I reported

This discussion is useless

2021-10-23 23:35 UTC, ErfanBahramali commented
It is better for more people to participate

Get help from friends who have worked on this translation before

2021-10-23 23:40 UTC, BahmanMehrdad commented
Unfortunately, your unfamiliarity with the rules does not allow you to be convinced. I will also give you all the reasons I can give you to notice the flaw in the previous translation.
Exactly this discussion is useless.
Good luck

2021-10-23 23:52 UTC, BahmanMehrdad commented
I would be happy for other friends to express their opinions.
Just remember that we want a fluent and meaningful translation and we do not want to use complicated words.

2021-10-24 10:06 UTC, BahmanMehrdad reviewed
Final review.

2021-10-25 12:07 UTC, BahmanMehrdad commented
Hi @fabpot  and @derrabus 
I request to review this PR. Thank you

2021-10-25 12:33 UTC, fabpot commented
I would love to get a review from another native speaker as none of the core team members is able to validate this PR.

2021-10-25 18:35 UTC, Arman-Hosseini commented on src/Symfony/Component/Validator/Resources/translations/validators.fa.xlf
> +                <target>این یک پست الکترونیکی (ایمیل) معتبر نمی‌باشد.</target>
I agree with @ErfanBahramali on this.

2021-10-25 19:18 UTC, BahmanMehrdad commented on src/Symfony/Component/Validator/Resources/translations/validators.fa.xlf
> +                <target>این یک پست الکترونیکی (ایمیل) معتبر نمی‌باشد.</target>
@Arman-Hosseini 
آرمان جان ممنون از پیامت، کلمه رایانامه معمولا کاربردی نداره و کلمه سنگینی هست، بجز نامه های اداری من ندیدم جایی از این کلمه استفاده کنه که همون نامه های اداریهم از پست الکترونیکی استفاده میکنن. ما میخوایم ترجمه روان و راحتی داشته باشیم.
نظر شما و عرفان عزیز محترمه ولی بنظرم بهتره ترجمه عامیانه داشته باشیم تا کلماتی که در عموم تعریفی نداره. باز هم اگر شما دو بزرگوار فکر میکنین به رایانامه تغییر بدم بهتر هست اینکار رو انجام بدم.

2021-10-25 21:02 UTC, BahmanMehrdad commented on src/Symfony/Component/Validator/Resources/translations/validators.fa.xlf
> +                <target>این یک پست الکترونیکی (ایمیل) معتبر نمی‌باشد.</target>
این کلمات بیشتر در نامه های آقای حداد عادل دیده میشه 😄 برای همین بنظرم استفاده از این سبک کلمات در فارسی روان اشتباه هست

2021-10-26 07:37 UTC, BahmanMehrdad commented
Due to changes in the main file, this PR close and another PR open

2021-10-26 07:37 UTC, closed without merging