[Security] Deprecate LogoutListener being returned as 3rd element by FirewallMapInterface::getListeners
symfony/symfony pull request #43674
Opened 2021-10-23 09:41 UTC by scheb

| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | yes
| License       | MIT

[As discussed](https://github.com/symfony/symfony/pull/43548#issuecomment-945187951) with @chalasr, I'm adding these deprecations in preparation for #43548, which is targeting Symfony 6.0.

---

**What's this PR about?**

The 3rd element in the array returned by `FirewallMapInterface::getListeners()` containing the `LogoutListener` will be deprecated. Instead, in Symfony 6.0 the logout listener will be included in the first element, which is then containing _all_ firewall listeners and removing some unnecessary complexity (-> #43548).

This change is a follow-up of introducing the ability to sort security listeners, which was introduced in #37337. There is no longer the need for treating the `LogoutListener` as a special case to get its execution order right.

2021-10-23 10:45 UTC, chalasr requested changes
Thanks for the PR, Christian! I have some concerns with the current BC layer

2021-10-23 10:45 UTC, chalasr commented on src/Symfony/Bundle/SecurityBundle/Security/FirewallMap.php
> +        }
The issue with this notice is that there is no way for end users to get rid of it, meaning that there is no proper upgrade path.

2021-10-23 10:45 UTC, chalasr commented on src/Symfony/Bundle/SecurityBundle/Security/FirewallMap.php
> +        }
Here is an alternative proposal:
- In `Firewall.php:55`: Trigger a deprecation notice `if (isset($listeners[2]))` then `trigger_deprecation('Returning a "%s" as third ...)`
- Deprecate method `FirewallContext::getLogoutListener()
- Mute the `getLogoutListener()` deprecation using an implicit argument when calling it from core, as you did here

Note that IMO there is no hurry, we can tackle this as part of the feature freeze. 
Also if you don't feel super comfortable, just let me know and I can help or just take over this PR.

2021-10-23 11:17 UTC, scheb commented on src/Symfony/Bundle/SecurityBundle/Security/FirewallMap.php
> +        }
Thanks for checking! To share my thoughts:

I see the problem as well, that there's effectively no way to get rid of the deprecation notice. Though I wanted to make sure that when you're using `getListeners` from your application code, that you're informed about the deprecation. To trigger the deprecation only from `Firewall` (on the client side) doesn't cover that use case.

> The issue with this notice is that there is no way for end users to get rid of it, meaning that there is no proper upgrade path.

My thinking was: They could silence the deprecation notice by passing the virtual second `false` parameter to the method call, if the deprecation doesn't affect their code. The same is already happening for the calls coming from within Symfony (i.e. from `Firewall`). They pass the virtual second `false` parameter, because Symfony-interal code will be upgraded with the breaking changes.

2021-10-23 11:56 UTC, chalasr commented on src/Symfony/Bundle/SecurityBundle/Security/FirewallMap.php
> +        }
> Though I wanted to make sure that when you're using getListeners from your application code, that you're informed about the deprecation. To trigger the deprecation only from Firewall (on the client side) doesn't cover that use case.

Your reasoning makes sense. However, we prefer not to make end users aware of such an implicit parameter that is only useful for BC, it should be exclusively internal.
Here I'm taking the pragmatic way, mostly because the potential for calling `getListeners()` outside of `Firewall` in userland is very low. Nobody does that hopefully. 
If it was likely to happen, I'd rather suggest to deprecate the method entirely and add new ones with proper return value (single object type or iterable of single object type). But I think we don't need to go that far now.

So I'm going to insist :) Triggering only from `Firewall` should be enough here as it covers people that are potentially using or decorating the logout listener on the fly from `FirewallMap`.

2021-10-23 12:04 UTC, scheb commented on src/Symfony/Bundle/SecurityBundle/Security/FirewallMap.php
> +        }
All good 👍 Just wanted to make sure we've considered all use-cases and make a reasonable decision.

2021-10-23 12:08 UTC, stof commented on src/Symfony/Bundle/SecurityBundle/Security/FirewallMap.php
> +        }
To me, either we deprecate the method entirely in favor of a new one (but what would be its name ?) or we add a boolean argument allowing the *caller* of the method to opt-in for the new signature (but in such case, we should not only hide the deprecation, we should actually return the new structure so that the code is compatible with Symfony 6). Just silencing a deprecation without actually getting the new behavior is hiding the fact that the code is not compatible with Symfony 6 (and may mean that the code cannot support both 5.4 and 6.0 btw)

2021-10-23 12:17 UTC, chalasr commented on src/Symfony/Bundle/SecurityBundle/Security/FirewallMap.php
> +        }
Right. Deprecating the entire method will make things more simple.

> but what would be its name ?

`getSortedListeners(): iterable` and `getExceptionListener(): ExceptionListener`?

2021-10-23 12:20 UTC, scheb commented on src/Symfony/Bundle/SecurityBundle/Security/FirewallMap.php
> +        }
Deprecate `getListeners` and add instead:

`getFirewallListeners(): array<object>` - Returns _all_ firewall listeners. Since listeners can be any invokeable object, they don't have a specific type. So would be just an array/iterable of objects.

`getExceptionListener(): ExceptionListener` - Return the exception listener (it's always `Symfony\Component\Security\Http\Firewall\ExceptionListener`, right?)

2021-10-23 12:24 UTC, chalasr commented on src/Symfony/Bundle/SecurityBundle/Security/FirewallMap.php
> +        }
Sounds good to me 👍

2021-10-27 10:08 UTC, nicolas-grekas reviewed
Here are some comments, but the 2nd one might not be relevant after @stof's comments (which I agree with: the current deprecation layer should be improved)

2021-10-27 10:08 UTC, nicolas-grekas commented on src/Symfony/Component/Security/Http/CHANGELOG.md
> + * Deprecate the third element of the outer array returned by `FirewallMapInterface::getListener` which contains the `LogoutListener`.
final dot should be removed

2021-10-27 10:08 UTC, nicolas-grekas commented on src/Symfony/Component/Security/Http/FirewallMapInterface.php
> +     * will be removed in Symfony 6.0 and instead the LogoutListener will be
what does "instead the LogoutListener will be included in the first element"?
shouldn't we include it right away?

2021-10-30 10:20 UTC, fabpot commented
@scheb Do you think you can work on this one soon? We are closing 5.4 for new features.

2021-10-30 10:34 UTC, scheb commented
I got time this weekend!

My suggestion would be to combine adding the new methods ([as discussed here](https://github.com/symfony/symfony/pull/43674#discussion_r734964198)) with the changes from #43548 and target 5.4. With new methods added and the existing method becoming deprecated, it should be possible to do it all at once within the 5.4 release.

2021-10-30 17:29 UTC, scheb commented
Force-pushed a draft to deprecate `getListeners` method and add `getFirewallListeners` and `getExceptionListener` as a replacement. Didn't touch the tests yet, would like to get some feedback first if this would be the way to go.

Considerations:
- Wasn't sure of constructor arguments need to be kept backwards compatible. Since `FirewallContext` and `LazyFirewallContext` are somewhat internal to security-bundle, I went with changing them.
- Came to the conclusion that deprecation _and_ #43548 can't be done both in 5.4, because there's no guarantee the new methods are actually implemented by the user.

2021-11-12 23:51 UTC, chalasr commented
> would like to get some feedback first if this would be the way to go.

To me it is, yes 👍 .

> Wasn't sure of constructor arguments need to be kept backwards compatible. Since FirewallContext and LazyFirewallContext are somewhat internal to security-bundle, I went with changing them.

We cannot remove them as these classes are not marked as internal. We need to deprecate these constructor parameters first (happy to help with the BC layer.)

> Came to the conclusion that deprecation and [Security] Remove sorting of security listeners at runtime from Firewall #43548 can't be done both in 5.4, because there's no guarantee the new methods are actually implemented by the user.

Indeed.

2021-11-13 11:37 UTC, scheb commented
> We cannot remove them as these classes are not marked as internal. We need to deprecate these constructor parameters first (happy to help with the BC layer.)

@chalasr Ok, that was what I was afraid of 😟. For derprecating arguments at the end of the argument list it's easy, make it optional and trigger deprecation warning when it's set. Though for arguments in between I'm not really sure how to proceed. Can you point me to an example how to approach this? We could also have a chat on Slack, since that works better for back and forth comms.

2021-11-13 11:52 UTC, wouterj commented
> Though for arguments in between I'm not really sure how to proceed. Can you point me to an example how to approach this?

See e.g: https://github.com/symfony/symfony/blob/0d15daff2950d619ecebb447efdecbf93decb8db/src/Symfony/Component/Security/Http/Firewall/AccessListener.php#L42-L59

Basically:
- Update the argument list to match the new signature
- Remove all type hints from the removed argument to the end of the argument list
- Check one instanceof to see if the old or new signature is used, and activate the BC layer when necessary

2021-11-15 20:33 UTC, scheb commented
So here's a suggestion. The fabbot.io failing seems to be unrelated to my changes. 

Considerations:

- The fact that `$listeners` is an iterable makes things messy when trying to ensure the `LogoutListener` is contained, since it can be either an array or a (lazy-loaded) iterator. Tried to not mess up the lazy-loading iterators.
- `LazyFirewallContext` extending the constructor makes things complicated. Decided to just get the argument that matters for that class (the `$tokenStorage`) from the constructor arguments and push other responsibilities down to be handled in the `FirewallContext` superclass.

2025-02-20 11:35 UTC, closed without merging

2025-02-20 11:35 UTC, nicolas-grekas commented
Let me close here as I think that while cleanups are welcome, this one is hard (with BC implications) for little practical benefit. 3 years passed also :)