[FrameworkBundle] Add completion feature on translation:update command
symfony/symfony pull request #43676
Opened 2021-10-23 11:54 UTC by stephenkhoo

| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Part of #43594
| License       | MIT
| Doc PR        | -

Adding completion for translation:update.
- [x] locale
- [X] bundle 
- [X] --format
- [X] --domain
- [X] --sort

Test for 
- [x] locale
- [x] bundle 
- [X] --format
- [X] --domain
- [X] --sort

Locale completion still under discussion in https://github.com/symfony/symfony/pull/43644#pullrequestreview-786510272

Locale and bundle test still not complete

2021-10-23 20:03 UTC, GromNaN requested changes

2021-10-23 20:03 UTC, GromNaN commented on src/Symfony/Bundle/FrameworkBundle/Tests/Command/TranslationUpdateCommandCompletionTest.php
> +        yield 'format' => [['en', '--format='], ['xlf12', 'xlf20']];
According to the current output in case of wrong format:
> Supported formats are: php, xlf, po, mo, yml, yaml, ts, csv, ini, json, res, xlf12 and xlf20.

2021-10-23 20:03 UTC, GromNaN commented on src/Symfony/Bundle/FrameworkBundle/Command/TranslationUpdateCommand.php
> +            $suggestions->suggestValues(array_keys(self::FORMATS));
```suggestion
            $suggestions->suggestValues(array_merge(
                $this->writer->getFormats(),
                array_keys(self::FORMATS)
            ));
```

2021-10-23 20:03 UTC, GromNaN commented on src/Symfony/Bundle/FrameworkBundle/Command/TranslationUpdateCommand.php
> +            $locale = $input->getArgument('locale');
If the `locale` argument is not set, is it possible to fallback to the default locale? It is required to call the methods after.

2021-10-24 02:10 UTC, stephenkhoo commented on src/Symfony/Bundle/FrameworkBundle/Command/TranslationUpdateCommand.php
> +            $locale = $input->getArgument('locale');
> It is required to call the methods after.

Do you mean after the if statement?

I'm thinking because it is only used within, that's why put the 
`$locale = $input->getArgument('locale');`
after the if statement.

---
It is possible to fallback to the default locale, but the locale input is required, and I think default locale has another purpose?

2021-10-24 06:53 UTC, GromNaN commented on src/Symfony/Bundle/FrameworkBundle/Command/TranslationUpdateCommand.php
> +            $locale = $input->getArgument('locale');
If someone type `bin/console translation:update --domain ` the completion enter in this `if` but the value for `locale` is not set.
It may be a edge case that we chose to ignore and suggest nothing.

2021-10-24 14:02 UTC, stephenkhoo commented on src/Symfony/Bundle/FrameworkBundle/Command/TranslationUpdateCommand.php
> +            $locale = $input->getArgument('locale');
Yes, I think this is more reasonable, because the locale is required, so it makes more sense to only suggest if locale is typed, and we ignore and suggest nothing if locale is not typed in.

So we agree to proceed with
`if ($input->mustSuggestOptionValuesFor('domain') && $locale = $input->getArgument('locale'))` right?

2021-10-25 11:34 UTC, stephenkhoo commented
Added locale completion with `Locales::getLocales()`

will update again if there's other conclusion from https://github.com/symfony/symfony/pull/43644#pullrequestreview-786510272

Otherwise, it seems this PR has achieved its goal?

2021-10-25 13:10 UTC, welcoMattic commented on src/Symfony/Bundle/FrameworkBundle/Command/TranslationUpdateCommand.php
> +            $suggestions->suggestValues(Locales::getLocales());
Same comment as here: https://github.com/symfony/symfony/pull/43644/files#r734297130

TL;DR : it's a huge list, we must reduce it to the currently enabled locales of the application.

2021-10-25 15:36 UTC, stephenkhoo commented on src/Symfony/Bundle/FrameworkBundle/Command/TranslationUpdateCommand.php
> +            $suggestions->suggestValues(Locales::getLocales());
Yeap, just saw the conclusion from there, fixed it with DI for enabled locales already

2021-10-26 07:52 UTC, fabpot requested changes

2021-10-26 07:52 UTC, fabpot commented on src/Symfony/Bundle/FrameworkBundle/Command/TranslationUpdateCommand.php
> +                return $bundle->getName();
We should probably also support bundle aliases here (see https://github.com/symfony/symfony/pull/43682/files#diff-ab7b4bb02fe1986f66a5bde7a77b924f1d86cc26d209c4399e80e8d7ee9554aaR174).

2021-10-26 08:03 UTC, stephenkhoo commented on src/Symfony/Bundle/FrameworkBundle/Command/TranslationUpdateCommand.php
> +                return $bundle->getName();
Noted on this, thank you

2021-10-29 14:48 UTC, fabpot approved these changes

2021-10-29 14:49 UTC, fabpot commented
Thank you @stephenkhoo.

2021-10-29 14:49 UTC, merged