[Translation] Add completion feature on translation pull and push commands
symfony/symfony pull request #43672
Opened 2021-10-23 09:38 UTC by welcoMattic

| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no 
| Tickets       | Fix (partially) https://github.com/symfony/symfony/issues/43594 
| License       | MIT
| Doc PR        | 

This PR adds completion for arguments and options on `translation:pull` and `translation:push` commands.

2021-10-25 16:01 UTC, stof requested changes

2021-10-25 16:01 UTC, stof commented on src/Symfony/Bundle/FrameworkBundle/Tests/Command/AboutCommand/AboutCommandTest.php
> +namespace Symfony\Component\Translation\Tests\Command\AboutCommand;
This change is wrong. This file is in FrameworkBundle

2021-10-25 16:01 UTC, stof commented on src/Symfony/Bundle/FrameworkBundle/Tests/Command/AboutCommand/AboutCommandTest.php
> +namespace Symfony\Component\Translation\Tests\Command\AboutCommand;
same in most other modified files

2021-10-25 16:09 UTC, welcoMattic commented on src/Symfony/Bundle/FrameworkBundle/Tests/Command/AboutCommand/AboutCommandTest.php
> +namespace Symfony\Component\Translation\Tests\Command\AboutCommand;
Thanks, IDK where this change comes from :grimacing:

2021-10-25 16:10 UTC, welcoMattic commented
@GromNaN It's ready for review here

2021-10-25 16:58 UTC, fabpot requested changes

2021-10-25 16:58 UTC, fabpot commented on src/Symfony/Component/Translation/Command/TranslationPushCommand.php
> +    private $providerCollection;
Let's not rename this var as the new name is not "better" than the old one.

2021-10-25 16:58 UTC, fabpot commented on src/Symfony/Component/Translation/Test/TranslationProviderTestCase.php
> +namespace Symfony\Component\Translation\Test;
Moving to the Test namespace means that we allow developers to use it in their own app, with our BC policy. Not sure this is what we want here.

2021-10-25 17:02 UTC, welcoMattic commented on src/Symfony/Component/Translation/Command/TranslationPushCommand.php
> +    private $providerCollection;
I did it to match with the same var in TranslationPullCommand https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Translation/Command/TranslationPullCommand.php#L36

2021-10-26 07:38 UTC, fabpot commented on src/Symfony/Bundle/FrameworkBundle/Tests/Command/AboutCommand/AboutCommandTest.php
> +use Symfony\Component\Translation\Tests\Command\AboutCommand\Fixture\TestAppKernel;
I don't get this change. AFAICS, this file is in the `Symfony\Bundle\FrameworkBundle\Tests\Command\AboutCommand` namespace.

2021-10-26 07:47 UTC, welcoMattic commented on src/Symfony/Bundle/FrameworkBundle/Tests/Command/AboutCommand/AboutCommandTest.php
> +use Symfony\Component\Translation\Tests\Command\AboutCommand\Fixture\TestAppKernel;
Sure, it's a bad manipulation. I revert it.

2021-10-26 07:49 UTC, welcoMattic commented on src/Symfony/Component/Translation/Command/TranslationPullCommand.php
> +            $suggestions->suggestValues(['php', 'xlf', 'xlf12', 'xlf20', 'po', 'mo', 'yml', 'yaml', 'ts', 'csv', 'json', 'ini', 'res']);
Shouldn't we centralize this list of translation file formats somewhere?

2021-10-26 07:52 UTC, fabpot commented on src/Symfony/Component/Translation/Command/TranslationPullCommand.php
> +            $suggestions->suggestValues(['php', 'xlf', 'xlf12', 'xlf20', 'po', 'mo', 'yml', 'yaml', 'ts', 'csv', 'json', 'ini', 'res']);
Not sure it's worth it. Let's keep it that way for now.

2021-10-26 07:53 UTC, fabpot commented on src/Symfony/Component/Translation/Command/TranslationPushCommand.php
> +    private $providerCollection;
Let's revert (we are always trying to minimize the diffs).

2021-10-26 08:18 UTC, welcoMattic commented on src/Symfony/Component/Translation/Command/TranslationPushCommand.php
> +    private $providerCollection;
Ok, I've reverted it

2021-10-26 08:34 UTC, fabpot commented
Can you skip the tests for older versions of Symfony? Like in #43731 for instance.

2021-10-26 08:54 UTC, welcoMattic commented
~The last failing test seems to be related to https://github.com/symfony/symfony/pull/43688~
Rebased on 5.4, everything is green.

2021-10-29 14:45 UTC, fabpot approved these changes

2021-10-29 14:46 UTC, fabpot commented
Thank you @welcoMattic.

2021-10-29 14:46 UTC, merged