Add suggestions for the option 'format' of lints commands: twig, yaml and xliff
symfony/symfony pull request #43680
Opened 2021-10-23 18:29 UTC by makraz

| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | #43594
| License       | MIT
| Doc PR        | -

Adding Bash completion for the following commands:

- lint:twig (--format)
- lint:xliff (--format)
- lint:yaml (--format)

2021-10-23 19:18 UTC, GromNaN requested changes
The 3 commands have the same pattern and does not use the `DescriptorHelper` class. The suggestions could be simply hardcoded in each class.

2021-10-23 19:18 UTC, GromNaN commented on src/Symfony/Bridge/Twig/Tests/Command/LintCommandTest.php
> +        ];
Here is the suggestions that is expected.
```suggestion
        yield 'option' => [['--format', ''], ['txt', 'json', 'github']];
```

2021-10-23 19:18 UTC, GromNaN commented on src/Symfony/Bridge/Twig/Tests/Command/LintCommandTest.php
> +        ];
I'm not sure this case has value, since something should be returned once file path completion will be supported.
```suggestion
```

2021-10-23 19:18 UTC, GromNaN commented on src/Symfony/Component/Translation/Command/XliffLintCommand.php
> +            $helper = new DescriptorHelper();
Same here, the helper is not used by this command. Returned formats are incorrect.

2021-10-23 19:18 UTC, GromNaN commented on src/Symfony/Component/Yaml/Command/LintCommand.php
> +            $helper = new DescriptorHelper();
Same here, the helper is not used by this command. Returned formats are incorrect.

2021-10-23 19:18 UTC, GromNaN commented on src/Symfony/Bridge/Twig/Command/LintCommand.php
> +            $suggestions->suggestValues($helper->getFormats());
This command does not use this helper. Supported formats are specified in the [`display` method](https://github.com/symfony/symfony/pull/43680/files#diff-eef83d0198d3a7daee9a487dbaad38bd11b7be712fd0c65ab3b344a97cdaad83R186-R194) of this class.
```suggestion
            $suggestions->suggestValues(['txt', 'json', 'github']);
```

2021-10-23 20:46 UTC, GromNaN approved these changes

2021-10-24 08:22 UTC, fabpot approved these changes

2021-10-24 08:23 UTC, merged