[FrameworkBundle] Rename translation:update to translation:extract
symfony/symfony pull request #43758
Opened 2021-10-26 16:13 UTC by welcoMattic

| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | yes
| Tickets       | Fix https://github.com/symfony/symfony/issues/41411
| License       | MIT
| Doc PR        | 

As we discussed in https://github.com/symfony/symfony/issues/41411, I've renamed `translation:update` to `translation:extract` which is a more accurate name.

`translation:update` will trigger a deprecation alert until 6.0 where we could remove it completely. For now all the code of the command lives in TranslationExtractCommand.php file, and TranslationUpdateCommand call it.

I think it should be merged after https://github.com/symfony/symfony/pull/43676.

It's my first attempt to deprecate something in Symfony, let me know if I forgot something or if I did something wrong.

2021-10-26 16:47 UTC, nicolas-grekas commented
While at it, let's move the command to the component instead of fwb, wdyt?

2021-10-26 16:51 UTC, stof commented
When renaming a command, we need to have the old name as an alias of the new name in the command. Otherwise, it is a BC break for people calling the command in the CLI.

@nicolas-grekas the command currently relies on getting the Kernel from the Application, which relies on the FrameworkBundle Application, so it does not make sense to move it.

2021-10-26 16:57 UTC, nicolas-grekas commented
But the kernel can be injected to the constructor instead of relying on getApplication, isn't it?

2021-10-26 16:59 UTC, welcoMattic commented
@stof by alias do you mean something like that in console.php ?
```
->alias('console.command.translation_update', 'console.command.translation_extract')
``` 

@nicolas-grekas I'm not comfortable to move the command in the component right now (at least in this PR). Moreover it relies to the Kernel as @stof said, so I'm not sure we can move it.

2021-10-26 17:07 UTC, nicolas-grekas commented
Moving means deprecating, we'd better not deprecate twice the same command, that's why I'm wondering.

2021-10-26 17:10 UTC, stof commented
@welcoMattic no, I'm not talking about aliasing the service. I'm talking about defining aliases for the command *name* in the Command itself

2021-10-26 17:12 UTC, stof commented
Note that there is really 2 separate renamings here:

- renaming the PHP class
- renaming the CLI command

If we are not sure the new location of the class, we might delay that class renaming until Symfony 6.1, doing only the command renaming before the feature freeze.

2021-10-26 17:14 UTC, welcoMattic commented
@stof Ok, I got it. But renaming the CLI command without renaming the file is kind of half done job. I'll try to move it to the Component, I'm just not sure about how to inject the Kernel (like any other service?).

2021-10-26 17:15 UTC, chalasr commented
>  we'd better not deprecate twice the same command

Moving does not necessarily imply deprecating in this case since the command uses the kernel mainly for extracting translations from a given bundle. So the command could be split in one base command located in the component and one bundle-aware decorator in framework-bundle, as we did for yaml and twig lint commands. 
Also this move could apply to other translation commands, I vote for postponing it.

2021-10-26 17:16 UTC, stof commented
@welcoMattic I would still say more than half, as it is the part of the renaming that solves the DX issue (devs using FrameworkBundle don't care about the class names of commands, as FrameworkBundle is registering them)

2021-10-26 17:25 UTC, welcoMattic commented
I've just push the renaming of the CLI command only, with the deprecation trigger in case of usage of `translation:update`.
Are we ok to postpone the renaming/moving of the file to 6.1?

2021-10-26 17:56 UTC, stof requested changes

2021-10-26 17:56 UTC, stof commented on src/Symfony/Bundle/FrameworkBundle/Command/TranslationUpdateCommand.php
> +            trigger_deprecation('symfony/framework-bundle', '5.4', 'Command "translation:update" is deprecated and will be removed in Symfony 6.0. Use "translation:extract" instead.');
this should not use `trigger_deprecation` but write a warning to stderr. The caller of the CLI is not a codebase receiving the PHP deprecations.

2021-10-26 17:56 UTC, stof commented on src/Symfony/Bundle/FrameworkBundle/Command/TranslationUpdateCommand.php
> +            ->setAliases(['translation:update'])
the alias should actually be defined in `$defaultName` (using `|` to separate the various names) to make it compatible with lazy-loading the command.

2021-10-26 18:53 UTC, welcoMattic commented on src/Symfony/Bundle/FrameworkBundle/Command/TranslationUpdateCommand.php
> +            trigger_deprecation('symfony/framework-bundle', '5.4', 'Command "translation:update" is deprecated and will be removed in Symfony 6.0. Use "translation:extract" instead.');
We already have `trigger_deprecation` calls below in the file, what about those? Should I change it too?

2021-10-26 18:56 UTC, chalasr commented on src/Symfony/Bundle/FrameworkBundle/Command/TranslationUpdateCommand.php
> +            trigger_deprecation('symfony/framework-bundle', '5.4', 'Command "translation:update" is deprecated and will be removed in Symfony 6.0. Use "translation:extract" instead.');
Please yes, in another PR targeting the branch they have been introduced in

2021-10-27 19:44 UTC, chalasr commented
When deprecating something, we try to keep at least one test covering the legacy behavior. Can you please do that?
Rebase needed also

2021-10-28 07:08 UTC, welcoMattic commented
@chalasr thanks for the advice, it's done [here](https://github.com/symfony/symfony/pull/43758/files#diff-31da7cae0444fc6b56e28552e06cde537747f528d5fec6af7c551ff36330928fR32), rebase too.

2021-10-28 07:54 UTC, chalasr approved these changes

2021-10-28 08:01 UTC, fabpot approved these changes

2021-10-28 08:01 UTC, fabpot commented
Thank you @welcoMattic.

2021-10-28 08:01 UTC, merged