[Console] Runtime conflict for psr/log >= 3.0 instead of composer conflict
symfony/symfony pull request #43884
Opened 2021-11-02 11:15 UTC by fancyweb

| Q             | A
| ------------- | ---
| Branch?       | 5.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | -

`ConsoleLogger` is not compatible with `psr/log >= 3.0` but it's an optional feature and `psr/log` is an optional dependency in the Console component. Yet, having a real "composer conflict", prevents `symfony/console` from being updated above the `5.3.2` version if a previous dependency has already installed `psr/log 3.0`. But I'd rather have an updated `symfony/console` version and `psr/log 2.0` since the `psr/log` changes are just about types.

2021-11-02 11:24 UTC, stof commented
Well, to me, letting the solver know about the conflict is better than forcing the user to manage dependencies manually.

Cases where the latest versions of packages are incompatible together need to be resolved by the user anyway to choose which requirement they want to relax, but that's only happening properly if the solver knows about the incompatibility.
And `composer why-not symfony/console 5.3.7` will tell you why you don't get the 5.3.7 version for instance.

2021-11-02 11:29 UTC, derrabus requested changes
I think, no matter how we deal with this issue, there will be a group of people dissatisfied with our solution. Currently, we have a well documented incompatibility that should be easy to resolve. Moving this to a runtime check feels like we're doing the job Composer should've done.

I'm not convinced we should make this change.

2021-11-02 11:44 UTC, nicolas-grekas commented
Shouldn't we have a mix here? This exception in 5.3 and the conflict in 5.4?
Since 5.3.2 is already tagged without the conflict, the harm is already done for 5.4.

What about moving the check to the constructor though?

2021-11-02 11:54 UTC, derrabus commented
> Since 5.3.2 is already tagged without the conflict, the harm is already done for 5.3.

Good point. If we restore the conflict in 5.4, I'm 👍 

> What about moving the check to the constructor though?

That wouldn't work because the class definition itself raises a fatal error, doesn't it?

2021-11-02 12:02 UTC, derrabus approved these changes

2021-11-02 12:57 UTC, nicolas-grekas approved these changes

2021-11-03 06:58 UTC, fabpot commented
Thank you @fancyweb.

2021-11-03 06:58 UTC, merged