4.4
symfony/symfony pull request #43964
Opened 2021-11-08 14:03 UTC by agaktr

| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #43719 
| License       | MIT

Greek Translation Addition.

2021-11-08 14:06 UTC, derrabus requested changes
Thank you for your contributon. Please remove all extra files from this PR and restore the newline@EOF of the updated language file.

2021-11-08 14:22 UTC, derrabus commented on .gitignore
> +/.phpunit
Should be reverted.

2021-11-08 14:22 UTC, agaktr commented
Not sure why PHPUnit tests fail, some issue with MongoDB or something?! Have not touched anything :_)

2021-11-08 14:23 UTC, derrabus commented
> Not sure why PHPUnit tests fail, some issue with MongoDB or something?! Have not touched anything :_)

You can ignore test failures that are unrelated to you changes.

2021-11-08 15:23 UTC, agaktr commented
Inform me if i have to do anything else :)

2021-11-08 16:21 UTC, derrabus commented
Still the same. Please revert your changes to the `.gitignore` file and remove your `.idea` folder from the PR, please. We cannot merged your PR with all that noise in there.

2021-11-09 13:17 UTC, agaktr commented
Terribly sorry... Not sure how they reappeared! I believe i fixed this now!

2021-11-09 14:00 UTC, derrabus commented
There's still a change in the `.gitignore` file (missing new line at EOF). Revert that file too, please. The language file must be the only file changed by this PR.

2021-11-09 15:10 UTC, agaktr commented
added it!

2021-11-09 15:41 UTC, fabpot approved these changes

2021-11-09 15:43 UTC, fabpot commented
Thank you @agaktr.

2021-11-09 15:44 UTC, merged

2021-11-10 11:47 UTC, agaktr commented
Anytime! Actually now that I learned how to do the translations I could do that on any new GR content!