Zsh shell autocompletions
symfony/symfony pull request #43970
Opened 2021-11-09 10:22 UTC by adhocore

| Q             | A
| ------------- | ---
| Branch?       | 5.4 for features 
| Bug fix?      | no
| New feature?  | yes 
| Deprecations? | no 
| Tickets       | Fix #43592 
| License       | MIT
| Doc PR        | - 

### Usage
#### Setup/Install
In `zsh` terminal run:
```zsh
bin/console completion zsh > "$fpath[1]/console"
```
which will add dumped zsh completion helper in first fpath (zsh's functions autoload path).
Then reload shell or just do `source "$fpath[1]/console"`.

---

Here's a simple script `sfzsh` that I'm using while adding the **zsh** autocompletion support as a testbed:

<details><summary>Toggle code</summary>
<p>

```php
#!/bin/env php
<?php

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Completion\CompletionInput;
use Symfony\Component\Console\Completion\CompletionSuggestions;
use Symfony\Component\Console\Descriptor\ApplicationDescription;
use Symfony\Component\Console\Helper\DescriptorHelper;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;

putenv('SYMFONY_COMPLETION_DEBUG=1');

$app = new Application('sfzsh', '0.0.1');

// test1
$app->add(new class() extends Command {
    protected static $defaultName = 'test1';
    protected static $defaultDescription = 'Test one cmd';

    protected function configure(): void
    {
        $this
            ->addOption('t1o1', '1', InputOption::VALUE_REQUIRED, 't1o1 str val')
            ->addOption('t1o2', '2', InputOption::VALUE_REQUIRED | InputOption::VALUE_IS_ARRAY, 't1o2 array val')
            ->addArgument('php', InputArgument::REQUIRED, 'PHP file in current dir')
        ;
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        return 0;
    }

    public function complete(CompletionInput $input, CompletionSuggestions $suggestions): void
    {
        if ($input->mustSuggestOptionValuesFor('t1o1')) {
            $suggestions->suggestValues(['t1o1.v1', 't1o1.v2']);

            return;
        }

        if ($input->mustSuggestOptionValuesFor('t1o2')) {
            $suggestions->suggestValues(['t1o2.v1', 't1o2.v2']);

            return;
        }

        if ($input->mustSuggestArgumentValuesFor('php')) {
            $suggestions->suggestValues([system('ls -1 *.php')]);

            return;
        }
    }
});

// test2
$app->add(new class() extends Command {
    protected static $defaultName = 'test2';
    protected static $defaultDescription = 'Test two cmd';

    protected function configure(): void
    {
        $this
            ->addOption('t2o1', '1', InputOption::VALUE_REQUIRED, 't2o1 str val')
            ->addOption('t2o2', '2', InputOption::VALUE_REQUIRED | InputOption::VALUE_IS_ARRAY, 't2o2 array val')
            ->addArgument('dir', InputArgument::REQUIRED, 'subdir in current dir')
        ;
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        return 0;
    }

    public function complete(CompletionInput $input, CompletionSuggestions $suggestions): void
    {
        if ($input->mustSuggestOptionValuesFor('t2o1')) {
            $suggestions->suggestValues(['t2o1.v1', 't2o1.v2']);

            return;
        }

        if ($input->mustSuggestOptionValuesFor('t2o2')) {
            $suggestions->suggestValues(['t2o2.v1', 't2o2.v2']);

            return;
        }

        if ($input->mustSuggestArgumentValuesFor('dir')) {
            $suggestions->suggestValues([system('ls -1d */')]);

            return;
        }
    }
});

$app->run();
```
</p>
</details>

```zsh
sfzsh completion zsh > "${fpath[1]}/sfzsh"
. "${fpath[1]}/sfzsh"
```
#### Autocomplete commands
```zsh
sfzsh [TAB]
```
![image](https://user-images.githubusercontent.com/2908547/140903159-718e27bd-226a-4e15-b976-88fc34b74d3b.png)

> Shortlisting works too: `sfzsh te[TAB]` autocompletes for `test1` and `test2`

> Fuzzy match works too: `sfzsh t1[TAB]` autocompletes `test1`
  
#### Autocomplete options
```zsh
 sfzsh test1 --[TAB]
```
![image](https://user-images.githubusercontent.com/2908547/140903736-bdbd4c1b-5a39-4e68-83f5-e8580bcf53e3.png)

#### Autocomplete option values
```zsh
sfzsh test1 --t1o1 [TAB]
```
![image](https://user-images.githubusercontent.com/2908547/140904073-4445f053-7abe-4e94-9582-9df185aadf57.png)

> `=` separator works too: `sfzsh test1 --t1o1=[TAB]`

#### Autocomplete args
```zsh
sfzsh test1 [TAB]
```
> |_ (autocompletes *.php files in current dir)

```zsh
sfzsh test2 [TAB]
```
> |_ (autocompletes subdirs in current dir)

2021-11-09 10:30 UTC, adhocore commented
maybe a false positive in fabbot ci for typo?
`"help": "The <info>completion</> command dumps the shell completion script required\nto`
is suggested to be
`"help": "The <info>completion</> command dumps the shell completion script required\not`

the `\n` is LF and not `not`

2021-11-09 10:32 UTC, stof commented
Yeah, this definitely looks like a false positive

2021-11-09 10:33 UTC, adhocore commented
@stof  i used auto sync upstream from github ui, so any idea how can i remove the Merge commit now?

2021-11-09 10:35 UTC, stof commented
@adhocore see https://symfony.com/doc/current/contributing/code/pull_requests.html#rebase-your-pull-request

2021-11-10 15:01 UTC, GromNaN requested changes
I like that you added comments in the script; especially since we don't have a way to write test on it for now.

I have a suggestion to avoid shell-specific code in `Application` class.

2021-11-10 15:01 UTC, GromNaN commented on src/Symfony/Component/Console/Application.php
> +                return $command->isHidden() ? null : $command->getName().($input->isShell('zsh') ? "\t".$command->getDescription() : '');
Testing if shell is zsh seems very specific for this place.

We could use a DTO. The `ZshCompletionOutput` would format the value with its specificities. By implementing the `__toString` method, the `BashCompletionOutput` would not require any change.

```php
namespace Symfony\Component\Console\Completion;

final class SuggestedValue {
    private $value;
    private $description;

    public function __construct(string $value, string $description = null) {
        $this->value = $value;
        $this->description = $description;
    }

    public function __toString(): string {
        return $this->value;
    }
}
```

2021-11-10 15:01 UTC, GromNaN commented on src/Symfony/Component/Console/Resources/completion.zsh
> +        requestComp="${requestComp} -i\" \""
That makes the `CompletionInput::getCurrentValue()` equals to a space? it would be better to skip the value entirely.

2021-11-10 15:01 UTC, GromNaN commented on src/Symfony/Component/Console/Completion/CompletionInput.php
> +        return $old;
The "old" value is never used.

```suggestion
    public function setShell(string $shell): void
    {
        $this->shell = $shell;
```

2021-11-10 15:46 UTC, adhocore commented on src/Symfony/Component/Console/Resources/completion.zsh
> +        requestComp="${requestComp} -i\" \""
i think it still requires -i option equal or 1 more than -c option that's why

2021-11-10 15:52 UTC, adhocore commented on src/Symfony/Component/Console/Application.php
> +                return $command->isHidden() ? null : $command->getName().($input->isShell('zsh') ? "\t".$command->getDescription() : '');
or maybe some abstraction to tell/handle if the shell supports description for autocompleted suggestion

2021-11-10 18:03 UTC, GromNaN commented on src/Symfony/Component/Console/Application.php
> +                return $command->isHidden() ? null : $command->getName().($input->isShell('zsh') ? "\t".$command->getDescription() : '');
That would add complexity in all commands that implements completion. I'm not sure this is something we want. 
Each command should set suggestions values, optionally with a description using this DTO.

2021-11-10 18:04 UTC, GromNaN commented on src/Symfony/Component/Console/Resources/completion.zsh
> +        requestComp="${requestComp} -i\" \""
Then, does it work with an empty string?
```suggestion
        requestComp="${requestComp} -i\"\""
```

2021-11-11 07:20 UTC, adhocore commented on src/Symfony/Component/Console/Resources/completion.zsh
> +        requestComp="${requestComp} -i\" \""
no it can't be empty

2022-07-20 17:06 UTC, fabpot commented
@adhocore @GromNaN What's the status of this PR?
I see that, at least, it needs to be rebased on current 6.2.

2022-07-21 21:52 UTC, GromNaN commented
Hello @adhocore. I created a new PR to rebase your work and change how descriptions are output.  
Please feel free to review #47018.

2022-07-21 21:52 UTC, closed without merging