[Serializer][Messenger] Deprecate "context aware" interfaces
symfony/symfony pull request #43982
Opened 2021-11-09 17:42 UTC by mtarld

| Q             | A
| ------------- | ---
| Branch?       | 6.1 (but not ready yet)
| Bug fix?      | no
| New feature?  | no
| Deprecations? | yes
| Tickets       | 
| License       | MIT
| Doc PR        | TODO

In `supports*` methods, we are really often relying on serialization context.
Previously (~2017), in order to have the context in these methods (and be BC compatible), new interfaces were introduced:
- `ContextAwareNormalizerInterface`
- `ContextAwareDenormalizerInterface` 
- `ContextAwareEncoderInterface`
- `ContextAwareDecoderInterface`

But right now, thanks to the `DebugClassLoader`, we're able to have an upgrade path where the regular interfaces:
- `NormalizerInterface`
- `DenormalizerInterface` 
- `EncoderInterface`
- `DecoderInterface`
can be updated to rely on the serialization context.

Therefore, the "context aware" interfaces could be deprecated in favor of "regular" ones (and then save 4 interfaces in 7.0).

2021-11-09 17:46 UTC, mtarld commented
fabbot.io isn't happy because I touched to `XmlEncoder`:
```diff
-        throw new NotEncodableValueException('An unexpected value could not be serialized: '.(!\is_resource($data) ? var_export($data, true) : sprintf('%s resource', get_resource_type($data))));
+        throw new NotEncodableValueException('An unexpected value could not be serialized: '.(!\is_resource($data) ? var_export($data, true) : sprintf('"%s" resource', get_resource_type($data))));
```

But this isn't related to the current PR.

2021-11-09 17:46 UTC, mtarld commented
fabbot.io isn't happy because I touched to `XmlEncoder`:
```diff
-        throw new NotEncodableValueException('An unexpected value could not be serialized: '.(!\is_resource($data) ? var_export($data, true) : sprintf('%s resource', get_resource_type($data))));
+        throw new NotEncodableValueException('An unexpected value could not be serialized: '.(!\is_resource($data) ? var_export($data, true) : sprintf('"%s" resource', get_resource_type($data))));
```

But this isn't related to the current PR.

2021-11-09 17:46 UTC, dunglas approved these changes
LGTM!

2021-11-09 19:18 UTC, ogizanagi approved these changes

2021-12-25 19:09 UTC, nicolas-grekas requested changes

2021-12-25 19:09 UTC, nicolas-grekas commented on UPGRADE-6.1.md
> +-----
Please fix the number of dashes

2021-12-25 19:09 UTC, nicolas-grekas commented on src/Symfony/Component/Serializer/Serializer.php
> +class Serializer implements SerializerInterface, NormalizerInterface, DenormalizerInterface, EncoderInterface, DecoderInterface
removing the legacy interface is a BC break

2022-01-07 12:26 UTC, chalasr approved these changes

2022-01-09 10:51 UTC, fabpot approved these changes

2022-01-09 10:52 UTC, fabpot commented
Thank you @mtarld.

2022-01-09 10:52 UTC, merged