[Mailer][Mailgun] Allow multiple TagHeaders with MailgunApiTransport
symfony/symfony pull request #44137
Opened 2021-11-19 08:49 UTC by starred-gijs

| Q             | A
| ------------- | ---
| Branch?       | 5.3 
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| License       | MI
| Doc PR        |

Mailgun allows you to set [3 tags per message](https://documentation.mailgun.com/en/latest/user_manual.html#tagging) but the current implementation in MailgunApiTransport, any consecutive TagHeader will override the previous one. Because it uses FormDataPart to build the payload, by using a integer key, it allows to set multiple parts with the same name #38323
The MailgunHttpTransport already supports multiple TagHeaders and I added a test to prove that.

2021-12-09 15:12 UTC, starred-gijs commented
Hi @kbond, you implemented the original version for Mailgun TagHeader support, are you the right person to ask for a review/feedback?

2021-12-09 22:06 UTC, kbond requested changes
Thanks for the ping @starred-gijs! This looks good to me but let's add as a new feature so you'll need to target 6.1.

2021-12-10 08:48 UTC, starred-gijs commented
Thanks for your reply! Any change I can convince you to handle this as a bug? 😄 
Main reason is that multiple `TagHeader` does work with the `MailgunHttpTransport` and this PR fixes it for `MailgunApiTransport`.

2021-12-10 12:57 UTC, kbond commented
I admit this feels like a bit of a grey area personally and I know the frustration of having to wait a few versions for a fix like this. I'm falling back on the established Symfony process and this would be considered a feature. The code isn't currently broken, it just doesn't allow a specific feature provided by Mailgun.

2021-12-10 13:01 UTC, starred-gijs commented
Oke fair enough, it was worth a try. I will rebase and target 6.1 :)

2021-12-10 13:02 UTC, kbond commented
Awesome, and thanks for understanding :)

2021-12-10 13:15 UTC, kbond approved these changes

2021-12-10 18:59 UTC, OskarStark commented on src/Symfony/Component/Mailer/Bridge/Mailgun/CHANGELOG.md
> + * Allow multiple TagHeaders with MailgunApiTransport
```suggestion
 * Allow multiple `TagHeader`s with `MailgunApiTransport`
```

2021-12-10 19:00 UTC, OskarStark approved these changes
Only one minor

2021-12-10 19:20 UTC, dooooofhgf approved these changes

2021-12-11 14:45 UTC, fabpot approved these changes

2021-12-11 14:47 UTC, fabpot commented
Thank you @starred-gijs.

2021-12-11 14:47 UTC, merged

2021-12-13 13:25 UTC, starred-gijs commented
@OskarStark Thanks for the review! 
Sorry did not read your comment in time to change it, its now already merged so I will leave it as is.

2021-12-13 18:10 UTC, OskarStark commented
No problem, thanks for reaching out

2021-12-13 18:19 UTC, fabpot commented
I've made the change myself while merging as it was a small one.

2022-03-01 12:00 UTC, starred-gijs commented
> I admit this feels like a bit of a grey area personally and I know the frustration of having to wait a few versions for a fix like this. I'm falling back on the established Symfony process and this would be considered a feature. The code isn't currently broken, it just doesn't allow a specific feature provided by Mailgun.

Not to disrespect anyone, but how is this PR different? https://github.com/symfony/symfony/pull/45274

2022-03-01 12:51 UTC, kbond commented
> Not to disrespect anyone

None taken :)

> but how is this PR different?

I chose https://github.com/symfony/symfony/pull/45274 as a bug fix because multiple tags were already implemented, tested, and documented for Mailchimp. The way they were added was not consistent.