Leverage array_is_list
symfony/symfony pull request #44167
Opened 2021-11-20 18:44 UTC by jderusse

| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | -

Use `array_is_list` instead of `count`+`range`+`array_key`

take over #44156

2021-11-20 19:03 UTC, fancyweb reviewed
Looks like there is one more here: https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Intl/Data/Bundle/Writer/TextBundleWriter.php#L84

2021-11-20 19:03 UTC, fancyweb commented on src/Symfony/Bundle/FrameworkBundle/composer.json
> +        "symfony/polyfill-php81": "^1.16",
```suggestion
        "symfony/polyfill-php81": "^1.22",
```

The first release is 1.22.0.

2021-11-20 19:04 UTC, derrabus requested changes

2021-11-20 19:04 UTC, derrabus commented on src/Symfony/Bundle/FrameworkBundle/composer.json
> +        "symfony/polyfill-php81": "^1.16",
```suggestion
        "symfony/polyfill-php81": "^1.22",
```

The function that we need was introduced with 1.22.0. See symfony/polyfill#324

2021-11-20 19:04 UTC, derrabus commented on src/Symfony/Component/DependencyInjection/composer.json
> +        "symfony/polyfill-php81": "^1.16",
```suggestion
        "symfony/polyfill-php81": "^1.22",
```

2021-11-20 19:05 UTC, derrabus commented
Looks like @fancyweb was a few seconds faster than me. 🙈

2021-11-20 20:38 UTC, jderusse commented
:facepalm:

2021-11-20 21:22 UTC, derrabus approved these changes

2021-11-21 10:07 UTC, fabpot approved these changes

2021-11-21 10:07 UTC, fabpot commented
Thank you @jderusse.

2021-11-21 10:07 UTC, merged