Adding setSymbolsMap()
symfony/symfony pull request #44199
Opened 2021-11-22 19:33 UTC by ThomasLandauer

| Q             | A
| ------------- | ---
| Branch?       | 5.4 for features
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | None
| License       | MIT
| Doc PR        | None yet

Am I right that there is no way to configure the `$ymbolsMap` when using the Symfony framework integration (i.e. dependency injection)?
What about adding a public method for this?
The feature to set it in the constructor was added in https://github.com/symfony/symfony/pull/36456

Waiting for feedback before continuing.

2021-11-22 20:01 UTC, ThomasLandauer commented
Besides, it would be nice to be able to set *global* options for the slugger (i.e. at https://symfony.com/doc/current/reference/configuration/framework.html) - just like `cocur/slugify` allows: https://github.com/cocur/slugify#symfony-configuration

2021-11-22 20:56 UTC, xabbuh commented
> Besides, it would be nice to be able to set global options for the slugger (i.e. at https://symfony.com/doc/current/reference/configuration/framework.html)

Given the reason why you wanted to introduce this method I think it would make more sense to introduce that possibility than adding the setter method.

2021-11-22 21:02 UTC, derrabus requested changes
I believe it was an intentional design decision to make the symbols map immutable. The map can be set via the constructor and you could easily wire your own configuration of the slugger if you need a different map.

Making the map configurable in FrameworkBundle could also be feasible, but I'm afraid that it's a bit too late to squeeze that into the already frozen 5.4 release.

2021-11-22 21:22 UTC, nicolas-grekas commented
Yep, this is intentional: having the service immutable is desired.
I guess it's possible to wire a new value in a compiler pass, or by replacing the service definition, isn't it?
Dunno if this is common enough to be added to configuration though.
To be discussed for 6.1.

2021-11-23 00:22 UTC, ThomasLandauer commented
Setter vs. configuration: Well, both would be nice ;-) If you're using the slugger in 100 services, you need the configuration; if you have *one* exception, you need the setter ;-)

Version: I didn't really mean to get this into 5.4 ;-)

This is the default `$symbolsMap`:

> 'en' => ['@' => 'at', '&' => 'and'],

... and this looks like a "template" to me, showcasing how to set it up. So at least an easy way to get `'&' => 'and'` in more languages would be nice :-)

This is the first Symfony feature I'm seeing where the framework integration is *harder* to use than the standalone (cause you can't just pass it to the constructor). Shouldn't this be the other way round?
But maybe the following is the answer and it's just not documented:

"wire your own configuration" or "replacing the service definition": How does this work?

2021-11-23 00:39 UTC, stof commented
> if you have _one_ exception, you need the setter ;-)

No. You need a separate instance. If you use the setter for this exception, you also affect the usages done in other services after you called that setter.
That's the main reason why we avoid setters on services. It makes things a lot harder to reason about.

2021-12-31 14:39 UTC, fancyweb commented
Should we close this one?

2021-12-31 15:03 UTC, closed without merging

2023-03-20 22:08 UTC, ThomasLandauer commented
Indeed, if I pass `->args()` in my `services.php`, it works:
```php
$services->set('slugger', AsciiSlugger::class)->args(['de', ['de' => ['&' => 'und']]]);
```
However, if I pass `->arg()` it does not work:
```php
$services->set('slugger', AsciiSlugger::class)->arg('$symbolsMap', ['de' => ['&' => 'und']]);
```
Does anybody have an idea, why?
The argument name `$symbolsMap` is correct, see https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/String/Slugger/AsciiSlugger.php