[Messenger] #44254 Changing queue name precedence
symfony/symfony pull request #44291
Opened 2021-11-26 16:24 UTC by aderiyenko

| Q             | A
| ------------- | ---
| Branch?       | 5.3 
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #44254 
| License       | MIT

Suggesting to change the precedence of `queue_name` option to `config -> DSN -> default ("messages")` instead of current `DSN -> config -> default ("messages")`

2021-11-26 17:30 UTC, jderusse requested changes
The DSN takes precedence over the options on purpose.

ie. PROD and PRE_PROD share the same configuration (and same `queue_name` in the messenger.yaml) but they use 2 differents DSN to define the targeted queue.

If you want to share the same DSN across different configurations, you can either:
- remove the queue name from the ENV variabnle, in that way, the connection will fallback to the option
- make the queue name part the DSN. ie. `dsn : "%env(MESSENGER_TRANSPORT_DSN)%/my_queue"`

2021-11-26 17:30 UTC, jderusse commented on src/Symfony/Component/Messenger/Bridge/AmazonSqs/Tests/Transport/ConnectionTest.php
> -        return new MockResponse(<<<XML
not related. to be reverted

2021-11-28 13:07 UTC, aderiyenko commented on src/Symfony/Component/Messenger/Bridge/AmazonSqs/Tests/Transport/ConnectionTest.php
> -        return new MockResponse(<<<XML
reverted, thanks!

2021-11-28 13:08 UTC, aderiyenko commented
Thanks for your review @jderusse !

In this case I'll let the reporter [here](https://github.com/symfony/symfony/issues/44254) know to just remove the queue name from the DSN and specify it explicitly in the options. 

And then I just left a test for the default message name == 'messages' as I haven't found such a test in the suite.

LMK if it makes sense and thanks again!

2026-02-23 15:29 UTC, nicolas-grekas commented
Thank you @aderiyenko.

2026-02-23 15:29 UTC, merged