[Form]Improve Persian (Farsi) Translation For Forms
symfony/symfony pull request #44512
Opened 2021-12-08 20:05 UTC by mostafazs

| Q             | A
| ------------- | ---
| Branch?       | 6.1 
| Bug fix?      | no
| New feature?  | no 
| Deprecations? | no 
| License       | MIT

Improve Persian (Farsi) Translation For Form Component Translation File.

2021-12-12 07:53 UTC, BahmanMD requested changes

2021-12-12 07:53 UTC, BahmanMD commented on src/Symfony/Component/Form/Resources/translations/validators.fa.xlf
> +                <target>گزینه‌ انتخاب‌شده نامعتبر است.</target>
This text should be replaced with this sentence (There must be a space between the two words `انتخاب‌` and `شده`). The rest of the edited sentences are correct:
`<target>گزینه‌ انتخاب‌ شده نامعتبر است.</target>`

2021-12-12 13:50 UTC, mostafazs commented on src/Symfony/Component/Form/Resources/translations/validators.fa.xlf
> +                <target>گزینه‌ انتخاب‌شده نامعتبر است.</target>
Yes, That's Correct too.

2021-12-12 14:03 UTC, mostafazs reviewed
Correct

2021-12-12 16:43 UTC, azjezz approved these changes

2021-12-12 16:57 UTC, BahmanMD approved these changes

2021-12-12 17:01 UTC, azjezz commented
This should be considered a bug fix, and merged in 5.4 i suppose.

2021-12-13 06:46 UTC, mostafazs commented
> This should be considered a bug fix, and merged in 5.4 I suppose.

@azjezz so I must remove this PR and create a new one on the 5.4 repo? I don't know that 6.1 is just for new features.

2021-12-13 08:11 UTC, fancyweb commented
All translations are actually backported to the lowest maintained branch (4.4 atm) so you can just change the target branch to 4.4 and there shouldn't be any conflict.

2021-12-13 12:44 UTC, wouterj approved these changes

2021-12-13 12:46 UTC, wouterj commented
Thank you @mostafazs!

As you created the PR on the 6.1 branch of your fork, I took your commit and created a new PR to 4.4: #44591 We'll merge it to 6.1 from there.

For your next contribution, it is recommended that you create a new branch for each PR (see [the contributing docs](https://symfony.com/doc/current/contributing/code/pull_requests.html#create-a-topic-branch)). A PR is always between a branch in your fork and the main repository. Having a separate branch for each PR allows to work on more than 1 PR at the same time. And it makes sure you can freely change the base version without changing the 6.1 branch in your fork.

However, as I only took your commit, you're still the full author of this change. All credits (and badges) to you and hope to see you back another time!

2021-12-13 12:46 UTC, closed without merging