Allow route paths and prefixes to be lists
symfony/symfony pull request #44849
Opened 2021-12-29 14:15 UTC by kylekatarnls

| Q             | A
| ------------- | ---
| Branch?       | 6.1
| Bug fix?      | no (likely)
| New feature?  | yes (likely)
| Deprecations? | no
| Tickets       | Fix #44840
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

Allow "intuitive" usage of `Route` ro define multiple route paths where each has multiple possible prefixes.:
```php
#[Route(['/attr1', '/attr2'])]
class AttributeController
{
    #[Route(['/route1', '/route2'])]
    public function ok(): Response
    {
        return new Response('OK');
    }
}
```

2021-12-29 15:59 UTC, fancyweb requested changes
Can you please add tests covering all the use cases from your issue?

2021-12-29 19:20 UTC, kylekatarnls commented
This PR fixes the array case, so I added a test for this case, an other PR is needed for the case of multiple prefixes using several attributes.

2021-12-29 23:17 UTC, derrabus commented
I'm not very fond of this change since, I must admit. It introduces another edge-case to the route attributes and passing paths as array is already used by the localized routes feature. Also, what impact does this change have on route generation?

I think, there are already ways to achieve what this PR attempts to achieve. For instance, the `Route` attribute can be repeated if you want to match multiple paths to the same controller. Also, there's the possibility of aliasing routes now.

Can you elaborate why both solutions would not work for you or would be significantly inferior to the solution you're proposing?

2022-01-04 13:40 UTC, BafS commented
What is strange, I think, is to be able to use multiple `Route` on the method level but not on the controller level.

Example with a new controller in symfony/demo:

```php
#[Route(['/controller1', '/controller2'])]
#[Route('/controller3')]
class TestController extends AbstractController
{
    #[Route('/a', name: 'a')]
    public function a(): Response {
        return new Response('a');
    }

    #[Route(['/b1', '/b2'], name: 'b12')]
    #[Route('/b3', name: 'b3')]
    public function b(): Response {
        return new Response('b');
    }
}
```

```
./bin/console debug:router | grep controller
  a                          ANY        ANY      ANY    /{_locale}/controller1/a
  a.1                        ANY        ANY      ANY    /{_locale}/controller2/a
  b12                        ANY        ANY      ANY    /{_locale}/controller1/b1
  b12.1                      ANY        ANY      ANY    /{_locale}/controller2/b2
  b3                         ANY        ANY      ANY    /{_locale}/controller1/b3
  b3.1                       ANY        ANY      ANY    /{_locale}/controller2/b3
```

Here `/b1` and `/b2` appear, so the array path is working. `/b3` appear, the multiple attributes is working for a method but we never see `/controller3`, multiple attributes are not working on the controller level.

But when going on my browser, only `.../controller1/a`, `.../controller1/b1` and `.../controller1/b3` are working which is quite confusing.

Edit: and that's what we have in the profiler, even more confusing:

<img width="847" alt="image" src="https://user-images.githubusercontent.com/588205/148068371-255988d0-6181-447e-825e-2793477bf8b4.png">

2022-01-04 14:09 UTC, kylekatarnls commented
Yes, if ever this is not valid usage, then could you (@symfony) please:
- Provide an alternative that could be used via attributes and would be consistent for both class and method?
- Add an exception on next major version so lists (non-associative arrays) as route path would be explicitly forbidden (and reference the alternative in the exception message)?

If you feel like this is the way to handle this, I could make a PR for the exception, but about the first thing (attribute-style alias matrix declaration) I was not able to find it.

2022-01-04 22:21 UTC, derrabus commented
I think the sanest way forward would be to deprecate passing arrays to `$path` and turn `$localizedPaths` into a constructor parameter.

2022-01-05 15:34 UTC, kylekatarnls commented
@derrabus OK but again in my use case, there is no localized paths. We're using multiple paths as simple aliases. This might just work by accident but it does and array syntax comes here rather naturally and this is a legit use case.

If it's deprecated, an alternative for this use case (alias at both class-level and method-level) would be nice. Documentation or code snippet for it would be awesome.

2022-01-05 15:52 UTC, derrabus commented
> @derrabus OK but again in my use case, there is no localized paths.

Well yes, you use that feature whether you like it or not.

> We're using multiple paths as simple aliases. This might just work by accident but it does and array syntax comes here rather naturally and this is a legit use case.

Very well, but you're sugesting to turn the accident into a feature. I don't think we should do that.

2022-01-05 15:53 UTC, stof commented
Passing an array as a way to define aliases (rather than localized paths) is definitely something that works only by accident and not something supported intentionally. And I don't think we should

2022-01-05 15:59 UTC, BafS commented
What about having multiple Route attributes? Currently this works for actions but not on the controller level (cf. my previous example).

2022-01-05 16:01 UTC, kylekatarnls commented
OK, got it. We took a wrong assertion seeing `$path` could take array and assuming it allowed to create aliases. Fine. Now that we agreed the blame is on me for doing this, it would be wonderful if you could advise some concrete better alternative so we could actually stop using it the wrong way and handle it cleanly. 🤩

Thanks 🙏

2022-01-05 16:04 UTC, stof commented
Multiple annotations at the method level work fine, because each one can define a route name for the route being defined.

Multiple class-level annotations defining different shared settings are an issue in that regard: each method level annotation (defining **one** name) will now need to actually register multiple routes (and so need multiple names).

2022-03-26 11:17 UTC, fabpot commented
Closing as we won't merge this anyway and @stof described the "better solution".

2022-03-26 11:17 UTC, closed without merging