[Validator] Error using CssColor with doctrine annotations
symfony/symfony pull request #44877
Opened 2021-12-31 13:25 UTC by sormes

| Q             | A
| ------------- | ---
| Branch?       | 5.4 
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | none
| License       | MIT

When use doctrine annotations and set formats parameter throw and error 

`array_merge(): Argument #2 must be of type array, null given`

`in vendor/symfony/validator/Constraints/CssColor.php (line 75) `

2021-12-31 13:53 UTC, fancyweb requested changes

2021-12-31 13:53 UTC, fancyweb commented on src/Symfony/Component/Validator/Constraints/CssColor.php
> +            $options = array_merge($formats, $options ?: []);
```suggestion
            $options = array_merge($formats, $options ?? []);
```

2021-12-31 14:24 UTC, fancyweb approved these changes

2021-12-31 21:04 UTC, welcoMattic approved these changes

2022-01-01 14:48 UTC, fabpot approved these changes

2022-01-01 14:48 UTC, fabpot commented
Thank you @sormes.

2022-01-01 14:49 UTC, merged