Free process resources
symfony/symfony pull request #44882
Opened 2021-12-31 23:26 UTC by jtojnar

| Q             | A
| ------------- | ---
| Branch?       | 5.3 
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | - 
| License       | MIT
| Doc PR        | - 

I am experiencing `Failed to open stream: Too many open files` error when running tests. Since `lsof` shows new `/dev/pts/1` being added every second, I tried closing the open processes and also https://github.com/squizlabs/PHP_CodeSniffer/pull/3523 but to no avail. But it is a good practice nonetheless.

2022-01-01 12:14 UTC, nicolas-grekas commented
You say that this doesn't fix anything for you, isn't it?
Closing resources explicitly is not needed so I'm not sure there's any reason to do this chance.

2022-01-01 12:18 UTC, jtojnar commented
Cannot say it does not fix anything but it is not sufficient to fix the issue I am experiencing.

2022-01-01 12:20 UTC, jtojnar commented
I am going by the [docs](https://www.php.net/manual/en/function.proc-open.php), which say “[return value] should be freed using proc_close() when you are finished with it”

2022-01-03 09:37 UTC, adrienfr commented
Hi,

Same here, since upgrading to SF 5.3.13, my PHPUnit test suite fails with :
```
PHPUnit 9.5.11 by Sebastian Bergmann and contributors.

Testing 
.............................................................   61 / 4733 (  1%)
.............................................................  122 / 4733 (  2%)
.............................................................  183 / 4733 (  3%)
.............................................................  244 / 4733 (  5%)
.............................................................  305 / 4733 (  6%)
.............................................................  366 / 4733 (  7%)
.............................................................  427 / 4733 (  9%)
.............................................................  488 / 4733 ( 10%)
.............................................................  549 / 4733 ( 11%)
.............................................................  610 / 4733 ( 12%)
.............................................................  671 / 4733 ( 14%)
.............................................................  732 / 4733 ( 15%)
................PHP Warning:  include(/var/www/project/symfony/vendor/phpunit/phpunit/src/Framework/Error/Warning.php): failed to open stream: Too many open files in /var/www/project/symfony/vendor/symfony/error-handler/DebugClassLoader.php on line 349
PHP Warning:  include(): Failed opening '/var/www/project/symfony/vendor/composer/../phpunit/phpunit/src/Framework/Error/Warning.php' for inclusion (include_path='.:/usr/share/php:/var/www/project/symfony/vendor/deployer/recipes') in /var/www/project/symfony/vendor/symfony/error-handler/DebugClassLoader.php on line 349
PHP Warning:  include(/var/www/project/symfony/vendor/phpunit/phpunit/src/Framework/Error/Warning.php): failed to open stream: Too many open files in /var/www/project/symfony/vendor/composer/ClassLoader.php on line 571
PHP Warning:  include(): Failed opening '/var/www/project/symfony/vendor/composer/../phpunit/phpunit/src/Framework/Error/Warning.php' for inclusion (include_path='.:/usr/share/php:/var/www/project/symfony/vendor/deployer/recipes') in /var/www/project/symfony/vendor/composer/ClassLoader.php on line 571
Class 'PHPUnit\Framework\Error\Warning' not found
```
I'll try to set up a reproducer

2022-01-03 09:46 UTC, jtojnar commented
@adrienfr do you know the previous version of dependencies? Also I am not completely sure Symfony is responsible, might also be PHPUnit or something else.

2022-01-03 10:34 UTC, adrienfr commented
> @adrienfr do you know the previous version of dependencies? Also I am not completely sure Symfony is responsible, might also be PHPUnit or something else.

I can confirm this is SF related, no more issues when downgrading to previous version :
```
Downgrading symfony/string (v5.3.13 => v5.3.10): Extracting archive
Downgrading symfony/console (v5.3.13 => v5.3.11): Extracting archive
Downgrading symfony/property-info (v5.3.13 => v5.3.8): Extracting archive
Downgrading symfony/property-access (v5.3.13 => v5.3.8): Extracting archive
Downgrading symfony/http-foundation (v5.3.13 => v5.3.11): Extracting archive
Downgrading symfony/dom-crawler (v5.3.13 => v5.3.7): Extracting archive
Downgrading symfony/config (v5.3.13 => v5.3.11): Extracting archive
Downgrading symfony/yaml (v5.3.13 => v5.3.11): Extracting archive
Downgrading symfony/translation (v5.3.13 => v5.3.11): Extracting archive
Downgrading symfony/dependency-injection (v5.3.13 => v5.3.11): Extracting archive
Downgrading symfony/process (v5.3.13 => v5.3.12): Extracting archive
Downgrading symfony/var-dumper (v5.3.13 => v5.3.11): Extracting archive
Downgrading symfony/error-handler (v5.3.13 => v5.3.11): Extracting archive
Downgrading symfony/http-kernel (v5.3.13 => v5.3.12): Extracting archive
Downgrading symfony/doctrine-bridge (v5.3.13 => v5.3.11): Extracting archive
Downgrading symfony/finder (v5.3.13 => v5.3.7): Extracting archive
Downgrading symfony/cache (v5.3.13 => v5.3.12): Extracting archive
Downgrading symfony/framework-bundle (v5.3.13 => v5.3.11): Extracting archive
Downgrading symfony/validator (v5.3.13 => v5.3.12): Extracting archive
Downgrading symfony/proxy-manager-bridge (v5.3.13 => v5.3.11): Extracting archive
Downgrading symfony/templating (v5.3.13 => v5.3.7): Extracting archive
Downgrading symfony/security-core (v5.3.13 => v5.3.11): Extracting archive
Downgrading symfony/security-http (v5.3.13 => v5.3.11): Extracting archive
Downgrading symfony/security-bundle (v5.3.13 => v5.3.12): Extracting archive
Downgrading symfony/form (v5.3.13 => v5.3.11): Extracting archive
Downgrading symfony/http-client (v5.3.13 => v5.3.11): Extracting archive
Downgrading symfony/intl (v5.3.13 => v5.3.11): Extracting archive
Downgrading symfony/twig-bridge (v5.3.13 => v5.3.11): Extracting archive
Downgrading symfony/debug-bundle (v5.3.13 => v5.3.4): Extracting archive
Downgrading symfony/dotenv (v5.3.13 => v5.3.10): Extracting archive
Downgrading symfony/mime (v5.3.13 => v5.3.11): Extracting archive
Downgrading symfony/mailer (v5.3.13 => v5.3.9): Extracting archive
Downgrading symfony/serializer (v5.3.13 => v5.3.12): Extracting archive
Downgrading symfony/web-profiler-bundle (v5.3.13 => v5.3.8): Extracting archive

=> OK (4733 tests, 31650 assertions)
```
Might not be able to provide a reproducer thus, got 4733 tests and it fails at 14-15%. Do you have any idea how to process?

Should I create a dedicated issue on GitHub with the error message `failed to open stream: Too many open files in /var/www/morningcroissant/symfony/vendor/symfony/error-handler/DebugClassLoader.php on line 349`? Might not be the only ones having this issue

2022-01-03 12:40 UTC, jtojnar commented
I would try installing the dependencies with `--prefer-source` and then bisecting individual dependencies – `console` and `process` are most likely suspects. (If you are unfamiliar, you can run `git bisect start v5.3.13 v5.3.12` in the `vendor/symfony/console` directory, then run the tests and based on success/failure use `git bisect good/bad` in the dependency. It should either find the commit that broke it or use `git bisect reset` and try another dependency.)

2022-01-03 18:08 UTC, adrienfr commented
> I would try installing the dependencies with `--prefer-source` and then bisecting individual dependencies – `console` and `process` are most likely suspects. (If you are unfamiliar, you can run `git bisect start v5.3.13 v5.3.11` in the `vendor/symfony/console` directory, then run the tests and based on success/failure use `git bisect good/bad` in the dependency directory. After few steps, it should either find the commit that might have broken it, or you can use `git bisect reset` and try another dependency.)

Thanks @jtojnar for your help! `symfony/console & symfony/process` are OK, the issue seems to come from `symfony/http-client`.
I try to find a specific commit but it seems related to this PR https://github.com/symfony/symfony/pull/44204/files, no more `failed to open stream: Too many open files` when reverting. cc @nicolas-grekas

2022-01-03 18:47 UTC, adrienfr commented
I created an issue (https://github.com/symfony/symfony/issues/44900) so other users can find it and for better tracking.

2022-01-04 08:47 UTC, nicolas-grekas requested changes
I'm :-1: here because this is not be needed: PHP closes resources automatically when they are destructed. Also because right now this is a guess that's would need a proof to turn into a merge.

#44900 looks like a better start to find the underlying issue. Does you issue happen when HttpClient is used? Is it fixed when you revert to an older version of it?

2022-01-04 19:46 UTC, jtojnar commented
> I'm -1 here because this is not needed: PHP closes resources automatically when they are destructed.

I have not seen any much documentation an PHP resource management other than [`proc_open` docs](https://www.php.net/manual/en/function.proc-open.php), which say that we should close the handles when we are done with them.

> does you issue happen when HttpClient is used

As mentioned in the other thread, I do not have HttpClient in my use case.

I did some [more digging](https://github.com/rectorphp/rector/issues/6904#issuecomment-1005103769) and it appears that `fopen('php://stdout')` is responsible. Will try closing more of those.

2022-01-04 20:08 UTC, jtojnar commented
I confirmed that the leak originates from this line:

https://github.com/symfony/symfony/blob/4b41d178e3c073e267f12d662d7f2536f0bf895a/src/Symfony/Component/Console/Output/ConsoleOutput.php#L152

We need to `fclose` this.

2022-01-17 17:27 UTC, jtojnar commented
It seems that the test suite that triggers my issue caches configuration object for each new test. Since each configuration creates a new `ConsoleOutput`, which creates a new file descriptor, this causes the leak. But even explicitly closing the descriptor would not help, since the configuration objects are not destroyed before the test suite finishes.

On Symfony site, this could be prevented by caching the file descriptor of `stdout` (e.g. inside static property of ConsoleOutput) to avoid creating unnecessary file descriptors but I am not sure if this is desirable.

2022-01-17 17:30 UTC, nicolas-grekas commented
Or by using the STDOUT const on the cil sapi I guess? Can you give it a try and see if that fixes your issue?

2022-01-18 09:15 UTC, nicolas-grekas commented
Closing in favor of #45053

2022-01-18 09:15 UTC, closed without merging