ticket_44872 fixed autoconfigured serializer handling non-array value…
symfony/symfony pull request #44881
Opened 2021-12-31 20:40 UTC by JustDylan23

…s incorrectly when trying to denormalize object attributes

| Q             | A
| ------------- | ---
| Branch?       | 6.1
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #44872
| License       | MIT
| Doc PR        | 

When using dependency injection to get the serializer (instead of manually instantiating it) the object normalizer that is injected into that serializer throws a value exception when doing denormalizing the following:

```php
class Outer {
  public Inner $inner;
}

class Inner {
  public $foo;
}

#[Route('/bug')]
public function test(DenormalizerInterface $denormalizer) {
    $blog = $denormalizer->denormalize([
        'inner' => 'test string',
    ], Outer ::class);
}```

This throws
```php
TypeError:
Symfony\Component\Serializer\Normalizer\AbstractNormalizer::prepareForDenormalization(): Argument #1 ($data) must be of type object|array|null, string given, called in /var/www/symfony/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php on line 368

  at vendor/symfony/serializer/Normalizer/AbstractNormalizer.php:299
  at Symfony\Component\Serializer\Normalizer\AbstractNormalizer->prepareForDenormalization('test string')
     (vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php:368)
  at Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer->denormalize('test string', 'App\\Entity\\User', null, array('cache_key' => 'c93a6d4efa206ea58a62cc6b7fab8dfb', 'deserialization_path' => 'author'))
     (vendor/symfony/serializer/Serializer.php:238)
  at Symfony\Component\Serializer\Serializer->denormalize('test string', 'App\\Entity\\User', null, array('cache_key' => 'c93a6d4efa206ea58a62cc6b7fab8dfb', 'deserialization_path' => 'author'))
     (vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php:559)
  at Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer->validateAndDenormalize(array(object(Type)), 'App\\Entity\\Blog', 'author', 'test string', null, array('cache_key' => '44db5a926a1544b1a8585af40107ca3a', 'deserialization_path' => 'author'))
     (vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php:401)
  at Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer->denormalize(array('author' => 'test string'), 'App\\Entity\\Blog', null, array('cache_key' => '44db5a926a1544b1a8585af40107ca3a'))
     (vendor/symfony/serializer/Serializer.php:238)
  at Symfony\Component\Serializer\Serializer->denormalize(array('author' => 'test string'), 'App\\Entity\\Blog')
     (src/Controller/BugReproductionController.php:18)
  at App\Controller\BugReproductionController->test(object(Serializer))
     (vendor/symfony/http-kernel/HttpKernel.php:152)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:74)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:202)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php:35)
  at Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run()
     (vendor/autoload_runtime.php:29)
  at require_once('/var/www/symfony/vendor/autoload_runtime.php')
     (public/index.php:5)
```

I deducted that it was an issue with the `Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer::validateAndDenormalize` function which didn't check the contents of the value before calling the object normalizer's denormalize method as long as the resolved `$builtinType` evaluated to an object. This caused a function in the denormalize function to be called. From here on out you can follow the stacktrace and see that it fails on the `AbstractNormalizer::prepareForDenormalization()` since the `$data` field is indeed not an object. 

Any suggestions on how I can unit test this are welcome. I think I would need to fetch the serializer instance from the container which I can't imagine how to do in a unit test. So I didn't have much luck.

2021-12-31 21:01 UTC, JustDylan23 commented
it appears that this PR needs some work and further debugging, strings apparently should be allowed since they can be converted to datetimes

2022-01-03 12:06 UTC, JustDylan23 commented
do we want to keep the same behavior as in 5 where an empty object is initialized and no error is thrown or do we want to introduce an exception like I proposed in #44872?

2022-01-03 12:15 UTC, fancyweb commented
Firstly, I would just fix it on 6.0 by changing the prepareForDenormalization() argument type to mixed.

2022-01-03 17:06 UTC, JustDylan23 commented
@dunglas can you review this?

2022-01-04 09:47 UTC, dbu commented
another way to run into this problem: when de-normalizing an xml response with only the root node and no attributes. the XmlEncoder::decode returns the $rootNode->nodeValue when there are neither children nor attributes.

2022-01-04 10:08 UTC, fancyweb requested changes

2022-01-04 10:08 UTC, fancyweb commented on src/Symfony/Component/Serializer/Tests/Normalizer/ObjectNormalizerTest.php
> +    public function testDenomalizeRecursiveWithObjectAttributeWithStringValue()
```suggestion
    public function testDenormalizeRecursiveWithObjectAttributeWithStringValue()
```

2022-01-04 10:08 UTC, fancyweb commented on src/Symfony/Component/Serializer/Tests/Normalizer/ObjectNormalizerTest.php
> +        $extractor = new PropertyInfoExtractor([], [new PhpDocExtractor(), new ReflectionExtractor()]);
```suggestion
        $extractor = new ReflectionExtractor();
```

2022-01-04 10:08 UTC, fancyweb commented on src/Symfony/Component/Serializer/Tests/Normalizer/ObjectNormalizerTest.php
> +        $serializer = new Serializer([new ArrayDenormalizer(), new DateTimeNormalizer(), $normalizer]);
```suggestion
        $serializer = new Serializer([$normalizer]);
```

2022-01-04 10:08 UTC, fancyweb commented on src/Symfony/Component/Serializer/Tests/Normalizer/ObjectNormalizerTest.php
> +        self::assertInstanceOf(ObjectInner::class, $obj->getInner());
```suggestion
        $this->assertInstanceOf(ObjectInner::class, $obj->getInner());
```

2022-01-04 10:11 UTC, fancyweb commented
Also I think it would be better if the test was in `AbstractObjectNormalizerTest` since what we test is `AbstractObjectNormalizer::denormalize`.

2022-01-04 10:15 UTC, fancyweb commented
Also please target 6.0 instead of 6.1, thanks.

2022-01-04 21:21 UTC, closed without merging

2022-01-04 21:27 UTC, JustDylan23 commented
messed up when changing the base branch, my thought process was
- get diff between 6.1 and my branch and create a patch
- delete branch
- push (I should not have done this)
- create branch
- get diff back
- push

2022-01-04 21:32 UTC, JustDylan23 commented
see https://github.com/symfony/symfony/pull/44908 for the new PR