[Notifier] Add Orange SMS bridge
symfony/symfony pull request #44913
Opened 2022-01-05 12:24 UTC by enigma972

| Q             | A
| ------------- | ---
| Branch?       | 6.1
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| License       | MIT

Add Orange SMS bridge

Previously [#44884](https://github.com/symfony/symfony/pull/44884)

2022-01-05 12:42 UTC, OskarStark commented on src/Symfony/Component/Notifier/Bridge/OrangeSms/OrangeSmsTransport.php
> +            'Authorization' => 'Basic '.base64_encode($credentials),
http client has `auth_basic` option, please use it, thanks

2022-01-05 14:37 UTC, GromNaN requested changes

2022-01-05 14:37 UTC, GromNaN commented on src/Symfony/Component/Notifier/Bridge/OrangeSms/OrangeSmsTransport.php
> +            throw new TransportException('Get Access Token Failled.', $response);
```suggestion
            throw new TransportException('Failed to get Orange access token.', $response);
```

2022-01-06 12:47 UTC, GromNaN approved these changes

2022-01-06 14:48 UTC, OskarStark approved these changes

2022-01-09 11:12 UTC, fabpot requested changes

2022-01-09 11:12 UTC, fabpot commented on src/Symfony/Component/Notifier/Bridge/OrangeSms/CHANGELOG.md
> +-----
```suggestion
---
```

2022-01-09 11:12 UTC, fabpot commented on src/Symfony/Component/Notifier/Bridge/OrangeSms/OrangeSmsTransportFactory.php
> +        return ['orangesms'];
Maybe?

```suggestion
        return ['orange-sms'];
```

2022-01-11 12:48 UTC, OskarStark approved these changes

2022-01-11 12:49 UTC, OskarStark commented
Please create a PR on the symfony/symfony-docs repo and symfony/recipes-contrib, thanks!

2022-01-16 14:09 UTC, 94noni commented on src/Symfony/Component/Notifier/Bridge/OrangeSms/OrangeSmsTransport.php
> +        if (201 != $response->getStatusCode()) {
Strict comparison would be better :)

2022-01-16 14:10 UTC, 94noni commented on src/Symfony/Component/Notifier/Bridge/OrangeSms/OrangeSmsTransport.php
> +        $args = [
I would call it payload instead of args, wdyt?

2022-01-16 14:11 UTC, 94noni commented on src/Symfony/Component/Notifier/Bridge/OrangeSms/OrangeSmsTransport.php
> +    public function getAccessToken(): string
Are you sure of the public visibility? Seems private

2022-01-16 14:13 UTC, 94noni commented on src/Symfony/Component/Notifier/Bridge/OrangeSms/composer.json
> +        "symfony/uid": "^5.4|^6.0"
Seems not needed, isnt it?

2022-01-16 23:18 UTC, enigma972 commented on src/Symfony/Component/Notifier/Bridge/OrangeSms/composer.json
> +        "symfony/uid": "^5.4|^6.0"
I think so

2022-01-17 14:24 UTC, fabpot approved these changes

2022-01-17 14:26 UTC, fabpot commented
Thank you @enigma972.

2022-01-17 14:26 UTC, merged

2022-01-17 14:44 UTC, nicolas-grekas commented
This could be a great fit for the backing program!
Does anyone know someone at Orange that we could reach for that purpose?
DM me on Slack/Twitter if you do! :pray: