[Serializer] Improve collecting errors on denormalization and promoted property constructors
symfony/symfony pull request #45112
Opened 2022-01-22 00:13 UTC by barell

| Q             | A
| ------------- | ---
| Branch?       | 5.4 
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #44772 
| License       | MIT

There are few improvements/fixes:

1. It will show all missing properties based on the constructor parameters (previously it was only first one)
2. There will be proper path and expected type (with support for union types) instead of unknown expected type and null path
3. It won't throw TypeError anymore on incompatible constructor types and will continue to collect all errors

2022-01-22 00:14 UTC, barell commented
After some crazy rollercoaster with git branches I think I managed to make it right this time.

2022-01-27 15:38 UTC, barell commented
This PR is based on https://github.com/symfony/symfony/pull/44782 which I messed up a bit. 

I fixed all checks but not sure why psalm is broken. Any feedback will be appreciated!

2022-01-28 15:51 UTC, barell commented
@dunglas @nicolas-grekas any feedback on this PR will be appreciated. These fixes would really help simplify a lot of things where we use Symfony Serializer :pray:

2022-10-05 07:52 UTC, mtarld requested changes
Hi @barell !
Thank you for that PR :slightly_smiling_face: 
Could you target the 6.2 branch instead?

2022-10-05 07:52 UTC, mtarld commented on src/Symfony/Component/Serializer/Normalizer/AbstractNormalizer.php
> +                        if (\PHP_VERSION_ID >= 80000) {
This can be removed as Symfony will now require at least PHP8.1

2022-10-05 07:52 UTC, mtarld commented on src/Symfony/Component/Serializer/Tests/SerializerTest.php
> +    /** @requires PHP 8.0 */
You can remove it as well (same for others)

2022-10-05 07:52 UTC, mtarld commented on src/Symfony/Component/Serializer/Tests/SerializerTest.php
> +    public function testCollectDenormalizationErrorsWithConstructorPartiallyMissingParameters()
That test and the previous one (`testCollectDenormalizationErrorsWithConstructorMissingParameters`) are kind of testing the same stuff, WDYT?

2022-10-05 07:52 UTC, mtarld commented on src/Symfony/Component/Serializer/Normalizer/AbstractNormalizer.php
> +                            }
In PHP8.1, there is a new "intersection" type. And the `ReflectionIntersectionType` do not have any `getName` method.
Therefore IMHO, the easiest way to go is to rely on the fact that the `ReflectionPropertyType` is stringable.

So we can do something like that:
```php
if ($constructorParameter->getType() instanceof \ReflectionUnionType) {
    $expectedTypes = array_map(function (\ReflectionType $t): string { return (string) $t; }, $constructorParameter->getType()->getTypes());
} else {
    $expectedTypes = [(string) $constructorParameter->getType()];
}
```
It'll handle every kind of `ReflectionPropertyType` and only split the expected type array whenever it's an union type.

2023-04-18 13:34 UTC, nicolas-grekas commented
I'm closing because this stalled. Also because closing my encourage taking over? @mtarld maybe? :)

2023-04-18 13:34 UTC, closed without merging