ADD placeholder as option in all TextType(TextareaType, EmailType,...)
symfony/symfony pull request #45246
Opened 2022-01-30 18:37 UTC by johdcode

| Q             | A
| ------------- | ---
| Branch?       | 6.1 for features / 4.4, 5.4 or 6.0 for bug fixes 
| Bug fix?      | yes/no
| New feature?  | yes/no 
| Deprecations? | yes/no 
| Tickets       | Fix #... 
| License       | MIT
| Doc PR        | symfony/symfony-docs#...

2022-02-01 13:56 UTC, johdcode commented
Tests added !

2022-02-01 14:38 UTC, johdcode commented
Should i create a new PR for a better history ?

2022-02-01 16:08 UTC, alexislefebvre commented
> Should i create a new PR for a better history ?

There's no need to alter the commits, they will be squashed when the PR will be merged.

2022-02-06 16:29 UTC, GromNaN requested changes
Thanks for working on this useful feature. I have some observations: the tests should be reworked.

2022-02-06 16:29 UTC, GromNaN commented on src/Symfony/Component/Form/Extension/Core/Type/TextType.php
> +            'placeholder' => '',
You can restrict type with `$resolver->setAllowedTypes('placeholder', 'string');`

2022-02-06 16:29 UTC, GromNaN commented on src/Symfony/Component/Form/Extension/Core/Type/TextType.php
> +        if (isset($options['placeholder']) && '' != $options['placeholder']) {
Strict comparison is more safe.

```suggestion
        if (isset($options['placeholder']) && '' !== $options['placeholder']) {
```

2022-02-06 16:29 UTC, GromNaN commented on src/Symfony/Component/Form/Test/TypeTestCase.php
> +    public const PLACEHOLDER_OPTION_TEXT = 'My placeholder...';
It's used only inside this class. Should be `private`.

2022-02-06 16:29 UTC, GromNaN commented on src/Symfony/Component/Form/Test/TypeTestCase.php
> +    public function testTextTypePlaceholderOption()
The class `TypeTestCase` is extended by several test classes; consequently test methods are run for each child class. That's waste of machine time.

The assertion for each form type should be in the related test class (`TypeTestCase::testTextTypePlaceholderOption` become `TextTypeTest::testPlaceholderOption`)

2022-02-06 18:24 UTC, johdcode commented
With pleasure, I tried to find one useful but accessible for my first PR, and thanks for your really clear explains I work it

2022-02-07 16:01 UTC, johdcode commented
@GromNaN should you have any other suggestions for me ?

2022-04-12 12:26 UTC, stof commented
Closing this PR for the reason given by @xabbuh on the issue: https://github.com/symfony/symfony/issues/45214#issuecomment-1096650865

2022-04-12 12:26 UTC, closed without merging