Form with ChoiceType and option "expanded" return integer keys
symfony/symfony pull request #45335
Opened 2022-02-07 10:28 UTC by willemverspyck

…n no string

| Q             | A
| ------------- | ---
| Branch?       | 6.0
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | yes
| Tickets       | Fix #44792
| License       | MIT

When creating a form with ChoiceType and the option "expanded" is set as true, the choices are changed into "checkbox" fields. But the keys of those fields are integers (0 for the first checkbox, 1 for the second checkbox). If you want to "get" one of those fields with FormBuilderInterface->get(string $name) that impossible with "declare(strict_types=1);" as the $name can only be string. In Symfony 5.4 it worked.

I converted the index to string and throw a deprecation if the callback doesn't return string. I'm not sure if the deprecation is the right solution?

If that the right solution, I still have to add tests for this, but that's difficult as the test don't have the "declare(strict_types=1);".

2022-02-07 10:36 UTC, willemverspyck commented
Maybe @nicolas-grekas / @vudaltsov can check my solution as they added / authored the type declarations in  https://github.com/symfony/form/commit/c46149559a1d9d7551a44975276e082fa4be598b#diff-d12252079a069f0ec8e4c6929ca9489ca26f2898d6c0b0e96a47dafe846ed56a. I just want to know if this is the right solution (including the deprecation) and then I will add tests and fix checks.

2022-02-08 10:24 UTC, nicolas-grekas commented
The patch doesn't make sense to me sorry. Can you please add a failing test case, as that may help understand the issue?

2022-02-09 00:11 UTC, derrabus requested changes

2022-02-09 00:11 UTC, derrabus commented on src/Symfony/Component/Form/Tests/Extension/Core/Type/ChoiceTypeTest.php
> +declare(strict_types=1);
We don't use strict types in this repository.

2022-02-09 00:11 UTC, derrabus commented on src/Symfony/Component/Form/ChoiceList/Factory/DefaultChoiceListFactory.php
> +                trigger_deprecation('symfony/form', '6.0.0', 'The "choice_name" callback returns "%s", return "string" instead.', \gettype($nextIndex));
Since you're targeting the 6.0 branch: We don't add deprecations in a bugfix release.

2022-03-21 12:49 UTC, xabbuh commented
closing here as the PR seems to be stalled

2022-03-21 12:50 UTC, closed without merging