Fix embed logic for background attributes
symfony/symfony pull request #45376
Opened 2022-02-09 13:25 UTC by flack

| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #42921
| License       | MIT
| Doc PR        | 

As suggested by @fabpot here https://github.com/symfony/symfony/pull/43255#issuecomment-1030025526, this is the most minimal fix for the linked issue. I guess the same problem can happen if you use e.g.

```html
<div style="background-image:url(test.gif)"></div>
```

I have changed it so that there is now an array of regexes to look for embedded images, so at least code for the `background-image` case (or others that might be found later on) can easily be added.

2022-02-09 13:28 UTC, fabpot requested changes

2022-02-09 13:28 UTC, fabpot commented on src/Symfony/Component/Mime/Tests/EmailTest.php
> +        $this->assertStringMatchesFormat('<div background=3D"cid:%s@symfony"></div>', $parts[0]->bodyToString());
Same here

2022-02-09 13:28 UTC, fabpot commented on src/Symfony/Component/Mime/Tests/EmailTest.php
> +        $content = '<div background="cid:test.gif"></div>';
Can you add new tests instead of modifying existing ones?

2022-02-09 13:29 UTC, flack commented
There's a coding style violation that wants me to add a trailing comma in the regex array. AFAIK that is only supported on PHP 7.3+, so it'll probably cause CI to fail. Should I still do it?

2022-02-09 13:30 UTC, flack commented
also, what is your policy with implementing review comments, should I make new commits or squash immediately?

2022-02-09 13:41 UTC, flack commented
implemented review comments (except for the trailing comma one, see above)

2022-02-09 14:03 UTC, derrabus commented
> There's a coding style violation that wants me to add a trailing comma in the regex array. AFAIK that is only supported on PHP 7.3+, so it'll probably cause CI to fail. Should I still do it?

Trailing commas in array constructors are allowed in PHP 7.1 already, no worries.

2022-02-09 14:04 UTC, derrabus commented
> also, what is your policy with implementing review comments, should I make new commits or squash immediately?

As you wish, we can squash while merging.

2022-02-09 14:12 UTC, flack commented
alright, thx. All suggestions should be implemented now

2022-02-10 13:57 UTC, fabpot approved these changes

2022-02-10 13:58 UTC, fabpot commented
I'm merging it in 6.1 as this is a new feature (this was not supported before).

2022-02-10 14:01 UTC, flack commented
well, it worked with Swiftmailer, so from the point of view of the user it's still a regression

2022-02-10 14:02 UTC, fabpot commented
Thank you @flack.

2022-02-10 14:02 UTC, merged

2022-02-10 14:03 UTC, fabpot commented
We've been more and more strict about what we consider a bug. Stability is the most important thing for already released versions.

2022-02-10 14:05 UTC, flack commented
Yeah, makes sense I guess. Unfortunately, for me it means I have to continue using the abandoned Switfmailer package (with composer shouting at me every time I update something) until I can migrate to php 8+ and sf 6

2022-05-19 09:58 UTC, veto221 commented
Hi. 
Can we merge this for LTS version too?