[Messenger] Add HandlerArgumentsStamp
symfony/symfony pull request #45418
Opened 2022-02-14 08:28 UTC by enumag

| Q             | A
| ------------- | ---
| Branch?       | 6.1
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #31075
| License       | MIT
| Doc PR        | will add later if this feature is wanted

As discussed in #31075 sometimes it's desirable for the messenger handler to receive additional argument than just the message itself. I understand the voiced concerns about passing the entire envelope but instead of that we could use the approach from this PR which doesn't add any additional arguments by default but is actually even more powerful since it gives the user full control what should be sent to the handler if desired.

This is just a prototype of course. With https://github.com/symfony/symfony/pull/45377 I used a readonly property from PHP 8.1 but of course such details can be easily adjusted.

Let me know if such feature is wanted in Symfony. If yes then I'll add tests and a doc PR.

2022-03-03 09:43 UTC, enumag commented
Can I get some feedback on this feature?

2022-08-05 14:11 UTC, fabpot requested changes
LGTM

2022-08-05 14:11 UTC, fabpot commented on src/Symfony/Component/Messenger/Stamp/HandlerArgumentsStamp.php
> +<?php declare(strict_types = 1);
`declare` should be removed (as we are using that in Symfony).

2022-08-05 14:11 UTC, fabpot commented on src/Symfony/Component/Messenger/Middleware/HandleMessageMiddleware.php
> +    ): mixed {
Should be on one line.

2022-08-08 07:33 UTC, enumag commented
@fabpot Thanks for the review. I changed the code according to your comments and added a test.

The CI failure seems unrelated.

Status: Needs review

2022-08-14 13:48 UTC, fabpot approved these changes
Just a small code change to make it more consistent with the rest of Symfony.

2022-08-14 13:48 UTC, fabpot commented on src/Symfony/Component/Messenger/Stamp/HandlerArgumentsStamp.php
> +        public readonly array $additionalArguments,
As we are not using public properties in Symfony yet, I think we should make it private and create a proper getter (for consistency with the rest of the code base).

2022-08-14 18:20 UTC, enumag commented
@fabpot Updated. Is it okay to keep the promoted property or should I use the non-promoted syntax?

2022-08-14 18:32 UTC, enumag commented
Tests are failing but once again I don't think it's related to my code.

2022-08-14 19:17 UTC, fabpot commented
Thank you @enumag.

2022-08-14 19:18 UTC, merged

2024-04-30 11:45 UTC, melkamar commented
What is the reasoning behind making the stamp implement a `NonSendableStampInterface`? I needed to customize the arguments for a handler reading this from the transport and it seems like I cannot. Is there a technical reason why not?