Only manipulate headers if not already sent
symfony/symfony pull request #45434
Opened 2022-02-16 06:16 UTC by BlackbitNeueMedien

| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no
| License       | MIT

When you want to send headers before request finishes via
```php
class MyController  {
  public function myAction() {
      $response = new Response();
      $response->headers->set(
          'Content-Disposition',
          HeaderUtils::makeDisposition(
              HeaderUtils::DISPOSITION_ATTACHMENT,
              'file.txt
          )
      );
      
      $response->sendHeaders();
      ob_flush();
      flush();

      // do some work to populate response
      sleep(5); // this is only for demonstraton purposes

      return $response;
  }
}
```
I get a warning error 
> E_WARNING: Cannot modify header information - headers already sent in [Root folder]/vendor/symfony/http-foundation/Session/SessionUtils.php, line 54

The goal of above code is to trigger the download dialog to open before the actual data generation is finished.

With this PR the headers get only manipulated during `kernel.response` event if the headers have ot already been sent.

2022-02-16 07:11 UTC, GromNaN approved these changes
Good catch. This is checked in other places where headers are set.

Should merged to 4.4?

2022-02-17 06:25 UTC, BlackbitNeueMedien commented
Rebased to 4.4

2022-02-17 09:31 UTC, fancyweb reviewed
I don't think this method is useful at all if the headers have already been sent, maybe a guard clause at the beginning would be better?

2022-02-17 15:54 UTC, BlackbitNeueMedien commented
Ok, changed to guard condition.

2022-02-17 15:56 UTC, fancyweb commented
Thanks @BlackbitNeueMedien. It was a suggestion. Let's see what @GromNaN and other reviewers think about it :man_shrugging:

2022-02-18 09:34 UTC, nicolas-grekas requested changes
I don't think the code example in the controller is legit. Controllers should never "echo".
Instead of a Response, this should use a StreamedResponse

:-1: on my side.

2022-02-18 09:42 UTC, BlackbitNeueMedien commented
@nicolas-grekas I actually also tried with `StreamedResponse` but the browser always showed the download dialog yet when the response generation was finished.

Perhaps I did not put the `flush()` in the callback. Will try again this way:
```php
$response = new StreamedResponse();
$response->headers->set(
          'Content-Disposition',
          HeaderUtils::makeDisposition(
              HeaderUtils::DISPOSITION_ATTACHMENT,
              'file.txt'
          )
      );
$response->setCallback(function () {
    flush(); // in this moment Response::sendHeaders() should have already been called by Response::send()
    
    sleep(5);
    echo 'My response';
});
```

2022-02-18 16:01 UTC, nicolas-grekas commented
I gave it a try and I confirm StreamedResponse is the way to go.

2022-02-18 16:01 UTC, closed without merging