Fix table header seperator wrapping
symfony/symfony pull request #45565
Opened 2022-02-26 13:34 UTC by alamirault

| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #45520
| License       | MIT
| Doc PR        | 

Before PR, a new seperator is added foreach split line in header

```php
        $table = new Table();
        $table
            ->setHeaders([
                [
                    'Publication',
                    'Very long header with a lot of information',
                ],
            ])
            ->setRows([
                [
                    '1954',
                    'The Lord of the Rings, by J.R.R. Tolkien',
                ],
            ])
            ->setColumnMaxWidth(1, 30);
```
Before PR:

![image](https://user-images.githubusercontent.com/9253091/155845175-94482e50-8507-4762-9da1-dbc88967bd47.png)

After PR
![image](https://user-images.githubusercontent.com/9253091/155845154-3182ec3a-eaa8-423f-a1bc-8744c2a95a88.png)

2022-04-05 22:29 UTC, alamirault commented
Any feedback on this PR will be appreciated. Thanks

2022-04-07 23:28 UTC, chalasr requested changes
Looks good to me, just some minor comments.
I think the bug exists on 4.4 as well, can you confirm and rebase if it's the case?

2022-04-07 23:28 UTC, chalasr commented on src/Symfony/Component/Console/Helper/Table.php
> +                ];
as per our coding standards
```suggestion
        $rowGroup = [$row instanceof TableSeparator ? $row : $this->fillCells($row)];
```

2022-04-07 23:28 UTC, chalasr commented on src/Symfony/Component/Console/Helper/Table.php
> +            if (null !== $cell && !$cell instanceof TableCell && !\is_scalar($cell) && !(\is_object($cell) && method_exists($cell, '__toString'))) {
this change should be reverted as (it's useful for some functions only, `is_scalar` is not in the list).

2022-04-09 17:38 UTC, fabpot approved these changes

2022-04-09 17:39 UTC, fabpot commented
Thank you @alamirault.

2022-04-09 17:39 UTC, merged