Updating twig required version (fixing vulnerability) 4.4
symfony/symfony pull request #45773
Opened 2022-03-17 18:28 UTC by ferjep

| Q             | A
| ------------- | ---
| Branch?       | 6.1 for features / 4.4, 5.4 or 6.0 for bug fixes 
| Bug fix?      | yes
| New feature?  | yes
| Deprecations? | yes
| Tickets       | null
| License       | MIT
| Doc PR        | null

https://symfony.com/blog/twig-security-release-disallow-non-closures-in-the-sort-filter

2022-03-17 19:25 UTC, GromNaN requested changes
Can you update the constraint in other places where `twig/twig` is required.

- composer.json
- src/Symfony/Bridge/Twig/composer.json
- src/Symfony/Bundle/FrameworkBundle/composer.json
- src/Symfony/Bundle/SecurityBundle/composer.json
- src/Symfony/Component/HttpKernel/composer.json
- src/Symfony/Component/VarDumper/composer.json

2022-03-17 19:25 UTC, GromNaN commented on src/Symfony/Bundle/TwigBundle/composer.json
> +        "twig/twig": "^1.43|^2.14|^3.3.8"
Should include the bugfix version.
```suggestion
        "twig/twig": "^1.43|^2.14.11|^3.3.8"
```

2022-03-18 00:28 UTC, ferjep commented on src/Symfony/Bundle/TwigBundle/composer.json
> +        "twig/twig": "^1.43|^2.14|^3.3.8"
Done, changed in

- composer.json
- src/Symfony/Bridge/Twig/composer.json
- src/Symfony/Bundle/FrameworkBundle/composer.json
- src/Symfony/Bundle/SecurityBundle/composer.json
- src/Symfony/Bundle/TwigBundle/composer.json
- src/Symfony/Bundle/WebProfilerBundle/composer.json
- src/Symfony/Component/HttpKernel/composer.json
- src/Symfony/Component/VarDumper/composer.json

2022-03-18 08:20 UTC, GromNaN approved these changes

2022-03-18 08:28 UTC, nicolas-grekas commented
:-1:, it's not our responsibility to bump deps, even for security issues.

2022-03-18 08:41 UTC, fabpot commented
I agree, also because Composer will always install the maximum possible version allowed by the constraint when creating a new project (or when updating dependencies).

2022-03-18 08:41 UTC, closed without merging