[Console] Fix exit status on uncaught exception with negative code
symfony/symfony pull request #45851
Opened 2022-03-26 01:02 UTC by acoulton

| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #45850
| License       | MIT
| Doc PR        | N/A

As described in #45850, if an application threw an exception with the `code` property set to a negative number this could in some cases cause the process to appear to exit 'successfully' with a zero exit status. Exiting with any negative number produces potentially unexpected results - the reported exit status will not appear to match the value that was set. This is due to the binary handling / truncation of exit codes.

**This PR may theoretically break BC for applications that were intentionally throwing exceptions with negative codes and
performing some action based on that status.** However, given they would have had to implement an algorithm to map e.g. `-10` in PHP to `246` as the actual exit status, it seems unlikely this is a common usage.

IMO therefore applications using negative statuses are relying on an undocumented / incorrect implementation, and this is not a formal BC break.

I believe it is essentially safe to assume that exceptions with negative codes are e.g. being thrown by lower-level components, and are not intended to set a shell exit status.

Coalescing all negative numbers to 1 matches the existing behaviour with other 'invalid' exception codes e.g. empty / zero / non-numeric.

This therefore feels the most robust fix and eliminates any potential for confusion.

2022-03-26 01:15 UTC, acoulton commented
It looks like appveyor failed on a network issue - I'm not sure how to make that retry - and the coding standards report is for existing content in the testcase that is not modified here.

2022-03-26 07:24 UTC, fabpot requested changes
Small CS issue but it looks good to me.

2022-03-26 07:24 UTC, fabpot commented on src/Symfony/Component/Console/Tests/ApplicationTest.php
> +    public function testRunReturnsExitCodeOneForNegativeExceptionCode($exception_code)
```suggestion
    public function testRunReturnsExitCodeOneForNegativeExceptionCode($exceptionCode)
```

2022-03-26 07:26 UTC, fabpot commented
As there is a potential behavior change (even if theoretical only), I would do the change on 6.1 instead and add a note in the CHANGELOG file to document the change.

2022-03-26 08:33 UTC, acoulton commented
@fabpot the only issue with targeting 6.1 is we're currently still tied to 4.4 due to third-party dependencies.

As it stands our CI occasionally false-positives when in fact the process has crashed. We've now had two branches (that we know of) where code has been merged with failing tests that have not shown up till a later run. And more times it has occurred during work on a branch. Essentially we can't trust our green tick now, and have to check the output of every build. There may well be other users who have cron/CI/etc processes that are failing undetected. 

That feels like quite a significant bug. It is definitely higher impact than the possibility someone starts to see failures due to an unexpected but still nonzero exit code.

So it should really be fixed in the first supported version IMO.

If you're not happy to change all negative values in 4.4 then I think at least we should change anything `< -255`. Values lower than that are very clearly not valid exit codes, so changing them seems reasonable even in the older versions.

Then I could do a separate PR for 6.1 to apply this broader change to get rid of all negative values, which I think is best long-term.

What do you think?

2022-03-26 08:36 UTC, acoulton commented
PS thank you for the quick weekend review!

2022-03-26 10:59 UTC, fabpot commented
As you said, someone might rely on the current behavior. From my past experience, whenever we said that it was ok to merge something because there is 0 chance someone would have used the bad behavior, we had to revert because someone somewhere did rely on the behavior.

So, we have decided quite a while ago to not play this game anymore and always only merge bug fixes.

I know that this is frustrating, but we want to be on the safe side and try to minimize BC breaks as much as possible.

I hope you will understand our position.

2022-03-26 11:16 UTC, acoulton commented
@fabpot ok fair enough for the general negative number case.

But surely nobody can be relying on `throw new Exception ('not really', -256)` (or -512 etc), allowing that to bubble out of their app and expecting that to terminate the app with an exit code of zero?

That is 100% a bug IMO - and a nasty one - and I can't see any valid reason not to fix it.

If you wanted to limit the behaviour change to the bare minimum then I suppose the fix could only change the specific -256,-512,... values that result in a zero. But that is very inconsistent with how you handle positive numbers >= 256.

2022-03-26 11:19 UTC, fabpot commented
I must admit that you have a point here :)

Can you fix the CS issue so that I can merge it in 4.4.

2022-03-26 14:25 UTC, acoulton commented
@fabpot thanks very much. Of course, I'll sort that when I'm back at my machine later on.

2022-03-26 20:24 UTC, kaznovac commented
Negative error codes have unspecified (implementation/environment specific - in most cases it's modulo 256) behavior, only codes 0-255 are defined.

https://tldp.org/LDP/abs/html/exitcodes.html

So this is rather a bug fix rather than a BC.

2022-03-26 22:35 UTC, acoulton commented
@fabpot thanks for spotting the CS issue I've corrected that now.

2022-03-27 07:45 UTC, fabpot approved these changes

2022-03-27 07:46 UTC, fabpot commented
Thank you @acoulton.

2022-03-27 07:46 UTC, merged

2022-03-28 10:52 UTC, acoulton commented
Thanks very much @fabpot