[Security] Don't allow empty username or empty password
symfony/symfony pull request #46118
Opened 2022-04-20 04:24 UTC by bikalbasnet

| Q             | A
| ------------- | ---
| Branch?       | 6.1
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       |  #46100 
| License       | MIT
| Doc PR        | -

Reopened from https://github.com/symfony/symfony/pull/46109 into `6.1` branch as this is not a bug rather a security feature

2022-04-20 23:14 UTC, chalasr commented
This is a BC break, which Symfony doesn't allow in minor versions. We need to deprecate passing empty strings at first, then convert the deprecation to an error in the next major version.

2022-04-24 06:39 UTC, bikalbasnet commented
@chalasr Do I need to create a new `UPGRADE-6.2.md` myself right or have to wait until `6.2` branch is created?

2022-04-25 08:59 UTC, wouterj commented
We'll create the 6.2 after the stabilization period, you can then rebase this PR on the new 6.1 branch. I guess you can create a new `UPGRADE-6.2.md` file.

2022-04-25 09:39 UTC, chalasr requested changes

2022-04-25 09:39 UTC, chalasr commented on src/Symfony/Component/Security/Http/Authenticator/JsonLoginAuthenticator.php
> +            );
should be on 1 line

2022-04-25 09:39 UTC, chalasr commented on src/Symfony/Component/Security/Http/Authenticator/JsonLoginAuthenticator.php
> +        if ("" === $credentials['username'] || "" === $credentials['password']) {
```suggestion
        if ('' === $credentials['username'] || '' === $credentials['password']) {
```

2022-04-25 09:39 UTC, chalasr commented on src/Symfony/Component/Security/Http/Authenticator/JsonLoginAuthenticator.php
> +        if ("" === $credentials['username'] || "" === $credentials['password']) {
single quotes everywhere please

2022-04-25 09:39 UTC, chalasr commented on src/Symfony/Component/Security/Http/Authenticator/JsonLoginAuthenticator.php
> +                "Passing empty string for username or password is deprecated and will be removed in 7.0"
```suggestion
                'Passing an empty string as username or password parameter is deprecated.'
```

2022-04-25 09:39 UTC, chalasr commented on src/Symfony/Component/Security/Http/CHANGELOG.md
> +* Deprecate empty username or password when using when using `JsonLoginAuthenticator`
only empty strings are deprecated (e.g. `"0"` is still valid)

2022-07-20 16:36 UTC, fabpot approved these changes

2022-07-20 16:39 UTC, fabpot commented
Thank you @bikalbasnet.

2022-07-20 16:39 UTC, merged

2023-03-05 16:52 UTC, adrianrudnik commented
Just came across this in some application tests. Right now I get the 401 HTTP status code and the user deprecation. What is the upcoming target? From the other closed commits I assume 400 HTTP status code instead?

The naming `Passing empty username or password parameter when using `JsonLoginAuthenticator` is not supported anymore` is somewhat strange, as JSON clients still could send empty usernames and passwords or is there a change in this mechanic planned?

2023-03-05 17:11 UTC, chalasr commented
@adrianrudnik I'm not sure to truly understand what is the question here. 
Anyway if you think there's something wrong or inconsistent, please consider opening a separate issue with enough details to reproduce.