[Translator] Fix translator overlapse
symfony/symfony pull request #46190
Opened 2022-04-27 12:56 UTC by xavren

| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #46189 
| License       | MIT
| Doc PR        | symfony/symfony-docs#...

2022-04-27 13:09 UTC, stof commented on src/Symfony/Component/Translation/Tests/TranslatorTest.php
> +     * @requires extension intl
This test does not require the intl extension. The test will also work when using `symfony/polyfill-intl-icu` (and the testsuite always has it available)

2022-04-27 15:30 UTC, xavren commented on src/Symfony/Component/Translation/Tests/TranslatorTest.php
> +     * @requires extension intl
Ok thanks i removed it :)

2022-05-14 11:18 UTC, nicolas-grekas requested changes
I'm sorry but this does not make sense to me as MessageCatalog::get() starts with:
```php
        if (isset($this->messages[$domain.self::INTL_DOMAIN_SUFFIX][$id])) {
            return $this->messages[$domain.self::INTL_DOMAIN_SUFFIX][$id];
        }
```

To confirm, I checked out the PR and reverted the patch: tests still pass.
Can you figure out a tests that fails without the patch?

2022-06-19 11:51 UTC, nicolas-grekas commented
@xavren still up to finish this one? Can you figure out a failing test case?

2022-06-20 15:01 UTC, xavren commented
@nicolas-grekas sorry for the delay, we had some new priorities and forgot to follow this issue.

You are right, this is not the issue, but the bug exists as demonstrated by this https://github.com/xavren/symfony-translator-bug/blob/master/src/Command/TestCommand.php

Code 
```php
$output->writeln($this->translator->trans('test', ['name' => 'World']));
$output->writeln($this->translator->trans('test', ['name' => 'World'], 'messages+intl-icu'));
$output->writeln($this->translator->trans('test', ['name' => 'World'], 'messages'));
```

Result is
```bash
php bin/console app:test
Hello %name%
Hello %World%
Hello %name%
```

It seems that MessageCatalogue loading messages has an issue but cannot spot it and did not find any tests :/

For the debug, here is the cache file

var/cache/dev/translations/catalogue.en.bBuRKVV.php
```php
<?php

use Symfony\Component\Translation\MessageCatalogue;

$catalogue = new MessageCatalogue('en', array (
  'messages+intl-icu' => 
  array (
    'test' => 'Hello %name%',
  ),
));


return $catalogue;
```

2022-06-20 15:12 UTC, stof commented
Well, using `%name%` in a catalogue that has the intl suffix is not replaced at all and this is expected, as this is not a placeholder at all in the ICU message format.

2022-06-20 15:22 UTC, xavren commented
Completly ok with that, but you can see the content of my translations files 
![image](https://user-images.githubusercontent.com/2655636/174634088-c1fb79ac-6ff6-45e6-ae0c-a29c6ff2190b.png)

Result is completly mixed up

2022-06-20 15:41 UTC, stof commented
@xavren The legacy format replaces whatever you pass as key. so to replace `%name%`, you need to pass `%name%` as key, not `name` (as part if the Intl ICU message format migration, `%` are trimmed from the placeholder name, but they are not _added_ automatically)

2022-06-20 17:51 UTC, xavren commented
@stof, the idea was to show mixup catalogue data, we have legacy data in intl-icu domain, that override intl-icu data, formatted by intlFormatter. 
If you tell me this is what's expected, i'll close this issue

2022-06-21 09:24 UTC, stof commented
you should not have legacy data in your intl-icu catalogue. That should go in the non-suffixed catalogue for that domain. Putting legacy data in the catalogue that is meant to contain ICU format will indeed not work, and that's totally expected.

2022-06-21 09:27 UTC, xavren commented
Hi @stof and @nicolas-grekas, i modified my PR adding tests  that demonstrate the issue (hopefully)

public function testIntlDomainOverlapseWithIntlResourceBefore() does not pass, because MessageCatalogue is mixing up legacy / intl domains

2022-08-02 12:53 UTC, nicolas-grekas approved these changes
This issue was likely introduced in #35430
I fixed it, all green. Thanks for the test case.

2022-08-02 12:54 UTC, nicolas-grekas commented
Thank you @xavren.

2022-08-02 12:54 UTC, merged