[Mailer] Add Infobip bridge
symfony/symfony pull request #46211
Opened 2022-04-29 06:43 UTC by B-Galati

| Q             | A
| ------------- | ---
| Branch?       | 6.2
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| License       | MIT
| Doc PR        | symfony/symfony-docs#16760

Hello,

Add Infobip as new email provider for Symfony Mailer!

Co-authored with @jbdelhommeau :+1:

2022-04-29 07:16 UTC, OskarStark commented on src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php
> +            InfobipTransportFactory::class => 'mailer.transport_factory.infobip',
can you please sort them alphabetically? And please move OhMySmtpTransportFactory, too, thanks

2022-04-29 07:17 UTC, OskarStark commented on src/Symfony/Component/Mailer/Bridge/Infobip/CHANGELOG.md
> + * Added the bridge
```suggestion
6.1
---

 * Add the bridge
```

2022-04-29 07:20 UTC, OskarStark reviewed
Some minor comments, thank you

2022-04-29 07:20 UTC, OskarStark commented on src/Symfony/Component/Mailer/Bridge/Infobip/Transport/InfobipApiTransport.php
> +class InfobipApiTransport extends AbstractApiTransport
```suggestion
final class InfobipApiTransport extends AbstractApiTransport
```

2022-04-29 07:20 UTC, OskarStark commented on src/Symfony/Component/Mailer/Bridge/Infobip/Transport/InfobipSmtpTransport.php
> +class InfobipSmtpTransport extends EsmtpTransport
```suggestion
final class InfobipSmtpTransport extends EsmtpTransport
```

2022-04-29 07:20 UTC, OskarStark commented on src/Symfony/Component/Mailer/Bridge/Infobip/Transport/InfobipTransportFactory.php
> +class InfobipTransportFactory extends AbstractTransportFactory
```suggestion
final class InfobipTransportFactory extends AbstractTransportFactory
```

2022-04-29 07:20 UTC, OskarStark commented on src/Symfony/Component/Mailer/Exception/UnsupportedSchemeException.php
> +        'infobip' => [
Can you please sort this alphabetically? Thanks

Please move ohmysmtp, too

Thanks

2022-04-29 07:20 UTC, OskarStark commented on src/Symfony/Component/Mailer/Tests/Exception/UnsupportedSchemeExceptionTest.php
> +            InfobipTransportFactory::class => false,
Please sort, thanks

2022-04-29 07:20 UTC, OskarStark commented on src/Symfony/Component/Mailer/Tests/Exception/UnsupportedSchemeExceptionTest.php
> +        yield ['infobip', 'symfony/infobip-mailer'];
Please sort, thanks

2022-04-29 07:20 UTC, OskarStark commented on src/Symfony/Component/Mailer/Transport.php
> +        InfobipTransportFactory::class,
Please sort, thanks

2022-04-29 08:00 UTC, B-Galati commented
@OskarStark Thanks! All fixed, hope I did not forget anything :+1:

2022-05-02 09:29 UTC, B-Galati commented
just done a little update to fix the SMTP client, all good now.

2022-05-02 09:37 UTC, B-Galati commented
Rebased with last commit to check if it fixes psalm error.

2022-05-09 09:21 UTC, B-Galati commented
@OskarStark I know it's a bit late but do you know if it could be released with 6.1?

2022-05-09 20:36 UTC, fabpot commented
We’ve been in feature freeze for more than a month now, so it’ll be for 6.2 unfortunately.

2022-05-16 09:25 UTC, B-Galati commented
Thank you, I will change the branch target then :+1:

2022-06-01 12:27 UTC, OskarStark commented on src/Symfony/Component/Mailer/Bridge/Infobip/CHANGELOG.md
> +6.1
6.2

2022-06-25 07:36 UTC, fabpot requested changes

2022-06-25 07:36 UTC, fabpot commented on src/Symfony/Component/Mailer/Bridge/Infobip/Tests/Transport/InfobipApiTransportFactoryTest.php
> +declare(strict_types=1);
all such lines should be removed

2022-06-25 07:36 UTC, fabpot commented on src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php
> -            OhMySmtpTransportFactory::class => 'mailer.transport_factory.ohmysmtp',
Rebasing on current 6.2 should cleanup the diff here

2022-06-25 07:36 UTC, fabpot commented on src/Symfony/Component/Mailer/Bridge/Infobip/CHANGELOG.md
> +6.1
6.2

2022-07-17 16:06 UTC, fabpot commented
@B-Galati Are you still interested in finishing this PR?

2022-07-17 20:35 UTC, B-Galati commented
Yes @fabpot 👍

2022-07-18 07:16 UTC, B-Galati commented
@fabpot it's ready, the CI failure looks unrelated but I am may be wrong of course.

2022-07-20 08:45 UTC, fabpot approved these changes

2022-07-20 09:32 UTC, fabpot commented
@B-Galati Can you create a PR on symfony/recipes?

2022-07-20 09:32 UTC, fabpot commented
Thank you @B-Galati.

2022-07-20 09:32 UTC, merged

2022-07-26 09:17 UTC, B-Galati commented
PR for the recipe opened symfony/recipes#1113 :heavy_check_mark: