[DependencyInjection] Autowire tagged iterators using doc blocks
symfony/symfony pull request #46253
Opened 2022-05-04 16:47 UTC by dunglas

| Q             | A
| ------------- | ---
| Branch?       | 6.1
| Bug fix?      | no
| New feature?  | yes 
| Deprecations? | no 
| Tickets       | n/a
| License       | MIT
| Doc PR        | todo

This patch allows the Dependency Injection component to autowire basic tagged iterators:

```php
namespace App;

interface RoomInterface
{
    public function getBeds(): int;
}

class Hospital
{
    /** @param RoomInterface $rooms */
    public function __construct(private iterable $rooms) {}
}
```

```yaml
# config/services.yaml
services:
    _instanceof:
        App\RoomInterface:
            tags: ['app.room']
```

Tadam! This just works 🎉

This follows [discussions](https://twitter.com/dunglas/status/1519552863915196419?s=20&t=lk_w-0sEO-89XIp1MVt2CA) about @GregoireHebert's article ["Inject a tagged iterator in a more natural way"](https://knot.gheb.dev/blog/sf-inject-tagged-iterator/).

This patch has the following limitations:

* `phpdocumentor/reflection-docblock` must be installed
* Advanced cases aren't supported (union types, multiple tags...), use the new `#[TaggedIterator]` to handle these cases

2022-05-04 17:06 UTC, stof commented
In all static analyzers, `Room[]` means `array<Room>`. But TaggedIterator does not inject an array. So it would be better to build that based on a phpdoc of `iterable<Room>` instead.

2022-05-04 17:11 UTC, dunglas commented
@stof indeed it's much better. Patch and PR description updated to use `iterable<RoomInterface>`.

2022-05-04 17:15 UTC, fabpot requested changes

2022-05-04 17:15 UTC, fabpot commented on src/Symfony/Component/DependencyInjection/CHANGELOG.md
> + * Autowire tagged iterators (needs `phpdocumentor/reflection-docblock`)
That's for 6.2, so you need to create a new section.

2022-05-04 19:02 UTC, alanpoulain commented
I don't see the value of having this configuration:
```yml
# config/services.yaml
services:
    _instanceof:
        App\RoomInterface:
            tags: ['app.room']
```
Since there is no tag information in the doc block, tagging the interface feels weird, at least to me.

2022-05-04 20:38 UTC, dunglas commented
@alanpoulain this is an existing feature: https://symfony.com/doc/current/service_container/tags.html#define-services-with-a-custom-tag

This patch just adds some syntactic sugar on top of this feature, to remove some verbose and useless configuration or attributes in the common case.

I discussed with @nicolas-grekas off-GitHub on a way to remove the config block you pointed out, but this will be for a follow-up PR (and may have edge cases).

2022-05-05 15:00 UTC, Tobion commented
I don't think this is a good idea as it removes the relation between the tag name and the iterator as already pointed out by @alanpoulain . If you search for the tag name, you won't find anything. That's really bad developer experience.

2022-05-05 15:29 UTC, dunglas commented
@Tobion @alanpoulain what we need is just a new convention: use the interface name if you want to inject all services implementing it, as we use the class name if there is only one instance of it registered as service:

```patch
# config/services.yaml
services:
    _instanceof:
        App\RoomInterface:
-            tags: ['app.room']
+            tags: ['App\RoomInterface']
```

This would fix this DX issue isn't it?

 I'm working on a follow-up PR to simplify/remove the need for this configuration snippet.

2022-05-05 15:39 UTC, dunglas commented
Actually it's already supported:

```php
namespace App;

use Symfony\Component\DependencyInjection\Attribute\AutoconfigureTag;

#[AutoconfigureTag]
interface RoomInterface
{
    public function getBeds(): int;
}

class Hospital
{
    /** @param iterable<RoomInterface> $rooms */
    public function __construct(private iterable $rooms) {}
}
```

That's all you need.

2022-05-05 16:19 UTC, chalasr commented
It's quite common that the service taking the tagged iterator as dependency implements the same interface as the services included in the iterator, so that each method iterates over these services until it finds the right one and delegates the call to it. e.g:

```php
class ChainRoomProvider implements RoomProviderInterface
{
    /** @param iterable<RoomProviderInterface> $roomProviders */
    public function __construct(private iterable $roomProviders) {}
    
    public function findRoom(): Room {
        foreach ($this->roomProviders as $roomProvider) {
            if ($roomProvider->supports($someRuntimeCriteria)) {
                return $this->roomProvider->findRoom(); 
            }
        }
    }
}
```

That wouldn't work with the proposed approach since the delegating implementation would end up being part of the iterator, right?

2022-05-05 18:58 UTC, dunglas commented
This is exactly the same situation as currently. This works as long as you don't enable autoconfiguration on `ChainRoomProvider` (and it's the same regardless of the config format you choose).

2022-05-10 08:27 UTC, nicolas-grekas reviewed
On second though, I fear this might have a too big impact on the compile-time of the container, since this is now going to parse all doc-blocks of all autowired methods. We should double check this aspect before considering this change.

Note that adding `#[TaggedIterator(FooInterface::class)]` next to the `@param`already works so this is just a way to write less declarative code next to an argument.

2022-05-10 08:32 UTC, nicolas-grekas commented
> This works as long as you don't enable autoconfiguration on ChainRoomProvider

Feature idea: allow doing this with an attribute? `#[DontAutoconfigure(...string[] $superTypes = [])]`

2022-07-02 14:16 UTC, chalasr commented
Trying to help moving forward here: Given the limitations, the potential perf cost and the fact we already have an attribute for that (and using this feature implies to use an attribut anyway) I'm not convinced this is worth it.

2022-07-11 07:46 UTC, nicolas-grekas commented
Closing as discussed. Thanks for proposing.

2022-07-11 07:46 UTC, closed without merging