[Security] Allow disabling redirect on login
symfony/symfony pull request #46320
Opened 2022-05-11 12:21 UTC by jvasseur

| Q             | A
| ------------- | ---
| Branch?       | 6.1
| Bug fix?      | no
| New feature  | yes
| Deprecations | no
| License       | MIT
| Doc PR        |

When using JSON authentication, customizing the success response can be done easily in the corresponding controller, but customizing the logout success is more tiresome and requires to create a listener for it (while still requiring to create a route for it to work).

This PR propose to add the possibility to disable the redirect on successful logout and let the request fallback to the defined route in this case.

This allow customizing both login and logout response in the same place like this:
```yaml
security:
    firewalls:
        main:
            json_login:
                check_path: auth_login
            logout:
                path: auth_logout
                target: ~
```

```php
class AuthController extends AbstractController
{
    #[Route("/login", name: "auth_login")]
    public function login(): Response
    {
        return $this->json($this->getUser());
    }

    #[Route("/logout", name: "auth_logout")]
    public function logout(): Response
    {
        return $this->json(null);
    }
}
```

It means I had to remove the Exception in case no logout listener set a response but I don't think it should be considered a BC break since the it's an error case that is removed and the corresponding exception was just the base `RuntimeException` and thus wasn't specifically catchable.

The only downside is that other logout listeners cans modify the response anymore because it doesn't exists in the event but since this is an opt-in feature I don't think it's a problem.

2025-03-08 09:38 UTC, Spomky requested changes
Hi @jvasseur,

Thank you for the proposed changes. This looks good to me.
Just a few changes rebase and we are good to go.

2025-03-08 09:38 UTC, Spomky commented on src/Symfony/Bundle/SecurityBundle/CHANGELOG.md
> + * Allow disabling the redirection on successful logout by passing `null` to the `target` option
Should move to 7.3

2025-03-08 17:03 UTC, chalasr commented
👍 from me also, once rebased and retargeted.

2026-04-09 15:17 UTC, jvasseur commented
I finally took the time to come back to this. The PR is rebased and updated for 8.1.

2026-04-09 15:22 UTC, chalasr approved these changes

2026-07-09 15:10 UTC, welcoMattic approved these changes

2026-07-09 15:18 UTC, chalasr commented
Nothing as good as merging a 4 years old PR. Thanks Jérôme!

2026-07-09 15:18 UTC, merged