[Security] Allow configuring a target url when switching user
symfony/symfony pull request #46338
Opened 2022-05-12 21:41 UTC by 94noni

| Q             | A
| ------------- | ---
| Branch?       | 6.1 (waiting 6.2)
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | none
| License       | MIT
| Doc PR        | if accepted

When using the [user switch](https://symfony.com/doc/current/security/impersonating_user.html) feature, I sometime found myself needing to redirect to a specific url (like for example the logout target)

Thus I am proposing this feature, thank you,

2022-06-23 14:37 UTC, 94noni commented
@wouterj @chalasr friendly ping as code owner
does this small feature would be accepted so I can continue working on the PR (tests etc ?)

many thanks !

2022-06-23 18:15 UTC, chalasr commented
Thanks for the ping @94noni, this looks sensible to me.

Should we throw an error if both `target_url` and `stateless` are set?

2022-06-28 06:23 UTC, 94noni commented
@chalasr I appreciate the fast feedback!

> this looks sensible to me. Should we throw an error if both target_url and stateless are set?

I will check this part as I know a little bit on this side
Are you thinking on any pitfall regarding this?

2022-06-29 20:36 UTC, chalasr commented
@94noni It's just about DX: setting a `target_url` on a stateless firewall does not make sense as there is no redirect in that case, hence forbidding that combination would make sense I think. Better be explicit than silent :) especially in the security area

2022-07-06 15:02 UTC, 94noni commented
@chalasr Indeed it makes sens, I will have a deeper look at it soon, thx

status: need work

2022-07-19 16:29 UTC, 94noni commented
@chalasr I've tried to implement your [request comment](https://github.com/symfony/symfony/pull/46338#issuecomment-1170469831)

feel free to give me feedbacks :)

2022-07-20 20:19 UTC, fabpot approved these changes

2022-07-20 20:20 UTC, chalasr requested changes

2022-07-20 20:20 UTC, chalasr commented on src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php
> +            throw new InvalidConfigurationException(sprintf('Definining a "target_url" for the "switch_user" listener on "%s" stateless firewall is forbidden as it does not make sens.', $id));
typo

2022-07-20 20:22 UTC, chalasr commented on src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php
> +            throw new InvalidConfigurationException(sprintf('Definining a "target_url" for the "switch_user" listener on "%s" stateless firewall is forbidden as it does not make sens.', $id));
```suggestion
            throw new InvalidConfigurationException(sprintf('Cannot set a "target_url" for the "switch_user" listener on the "%s" firewall as it is stateless.', $id));
```

2022-07-20 20:23 UTC, chalasr approved these changes

2022-07-20 20:38 UTC, chalasr commented
Thank you @94noni.

2022-07-20 20:38 UTC, merged