fix probably undefined variable $expireAt
symfony/symfony pull request #46346
Opened 2022-05-13 15:46 UTC by Nommyde

$expireAt is undefined when $limiterState->getExpirationTime() returns null. Built in limiters don't return null, but interface allows to do it. I've made my custom limiter with unexpired state and found this problem

| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| License       | MIT

2022-05-13 16:00 UTC, stof requested changes

2022-05-13 16:00 UTC, stof commented on src/Symfony/Component/RateLimiter/Storage/InMemoryStorage.php
> +            return $this->buckets[$limiterState->getId()][0];
This is changing the existing logic, where `$limiterState->getExpirationTime()` wins over the existing bucket expiration time.

2022-05-13 16:01 UTC, stof commented
Instead of adding a new method, I would just add a `$expireAt  = null` before the first `if`

2022-05-13 16:20 UTC, Nommyde commented
> Instead of adding a new method, I would just add a `$expireAt = null` before the first `if`

In my view this approach is the reason of this bug. So I've decided to change it. It leads to such cases like propbably undefined variables, extra computations and priority confusions.

2022-05-14 11:03 UTC, nicolas-grekas commented
Thank you @Nommyde.

2022-05-14 11:03 UTC, merged