[DependencyInjection] add `#[Exclude]` in order to not register as a service
symfony/symfony pull request #46655
Opened 2022-06-12 20:24 UTC by alamirault

| Q             | A
| ------------- | ---
| Branch?       | 6.2
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #46643
| License       | MIT
| Doc PR        | TODO

This PR allow to use `#[Exclude]` attribute when we don't want a class/method/function as service.
It can be useful in some cases and avoid use `#[When(env: 'never')]` for bad reason.

TODO:

- [ ] PR symfony doc

2022-06-14 08:15 UTC, ruudk requested changes
I would love to see this feature merged 😍

2022-06-14 08:15 UTC, ruudk commented on src/Symfony/Component/DependencyInjection/Loader/FileLoader.php
> +                if (!empty($r->getAttributes(Exclude::class))) {
never use `empty`

2022-06-14 08:15 UTC, ruudk commented on src/Symfony/Component/DependencyInjection/Loader/PhpFileLoader.php
> +        if (!empty($r->getAttributes(Exclude::class))) {
never use `empty`

2022-06-14 08:15 UTC, ruudk commented on src/Symfony/Component/DependencyInjection/Attribute/Exclude.php
> +#[\Attribute(\Attribute::TARGET_CLASS | \Attribute::TARGET_METHOD | \Attribute::TARGET_FUNCTION | \Attribute::IS_REPEATABLE)]
I wonder how this can be used on methods / functions? Wouldn't it be better to only exclude services?

2022-07-26 09:32 UTC, ruudk commented
@alamirault Do you need help with finishing this PR? It would be amazing to have this in Symfony 6.2

2022-07-26 09:44 UTC, alamirault commented
Note sure if is a good idea after discussion in https://github.com/symfony/symfony/issues/46643#issuecomment-1154355149

> do we really want to put an attribute imported from the DependencyInjection component to all non-service classes

If it's ok for core contributors, I can continue work on it

2022-07-26 12:09 UTC, chalasr commented
I won't block this as it does not hurt and it seems to be desired by the community, so I'm just +0 here :)

2022-07-26 12:20 UTC, fabpot commented
As there is already a way to do it (via When) and because it's not a widespread use case, I tend to be :-1: on this one. Adding attributes comes with a cost (maintenance, docs, complexity, learning curve, ...).

2022-07-27 16:38 UTC, nicolas-grekas commented
I'm also moot on this one. `#[When('never')]` is nicely read. If we don't like the magic value, could we use `null` for that purpose: `#[When(null)]`?

2022-07-27 17:17 UTC, nicolas-grekas commented
Closing as explained and to keep as is for history. Please submit another PR if you'd like to follow up with another approach.

2022-07-27 17:17 UTC, closed without merging

2022-07-27 17:18 UTC, nicolas-grekas commented
Thank you for the PR @alamirault!

2022-08-05 08:27 UTC, ruudk commented
Too bad this was not merged but I understand the reasonings.

I created a PR with a different and maybe more flexibel approach. Curious what you all think:
- https://github.com/symfony/symfony/pull/47196