[Mailer] Deprecate OhMySmtp Transport, Create MailPace transport
symfony/symfony pull request #46714
Opened 2022-06-19 14:38 UTC by Holicz

| Q             | A
| ------------- | ---
| Branch?       | 6.2
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | yes
| Tickets       | Fix #46340
| License       | MIT
| Doc PR        | symfony/symfony-docs#16896

OhMySMTP duplicate was created and renamed to MailPace. OhMySMTP was deprecated.

2022-06-20 10:08 UTC, welcoMattic reviewed
Looks good, thank you @Holicz. I have added some notes

2022-06-20 10:08 UTC, welcoMattic commented on src/Symfony/Component/Mailer/Bridge/OhMySmtp/Transport/OhMySmtpApiTransport.php
> +trigger_deprecation('symfony/oh-my-smtp-mailer', '6.2', 'The "%s" class is deprecated.', OhMySmtpApiTransport::class);
Please mention the new Bridge as replacement here: "…deprecated, use Symfony\Component\Mailer\Bridge\MailPace\Transport\MailPaceApiTransport instead."

2022-06-20 10:08 UTC, welcoMattic commented on src/Symfony/Component/Mailer/Bridge/OhMySmtp/Transport/OhMySmtpSmtpTransport.php
> +trigger_deprecation('symfony/oh-my-smtp-mailer', '6.2', 'The "%s" class is deprecated.', OhMySmtpSmtpTransport::class);
Please mention the new Bridge as replacement here: "…deprecated, use Symfony\Component\Mailer\Bridge\MailPace\Transport\MailPaceSmtpTransport instead."

2022-06-20 12:23 UTC, stof requested changes

2022-06-20 12:23 UTC, stof commented on src/Symfony/Component/Mailer/Bridge/MailPace/Transport/MailPaceApiTransport.php
> +            throw new HttpTransportException('Unable to send an email: '.$response->getContent(false).sprintf(' (code %d).', $statusCode), $response);
IMO, we should attach the caught exception as previous exception.

2022-06-21 11:26 UTC, Holicz commented
All comments were taken into account.

PS: What is the process for this? Should I resolve the comments when I push the changes or should the original author of the comment review the touched code once again and resolve it himself?

Thanks!

2022-06-21 12:22 UTC, welcoMattic commented
@Holicz you can resolve comment (if needed, we can unresolve it)

2022-06-25 07:23 UTC, fabpot approved these changes

2022-06-25 07:25 UTC, fabpot commented
Thank you @Holicz.

2022-06-25 07:25 UTC, closed without merging

2022-06-25 07:33 UTC, fabpot commented
@Holicz Can you submit a PR on symfony/recipes and one for the docs?

2022-06-26 13:55 UTC, Holicz commented
Sure,

Docs: https://github.com/symfony/symfony-docs/pull/16896
Recipes: https://github.com/symfony/recipes/pull/1104