[Yaml] Add support for `!php/enum *->value` syntax
symfony/symfony pull request #46771
Opened 2022-06-24 14:10 UTC by nicolas-grekas

| Q             | A
| ------------- | ---
| Branch?       | 6.2
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #44203 and the likes
| License       | MIT
| Doc PR        | -

This PR allows one to use the following Yaml together with enums:
```yaml
- !php/enum SomeEnum::Bar
- !php/enum SomeEnum::Bar->value
```

The first line gets the `SomeEnum::Bar` instance. It's the same as writing `!php/const SomeEnum::Bar` but with an additional check that this is really an enum.

The second line is the one that is really needed as it allows referencing the value backed by an enum, which is something that is not possible currently.

2022-06-24 14:14 UTC, stof requested changes
This misses the test ensuring that `!php/enum` cannot be parsed without `Yaml::PARSE_CONSTANT`

2022-06-24 14:24 UTC, nicolas-grekas commented
@stof PR updated, thanks for the review

2022-06-24 14:58 UTC, ogizanagi approved these changes

2022-06-25 07:13 UTC, fabpot approved these changes

2022-06-25 07:13 UTC, fabpot commented
Thank you @nicolas-grekas.

2022-06-25 07:13 UTC, merged