[Console] Fix/4.4/console section output without newline
symfony/symfony pull request #46812
Opened 2022-06-29 22:09 UTC by bhujagendra-ishaya

| Q             | A
| ------------- | ---
| Branch       | 4.4
| Bug fix      | yes
| New feature  | no
| Deprecations | no
| Tickets       | Fix #37304
| License       | MIT
| Doc PR        | n/a

As described in #37304, when writing to a output section, a newline would automatically be added, inrespective wether using `write()` or `writeln()`. This PR fixes said behaviour. Lines can now be appended to.

2022-06-29 22:10 UTC, bhujagendra-ishaya commented
PS: this is my first PR and I have done my best in following code style and any other applicable rules. Please advice if the PR needs improvement

2022-06-29 22:18 UTC, bhujagendra-ishaya commented
Appears as the tests that failed are not in the Console component. Does it still apply? I've only tested the Console componend with

`php ./phpunit -v src/Symfony/Component/Console/`

2022-06-30 10:22 UTC, bhujagendra-ishaya commented
The following code can be used to display the new feature.

Please note, however, that `INITIAL_ELEMENTS` needs to be set in such a way that the row with "Element_X" entries does not consume more than one line, as otherwise things will get messy.

```PHP
<?php

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Helper\ProgressBar;
use Symfony\Component\Console\Helper\QuestionHelper;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Question\Question;

require_once 'vendor/autoload.php';

const INITIAL_ELEMENTS = 5;

class TestCommand
    extends
    Command
{

    protected function configure(): void
    {

        $this->setName('test-command');
        parent::configure();
    }


    protected function execute(
        InputInterface $input,
        OutputInterface $output
    ): int {

        $output1 = $output->section();
        $output2 = $output->section();
        $output3 = $output->section();

        for ($i = 0; $i <= INITIAL_ELEMENTS;) {
            $output3->write(sprintf('Element_%s ', ++$i), false);
        }


        $progress1 = new ProgressBar($output1, 50, 0);
        $progress2 = new ProgressBar($output2, 50, 0);

        $progress1->setFormat(' [%bar%] %percent:3s%% %current%/%max% %message%');
        $progress2->setFormat(' [%bar%] %percent:3s%% %current%/%max% %message%');

        $progress1->setMessage('progress_1');
        $progress2->setMessage('progress_2');

        $progress1->start();
        sleep(1);
        $output3->write(sprintf('Element_%s ', ++$i), false);

        $progress2->start();
        sleep(1);
        $output3->write(sprintf('Element_%s ', ++$i), false);

        $progress2->advance(20);
        sleep(1);
        $output3->write(sprintf('Element_%s ', ++$i), false);

        $progress1->advance(10);
        sleep(1);
        $output3->write(sprintf('Element_%s ', ++$i), false);

        $output4 = $output->section();
        $output5 = $output->section();

        $output5->write("Wait for the question!");
        sleep(1);
        $output3->write(sprintf('Element_%s ', ++$i), false);

        $question = new QuestionHelper();
        $answer   = $question->ask($input, $output4, new Question('What\'s your favorite super hero?'));
        $output4->clear();

        $output3->writeln(". The answer is: $answer");
        $output5->writeln(" Thank you.");

        return 0;
    }

}


$application = new Application('test', '1.0');

$application->add(new TestCommand());
$application->setDefaultCommand('test-command');
$application->run();

```

2022-06-30 11:09 UTC, chalasr requested changes
Thanks for the PR. just a cosmetic review for now. 
Please ignore the unrelated failing tests.

2022-06-30 11:09 UTC, chalasr commented on src/Symfony/Component/Console/CHANGELOG.md
> + * fixed automatic adding of newlines when writing to output sections
For bugfixes, the changelog entries are auto generated at release time. As such this change should be reverted

2022-06-30 11:09 UTC, chalasr commented on src/Symfony/Component/Console/Tests/Output/ConsoleSectionOutputTest.php
> +        );
On one line please as per our coding standards, same for all object creations.

2022-06-30 11:33 UTC, bhujagendra-ishaya commented
Thanks @chalasr for your feedback. I have updated the code accordingly.

Also happy to stash the changes into one single commit. As I could not find the "Allow edits from maintainers" as mentioned by the bot.

> It looks like you unchecked the "Allow edits from maintainer" box. That is fine, but please note that if you have multiple commits, you'll need to squash your commits into one before this can be merged. Or, you can check the "Allow edits from maintainers" box and the maintainer can squash for you.
> 
> Cheers!
> 
> Carsonbot

2022-06-30 11:40 UTC, chalasr commented
You can find that checkbox on the right side of your PR: 
<img width="353" alt="Screenshot 2022-06-30 at 13 39 57" src="https://user-images.githubusercontent.com/7502063/176668701-41ce6ac7-2dc0-4b48-b47b-915ef867ebc5.png">

2022-06-30 11:53 UTC, bhujagendra-ishaya commented
> You can find that checkbox on the right side of your PR

Thank you. Actually, that's where I was looking for it but there is nothing following the Participants list ... But no worries, I'll do the stashing.

![image](https://user-images.githubusercontent.com/87441244/176670602-baa3bd6f-7507-4c7e-a232-4730edfb42ff.png)

2022-06-30 14:44 UTC, nicolas-grekas reviewed
pure cs review :)

2022-06-30 14:44 UTC, nicolas-grekas commented on src/Symfony/Component/Console/Tests/Output/ConsoleSectionOutputTest.php
> +     * @return void
the while comment should be removed imho, it doesn't bring enough value to be kept

2022-06-30 14:44 UTC, nicolas-grekas commented on src/Symfony/Component/Console/Output/ConsoleSectionOutput.php
> +            if ('' !== $sectionContent) {
should be merged with the previous line:
`if ('' !== $sectionContent = $section->getContent()) {`

2022-06-30 14:44 UTC, nicolas-grekas commented on src/Symfony/Component/Console/Tests/Output/ConsoleSectionOutputTest.php
> +        $this->assertEquals($expected, stream_get_contents($output->getStream()));
please use assertSame everywhere possible

2022-06-30 14:44 UTC, nicolas-grekas commented on src/Symfony/Component/Console/Output/ConsoleSectionOutput.php
> +                && (false !== ($lastLine = end($this->content)))
extra brackets should be removed:
`(false !== $lastLine = end($this->content))`

2022-06-30 14:44 UTC, nicolas-grekas commented on src/Symfony/Component/Console/Output/ConsoleSectionOutput.php
> +                && substr($lastLine, -1) !== \PHP_EOL
PHP_EOL can be two-chars long isn't it?
this should use str_ends_with instead no?

2022-06-30 15:28 UTC, bhujagendra-ishaya commented on src/Symfony/Component/Console/Tests/Output/ConsoleSectionOutputTest.php
> +     * @return void
Happy to do that. I was just following the phpcs reccomendation given by

`vendor/bin/phpcs src/Symfony/Component/Console/Tests/Output/ConsoleSectionOutputTest.php`

using 

` "escapestudios/symfony2-coding-standard": "^3.12.0",`

as recommended by https://github.com/djoos/Symfony-coding-standard which apparently are not very accurate, given that also the line breaks added to the object creation (as mentioned by the previous reviewer) were implemented due to those recommendations.

2022-06-30 15:32 UTC, nicolas-grekas commented on src/Symfony/Component/Console/Tests/Output/ConsoleSectionOutputTest.php
> +     * @return void
we don't use those tools in this repo :shrug:

2022-06-30 15:34 UTC, bhujagendra-ishaya commented on src/Symfony/Component/Console/Output/ConsoleSectionOutput.php
> +                && substr($lastLine, -1) !== \PHP_EOL
Absolutely! Thank you for spotting it!

2022-06-30 15:40 UTC, fabpot commented
As this is a behavior change that people rely on, it cannot be fixed in 4.4. I'm not even sure having this in 6.2 would be acceptable.

2022-06-30 15:57 UTC, bhujagendra-ishaya commented
@fabpot in that case, #37304 should not be considered a but, but a feature request.

But why would people rely on this bug? If you want to have a new line at the end of your message, then you would certainly use `writeln()` and not `write()`. In case you have always used `writeln()`, then the behavior does not change. If you used `write()` instead, relying on the fact that the newline would be added (but only if you write to a section), then I would consider this a buggy code that should be fixed. (IMO)

Fact is, that it is currently not possible to write partial lines. Imagine the case of `./configure` in binary projects. Where you have something like:

`checking for make ...`

which will then become

`checking for make ... ok.`

This is possible in a normal console output, but not if it's a section. To me, that does not make sense. As a workaround, people could overwrite the entire section. If they do that, this will still work even with the fix applied.

It would be good to have a use case, where people actually rely on the current buggy behavior.

2022-07-05 13:36 UTC, bhujagendra-ishaya commented
@fabpot, how do we proceed with this?

2022-07-05 14:48 UTC, nicolas-grekas commented
I'm personally fine merging this on 6.2 if we consider this is too risky for 4.4.

2022-07-05 17:38 UTC, fabpot commented
There is no use case for the bug, just people not realizing the difference. Anyway, as this is "just" some CLI output, let's merge it in 6.2.

2022-07-05 17:39 UTC, fabpot commented
Can you change the branch to 6.2?

2022-07-05 22:00 UTC, bhujagendra-ishaya commented
Thank you guys for getting back on this. Certainly I can change the branch.

Given that **v6.2 requires php v8.1** and this is unfortunately still not available on many platforms, would maybe **v5.4** be an acceptable compromise?

2022-07-06 09:42 UTC, chalasr commented
@bhujagendra-ishaya I fear it is not, sorry. Either we qualify it as a bug and then the fix goes to the lowest branch where it applies, or we qualify it as an enhancement (which is the case here for the reasons given) and then it is for the current development branch, namely 6.2.

2022-07-06 09:45 UTC, fabpot commented
@chalasr is right.

2022-07-08 05:34 UTC, fabpot commented
Thank you @bhujagendra-ishaya.

2022-07-08 05:35 UTC, closed without merging

2022-07-08 12:45 UTC, bhujagendra-ishaya commented
> @bhujagendra-ishaya I fear it is not, sorry. Either we qualify it as a bug and then the fix goes to the lowest branch where it applies, or we qualify it as an enhancement (which is the case here for the reasons given) and then it is for the current development branch, namely 6.2.

HI guys,

strictly speaking, the question was whether it is a bug or a breaking change. @fabot argued that people would rely on this buggy behavior and as such the change would break their code based on that expectation (using `write()` instead of `writeln()`). At the same time there seems to be no use-case for this. If I want to make sure, my output is terminated y a newline, I just add a newline to it...

According to https://github.com/symfony/symfony/issues/37304 it is a bug since version 4.1. Since it was qualified as a bug, I created a PR against the 4.4 branch. If it is not a bug, it would be a breaking change and have to go to v7.x based on symver policy.

Treating this PR as a new feature seems odd to me, as there is not really a "feature" that you can enable or disable, use or not use. This would be the case, if you could chose the behavior when creating the section (e.g. adding an optional function argument to `ConsoleOutputInterface::section()`, defaulting to the old behavior, if no value is given. But this seems a bit overkill to me.

Since I don't really understand why it is not considered a bug, it seems an arbitrary choice to me to classify it as a "new feature", rather than a "breaking change"...

2022-07-08 13:08 UTC, bhujagendra-ishaya commented
Oh, I just saw that this is a fait-complit, as it has already been merged to 6.2 ...

See Commit https://github.com/symfony/symfony/commit/1f73c495392b12d4876d583c7ae3015ad9afaa53.