add test with wrong include, see #46833
symfony/symfony pull request #46835
Opened 2022-07-03 21:53 UTC by alexislefebvre

| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes/no
| New feature?  | no
| Deprecations? | no
| Tickets       | Test for #46833
| License       | MIT
| Doc PR        | 

I only added cases that should break the tests as described in #46833

2022-07-12 18:24 UTC, alexislefebvre commented on src/Symfony/Component/DependencyInjection/Tests/Fixtures/yaml/services_prototype.yml
> +            - '../Prototype/OtherDir'
The test should test the same behaviour as before, this line must be changed.

2022-07-21 11:14 UTC, stof commented
I would rather fail with a good error message explaining you your mistake rather than silently ignoring the invalid pattern.

2022-07-21 11:28 UTC, alexislefebvre commented
@stof Right, I force-pushed a check that will throw an error instead of ignoring it.

If it's ok for you, tests will have to be updated to handle this case in a new test.

2022-07-21 11:43 UTC, fabpot requested changes

2022-07-21 11:43 UTC, fabpot commented on src/Symfony/Component/DependencyInjection/Loader/FileLoader.php
> +            throw new InvalidArgumentException('The exclude list contain a null value.');
```suggestion
            throw new InvalidArgumentException('The exclude list must not contain a "null" value.');
```
?

2022-07-21 12:06 UTC, fabpot commented
I think this should be rebased on 6.2.
Can you update the tests?

2022-07-21 21:43 UTC, alexislefebvre commented
What if using an empty item in another part of the config throw another error in another part of Symfony? Should the config validator be more strict? As I wrote in #46833, the YAML (or XML, etc.) is still valid.

2022-07-21 23:24 UTC, stof commented
the Yaml being valid for the Yaml parser does not mean that the content of this Yaml is a valid input for the DependencyInjection file loader. That's why it is the FileLoader doing its validation on the input it expects.

2022-07-27 16:27 UTC, nicolas-grekas commented
Tests fail, see failures + fabbot report also.

It'd be better to create dedicated test cases to me. Can you please update the PR to do so?

2022-08-02 18:52 UTC, alexislefebvre commented
The branch has been rebased and tests have been added.

2022-08-03 12:05 UTC, nicolas-grekas approved these changes

2022-08-03 12:09 UTC, nicolas-grekas commented
Thank you @alexislefebvre.

2022-08-03 12:09 UTC, merged