Remove .gitignore file from dist package
symfony/symfony pull request #47079
Opened 2022-07-27 13:34 UTC by cedric-anne

| Q             | A
| ------------- | ---
| Branch?       | 6.2
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | -

Not a big deal, but `.gitignore` file is present in dist package fetched from packagist.

2022-07-27 13:37 UTC, cedric-anne commented
Sorry for the multiple commits, I have made it one by one from GitHub UI. I can squash them if it is a problem.

2022-07-27 14:40 UTC, GromNaN approved these changes
> Sorry for the multiple commits, I have made it one by one from GitHub UI. I can squash them if it is a problem.

Don't worry, we have a tool to squash before merging.

2022-07-28 08:22 UTC, nicolas-grekas commented
There are more of them:
```
src/Symfony/Contracts/Cache/.gitignore
src/Symfony/Contracts/.gitignore
src/Symfony/Contracts/EventDispatcher/.gitignore
src/Symfony/Contracts/Service/.gitignore
src/Symfony/Contracts/Translation/.gitignore
src/Symfony/Contracts/Deprecation/.gitignore
src/Symfony/Contracts/HttpClient/.gitignore
```

2022-07-29 10:13 UTC, cedric-anne commented
I added `.gitattributes` files where they were missing, and also added `export-ignore` on test files.
By the way, I noticed that some the namespace of test files is sometimes `Test` on `Symfony\Contracts`, and that is not consistent with namespace `Tests` used everywhere else in Symfony codebase.

2022-07-29 10:18 UTC, cedric-anne commented
> By the way, I noticed that some the namespace of test files is sometimes `Test` on `Symfony\Contracts`, and that is not consistent with namespace `Tests` used everywhere else in Symfony codebase.

My bad, these should not be excluded.

2022-07-29 10:20 UTC, fabpot requested changes

2022-07-29 10:20 UTC, fabpot commented on src/Symfony/Contracts/Translation/.gitattributes
> +/Test export-ignore
Should be reverted. The `Test` namespace contains files that people can reuse in their own tests. The `Tests` namespace contains tests that we can indeed ignore.

2022-07-29 10:28 UTC, GromNaN approved these changes

2022-07-29 11:13 UTC, nicolas-grekas commented
Thank you @cedric-anne.

2022-07-29 11:13 UTC, merged