[HttpKernel] Use xxh3 algorithm instead of sha256 for http cache store key
symfony/symfony pull request #47094
Opened 2022-07-28 09:06 UTC by pascalwoerde

| Q             | A
| ------------- | ---
| Branch?       | 6.2 
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #46893
| License       | MIT

Use xxh3 algorithm instead of sha256 for http cache store key. PR as requested in #46893

* Note that the xxHash support is available since PHP 8.1 as noted in the [change log](https://www.php.net/ChangeLog-8.php#PHP_8_1).

2022-07-28 09:12 UTC, nicolas-grekas commented
Thanks for the PR, that's always the best way to start a conversation on this repo :)

Now that I double checked xxh3, it's not cryptographically secure, isn't it? Since we're using this hash as the key to the cached response payload, this means we could open the storage to hash collisions attacks, provided the hacker can somehow control the response content. WDYT? Doesn't this disqualify xxh3 for this use case?

2022-07-28 10:02 UTC, pascalwoerde commented
That's right the whole xxh family isn't cryptographically secure, so it's easier for someone to recalculate a potential collision. I don't think that a hacker can have any benefit from this, since it is a oneway direction to retrieve data. xxh is great for change detection, which is ideal for this situation IMO. While I'm typing the only thing that I can imaging now is a collision by the number of responses, because xxh3 is 64 bit. Which means that when there are over a bilion of responses cached there will be a small change resulting in identical hash. I will suggest to use the xxh128 instead to extend the range.

2022-07-29 10:25 UTC, GromNaN commented
This is a great performance optimization. I shared some references on https://github.com/twigphp/Twig/pull/3588.

Regarding security: the hashed contents comes from an external input. An attacker could manipulate the query string so that the hash of a request URI would colite with an other. This is a cache poisoning attack: you could make the content of the page https://connect.symfony.com/profile/pascalwoerde appear under the URI https://connect.symfony.com/profile/fabpot. I don't have the skills to do so, but we have to trust the experts that flagged this algorithm as non-cryptographically safe.

2022-07-29 10:45 UTC, alexislefebvre commented
> Regarding security: the hashed contents comes from an external input. An attacker could manipulate the query string so that the hash of a request URI would colite with an other.

In this PR, the hash is not on the URL but on `$response->getContent()`, so an attacker would have to alter the content of the resulting HTML?

2022-07-29 11:20 UTC, GromNaN commented
Oh exact. So at most the attacker could update a page without invalidate the cache. That seems safe.

2022-07-29 13:15 UTC, fabpot requested changes

2022-07-29 13:15 UTC, fabpot commented on src/Symfony/Component/HttpKernel/HttpCache/Store.php
> - *
Should be reverted

2022-07-29 13:15 UTC, fabpot commented on src/Symfony/Component/HttpKernel/HttpCache/Store.php
> +        // Everything seems ok, omit writing content to disk
should be reverted

2022-07-29 13:15 UTC, fabpot commented on src/Symfony/Component/HttpFoundation/CHANGELOG.md
> + * Http cache store uses the `xxh128` algorithm
```suggestion
 * The HTTP cache store uses the `xxh128` algorithm
```

2022-08-14 13:51 UTC, fabpot approved these changes

2022-08-14 13:52 UTC, fabpot commented
Note that this change invalidates all the cached items when upgrading to 6.2.

2022-08-14 13:52 UTC, fabpot commented
Thank you @pascalwoerde.

2022-08-14 13:52 UTC, merged