[Serializer] Fallback Looking for DiscriminatorMap on interfaces
symfony/symfony pull request #47221
Opened 2022-08-08 12:06 UTC by Caligone

…ent object also extends from a class

| Q             | A
| ------------- | ---
| Branch?       | 6.2 for features / 4.4, 5.4, 6.0 or 6.1 for bug fixes 
| Bug fix?      | yes/no
| New feature?  | yes/no 
| Deprecations? | yes/no 
| Tickets       | Fix #... 
| License       | MIT
| Doc PR        | symfony/symfony-docs#...

2022-11-28 18:28 UTC, derrabus commented
Hello. Sorry nobody has picked up your PR yet. I have to ask you to provide a test for your change. This helps a reviewer understand the problem that you're attempting to fix. The test also makes sure, your bug is not re-introduced by accident.

2022-11-29 08:12 UTC, Caligone commented
No worries
As requested, I added a test
I would be happy to receive feedback and make adjustments as needed

2023-09-01 14:03 UTC, mtarld requested changes
Almost good!

2023-09-01 14:03 UTC, mtarld commented on src/Symfony/Bridge/Doctrine/Middleware/Debug/Query.php
> -    public function setParam(string|int $param, null|string|int|float|bool &$variable, int $type): void
I don't think this change is related to the Serializer :slightly_smiling_face:

2023-09-01 14:03 UTC, mtarld commented on src/Symfony/Bridge/Doctrine/Tests/Middleware/Debug/MiddlewareTest.php
> +        $sql = <<<EOT
Same for these changes

2023-09-01 14:03 UTC, mtarld commented on src/Symfony/Component/Serializer/Tests/Fixtures/DummyMessageNumberThree.php
> + * @author Samuel Roze <samuel.roze@gmail.com>
I think you can be the author here :wink:

2023-09-01 14:03 UTC, mtarld commented on src/Symfony/Component/Serializer/Tests/Fixtures/DummyMessageNumberThree.php
> +use Symfony\Component\Serializer\Annotation\Groups;
This use is useless

2023-09-01 14:04 UTC, mtarld commented
As it's an old bug, could you target the `5.4` branch instead?

2023-09-01 14:47 UTC, stof commented on src/Symfony/Component/Serializer/Tests/Fixtures/DummyMessageNumberThree.php
> + * @author Samuel Roze <samuel.roze@gmail.com>
generally, we don't care about maintaining `@author` on test fixtures. Anyway, to see who worked on a file, the git history is a more reliable tool.

2023-09-02 08:22 UTC, Caligone commented
Thanks for the feedback !
I rebased and fixed last issues

2023-09-05 09:40 UTC, mtarld approved these changes

2023-09-10 09:03 UTC, fabpot approved these changes

2023-09-10 09:03 UTC, fabpot commented
Thank you @Caligone.

2023-09-10 09:03 UTC, merged