[FrameworkBundle] Update ContainerDebugCommand to add parial search for tags
symfony/symfony pull request #47311
Opened 2022-08-18 05:32 UTC by BOB41K1987

| Q             | A
| ------------- | ---
| Branch?       | 6.2
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | 
| License       | MIT
| Doc PR        | 

As of now, the `debug:container` command allows the use of partial search for the service name but doesn't allow the partial search for `tags`. It can be especially useful when using with `#[AutoconfigureTag]` attribute when the class FQN becomes a tag.
```
namespace App\SomeBundle\SomeService\Inerfaces;

use Symfony\Component\DependencyInjection\Attribute\AutoconfigureTag;

#[AutoconfigureTag]
interface SomeInterface{}
```

As of now, to find the services tagged with this interface we need to execute
`bin/console debug:container --tag=App\\SomeBundle\\SomeService\\Inerfaces\\SomeInterface`
which looks a bit overwhelming.

This PR allows to search simply by  
`bin/console debug:container --tag=SomeInterface`
which is much simpler. 

In case there are multiple tags containing the string, the command will allow choosing the one the user is looking for:
```
bin/console debug:container --tag=kernel

 Select one of the following tags to display its information:
  [0] kernel.event_listener
  [1] kernel.event_subscriber
  [2] kernel.reset
  [3] kernel.cache_warmer
  [4] kernel.locale_aware
  [5] kernel.fragment_renderer
  [6] kernel.cache_clearer
```

2022-08-18 09:19 UTC, 94noni reviewed
Nice PR

2022-08-18 09:19 UTC, 94noni commented on src/Symfony/Bundle/FrameworkBundle/Command/ContainerDebugCommand.php
> +            if (false !== stripos($tag, $tagName)) {
You can use str_contains :)

2022-08-23 15:46 UTC, BOB41K1987 commented on src/Symfony/Bundle/FrameworkBundle/Command/ContainerDebugCommand.php
> +            if (false !== stripos($tag, $tagName)) {
Thanks, fixed.

2022-08-23 15:57 UTC, fabpot requested changes

2022-08-23 15:57 UTC, fabpot commented on src/Symfony/Bundle/FrameworkBundle/Command/ContainerDebugCommand.php
> +        if (empty($matchingTags)) {
```suggestion
        if (!$matchingTags) {
```

2022-08-27 05:54 UTC, fabpot approved these changes

2022-08-27 05:54 UTC, fabpot commented on src/Symfony/Bundle/FrameworkBundle/Command/ContainerDebugCommand.php
> +            if (false !== str_contains($tag, $tagName)) {
```suggestion
            if (str_contains($tag, $tagName)) {
```

2022-08-29 06:42 UTC, fabpot commented
Thank you @BOB41K1987.

2022-08-29 06:42 UTC, closed without merging