Replace get_class() calls by ::class
symfony/symfony pull request #47401
Opened 2022-08-26 15:00 UTC by deguif

| Q             | A
| ------------- | ---
| Branch?       | 6.2
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | 
| License       | MIT
| Doc PR        | 

Replace `get_class()` by `::class`

2022-08-26 15:07 UTC, fabpot requested changes

2022-08-26 15:07 UTC, fabpot commented on src/Symfony/Bridge/PhpUnit/CoverageListener.php
> +            $class = $test::class;
Should be reverted as PHPUnit must still be compatible with PHP 7.1 (same for all files in this bridge).

2022-08-26 15:11 UTC, stof commented
I'm really not convinced that `$object::class` is more readable than `get_class($object)`. I would be in favor of keeping the usage of `get_class`

2022-08-26 15:26 UTC, deguif commented on src/Symfony/Bridge/PhpUnit/CoverageListener.php
> +            $class = $test::class;
I reverted the changes on the phpunit bridge

2022-08-26 15:45 UTC, nicolas-grekas commented
I like the change personally. It gives a consistent syntax to get the class of something. Once use to it, we won't want to get back :)

2022-08-26 22:37 UTC, derrabus approved these changes

2022-08-30 10:28 UTC, chalasr approved these changes

2022-08-31 06:24 UTC, artyuum approved these changes

2022-09-01 02:03 UTC, fabpot commented
Thank you @deguif.

2022-09-01 02:03 UTC, merged