Fix checking result of DateTime::getLastErrors
symfony/symfony pull request #47428
Opened 2022-08-30 10:25 UTC by nicolas-grekas

| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | -

Spotted by our CI on PHP 8.2

This returns an array on PHP < 8.2 and `false` on 8.2:
```php
DateTime::createFromFormat('Y', '2022');
var_dump(DateTime::getLastErrors());
```

/cc @derickr FYI as this might also be considered as a BC break on PHP 8.2

2022-08-30 10:27 UTC, chalasr approved these changes

2022-08-30 10:32 UTC, xabbuh approved these changes

2022-08-30 10:33 UTC, xabbuh requested changes
looks like (at least) the `DateTimeValidator` needs some more changes

2022-08-30 10:34 UTC, stof commented
Access to `$errors['warnings']` should indeed also be guarded there.

2022-08-30 10:36 UTC, derickr commented
On 30 August 2022 11:25:46 BST, Nicolas Grekas ***@***.***> wrote:
>| Q             | A
>| ------------- | ---
>| Branch?       | 4.4
>| Bug fix?      | yes
>| New feature?  | no
>| Deprecations? | no
>| Tickets       | -
>| License       | MIT
>| Doc PR        | -
>
>Spotted by our CI on PHP 8.2
>
>This returns an array on PHP &lt; 8.2 and `false` on 8.2:
>```php
>DateTime::createFromFormat(&#39;Y&#39;, &#39;2022&#39;);
>var_dump(DateTime::getLastErrors());
>```
>
>
>/cc @derickr FYI as this might also be considered as a BC break on PHP 8.2
>You can view, comment on, or merge this pull request online at:
>
>  https://github.com/symfony/symfony/pull/47428
>
>-- Commit Summary --
>
>  * Fix checking result of DateTime::getLastErrors
>
>-- File Changes --
>
>    M src/Symfony/Component/Form/Extension/Core/DataTransformer/DateTimeToStringTransformer.php (2)
>    M src/Symfony/Component/Validator/Constraints/DateTimeValidator.php (2)
>
>-- Patch Links --
>
>https://github.com/symfony/symfony/pull/47428.patch
>https://github.com/symfony/symfony/pull/47428.diff
>

This is a bug fix as the new 8.2 behaviour is how it has been documented for over a decade. I didn't merge it to 8.0 and 8.1 because it does change BC.

2022-08-30 10:38 UTC, stof commented
> This is a bug fix as the new 8.2 behaviour is how it has been documented for over a decade. I didn't merge it to 8.0 and 8.1 because it does change BC.

Well, I would say that code is a lot more likely to expect the behavior that exists since a decade than the documented code that was never implemented until now.

2022-08-30 10:42 UTC, derrabus approved these changes

2022-08-30 11:57 UTC, nicolas-grekas commented
> looks like (at least) the DateTimeValidator needs some more changes

yup, fixed

2022-08-30 12:07 UTC, stof approved these changes

2022-08-30 12:34 UTC, xabbuh approved these changes

2022-08-30 15:58 UTC, merged

2022-09-05 16:13 UTC, PhilETaylor commented
I just stumbled upon this bug in my project, wrote the pr, unit test and was getting ready to submit and then checked my branch was up to date and it wasn't, so  checked here and BANG 🎉 its already fixed 5 days ago... you guys are awesome!