Add warning for possibly truncated inputs (#47586)
symfony/symfony pull request #47588
Opened 2022-09-15 13:57 UTC by pbek

| Q             | A
| ------------- | ---
| Branch?       | 6.2
| Bug fix?      | yes
| Tickets       | Fix #47586
| License       | MIT

2022-09-20 18:31 UTC, fabpot requested changes

2022-09-20 18:31 UTC, fabpot commented on src/Symfony/Component/Console/Helper/QuestionHelper.php
> +            $errOutput->warning('Value has exactly 4095 characters: it possibly was truncated by your shell or terminal emulator');
```suggestion
            $errOutput->warning('The value was possibly truncated by your shell or terminal emulator');
```

2022-09-23 06:08 UTC, fabpot approved these changes

2022-09-23 06:08 UTC, fabpot commented
Thank you @pbek.

2022-09-23 06:09 UTC, merged

2022-09-23 06:20 UTC, pbek commented
Thank you too, @fabpot! 😉