Add warning for possibly truncated inputs (#47586)
symfony/symfony pull request #47587
Opened 2022-09-15 13:32 UTC by pbek

| Q             | A
| ------------- | ---
| Branch?       | 6.2 for features / 4.4, 5.4, 6.0 or 6.1 for bug fixes 
| Bug fix?      | yes
| Tickets       | Fix #47586
| License       | MIT

2022-09-20 18:32 UTC, fabpot requested changes

2022-09-20 18:32 UTC, fabpot commented on src/Symfony/Bundle/FrameworkBundle/Command/SecretsSetCommand.php
> +                $io->warning('Value has exactly 4095 characters: it possibly was truncated by your shell or terminal emulator');
```suggestion
                $io->warning('The value was possibly truncated by your shell or terminal emulator');
```

2022-09-21 06:26 UTC, pbek commented
Just a note: If #47588 would get accepted, this PR is redundant and can be ignored.

2022-09-23 06:07 UTC, fabpot commented
Closing in favor of #47588

2022-09-23 06:07 UTC, closed without merging