add azerbaijani missing translation
symfony/symfony pull request #47699
Opened 2022-09-26 15:38 UTC by lacpandore

| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #45125
| License       | MIT

2022-09-26 15:46 UTC, nicolas-grekas commented
How do you do those translations @lacpandore? We require a review by a native speaker before merging translations. Can you please figure out who would be a native speaker of each language and ask the a review here? I suggest looking at the "blame" of the file to figure this out. Please do that for every language you're contributing.

2022-09-26 16:13 UTC, stof commented on src/Symfony/Component/Stopwatch/Tests/StopwatchPeriodTest.php
> +        yield [2.71, 3.14, true, 0.43000000000000016];
this change does not belong to a PR updating translations

2022-09-27 12:34 UTC, lacpandore commented
> How do you do those translations @lacpandore? We require a review by a native speaker before merging translations. Can you please figure out who would be a native speaker of each language and ask them a review here? I suggest looking at the "blame" of the file to figure this out. Please do that for every language you're contributing.

ok i"ll do this

@seferov would you accept to see this PR to review the translation ?

2022-09-27 12:54 UTC, seferov requested changes

2022-09-27 12:54 UTC, seferov commented on src/Symfony/Component/Security/Core/Resources/translations/security.az.xlf
> +                <target>Həddindən artıq uğursuz giriş cəhdləri, %minutes% dəqiqə ərzində yenidən cəhd edin.</target>
```suggestion
                <target>Həddindən artıq uğursuz giriş cəhdi, lütfən %minutes% dəqiqə ərzində yenidən yoxlayın.</target>
```

2022-09-27 12:54 UTC, seferov commented on src/Symfony/Component/Security/Core/Resources/translations/security.az.xlf
> +                <target>Həddindən artıq uğursuz giriş cəhdləri, %minutes% dəqiqə ərzində yenidən cəhd edin.</target>
```suggestion
                <target>Həddindən artıq uğursuz giriş cəhdi, lütfən %minutes% dəqiqə ərzində yenidən yoxlayın.</target>
```

2022-09-27 12:58 UTC, seferov commented
> @seferov would you accept to see this PR to review the translation ?

@lacpandore I corrected some minor mistakes but the rest looks good.

2022-10-15 06:47 UTC, fabpot commented
@seferov Can you submit a new PR so that we can merge it? Thank you.

2022-10-15 21:13 UTC, seferov commented
> @seferov Can you submit a new PR so that we can merge it? Thank you.

@fabpot here it is https://github.com/symfony/symfony/pull/47875

2022-10-17 06:40 UTC, fabpot commented
Closing in favor of #47875

2022-10-17 06:40 UTC, closed without merging