[Console] Fix completion
symfony/symfony pull request #47780
Opened 2022-10-03 23:20 UTC by h3xx

| Q             | A
| ------------- | ---
| Branch?       | 6.1
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | None found
| License       | MIT
| Doc PR        | -

Set `COMP_WORDBREAKS` instead of `IFS` in the completion script.

More in-depth explanation:

`IFS` affects other things not related to programmable completion, such as how the shell breaks up argument lists.

For example, by default this splits the unquoted variable as-expected:
```sh
OPTION_LIST='foo bar'
for OPT in $OPTION_LIST; do printf '%s\n' "$OPT"; done
> foo
> bar
```

Changing IFS makes the variable not split as expected, printing all on one line:
```sh
IFS=$'\n'
for OPT in $OPTION_LIST; do printf '%s\n' "$OPT"; done
> foo bar
```

This PR changes it to use `$COMP_WORDBREAKS` which specifically affects how programmable completion works, instead of affecting and effectively poisoning how the user's shell works.

2022-10-03 23:22 UTC, h3xx commented
By the way, the out-of-date nature of this branch is intentional to allow merging wherever necessary.

2022-10-04 07:31 UTC, GromNaN commented
Hello @h3xx, thank you for the patch and the details. I worked on this completion script and would like to make some tests.

I'm a beginner in bash scripting, but apparently updating `COMP_WORDBREAKS` is not more recommended than `IFS`.

https://stackoverflow.com/a/12495480

Did you hit a specific issue?

2022-10-04 15:53 UTC, h3xx commented
> I'm a beginner in bash scripting, but apparently updating `COMP_WORDBREAKS` is not more recommended than `IFS`. https://stackoverflow.com/a/12495480

Interesting. I didn't know that's what `__ltrim_colon_completions` did. I'll see if it makes sense to integrate a call to that function instead of modifying `COMP_WORDBREAKS`. I'm still convinced that modifying `IFS` isn't the right thing to do -- see issue below.

> I worked on this completion script and would like to make some tests.

I'm all in favor of unit tests :-). I'll see what I can come up with, integrating a test for my issue into CI.

> Did you hit a specific issue?

Yes, the issue is outlined in the PR's description, but a more concise failure case is thus:

On my system, `ls` is an alias for `/bin/ls $LS_OPTIONS`, `$LS_OPTIONS` is a space-separated list of options:

```sh
alias ls='/bin/ls $LS_OPTIONS'
LS_OPTIONS="-F -b -T 0 --color=auto --block-size='1"
ls
CHANGELOG-6.0.md    CONTRIBUTORS.md  UPGRADE-6.1.md  phpunit.xml.dist
CHANGELOG-6.1.md    LICENSE          composer.json   psalm.xml
CODE_OF_CONDUCT.md  README.md        link*           src/
CONTRIBUTING.md     UPGRADE-6.0.md   phpunit*
```

After using this function the alias would no longer work:

```
eval "$(sed -e 's,{{ COMMAND_NAME }},foo,g' < src/Symfony/Component/Console/Resources/completion.bash)"
_sf_foo
ls
ls: invalid option -- ' '
Try 'ls --help' for more information.
```

2022-10-12 23:05 UTC, h3xx commented
Okay, I've added a unit test that successfully reproduces my issue. Now, I'm looking into the `__ltrim_colon_completions` solution you suggested.

2022-11-12 20:24 UTC, GromNaN requested changes
Thank you very much for working on a test but I tried on a Mac Intel and in Docker Alpine and it fails (see other comments).

The fix actually works and fixes the reported issues. We can keep only the 1st commit and work on tests in a separate PR.

2022-11-12 20:24 UTC, GromNaN commented on src/Symfony/Component/Console/Tests/Resources/BashCompletionTest.php
> +            'LS_OPTIONS="-F -b"',
Is it necessary to have the option `-b`? It is not recognized on alpine.

If I remove this option, the test pass even if revert the change on the completion script.

```
bash-5.1# ls -b
ls: unrecognized option: b
BusyBox v1.35.0 (2022-08-01 15:14:44 UTC) multi-call binary.

Usage: ls [-1AaCxdLHRFplinshrSXvctu] [-w WIDTH] [FILE]...

List directory contents

        -1      One column output
        -a      Include names starting with .
        -A      Like -a, but exclude . and ..
        -x      List by lines
        -d      List directory names, not contents
        -L      Follow symlinks
        -H      Follow symlinks on command line
        -R      Recurse
        -p      Append / to directory names
        -F      Append indicator (one of */=@|) to names
        -l      Long format
        -i      List inode numbers
        -n      List numeric UIDs and GIDs instead of names
        -s      List allocated blocks
        -lc     List ctime
        -lu     List atime
        --full-time     List full date/time
        -h      Human readable sizes (1K 243M 2G)
        --group-directories-first
        -S      Sort by size
        -X      Sort by extension
        -v      Sort by version
        -t      Sort by mtime
        -tc     Sort by ctime
        -tu     Sort by atime
        -r      Reverse sort order
        -w N    Format N columns wide
        --color[={always,never,auto}]

```

2022-11-12 20:24 UTC, GromNaN commented on src/Symfony/Component/Console/Tests/Resources/BashCompletionTest.php
> +            '/usr/share/bash-completion/bash_completion',
On Mac Intel, none of this files exists. There is `/usr/local/Cellar/bash-completion/1.3_3/etc/bash_completion` and `/usr/local/Cellar/bash-completion@2/2.11/share/bash-completion/bash_completion`.

2022-11-12 20:24 UTC, GromNaN commented on src/Symfony/Component/Console/Tests/Resources/BashCompletionTest.php
> +        $this->assertEmpty($missing);
I have a more debuggable output with this:
```suggestion
        $this->assertEquals([], $missing);
```

2022-11-13 02:15 UTC, h3xx commented on src/Symfony/Component/Console/Tests/Resources/BashCompletionTest.php
> +            '/usr/share/bash-completion/bash_completion',
On Mac Intel, is bash completion even supported outside of Homebrew?

2022-11-13 02:16 UTC, h3xx commented on src/Symfony/Component/Console/Tests/Resources/BashCompletionTest.php
> +            'LS_OPTIONS="-F -b"',
Replaced with `LS_OPTIONS="-a -l"`. Hopefully those are more universally supported, even in ancient versions of ls.

2022-11-13 02:20 UTC, h3xx commented on src/Symfony/Component/Console/Tests/Resources/BashCompletionTest.php
> +            '/usr/share/bash-completion/bash_completion',
The real question is, does CI need to run/pass on a Mac? Are any of the CI images used OSX-based?

2022-11-13 07:14 UTC, GromNaN commented on src/Symfony/Component/Console/Tests/Resources/BashCompletionTest.php
> +            '/usr/share/bash-completion/bash_completion',
Yes, tests must run on all supported environments. They could be skipped if some preconditions are not meet (bash completion not installed).

2022-12-13 17:13 UTC, nicolas-grekas commented
What's the status here?

2022-12-13 20:38 UTC, h3xx commented
> What's the status here?

@nicolas-grekas It's "on my list of things to do." Life is pretty hectic atm.

If it lessens your mental load, feel free to close this PR and I will re-open when I get around it.

2022-12-14 15:24 UTC, nicolas-grekas commented
No worries, I was just wondering. When you can!

2025-03-29 15:26 UTC, chalasr commented
Closing as there is no more activity. Please feel free to reopen

2025-03-29 15:26 UTC, closed without merging