TraceableHttpClient: increase decorator's priority
symfony/symfony pull request #47836
Opened 2022-10-11 18:32 UTC by adpeyre

| Q             | A
| ------------- | ---
| Branch?       | 4.4 
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | 
| License       | MIT
| Doc PR        | 

Hello,

When I decorate my http client, all requests are not collected and visible in the profiler because of the decorator's priority of TraceableHttpClient (sub request for example). I think it should be in increased. I fixed an arbitrary value of 100.

What do you think about that ?

Ty

2022-10-17 17:11 UTC, nicolas-grekas approved these changes
makes sense to me

2022-10-17 17:48 UTC, chalasr commented
~~Sorry if I'm mistaken, but wouldn't increasing the priority rather make your decorator untraceable? Ref: https://github.com/symfony/symfony/pull/47764, looks like we need a policy here~~

Got it, we don't care as the http-client collector is not about tracing code execution but requests/responses.

2022-10-17 21:38 UTC, chalasr requested changes
This means we have to adjust the decoration priority of `RetryableHttpClient` as well on higher branches:
https://github.com/symfony/symfony/blob/af6a7770049011342ce43c7469b90354b61b269a/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L2411
 which might be more risky BC-wise (see https://github.com/symfony/symfony/pull/38633 for background)

2022-12-13 11:08 UTC, nicolas-grekas approved these changes
I set the priority to 5 instead, to account for @chalasr's well spotted comment.

2022-12-13 11:08 UTC, nicolas-grekas commented
Thank you @adpeyre.

2022-12-13 11:09 UTC, merged