[HttpKernel] Fix empty request stack when terminating with exception
symfony/symfony pull request #47857
Opened 2022-10-13 15:42 UTC by krzyc

| Q             | A
| ------------- | ---
| Branch?       | 4.4, 5.4, 6.0, 6.1, 6.2
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #47577
| License       | MIT
| Doc PR        | 

After https://github.com/symfony/symfony/pull/47358 the RequestStack is empty when request terminates with exception, which prevents SecurityDataCollector to generate logout URL and generates fatal error.

2022-10-13 16:03 UTC, stof requested changes

2022-10-13 16:03 UTC, stof commented on src/Symfony/Component/HttpKernel/HttpKernel.php
> +        $this->requestStack->pop();
should be in a finally block

2022-10-18 12:45 UTC, VincentLanglet commented
I got the issue locally and I can confirm this PR is fixing the issue.

2022-10-18 13:04 UTC, nicolas-grekas approved these changes
I added a check to make the logic work in case of re-injected fatal errors (which means the request won't have had the opportunity to be popped)

2022-10-18 13:04 UTC, nicolas-grekas commented
Thank you @krzyc.

2022-10-18 13:05 UTC, merged