[TwigBridge] (Simple new branch for failed PR at #44464)
symfony/symfony pull request #48035
Opened 2022-10-28 20:19 UTC by DocFX

| Q             | A
| ------------- | ---
| Branch?       |  6.2
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | 
| License       | MIT
| Doc PR        | 

This is just a new PR for #44464, as previous one was merged in haste and reverted, with tests.

2022-10-29 00:08 UTC, DocFX commented
Remaining broken tests (cache & doctrine) seem to have nothing to do with this PR. Not sure I can help with that on that one.

2022-10-29 00:12 UTC, DocFX commented
@nicolas-grekas this should be a follow-up to #44464 if I got everything right. :)

2022-10-31 13:18 UTC, xabbuh requested changes
The failures on the `deps=low` job look related.

2022-10-31 17:21 UTC, DocFX commented
> The failures on the `deps=low` job look related.

Oh gosh, you're completely right, I went too fast and forgot some tests XD
Thanks @xabbuh!

2022-10-31 18:04 UTC, DocFX commented
I have a HUGE cache problem with Github... When I look at the tests here it says they're broken, even with force-refresh, no cache in browser, and with I go to "actions" page to see details, tests are OK.

Can anyone help and tell me what they see? XD

2022-11-01 09:37 UTC, xabbuh commented
https://github.com/symfony/symfony/actions/runs/3363313786/jobs/5576279353 does not fail for you?

2022-11-01 10:39 UTC, derrabus commented
Please find a PR description that tells me what the PR does. The PR description will be used as a change log entry.

2022-11-04 13:31 UTC, DocFX commented
> Please find a PR description that tells me what the PR does. The PR description will be used as a change log entry.

Sure, edited the title and description!

2022-11-04 13:34 UTC, DocFX commented
> 

That's exactly my problem, @xabbuh: this is not my code, and it's not the one from the PR.

https://github.com/symfony/symfony/pull/48035/files#diff-4125508802c9ee9145cb3e5f9c6742dad7c084623d03442c38b7cba10b8c8f09

2022-11-04 15:11 UTC, DocFX commented
(meanwhile, someone fixed the "Integration / Tests (8.1) (pull_request)" job, so this one now passes :) )

2026-08-07 08:28 UTC, nicolas-grekas commented
Closing this one. The same change was merged as #44464 on 2022-10-24 and reverted the same day (commit 88191f517e1), and this resubmission has been waiting on xabbuh's change request from 2022-10-31 ever since. Injecting a default `--` changes the rendered HTML of every application that relies on an empty placeholder option, which is why the first attempt was reverted. Thanks for the effort, and sorry it took so long to get back to you.

2026-08-07 08:28 UTC, closed without merging