The console app now can print the version even if the application name is not set
symfony/symfony pull request #48055
Opened 2022-10-31 05:57 UTC by aleksandr-shevchenko

The console application can now print the version even if the application name is not set.

$app = new Application();
$app->setVersion("1.0.585");

Before "console -V" print
Console Tool

Now "console -V" print
Console Tool 1.0.585

2022-11-01 19:42 UTC, derrabus commented
Please add a test that covers your change.

2022-11-02 05:23 UTC, aleksandr-shevchenko commented
Original code

```
    public function getLongVersion()
    {
        if ('UNKNOWN' !== $this->getName()) {
            if ('UNKNOWN' !== $this->getVersion()) {
                return sprintf('%s <info>%s</info>', $this->getName(), $this->getVersion());
            }

            return $this->getName();
        }

        return 'Console Tool';
    }
```

Tests
```
1.
$app = new Application();
// $app->setName("Test symfony/console");
// $app->setVersion("1.0.585");

2.
$app = new Application();
// $app->setName("Test symfony/console");
$app->setVersion("1.0.585");

3.
$app = new Application();
$app->setName("Test symfony/console");
// $app->setVersion("1.0.585");

4.
$app = new Application();
$app->setName("Test symfony/console");
$app->setVersion("1.0.585");
```
![ss_2022_11_02__09_13_09](https://user-images.githubusercontent.com/25248634/199404131-42f8a1f9-9e03-4930-a83c-086ad2a083dd.png)

I suggest this code

```
    public function getLongVersion()
    {
        $name = 'Console Tool';

        if ('UNKNOWN' !== $this->getName()) {
            $name = $this->getName();
        }

        if ('UNKNOWN' !== $this->getVersion()) {
            $name .= sprintf(' <info>%s</info>', $this->getVersion());
        }

        return $name;
    }
```

![ss_2022_11_02__09_13_45](https://user-images.githubusercontent.com/25248634/199404630-1548aa49-f81a-4089-920b-0d7051871f90.png)

2022-11-02 14:37 UTC, stof requested changes
This new behavior should be coverted by a test asserting `getLongVersion` for an application with only a version configured.

2022-11-02 14:37 UTC, stof commented on src/Symfony/Component/Console/Application.php
> +        $name = 'Console Tool';
I would name the variable `$longVersion` based on the method name. This variable is not only about the name

2022-12-02 11:48 UTC, fabpot commented
@aleksandr-shevchenko Can you finish this PR?

2023-08-03 06:20 UTC, fabpot commented
Closing as there is no more activity. Feel free to reopen when you have time.

2023-08-03 06:20 UTC, closed without merging