Use ??= more
symfony/symfony pull request #48069
Opened 2022-11-01 21:49 UTC by nicolas-grekas

| Q             | A
| ------------- | ---
| Branch?       | 6.2
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | -

2022-11-01 22:01 UTC, derrabus requested changes

2022-11-01 22:01 UTC, derrabus commented on src/Symfony/Bridge/PhpUnit/Legacy/ConstraintTraitForV7.php
> +        $this->exporter ??= new Exporter();
Shall we make this method a one-liner?

```php
return $this->exporter ??= new Exporter();
```

There are more methods like this one changed in this PR.

2022-11-01 22:01 UTC, derrabus commented on src/Symfony/Component/Config/Definition/Builder/ExprBuilder.php
> +        $closure ??= static function ($v) { return true === $v; };
Maybe we should browse the codebase for potential arrow functions as well. 🤔 

```suggestion
        $closure ??= static fn ($v) => true === $v;
```

But this should probably be a separate PR.

2022-11-01 22:01 UTC, derrabus commented on src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php
> +            } else$class ??= $definition->getClass();
This looks broken.

2022-11-02 08:07 UTC, nicolas-grekas commented
PR updated

2022-11-02 08:59 UTC, derrabus approved these changes

2022-11-02 09:43 UTC, fancyweb approved these changes

2022-11-02 15:21 UTC, yceruto approved these changes

2022-11-02 16:12 UTC, merged