Print the original exception message
symfony/symfony pull request #48197
Opened 2022-11-11 16:14 UTC by Tofandel

Fixes #45614

| Q             | A
| ------------- | ---
| Branch?       | 6.3 for features / 4.4, 5.4, 6.0, 6.1, or 6.2 for bug fixes 
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #45614
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

When running the `cache:warmup` command if an env var is missing we get a very obscure error message that doesn't help in tracking the issue

With this PR the original error message is displayed and allows to find the error

2022-11-11 17:11 UTC, derrabus requested changes

2022-11-11 17:11 UTC, derrabus commented on src/Symfony/Bundle/FrameworkBundle/CacheWarmer/ConfigBuilderCacheWarmer.php
> +                $this->logger?->warning('Failed to generate ConfigBuilder for extension {extensionClass}.', ['exception' => $e->getMessage(), 'extensionClass' => $extension::class]);
The `exception` context field is actually standardized in PSR-3 and reserved for exception _objects_.

It's probably fine to include the exception message in the log, but please don't repurpose that context field.

2022-11-14 09:42 UTC, nicolas-grekas approved these changes

2022-11-14 09:44 UTC, nicolas-grekas commented
Thank you @Tofandel.

2022-11-14 09:44 UTC, merged