[DependencyInjection] Fix ContainerBuilder stats env usage with enum
symfony/symfony pull request #48502
Opened 2022-12-05 20:33 UTC by alamirault

| Q             | A
| ------------- | ---
| Branch?       | 6.2
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #48498 
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

Without patch:

```php
[
    'enum:Symfony\Component\DependencyInjection\Tests\Fixtures\StringBackedEnum:foo' => 0,
    'Bar' => 1,
]
```

With patch:

```php
[
    'enum:Symfony\Component\DependencyInjection\Tests\Fixtures\StringBackedEnum:foo' => 1,
    'Bar' => 1,
]
```

2022-12-05 22:06 UTC, GromNaN approved these changes
Thank you for the test.
For reviewers, this regex was introduced by [#47176](https://github.com/symfony/symfony/pull/47176/files#diff-1d2e8c3b3187bf1dd7f3a036d0b0f6de9728d5cdc19367e361c5feef71cb8becR124)

2022-12-05 22:10 UTC, GromNaN requested changes
The regex is also in `MergeExtensionConfigurationPass`.

2022-12-06 07:41 UTC, GromNaN approved these changes

2022-12-06 07:51 UTC, nicolas-grekas commented
Looking why we forgot that in #46564, I think the correct patch is to add `\\` to the strtr on this line:
https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/DependencyInjection/ParameterBag/EnvPlaceholderParameterBag.php#L52

2022-12-06 17:09 UTC, nicolas-grekas reviewed
(I implemented the change I suggested)

2022-12-06 17:09 UTC, nicolas-grekas commented
Thank you @alamirault.

2022-12-06 17:09 UTC, merged

2022-12-06 18:03 UTC, alamirault commented
> (I implemented the change I suggested)

Thanks Nicolas :smile: