Prevent browser bfcache by default
symfony/symfony pull request #48679
Opened 2022-12-16 11:57 UTC by clemblanco

Back / forward cache seems to be a fairly recent feature browsers seem to rollout.

More information can be found here: https://web.dev/bfcache.

Long story short, when a user for example login then logout from a given application, they could then hit the "Back" button from their browser and access the login page again with the credentials pre-filled as the page would be served from the `bfcache`. This could lead to security concerns, especially on shared devices where someone could inspect the page and retrieve some user credentials.

Currently, the sensible defaults for the HTTP cache headers seem to be `no-cache, private` in order to be conservative by default. A lot of applications currently rely on this to be the sensible default for their application too.

Replacing `no-cache` by `no-store` would prevent `bfcache` to kick in from any browser and could be considered as a more secure default.

> `no-cache` shows that returned responses can't be used for subsequent requests to the same URL before checking if server responses have changed. If a proper `ETag` (validation token) is present as a result, `no-cache` incurs a roundtrip in an effort to validate cached responses. Caches can however eliminate downloads if the resources haven't changed. In other words, web browsers might cache the assets but they have to check on every request if the assets have changed (304 response if nothing has changed).

> On the contrary, `no-store` is simpler. This is the case because it disallows browsers and all intermediate caches from storing any versions of returned responses, such as responses containing private/personal information or banking data. Every time users request this asset, requests are sent to the server. The assets are downloaded every time.

More information can be found here: https://www.keycdn.com/blog/http-cache-headers#no-cache-and-no-store

The purpose of this PR is to start the discussion rather than bringing a definite solution.

2022-12-17 09:16 UTC, GromNaN requested changes
I think you modified parts of the code that are not related to the issue.

2022-12-17 09:16 UTC, GromNaN commented on src/Symfony/Component/HttpClient/EventSourceHttpClient.php
> +                'Cache-Control' => 'no-store',
This is a request header. It seems not related to the concerns of this PR.

2022-12-17 09:16 UTC, GromNaN commented on src/Symfony/Component/HttpFoundation/Request.php
> +        return $this->headers->hasCacheControlDirective('no-store') || 'no-store' == $this->headers->get('Pragma');
This method is a getter that checks if the `no-cache` instruction is sent. If `no-store` includes `no-cache` in its spec, we can add a condition. The current condition must be kept.

2022-12-17 18:21 UTC, nicolas-grekas commented
Thanks for the PR. This has been proposed and rejected before, see eg #47794.
I'm still :-1: to do this change, this is too aggressive.

2022-12-18 10:05 UTC, fabpot commented
Closing then.

2022-12-18 10:05 UTC, closed without merging