[Notifier] Add new Symfony Notifier for PagerDuty
symfony/symfony pull request #48855
Opened 2023-01-02 14:50 UTC by stloyd

| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | no
| New feature?  | yes 
| Deprecations? | no 
| License       | MIT
| Doc PR        | symfony/symfony-docs#...

2023-01-02 15:53 UTC, OskarStark approved these changes

2023-01-05 06:39 UTC, fabpot requested changes

2023-01-05 06:39 UTC, fabpot commented on src/Symfony/Component/Notifier/Bridge/PagerDuty/composer.json
> +    "name": "symfony/pagerduty-notifier",
```suggestion
    "name": "symfony/pager-duty-notifier",
```

2023-01-05 06:39 UTC, fabpot commented on src/Symfony/Component/Notifier/Exception/UnsupportedSchemeException.php
> +            'package' => 'symfony/pagerduty-notifier',
```suggestion
            'package' => 'symfony/pager-duty-notifier',
```

2023-01-05 08:07 UTC, fabpot approved these changes

2023-01-08 15:24 UTC, fabpot commented
Thank you @stloyd.

2023-01-08 15:24 UTC, merged