Draft: First draft of adding Enum Support to Workflow component
symfony/symfony pull request #48919
Opened 2023-01-08 16:40 UTC by bartrail

| Q             | A
| ------------- | ---
| Branch?       | 6.3 
| Bug fix?      | no
| New feature?  | yes 
| Deprecations? | no
| Tickets       | Fix #44211
| License       | MIT
| Doc PR        | symfony/symfony-docs#...

2023-01-09 00:41 UTC, derrabus requested changes

2023-01-09 00:41 UTC, derrabus commented on src/Symfony/Component/Workflow/Definition.php
> +     * @return Place[]
Switching from strings to your new class everywhere will break a lot of applications that currently use the component. You'll need to find another way.

2023-01-09 05:17 UTC, OskarStark commented
This was rejected in the past. I don't have the PR/issue at hand

2023-01-09 05:50 UTC, derrabus commented
> This was rejected in the past. I don't have the PR/issue at hand

#44211, the issue is linked in the PR description. 🙂 

The issue was closed after @lyrixx' assessment that implementing the feature is not worth the effort. A good PR could prove the opposite.

2023-01-09 09:30 UTC, OskarStark commented
Sorry, I overlooked the referenced issue. 

> A good PR could prove the opposite.

Sure, go ahead then 👍

2023-01-09 09:42 UTC, stof commented
This PR contains lots of BC breaks, and so it is a no-go as is. That's one of the reason why @lyrixx assessed that the feature is probably not worth the effort: you did less than half of the effort for now.
Side note: using `UnitEnum::$name` as fallback for `BackedEnum::$value` when an enum is not backed does not make sense. Names and values are not the same concept (and this probably indicates a bad integration of enums in the component)

2023-01-09 10:06 UTC, bartrail commented
> This PR contains lots of BC breaks, and so it is a no-go as is. That's one of the reason why @lyrixx assessed that the feature is probably not worth the effort: you did less than half of the effort for now. Side note: using `UnitEnum::$name` as fallback for `BackedEnum::$value` when an enum is not backed does not make sense. Names and values are not the same concept (and this probably indicates a bad integration of enums in the component)

I just opened the PR as _draft_ so nothing is finished for now :) I am sure aware of the BC breaks and most of the tests are failing. So I will have a closer look at the BC concerns.

Regarding the `UnitEnum` vs `BackedEnum` case, I have started with `UnitEnum` as the least common denominator, but realised quick that it requires some custom code in the used Enum which feels a bit clunky. I would suggest using `BackedEnum` because it's more feasible.

2023-02-22 10:51 UTC, lyrixx commented
Hello, Thanks for the effort, But I'm going to close this PR for the reason explained.

But don't hesitate to re-open when finish / ready.

2023-02-22 10:51 UTC, closed without merging