Add ReStructuredText descriptor for console component
symfony/symfony pull request #48981
Opened 2023-01-14 18:11 UTC by danepowell

| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #45717
| License       | MIT
| Doc PR        | n/a, descriptors are internal and not documented.

### Description

The console component currently has descriptors for Markdown, Json, etc. This feature would add Restructured Text descriptor (rst) as an option.

This replaces and addresses all feedback from #45718

### Example

```
$helper = new DescriptorHelper();
$helper->describe($output, $this->getApplication(), [
  'format' => 'rst',
]);
```

2023-01-14 18:42 UTC, danepowell commented
I don't understand the Psalm failure. It doesn't seem related to this PR.

2023-01-20 20:58 UTC, danepowell commented
@fabpot mind reviewing this since you approved the last one?

2023-01-21 06:35 UTC, fabpot requested changes

2023-01-21 06:35 UTC, fabpot commented on composer.json
> +        "ext-iconv": "*"
I would remove the dep here and use the String component instead when you've used `iconv`.

2023-01-21 06:35 UTC, fabpot commented on src/Symfony/Component/Console/Descriptor/ReStructuredTextDescriptor.php
> +    private string $partChar = '#';
Let's be consistent with what we are using in the docs:

h1 =====
h2 -----
h3 ~~~~~
h4 .....

2023-01-21 06:35 UTC, fabpot commented on src/Symfony/Component/Console/Tests/Descriptor/AbstractDescriptorTest.php
> +        $this->assertEquals($expected, $actual);
Should be reverted as the code is semantically the same.

2023-01-23 17:38 UTC, danepowell commented
Thanks for the review, all feedback addressed, this is good to go.

Tests are failing in HEAD, so probably not related to this PR. I think every PR I've opened has had failures of this nature.

Have you thought about using branch protections to prevent PRs / commits with failing tests from being merged?

2023-01-26 13:54 UTC, nicolas-grekas commented on src/Symfony/Component/Console/Descriptor/ReStructuredTextDescriptor.php
> +     * @param \Symfony\Component\Console\Descriptor\ApplicationDescription $description
should be removed

2023-01-26 13:54 UTC, nicolas-grekas commented on src/Symfony/Component/Console/Descriptor/ReStructuredTextDescriptor.php
> +     * @param \Symfony\Component\Console\Descriptor\ApplicationDescription $description
should be removed

2023-01-26 14:05 UTC, nicolas-grekas reviewed
I only have CS fixes to suggest :)

2023-01-26 14:05 UTC, nicolas-grekas commented on src/Symfony/Component/Console/Descriptor/ReStructuredTextDescriptor.php
> +                $namespace_commands = $namespace['commands'];
we use camel case: `$namespaceCommands`

2023-01-26 14:05 UTC, nicolas-grekas commented on src/Symfony/Component/Console/Descriptor/ReStructuredTextDescriptor.php
> +                if (!\count($namespace_commands)) {
`if (!$namespaceCommands) {`

2023-01-26 14:05 UTC, nicolas-grekas commented on src/Symfony/Component/Console/Descriptor/ReStructuredTextDescriptor.php
> +use Exception;
should be replaced by inline `\Exception`

2023-01-26 14:05 UTC, nicolas-grekas commented on src/Symfony/Component/Console/Descriptor/ReStructuredTextDescriptor.php
> +        // Remove aliases.
should be removed, the name of the method says it already

2023-01-26 14:05 UTC, nicolas-grekas commented on src/Symfony/Component/Console/Descriptor/ReStructuredTextDescriptor.php
> +            // @todo Show these once at the beginning.
let's do it?

2023-01-26 14:05 UTC, nicolas-grekas commented on src/Symfony/Component/Console/Descriptor/ReStructuredTextDescriptor.php
> +        $global_options = [
camel case

2023-01-26 14:05 UTC, nicolas-grekas commented on src/Symfony/Component/Console/Descriptor/ReStructuredTextDescriptor.php
> +                $non_default_options[] = $option;
camel case

2023-01-26 14:05 UTC, nicolas-grekas commented on src/Symfony/Component/Console/Descriptor/ReStructuredTextDescriptor.php
> +            $this->write(implode("\n", array_map(static function ($commandName) {
`static fn ($commandName) => sprintf('- `%s`_', $commandName)`

2023-01-26 14:05 UTC, nicolas-grekas commented on src/Symfony/Component/Console/Descriptor/ReStructuredTextDescriptor.php
> +        $describedNamespace = $options['namespace'] ?? null;
no need for the tmp variable

2023-01-26 14:05 UTC, nicolas-grekas commented on src/Symfony/Component/Console/Descriptor/ReStructuredTextDescriptor.php
> +        $option_description = (new UnicodeString($option_description))->ascii();
camel case

2023-01-26 14:05 UTC, nicolas-grekas commented on src/Symfony/Component/Console/Descriptor/ReStructuredTextDescriptor.php
> +        if ($showArguments = (\count($definition->getArguments()) > 0)) {
`if ($showArguments = (bool) $definition->getArguments()) {`

2023-01-26 14:05 UTC, nicolas-grekas commented on src/Symfony/Component/Console/Descriptor/ReStructuredTextDescriptor.php
> +        $non_default_options = $this->getNonDefaultOptions($definition);
camel

2023-01-26 14:05 UTC, nicolas-grekas commented on src/Symfony/Component/Console/Descriptor/ReStructuredTextDescriptor.php
> +        if (\count($non_default_options) > 0) {
`if ($nonDefaultOptions = $this->getNonDefaultOptions($definition)) {`

2023-01-26 14:05 UTC, nicolas-grekas commented on src/Symfony/Component/Console/Descriptor/ReStructuredTextDescriptor.php
> +                .array_reduce($command->getAliases(), static function ($carry, $usage) {
`static fn ($carry, $usage) => ...`

2023-01-26 14:05 UTC, nicolas-grekas commented on src/Symfony/Component/Console/Descriptor/ReStructuredTextDescriptor.php
> +            .array_reduce(array_merge([$command->getSynopsis()], $command->getAliases(), $command->getUsages()), static function ($carry, $usage) {
`fn (...) => ...`

2023-01-26 14:05 UTC, nicolas-grekas commented on src/Symfony/Component/Console/Descriptor/ReStructuredTextDescriptor.php
> +        if ('UNKNOWN' !== $application->getName()) {
```php
if ('UNKNOWN' === $application->getName()) {
    return 'Console Tool';
}
```

2023-01-26 14:05 UTC, nicolas-grekas commented on src/Symfony/Component/Console/Descriptor/ReStructuredTextDescriptor.php
> +            foreach ($commands as $command) {
`foreach ($this->removeAliasesAndHiddenCommands($commands) as $command) {`

2023-01-26 14:05 UTC, nicolas-grekas commented on src/Symfony/Component/Console/Descriptor/ReStructuredTextDescriptor.php
> +        $chapter_title = 'Table of Contents';
camel

2023-01-26 14:05 UTC, nicolas-grekas commented on src/Symfony/Component/Console/Descriptor/ReStructuredTextDescriptor.php
> +                foreach ($namespace_commands as $key => $command_name) {
`$commandName`

2023-01-26 14:05 UTC, nicolas-grekas commented on src/Symfony/Component/Console/Descriptor/ReStructuredTextDescriptor.php
> +            } catch (Exception) {
`\Exception`

2023-01-26 20:24 UTC, danepowell commented
Thanks for the feedback, all comments addressed.

2023-02-01 13:52 UTC, anavarre commented
Is there anything else missing here?

2023-02-02 06:54 UTC, fabpot approved these changes

2023-02-02 06:55 UTC, fabpot commented
Thank you @danepowell.

2023-02-02 06:55 UTC, closed without merging

2023-02-10 15:27 UTC, fabpot commented
@danepowell Would you be interested in supporting restructuredtext in `src/Symfony/Bundle/FrameworkBundle/Console/Descriptor/` as well?

2023-02-10 16:03 UTC, danepowell commented
I only build console apps and actively avoid the Framework bundle because of all the web-specific bulk. So I don't have an interest in adding to it.