[DoctrineBridge] fix issue with missing stopwatch events
symfony/symfony pull request #49079
Opened 2023-01-23 16:38 UTC by dmaicher

| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix https://github.com/doctrine/DoctrineBundle/issues/1622
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

This fixes https://github.com/doctrine/DoctrineBundle/issues/1622

We were not triggering the stopwatch events/sections properly when using prepared statements.

Now it works:

![image](https://user-images.githubusercontent.com/921145/214097708-2986e3c9-262e-4b7e-903e-9b7e0dda208e.png)

![image](https://user-images.githubusercontent.com/921145/214097936-67948cb3-63ad-4eff-b53e-f8ff9e12a7f0.png)

2023-01-24 08:45 UTC, javiereguiluz commented on src/Symfony/Bridge/Doctrine/Tests/Middleware/Debug/MiddlewareTest.php
> -        $product = 'product2';
Why were these lines removed? Thanks

2023-01-24 08:52 UTC, dmaicher commented on src/Symfony/Bridge/Doctrine/Tests/Middleware/Debug/MiddlewareTest.php
> -        $product = 'product2';
unused variables

2023-02-08 09:41 UTC, dmaicher commented
@stof maybe you have some time to review this?

2023-02-15 13:02 UTC, maxhelias approved these changes

2023-03-25 09:38 UTC, fabpot requested changes
Minor CS comments

2023-03-25 09:38 UTC, fabpot commented on src/Symfony/Bridge/Doctrine/Middleware/Debug/Statement.php
> +        if (null !== $this->stopwatch) {
```suggestion
        if ($this->stopwatch) {
```

2023-03-25 09:38 UTC, fabpot commented on src/Symfony/Bridge/Doctrine/Middleware/Debug/Statement.php
> +            if (null !== $this->stopwatch) {
```suggestion
            if ($this->stopwatch) {
```

2023-03-25 09:38 UTC, fabpot commented on src/Symfony/Bridge/Doctrine/Middleware/Debug/Connection.php
> +            $this->stopwatch
```suggestion
            $this->stopwatch,
```

2023-04-05 05:18 UTC, fabpot approved these changes

2023-04-05 05:19 UTC, fabpot commented
Thank you @dmaicher.

2023-04-05 05:20 UTC, closed without merging