Introduce Symfony StoppableEventInterface
symfony/symfony pull request #49101
Opened 2023-01-25 13:06 UTC by VincentLanglet

| Q             | A
| ------------- | ---
| Branch?       | 6.3 for features
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #... instead -->
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

The StoppableEventInterface from Psr only provide a 
```
public function isPropagationStopped(): bool
```
method, but there is no interface for the 
```
public function stopPropagation(): void
```
method provided in the Event class.

From https://github.com/symfony/symfony/issues/9539, the Event is a value object and no EventInterface should be provided.

But if someone want to create a specific interface for event with more methods:
```
interface MyEventInterface extends PsrStoppableEventInterface
{
     public function getUser(): ?User;
}
```
because he need to have a getUser method on every events, 
then he cannot call `stopPropagation` on it without static analysis errors ; unless doing
```
interface MyEventInterface extends PsrStoppableEventInterface
{
     public function getUser(): ?User;

     public function stopPropagation(): void;
}
```

If Symfony provide a `StoppableEventInterface` with the `stopPropagation` in it, it solve this issue.

2023-01-25 13:11 UTC, stof requested changes

2023-01-25 13:11 UTC, stof commented on src/Symfony/Contracts/EventDispatcher/StoppableEventInterface.php
> +    public function stopPropagation(): void;
This method must have some phpdoc describing it (the one that is currently in the Event class)

2023-01-25 13:29 UTC, VincentLanglet commented on src/Symfony/Contracts/EventDispatcher/StoppableEventInterface.php
> +    public function stopPropagation(): void;
Indeed.
I moved the Phpdoc (or do you want it in the two classes ?)

2023-01-25 13:42 UTC, stof commented on src/Symfony/Contracts/EventDispatcher/StoppableEventInterface.php
> +    public function stopPropagation(): void;
As the other method is now the implementation of this interface method, it is fine to move it.

2023-01-25 13:42 UTC, stof approved these changes

2023-01-25 18:02 UTC, derrabus approved these changes

2023-01-25 18:29 UTC, nicolas-grekas commented
>  then he cannot call stopPropagation on it without static analysis errors ; unless doing

There is another way, which is using `MyEventInterface&PsrStoppableEventInterface` as a type.
And another, which is creating your own Event VO that extends the base one and declares `MyEventInterface`.

Wouldn't that solve your problem with SA?

2023-01-25 23:37 UTC, VincentLanglet commented
> > then he cannot call stopPropagation on it without static analysis errors ; unless doing
> 
> There is another way, which is using `MyEventInterface&PsrStoppableEventInterface` as a type. 

No really, since stopPropagation is not in PsrStoppableEventInterface, but `MyEventInterface&Event` would solve the issue.
I just thought it could be nice to provide an interface to directly rely on instead on using `MyEventInterface&Event` everywhere.

> And another, which is creating your own Event VO that extends the base one and declares `MyEventInterface`.
> 
> Wouldn't that solve your problem with SA?

Since the implementation of MyEventInterface are not the same for different events, it would require having `MyOwnEvent` an abstract class and then using an abstract class everywhere as a typehint. I thought this was better to use an interface as typehint rather than Abstract class.

2023-01-26 09:49 UTC, nicolas-grekas commented
Honeslty, I'm not convinced this is needed nor that it would be useful. As stated, this doesn't make much difference for userland, and at the abstraction level, the Event VO is really fine as an implementation. I don't really like interfaces for data structures so I'm "-0" here.

2023-01-27 11:26 UTC, chalasr commented
I'm -1 here for the reasons pointed by Nicolas above.

2023-01-27 15:16 UTC, nicolas-grekas commented
Thanks for proposing.

2023-01-27 15:16 UTC, closed without merging