Detect unused environment variables in .env
symfony/symfony pull request #49161
Opened 2023-01-30 20:35 UTC by mw3e21a

| Q             | A
| ------------- | ---
| Branch?       | 6.3 
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #48552-->
| License       | MIT
| Doc PR        | [symfony/symfony-docs#... ](https://github.com/symfony/symfony-docs/pull/17833)

 Improved `bin/console debug:container --env-vars` and the `--env-var` option to display the number of occurrences of each environment variable in the container. This allows you to identify unused variables from .env files.

Example usage:
`php bin/console debug:container --env-vars`

![image](https://user-images.githubusercontent.com/24555839/215588820-375295c8-0003-49f1-be96-8caa15755594.png)

`php bin/console debug:container --env-var=APP_SECRET`

![image](https://user-images.githubusercontent.com/24555839/215588970-81f3cf3e-4e58-4c36-bb38-f13b7fb5f105.png)

2023-01-30 21:11 UTC, GromNaN reviewed
I like this way of demonstrating usage of each variable. 

Here is the output for `symfony/demo`. We can see that `APP_ENV` is not used by the container (because it is used earlier).
```console
$ bin/console debug:container --env-vars

Symfony Container Environment Variables
=======================================

 ------------------- ------------------ ------------------------------------------------------- ------------- 
  Name                Default value      Real value                                              Usage count  
 ------------------- ------------------ ------------------------------------------------------- ------------- 
  APP_ENV             n/a                "dev"                                                   n/a          
  APP_SECRET          n/a                "2ca64f8d83b9e89f5f19d672841d6bb8"                      8            
  DATABASE_URL        n/a                "sqlite:///%kernel.project_dir%/data/database.sqlite"   1            
  VAR_DUMPER_SERVER   "127.0.0.1:9912"   n/a                                                     3            
 ------------------- ------------------ ------------------------------------------------------- ------------- 

 // Note real values might be different between web and CLI.                                                            
```

2023-01-30 21:11 UTC, GromNaN commented on src/Symfony/Bundle/FrameworkBundle/Console/Descriptor/TextDescriptor.php
> +                        ['<info>Usage count</>', $env['usage_count'] ? $dump($env['usage_count']) : 'n/a'],
For a count, `0` is correct.
```suggestion
                        ['<info>Usage count</>', $dump($env['usage_count'])],
```

2023-01-30 21:11 UTC, GromNaN commented on src/Symfony/Bundle/FrameworkBundle/Console/Descriptor/TextDescriptor.php
> +                $env['usage_count'] ? $dump($env['usage_count']) : 'n/a',
Same here.
```suggestion
                $dump($env['usage_count']),
```

2023-02-01 19:33 UTC, mw3e21a commented
@GromNaN  Thanks for the suggestions, I made changes in the code.

2023-02-02 10:06 UTC, GromNaN requested changes

2023-02-02 10:06 UTC, GromNaN commented on src/Symfony/Bundle/FrameworkBundle/Console/Descriptor/Descriptor.php
> +            $envs = $dotenv->parse(file_get_contents($file), $file);
You don't need to find and parse all the env files. `SYMFONY_DOTENV_VARS` already contains all the variables read by `Dotenv`.

https://github.com/symfony/symfony/blob/acb7a989976f5f88cf745e9580a4ece23d65e12a/src/Symfony/Component/Dotenv/Command/DebugCommand.php#L152-L158

Note that the `.env` file names can be customized with the [runtime options](https://symfony.com/doc/current/components/runtime.html#using-options) `dotenv_path`.

2023-02-02 13:51 UTC, GromNaN requested changes
Yet an other review, sorry it's so fragmented on my part.

2023-02-02 13:51 UTC, GromNaN commented on src/Symfony/Bundle/FrameworkBundle/Tests/Functional/ContainerDebugCommandTest.php
> +        (new Dotenv())->bootEnv(__DIR__.'/app/.env');
Instead of writing the `.env` files, you can simulate the behavior of `Dotenv` by setting the var `SYMFONY_DOTENV_VARS`.

2023-02-02 13:51 UTC, GromNaN commented on src/Symfony/Bundle/FrameworkBundle/Tests/Functional/ContainerDebugCommandTest.php
> +  JSON                          "[1, "2.5", 3]"   n/a                    1%w
I see 2 usages of `JSON` in the config. https://github.com/symfony/symfony/pull/49161/files#diff-9aad08d07b3694cbc7c5e0edf48e28ee4f47122f7ae6559e337c3df7e2ea7b2eR34-R35

2023-02-06 15:31 UTC, mw3e21a commented on src/Symfony/Bundle/FrameworkBundle/Tests/Functional/ContainerDebugCommandTest.php
> +  JSON                          "[1, "2.5", 3]"   n/a                    1%w
Thank you, I didn't notice it :)

2025-06-27 12:12 UTC, ibtissem13 commented
Will this change be added soon?

2025-09-22 06:11 UTC, fabpot requested changes

2025-09-22 06:11 UTC, fabpot commented on src/Symfony/Bundle/FrameworkBundle/CHANGELOG.md
> + * Improved `bin/console debug:container --env-vars` and the `--env-var` option to display the number of occurrences of each environment variable in the container.
```suggestion
 * Improved `bin/console debug:container --env-vars` and the `--env-var` option to display the number of occurrences of each environment variable in the container
```

2025-09-22 06:11 UTC, fabpot commented on src/Symfony/Bundle/FrameworkBundle/CHANGELOG.md
> + * Improved `bin/console debug:container --env-vars` and the `--env-var` option to display the number of occurrences of each environment variable in the container.
To be moved to a new 7.4 section

2025-09-22 06:11 UTC, fabpot commented on src/Symfony/Bundle/FrameworkBundle/Tests/Functional/ContainerDebugCommandTest.php
> +        $_SERVER['SYMFONY_DOTENV_VARS'] = 'APP_FOO,APP_BAR,APP_BAZ';
This needs to be reverted at the end of the test.

2025-09-22 06:11 UTC, fabpot commented on src/Symfony/Bundle/FrameworkBundle/Console/Descriptor/Descriptor.php
> +        $containerFile = file_get_contents($container->getParameter('debug.container.dump'));
```suggestion
        $file = file_get_contents($container->getParameter('debug.container.dump'));
```

2025-09-22 06:11 UTC, fabpot commented on src/Symfony/Bundle/FrameworkBundle/Console/Descriptor/Descriptor.php
> +        preg_match_all('{%env\(((?:\w++:)*+\w++)\)%}', $containerFile, $envVarsFromContainer);
```suggestion
        preg_match_all('{%env\(((?:\w++:)*+\w++)\)%}', $file, $envVars);
```

2025-09-22 06:11 UTC, fabpot commented on src/Symfony/Bundle/FrameworkBundle/Console/Descriptor/Descriptor.php
> +            preg_match_all('/'.preg_quote($env).'/', $containerFile, $matches);
```suggestion
            preg_match_all('/'.preg_quote($env).'/', $file, $matches);
```

2025-09-22 06:11 UTC, fabpot commented on src/Symfony/Bundle/FrameworkBundle/Console/Descriptor/Descriptor.php
> +        $envVarsFromContainer = [];
Let's not rename variables to make review easier.

```suggestion
        $envVars = [];
```

2025-09-22 06:11 UTC, fabpot commented on src/Symfony/Bundle/FrameworkBundle/Console/Descriptor/Descriptor.php
> +        $envVarsFromContainer = array_unique($envVarsFromContainer[1]);
```suggestion
        $envVars = array_unique($envVars[1]);
```

2025-09-22 06:11 UTC, fabpot commented on src/Symfony/Bundle/FrameworkBundle/Console/Descriptor/Descriptor.php
> +        foreach ($allEnvVars as $env) {
```suggestion
        foreach ($envVars as $env) {
```

2026-06-19 12:49 UTC, GromNaN approved these changes
I rebased the branch on top of 8.2 and applied the requested changes.

2026-06-19 13:01 UTC, GromNaN approved these changes

2026-07-28 05:45 UTC, nicolas-grekas commented
I have rewritten the implementation on this branch. Thanks @mw3e21a for the original and @GromNaN for the rebase and the review round; the shape of the feature and the `SYMFONY_DOTENV_VARS` idea are both yours and both kept.

What changed and why.

**The usage count is gone, because it could not be made right.** It was `preg_match_all('/'.preg_quote($env).'/', $file)` over the whole XML dump, which is a substring scan rather than a count of references. Measured on a probe container:

| variable | reported | real |
|---|---|---|
| a variable with only an `env()` default and no reader | 1 | 0 |
| `PROBE_SUB`, referenced nowhere, prefix of `PROBE_SUB_LONG` | 3 | 0 |
| `MIXED`, used bare and through `int:` | 3 | 2 |
| `debug` | 308 | 1 |

Realistic collisions are `DATABASE_URL` against `DATABASE_URL_REPLICA` and `APP_SECRET` against `APP_SECRET_KEY`. The fixture in the first version also asserted `APP_FOO ... 1` for a variable no service reads, so the wrong number was pinned as expected output.

Fixing the arithmetic would not have been enough, because a count cannot answer the question anyway. `PhpDumper::dump()` already refuses to compile a container that declares an environment variable nothing reads:

```php
foreach ($this->container->getEnvCounters() as $env => $use) {
    if (!$use) { $unusedEnvs[] = $env; }
}
if ($unusedEnvs) { throw new EnvParameterException($unusedEnvs, ...); }
```

So in any container that compiles, every tracked variable is used, and a count column can only ever print numbers greater than zero. The genuinely unused `.env` variables are not in the container at all. The feature is a set difference, not a count, which is why the column is now `Used` and reads `yes` or `no`.

**The list now comes from the compiler.** `ContainerBuilderDebugDumpPass` writes `array_keys($container->getEnvCounters())` into the debug dump, and the descriptor reads it from there instead of re-parsing the XML. The declaration-versus-use distinction then comes for free: a bare `parameters: env(FOO): 'x'` never registers a placeholder, so it never appears as used.

**The empty `SYMFONY_DOTENV_VARS` case is fixed.** `explode(',', '')` returns `['']`, so the empty name was merged into the list and `preg_quote('')` produced the pattern `//`, which matches at every byte offset. Without Dotenv the table gained a nameless row with a count equal to the dump length, plus a `[WARNING] The following variables are missing:` with an empty bullet. That is the default path for anyone not using `symfony/dotenv`, and no test covered it. There is one now, `testDescribeEnvVarsWithoutDotenv`.

**Two things the old regex was hiding.** `{%env\(((?:\w++:)*+\w++)\)%}` requires the chain to end on a word, and allows neither `::` nor `.`, so it silently skipped every `default:` placeholder. Two consequences, both visible now:

* variables the framework itself reads, such as `SYMFONY_TRUSTED_PROXIES`, `SYMFONY_IDE` and `APP_RUNTIME_ENV`, were never listed although the container does read them. They are listed now;
* a chain ending on the separator, such as `not:default:kernel.runtime_mode.web:`, has no variable name. Those are filtered out rather than rendered as a nameless row.

Since those framework variables are normally unset, they would have filled the missing-variables warning with noise, so a variable whose chain carries a `default` processor is no longer reported as missing. The fallback is the reason that processor exists.

**Test changes.** `testDescribeEnvVar` went back to `assertStringContainsString`: the switch to `assertStringEqualsFile` against a fixture padded to 120 columns made it depend on terminal width, and it failed at the default 80 that a non-tty run gets, passing on CI only because that runner reports a wide terminal. The table assertions are now targeted rather than whole-output, because listing the framework variables makes a full-table match depend on whatever `SYMFONY_IDE` and friends happen to be set to on the machine running the suite. The environment cleanup @fabpot asked for is now in a `finally`, so a failing assertion no longer leaks `SYMFONY_DOTENV_VARS` and four `putenv()` values into every test that follows in the same process.

Revert-verify: restoring only the empty-name filter and leaving everything else in place makes `testDescribeEnvVarsWithoutDotenv` fail on its first assertion, the one that checks no nameless row is printed. Full `FrameworkBundle` suite is green, 1406 tests and 4704 assertions, and the env var tests pass at `COLUMNS` of 80, 120 and 200.

One thing to sort out separately: `configuration.rst` documents the `Usage count` column on the `6.4`, `7.4` and `8.1` branches, from symfony/symfony-docs#17833 merged in December 2023, for a feature that has never shipped. Worth removing from those branches regardless of what happens here.

2026-07-28 06:44 UTC, nicolas-grekas commented
Thank you @mw3e21a.

2026-07-28 06:44 UTC, merged