42948 reduce response constraints verbosity
symfony/symfony pull request #49184
Opened 2023-02-01 11:41 UTC by Nicals

| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #42948
| License       | MIT
| Doc PR        | 

Adds a `verbose` argument to HttpFoundation response test constraints.
If set to false, only the HTTP response command and headers will be displayed in case of test failure.

This argument is `true` by default to keep backward compatibility, but I think it would make more sense to be `false`.

I added a method `Symfony\Component\HttpFoundation\Response::getCommandString()` that builds the first line of an HTTP response to avoid code duplication in constraints classes.
I thought of other solutions:

  +  Build the HTTP command line in each `Constraint`. This seems that too much code duplication.
  + Add an `AbstractResponseConstraint` with a utility method to build a less verbose response string. I wasn't sure we needed to add an extend layer here.
  + Add a `ResponseConstraintTrait` with an exposed method to build the less verbose response string. This did not *feel* right.

Overall, I think the `Response` class is the more appropriate to build this string.

2023-03-16 21:45 UTC, GromNaN commented
Hi there! Thank you for submitting this pull request and for all the hard work you put into it. I appreciate your effort and dedication to improving this project.

However, after reviewing your changes, I'm not entirely sure if your solution is necessary or if using [`$client->catchExceptions(false);`](https://symfony.com/doc/6.3/testing.html#reporting-exceptions) might already achieve the same result.

2023-04-17 09:21 UTC, Nicals commented
Catching exception effectively reduces the verbosity.

This PR intends to reduces the verbosity of test logs in all cases.

For example, a failed assertion about response status code will dump the entire response, including body.
When debugging such assertion I want to see the actual response status code, but this information is in the response header, hundreds of lines above the tail of the unit test logs.
Exception catching is not the issue in this case.

2023-08-01 08:44 UTC, fabpot requested changes

2023-08-01 08:44 UTC, fabpot commented on src/Symfony/Component/HttpFoundation/Response.php
> +    public function getCommandString(): string
I don't think this is something we want to expose in the public API.

2024-02-03 17:47 UTC, fabpot commented
@Nicals Are you still interesting in finishing this PR?

2024-02-04 11:55 UTC, Nicals commented
@fabpot I totally forgot about this MR. I don't work with php/symfony anymore so I did not keep track of it.

I quickly rebased this branch on up to date 7.1 and built the response headers manually.

2024-03-17 15:31 UTC, fabpot approved these changes

2024-03-17 16:31 UTC, fabpot commented
Thank you @Nicals.

2024-03-17 16:32 UTC, merged