Fix Autocomplete setData
symfony/symfony pull request #49190
Opened 2023-02-01 16:34 UTC by Aziz403

| Q             | A
| ------------- | ---
| Branch?       | 6.2 
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix [#(https://github.com/symfony/ux/issues/667)] 
| License       | MIT

Bypass autocomplete field check the viewData

2023-02-01 19:49 UTC, yceruto requested changes
> The form's view data is expected to be a "App\Entity\Reference", but it is a "string". You can avoid this error by setting the "data_class" option to null or by adding a view transformer that transforms "string" to an instance of "App\Entity\Reference". 

Resolving your issue can be achieved by following one of the two options outlined in that error message. Or you should pass an instance of `App\Entity\Reference` as `data` value instead of an string.

2023-02-01 19:49 UTC, yceruto commented on src/Symfony/Component/Form/Form.php
> +            if (null !== $dataClass && !$viewData instanceof $dataClass && $this->name !=='autocomplete') {
This change appears to be incorrect as the name of the form field is an arbitrary value.

2023-02-01 22:00 UTC, Aziz403 commented
> Resolving your issue can be achieved by following one of the two options outlined in that error message. Or you should pass an instance of `App\Entity\Reference` as `data` value instead of an string.

its not about the exception, in this is situation shouldn't throw the error!
its a exception when using `ux-autocomplete`, we need to bypass check `$dataClass`.
check [this](https://github.com/https://github.com/symfony/ux/issues/667)

2023-02-01 22:57 UTC, derrabus commented
Very well, but what you're doing here is you change a very generic form class and add a special case for a very specific control. I strongly believe that there has to be a better way to address your problem.

Oh, and we always need a test that covers your change.

2023-02-02 10:13 UTC, Aziz403 commented
You convinced me, and wow! I found a better solution that doesn't need to modify symfony/form.

2023-02-02 10:13 UTC, closed without merging