[HttpKernel] [Profiler] fix research feature
symfony/symfony pull request #49316
Opened 2023-02-09 13:51 UTC by Pelagoss

| Q             | A
| ------------- | ---
| Branch?       |  5.4 
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | -

This fix research feature in the profiler. The break condition was wrong.

2023-03-05 11:10 UTC, alamirault requested changes
Thanks for your PR @Pelagoss 

Can you update or add a new test, in order to confirm fix and avoid regression in future ?

https://github.com/symfony/symfony/blob/10c73d3a9394eb3730704588af935360ac598703/src/Symfony/Component/HttpKernel/Tests/Profiler/FileProfilerStorageTest.php#L347-L360

2023-03-25 09:30 UTC, fabpot approved these changes

2023-03-30 06:35 UTC, javiereguiluz commented
Thanks @Pelagoss.

I've tested this locally ... and didn't work for me. First, I tried the search without this change: it works as expected. Then, I did this change to my local app ... and the search feature broke. Now I can't find any result.

I know the change of this PR looks intuitive, but for me it broke the profiler search. Can anyone please confirm this? Maybe I'm doing something wrong. Thanks!

2023-03-30 13:51 UTC, nicolas-grekas commented
This doesn't look to me either. The description of the method says we skip empty lines, which is what the current code does.

2023-03-30 13:52 UTC, nicolas-grekas commented
Closing as this can't be the fix.

2023-03-30 13:52 UTC, closed without merging