Add dependency on symfony/polyfill-intl-icu to symfony/translation
symfony/symfony pull request #49609
Opened 2023-03-06 05:06 UTC by larowlan

| Q             | A
| ------------- | ---
| Branch?       | 6.2
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | N/a - see below
| License       | MIT
| Doc PR        | n/a

In #45793 a new LocaleSwitcher was added which uses the \Locale class from ext-intl.
On upgrading an English only project from 5.4 to 6.2, I received the following error as we don't have the ext-intl extension

```
Error: Class "Locale" not found
```

I searched for previous PRs to add a dependency on `ext-intl` and [came across one](https://github.com/symfony/symfony/issues/49280) for the string component directing the user to install a polyfill.

Should symfony/translation therefore depend on the polyfill - otherwise updating is broken without manually installing the polyfill?

If so, here's a PR for that.

Keep up the good work folks :heart:

2023-03-06 08:34 UTC, derrabus approved these changes
Sounds reasonable to me.

2023-03-06 08:37 UTC, nicolas-grekas commented
What about wrapping the call to `\Locale::setLocale()` in a `class_exists()` check instead?

2023-03-06 08:49 UTC, derrabus commented
> What about wrapping the call to `\Locale::setLocale()` in a `class_exists()` check instead?

You mean `\Locale::setDefault()`? You're right, if there's no `Locale` class, there's no reason to mutate the default locale here. And the locale switcher would work very well without it.

Let's do that instead.

2023-03-06 20:18 UTC, larowlan commented
No worries, will update

2023-03-07 07:01 UTC, derrabus requested changes

2023-03-07 07:01 UTC, derrabus commented on src/Symfony/Component/Translation/LocaleSwitcher.php
> +            \Locale::setDefault($this->locale = $locale);
I think, you'll have to move the assignment out of the `if` block now.

2023-03-07 07:21 UTC, nicolas-grekas approved these changes
I fixed @derrabus comment

2023-03-07 07:21 UTC, nicolas-grekas commented
Thank you @larowlan.

2023-03-07 07:21 UTC, merged

2023-03-07 07:24 UTC, larowlan commented
Oh right I missed it was assigning too 🙂

Thanks!