[Serializer] CsvEncoder: allow the nested array parsing to be disabled
symfony/symfony pull request #49692
Opened 2023-03-15 15:54 UTC by Deuchnord

| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | N/A
| License       | MIT
| Doc PR        | _doing it ASAP_ 

By default, `CsvEncoder` decoding process explodes the headers automatically based on the `.` character to generate nested arrays, the separation character being configurable based on our needs. For instance:

```csv
username,birth.day,birth.month,birth.year
deuchnord,9,6,1993
```

Would result in the following PHP array:

```php
[
    "username" => "deuchnord",
    "birth" => [
        "day" => 9,
        "month => 6,
        "year" => 1993
    ]
]
```

This is a very nice feature, but in some cases, we prefer to skip the generation of those nested arrays.
This PR provides a way to disable it by simply setting the already existent `CsvEncoder::KEY_SEPARATOR_KEY` option to `false`, so the same CSV above now results to:

```php
[
    "username" => "deuchnord",
    "birth.day" => 9,
    "birth.month => 6,
    "birth.year" => 1993
]
```

2023-03-21 16:12 UTC, mtarld requested changes

2023-03-21 16:12 UTC, mtarld commented on src/Symfony/Component/Serializer/Encoder/CsvEncoder.php
> +                        $header = false === $keySeparator ? [$col] : explode($keySeparator, $col ?? '');
Don't forget to update the `CsvEncoderContextBuilder` so that it can handle the `false` value.

2023-03-27 09:14 UTC, mtarld requested changes

2023-03-27 09:14 UTC, mtarld commented on src/Symfony/Component/Serializer/Tests/Context/Encoder/CsvEncoderContextBuilderTest.php
> +        yield 'With false key separator' => [[
You can just add `CsvEncoder::KEY_SEPARATOR_KEY => false` in the previous yield instead of yielding a new set

2023-03-27 09:14 UTC, mtarld commented on src/Symfony/Component/Serializer/Tests/Context/Encoder/CsvEncoderContextBuilderTest.php
>          yield 'With null values' => [[
Please add `CsvEncoder::KEY_SEPARATOR_KEY => null` here as well

2023-05-03 14:38 UTC, dunglas commented
I'm 👍 for the feature, but what about encoding? You should update `CsvEncoder::flatten()` to take the new allowed value into account.

2023-05-03 14:51 UTC, dunglas commented
Also, using `false` as a magic value will remove the ability to choose the character to use as a separator. What about introducing a new `csv_flatten` option instead?

2023-12-09 09:58 UTC, OskarStark commented
@Deuchnord open to finish this PR? I would really appreciate this new feature!

Please rebase on 7.1 branch, thanks

2023-12-12 10:41 UTC, Deuchnord commented
I'm sorry, I didn't have much time lastly
I will try to finish it as soon as I can

2025-07-01 19:55 UTC, OskarStark commented
Thank you @Deuchnord for your contribution and the effort you put into this PR\! We're closing this due to lack of recent activity. If this feature is still needed, please feel free to open a new PR against the current branch.

2025-07-01 19:55 UTC, closed without merging