Stop stopwatch events in case of exception
symfony/symfony pull request #49706
Opened 2023-03-16 16:08 UTC by MatTheCat

| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #49677 
| License       | MIT
| Doc PR        | N/A

Stopwatch events need to be stopped even if an exception occurred, else they will appear to span across the whole request timeline.

The following screenshots were taken with `RouterListener` throwing in debug mode following a [`NoConfigurationException`](https://github.com/symfony/symfony/blob/0362350a720e38df55531ab0cf726a082d3d34d4/src/Symfony/Component/Routing/Exception/NoConfigurationException.php):

<details>
<summary>Before</summary>
<img src="https://user-images.githubusercontent.com/243674/224777379-1209dfde-8086-49e3-af56-147ceda3e6c9.png" alt="">
</details>

<details>
<summary>After</summary>
<img src="https://user-images.githubusercontent.com/1898254/225371948-a21acf87-203c-49f9-b73a-4947e9a5092a.png" alt="">
</details>

2023-03-16 16:25 UTC, fabpot approved these changes

2023-03-16 22:53 UTC, GromNaN approved these changes
Thanks, the PR would be absolutely perfect with a unit test.

2023-03-16 23:00 UTC, GromNaN requested changes

2023-03-16 23:00 UTC, GromNaN commented on src/Symfony/Component/HttpKernel/Controller/TraceableControllerResolver.php
> +        }
The `$ret` variable is no longer necessary with `finally`.
```suggestion
        try {
            return $this->resolver->getController($request);
        } finally {
            $e->stop();
        }
```

2023-03-16 23:00 UTC, GromNaN commented on src/Symfony/Component/HttpKernel/Controller/TraceableArgumentResolver.php
> +        }
The `$ret` variable is no longer necessary with `finally`.

```suggestion
        try {
            return $this->resolver->getArguments($request, $controller);
        } finally {
            $e->stop();
        }
```

2023-03-17 10:53 UTC, MatTheCat commented on src/Symfony/Component/HttpKernel/Controller/TraceableControllerResolver.php
> +        }
Good catch, PhpStorm did not even notice!

2023-03-17 10:55 UTC, GromNaN approved these changes

2023-03-17 11:32 UTC, fabpot commented
Thank you @MatTheCat.

2023-03-17 11:32 UTC, closed without merging