[Form] Replace hardcoded class name with FQCN resolution in tests
symfony/symfony pull request #49757
Opened 2023-03-21 15:58 UTC by ker0x

| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | -

2023-03-22 06:26 UTC, OskarStark approved these changes

2023-03-22 10:48 UTC, WebMamba commented on src/Symfony/Component/Form/Tests/Extension/Csrf/Type/FormTypeCsrfExtensionTest.php
> +    public static function provideBoolean(): array
Looks like there are also some unrelated change. Maybe it could be better to add those return type in a separate PR?

2023-03-22 14:51 UTC, GromNaN requested changes
Code refactoring are accepted only for the next minor release (branch  6.3), [see the doc](https://symfony.com/doc/current/contributing/code/maintenance.html).

Also if we want to do this, it should be on the whole codebase and automated. Rector can do the changes with [`StringClassNameToClassConstantRector`](https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#stringclassnametoclassconstantrector).

2023-03-28 15:05 UTC, nicolas-grekas commented
Closing as explained.

2023-03-28 15:05 UTC, closed without merging