[WIP] [Serializer] Add XmlEncoder CDATA wrapping opt out
symfony/symfony pull request #49893
Opened 2023-04-01 16:43 UTC by AndoniLarz

| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #26128
| License       | MIT
| Doc PR        | TODO

Usage example :
```php
$data = [
	'Hello' => 'Paul & Martha <or Me>',
];

return new Response(
    $this->serializer->serialize(
        $data,
        XmlEncoder::FORMAT,
        [
            XmlEncoder::ENABLE_CDATA_WRAPPING => false
        ]
    ),
    headers: [
        'Content-Type' => 'application/xml'
    ]
);
```

will output

```xml
<?xml version="1.0"?>
<response><Hello>Paul &amp; Martha &lt;or Me&gt;</Hello></response>
```

instead of

```xml
<?xml version="1.0"?>
<response><Hello><![CDATA[Paul & Martha <or Me>]]></Hello></response>
```

---

As stated in [the following comment from PHP.net](https://www.php.net/manual/fr/domdocument.createtextnode.php#116351) : PHP automatically handles the escape when calling `DOMDocument::createTextNode` which is done in [::appendText](https://github.com/symfony/symfony/blob/6.3/src/Symfony/Component/Serializer/Encoder/XmlEncoder.php#L193).
`::appendText` is always called if `XmlEncoder::ENABLE_CDATA_WRAPPING => false`.

---

Questions:
* Should we allow for custom XPath to be wrapped in CDATA while others are simply escaped ?
* Should we allow for a callback function to be used in place of a boolean (`callable(string $val): bool`)
* [W3Schools#Entity References](https://www.w3schools.com/xml/xml_syntax.asp#:~:text=/note%3E-,Entity%20References,-Some%20characters%20have) states that `'` and `"` might also be escaped. Based on this should we instead provide a list of characters to escape/wrap ? (currently it would be set to `['<', '>', '&']`)

---
- [ ] Create the documentation PR

2023-04-01 17:06 UTC, AndoniLarz commented
Failing checks seem unrelated to my changes

2023-04-05 09:14 UTC, mtarld requested changes

2023-04-05 09:14 UTC, mtarld commented on src/Symfony/Component/Serializer/Encoder/XmlEncoder.php
> +        }
```suggestion
        if (false === ($context[self::ENABLE_CDATA_WRAPPING] ?? true)) {
            return false;
        }
```
WDYT?

2023-04-05 09:14 UTC, mtarld commented on src/Symfony/Component/Serializer/Encoder/XmlEncoder.php
> +    public const ENABLE_CDATA_WRAPPING = 'enable_cdata_wrapping';
Could you update the `XmlEncoderContextBuilder` and the related test as well?

2023-09-08 10:49 UTC, astehlik commented
I tested the changes from the PR and they work like a charm :+1:

2023-10-11 14:22 UTC, nicolas-grekas approved these changes
I fixed the remaining comments and renamed the option to `CDATA_WRAPPING`

2023-10-11 14:22 UTC, nicolas-grekas commented
Thank you @AndoniLarz.

2023-10-11 14:23 UTC, merged