[TwigBridge] [TwigBundle] Add current locale to `AppVariable`
symfony/symfony pull request #49913
Opened 2023-04-03 14:55 UTC by SVillette

| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no 
| Tickets       | Fix #49870
| License       | MIT
| Doc PR        | -

As stated in #49870, they were no way to get the current locale without passing it through a variable when rendering a template within `LocaleSwitcher::runWithLocale()`.

```php
#[AsController]
final class HomeController
{
    #[Route('/', name: 'app_home')]
    public function __invoke(LocaleSwitcher $localeSwitcher, Environment $twig): Response
    {
        $localeSwitcher->setLocale('en');

        return $localeSwitcher->runWithLocale('fr', function () use ($twig) {
            return new Response($twig->render('index.html.twig'));
        });
    }
}
```

```twig
{{ app.locale }} // fr
```

A doc PR will be submitted if Core team accept this change.

2023-04-03 15:48 UTC, SVillette commented
About the failing tests, I may need some help / directions here. 
- The `Integration / Integration (8.1)` seems to be unrelated to this PR (`Cache` related).
- The `Unit Tests / Unit Tests (8.1)` is failing because `AppVariable::setLocaleSwitcher()` does not have a return type and is not listed in `.github/expected-missing-return-types.diff`. Updating this file should resolve the issue but I can't do it as they are bunch of other changes here.
- The `Unit Tests / Unit Tests (8.1, low-deps)` fails because `LocaleSwitcher` class is missing. Do I have to skip the test if the class does not exist ?
- Finally, `continuous-integration/appveyor/pr` fail seems unrelated to this PR (`VarDumper` issue).

2023-04-07 17:13 UTC, stof requested changes

2023-04-07 17:13 UTC, stof commented on src/Symfony/Bridge/Twig/AppVariable.php
> +     * @return void
As this is a new method, you should add the native return type directly, as there is no BC impact forgetting to add it in a minor version (btw, that's why the CI fails)

2023-04-07 17:14 UTC, stof commented
For low-deps, you need to increase the lower bound of the requirement

2023-04-08 07:23 UTC, fabpot requested changes

2023-04-08 07:23 UTC, fabpot commented on src/Symfony/Bridge/Twig/CHANGELOG.md
> + * Add `AppVariable::getLocale()` to retrieve the current locale when using the `LocaleSwitcher`
missing newline above

2023-04-11 08:07 UTC, SVillette commented
Thank you for the input, CI is still failling but not because of this PR.

2023-04-11 15:31 UTC, fabpot approved these changes

2023-04-11 15:34 UTC, stof approved these changes

2023-04-11 17:34 UTC, fabpot commented
Thank you @SVillette.

2023-04-11 17:35 UTC, merged

2023-05-03 15:39 UTC, curry684 commented
When installing the Twig Bundle 6.3.0-BETA1 this breaks the application if you didn't directly add the bridge as well:
```sh
!!    [Symfony\Component\ErrorHandler\Error\UndefinedMethodError]
!!    Attempted to call an undefined method named "setLocaleSwitcher" of class "S
!!    ymfony\Bridge\Twig\AppVariable".
```
Bundle 6.3 is thus incompatible with Bridge 6.2 yet this is not enforced through dependencies.