46867 - add more helpful property path accessor exceptions
symfony/symfony pull request #50128
Opened 2023-04-23 11:59 UTC by patrickmaynard

| Branch? | 6.3
| Bug fix? | no
| New feature? | no
| Deprecations? | no
| Tickets | https://github.com/symfony/symfony/issues/46867
| License | MIT
| Doc PR | none

Dear reviewers,

This small modification adds more helpful exceptions when properties cannot be accessed/set
using forms. Only one file was modified, so it should be relatively easy to review. Please feel free to leave a comment if you have any questions about what I'm doing here, and thanks for your work as a reviewer on an open-source project!

All the best,

Patrick

2023-04-23 12:17 UTC, patrickmaynard commented
All tests seem to be passing, but there's some sort of infrastructure error when the pipeline runs:
```
Error: KO src/Symfony/Component/Mime
```

Any ideas on what this means?

2023-08-02 10:15 UTC, patrickmaynard commented
> All tests seem to be passing, but there's some sort of infrastructure error when the pipeline runs:
> 
> ```
> Error: KO src/Symfony/Component/Mime
> ```
> 
> Any ideas on what this means? It seems to be unrelated to the change in my PR.

@nicolas-grekas @aurelijus @theinterned anybody have thoughts on what I should do next to try to get the pipeline running correctly again? As I mentioned, this broken pipeline doesn't seem to have anything to do with my (very small) changes.

2024-02-06 11:45 UTC, fabpot requested changes

2024-02-06 11:45 UTC, fabpot commented on src/Symfony/Component/Form/Extension/Core/DataAccessor/PropertyPathAccessor.php
> +                throw new NoSuchPropertyException($e->getMessage().' Make the property public, add a setter, or set the "mapped" field option in the form type to be false.');
Can we set $e as the previous exception instead or concatenating the messages?

2024-03-17 16:55 UTC, fabpot approved these changes

2024-03-17 16:57 UTC, fabpot commented
Thank you @patrickmaynard.

2024-03-17 16:57 UTC, merged