Fix registering traceable voters, argument resolvers and normalizers
symfony/symfony pull request #50158
Opened 2023-04-26 10:17 UTC by nicolas-grekas

| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | -

By using service decoration to trace voters, resolvers and normalizers, we break the possibility to register them under several tags. We also make it harder to decorate them for end users. But adding observability to those doesn't require adding side effect to service definitions. Instead, we can and should use regular decoration.

2023-04-28 16:16 UTC, stof requested changes

2023-04-28 16:16 UTC, stof commented on src/Symfony/Component/HttpKernel/DependencyInjection/ControllerArgumentValueResolverPass.php
> +                    ->addTag('controller.argument_value_resolver');
shouldn't we copy the tag attributes ?

2023-04-28 16:16 UTC, stof commented on src/Symfony/Component/HttpKernel/DependencyInjection/ControllerArgumentValueResolverPass.php
> +                    ->addTag('controller.argument_value_resolver');
Wouldn't this break support for the `AsTaggedItem` attribute when resolving the TaggedIteratorArgument for those resolvers as it would look for the attribute on the TraceableValueResolver rather than on the actual resolver ?

2023-04-28 16:16 UTC, stof commented on src/Symfony/Component/HttpKernel/DependencyInjection/ControllerArgumentValueResolverPass.php
> +                    ->addTag('controller.argument_value_resolver');
same in other compiler passes btw

2023-05-02 09:35 UTC, nicolas-grekas commented
Thanks for the review @stof. You made me realize that we don't need to move the tags to the decorator. PR updated.

2023-05-02 09:54 UTC, chalasr commented
Could you double check that this does not break data collectors? Pretty sure it's ok for voters due to the way they're registered in debug mode but I don't know for normalizers and arg resolvers (thinking to some tagged locator referencing the original services while expecting to end up with the debug wrappers injected)

2023-05-02 10:00 UTC, nicolas-grekas commented
@chalasr I checked the code: the only way they're registered is via this pass. The updated tests should give you the hint to be confident this doesn't break the profiler: the injected refs are the debug ones, which have the stopwatch in them.

2023-05-02 10:21 UTC, chalasr commented
Thanks for confirming

2023-05-02 10:21 UTC, chalasr approved these changes

2023-05-02 13:53 UTC, stof approved these changes

2023-05-02 14:10 UTC, merged