Serializer backed enum throw notNormalizableValueException outside construct method
symfony/symfony pull request #50192
Opened 2023-04-28 21:38 UTC by alli83

| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | https://github.com/symfony/symfony/pull/47128#issuecomment-1527776830
| License       | MIT
| Doc PR        | 

PR https://github.com/symfony/symfony/pull/47128#issuecomment-1527776830 was aiming  to throw  an InvalidArgumentException if a constructor's argument is not a valid backedEnum( knowing an error will be thrown in all case e.g when it will be instantiated).

This PR aims to throw a NotNormalizableValueException  (like it was the case before) if an error occurs on an BackedEnum outside the case of the first PR

2023-05-02 08:39 UTC, TerjeBr requested changes
Looks good, but missing all the data in the NotNormalizableValueException that makes it useful.

2023-05-02 08:39 UTC, TerjeBr commented on src/Symfony/Component/Serializer/Normalizer/BackedEnumNormalizer.php
> +            throw new NotNormalizableValueException('The data must belong to a backed enumeration of type '.$type);
Please add all the data that belongs in a NotNormalizableValueException

2023-05-02 12:46 UTC, nicolas-grekas commented on src/Symfony/Component/Serializer/Tests/SerializerTest.php
> +        } catch (\Throwable $th) {
```suggestion
        } catch (\Throwable $e) {
```

2023-05-02 15:50 UTC, TerjeBr commented on src/Symfony/Component/Serializer/Normalizer/BackedEnumNormalizer.php
> +            throw new NotNormalizableValueException('The data must belong to a backed enumeration of type '.$type);
```suggestion
            throw NotNormalizableValueException::createForUnexpectedDataType('The data must belong to a backed enumeration of type '.$type, $data, [$type], $context['deserialization_path'] ?? null, true, 0, $e);
```

2023-05-02 17:51 UTC, TerjeBr approved these changes
Looks good to me

2023-05-03 11:39 UTC, chalasr approved these changes

2023-05-05 11:04 UTC, fabpot approved these changes

2023-05-05 11:05 UTC, fabpot commented
Thank you @alli83.

2023-05-05 11:05 UTC, merged