[Serializer][FrameworkBundle] Add TranslatableNormalizer
symfony/symfony pull request #50212
Opened 2023-05-02 15:04 UTC by Jean-Beru

| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | maybe
| Tickets       | 
| License       | MIT
| Doc PR        | WIP

In 5.2, Symfony introduced translatable objects. This PR adds a dedicated normalizer to translate them. It can be useful for an API to return translated properties.

Also I'm wondering if it could be considered as a BC break since translatable objects were handled by the ObjectNormalizer which currently returns a plain object.

PS: if accepted, I'll rebase this PR on 6.4 since 6.3 is closed for new features.

2023-07-29 17:02 UTC, dunglas requested changes

2023-07-29 17:02 UTC, dunglas commented on src/Symfony/Component/Serializer/Normalizer/TranslatableNormalizer.php
> +        private readonly ?TranslatorInterface $translator = null,
Shouldn't we force this property to be non-null and remove the related to this class if the translator isn't available?

2023-07-29 17:02 UTC, dunglas commented on src/Symfony/Component/Serializer/Normalizer/TranslatableNormalizer.php
> +        return [TranslatableInterface::class => true];
With the current implementation, this method should return an empty array of no translator is injected. But see my other comment.

2023-08-01 07:58 UTC, Jean-Beru commented on src/Symfony/Component/Serializer/Normalizer/TranslatableNormalizer.php
> +        private readonly ?TranslatorInterface $translator = null,
Good catch, especially since this normalizer is useless without the Translator

2023-08-01 10:16 UTC, dunglas approved these changes

2023-08-01 10:16 UTC, dunglas commented on src/Symfony/Bundle/FrameworkBundle/Tests/DependencyInjection/FrameworkExtensionTestCase.php
> +        $this->assertEquals(TranslatableNormalizer::class, $definition->getClass());
`assertSame` ?

2023-08-01 10:28 UTC, Jean-Beru commented on src/Symfony/Bundle/FrameworkBundle/Tests/DependencyInjection/FrameworkExtensionTestCase.php
> +        $this->assertEquals(TranslatableNormalizer::class, $definition->getClass());
:+1:

2023-08-01 12:38 UTC, fabpot approved these changes

2023-08-01 12:39 UTC, fabpot commented
Thank you @Jean-Beru.

2023-08-01 12:39 UTC, merged