[Validator] Allow single constraint to be passed to the `constraints` option of the `When` constraint
symfony/symfony pull request #50425
Opened 2023-05-25 09:16 UTC by alexandre-daubois

| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | _NA_
| License       | MIT
| Doc PR        | Todo

It would be nice for the DX to allow passing a single constraint to `When`, allowing to write the following:

```php
final class MyClass
{
    public string $type;

    #[Assert\When(
        expression: 'this.type === ...',
        constraints: new Assert\NotNull()
    )]
    public ?int $thickness = null;
}
```

2023-05-25 11:46 UTC, chalasr commented
Symfony doesn't do backward-incompatible changes without deprecating first, this should target 6.4 and provide BC layers if/where needed.

2023-05-25 11:47 UTC, alexandre-daubois commented
@chalasr Nicolas and Christian are giving me instructions for the same issue [here](https://github.com/symfony/symfony/pull/50396). I'm having a look, thanks!

2023-05-25 11:49 UTC, chalasr commented
AFAICT there is no BC break here, this should be fine as-is on 6.4.

2023-05-25 11:51 UTC, OskarStark commented
> AFAICT there is no BC break here, this should be fine as-is on 6.4.
I agree, as it is widening the type

2023-05-25 11:58 UTC, alexandre-daubois commented
I thought again about it, you're right, it shouldn't cause any issue as it is in the constructor. Thank you both :pray:

2023-06-08 21:53 UTC, nicolas-grekas commented
This PR should be put on hold until we settle on https://github.com/symfony/symfony/pull/50396#issuecomment-1575013763

2023-06-21 10:12 UTC, nicolas-grekas approved these changes

2023-06-21 16:19 UTC, xabbuh requested changes

2023-06-21 16:19 UTC, xabbuh commented on src/Symfony/Component/Validator/CHANGELOG.md
> +7.0
```suggestion
6.4
```

2023-06-21 16:21 UTC, nicolas-grekas commented
Thank you @alexandre-daubois.

2023-06-21 16:21 UTC, merged