[Webhook][RemoteEvent] Add Mailjet support.
symfony/symfony pull request #50502
Opened 2023-05-31 11:52 UTC by blaugueux

| Q             | A
| ------------- | ---
| Branch       | 6.4
| Bug fix      | no
| New feature  | yes
| Deprecations | no
| Tickets       | 
| License       | MIT
| Doc PR        |

2023-05-31 15:33 UTC, fabpot approved these changes
LGTM, just a small suggestion to make code shorter and maybe more readable.

2023-05-31 15:33 UTC, fabpot commented on src/Symfony/Component/Mailer/Bridge/Mailjet/RemoteEvent/MailjetPayloadConverter.php
> +        return '';
```suggestion
        return $payload['smtp_reply'] ?? $payload['error_related_to'] ?? '';
```

2023-06-03 15:07 UTC, fabpot requested changes
@blaugueux You need to add `"symfony/webhook": "^6.3"` in the `require-dev` section of the Mailjet bridge `composer.json` file to make tests pass.

2023-07-31 13:32 UTC, fabpot commented
@blaugueux Can you rebase to see if the tests would pass?

2023-08-03 19:47 UTC, OskarStark commented on src/Symfony/Component/Mailer/Bridge/Mailjet/composer.json
> +        "symfony/webhook": "^6.3"
```suggestion
        "symfony/webhook": "^6.4"
```

2023-08-04 05:52 UTC, fabpot approved these changes

2023-08-04 05:53 UTC, fabpot commented
Thank you @blaugueux.

2023-08-04 05:53 UTC, merged