[ErrorHandler] Improve fileLinkFormat handling (#50619)
symfony/symfony pull request #50734
Opened 2023-06-21 19:13 UTC by nlemoine

| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | 🤷 (not sure this can be considered a bug)
| New feature?  | 🤷
| Deprecations? | no
| Tickets       | Fix #50619
| License       | MIT
| Doc PR        | 

- Avoid repeating file link format guessing (logic is already in FileLinkFormatter class)
- Always set a fileLinkFormat to a FileLinkFormatter object to handle path mappings properly

2023-06-23 10:01 UTC, GromNaN requested changes
Using the `Symfony\Component\HttpKernel\Debug\FileLinkFormatter` in `Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer`, but the 2 classes are not in the same composer packages.
I think the `FileLinkFormatter` should be moved to `symfony/error-renderer`: this package is already required by `symfony/http-kernel`, but not in the other direction.

This can be done in a backward-compatible way by replacing the class with:
```php
namespace Symfony\Component\HttpKernel\Debug;

use Symfony\Component\ErrorHandler\ErrorRenderer\FileLinkFormatter as NewFileLinkFormatter;

/** @deprecated since 6.4, use Symfony\Component\ErrorHandler\ErrorRenderer\FileLinkFormatter */
class FileLinkFormatter extends NewFileLinkFormatter
{
    // Inherit all the methods from the parent
}
```

I'll just ask @symfony/mergers opinion before you can start editing if you wish.

2023-06-23 10:01 UTC, GromNaN commented on src/Symfony/Component/ErrorHandler/ErrorRenderer/HtmlErrorRenderer.php
> +        }
The type of `$fileLinkFormat` is `string|FileLinkFormatter|null`. And the `FileLinkFormatter` constructor accepts `string|array|null`. The assignment can be one-lined.

```suggestion
        $this->fileLinkFormat = $fileLinkFormat instanceof FileLinkFormatter ? $fileLinkFormat : new FileLinkFormatter($fileLinkFormat);
```

---

But, note the class `FileLinkFormatter` can be missing as the `symfony/error-handler` package doesn't require `symfony/http-kernel`.

2023-06-23 12:38 UTC, nlemoine commented on src/Symfony/Component/ErrorHandler/ErrorRenderer/HtmlErrorRenderer.php
> +        }
Thanks for you review! I must say these one liners gives me headaches 🙂  Sure they are concise but [takes minutes to process](https://github.com/zakirullin/cognitive-load) for my (modest/slow) developer brain 🤯

2023-06-23 12:56 UTC, nlemoine commented
> Using the Symfony\Component\HttpKernel\Debug\FileLinkFormatter in Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer is a good idea, but the 2 classes are not in the same composer packages.

That would be great! My original issue about was actually aiming to make file link formatting more consistent across components. Some business logic, that's already contained in `FileLinkFormatter` class, is repeated in various places:
- https://github.com/symfony/symfony/blob/81c102dd54372d0b353f8a80044c825205a33c1a/src/Symfony/Bridge/Twig/Extension/CodeExtension.php#L31
- https://github.com/symfony/symfony/blob/81c102dd54372d0b353f8a80044c825205a33c1a/src/Symfony/Component/VarDumper/Dumper/CliDumper.php#L84
- https://github.com/symfony/symfony/blob/81c102dd54372d0b353f8a80044c825205a33c1a/src/Symfony/Component/HttpKernel/DataCollector/DumpDataCollector.php#L48
- https://github.com/symfony/symfony/blob/81c102dd54372d0b353f8a80044c825205a33c1a/src/Symfony/Component/VarDumper/Dumper/CliDumper.php#L84
- https://github.com/symfony/symfony/blob/81c102dd54372d0b353f8a80044c825205a33c1a/src/Symfony/Component/VarDumper/Dumper/HtmlDumper.php#L81

Probably all those statements could be replaced with something like (long version):
```php
if ($fileLinkFormat instanceof FileLinkFormatter) {
    $this->fileLinkFormat = $fileLinkFormat;
} else {
    $this->fileLinkFormat = class_exists(FileLinkFormatter::class) ? new FileLinkFormatter() : $fileLinkFormat;
}
```

What do you think?

2023-06-23 13:36 UTC, GromNaN commented on src/Symfony/Component/ErrorHandler/ErrorRenderer/HtmlErrorRenderer.php
> +        }
Sorry for your brain. That's actually less logic and operations.

The type of `$fileLinkFormat;` can be modified to `private FileLinkFormatter $fileLinkFormat;`

2023-06-23 13:51 UTC, nlemoine commented on src/Symfony/Component/ErrorHandler/ErrorRenderer/HtmlErrorRenderer.php
> +        }
Done!

2023-10-16 20:05 UTC, nicolas-grekas approved these changes
I updated all references to the deprecated namespace.
This should be good to do (despite tests)

2023-10-16 20:15 UTC, fabpot approved these changes

2023-10-16 20:16 UTC, fabpot commented
Thank you @nlemoine.

2023-10-16 20:16 UTC, merged

2023-10-18 17:20 UTC, nlemoine commented
Great, thanks!