[EnventDispatcher] Fix method resolving for listeners
symfony/symfony pull request #50775
Opened 2023-06-26 06:23 UTC by nikophil

2023-06-26 07:10 UTC, nicolas-grekas commented
This should target 5.4 to me since it's a bugfix.

2023-06-26 07:40 UTC, nikophil commented
@nicolas-grekas I've rebased the PR

2023-06-26 07:40 UTC, nicolas-grekas approved these changes

2023-06-26 07:47 UTC, GromNaN commented
Thank you for your findings on this bug. 

> If it does not, we evaluate if one unique public method exists which would take the event as unique parameter (ie: the listener definition above would resolve someMethod() as the listener's method).

This looks like a new feature. Even if there is currently a runtime exception for this situation, I don't think we should support it as a bugfix.
The bugfix should be restricted to throwing an exception on build time when the method (`__invoke` or `onEventName`) doesn't exist.

I see situations where the "only public method" will fail and the developer will have to rework its configuration while it would be working previously:
- a public getter or setter is added for DI or testing
- a second event listener is added

For brevity, developers should set the `AsEventListener` attribut on the method instead of the class.

2023-06-26 08:08 UTC, nikophil commented
> This looks like a new feature. Even if there is currently a runtime exception for this situation, I don't think we should support it as a bugfix.
> The bugfix should be restricted to throwing an exception on build time when the method (__invoke or onEventName) doesn't exist.

ok let's do this: I'll split the PR and in the bugfix I'll only throw an exception if the resolved method does not exist

> I see situations where the "only public method" will fail and the developers will have to rework their configuration while it would be working previously:
>
>    a public getter or setter is added for DI or testing
>    a second event listener is added
>
> For brevity, developers should set the AsEventListener attribut on the method instead of the class.

indeed, there will be a failure in these cases, but for both cases, we don't have any way to resolve the method name, then their listener declaration becomes invalid. And since the error will occur in compile time, I think this is acceptable

2023-06-26 08:11 UTC, GromNaN commented
> ok let's do this: I'll split the PR and in the bugfix I'll only throw an exception if the resolved method does not exist

👍🏻 Sounds like a plan.

2023-06-26 08:16 UTC, nikophil commented
> For brevity, developers should set the AsEventListener attribut on the method instead of the class.

This is just an idea, but since listeners are callables and not actual services, maybe in 7.0 we should allow `#[AsEventListener]` to be set on the class only if the class in invokable? This would simplify a lot all this resolving stuff, and remove some un-needed magic

2023-06-26 08:32 UTC, GromNaN commented
I wouldn't bother developers with such a restriction. We're not going to deprecate [documented](https://symfony.com/doc/current/event_dispatcher.html#defining-event-listeners-with-php-attributes) way of using this attribute.

2023-06-26 08:32 UTC, nicolas-grekas commented
>  I'll split the PR and in the bugfix I'll only throw an exception if the resolved method does not exist

Totally. I missed this was a new feature.

> This is just an idea, but since listeners are callables and not actual services, maybe in 7.0 we should allow #[AsEventListener] to be set on the class only if the class in invokable? This would simplify a lot all this method-resolving stuff, and remove some un-needed magic

I would advise against this. It's needlessly rigid.

2023-06-26 15:36 UTC, GromNaN requested changes
LGTM, after few changes.

2023-06-26 15:36 UTC, GromNaN commented on src/Symfony/Component/EventDispatcher/DependencyInjection/RegisterListenersPass.php
> +                            throw new InvalidArgumentException(sprintf('Service "%s" must define the "method" attribute on "%s" tags.', $id, $this->listenerTag));
You can add that none of `$event['method']` and `__invoke` are defined. That would help to discover the default naming conventions and eventually track a typo in the method name.

2023-06-26 15:36 UTC, GromNaN commented on src/Symfony/Component/EventDispatcher/DependencyInjection/RegisterListenersPass.php
> +    private function resolveListenerMethodFromTypeDeclaration(ContainerBuilder $container, string $id, string $eventName, array $aliases): string
This method is no longer used.

2023-06-26 15:37 UTC, nikophil commented on src/Symfony/Component/EventDispatcher/DependencyInjection/RegisterListenersPass.php
> +    private function resolveListenerMethodFromTypeDeclaration(ContainerBuilder $container, string $id, string $eventName, array $aliases): string
whopsy

2023-06-26 15:43 UTC, nikophil commented
CI failures seems unrelated

2023-06-26 15:49 UTC, GromNaN approved these changes

2023-06-26 15:49 UTC, GromNaN commented on src/Symfony/Component/EventDispatcher/Tests/DependencyInjection/RegisterListenersPassTest.php
> +        $this->expectExceptionMessage('Methods "onFooBar" and "__invoke" do not exist for service "foo". Please define the "method" attribute on "kernel.event_listener" tags.');
Maybe better like this.
```suggestion
        $this->expectExceptionMessage('None of the "onFooBar" or "__invoke" methods exist for the service "foo". Please define the "method" attribute on "kernel.event_listener" tags.');
```

2023-06-26 15:54 UTC, nikophil commented on src/Symfony/Component/EventDispatcher/Tests/DependencyInjection/RegisterListenersPassTest.php
> +        $this->expectExceptionMessage('Methods "onFooBar" and "__invoke" do not exist for service "foo". Please define the "method" attribute on "kernel.event_listener" tags.');
:pray:

2023-06-27 09:42 UTC, nicolas-grekas reviewed
One minor thing. Can you please also update the commit+PR messages to make them tell what this does?

2023-06-27 09:42 UTC, nicolas-grekas commented on src/Symfony/Component/EventDispatcher/DependencyInjection/RegisterListenersPass.php
> +                        }
```suggestion
                        if (!$r->hasMethod('__invoke')) {
                            throw new InvalidArgumentException(sprintf('None of the "%s" or "__invoke" methods exist for the service "foo". Please define the "method" attribute on "kernel.event_listener" tags.', $event['method'], $id, $this->listenerTag));
                        }
                        $event['method'] = '__invoke';
```

2023-06-27 09:59 UTC, nikophil commented
@nicolas-grekas done!

2023-06-27 10:04 UTC, nicolas-grekas approved these changes

2023-06-28 19:10 UTC, nicolas-grekas commented
Thank you @nikophil.

2023-06-28 19:10 UTC, merged