[TwigBridge] Fix for GitHub ticket 50789
symfony/symfony pull request #50794
Opened 2023-06-27 10:26 UTC by Dirkhuethorst

Change the return type of AppVariable.php getSession from 'Session' to 'SessionInterface', to be in line with the return type of getSession in http-foundation/Request.php

| Q             | A
| ------------- | ---
| Branch?       | 6.2
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #50789
| License       | MIT
| Doc PR        |

2023-06-27 11:07 UTC, derrabus commented
The failing tests on the low-deps run look related.

2023-06-27 20:05 UTC, Nyholm commented
I see you replaced the return type from class `Session` to interface `FlashBagAwareSessionInterface`. This is not always correct. It could be a Session that do not implement FlashBag feature. 

I suggest to change it to `SessionInterface`

2023-06-27 20:14 UTC, GromNaN requested changes
The `FlashBagAwareSessionInterface` was introduced in `symfony/http-foundation: 6.2` by #46491, and `symfony/twig-bridge: 6.2` allows `symfony/http-foundation: 5.4` in which the interface doesn't exit.
We usually don't update the dependencies constraints in maintenance branches except for security reasons. I don't think we should accept this change as a bugfix, it looks more like a new feature that would target the next version (6.4 ATM).

Also, `Symfony\Component\HttpFoundation\Session\Session` implements `\IteratorAggregate` and `\Countable` on top of `FlashBagAwareSessionInterface` or `SessionInterface`. Changing the return type to this single interface would reduce the functions that could be used in the templates.

2023-06-27 20:14 UTC, GromNaN commented on src/Symfony/Bridge/Twig/AppVariable.php
> +    public function getSession(): ?FlashBagAwareSessionInterface
The return type could be the intersection of all the interfaces implemented by `Session` in `symfony/http-foundation: 5.4`.

```suggestion
    public function getSession(): ?SessionInterface&\Traversable&\Countable
```

2023-06-27 20:18 UTC, Nyholm commented
I was hesitating if this was a bugfix or not. But with @GromNaN arguments, I agree. This is a feature.

2023-06-28 13:15 UTC, derrabus commented on src/Symfony/Bridge/Twig/AppVariable.php
> +    public function getSession(): ?FlashBagAwareSessionInterface
@GromNaN Native intersection types are not nullable. And unions of a intersection type with the `null` type require PHP >= 8.2. That aside, your proposal generates the same problem as the current type: The HttpFoundation `Request` cannot guarantee that the session it returns in `Traversable` and `Countable`.

2023-06-28 13:25 UTC, derrabus commented
I think, if we change the return type to `?SessionInterface`, we can file it as a bugfix. Using a custom implementation of the `SessionInterface` should've worked in Symfony 5 and it stopped working because of a too narrow native return type in Symfony 6. I believe this breaking change was unintended.

2023-06-28 14:11 UTC, GromNaN commented on src/Symfony/Bridge/Twig/AppVariable.php
> +    public function getSession(): ?FlashBagAwareSessionInterface
Well, I've forgotten nullable in my proposal. Clearly, the return type cannot be changed in a totally backwards-compatible way.

Noticed [your proposition](https://github.com/symfony/symfony/pull/50794#issuecomment-1611409156) looks more correct.

2023-07-17 08:25 UTC, GromNaN approved these changes

2023-07-17 08:26 UTC, Dirkhuethorst commented
I've changed the return type to SessionInterface, but now the Psalm check fails because in the AppVariable class the Flashbag of the session is accessed. 

`src/Symfony/Bridge/Twig/AppVariable.php:147:30: UndefinedInterfaceMethod: Method Symfony\Component\HttpFoundation\Session\SessionInterface::getFlashBag does not exist (see https://psalm.dev/181)`

I am not sure how to proceed with this issue

2023-07-17 08:38 UTC, GromNaN commented
You can `return []` if `$session` is not an instance of `FlashBagAwareSessionInterface`.

2023-07-17 08:41 UTC, Dirkhuethorst commented
> You can `return []` if `$session` is not an instance of `FlashBagAwareSessionInterface`.

Won't that break backwards compatibility  with http-foundation 5.4 where the FlashBagAwareSessionInterface does not exist?

2023-07-17 08:57 UTC, GromNaN commented on src/Symfony/Bridge/Twig/AppVariable.php
> +        if (!method_exists($session, 'getFlashBag')) {
You can add a comment that this can be updated in 7.0 to check `FlashBagAwareSessionInterface`, when `symfony/http-foundation: 6.4` is required.

2023-09-10 08:49 UTC, fabpot approved these changes

2023-09-10 08:51 UTC, fabpot commented
Thank you @Dirkhuethorst.

2023-09-10 08:52 UTC, fabpot commented
Merged, but Github didn't get the memo.

2023-09-10 08:52 UTC, closed without merging