[Notifier] support local development for sns
symfony/symfony pull request #50879
Opened 2023-07-04 19:45 UTC by Ferror

| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | no
| New feature?  | yes 
| Deprecations? | no 
| Tickets       | none
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

When developing locally with AWS -> localstack we have to communicate via HTTP similarly to the SQS Transport for Messenger component.

https://github.com/symfony/amazon-sqs-messenger/blob/6.3/Transport/Connection.php#L50C14-L50C14

2023-07-30 12:24 UTC, fabpot requested changes

2023-07-30 12:24 UTC, fabpot commented on src/Symfony/Component/Notifier/Bridge/AmazonSns/AmazonSnsTransportFactory.php
> +        $sslmode = $dsn->getOption('sslmode', true);
Can we be consistent with SQS? It seems that we are using `disable` there to disable SSL.

2023-07-31 14:13 UTC, Ferror commented on src/Symfony/Component/Notifier/Bridge/AmazonSns/AmazonSnsTransportFactory.php
> +        $sslmode = $dsn->getOption('sslmode', true);
I noticed it has only disable/enable values which seems like a great usage of a simple boolean. Yea, let's keep it consistent.

2023-08-01 05:58 UTC, fabpot approved these changes

2023-08-01 05:59 UTC, fabpot commented
Thank you @Ferror.

2023-08-01 05:59 UTC, merged