[Notifier] Fix Esendex messages serialization
symfony/symfony pull request #50893
Opened 2023-07-05 15:31 UTC by raphael-geffroy

| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no
| Tickets       | Fix #50892 
| License       | MIT

It seems that the "messages" is missing a dimension since 6.3 and its serialized as an object instead of an array of objects.

2023-07-05 15:44 UTC, derrabus commented
Thank you. Can we add a test that covers your change?

2023-07-05 15:48 UTC, raphael-geffroy commented
Sure I will try :)

2023-07-05 19:18 UTC, raphael-geffroy commented
I added a test but feel free to modify it to comply to your level of requirement.

2023-07-06 05:59 UTC, fabpot requested changes

2023-07-06 05:59 UTC, fabpot commented on src/Symfony/Component/Notifier/Bridge/Esendex/Tests/EsendexTransportTest.php
> +        $this->assertIsArray($body->messages);
Let's test the content of the array.

2023-07-06 07:32 UTC, raphael-geffroy commented on src/Symfony/Component/Notifier/Bridge/Esendex/Tests/EsendexTransportTest.php
> +        $this->assertIsArray($body->messages);
Done :white_check_mark: Does it suit ?

2023-07-09 06:47 UTC, fabpot approved these changes

2023-07-09 06:50 UTC, fabpot commented
Thank you @raphael-geffroy.

2023-07-09 06:50 UTC, merged