[Mailer] File DNS transport
symfony/symfony pull request #50962
Opened 2023-07-13 07:25 UTC by claudiu-cristea

| Q             | A
| ------------- | ---
| Branch?       | 6.4 
| Bug fix?      | no
| New feature?  | yes 
| Deprecations? | no 
| Tickets       | Fix #50961 
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

Provides a file DSN to be configured as `file://path/to/relative/file.txt` or `file:///path/to/abolute/file.txt`

2023-07-13 08:26 UTC, OskarStark requested changes
Tests missing

2023-07-13 08:26 UTC, OskarStark commented on src/Symfony/Component/Mailer/Transport/FileTransport.php
> +use function _PHPStan_690619d82\RingCentral\Psr7\str;
This looks wrong

2023-07-13 08:26 UTC, OskarStark commented on src/Symfony/Component/Mailer/Transport/FileTransport.php
> +    public function __construct(EventDispatcherInterface $dispatcher = NULL, LoggerInterface $logger = NULL, protected Dsn $dsn)
NULL -> null

2023-07-13 08:26 UTC, OskarStark commented on src/Symfony/Component/Mailer/Transport/FileTransportFactory.php
> + * @author ...
TBD

2023-07-13 08:26 UTC, OskarStark commented on src/Symfony/Component/Mailer/Transport/FileTransport.php
> + * @author Fabien Potencier <fabien@symfony.com>
Should be you

2023-07-13 08:26 UTC, OskarStark commented on src/Symfony/Component/Mailer/Transport/FileTransport.php
> + * Sends the message to a file.
```suggestion
 * Writes the message to a file.
```

2023-07-13 09:51 UTC, claudiu-cristea commented on src/Symfony/Component/Mailer/Transport/FileTransport.php
> + * Sends the message to a file.
Fixed.

2023-07-13 09:51 UTC, claudiu-cristea commented on src/Symfony/Component/Mailer/Transport/FileTransport.php
> +use function _PHPStan_690619d82\RingCentral\Psr7\str;
Yes, leaked somehow. Fixed.

2023-07-13 09:51 UTC, claudiu-cristea commented on src/Symfony/Component/Mailer/Transport/FileTransport.php
> +    public function __construct(EventDispatcherInterface $dispatcher = NULL, LoggerInterface $logger = NULL, protected Dsn $dsn)
Drupal coding standards :) Fixed.

2023-07-13 09:51 UTC, claudiu-cristea commented on src/Symfony/Component/Mailer/Transport/FileTransportFactory.php
> + * @author ...
Fixed.

2023-07-13 09:51 UTC, claudiu-cristea commented on src/Symfony/Component/Mailer/Transport/FileTransport.php
> + * @author Fabien Potencier <fabien@symfony.com>
OK :)

2023-07-13 09:55 UTC, claudiu-cristea commented
Added tests but I don't understand the failures. Seems not to be related

2023-07-13 11:50 UTC, claudiu-cristea commented
@OskarStark I cannot change the status to "needs review". Also I cannot re-trigger the tests. It seems to me that those were random failures, anyway not related to this change

2023-07-31 11:46 UTC, fabpot commented
Sorry, but I still think that this should not be provided by Symfony core (for the reasons I've listed in the linked ticket).

2023-07-31 11:46 UTC, closed without merging