Improve message
symfony/symfony pull request #51270
Opened 2023-08-04 09:05 UTC by flohw

| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | not required I think

OptionsResolver exception message is very explicit on which option has an invalid value with the full path of the option on lazy option. But the message only showed the latest option name when the type is not valid. This PR fixes it and display the full option path of the lazy option's invalid type.

2023-08-04 09:11 UTC, flohw commented
Some unrelated tests fail on local environment and here. :thinking:

2023-08-04 15:50 UTC, yceruto requested changes
Improvements should go against 6.4 branch. Please rebase your commit.

I left a minor change request, 
Thanks!

2023-08-04 15:50 UTC, yceruto commented on src/Symfony/Component/OptionsResolver/Tests/OptionsResolverTest.php
> +    public function testResolveFailsIfInvalidValueFromLazyOption()
I think you meant `...FromNestedOption` https://symfony.com/doc/current/components/options_resolver.html#nested-options

Lazy options have a different definition https://symfony.com/doc/current/components/options_resolver.html#default-values-that-depend-on-another-option

2023-08-04 15:50 UTC, yceruto commented on src/Symfony/Component/OptionsResolver/Tests/OptionsResolverTest.php
> +    public function testResolveFailsIfInvalidTypeFromLazyOption()
same here `Nested` instead of `Lazy`

2023-08-04 15:50 UTC, yceruto commented on src/Symfony/Component/OptionsResolver/CHANGELOG.md
> + * Improve message with full path on invalid type in lazy option
`s/lazy/nested`

2023-08-04 15:55 UTC, yceruto commented
> Some unrelated tests fail on local environment and here.

Nothing to do in your side, unless you want to fix them in a separate PR ;-)

> I removed the latest commit as it make a lot of test fail. But fabbot is not happy anymore... Let me know if I need to update them.

They seem unrelated to your changes here and should be ignored, in my opinion.

2023-08-04 18:52 UTC, flohw commented
Thanks for your review @yceruto :-)
And the difference between nested and lazy options.

2023-08-05 13:06 UTC, yceruto commented
It seems something is wrong with the tests. Could you please squash your commits so that the tests are triggered again?

2023-08-06 09:22 UTC, flohw commented
I have squashed my two last commits.

I won't be available the next two weeks because of holidays. But I will be able to make any required changes when I come back. :-)

2023-08-07 02:28 UTC, yceruto approved these changes

2023-08-08 10:16 UTC, nicolas-grekas commented
Thank you @flohw.

2023-08-08 10:16 UTC, merged