[SecurityBundle] Remove the `require_previous_session` config option
symfony/symfony pull request #51333
Opened 2023-08-09 20:16 UTC by alamirault

| Q             | A
| ------------- | ---
| Branch?       | 7.0 for features / 5.4, or 6.3 for bug fixes 
| Bug fix?      | no
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #... 
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

PR #51332 deprecate config option. This PR remove last usage of option

2023-08-09 20:24 UTC, wouterj requested changes
Please add an entry to `UPGRADE-7.0.md` and the bundle's CHANGELOG.

2023-08-10 10:46 UTC, wouterj approved these changes

2023-08-11 08:14 UTC, fabpot approved these changes

2023-08-11 08:14 UTC, fabpot commented
Thank you @alamirault.

2023-08-11 08:15 UTC, merged