[HttpFoundation] Add `HeaderRequestMatcher`
symfony/symfony pull request #51343
Opened 2023-08-10 13:06 UTC by alexandre-daubois

| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | _NA_
| License       | MIT
| Doc PR        | Todo

This a follow up to:
- https://github.com/symfony/symfony/pull/51324

After @norkunas' [comment](https://github.com/symfony/symfony/pull/51324#issuecomment-1673145964)

2023-08-10 17:37 UTC, norkunas commented on src/Symfony/Component/HttpFoundation/RequestMatcher/HeaderRequestMatcher.php
> +            if (!\in_array($header, $request->headers->keys(), true)) {
Maybe:

```suggestion
            if (!$request->headers->has($header)) {
```
? 🙂

2023-08-11 07:13 UTC, alexandre-daubois commented on src/Symfony/Component/HttpFoundation/RequestMatcher/HeaderRequestMatcher.php
> +            if (!\in_array($header, $request->headers->keys(), true)) {
Much better!

2023-08-11 08:11 UTC, derrabus requested changes

2023-08-11 08:11 UTC, derrabus commented on src/Symfony/Component/HttpFoundation/RequestMatcher/HeaderRequestMatcher.php
> + * Checks the HTTP headers of a Request.
Can we be more precise here? After reading the code, I understood that the class matches request where a given header is simply present. We should point out that we cannot match on the value of headers with this class.

2023-08-11 08:11 UTC, derrabus commented on src/Symfony/Component/HttpFoundation/RequestMatcher/HeaderRequestMatcher.php
> +     *                                 Strings can contain a comma-delimited list of headers
Should we really go down that rabbit hole of splitting strings? What would be the use-case?

2023-08-11 11:00 UTC, alexandre-daubois commented on src/Symfony/Component/HttpFoundation/RequestMatcher/HeaderRequestMatcher.php
> + * Checks the HTTP headers of a Request.
That's right, I updated the description :slightly_smiling_face:

2023-08-11 11:02 UTC, alexandre-daubois commented on src/Symfony/Component/HttpFoundation/RequestMatcher/HeaderRequestMatcher.php
> +     *                                 Strings can contain a comma-delimited list of headers
Actually, it is to keep consistency with other request matchers, as many other ones accept a comma delimited list

2023-08-11 12:26 UTC, norkunas commented on src/Symfony/Component/HttpFoundation/RequestMatcher/HeaderRequestMatcher.php
> +        $this->headers = array_reduce(array_map(strtolower(...), (array) $headers), static fn (array $headers, string $header) => array_merge($headers, preg_split('/\s*,\s*/', $header)), []);
`strtolower` is not needed I think as request header checking matches case insensitive

2023-08-16 07:53 UTC, alexandre-daubois commented on src/Symfony/Component/HttpFoundation/RequestMatcher/HeaderRequestMatcher.php
> +        $this->headers = array_reduce(array_map(strtolower(...), (array) $headers), static fn (array $headers, string $header) => array_merge($headers, preg_split('/\s*,\s*/', $header)), []);
You're right! Removed :slightly_smiling_face:

2023-08-17 06:52 UTC, alexandre-daubois commented
Status: Needs Review

2023-08-17 09:05 UTC, GromNaN requested changes

2023-08-17 09:05 UTC, GromNaN commented on src/Symfony/Component/HttpFoundation/RequestMatcher/HeaderRequestMatcher.php
> +     *                                 Strings can contain a comma-delimited list of headers
The tests on splitting strings are missing.

2023-08-17 09:59 UTC, alexandre-daubois commented
That's right! I added the test here and also in https://github.com/symfony/symfony/pull/51324

2023-08-17 10:00 UTC, alexandre-daubois commented on src/Symfony/Component/HttpFoundation/RequestMatcher/HeaderRequestMatcher.php
> +     *                                 Strings can contain a comma-delimited list of headers
That's right! I added the test here and also in https://github.com/symfony/symfony/pull/51324

2023-10-02 08:42 UTC, alexandre-daubois commented
Rebased and conflicts fixed

2023-10-03 08:59 UTC, stof approved these changes

2023-10-23 17:44 UTC, 94noni approved these changes

2023-10-23 18:16 UTC, GromNaN approved these changes

2023-12-05 15:59 UTC, alexandre-daubois commented
Rebased and conflicts fixed :slightly_smiling_face: (as well as [this other related PR](https://github.com/symfony/symfony/pull/51324))

2023-12-29 22:17 UTC, OskarStark approved these changes

2024-02-03 16:10 UTC, fabpot approved these changes

2024-02-03 16:12 UTC, fabpot commented
Thank you @alexandre-daubois.

2024-02-03 16:12 UTC, merged