[Security] Prevent creating session in stateless firewalls
symfony/symfony pull request #51350
Opened 2023-08-11 03:46 UTC by Seb33300

| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix https://github.com/symfony/symfony/issues/51319
| License       | MIT
| Doc PR        | 

Please check related issue for details.

2023-08-16 01:30 UTC, chalasr requested changes
Please add test cases with `_stateless => true` for both success and failure handlers to prevent regressions

2023-08-16 08:26 UTC, Seb33300 commented
> Please add test cases with `_stateless => true` for both success and failure handlers to prevent regressions

@chalasr tests added

2023-08-20 16:05 UTC, stloyd approved these changes

2023-08-21 14:21 UTC, stloyd commented
@wouterj @chalasr Could you have a second look at this?

I can confirm the fix on HWIOAuthBundle. Before:
```
PHPUnit 9.6.11 by Sebastian Bergmann and contributors.

Testing /Users/stloyd/Documents/HWIOAuthBundle/tests/Functional

<!-- Session was used while the request was declared stateless. (500 Internal Server Error) -->
// error page printed
```

After:
```
PHPUnit 9.6.11 by Sebastian Bergmann and contributors.

Testing /Users/stloyd/Documents/HWIOAuthBundle/tests/Functional

Time: 00:00.090, Memory: 18.00 MB

OK (1 test, 4 assertions)
```

2023-08-21 15:12 UTC, mtarld approved these changes

2023-08-21 15:12 UTC, mtarld commented on src/Symfony/Component/Security/Http/Tests/Authentication/DefaultAuthenticationFailureHandlerTest.php
> +        $this->request->attributes = new ParameterBag(['_stateless' => false]);
I don't think this is needed, as the `getBoolean` will default to `false` :slightly_smiling_face:

2023-08-21 15:42 UTC, Seb33300 commented on src/Symfony/Component/Security/Http/Tests/Authentication/DefaultAuthenticationFailureHandlerTest.php
> +        $this->request->attributes = new ParameterBag(['_stateless' => false]);
`attributes` property is not defined in the request mock so it needs to be defined at least with a `new ParameterBag(()`.

And I prefer to keep the `['_stateless' => false]` explicit so we can understand why we need `attributes` to be defined.

2023-08-25 08:53 UTC, stloyd commented
@fabpot / @nicolas-grekas or anyone else can check this fix? I would love to have it in near 6.3 release

2023-08-25 09:26 UTC, Seb33300 commented
August is usually a period of holidays in europe so @chalasr and @wouterj may not be available this week.
Let's see next week :)

2023-08-25 12:39 UTC, stof approved these changes

2023-08-25 19:41 UTC, chalasr approved these changes

2023-08-25 19:43 UTC, chalasr commented
Thank you @Seb33300.

2023-08-25 19:44 UTC, merged