[Messenger] - phpdoc template for TransportFactoryInterface
symfony/symfony pull request #51374
Opened 2023-08-13 09:24 UTC by Ferror

Improved a little bit phpdocs when dealing with Transport & Transport Factory Interface.

2023-08-13 11:43 UTC, derrabus requested changes
If you make the `TransportFactoryInterface` generic, you need to update the PHPDoc on every implementation accordingly.

2023-08-13 11:43 UTC, derrabus commented on src/Symfony/Component/Messenger/Transport/TransportFactoryInterface.php
> + * @template T
Right now, `T` would be of type mixed, which is _a little_ too wide. Moreover, we should use a more expressive template variable name and allow covariance.

```suggestion
 * @template-covariant TTransport of TransportInterface
```

2023-08-13 11:43 UTC, derrabus commented on src/Symfony/Component/Messenger/Bridge/AmazonSqs/Transport/AmazonSqsTransport.php
> +    public function reset(): void
That's a BC break. We can't do that in a minor release.

2023-08-13 11:43 UTC, derrabus commented on src/Symfony/Component/Messenger/Bridge/AmazonSqs/Transport/AmazonSqsTransport.php
> +     */
This block serves no purpose. Let's remove it?

2023-08-13 11:43 UTC, derrabus commented on src/Symfony/Component/Messenger/Bridge/AmazonSqs/Transport/AmazonSqsTransport.php
> +    private function getReceiver(): MessageCountAwareInterface&ReceiverInterface
Let's postpone this change to 7.0 where we can use this type for the constructor parameter and the property as well?

2023-08-13 19:33 UTC, Ferror commented
> If you make the `TransportFactoryInterface` generic, you need to update the PHPDoc on every implementation accordingly.

Did as requested :)

2023-09-04 10:44 UTC, Ferror commented
@derrabus WDYT?

2023-09-04 10:46 UTC, derrabus approved these changes

2023-09-04 12:03 UTC, kbond approved these changes

2023-09-05 06:01 UTC, fabpot approved these changes

2023-09-05 06:02 UTC, fabpot commented
Thank you @Ferror.

2023-09-05 06:02 UTC, merged

2023-09-06 09:51 UTC, ro0NL commented
wasnt updating the returntypes on `createTransport` sufficient? eg. `SchedulerTransportFactory`

2023-09-06 14:44 UTC, Ferror commented
> wasnt updating the returntypes on `createTransport` sufficient? eg. `SchedulerTransportFactory`

Unfortunately not. SchedulerTransportFactory shares Transport Interface therefore by pipeline config it was also required to change to add that.

2023-09-06 14:51 UTC, ro0NL commented
i mean why prefer templating a factory when the return type is already sufficient?

https://github.com/symfony/symfony/blob/2bac801f8a4cba02e8ecc840fa7bf512034f860a/src/Symfony/Component/Scheduler/Messenger/SchedulerTransportFactory.php#L34

or what does this PR solve? :thinking:

2023-09-06 14:55 UTC, stof commented
If we never benefit from the generic types in places in which we inject a TransportFactory but only in places using a concrete factory explicitly, we could indeed avoid making it generic but using a refined return type...

2023-09-08 14:52 UTC, ro0NL commented
i guess we do :rocket: