WIP: [Workflow] deprecate `GuardEvent::getContext` method
symfony/symfony pull request #51484
Opened 2023-08-25 12:43 UTC by hhamon

| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | yes
| Tickets       | ~
| License       | MIT
| Doc PR        | ~

2023-08-25 13:03 UTC, lyrixx requested changes

2023-08-25 13:03 UTC, lyrixx commented on UPGRADE-6.4.md
> +* Deprecate `GuardEvent::getContext` method. It will throw a `\BadMethodCallException` in 7.0
```suggestion
* Deprecate `GuardEvent::getContext()` method
```

it'll be remove in 7.0

2023-08-25 13:03 UTC, lyrixx commented on src/Symfony/Component/Workflow/CHANGELOG.md
> + * Deprecate `GuardEvent::getContext` method. It will throw a `\BadMethodCallException` in 7.0
```suggestion
 * Deprecate `GuardEvent::getContext()` method
```

2023-08-25 13:03 UTC, lyrixx commented on src/Symfony/Component/Workflow/Event/GuardEvent.php
> +        @trigger_error(sprintf('The %s::getContext method is deprecated and will throw a \BadMethodCallException exception in next major version. You should not longer call this method as it always r
```suggestion
        trigger_deprecation('symfony/workflow', '6.4', 'The %s::getContext() method is deprecated and will be removed in 7.0. You should not longer call this method as it always returns an empty array when invoked within a guard listener.', __CLASS__);
```

2023-08-26 10:47 UTC, hhamon commented on UPGRADE-6.4.md
> +* Deprecate `GuardEvent::getContext` method. It will throw a `\BadMethodCallException` in 7.0
Fixed!

2023-08-26 10:47 UTC, hhamon commented on src/Symfony/Component/Workflow/CHANGELOG.md
> + * Deprecate `GuardEvent::getContext` method. It will throw a `\BadMethodCallException` in 7.0
Fixed!

2023-08-26 10:47 UTC, hhamon commented on src/Symfony/Component/Workflow/Event/GuardEvent.php
> +        @trigger_error(sprintf('The %s::getContext method is deprecated and will throw a \BadMethodCallException exception in next major version. You should not longer call this method as it always r
Fixed!

2023-08-27 10:58 UTC, lyrixx approved these changes
Thanks

2023-08-30 06:26 UTC, fabpot approved these changes

2023-08-30 06:27 UTC, fabpot commented
Thank you @hhamon.

2023-08-30 06:28 UTC, merged