[Messenger] Added generics for message in envelope
symfony/symfony pull request #51546
Opened 2023-09-04 08:58 UTC by RikudouSage

| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| License       | MIT

Adds generics to the Envelope class which allows user code to typehint it.

I created this because I have this piece of code which would benefit from it:

```
    /**
     * @template T of object
     * @param class-string<T> $type
     * @return array<Envelope<T>>
     */
    public function getJobsByType(string $type): array
    {
    }
```

2023-09-04 09:13 UTC, RikudouSage commented
I don't quite understand why the Psalm errors happen.

2023-09-07 06:21 UTC, RikudouSage commented
Can I get some assistance, please?

2023-09-12 13:44 UTC, derrabus commented
> I don't quite understand why the Psalm errors happen.

You used a template type on a static method that you did not declare. Static methods don't inherit template types from their class, you have to use a method-level template type.

2023-10-07 11:21 UTC, ro0NL commented on src/Symfony/Component/Messenger/Envelope.php
> +     * @var TMessage|Envelope<TMessage>
a union wont really help us with autocompletion isnt it?

2023-10-08 11:09 UTC, wouterj requested changes

2023-10-08 11:09 UTC, wouterj commented on src/Symfony/Component/Messenger/Envelope.php
>       */
This is wrong, the method is supposed to handle any `object`, see line 56.

I think we can make it something like this:

```suggestion
     * @template TNewMessage of object
     *
     * @param TNewMessage      $message
     * @param StampInterface[] $stamps
     *
     * @return self<TNewMessage>
     */
```

2023-10-12 16:45 UTC, ro0NL commented
`MessageBusInterface` should be updated btw

2024-02-03 18:10 UTC, fabpot commented
Closing as there is no more activity. Feel free to reopen when you have time.

2024-02-03 18:10 UTC, closed without merging