[Scheduler] Allow modifying the schedule at runtime and recalculate heap
symfony/symfony pull request #51553
Opened 2023-09-04 12:09 UTC by Jeroeny

| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #... 
| License       | MIT

Schedules are created statically by a ScheduleProviderInterface. This is nice if you have a small app with some predetermined scheduled actions. But if you want to schedule business logic dynamically, e.g. have admins Crud a schedule in the DB, then the schedule needs to be updateable at runtime. This also allows for the app to re-add schedules that have returned `null` as nextRunDate in the past (making them unscheduled) and to remove schedules.

2023-09-07 15:08 UTC, kbond commented
Interesting, is this a companion PR for #51542?

2023-09-07 16:05 UTC, Jeroeny commented
@kbond they don't depend on each other. But when both of them are merged, it enables a lot of capabilities for the Scheduler.

2023-09-16 16:43 UTC, fabpot requested changes
Can you add some usage example in the PR description?

2023-09-16 16:43 UTC, fabpot commented on src/Symfony/Component/Scheduler/Schedule.php
Blank line to be removed

2023-09-16 16:43 UTC, fabpot commented on src/Symfony/Component/Scheduler/CHANGELOG.md
> + * Allow modifying the Schedule at runtime and recalculate heap
```suggestion
 * Allow modifying the Schedule at runtime
```

(the heap is an implementation detail)

2023-09-16 16:43 UTC, fabpot commented on src/Symfony/Component/Scheduler/Schedule.php
> +    public function restart(bool $restart = null): bool
For more clarity, I would split this method: `setRestart(bool)` and `shouldRestart(): bool`

2023-09-16 16:43 UTC, fabpot commented on src/Symfony/Component/Scheduler/Schedule.php
> +    private bool $restart = false;
```suggestion
    private bool $shouldRestart = false;
```

2023-09-16 16:43 UTC, fabpot commented on src/Symfony/Component/Scheduler/Schedule.php
> +    public function remove(RecurringMessage $message): static
```suggestion
    /**
     * @return $this
     */
    public function remove(RecurringMessage $message): static
```

2023-09-26 16:04 UTC, fabpot approved these changes

2023-09-26 16:04 UTC, fabpot commented on src/Symfony/Component/Scheduler/CHANGELOG.md
> + * Allow modifying the Schedule at runtime
```suggestion
 * Allow modifying Schedule instances at runtime
```

2023-09-26 16:05 UTC, fabpot commented
Thank you @Jeroeny.

2023-09-26 16:05 UTC, merged

2024-02-17 17:21 UTC, Sophikitis commented
Hi ! 

Do you have any examples of use?
I'm trying to implement this, to dynamically retrieving frequencies and modifying the behavior with a custom event. 
But this->schedule is always null in the listener function. 
When I retrieve the instance from $this->getSchedule() I get an instance but when I try to delete a message or add one, nothing happens.

And as far as I understand, there's no documentation for this feature.
I'll try my luck here. 
Thanks in advance

2024-04-16 09:44 UTC, Hanmac commented
@fabpot I'm also looking for an example, currently i uses this Doctrine Query to build the Schedule

```
    public function getSchedule(): Schedule
    {
        $result = new Schedule();

        $repo = $this->manager->getRepository(Terminal::class);
        $q = $repo->createQueryBuilder('t');

        $q->where('t.status = true AND t.automatic = true');

        foreach ($q->getQuery()->getResult() as $r) {
            /**
             * @var Terminal $r
             */
            $result->add(RecurringMessage::cron(
                $r->getCronExpr(),
                new KassenschlussTask($r->getId()),
                $this->timezoneDetector->getTimezone())
            );
        }
        return $result;
    }
```

because each object might have its own CronExpr, each of them needs its own RecurringMessage

and how do i handle if they get disabled?

2024-04-17 10:57 UTC, Hanmac commented
@Sophikitis while maybe not the best way, i found `StopWorkersCommand`

```php
$cacheItem = $this->restartSignalCachePool->getItem(StopWorkerOnRestartSignalListener::RESTART_REQUESTED_TIMESTAMP_KEY);
$cacheItem->set(microtime(true));
$this->restartSignalCachePool->save($cacheItem);
```

i used `[AsEntityListener]` on my DB Entities, and then on `Events::postRemove, Events::postUpdate, Events::postPersist` i stop the messenger worker

2025-12-10 00:18 UTC, gremo commented
I'm facing the same issue when fetching messages from the database. I haven't found a reliable way to make it work. We really need some documentation and a simple example to help users!

2026-01-18 17:18 UTC, gremo commented
Ping. Is it possible that no one has even the faintest idea of how to update the scheduler without restarting the worker, which in some cases can be completely impractical?

This need to be documentend because it's so confusing.