[Notifier] Fix Smsmode HttpClient mandatory headers
symfony/symfony pull request #51629
Opened 2023-09-11 17:12 UTC by inwebo

| Q             | A
| ------------- | ---
| Branch?      | 6.3
| Bug fix?      | yes
| New feature? | no
| Deprecations? | no
| Tickets | no
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

As mentioned in the documentation https://dev.smsmode.com/sms/v1/home in section Content-Type & URL Encoding.

HTTP request and response bodies are JSON objects, which is why Accept and Content-Type headers are mandatory and are implicitly added when the request is executed with the TEST button. If the Accept header is missing, a Not Acceptable (406) HTTP status code is returned. (Accept: application/json) The Content-Type header is only needed with POST and PATCH methods. If it is missing, an Unsupported Media Type (415)

2023-09-11 17:20 UTC, derrabus commented
Thank you. Please add a test.

2023-09-12 07:32 UTC, inwebo commented
Hello,

I need help there, i don't get it why my simple PR is failing with Redis extension relay tests.

Regards

2023-09-12 07:35 UTC, inwebo commented
Hello,

I need help. I don't get it why my simple PR is failing with RedisProxiesTest::testRelayProxy ?

Regards

2023-09-12 08:50 UTC, stof requested changes

2023-09-12 08:50 UTC, stof commented on src/Symfony/Component/Notifier/Bridge/Smsmode/SmsmodeTransport.php
> +                'Content-type' => 'application/json',
tis content-type is added automatically when using the `json` option to build the body, so it is useless to add it explicitly.

2023-09-12 08:50 UTC, stof commented on src/Symfony/Component/Notifier/Bridge/Smsmode/Tests/SmsmodeTransportTest.php
> +    public function testIfMandatoryHttpClientRequestHeaderContentTypeIsMissing()
This is not testing anything here as you are not covering any code of the transport (you are not even using the transport)

2023-09-12 15:55 UTC, nicolas-grekas commented
> i don't get it why my simple PR is failing with Redis extension relay tests.

It's unrelated, you can ignore these failures and focus on your changes.

2023-09-19 12:22 UTC, nicolas-grekas commented
Thank you @inwebo.

2023-09-19 12:22 UTC, merged