Add PHPDoc to attributes
symfony/symfony pull request #51987
Opened 2023-10-11 09:53 UTC by squrious

| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Part of #51920
| License       | MIT

Add PHPDoc to attributes in `Symfony\Bridge\Doctrine` and `Symfony\Bridge\Twig`.

2023-10-12 09:54 UTC, stof commented on src/Symfony/Bridge/Doctrine/Attribute/MapEntity.php
> +         * The entity class.
`@var class-string|null`

2023-10-12 09:54 UTC, stof commented on src/Symfony/Bridge/Doctrine/Attribute/MapEntity.php
> +         * An expression to fetch the entity. The following variables are available:
this should mention that this is an expression using the ExpressionLanguage syntax, as done in the other PR.

2023-10-12 09:54 UTC, stof commented on src/Symfony/Bridge/Doctrine/Attribute/MapEntity.php
> +         * - Any route wildcards are available as variables.
request attributes, not route wildcards (which is not even a name used in Symfony anywhere)

2023-10-12 09:54 UTC, stof commented on src/Symfony/Bridge/Doctrine/Attribute/MapEntity.php
> +         * The key is the route placeholder name and the value is the Doctrine property name.
`@var array<string, string>|null`

2023-10-12 09:54 UTC, stof commented on src/Symfony/Bridge/Doctrine/Attribute/MapEntity.php
> +         * one or more properties so that not all are used.
`@var string[]|null`

2023-10-12 09:54 UTC, stof commented on src/Symfony/Bridge/Doctrine/Attribute/MapEntity.php
> +         * find by the primary key.
``@var string[]|string|null`

2023-10-12 09:54 UTC, stof commented on src/Symfony/Bridge/Doctrine/Validator/Constraints/UniqueEntity.php
> +     * @param bool|array|string $ignoreNull       The combination of fields that ignore null values
```suggestion
     * @param bool|string[]|string $ignoreNull       The combination of fields that ignore null values
```

2023-10-12 09:54 UTC, stof commented on src/Symfony/Bridge/Twig/Attribute/Template.php
> + * Define the template to render in the controller.
`$vars` should be documented as `string[]|null`

2023-10-12 11:44 UTC, squrious commented on src/Symfony/Bridge/Doctrine/Attribute/MapEntity.php
> +         * The entity class.
Thanks for your comments! I made the changes here and in the others as well

2023-11-21 13:41 UTC, GromNaN approved these changes

2023-12-29 22:13 UTC, OskarStark commented
rebased ✅

2023-12-29 22:14 UTC, OskarStark requested changes
Please use `@param` annotations

2024-01-02 10:46 UTC, squrious commented
> Please use `@param` annotations

Do you mean replacing '@var` with `@param` in CPP or moving descriptions to the constructor doc block?

2024-01-02 12:24 UTC, OskarStark commented
Yes please move it to the constructor doc block and use `@param`

2024-01-02 13:48 UTC, OskarStark approved these changes

2024-01-02 16:20 UTC, nicolas-grekas approved these changes

2024-01-05 08:20 UTC, nicolas-grekas commented
Thank you @squrious.

2024-01-05 08:20 UTC, merged