Add ext-pcntl to composer.json
symfony/symfony pull request #52129
Opened 2023-10-18 08:42 UTC by beesofts

Since ConsumeMessagesCommand.php uses SIGTERM and SIGINT, ext-pcntl must be available on system

2023-10-18 08:45 UTC, fabpot commented
It's optional.
Maybe #51791 is what you're looking for.

2023-10-18 08:57 UTC, derrabus requested changes
This change will basically forbid installing messenger on Windows. 👎🏻

2023-10-18 08:59 UTC, closed without merging

2023-11-14 16:22 UTC, SerheyDolgushev commented
@beesofts can you please check https://github.com/symfony/symfony/issues/52586 and confirm it describes your case?

2023-11-14 16:33 UTC, beesofts commented
in my point of view, https://github.com/symfony/symfony/pull/51791/files did the job