Closes #51936-Added Missing translations for Czech (cs) in validators…
symfony/symfony pull request #52239
Opened 2023-10-22 20:18 UTC by shubhalgupta

….cs.xlf file

| Q             | A
| ------------- | ---
| Branch?       | 6.4 for features / 5.4 or 6.3 for bug fixes 
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Issues        | Fix #51936  
| License       | MIT

2023-10-22 20:20 UTC, shubhalgupta commented
@carsonbot now please review!

2023-10-23 15:03 UTC, Nyholm commented
Hey. 

Thank you for this PR. Are you a native Czech speaker? 
I tried my best to verify this with Google translate and it looks okey. 

Do you know a native that could verify this?

2023-10-23 15:05 UTC, shubhalgupta commented
Yes, I am a native speaker!



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
10/23/23,
08:35:15 PM

On Mon, Oct 23, 2023 at 8:33 PM Tobias Nyholm ***@***.***>
wrote:

> Hey.
>
> Thank you for this PR. Are you a native Czech speaker?
> I tried my best to verify this with Google translate and it looks okey.
>
> Do you know a native that could verify this?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/symfony/symfony/pull/52239#issuecomment-1775411132>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZTJMWXE4RM4V3EZ6VWQEADYA2BNZAVCNFSM6AAAAAA6LEFMF2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTONZVGQYTCMJTGI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-10-23 15:06 UTC, shubhalgupta commented
@Nyholm please do merge this!

2023-10-23 15:08 UTC, Nyholm approved these changes
Lovely. =)

I'll be happy to approve this. A second maintain will review and merge this if they like this as much as I do. 

Thank you for your work!

2023-10-23 15:09 UTC, shubhalgupta commented
@Nyholm who is the second maintainer?

2023-10-23 15:10 UTC, shubhalgupta commented
And thanks for your approval @Nyholm

2023-10-23 15:11 UTC, Nyholm commented
> @Nyholm who is the second maintainer?

There are a few of us. See https://symfony.com/doc/current/contributing/code/core_team.html
Im sure someone will look at this in the next 2-3 days.

2023-10-23 15:17 UTC, shubhalgupta commented
@fabpot, @nicolas-grekas  kindly review this!

2023-10-23 15:19 UTC, stof approved these changes

2023-10-23 15:20 UTC, shubhalgupta commented
@stof can you merge this, please!

2023-10-24 03:59 UTC, shubhalgupta commented
@Nyholm can you please get it merged?

2023-10-24 09:21 UTC, OskarStark commented on src/Symfony/Component/Validator/Resources/translations/validators.cs.xlf
> +           </trans-unit>
```suggestion
            <trans-unit id="104">
                <source>The filename is too long. It should have {{ filename_max_length }} character or less.|The filename is too long. It should have {{ filename_max_length }} characters or less.</source>
                <target>Název souboru je příliš dlouhý. Měl by obsahovat {{ filename_max_length }} znak nebo méně.|Název souboru je příliš dlouhý. Měl by obsahovat {{ filename_max_length }} znaky nebo méně.</target>
            </trans-unit>
            <trans-unit id="105">
                <source>The password strength is too low. Please use a stronger password.</source>
                <target>Síla hesla je příliš nízká. Použijte silnější heslo, prosím.</target>
            </trans-unit>
            <trans-unit id="106">
                <source>This value contains characters that are not allowed by the current restriction-level.</source>
                <target>Tato hodnota obsahuje znaky, které nejsou povoleny aktuálním úrovní omezení.</target>
            </trans-unit>
           <trans-unit id="107">
               <source>Using invisible characters is not allowed.</source>
               <target>Používání neviditelných znaků není povoleno.</target>
           </trans-unit>
           <trans-unit id="108">
               <source>Mixing numbers from different scripts is not allowed.</source>
               <target>Kombinování čísel z různých písem není povoleno.</target>
           </trans-unit>
           <trans-unit id="109">
               <source>Using hidden overlay characters is not allowed.</source>
               <target>Použití skrytých překrývajících znaků není povoleno.</target>
           </trans-unit>
```

2023-10-24 09:22 UTC, OskarStark requested changes
Please fix the indentation, thanks

2023-10-24 14:38 UTC, shubhalgupta commented
@OskarStark now kindly check!

2023-10-24 14:51 UTC, xabbuh commented
I have asked a Czech colleague to review the changes

2023-10-24 15:00 UTC, jan-simbera requested changes
Hi, there are some changes in the wording of the Validation Error Messages, which should be implemented to be correct in Czech.

2023-10-24 15:00 UTC, jan-simbera commented on src/Symfony/Component/Validator/Resources/translations/validators.cs.xlf
> +                <target>Název souboru je příliš dlouhý. Měl by obsahovat {{ filename_max_length }} znak nebo méně.|Název souboru je příliš dlouhý. Měl by obsahovat {{ filename_max_length }} znaky neb
Hi, the correct wording should be: Měl by obsahovat {{ filename_max_length }} znaků nebo méně. Same for the filename length, but it could vary, as for 2,3,4 it should be znaky, for the others znaků and for 1 znak.

2023-10-24 15:00 UTC, jan-simbera commented on src/Symfony/Component/Validator/Resources/translations/validators.cs.xlf
> +                <target>Tato hodnota obsahuje znaky, které nejsou povoleny aktuálním úrovní omezení.</target>
The correct wording should be: Tato hodnota obsahuje znaky, které nejsou povoleny aktuální úrovní omezení.

2023-10-24 17:37 UTC, stof commented on src/Symfony/Component/Validator/Resources/translations/validators.cs.xlf
> +                <target>Název souboru je příliš dlouhý. Měl by obsahovat {{ filename_max_length }} znak nebo méně.|Název souboru je příliš dlouhý. Měl by obsahovat {{ filename_max_length }} znaky neb
Well, the varying part is supported by Symfony: for Czech, the Symfony translation format expects 3 variants for pluralization, not 2.

2023-10-24 18:25 UTC, jan-simbera commented
Hi, i have corrected the pluralization as i forgot it is also different for
1. So we have 1 - znak, 2,3,4 - znaky and 5+ znaků.

Sorry, missed thats special case in the first part.


Am Di., 24. Okt. 2023 um 19:37 Uhr schrieb Christophe Coevoet <
***@***.***>:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In
> src/Symfony/Component/Validator/Resources/translations/validators.cs.xlf
> <https://github.com/symfony/symfony/pull/52239#discussion_r1370588340>:
>
> > @@ -402,6 +402,30 @@
>                  <source>The value of the netmask should be between {{ min }} and {{ max }}.</source>
>                  <target>Hodnota masky sítě musí být mezi {{ min }} a {{ max }}.</target>
>              </trans-unit>
> +            <trans-unit id="104">
> +                <source>The filename is too long. It should have {{ filename_max_length }} character or less.|The filename is too long. It should have {{ filename_max_length }} characters or less.</source>
> +                <target>Název souboru je příliš dlouhý. Měl by obsahovat {{ filename_max_length }} znak nebo méně.|Název souboru je příliš dlouhý. Měl by obsahovat {{ filename_max_length }} znaky nebo méně.</target>
>
> Well, the varying part is supported by Symfony: for Czech, the Symfony
> translation format expects 3 variants for pluralization, not 2.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/symfony/symfony/pull/52239#discussion_r1370588340>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZ5C5Y3WSSNJ6PIDTFDU3M3YA74GDAVCNFSM6AAAAAA6LEFMF2VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTMOJVGUYTCOBZGU>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>


-- 


*Jan Simbera*

Software Developer

+49 221 16 53 54 57

[image: https://www.xing.com/profile/Tom_Ullner/cv]

QOSSMIC GmbH | Balthasarstraße 79 | 50670 Köln | Geschäftsführung:
Alexandra Sticht, Thomas Fräger, Eric Meurers | AG Köln HRB73031 | USt-Id.:
DE279166514

2023-11-20 14:17 UTC, nicolas-grekas commented on src/Symfony/Component/Validator/Resources/translations/validators.cs.xlf
> +                <target>Název souboru je příliš dlouhý. Měl by obsahovat {{ filename_max_length }} znak nebo méně.|Název souboru je příliš dlouhý. Měl by obsahovat {{ filename_max_length }} znaky neb
@jan-simbera thanks for the review. Is that what you mean?

```suggestion
                <target>Název souboru je příliš dlouhý. Měl by obsahovat {{ filename_max_length }} znaků nebo méně.|Název souboru je příliš dlouhý. Měl by obsahovat {{ filename_max_length }} znaky nebo méně.|Název souboru je příliš dlouhý.|Měl by obsahovat {{ filename_max_length }} znak nebo méně.</target>
```

2023-11-20 14:18 UTC, nicolas-grekas commented on src/Symfony/Component/Validator/Resources/translations/validators.cs.xlf
> +                <target>Tato hodnota obsahuje znaky, které nejsou povoleny aktuálním úrovní omezení.</target>
```suggestion
                <target>Tato hodnota obsahuje znaky, které nejsou povoleny aktuální úrovní omezení.</target>
```

2023-11-20 14:22 UTC, nicolas-grekas commented
Thank you @shubhalgupta.

2023-11-20 14:22 UTC, merged