[Dotenv] Add --dotenv-path option to DotenvDumpCommand
symfony/symfony pull request #52553
Opened 2023-11-11 14:27 UTC by alexndlm

| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Issues        | 
| License       | MIT

2023-11-11 15:11 UTC, alexndlm commented
@carsonbot find reviewer

2023-11-12 10:15 UTC, ghost requested changes

2023-11-12 10:15 UTC, ghost commented on src/Symfony/Component/Dotenv/Command/DotenvDumpCommand.php
> +            ->addOption('dotenv-path', null, InputOption::VALUE_OPTIONAL, 'Path to dot-env files')
Let's use `.env` instead of `dot-env` in the description as it's already in the other options/arguments.

2023-11-12 10:15 UTC, ghost commented on src/Symfony/Component/Dotenv/Command/DotenvDumpCommand.php
> +        if ($input->getOption('dotenv-path')) {
I think this class would like the following notation more: `$dotenvPath = $projectDir.'/'.($input->getOption('dotenv-path') ?? $config['dotenv_path'] ?? '.env');`

2023-11-12 12:37 UTC, alexndlm commented on src/Symfony/Component/Dotenv/Command/DotenvDumpCommand.php
> +        if ($input->getOption('dotenv-path')) {
Done

2023-11-12 12:37 UTC, alexndlm commented on src/Symfony/Component/Dotenv/Command/DotenvDumpCommand.php
> +            ->addOption('dotenv-path', null, InputOption::VALUE_OPTIONAL, 'Path to dot-env files')
Done

2023-11-12 14:39 UTC, ghost commented on src/Symfony/Component/Dotenv/Command/DotenvDumpCommand.php
> +            ->addOption('dotenv-path', null, InputOption::VALUE_OPTIONAL, 'Path to .env files')
Actually this is a path to .env file, not file**s**.

2023-11-12 14:39 UTC, ghost commented on src/Symfony/Component/Dotenv/Command/DotenvDumpCommand.php
>          $config += (is_file($composerFile) ? json_decode(file_get_contents($composerFile), true) : [])['extra']['runtime'] ?? [];
This line looks like you can set `dotenv_path` in your composer.json file:
```json
"extra": {
  "runtime": {
    "dotenv_path": "some/path/.env"
  }
}
```
In that case this PR would not be needed.

2023-11-12 14:39 UTC, ghost commented on src/Symfony/Component/Dotenv/Command/DotenvDumpCommand.php
> -        $dotenvPath = $projectDir.'/'.($config['dotenv_path'] ?? '.env');
I have second thoughts on this. Maybe we should set the `$config['dotenv_path']` if this option was passed to the command and then leave this line as it was before?

2023-11-13 06:56 UTC, alexndlm commented on src/Symfony/Component/Dotenv/Command/DotenvDumpCommand.php
>          $config += (is_file($composerFile) ? json_decode(file_get_contents($composerFile), true) : [])['extra']['runtime'] ?? [];
This is needed for cases when the .env file name contains an env name, like a `local.env`, `dev.env`, `prod.env`.

2023-11-13 06:58 UTC, alexndlm commented on src/Symfony/Component/Dotenv/Command/DotenvDumpCommand.php
> -        $dotenvPath = $projectDir.'/'.($config['dotenv_path'] ?? '.env');
I think it doesn't matter.

2023-11-13 06:58 UTC, alexndlm commented on src/Symfony/Component/Dotenv/Command/DotenvDumpCommand.php
> +            ->addOption('dotenv-path', null, InputOption::VALUE_OPTIONAL, 'Path to .env files')
Done

2023-11-13 08:15 UTC, ghost approved these changes

2023-11-20 13:23 UTC, nicolas-grekas commented
What about closing this PR in favor of #52638?

2023-11-20 14:50 UTC, alexndlm commented
I don't mind.

2023-11-20 14:50 UTC, closed without merging