[HttpFoundation]Fix/parameterbag get method
symfony/symfony pull request #52593
Opened 2023-11-15 12:27 UTC by wandesnet

| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no
| Issues        | 
| License       | MIT

This pull request replaces the **array_key_exists** check with the **null coalescing operator**. The change aims to improve the robustness and consistency of the code.

Problem:

Using **array_key_exists** in this specific context results in a problem identified in the **basename()** function. When encountering a null value for parameter ($path), the function call becomes obsolete, generating the following warning message:

`basename(): Passing null to parameter ($path) of type string is deprecated in Request.php`

This is because **array_key_exists** returns true when an array's key matches a null value, which leads to deprecation of the **basename()** function.

Solution:

Replacing the null navigation **operator (??)** provides a safer approach by properly handling null values. This solves the problem with the **basename()** function and contributes to improving the overall stability of the code.

2023-11-15 12:34 UTC, xabbuh commented
This change breaks backwards compatibility (see the failing tests).

2023-11-15 13:39 UTC, wandesnet commented
> This change breaks backwards compatibility (see the failing tests).

I understand, I noticed that it breaks in all versions, an alternative would be to force the retention type to (string) of the ->get() method when calling it, that is, in basename() in the place where this bug is occurring.
Example:

`basename((string) $this->server->get('SCRIPT_NAME', ''))` file Request.php on line 1802

2023-11-15 14:18 UTC, ghost requested changes
I'm sorry but I don't understand your issue. 

Do you get a deprecation notice from `basename` function because `ParameterBag:get()` returns null? 
Then this is on your side to code against such a case (e.g. add if statement)

2023-11-15 14:18 UTC, ghost commented on .gitignore
> +.idea/
Files that are not releated to the project should not be commited here but ignored in `.git/info/exclude` .

2023-11-15 15:24 UTC, wandesnet commented
> basename(): Passing null to parameter ($path) of type string is deprecated in Request.php

This is not a critical bug, but a warning message is appearing in my application log, `basename(): Passing null to parameter ($path) of type string is deprecated in Request.php.`

This happens because the **basename()** function expects to receive a string as a parameter, but is receiving null.

2023-11-15 15:25 UTC, wandesnet commented on .gitignore
> +.idea/
> Files that are not releated to the project should not be commited here but ignored in `.git/info/exclude` .

I didn't know, thanks for letting me know.

2023-11-15 15:28 UTC, xabbuh commented
I would first investigate why that value is `null`. Can you create a small example application that allows to reproduce?

2023-11-15 15:37 UTC, stof commented
If your parameter bag contains an explicit `null` value, I find it totally expected that you get a `null` value when reading it. And our tests even ensure that this behavior happens so changing that would be a BC break.

The fact that your own logic does not properly handle `null` values that it receives is not a bug in ParameterBag.

2023-11-15 15:38 UTC, ghost commented
~The only line where `Request` class on the current 5.4 branch calls `basename()` with a parameter that can possibly be null is:~
https://github.com/symfony/symfony/blob/4be970654b4a049374318c06f83cf4a80f9a3a80/src/Symfony/Component/HttpFoundation/Request.php#L1932

~However in 6.4 it's fine:~
https://github.com/symfony/symfony/blame/de3d115496c0ab76d9849896e9d4c8a15b91eb1f/src/Symfony/Component/HttpFoundation/Request.php#L1800

~but this was fixed in v4.4.42.~

~Weird...~

2023-11-15 15:53 UTC, ghost commented
Got it:

on 5.4 branch https://github.com/symfony/symfony/blame/4be970654b4a049374318c06f83cf4a80f9a3a80/src/Symfony/Component/HttpFoundation/Request.php#L1932

on 6.4 the same.
I think this line was unintentionally lost in https://github.com/symfony/symfony/pull/40964

2023-11-15 19:29 UTC, wandesnet commented
To provide context, the warning message in question relates to the following situation in the Request.php file, specifically on line 1802:

`if (basename($this->server->get('SCRIPT_NAME', '')) === $filename)` 

The basename() function expects to receive a string, correct?

When calling `$this->server->get('SCRIPT_NAME', '')`, if the **SCRIPT_NAME** key does not exist, it returns an empty string, correct?

However, a problem arises if the **SCRIPT_NAME** key exists and the value is null. The **array_key_exists** function returns true, indicating that the key exists, even if its value is null. As a result, the error warning occurs while executing the **basename()** function.

To resolve this issue, I tried to fix the implementation by replacing **array_key_exists** with the null navigation **operator (??)**. With this change, whenever the key contains a null value, the second parameter passed to the get() function will be returned, providing a safer solution and avoiding the aforementioned error warning.

2023-11-16 14:07 UTC, ghost commented
It's weird that SCRIPT_NAME is set and is null. How to you run your PHP server?

2023-11-17 15:10 UTC, nicolas-grekas commented
:-1: with the proposed change, the code is on purpose - parameters can be null and shouldn't fallback in that case

> It's weird that SCRIPT_NAME is set and is null. How to you run your PHP server?

that's the important question for the next step

2023-11-27 10:50 UTC, xabbuh commented
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

2023-11-27 10:50 UTC, closed without merging