fix: allow array on setParameter $value
symfony/symfony pull request #52695
Opened 2023-11-23 01:52 UTC by botjaeger

| Q             | A
| ------------- | ---
| Branch?       | 7.1 for features / 5.4, 6.3, 6.4, or 7.0 for bug fixes 
| Bug fix?      | yes/no
| New feature?  | yes/no 
| Deprecations? | yes/no 
| Issues        | Fix #... 
| License       | MIT

2023-11-23 23:22 UTC, ghost requested changes

2023-11-23 23:22 UTC, ghost commented on src/Symfony/Component/Mime/Header/ParameterizedHeader.php
> +     * params null|string|array $value
the doc block is redundant, you can use native union type hint

2023-11-24 11:56 UTC, nicolas-grekas commented
I'm sorry but this doesn't make sense to me. An array cannot be sent as is on the network. At some point, something needs to serialize it. The mime component doesn't know how to serialize this object. If you need to send many values for some header, you need to generate the serialized string on your side before passing it to setParameter.
IIUC.

2023-11-27 10:51 UTC, xabbuh commented
I am closing as explained before. Thank you for understanding.

2023-11-27 10:51 UTC, closed without merging