Use DenormalizerAwareInterface instead of SerializerAwareInterface
symfony/symfony pull request #52764
Opened 2023-11-27 20:06 UTC by jschaedl

| Q             | A
| ------------- | ---
| Branch?       | 7.1
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Issues        | -
| License       | MIT

The `UnwrappingDenormalizer` does not depend on the `SerializerInterface`. Using the `DenormalizerInterfacce` is enough, because only `denormalize()` is called. Also, the `SerializerInterface` does not define method `denormalize()` and it currently only works, because at runtime the `serializer` service is injected, which implements the `DenormalizerInterface`.

2023-11-28 07:43 UTC, derrabus commented
This is a breaking change that we need a deprecation layer for. By removing `SerializerAwareInterface`/`SerializerAwareTrait` from this class, we're effectively removing a public method from that class.

2023-11-28 07:48 UTC, jschaedl commented
Hi @derrabus,

> This is a breaking change that we need a deprecation layer for. By removing SerializerAwareInterface/SerializerAwareTrait from this class, we're effectively removing a public method from that class.

You are right, I missed this. I am going to add a deprecation layer.

2023-11-28 13:02 UTC, derrabus requested changes

2023-11-28 13:02 UTC, derrabus commented on src/Symfony/Component/Serializer/Normalizer/UnwrappingDenormalizer.php
> +    public function setSerializer(SerializerInterface $serializer): void
`/** @deprecated */`?

2023-11-28 13:02 UTC, derrabus commented on src/Symfony/Component/Serializer/Normalizer/UnwrappingDenormalizer.php
> -final class UnwrappingDenormalizer implements DenormalizerInterface, SerializerAwareInterface
I think we should keep `SerializerAwareInterface` as long as we implement `setSerializer()`.

2023-11-28 13:02 UTC, derrabus commented on src/Symfony/Component/Serializer/composer.json
> +        "symfony/deprecation-contracts": "^3.4@dev"
That's a bit too strict. Also, the `@dev` is unnecessary.

```suggestion
        "symfony/deprecation-contracts": "^2.5|^3"
```

2023-11-28 13:25 UTC, stof commented on src/Symfony/Component/Serializer/Normalizer/UnwrappingDenormalizer.php
> -final class UnwrappingDenormalizer implements DenormalizerInterface, SerializerAwareInterface
If we implement SerializerAwareInterface, the Serializer class will be calling the deprecated method.

2023-11-28 20:58 UTC, jschaedl commented on src/Symfony/Component/Serializer/Normalizer/UnwrappingDenormalizer.php
> -final class UnwrappingDenormalizer implements DenormalizerInterface, SerializerAwareInterface
Yes, that's the reason why I removed `SerializerAwareInterface`. The `Serializer` class will call `setSerializer()` here: https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/Serializer/Serializer.php#L85 

But without it, its a bc-break for code relying on `UnwrappingDenormalizer` implementing `SerializerAwareInterface`. I am not sure how to solve this problem.

2023-11-28 20:58 UTC, jschaedl commented on src/Symfony/Component/Serializer/composer.json
> +        "symfony/deprecation-contracts": "^3.4@dev"
adjusted

2023-11-28 20:58 UTC, jschaedl commented on src/Symfony/Component/Serializer/Normalizer/UnwrappingDenormalizer.php
> +    public function setSerializer(SerializerInterface $serializer): void
deprecated annotation added

2025-08-01 01:13 UTC, dmitryuk commented
@jschaedl may be close PR since it too outdated?

2026-08-07 10:22 UTC, nicolas-grekas commented
Thanks for spotting this, the observation is correct: `UnwrappingDenormalizer` only needs a denormalizer. The blocker was never the idea but the BC layer, since removing `SerializerAwareInterface` drops a public method while keeping it makes `Serializer` call the deprecated `setSerializer()`, as stof noted, and that was never resolved. Closing for now. This kind of change is much easier to land at the start of a major cycle, so it would be worth bringing back then.

2026-08-07 10:22 UTC, closed without merging