[DoctrineBridge] Global query time always at 0.00 ms on profiler
symfony/symfony pull request #52881
Opened 2023-12-04 05:23 UTC by maximethiry

| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #52880
| License       | MIT

(original explanation made from 7.0 branch, now targeting 6.4 cf comments)

The related issue, when i explained the possible solution : https://github.com/symfony/symfony/issues/52880

On `Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCollector`, updated the native return type from `int` to `float` for the method `getTime`.

Context : 
```
    public function getTime(): int
    {
        $time = 0;
        foreach ($this->data['queries'] as $queries) {
            foreach ($queries as $query) {
                $time += $query['executionMS'];
            }
        }

        return $time;
    }
```

Inside this method, the value of `$time` was always a float smaller than 0. The transition to native return type (which was correct regarding to old phpdoc type) made the return cast int to the floating value, hence returning always 0.

I updated the return type to float and updated the test to check for the calculus on floating values.
I had to switch to usleep instead of sleep, since the value might not be an int.

2023-12-04 06:22 UTC, derrabus requested changes

2023-12-04 06:22 UTC, derrabus commented on src/Symfony/Bridge/Doctrine/Tests/DataCollector/DoctrineDataCollectorTest.php
> +        $this->assertEquals(0.54, round($c->getTime(), 2));
```suggestion
        $this->assertEqualsWithDelta(0.54, $c->getTime(), .01);
```

2023-12-04 06:22 UTC, derrabus commented on src/Symfony/Bridge/Doctrine/Tests/DataCollector/DoctrineDataCollectorTest.php
> +        $this->assertEquals(0.54, round($c->getTime(), 2));
This should be a separate test.

2023-12-04 06:23 UTC, derrabus commented on src/Symfony/Bridge/Doctrine/DataCollector/DoctrineDataCollector.php
> +    public function getTime(): float
We should change the annotated type on 6.4 if it's incorrect.

2023-12-04 13:58 UTC, nicolas-grekas commented
Can you please rebase the PR on 6.4 to change the annotation there instead?
We will handle the case for 7.0 while merging that PR on 6.4 into 7.0.

2023-12-05 13:42 UTC, maximethiry commented
Thanks for the feedback, will do the rebase :+1: 
Should I keep the test for floats values, after moving it in a more appropriate function as requested by @derrabus ?

2023-12-05 17:58 UTC, derrabus commented
Yes, please keep the test!

2023-12-22 10:17 UTC, derrabus approved these changes

2023-12-22 10:18 UTC, derrabus commented
Thank you @maximethiry.

2023-12-22 10:18 UTC, merged

2023-12-22 10:26 UTC, derrabus commented
> We will handle the case for 7.0 while merging that PR on 6.4 into 7.0.

Done.