[Serializer] Rewrite `AbstractObjectNormalizer::createChildContext()` to use the provided `cache_key` from original context
symfony/symfony pull request #53523
Opened 2024-01-12 13:43 UTC by amne

| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | N/A
| License       | MIT

If the normalization starts with an initial 'cache_key' it is currently discarded when creating child contexts. This change fixes that. The main reason behind it is that if the client code sends a unique identifier (ApiPlatform injects the IRI) and we have a use case that iterates a big resultset we end up with a big private cache that quickly runs out of allowed memory. The solution should be to send a 'cache_key' which ignores the entire cache key calculation that hashes the context.

2024-01-12 15:28 UTC, mtarld requested changes
As it's a bug, you must target the 5.4 branch instead.

2024-01-12 15:28 UTC, mtarld commented on src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php
> -     * @return mixed
These coding style changes must not be committed as they don't belong to your bugfix.

2024-01-12 15:28 UTC, mtarld commented on src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php
> -        if (!isset($context['cache_key'])) {
I'd keep this if to avoid calling a method each time. Indeed, calling a method could be costly and we are in the hot path here.

2024-01-12 15:28 UTC, mtarld commented on src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php
> -        if (!isset($context['cache_key'])) {
Same here

2024-01-12 15:28 UTC, mtarld commented on src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php
> +        $this->assertSame($data, $normalizedObject);
To make sure that an assertion has been made, I'd use a property and make an assertion directly in the test:
```suggestion
        $normalizer = new class() extends AbstractObjectNormalizerDummy {
            public ?string $childContextCacheKey = null;
            
            protected function extractAttributes(object $object, string $format = null, array $context = []): array
            {
                return array_keys((array) $object);
            }

            protected function getAttributeValue(object $object, string $attribute, string $format = null, array $context = []): mixed
            {
                return $object->{$attribute};
            }

            protected function createChildContext(array $parentContext, string $attribute, ?string $format): array
            {
                $childContext = parent::createChildContext($parentContext, $attribute, $format);
                $this->childContextCacheKey = $childContext['cache_key'];

                return $childContext;
            }
        };
        
        $serializer = new Serializer([$normalizer]);
        $normalizedObject = $serializer->normalize($foobar, null, ['cache_key' => 'hardcoded']);

        $this->assertSame($data, $normalizedObject);
        $this->assertSame('hardcoded-'.$attribute, $normalizer->childContextCacheKey);
```

2024-01-12 15:28 UTC, mtarld commented on src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php
> +        if (isset($context['cache_key'])) {
Should it go after `$context[self::EXCLUDE_FROM_CACHE_KEY]` foreach loop?

2024-01-12 15:52 UTC, amne commented on src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php
> +        if (isset($context['cache_key'])) {
If I revert the removal of the inline ifs then this one goes away so it doesn't matter.

2024-01-12 15:53 UTC, amne commented on src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php
> +        if (isset($context['cache_key'])) {
But to answer, I don't it should go after because the method would not be called if there is an existing $context['cache_key']

2024-01-13 09:04 UTC, mtarld requested changes
Can you rebase your PR on the 5.4 branch please? :slightly_smiling_face:

2024-01-13 09:04 UTC, mtarld commented on src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php
> +        // $this->assertSame($data, $normalizedObject);
Unexpected comment I guess

2024-01-13 09:04 UTC, mtarld commented on src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php
> -    /**
This change should be reverted

2024-01-13 09:34 UTC, mtarld commented
This can be closed in favor of https://github.com/symfony/symfony/pull/53530, thanks!

2024-01-13 15:36 UTC, closed without merging