[Messenger][AmazonSqs] Allow async-aws/sqs version 2
symfony/symfony pull request #53524
Opened 2024-01-12 13:47 UTC by smoench

| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | no
| New feature?  | no 
| Deprecations? | no 
| Issues        |  -
| License       | MIT

With this PR async-aws/sqs version 2 would be allowed to be installed. [With version 2 they are using the AWS JSON-1.0 protocol instead of the XML one](https://github.com/async-aws/sqs/blob/master/CHANGELOG.md#200). They declared this as a BC-Break as they switced the protocol from query to json, but no public method signatures have been changed.

2024-01-14 16:41 UTC, xabbuh requested changes
test failures are related

2024-01-15 09:06 UTC, smoench commented
Tests are fixed. appveyor failues are unrelated to this PR.

2024-01-15 09:13 UTC, derrabus approved these changes

2024-01-15 09:31 UTC, xabbuh approved these changes
For 5.4?

2024-01-15 10:42 UTC, smoench commented
Base branch changed to 5.4

2024-01-15 10:58 UTC, xabbuh approved these changes

2024-01-15 11:03 UTC, stof requested changes
The dev requirement in the root composer.json should also be updated.

And once this is done, you will need to fix the integration-tests workflow which will break because the `asyncaws/testing-sqs` docker image only provides a fake implementation of the old protocol. You should migrate to `localstack` for the integration tests (as was done in async-aws itself)

2024-01-19 09:43 UTC, smoench commented
@stof I updated the missing parts :-)

2024-01-23 13:37 UTC, nicolas-grekas approved these changes

2024-01-23 13:38 UTC, nicolas-grekas commented
Thank you @smoench.

2024-01-23 13:38 UTC, merged