[TwigBridge][DX] Update the undefined callable list
symfony/symfony pull request #53536
Opened 2024-01-13 22:02 UTC by smnandre

| Q             | A
| ------------- | ---
| Branch?       | 7.1
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| License       | MIT

(minor/DX)

Add missing filter/functions (defined in Symfony\Bridge\Twig\Extension) in the UndefinedCallableHandler

Filter:
* serialize ([SerializerExtension](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Bridge/Twig/Extension/SerializerExtension.php))

Function:
* impersonation_path ([SecurityExtension](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Bridge/Twig/Extension/SecurityExtension.php))
* impersonation_url ([SecurityExtension](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Bridge/Twig/Extension/SecurityExtension.php))
* impersonate_exit_path ([SecurityExtension](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Bridge/Twig/Extension/SecurityExtension.php))
* impersonate_exit_url ([SecurityExtension](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Bridge/Twig/Extension/SecurityExtension.php))
* t ([TranslationExtension](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Bridge/Twig/Extension/TranslationExtension.php))

2024-01-18 08:27 UTC, fabpot requested changes

2024-01-18 08:27 UTC, fabpot commented on src/Symfony/Bridge/Twig/UndefinedCallableHandler.php
> +        'impersonate_exit_path' => 'security-http',
```suggestion
        'impersonation_exit_url' => 'security-http',
```

2024-01-18 08:27 UTC, fabpot commented on src/Symfony/Bridge/Twig/UndefinedCallableHandler.php
> +        'impersonate_exit_url' => 'security-http',
```suggestion
        'impersonation_exit_url' => 'security-http',
```

2024-01-18 11:35 UTC, smnandre commented on src/Symfony/Bridge/Twig/UndefinedCallableHandler.php
> +        'impersonate_exit_path' => 'security-http',
Sorry for this

2024-01-18 12:58 UTC, xabbuh approved these changes

2024-01-19 07:43 UTC, fabpot approved these changes

2024-01-19 07:44 UTC, fabpot commented
Thank you @smnandre.

2024-01-19 07:44 UTC, merged