Use `now` function to allow mock of time
symfony/symfony pull request #53531
Opened 2024-01-12 22:31 UTC by andersonamuller

| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes?
| New feature?  | yes?
| Deprecations? | no
| Issues        | N/A
| License       | MIT

When doing functional testing there is not really a easy way to mock the time for the `InMemoryTransport`. It's created by the `InMemoryTransportFactory` and you can't set which clock to use.

2024-01-30 10:00 UTC, ro0NL approved these changes

2024-01-30 10:02 UTC, ro0NL commented
however i think we should inject global clock into InMemoryTransportFactory isnt it?

2024-01-30 11:06 UTC, andersonamuller commented
> however i think we should inject global clock into InMemoryTransportFactory isnt it?

Yes, that is the best solution indeed

2024-01-30 11:26 UTC, derrabus requested changes
I don't believe that this is the right way. If the transport already receives a clock, we should rather leverage the injected clock for mocking than introduce a _second_ way of accessing mocked date values.

2024-04-11 15:27 UTC, nicolas-grekas commented
>It's created by the InMemoryTransportFactory and you can't set which clock to use.

I'd rather fix this aspect indeed: making the InMemoryTransportFactory accept and forward a clock.

PR welcome.

2024-04-11 15:27 UTC, closed without merging