[Validator] Add callback option to the ExpressionSyntax constraint
symfony/symfony pull request #53569
Opened 2024-01-17 23:13 UTC by symfonyaml

| Q             | A
| ------------- | ---
| Branch?       | 7.1
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| License       | MIT

### ExpressionSyntax
I introduced the ability to use a callback to specify allowed variables *(basically it will set the `$allowedVariables` value from this callback)*. Exactly like [the Choice callback constraint](https://symfony.com/doc/current/reference/constraints/Choice.html#callback).

This feature will be useful if an expression use dynamic variables (like in my personal project 😋).

### Example
```php
class MyEntity
{
    public static function getVars(): array
    {
        // some cool logic with allowed expression variables ... 
        return ['symfony', $this->getUsername()];
    }

    #[Assert\ExpressionSyntax(allowedVariablesCallback: 'getVars')]
    protected string $expression;
}
```

2024-01-18 09:13 UTC, xabbuh requested changes

2024-01-18 09:13 UTC, xabbuh commented on src/Symfony/Component/Validator/Constraints/ExpressionSyntax.php
> +        callable|string $allowedVariablesCallback = null,
adding a new parameter in between existing parameters is a BC break

2024-01-18 09:13 UTC, xabbuh commented on src/Symfony/Component/Validator/Constraints/ExpressionSyntaxValidator.php
> +        if (\is_array($constraint->allowedVariables) && $constraint->allowedVariablesCallback) {
What about allow `allowedVariables` to also be a callable instead?

2024-01-18 09:38 UTC, symfonyaml commented on src/Symfony/Component/Validator/Constraints/ExpressionSyntax.php
> +        callable|string $allowedVariablesCallback = null,
Oh that's right, thanks for the reminder !

2024-01-18 09:45 UTC, symfonyaml commented on src/Symfony/Component/Validator/Constraints/ExpressionSyntaxValidator.php
> +        if (\is_array($constraint->allowedVariables) && $constraint->allowedVariablesCallback) {
I like that, but we'll have a problem between these two allowed variables setups :
```php
// I mention 2 variables called 'className' and 'method'
#[ExpressionSyntax(allowedVariables: ['className', 'method'])]
// I mention the callback className::method()
#[ExpressionSyntax(allowedVariables: ['className', 'method'])] 
```
In this PR I took example on the [ChoiceValidator callback option](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/Validator/Constraints/ChoiceValidator.php#L48).

2024-11-09 11:36 UTC, symfonyaml commented
Closed. We can use the `ExpressionSyntax::$service` option instead.

2024-11-09 11:36 UTC, closed without merging