[Mime] Fix undefined array key 0 when empty sender
symfony/symfony pull request #53565
Opened 2024-01-17 16:44 UTC by 0x346e3730

| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | N/A
| License       | MIT

Today I managed to produce the following error :
![image](https://github.com/symfony/symfony/assets/28731165/11b3b76d-d220-4f08-9b12-838ca936f540)

From the following code :
```php
$email = (new TemplatedEmail())
            ->from()
            ->to($member->getEmail())
            ->subject('Adhésion Sauvade')
            ->htmlTemplate('emails/new-membership/index.html.twig')
            ->context([
                'member' => $member,
            ])
            ->addPart(new DataPart(
                $this->pdfService->generatePdfFromTemplate(
                    'emails/new-membership/attachments/recu.html.twig',
                    ['member' => $member]
                ),
            ))
            ->addPart(new DataPart(
                $this->pdfService->generatePdfFromTemplate(
                    'emails/new-membership/attachments/membership-card.html.twig',
                    ['member' => $member]
                ),
            ))
        ;

        $this->mailer->send($email);
```

This happens because the `from` method from the `Symfony\Component\Mime\Email` class adds the header even if the array of addresses is empty. I identified two ways of fixing this :
- Adding a check in the `Symfony\Component\Mime\Message` class before accessing the key 0 and throw a better exception in case the adresses are empty
- Modifying the `from` method so that it doesn't add the header if the adresses are empty; or throw an exception when trying to do so.

I'm unsure what method is the cleaner, I thought that fiwing the Message access of an undefined key was the most large fix (as I guess it could happen from somewhere else than the Mailer compomnent). Also not sure how to test that and wanted to make sure this fix was good before testing it.

2024-01-17 16:53 UTC, xabbuh commented
Can you please add a test to make sure that we don’t break this again.

2024-01-17 17:07 UTC, 0x346e3730 commented
Done. It seems to me that the failing tests are related to cryptography errors and not my code

2024-01-18 07:36 UTC, xabbuh commented on src/Symfony/Component/Mime/Tests/MessageTest.php
> +        $this->expectException(\LogicException::class);
please move this line right before the call of `generateMessageId()`, also we should change the class name to actually check for the `LogicException` that is thrown in the `Message` class (i.e. the one from the Mime component)

2024-01-18 07:38 UTC, xabbuh commented on src/Symfony/Component/Mime/Message.php
> +            if (empty($froms = $this->headers->get('From')->getAddresses())) {
```suggestion
            if ([] === $froms = $this->headers->get('From')->getAddresses()) {
```

2024-01-18 07:39 UTC, xabbuh commented on src/Symfony/Component/Mime/Message.php
> +                throw new LogicException('Your email has a From header that contains no addresses. Did you forgot to add emails in the "from" method ?');
```suggestion
                throw new LogicException('A "From" header must have at least one email address.');
```

2024-01-18 07:59 UTC, fabpot commented
What about forbidding calling `Email::from()` without any address instead?

2024-01-18 08:02 UTC, 0x346e3730 commented
> What about forbidding calling `Email::from()` without any address instead?

This is one of the ways I identified to fix this issue, I have no opinion on which is best for DX.

I went with fixing it in the Message class because it could (I guess ?) be used by other components than Mailer so I would suggest to still fix this here even if we block this behavior in the `from` method

2024-01-18 08:08 UTC, fabpot requested changes

2024-01-18 08:08 UTC, fabpot commented on src/Symfony/Component/Mime/Message.php
> +            if (empty($froms = $this->headers->get('From')->getAddresses())) {
```suggestion
            if (!$froms = $this->headers->get('From')->getAddresses()) {
```

2024-01-18 08:09 UTC, fabpot commented
I would do the fix in `Email::from()` anyway as there is no good use case for not passing anything to this method.

2024-01-19 05:16 UTC, 0x346e3730 commented on src/Symfony/Component/Mime/Message.php
> +            if (empty($froms = $this->headers->get('From')->getAddresses())) {
Used the proposition of Fabien instead, letting you resolve the conversation if it's okay with you

2024-01-19 05:28 UTC, 0x346e3730 commented
I adjusted the code with your reviews and added an exception if calling Email::from() with no addres, however the `from` method just calls `setListAddressHeaderBody` that is also called by `replyTo`, `to`, `cc`, `bcc` and `addListAddressHeaderBody`. Should we implement the throw in Email::setListAddressHeaderBody() instead so that it covers all method that add email addresses to certain headers ?

Plus the "add" version of those methods (`addFrom`, `addReplyTo` ect...) call `addListAddressHeaderBody` that does `$header->addAddresses(Address::createArray($addresses));`. Should we do the same throw in `MailboxListHeader::addAddresses` as well ?

2024-01-19 06:47 UTC, xabbuh commented on src/Symfony/Component/Mime/Email.php
> +            throw new LogicException(sprintf('"from()" must be called with at least one address.'));
```suggestion
            throw new LogicException('"from()" must be called with at least one address.');
```

2024-01-19 06:58 UTC, xabbuh approved these changes

2024-01-21 09:53 UTC, fabpot approved these changes

2024-01-21 09:54 UTC, fabpot commented
Thank you @0x346e3730.

2024-01-21 09:54 UTC, merged