[Console] Only execute additional checks for color support if the output
symfony/symfony pull request #53576
Opened 2024-01-18 10:13 UTC by theofidry

is a TTY

| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #53460
| License       | MIT

2024-01-18 10:18 UTC, theofidry commented on src/Symfony/Component/Console/Output/StreamOutput.php
> +    protected function isTty(): bool
I extracted into a dedicated method for clarity, but this may be a problem especially for 5.4?

2024-01-19 07:40 UTC, fabpot requested changes

2024-01-19 07:40 UTC, fabpot commented on src/Symfony/Component/Console/Output/StreamOutput.php
> +    protected function isTty(): bool
```suggestion
    private function isTty(): bool
```

2024-01-19 10:34 UTC, theofidry commented on src/Symfony/Component/Console/Output/StreamOutput.php
> +    protected function isTty(): bool
Done

2024-01-19 10:44 UTC, xabbuh approved these changes

2024-01-19 11:10 UTC, fabpot approved these changes

2024-01-19 11:11 UTC, fabpot commented
Thank you @theofidry.

2024-01-19 11:11 UTC, merged