[Serializer] Fix normalization promotion constructor unknown type when know type
symfony/symfony pull request #53945
Opened 2024-02-14 16:00 UTC by Myks92

| Q             | A
| ------------- | ---
| Branch?       | 7.0
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | -
| License       | MIT

When we use the normalizer with Promotion Constructor, a Non Normalizable Value Exception occurs with unknown type even when the type is known. This Pull request fix this error.

2024-02-14 16:12 UTC, nicolas-grekas approved these changes
LGTM, for branch 5.4

2024-02-14 16:47 UTC, mtarld requested changes

2024-02-14 16:47 UTC, mtarld commented on src/Symfony/Component/Serializer/Normalizer/AbstractNormalizer.php
> +                    if (null !== $reflectionType && method_exists($reflectionType, 'getName')) {
```suggestion
                    if ($reflectionType instanceof \ReflectionNamedType) {
```

2024-02-15 08:56 UTC, mtarld approved these changes
LGTM, but you should target the 5.4 branch as that bug is already existing in that version

2024-02-15 09:58 UTC, lyrixx approved these changes
Awesome 👍🏼

2024-02-15 20:34 UTC, closed without merging