[AssetMapper] Deprecate unused splitPackageNameAndFilePath
symfony/symfony pull request #54125
Opened 2024-03-01 07:48 UTC by smnandre

| Q             | A
| ------------- | ---
| Branch?       | 7.1
| Bug fix?      | no
| New feature?  | no
| Deprecations? | yes
| Issues        | Fix #54123
| License       | MIT

This method is not used in the codebase, and duplicates` ImportMapEntry::splitPackageNameAndFilePath()`

2024-03-01 08:19 UTC, maxbeckers approved these changes

2024-03-01 11:40 UTC, xabbuh requested changes

2024-03-01 11:40 UTC, xabbuh commented on src/Symfony/Component/AssetMapper/ImportMap/ImportMapConfigReader.php
>      public static function splitPackageNameAndFilePath(string $packageName): array
We should also add a `@deprecated` annotation on the method.

2024-03-01 11:49 UTC, stof requested changes

2024-03-01 11:49 UTC, stof commented on src/Symfony/Component/AssetMapper/ImportMap/ImportMapConfigReader.php
> +        trigger_deprecation('symfony/asset-mapper', '7.1', 'The method "%s()" is deprecated and will be removed in 8.0.', __METHOD__);
This should mention the replacement

2024-03-02 08:37 UTC, xabbuh commented on src/Symfony/Component/AssetMapper/CHANGELOG.md
> + * Deprecate `ImportMapConfigReader::splitPackageNameAndFilePath()`, use `ImportMapEntry::splitPackageNameAndFilePath()` instead
this should also be added to `UPGRADE-7.1.md`

2024-03-02 12:33 UTC, xabbuh approved these changes

2024-03-02 13:03 UTC, fabpot approved these changes

2024-03-02 13:03 UTC, fabpot commented
Thank you @smnandre.

2024-03-02 13:03 UTC, merged