[HttpKernel] allow boolean argument support for MapQueryString
symfony/symfony pull request #54153
Opened 2024-03-04 16:10 UTC by Jean-Beru

| Q             | A
| ------------- | ---
| Branch?       | 7.1
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Issues        | Fix #53616
| License       | MIT

Add a `$filters` argument to the `MapQueryString` attribute to allow filtering parameters using `filter_var` function. It will be useful to cast "false", "0", "no" or "off" to `false` before denormalizing the request data.

Usage:
```php
final readonly class SearchDto
{
    public function __construct(public bool $restricted = true)
    {
    }
}

final class MyController
{
    #[Route(name: 'homepage', path: '/')]
    public function __invoke(#[MapQueryString(filters: ['restricted' => \FILTER_VALIDATE_BOOL])] SearchDto $search): Response
    {
        return new JsonResponse($search);
    }
}
```

See #53616 for a use case.

2024-03-05 08:09 UTC, nicolas-grekas commented
I'm not sure how useful this could be: the query string can be a tuple of many different type of values, while this works only of all properties of the DTO are of the same type, isn't it?

2024-03-05 10:41 UTC, Jean-Beru commented
> I'm not sure how useful this could be: the query string can be a tuple of many different type of values, while this works only of all properties of the DTO are of the same type, isn't it?

The associative array allows to define which parameter is concerned. `#[MapQueryString(filters: ['restricted' => \FILTER_VALIDATE_BOOL])]` will only apply this filter on the `restricted` parameter.

TBH, I think that this mapping will mainly be used to cast string to boolean since other types (ex: string to int) are already handled by the Serializer.

2024-03-05 10:48 UTC, nicolas-grekas commented
Ah OK, so "restricted" is the name of the property. This wasn't obvious to me.

It's a bit of a shame that a type that is already clearly described on the DTO need to be specified again somewhere else.

This maps to the serializer component, which could have a mode to do the cast on its own, don't you think?

2024-03-05 15:21 UTC, Jean-Beru commented
> It's a bit of a shame that a type that is already clearly described on the DTO need to be specified again somewhere else.

I totally agree.

> This maps to the serializer component, which could have a mode to do the cast on its own, don't you think?

We could pass add `[FILTER_BOOL => value]` in the context to apply this filter. Should this filter be applied by default when using `#[MapQueryString]` ? Current request parameters like `active=false` will be cast to `false` in place of `true` now.

2024-03-05 15:25 UTC, nicolas-grekas commented
Yes, that'd be better IMHO. Dunno if bool is the only concerned type of if other ones could benefit from using filter_var to do the casting. Would need to be investigated.
Then yes, I would enable that flag for MapQueryString, but also for MarRequestPayload *when the payload is a form submition*.

2024-03-06 12:53 UTC, Jean-Beru commented
I updated this PR and its description this way with a new `AbstractNormalizer::FILTER_BOOL` context option.

2024-03-13 15:42 UTC, nicolas-grekas approved these changes
I like that :)

2024-03-13 15:42 UTC, nicolas-grekas commented on src/Symfony/Component/Serializer/Normalizer/AbstractNormalizer.php
> +        if (null === ($filteredData = filter_var($value, \FILTER_VALIDATE_BOOL, \FILTER_NULL_ON_FAILURE))) {
```suggestion
        return filter_var($value, \FILTER_VALIDATE_BOOL, \FILTER_NULL_ON_FAILURE) ?? $value;
```

2024-03-17 07:45 UTC, fabpot approved these changes

2024-03-17 14:45 UTC, fabpot requested changes

2024-03-17 14:45 UTC, fabpot commented on src/Symfony/Component/Serializer/Normalizer/AbstractNormalizer.php
> +        }
Looks wrong :)

2024-03-17 14:48 UTC, fabpot commented
Thank you @Jean-Beru.

2024-03-17 14:48 UTC, merged

2024-04-18 07:18 UTC, antoniovj1 commented
Will this fix apply to Symfony 7.0?

2024-04-18 07:29 UTC, nicolas-grekas commented
It's not a fix but a new feature, so 7.1

2024-04-18 11:27 UTC, antoniovj1 commented
Makes sense, thanks!