[DoctrineBridge] prevent deprecated message for ORM > 3.1 for Symfony 5.4
symfony/symfony pull request #54271
Opened 2024-03-13 13:24 UTC by eltharin

| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | 
| License       | MIT

 [DoctrineBridge] prevent deprecated message #54255  for symfony 5.4

2024-03-13 14:36 UTC, derrabus commented on src/Symfony/Bridge/Doctrine/Form/DoctrineOrmTypeGuesser.php
> +            $length = \is_array($mapping) ? $mapping['length'] : $mapping->length;
The previous logic allowed the `length` key not to be set. Your code would trigger a warning in that case.

2024-03-13 14:41 UTC, derrabus commented on src/Symfony/Bridge/Doctrine/Form/DoctrineOrmTypeGuesser.php
> +            $length = \is_array($mapping) ? $mapping['length'] : $mapping->length;
What if we tested for the actual class instead?

```php
$length = $mapping instanceof FieldMapping ? $mapping->length : ($mapping['length'] ?? null);
```

2024-03-13 15:12 UTC, nicolas-grekas commented on src/Symfony/Bridge/Doctrine/Form/DoctrineOrmTypeGuesser.php
> +            if (isset($length)) {
```suggestion
            if (null !== $length) {
```

2024-03-13 19:18 UTC, derrabus requested changes

2024-03-13 19:18 UTC, derrabus commented on src/Symfony/Bridge/Doctrine/Form/DoctrineOrmTypeGuesser.php
> +            if (null == $length) {
```suggestion
            if (null !== $length) {
```

2024-03-17 14:55 UTC, fabpot approved these changes

2024-03-17 14:56 UTC, fabpot commented
Thank you @eltharin.

2024-03-17 14:56 UTC, merged