Fix LockStoreSchemaListener not working properly with iterable objects
symfony/symfony pull request #54407
Opened 2024-03-26 13:54 UTC by barton-webwings

| Q             | A
| ------------- | ---
| Branch?       | 7.1 for features / 5.4, 6.4, or 7.0 for bug fixes 
| Bug fix?      | yes/no
| New feature?  | yes/no 
| Deprecations? | yes/no 
| Issues        | Fix #... 
| License       | MIT

2024-03-26 14:46 UTC, MatTheCat commented
I think you can simply revert #50761:

- `ArrayIterator` won’t work as expected when passed an iterator (this is why `testPostGenerateSchemaWithInvalidLockStore` passes: the iterator won’t yield anything).
- Exceptions thrown inside a generator will appear when calling `valid` or `next`, not `current`.
- Even if caught, an exception thrown inside a generator would still close it; this could result in other stores being silently ignored.

2024-04-11 15:10 UTC, nicolas-grekas commented
/cc @alexandre-daubois FYI

2024-04-11 15:22 UTC, alexandre-daubois commented
Indeed my solution doesn't work as expected. I don't think that reverting the PR is the best solution, because it would fix a bug but reintroduce one in the codebase.

I'm on my phone right now but I can have a look at it tomorrow to find/have a look for a proper solution 🙂

2024-04-12 08:56 UTC, barton-webwings commented
I think there could be a better solution to the original issue https://github.com/symfony/symfony/pull/50761.

Personally, I would take a similar path to Monolog's `NullHandler` or Mailer's `NullTransport` and introduce a `NullStore` and a corresponding case to the `StoreFactory`. The DSN could look something like `LOCK_STORE=null://`. 

This way we would avoid the `InvalidArgumentException`, which I agree is a legitimate exception, but preserve the option to effectively disable the Lock component.

2024-04-12 09:07 UTC, alexandre-daubois commented
Seems to be a great solution indeed, I like it!

2024-04-12 10:31 UTC, barton-webwings commented
I pushed a draft of my proposed solution into this PR, hopefully I didn't miss anything.

Since the `StoreFactory` already has cases which are not strictly a dsn, I went with a simple `null`, which would teoretically work with existing cases of `LOCK_STORE=null`.

2024-04-12 11:25 UTC, alexandre-daubois approved these changes
Seems like a clean solution like this 😊

2024-04-12 12:02 UTC, nicolas-grekas commented
So, that's a new feature now, isn't it?

2024-04-25 14:47 UTC, Toflar commented
Not really a new feature. The current implementation is broken. It will not add the required schema as described in https://github.com/symfony/symfony/issues/54406. Just faced the same issue and this PR fixes it :)

2024-05-04 15:34 UTC, MatTheCat commented
The `NullStore` is a new feature.

Reverting #50761 is a fix.

This PR should be split into two.

2024-08-05 12:23 UTC, xabbuh requested changes

2024-08-05 12:23 UTC, xabbuh commented on src/Symfony/Component/Lock/Store/NullStore.php
> +class NullStore implements BlockingSharedLockStoreInterface
Introducing this class (as well as the changes to the `StoreFactory`) must be moved into a separate PR targeting the `7.2` branch. That's a new feature.

2024-08-05 12:23 UTC, xabbuh commented on src/Symfony/Bridge/Doctrine/Tests/SchemaListener/LockStoreSchemaListenerTest.php
> -    public function testPostGenerateSchemaWithInvalidLockStore()
this test should be kept as fixing the issue #50761 tried to fix is legitimate

2024-08-05 12:23 UTC, xabbuh commented on src/Symfony/Bridge/Doctrine/SchemaListener/LockStoreSchemaListener.php
> -            } catch (InvalidArgumentException) {
we still need catch the exception to not reintroduce the bug that #50761 tried to fix

2024-08-05 13:05 UTC, MatTheCat commented
@xabbuh there was in fact no bug prior to #50761: it is normal an exception is thrown when giving the `StoreFactory` an invalid DSN, and it is outlined by the fact said exception extends `LogicException`, which is not supposed to be caught.

2024-08-07 12:25 UTC, uwej711 commented
OK, so where do we go from here? Keep the current bug in 6.4, revert the commit that causes the bug and having the issue it tried to fix again or something else?

2024-08-08 07:09 UTC, xabbuh commented
I would be okay with both solutions. Either reverting #50671 or switching to `foreach`). But the new `null` schema cannot be merged into 6.4 and must be moved into a PR targeting 7.2.

2024-08-08 08:30 UTC, barton-webwings commented
I am closing this PR, as it is superseded by https://github.com/symfony/symfony/pull/57944.
I am actually only interested in the bugfix part of this issue, so we can remove the workaround after update.
If someone wants to make a PR for the new feature introduced, feel free.

2024-08-08 08:30 UTC, closed without merging