[Emoji] Update slack data
symfony/symfony pull request #54450
Opened 2024-04-01 13:10 UTC by alamirault

| Q             | A
| ------------- | ---
| Branch?       | 7.1
| Bug fix?      | no
| New feature?  | yes 
| Deprecations? | no 
| Issues        | Fix #... 
| License       | MIT

Update slack data to latest with make build

Split https://github.com/symfony/symfony/pull/54441 in 2 PR as suggested in https://github.com/symfony/symfony/pull/54441#discussion_r1546252696

2024-04-01 14:09 UTC, derrabus requested changes

2024-04-01 14:09 UTC, derrabus commented on src/Symfony/Component/Emoji/CHANGELOG.md
> + * Update `slack` data
This entry is a bit pointless given that we haven't shipped a stable version of the component yet that would've included the old data set.

2024-04-01 14:28 UTC, alamirault commented on src/Symfony/Component/Emoji/CHANGELOG.md
> + * Update `slack` data
Thank you for explanation, updated

2024-04-02 07:04 UTC, javiereguiluz approved these changes

2024-04-02 07:14 UTC, lyrixx approved these changes
Thanks

2024-04-02 07:35 UTC, nicolas-grekas reviewed
For 6.4 ?

2024-04-02 08:38 UTC, stof commented
@nicolas-grekas as the data has been extracted in a standalone component in 7.1, I think it is easier to keep this update in 7.1.

2024-04-02 08:42 UTC, nicolas-grekas commented
Thank you @alamirault.

2024-04-02 08:42 UTC, merged