[String] Fix #54611 pluralization of -on ending words + singularization of -a ending foreign words
symfony/symfony pull request #54634
Opened 2024-04-17 11:22 UTC by DesLynx

| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Issues        | Fix #54611
| License       | MIT

* fix the pluralization of -on ending words as -ons (with exception for "criterion" and "phenomenon")

* fix singularization of -a ending foreign words (see https://english-zone.com/spelling/plurals.html)
![image](https://github.com/symfony/symfony/assets/72632819/ee32d12d-63b6-49ef-a815-4d9f1dc2d405)

note: I left "data" uninflected because it seems to me that changing it to the datum/data inflection could cause side effects as "data" is a widely used word (especially in the coding world).

* update the test suites (String component + deprecated Inflector component) according to the changes

2024-04-17 17:47 UTC, DesLynx commented
The common typo issue reported by fabbot.io is not a typo here.

2024-04-17 17:58 UTC, DesLynx commented
The `Unit Tests / Unit Tests (8.2, low-deps) (pull_request)` uses the String component v5.3 making the Inflector component test failed. Should I have targetted the 5.3 branch instead of the 5.4?

2024-04-23 09:44 UTC, nicolas-grekas approved these changes

2024-04-23 09:44 UTC, nicolas-grekas commented
(you need to bump the version of the string component in the composer.json file to fix the deps=low tests)

2024-04-23 11:04 UTC, DesLynx commented
@nicolas-grekas you lost me on this because I don't know to which version should I bump the string component in the composer file of the inflector component as the PR fixes the string component. I obviously can't use 5.4.x-dev ...

2024-04-23 11:20 UTC, nicolas-grekas commented
The next version is 5.4.39

2024-04-24 06:45 UTC, xabbuh requested changes

2024-04-24 06:45 UTC, xabbuh commented on src/Symfony/Component/Inflector/composer.json
> +        "symfony/string": "^5.4.39|^6.0"
```suggestion
        "symfony/string": "^5.4.39|^6.4.7"
```

2024-06-09 07:09 UTC, fabpot approved these changes

2024-06-09 07:13 UTC, fabpot commented
Thank you @DesLynx.

2024-06-09 07:13 UTC, merged