[Finder] Exclude relative to content root if suffixed `/`
symfony/symfony pull request #54752
Opened 2024-04-27 13:46 UTC by joshtrichards

Fixes #28158
Fixes #47431

Related: #26396
Related: #9158
Related: #28410

| Q             | A
| ------------- | ---
| Branch?       | 5.4 
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Issues        | Fix #28158 #47431 
| License       | MIT

This implements a fix for this situation in a non-BC breaking way by doing content root-only relative matches when the `exclude()` path is prefixed by `/`. If an `exclude()` path does not start with `/`, the behavior stays the same as today and will exclude any matching sub-dir anywhere in the tree. 

Approach first suggested [here](https://github.com/symfony/symfony/issues/28158#issuecomment-736329616) by @ogizanagi and most recently reiterated by @wouterj [here](https://github.com/symfony/symfony/issues/28158#issuecomment-2016855663).

2024-04-27 14:15 UTC, joshtrichards commented
Both test failures appear unrelated.

2024-04-27 16:55 UTC, OskarStark commented on src/Symfony/Component/Finder/Iterator/ExcludeDirectoryFilterIterator.php
> +            return false;
```suggestion
        
        if ($this->excludedPattern && preg_match($this->excludedPattern, $path)) {
            return false;
        }

        if ($this->excludedPatternAbsolute && preg_match($this->excludedPatternAbsolute, $path)) {
            return false;
```

2024-04-27 17:07 UTC, phil-davis commented
I had some unit test changes ready to test this solution, so I have made PR #54754 with the test changes/additions and the code cherry-picked from here. I made it to the 7.1 branch, because, as I read the rules, this is a "new feature" and so new features go to the current minor version branch.

Is this a "new feature" or an "enhancement that helps adjust behavior"?
Will we be able to get it added to the v6 series (and maybe to the v5 series, like this PR attempts)?

2024-04-27 17:56 UTC, smnandre commented
Does the notInPath method work for this ? 

This will be a _big_ BC break, as  `->exclude('/var/')` will have a major behaviour change, no ?

2024-04-27 21:28 UTC, joshtrichards commented
Thanks for your comments. Some initial responses below.

> Does the notInPath method work for this ?

Only in the same sense that `notPath` can always be used as an alternative to `exclude` if performance isn't of concern. So no. :-)

> This will be a big BC break, as ->exclude('/var/') will have a major behaviour change, no ?

Paths provided to `exclude` are only evaluated relative to the `in()` specified folder(s). Absolute (system) paths were never supported by `exclude`. 

So if someone puts a slash in front they (presumably) mean the root of their content (`in()`) directory. That's fine.

If that's not what they intended, well that's never been supported (or worked - and still won't).

i.e.`in($contentRoot)->exclude("/var")` will match `$contentRoot/var` just fine. 

So if someone is specifying `/var/` they're already likely not getting what they're expecting. Either they meant:

- the system `/var/` which never worked and still won't work 

Or:

- a folder called `var` located in their `$contentRoot` (i.e. within the root of `in($contentRoot)`) and only there

That second situation is what this would fix/enable.

---

You can play with the regex a bit (keeping in mind the new one is only used against `exclude` values that start with `/` - which is how this is isn't breaking BC):

Old and only: `#(?:^|/)(?:data|/blah|/var/)(?:/|$)#`

New and supplemental: `#^(data|/blah|/var/)$#`

Aside: The actual bug is in the original regex and/or in which scenarios even end up using it I suppose[1], but fixing this would not be BC. This PR does so in a reasonable way (I think!) without breaking existing code. It makes `exclude` useful outside of anything but the simplest folder structures (which is important since its main benefit over `notPath` is performance and that is likely to be of particular interest to those with big/complicated trees, but we can't use it as-is right now without risking losing deeper down paths that match undesirably).

[1] https://github.com/symfony/symfony/blob/c834064b3765d5c43e25fae2fca4498c53e2aee1/src/Symfony/Component/Finder/Iterator/ExcludeDirectoryFilterIterator.php#L56-L84

2024-04-27 23:31 UTC, smnandre commented
Thank you for the detailed answer. I guess adding some functional tests (testing the behaviour with the recursiveiterator) is not a bad idea :)

2024-04-28 01:39 UTC, phil-davis commented
> Thank you for the detailed answer. I guess adding some functional tests (testing the behaviour with the recursiveiterator) is not a bad idea :)

See the PR #54754 that has this code to the 7.1 branch, where I have expanded the test coverage. I'm happy to hear ideas for other combinations of things that should have test cases.

(Note: "someone" will need to decide if this is a fix or a new feature. That will determine if this will be allowed as a "patch" fix in v5 and v6 or whether it is only released to v7)

2024-05-02 15:52 UTC, Seldaek commented
IMO this would be very nice to have as a bug fix, because the advertised behavior was broken.

As an aside, we are trying to add support for this in Composer's autoloader which uses Finder to iterate files for classmaps, as this would allow skipping whole directories instead of iterating all files anyway like we do now, gaining perf, but I have no way of converting an `exclude-from-classmap: ['Tests/']` into a finder exclusion right now, as excluding `'Tests'` would exclude `src/Tests` as well, potentially wreaking havoc. Ref https://github.com/composer/class-map-generator/pull/7

2024-05-02 15:55 UTC, phil-davis commented
> IMO this would be very nice to have as a bug fix, because the advertised behavior was broken.

Agree. I am happy to help sort out "back-porting" the test changes to here for 5.4, and making a "mid-port" PR for major version 6. "Someone" just decide if this will be accepted as a bug fix.

2024-05-08 21:24 UTC, joshtrichards commented
Added tests:

- The new iterator unit tests all pass { `/foo`, `/toto/foo` }
- The finder integration test for `/foo` passes, but there's an issue with sub-folders `/toto/foo` (they're not being excluded when the iterator is called thru Finder)

Technically sub-folders don't have to work I suppose for now, but I'd like to see if I can get them to work too since it'll feel like a more correct implementation. I'll try to take a look at those in the coming days. If anyone sees the culprit, don't hesitate to speak up (I have a few guesses but don't have more time to look at it tonight).

2024-08-09 15:11 UTC, javiereguiluz commented
This looks like an important thing to fix (and we have another fix proposal in #54754). Let's ping @symfony/mergers to see if we can work on finishing this one. Thanks.

2024-08-09 15:17 UTC, phil-davis commented
> This looks like an important thing to fix (and we have another fix proposal in #54754). Let's ping @symfony/mergers to see if we can work on finishing this one. Thanks.

My contribution there is just to expand the test coverage to try and cover more cases. And I made the PR to a later branch, in case "those that have the power" decide that it has to go in the later branch.

How to we get the attention of the Symfony maintainers?

2025-05-14 08:28 UTC, raveren commented
Carson the bot is threatening to close the OP issue and there seems to be failing checks in this PR? 

I think this is still relevant, @joshtrichards do you feel that fixing the failing tests and code style issues is possible?

2026-02-24 17:59 UTC, nicolas-grekas approved these changes
I rebased this on 8.1 and reclassified it as a new feature, which it is ;)

2026-02-24 22:55 UTC, phil-davis commented
https://github.com/symfony/symfony/actions/runs/22363657857/job/64723726106?pr=54752
codespell complains about the function name "testIn()" which is not even touched by this PR.
I suppose that is an existing known CI "fail".

2026-03-18 09:45 UTC, alexandre-daubois approved these changes

2026-04-08 13:37 UTC, ruudk commented
@joshtrichards Could you rebase this one more time and fix the CS issue? Would be great to have this included in 8.1

2026-07-01 07:00 UTC, fabpot requested changes

2026-07-01 07:00 UTC, fabpot commented on src/Symfony/Component/Finder/Iterator/ExcludeDirectoryFilterIterator.php
> +            if (false !== $slashPos && \strlen($directory) - 1 !== $slashPos) {
This is always true as `$directory` is trimmed a few lines above. This means that we are matching any string with a / like `foo/bar`.

2026-09-02 09:41 UTC, nicolas-grekas commented
Thank you for the patience on this one, and for the clean approach: giving a meaning to the leading `/` is BC-safe, since such values could never match a relative path before, so they excluded nothing.

I checked the BC question raised above by probing the previous behavior, and rebased + reworked the PR based on what came out:

- As submitted, the new anchored matching applied to *every* value containing a slash, not only to `/`-prefixed ones: after `rtrim()`, the first slash can never be the last character, so the `\strlen($directory) - 1 !== $slashPos` guard was always true. That silently changed `exclude('foo/bar')` from "match at any depth" to "match at the root only". The condition is now `str_starts_with($directory, '/')`, and `testExcludeNestedPath` locks the floating behavior (it fails on the previous revision of this PR).
- The anchored pattern now ends with `(?:/|$)` instead of `$`, so that on non-recursive iterators the content below an excluded directory is filtered out too, consistently with the floating pattern.
- Renamed `excludedPatternAbsolute` to `excludedRootPattern`: absolute filesystem paths are not supported either way, which was precisely the confusion discussed above.
- Moved the changelog entry to 8.2 and rebased on current 8.2.

While probing this I also found two pre-existing bugs in the prune filters (`filter($closure, prune: true)`): they are not applied below the root directory, and they are skipped entirely when combined with a slash-containing `exclude()`. Fix in #65801, targeted at 6.4. This PR's restructured `accept()` matches the shape of that fix, which keeps the merge-up simple.

2026-09-02 11:11 UTC, nicolas-grekas commented
Thank you @joshtrichards.

2026-09-02 11:11 UTC, merged