[TypeInfo] mark classes as experimental
symfony/symfony pull request #54788
Opened 2024-04-30 12:44 UTC by soyuka

| Q             | A
| ------------- | ---
| Branch?       | 7.1
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| License       | MIT

This is following a discussion on slack with authors of the component, I feel that the TypeInfo component should have an experimental phase as we need to prove the component's functionality on software that is built on top of type information extraction. Here's a non-exhaustive list of software using the PropertyInfo Type class (thanks to @mtarld): 

- api-platform/core
- nelmio/api-doc-bundle
- typo3/cms-extbase
- typo3/cms
- sonata-project/page-bundle
- jolicode/automapper
- symfony/ux-live-component

These softwares should try their best in testing the new TypeInfo component and report back misfunctionalities and/or DX improvements before we can consider this non-experimental.

2024-04-30 13:04 UTC, mtarld commented
I should mark the new `getType` methods as experimental as well, and remove the deprecations on `getTypes` (they've been introduced in https://github.com/symfony/symfony/pull/53160). Also, the README has to be updated

2024-04-30 13:06 UTC, xabbuh commented
@mtarld see #54789

2024-04-30 14:34 UTC, nicolas-grekas approved these changes
let's add "as experimental" to the changelog of the component also

2024-04-30 20:41 UTC, dunglas approved these changes

2024-05-01 13:04 UTC, chalasr requested changes
Changelog update needed

2024-05-02 08:26 UTC, fabpot approved these changes

2024-05-02 08:29 UTC, fabpot commented
Thank you @soyuka.

2024-05-02 08:29 UTC, merged

2024-05-02 08:31 UTC, fabpot commented
I've added a note in CHANGELOG and README.