[Security][SecurityBundle] OIDC discovery
symfony/symfony pull request #54932
Opened 2024-05-15 10:00 UTC by vincentchalamon

This PR introduces [OIDC discovery](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfigurationResponse) on `oidc` and `oidc_user_info` token handlers.

| Q             | A
| ------------- | ---
| Branch?       | 7.2
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | yes
| Issues        | Fix #50433 Fix #50434
| License       | MIT
| Doc PR | https://github.com/symfony/symfony-docs/pull/20579 |

### TODO

- [x] use JWSLoader in OidcTokenHandler
- [x] introduce OidcUserInfoDiscoveryTokenHandler
- [x] introduce OidcDiscoveryTokenHandler
- [x] update src/**/CHANGELOG.md files
- [x] update UPGRADE-*.md files
- [x] add tests on AccessTokenFactoryTest with discovery
- [x] create documentation PR

### What is OIDC Discovery?

[OIDC discovery](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfigurationResponse) is a generic endpoint on the OIDC server, which gives any public information such as signature public keys and endpoints URIs (userinfo, token, etc.). An example is available on the API Platform Demo:
https://demo.api-platform.com/oidc/realms/demo/.well-known/openid-configuration.

Using the OIDC discovery simplifies the `oidc` security configuration, allowing to just configure the discovery and let Symfony store the configuration and the keyset in cache. For instance, if the _userinfo_endpoint_ or _signature keyset_ change on the OIDC server, no need to update the environment variables in the Symfony application, just clear the corresponding cache and it'll retrieve the configuration and the keyset accordingly on the next request.

In the `oidc_user_info` security configuration, it does the same logic but only about _userinfo_endpoint_ as this token handler doesn't need the _keyset_.

### How Do I Use This New Feature in Symfony?

The current `oidc` token handler configuration requires a `keyset` option which may change on the OIDC server. It is configured as following:
```yaml
# config/packages/security.yaml
security:
    firewalls:
        main:
            access_token:
                oidc:
                    claim: 'email'
                    audience: 'symfony'
                    issuers: ['https://example.com/']
                    algorithms: ['RS256']
                    keyset: '{"keys":[{"kty":"EC",...}]}'
```

> Note: those parameters should be configured with environment variables.

With the `discovery` option, Symfony will retrieve the `keyset` directly from the OIDC discovery URI and store it in a cache:
```yaml
# config/packages/security.yaml
security:
    firewalls:
        main:
            access_token:
                oidc:
                    # 'keyset' option is not necessary anymore as it's retrieved from OIDC discovery and stored in cache
                    claim: 'email'
                    audience: 'symfony'
                    issuers: ['https://example.com/']
                    algorithms: ['RS256']
                    discovery:
                        base_uri: 'https://example.com/oidc/realms/master/'
                        cache:
                            id: cache.app # require to create this cache in framework.yaml
```

> Note: some other parameters might be retrieven from the OIDC discovery, maybe 'algorithm' or 'issuers'. To discuss.

The current `oidc_user_info` token handler required a `base_uri` corresponding to the _userinfo_endpoint_ URI on the OIDC server. This URI may change if it's changed on the OIDC server. Introducing the discovery helps to configure it dynamically.

The current configuration looks like the following:
```yaml
# config/packages/security.yaml
security:
    firewalls:
        main:
            access_token:
                oidc_user_info:
                    # 'base_uri' is the userinfo_endpoint URI
                    base_uri: 'https://example.com/oidc/realms/master/protocol/openid-connect/userinfo'
                    claim: 'email'
```

With the `discovery`, it will look like this:
```yaml
# config/packages/security.yaml
security:
    firewalls:
        main:
            access_token:
                oidc_user_info:
                    # 'base_uri' can be the userinfo_endpoint for backward compatibility
                    # and can be the OIDC server url in addition of 'discovery' option
                    base_uri: 'https://example.com/oidc/realms/master/'
                    claim: 'email'
                    discovery:
                        cache:
                            id: cache.app # require to create this cache in framework.yaml
```

2024-05-15 10:17 UTC, vincentchalamon commented
@Spomky You might be interested by this PR

2024-07-10 07:20 UTC, Spomky commented
Hi @vincentchalamon,

Please note that I recently released the Web Token suite 4.0 and proposed https://github.com/symfony/symfony/pull/57694.
The migration is normally simple, but it impacts the claims/header checking classes of `iat`, `nbf`, `exp`. And may therefore have an impact on this PR (to be confirmed).

2024-07-10 07:26 UTC, vincentchalamon commented
Hi @Spomky,

Yep I just saw that and fixed the conflicts on OidcTokenHandler and services declarations.

Do you think it's a good thing to inject a JWSLoader and check the token through it, instead of creating multiple objects (checkers, managers, etc.) and checking the token with ClaimCheckerManager?

2024-07-13 07:33 UTC, Spomky commented
> Do you think it's a good thing to inject a JWSLoader and check the token through it, instead of creating multiple objects (checkers, managers, etc.) and checking the token with ClaimCheckerManager?

I am not sure. To me, the way the tokens are loaded and their content depends on the context of their use i.e. the algorithms, the keys and the verified headers/claims should not be centralized. The JWSLoader service will then only be used by one token handler and have no advantages.

2024-10-26 10:27 UTC, wgorczyca commented
Any update on this feature? I would love to use it

2024-11-04 14:02 UTC, wgorczyca commented
any update about this feature?

2024-11-04 14:32 UTC, vincentchalamon commented
> any update about this feature?

Still waiting for a review

2024-11-04 18:53 UTC, chalasr commented
It is too late for 7.2 but I'd like this PR to make it into the next development phase, so expect some review from me asap.

2025-02-26 16:29 UTC, Spomky requested changes
This PR looks great. Many thanks.
Please refer to 7.3 instead of 7.2 and it's good to me.

2025-02-26 16:29 UTC, Spomky commented on UPGRADE-7.2.md
> + * Add discovery support to `OidcTokenHandler` and `OidcUserInfoTokenHandler`
Should be in `UPGRADE-7.3.md`

2025-02-26 16:29 UTC, Spomky commented on src/Symfony/Bundle/SecurityBundle/CHANGELOG.md
> + * Add discovery support to `OidcTokenHandler` and `OidcUserInfoTokenHandler`
Please move to the 7.3 section

2025-02-26 16:29 UTC, Spomky commented on src/Symfony/Component/Security/Http/CHANGELOG.md
> + * Add discovery support to `OidcTokenHandler` and `OidcUserInfoTokenHandler`
Please move to 7.3 section

2025-02-26 17:08 UTC, Spomky approved these changes

2025-03-01 16:07 UTC, fabpot approved these changes

2025-03-01 16:08 UTC, fabpot commented
Thank you @vincentchalamon.

2025-03-01 16:08 UTC, merged