Notifier mercure
symfony/symfony pull request #54961
Opened 2024-05-17 08:36 UTC by ernie76

| Q             | A
| ------------- | ---
| Branch?       | 7.1
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| License       | MIT

Added body, icon, tag ,renotify for desktop notifications in Symfony UX
This pull-request are need changes in src/Notify/assets/dist/controller.js I have made a pull request there too.

2024-05-17 10:02 UTC, ernie76 commented
this PR connect to this PR [https://github.com/symfony/ux/pull/1853](https://github.com/symfony/ux/pull/1853)

2024-05-21 05:53 UTC, OskarStark commented on src/Symfony/Component/Notifier/Bridge/Mercure/CHANGELOG.md
> + * Added body, icon, tag ,renotify to MercureOptions.php and MercureTransport.php for Symfony UX Notify
```suggestion
 * Add body, icon, tag ,renotify to MercureOptions.php and MercureTransport.php for Symfony UX Notify
```

2024-05-21 14:36 UTC, chapterjason commented
I just noticed that `renotify` is not supported in firefox and safari; according to https://developer.mozilla.org/en-US/docs/Web/API/Notification/renotify

2024-05-21 16:41 UTC, ernie76 commented
> I just noticed that `renotify` is not supported in Firefox and Safari according to [developer.mozilla.org](https://developer.mozilla.org/en-US/docs/Web/API/Notification/renotify); and there seem to be more properties than just those 4.

you need this option in google chrome

2024-05-21 17:20 UTC, chapterjason commented
> > I just noticed that `renotify` is not supported in Firefox and Safari according to [developer.mozilla.org](https://developer.mozilla.org/en-US/docs/Web/API/Notification/renotify); and there seem to be more properties than just those 4.
> 
> you need this option in google chrome

Might be the case, couldn't find any example/issue that this is the case, but why excluding other browsers and not use just a simple array to dynamically pass the possible options?

My recommendation:
- Replace args for the options with an array
- Add type doc with all the possible options, taken from developer.mozilla.org - with a hint it might change and a reference link.
- Just pass the array (Also reduces the named arguments and multiple JSON.parse calls in ux package)

2024-05-22 05:08 UTC, ernie76 commented
@chapterjason it's a good idea
i close this PR and the PR on the ux side, and try it again.
is this ok?

2024-05-22 05:25 UTC, chapterjason commented
@ernie76 You don't need to create new ones, just modify it, that's what PRs are about, they are evolving. I really like the initial idea, as it gives more control without creating any JS.

2024-05-23 10:07 UTC, ernie76 commented
@chapterjason is this so ok now?

2024-05-23 15:30 UTC, norkunas commented on src/Symfony/Component/Notifier/Bridge/Mercure/MercureTransport.php
> +        return sprintf('mercure://%s%s', $this->hubId, null !== $this->topics ? '?'.http_build_query(['topic' => $this->topics], '', '&') : '');
Why checking for null if constructor always sets a topic in that case?

2024-05-24 07:01 UTC, norkunas commented on src/Symfony/Component/Notifier/Bridge/Mercure/MercureOptions.php
> +
why?

2024-05-24 07:11 UTC, OskarStark commented on src/Symfony/Component/Notifier/Bridge/Mercure/MercureTransport.php
> +    private HubInterface $hub;
This should be reverted, we already had promoted properties

2024-05-29 10:47 UTC, OskarStark commented on src/Symfony/Component/Notifier/Bridge/Mercure/MercureTransport.php
> +    private string $hubId;
can be removed

2024-05-29 11:26 UTC, OskarStark commented on src/Symfony/Component/Notifier/Bridge/Mercure/MercureTransport.php
> -    ) {
please keep this

2024-05-29 11:27 UTC, OskarStark commented on src/Symfony/Component/Notifier/Bridge/Mercure/Tests/MercureOptionsTest.php
> +        $options = (new MercureOptions('/topic/1', true, 'id', 'type', 1, null));
I would provide a text here, rather than `null`

2024-05-29 11:41 UTC, OskarStark commented on src/Symfony/Component/Notifier/Bridge/Mercure/MercureTransport.php
> +        $this->hubId = $hubId;
```suggestion
        ?EventDispatcherInterface $dispatcher = null,
    ) {
```

2024-05-29 11:41 UTC, OskarStark commented on src/Symfony/Component/Notifier/Bridge/Mercure/MercureTransport.php
> +            'content' => $options->getContent(),
```suggestion
            'mediaType' => 'application/json',
            'content' => $options->getContent(),
```

2024-05-29 11:42 UTC, OskarStark commented on src/Symfony/Component/Notifier/Bridge/Mercure/Tests/MercureOptionsTest.php
> +        $options = (new MercureOptions('/topic/1', true, 'id', 'type', 1, ['tag' => '1234','body' => 'TEST']));
```suggestion
        $options = (new MercureOptions('/topic/1', true, 'id', 'type', 1, ['tag' => '1234', 'body' => 'TEST']));
```

2024-05-29 11:42 UTC, OskarStark commented on src/Symfony/Component/Notifier/Bridge/Mercure/Tests/MercureOptionsTest.php
> +            'content' => ['tag' => '1234','body' => 'TEST']
```suggestion
            'content' => ['tag' => '1234', 'body' => 'TEST']
```

2024-05-29 11:43 UTC, OskarStark commented on src/Symfony/Component/Notifier/Bridge/Mercure/CHANGELOG.md
> + * Add content to MercureOptions.php for Symfony UX Notify
Please add a new 7.2 section and add only
```
 * Add `content` option
```

2024-05-29 11:58 UTC, chapterjason requested changes

2024-05-29 11:58 UTC, chapterjason commented on src/Symfony/Component/Notifier/Bridge/Mercure/MercureTransport.php
> +            'content' => $options->getContent(),
To make it fit correctly it should be serialized to json here. (Only the values of the content entry)

For now I think it is enough to just inject the Serializer and always encode to json. To keep this PR simple.

2024-05-29 12:02 UTC, chapterjason commented
Hey @ernie76 a bit busy the last days, only one thing, everything else looks good. 👍🏼

2024-06-25 14:30 UTC, nicolas-grekas reviewed
What's the status of this PR?
It looks like the description is a bit out of sync? Can you give it some live please?

2024-06-25 14:30 UTC, nicolas-grekas commented on src/Symfony/Component/Notifier/Bridge/Mercure/CHANGELOG.md
> + * Add `content` option
missing blank line before

2024-06-26 06:15 UTC, ernie76 commented
> What's the status of this PR? It looks like the description is a bit out of sync? Can you give it some live please?

in MercuryOptions you can now 
pass an array with the proterties [https://developer.mozilla.org/en-US/docs/Web/API/Notification?retiredLocale=de#instance_properties](https://developer.mozilla.org/en-US/docs/Web/API/Notification?retiredLocale=de#instance_properties)

            new MercureOptions(['https://example.com/books/1'], content: ['tag' => $randonnumber,'body' => 'TEST', 'icon' =>  'https://media.flaticon.com/dist/min/img/logos/flaticon-color-negative.svg'])

2024-06-26 06:16 UTC, ernie76 commented
what shall i do?

2024-07-09 04:53 UTC, ernie76 commented
What must i do, to make this to a end?

2025-02-28 12:56 UTC, OskarStark commented on src/Symfony/Component/Notifier/Bridge/Mercure/CHANGELOG.md
> +7.2
```suggestion
7.3
```

2025-03-29 07:49 UTC, fabpot commented on src/Symfony/Component/Notifier/Bridge/Mercure/MercureTransport.php
> +            'content' => $options->getContent(),
@ernie76 What about this comment?

2025-04-01 09:12 UTC, OskarStark commented
@ernie76 can you please update the PR header?

2025-04-02 07:06 UTC, OskarStark approved these changes

2025-04-02 07:09 UTC, OskarStark commented
Needs a rebase

2025-04-02 07:10 UTC, fabpot requested changes

2025-04-02 07:10 UTC, fabpot commented on src/Symfony/Component/Notifier/Bridge/Mercure/Tests/MercureTransportTest.php
> +            $this->assertSame('{"@context":"https:\/\/www.w3.org\/ns\/activitystreams","type":"Announce","summary":"subject","mediaType":"application\/json","content":null}', $update->getData());
I think we should add a test where content is not `null` as this is the goal off this PR.

2025-04-03 10:07 UTC, ernie76 commented
i can't make a rebase.
can i make a new pullrequest?
i have all changes done.

2025-04-04 06:58 UTC, fabpot commented
> i can't make a rebase. can i make a new pullrequest? i have all changes done.

Sure, just close this one, create a new one, and reference this one.

2025-04-04 09:07 UTC, ernie76 commented
new PullRequest under
[https://github.com/symfony/symfony/pull/60140](https://github.com/symfony/symfony/pull/60140)

2025-04-04 09:07 UTC, closed without merging