[String] Fix Inflector for 'hardware'
symfony/symfony pull request #57234
Opened 2024-05-30 09:24 UTC by podhy

| Q             | A
| ------------- | ---
| Branch?       | 7.1
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | -
| License       | MIT

Hello,
this PR fixes problem when inflecting `hardware` word into `hardwares`. This word should not be inflected.

Please make someone review because I'm not 100% sure if this is the right way how to fix it.

Thank you.

Btw: older versions are also affected and it should be possible to merge it there

2024-05-30 19:13 UTC, fabpot commented
Can you rebase to get rid of the merge commit and maybe rebase on 5.4?

2024-06-01 11:08 UTC, OskarStark approved these changes

2024-06-02 15:46 UTC, fabpot requested changes
-

2024-06-02 18:37 UTC, OskarStark approved these changes

2024-06-03 06:05 UTC, fabpot approved these changes
I've rebased on moved the PR to 5.4.

2024-06-03 06:06 UTC, fabpot commented
Thank you @podhy.

2024-06-03 06:06 UTC, merged

2024-06-03 12:17 UTC, podhy commented
@fabpot sorry for missing rebase. Had holiday. Thank you for merge.