[Validator] fix IBAN validator fails if IBAN contains non-breaking space
symfony/symfony pull request #57380
Opened 2024-06-12 13:06 UTC by antten

| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #57364
| License       | MIT

Hello,
It's my first contribution to Symfony and I am really happy to be able to participate in the project.

After analyzing the class \Symfony\Component\Validator\Constraints\IbanValidator, I think the solution proposed in the issue is the right one.

2024-06-15 08:05 UTC, fabpot requested changes

2024-06-15 08:05 UTC, fabpot commented on src/Symfony/Component/Validator/Constraints/IbanValidator.php
> -     */
I suppose that this comes from fabbot. This should be reverted as not related to this PR.

2024-06-15 08:05 UTC, fabpot commented on src/Symfony/Component/Validator/Constraints/IbanValidator.php
> +        $canonicalized = str_replace([' ', '\XC2\XA0'], '', strtoupper($value));
```suggestion
        // Remove spaces (regular, non-breaking, and narrow non-breaking) and convert to uppercase
        $canonicalized = str_replace([' ', "\xc2\xa0", "\xe2\x80\xaf"], '', strtoupper($value));
```

2024-06-15 08:43 UTC, antten commented on src/Symfony/Component/Validator/Constraints/IbanValidator.php
> +        $canonicalized = str_replace([' ', '\XC2\XA0'], '', strtoupper($value));
Thanks for the suggestion.

2024-06-16 20:33 UTC, xabbuh approved these changes
LGTM, I am just not sure if this qualifies as a bugfix at all

2024-06-17 05:50 UTC, fabpot approved these changes

2024-06-17 05:51 UTC, fabpot commented
Thank you @antten.

2024-06-17 05:51 UTC, merged

2024-06-17 19:29 UTC, xabbuh commented
changelog entry added in 62fcf934ae201622f618fa08358823aa5c828ec3

2025-06-04 19:38 UTC, nicodemuz commented
@fabpot should the documentation be updated to warn that the validator allows for various types of whitespaces? Now there is a situation in my project where IBAN numbers stored in the database have non-breaking spaces, etc. This is causing issues when integrating further with other APIs.

Maybe worth to mention in the documentation that the validator accepts various types of human readable IBAN formats.

2025-06-04 20:04 UTC, OskarStark commented
PR welcome 👍

2025-06-04 20:31 UTC, nicodemuz commented
> PR welcome 👍

@OskarStark See https://github.com/symfony/symfony-docs/pull/21049