add a message on password_hasher configuration
symfony/symfony pull request #57511
Opened 2024-06-24 13:07 UTC by lacpandore

| Q             | A
| ------------- | ---
| Branch?       | 7.2
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no 
| Issues        | Fix
| License       | MIT

I spent a little while looking for an error, and a message like this would have saved me a lot of time.
Could be useful for others!

2024-06-24 14:34 UTC, nicolas-grekas commented on src/Symfony/Component/PasswordHasher/Hasher/PasswordHasherFactory.php
> +                if(!class_exists($class)) {
```suggestion
                if (!class_exists($class) && !interface_exists($class, false)) {
```

2024-06-24 14:34 UTC, nicolas-grekas commented on src/Symfony/Component/PasswordHasher/Hasher/PasswordHasherFactory.php
> +                    throw new \RuntimeException(sprintf('Invalid class on parameters given to security.password_hashers "%s".', $class));
```suggestion
                    throw new LogicException(sprintf('Invalid password hashers\' configuration: class or interface "%s" not found.', $class));
```

2024-06-25 08:06 UTC, nicolas-grekas approved these changes

2024-06-25 08:26 UTC, derrabus requested changes
I'm not sure we should do this. Triggering the autoloader on each class seems unnecessary. Furthermore, configuring a mapping that never matches has been a valid thing to do until now.

I could for instance add an interface here that a dependency of mine will introduce in a new major because I want to prepare my app for that. After your change, that would not be possible anymore.

Also, if we accept the change despite my objections: there's no test and testing this would've been really easy.

2024-06-25 08:42 UTC, nicolas-grekas commented
Considering @derrabus' comment, we could do the checks in the codepath that already throws when no hashers has been found.

2024-06-25 08:49 UTC, derrabus commented
> Considering @derrabus' comment, we could do the checks in the codepath that already throws when no hashers has been found.

Yes, but that won't help if my app has a fallback rule, e.g.

```YAML
App\InvalidInterface: some_hasher
Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: another_hasher
```

2024-06-28 07:36 UTC, nicolas-grekas commented
>Yes, but that won't help if my app has a fallback rule, e.g.

True, but what can we do about it?
Let's at least improve things a bit, if we cannot 100%

2024-06-28 09:04 UTC, derrabus commented
> True, but what can we do about it?

Nothing. 🤷🏻‍♂️ 

> Let's at least improve things a bit, if we cannot 100%

Sure.

2025-03-29 07:46 UTC, fabpot commented
Closing as there is no more activity and one core team member expressed some concerns.

2025-03-29 07:46 UTC, closed without merging