[Console] Add finished indicator to ProgressIndicator
symfony/symfony pull request #57576
Opened 2024-06-28 09:54 UTC by LauLaman

| Q             | A
| ------------- | ---
| Branch?       | 7.2 
| Bug fix?      | no
| New feature?  | yes 
| Deprecations? | no 
| Issues        |  
| License       | MIT

Add a (configurable) finished indicator to the progress indicator to show that the progress is finished instead of last used indicator value.
This will make the output a bit nicer

instead of
```
 - Process A (4 secs, 8.0 MiB)
 \ Process B (1 min, 39 secs, 18.0 MiB)
 - Process C (7 secs, 18.0 MiB)
 - Process D (48 secs, 20.0 MiB)
 / Process E (45 secs, 20.0 MiB)

```
 
The output will look now like this:
```
 ✔ Process A (4 secs, 8.0 MiB)
 ✔ Process B (1 min, 39 secs, 18.0 MiB)
 ✔ Process C (7 secs, 18.0 MiB)
 ✔ Process D (48 secs, 20.0 MiB)
 ✔ Process E (45 secs, 20.0 MiB)
```

2024-07-04 14:15 UTC, GromNaN reviewed
Looks good. Thanks!

2024-07-04 14:15 UTC, GromNaN commented on src/Symfony/Component/Console/CHANGELOG.md
> +* Add a configurable finished indicator to the progress indicator to show that the progress is finished
You can add the version title.

```suggestion
7.2
---

 * Add a configurable finished indicator to the progress indicator to show that the progress is finished
```

2024-07-04 14:15 UTC, GromNaN commented on src/Symfony/Component/Console/Helper/ProgressIndicator.php
> +    public function finish(string $message, ?string $finishedIndicator = null): void
The [Symfony BC promise](https://symfony.com/doc/current/contributing/code/bc.html#changing-classes) does not allow adding a new argument to a public method. This needs to be added virtually:

```php
    /**
     * Finish the indicator with message.
     *
     * @param ?string $finishedIndicator
     */
    public function finish(string $message/*, ?string $finishedIndicator = null*/): void
    {
        $finishedIndicator = func_num_args() > 1 ? func_get_arg(1) : null;
        if ($finishedIndicator !== null && !is_string($finishedIndicator)) {
            throw new \TypeError(sprintf('Argument 2 passed to %s() must be of the type string or null, %s given.', __METHOD__, get_debug_type($finishedIndicator)));
        }

```

The argument is then hard-coded in the next major version (8.0).

2024-07-04 14:15 UTC, GromNaN commented on src/Symfony/Component/Console/Helper/ProgressIndicator.php
> +        $finishedIndicatorValue ??= '✔';
Just asking: does this character work on all terminals?

2024-07-12 10:11 UTC, alexandre-daubois commented on src/Symfony/Component/Console/CHANGELOG.md
> +* Add a configurable finished indicator to the progress indicator to show that the progress is finished
Don't forget the extra blank space at the start of the line :+1:

2024-07-12 10:14 UTC, alexandre-daubois commented on src/Symfony/Component/Console/Tests/Helper/ProgressIndicatorTest.php
> +
```suggestion
```

(Same in the test case below)

2024-07-12 10:14 UTC, alexandre-daubois commented on src/Symfony/Component/Console/Tests/Helper/ProgressIndicatorTest.php
> +        $this->assertEquals(
Could you use `assertSame` maybe? `assertEquals` tends to be replaced by it where possible in the codebase. Same in the test case below.

2024-09-06 06:46 UTC, fabpot commented
@LauLaman Do you have time to have a look at the feedback?

2024-09-09 09:44 UTC, LauLaman commented
@fabpot Yes will look at this the coming week/weekend

2024-10-01 12:53 UTC, LauLaman commented on src/Symfony/Component/Console/Helper/ProgressIndicator.php
> +        $finishedIndicatorValue ??= '✔';
Not sure how to test this which terminals to target, asked [ChatGPT][link] and i think we're fine


> Conclusion
> The ✔ character works on most modern terminals and systems that support Unicode and have appropriate fonts. If  you are targeting older systems or terminals, it's worth testing to ensure compatibility.

[link]: https://chatgpt.com/share/66fbf04b-8ef8-800d-9ef0-8a0a0842605c

2024-10-01 13:05 UTC, LauLaman commented
@fabpot Sorry it took a bit longer.. shoud be good now

2024-10-01 18:29 UTC, GromNaN requested changes
Almost ready.

2024-10-01 18:29 UTC, GromNaN commented on src/Symfony/Component/Console/Helper/ProgressIndicator.php
> +    public function finish(string $message/* , ?string $finishedIndicator = null */): void
This parameter need to be documented with `@param`

2024-10-01 18:29 UTC, GromNaN commented on src/Symfony/Component/Console/Tests/Helper/ProgressIndicatorTest.php
> +        usleep(101000);
Why do you need this `usleep`? It's better if w e can remove it as it slows down the test suite.

2024-10-01 19:03 UTC, alexandre-daubois reviewed
Looks good to me once @GromNaN comments are addressed!

2024-10-01 19:03 UTC, alexandre-daubois commented on src/Symfony/Component/Console/Helper/ProgressIndicator.php
> +        $finishedIndicator = \func_num_args() > 1 ? func_get_arg(1) : null;
The condition should use yoda style, like other occurrences of this kind

2024-10-02 11:34 UTC, LauLaman commented
@GromNaN Thanks! Done!

2024-10-02 12:49 UTC, GromNaN approved these changes

2024-10-02 12:51 UTC, alexandre-daubois approved these changes

2024-10-06 09:06 UTC, fabpot approved these changes

2024-10-06 09:06 UTC, fabpot commented
Thank you @LauLaman.

2024-10-06 09:07 UTC, merged