[Validator] Add German translation for `WordCount` constraint
symfony/symfony pull request #57720
Opened 2024-07-13 08:07 UTC by OskarStark

| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Issues        | 
| License       | MIT

2024-07-15 06:35 UTC, xabbuh approved these changes

2024-07-15 08:09 UTC, xabbuh requested changes
#57716 got some changes regarding pluralisation: https://github.com/symfony/symfony/pull/57716#issuecomment-2227842252

2024-07-15 09:16 UTC, alexandre-daubois commented
Thanks for this PR!

2024-07-17 12:35 UTC, OskarStark commented on src/Symfony/Component/Validator/Resources/translations/validators.de.xlf
> +            </trans-unit>
```suggestion
            <trans-unit id="114">
                <source>This value is too short. It should contain at least one word.|This value is too short. It should contain at least {{ min }} words.</source>
                <target>Dieser Wert ist zu kurz. Er muss mindestens ein Wort lang sein.|Dieser Wert ist zu kurz. Er muss mindestens {{ min }} Wörter lang sein.</target>
            </trans-unit>
            <trans-unit id="115">
                <source>This value is too long. It should contain one word.|This value is too long. It should contain {{ max }} words or less.</source>
                <target>Dieser Wert ist zu lang. Er darf maximal ein Wort lang sein.|Dieser Wert ist zu lang. Er darf maximal {{ max }} Wörter lang sein.</target>
            </trans-unit>
```

2024-07-17 12:35 UTC, OskarStark commented
Updated

@xabbuh I don't like the "lang sein." translation, WDYT?

2024-07-17 12:49 UTC, xabbuh commented on src/Symfony/Component/Validator/Resources/translations/validators.de.xlf
> +                <target>Dieser Wert ist zu kurz. Er muss mindestens ein Wort lang sein.|Dieser Wert ist zu kurz. Er muss mindestens {{ min }} Wörter lang sein.</target>
```suggestion
                <target>Dieser Wert ist zu kurz. Er muss aus mindestens einem Wort bestehen.|Dieser Wert ist zu kurz. Er muss mindestens {{ min }} Wörter enthalten.</target>
```

2024-07-17 12:49 UTC, xabbuh commented
I have suggested something for the "min message". If you agree with it, the other message can probably be adapted accordingly.

2024-07-17 12:53 UTC, OskarStark commented on src/Symfony/Component/Validator/Resources/translations/validators.de.xlf
> +                <target>Dieser Wert ist zu lang. Er darf maximal ein Wort lang sein.|Dieser Wert ist zu lang. Er darf maximal {{ max }} Wörter lang sein.</target>
```suggestion
                <target>Dieser Wert ist zu lang. Er darf maximal aus einem Wort bestehen.|Dieser Wert ist zu lang. Er darf maximal {{ max }} Wörter enthalten.</target>
```

2024-07-17 15:00 UTC, xabbuh approved these changes

2024-07-17 15:00 UTC, xabbuh commented
👍 but we should probably merge #57752 first

2024-07-17 20:19 UTC, fabpot approved these changes

2024-07-17 20:21 UTC, fabpot commented
Thank you @OskarStark.

2024-07-17 20:21 UTC, merged