Strange behavior for OidcTokenHandler
symfony/symfony pull request #57796
Opened 2024-07-22 09:31 UTC by thibaut22200

| Q             | A
| ------------- | ---
| Branch?       | 7.1 for bug fixes
| Bug fix?      | yes
| License       | MIT

Test failed on my Ubuntu, and on my Windows is OK. Differences between order in construct of Jose/Component/Checker/...

2024-07-22 09:39 UTC, xabbuh commented
Maybe we should backport #57694. In tests we don't use version 4 of web-token/jwt-library, but since we don't have a conflict rule for it consumers of symfony/security-http can use it and run into the issue this PR is going to fix.

2024-07-23 08:04 UTC, nicolas-grekas commented
Better back port than conflict to me also.

2024-07-24 13:19 UTC, thibaut22200 commented
Backport commit done @xabbuh @nicolas-grekas

2024-07-24 13:55 UTC, nicolas-grekas approved these changes

2024-07-24 14:42 UTC, xabbuh requested changes
looks like changes from #57767 slipped into this PR

2024-07-24 16:19 UTC, derrabus commented
Duplicate of #57694?

2024-07-25 08:53 UTC, thibaut22200 commented
Oops, fixed @xabbuh

2024-07-25 09:00 UTC, xabbuh approved these changes

2024-07-26 07:24 UTC, fabpot approved these changes

2024-07-26 07:24 UTC, fabpot commented
Thank you @thibaut22200.

2024-07-26 07:24 UTC, merged