Finetune AboutCommand
symfony/symfony pull request #57829
Opened 2024-07-25 10:33 UTC by JoppeDC

| Q             | A
| ------------- | ---
| Branch?       | 7.2 
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| License       | MIT

- Make the AboutCommand show more details about the XDebug extension (Installed vs Enabled).
- Show the same info about the OPcache and APCu extensions

2024-07-25 10:38 UTC, javiereguiluz approved these changes
Good idea Joppe!

Just displaying `true`/`false` is not clear enough to distinct between installed or not and enabled or not. Thanks!

2024-07-25 10:52 UTC, ro0NL commented on src/Symfony/Bundle/FrameworkBundle/Command/AboutCommand.php
> +            ['Xdebug', extension_loaded('xdebug') ? (ini_get('XDEBUG_MODE') ? 'Enabled (mode: ' . ini_get('XDEBUG_MODE') . ')' : 'Not enabled') : 'Not installed'],
`$mode = getenv('XDEBUG_MODE') ?: ini_get('xdebug.mode')`

2024-07-25 10:55 UTC, ro0NL reviewed
webprofiler deserves a similar patch https://github.com/symfony/symfony/blob/a980a462f5eb1593d45f375d87b4bf06d6682666/src/Symfony/Component/HttpKernel/DataCollector/ConfigDataCollector.php#L57-L59

2024-07-25 11:23 UTC, OskarStark commented on src/Symfony/Bundle/FrameworkBundle/Command/AboutCommand.php
> +
```suggestion
```

2024-07-26 11:39 UTC, xabbuh approved these changes

2024-07-26 12:04 UTC, ro0NL requested changes
the same is in webprofiler, it should be in sync

2024-07-28 08:20 UTC, OskarStark approved these changes

2024-07-28 08:21 UTC, OskarStark commented
> the same is in webprofiler, it should be in sync

After this comment 👍

2024-08-02 19:13 UTC, OskarStark commented
@JoppeDC open for finishing this PR? Thanks

2024-08-02 19:25 UTC, JoppeDC commented
> @JoppeDC open for finishing this PR? Thanks

Absolutely. I'll have a look at the profiler changes

2024-08-13 16:02 UTC, nicolas-grekas reviewed
Status: needs work

2024-08-13 16:02 UTC, nicolas-grekas commented on src/Symfony/Bundle/FrameworkBundle/Command/AboutCommand.php
> +            ['OPcache', extension_loaded('Zend OPcache') ? (filter_var(ini_get('opcache.enable'), FILTER_VALIDATE_BOOLEAN) ? 'Enabled' : 'Not enabled') : 'Not installed'],
please keep the `\` in place

2024-08-13 16:02 UTC, nicolas-grekas commented on src/Symfony/Bundle/FrameworkBundle/Command/AboutCommand.php
> +        $xdebugMode = getenv('XDEBUG_MODE') ?: ini_get('xdebug.mode');
```suggestion
        $xdebugMode = getenv('XDEBUG_MODE') ?: \ini_get('xdebug.mode');
```

2024-08-13 16:02 UTC, nicolas-grekas commented on src/Symfony/Bundle/FrameworkBundle/Command/AboutCommand.php
> +            ['Xdebug', extension_loaded('xdebug') ? ($xdebugMode && $xdebugMode !== 'off' ? 'Enabled (' . $xdebugMode . ')' : 'Not enabled') : 'Not installed'],
```suggestion
            ['Xdebug', extension_loaded('xdebug') ? ($xdebugMode && $xdebugMode !== 'off' ? 'Enabled ('.$xdebugMode.')' : 'Not enabled') : 'Not installed'],
```

2024-10-03 14:39 UTC, javiereguiluz commented
@JoppeDC if you have some time, we need some last effort from you to fix some minor issues here. Then, we'll merge this in time for Symfony 7.2 release. Thanks!

2024-10-03 15:26 UTC, JoppeDC commented
@javiereguiluz I've quickly fixed the feedback issues that were still open.
I have not had the time (and also i totally forgot) to check out the implementation in the Profiler tho

2024-10-07 08:52 UTC, GromNaN approved these changes
LGTM

2024-10-07 09:26 UTC, fabpot approved these changes
Small CS fixes needed.

2024-10-07 09:26 UTC, fabpot commented on src/Symfony/Bundle/WebProfilerBundle/Resources/views/Collector/config.html.twig
> +                <span class="value value-is-icon {{ not collector.haszendopcache ? 'value-shows-no-color' }}" title="{{ collector.zendopcachestatus | default('') }}">{{ source('@WebProfiler/Icon/' ~
```suggestion
                <span class="value value-is-icon {{ not collector.haszendopcache ? 'value-shows-no-color' }}" title="{{ collector.zendopcachestatus|default('') }}">{{ source('@WebProfiler/Icon/' ~ (collector.haszendopcache ? 'yes' : 'no') ~ '.svg') }}</span>
```

2024-10-07 09:26 UTC, fabpot commented on src/Symfony/Bundle/WebProfilerBundle/Resources/views/Collector/config.html.twig
> +                <span class="value value-is-icon {{ not collector.hasapcu ? 'value-shows-no-color' }}" title="{{ collector.apcustatus | default('') }}">{{ source('@WebProfiler/Icon/' ~ (collector.has
```suggestion
                <span class="value value-is-icon {{ not collector.hasapcu ? 'value-shows-no-color' }}" title="{{ collector.apcustatus|default('') }}">{{ source('@WebProfiler/Icon/' ~ (collector.hasapcu ? 'yes' : 'no') ~ '.svg') }}</span>
```

2024-10-07 09:26 UTC, fabpot commented on src/Symfony/Bundle/WebProfilerBundle/Resources/views/Collector/config.html.twig
> +                <span class="value value-is-icon {{ not collector.hasxdebug ? 'value-shows-no-color' }}" title="{{ collector.xdebugstatus | default('') }}">{{ source('@WebProfiler/Icon/' ~ (collector
```suggestion
                <span class="value value-is-icon {{ not collector.hasxdebug ? 'value-shows-no-color' }}" title="{{ collector.xdebugstatus|default('') }}">{{ source('@WebProfiler/Icon/' ~ (collector.hasxdebug ? 'yes' : 'no') ~ '.svg') }}</span>
```

2024-10-07 09:33 UTC, fabpot commented
Thank you @JoppeDC.

2024-10-07 09:33 UTC, merged