:bug: Gracefully handle invalid dates
symfony/symfony pull request #57968
Opened 2024-08-09 17:11 UTC by homersimpsons

| Q             | A
| ------------- | ---
| Branch?       | 7.2 for features / 5.4, 6.4, and 7.1 for bug fixes 
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Issues        | None 
| License       | MIT

(found in https://github.com/symfony-tools/docs-builder/pull/179)

When parsing the following yaml:
```
date: 6418-75-51
```

`symfony/yaml` will throw an exception:
```
$ php main.php
PHP Fatal error:  Uncaught Exception: Failed to parse time string (6418-75-51) at position 6 (5): Unexpected character in /tmp/symfony-yaml/vendor/symfony/yaml/Inline.php:714
Stack trace:
#0 /tmp/symfony-yaml/vendor/symfony/yaml/Inline.php(714): DateTimeImmutable->__construct()
#1 /tmp/symfony-yaml/vendor/symfony/yaml/Inline.php(312): Symfony\Component\Yaml\Inline::evaluateScalar()
#2 /tmp/symfony-yaml/vendor/symfony/yaml/Inline.php(80): Symfony\Component\Yaml\Inline::parseScalar()
#3 /tmp/symfony-yaml/vendor/symfony/yaml/Parser.php(790): Symfony\Component\Yaml\Inline::parse()
#4 /tmp/symfony-yaml/vendor/symfony/yaml/Parser.php(341): Symfony\Component\Yaml\Parser->parseValue()
#5 /tmp/symfony-yaml/vendor/symfony/yaml/Parser.php(86): Symfony\Component\Yaml\Parser->doParse()
#6 /tmp/symfony-yaml/vendor/symfony/yaml/Yaml.php(77): Symfony\Component\Yaml\Parser->parse()
#7 /tmp/symfony-yaml/main.php(8): Symfony\Component\Yaml\Yaml::parse()
#8 {main}
  thrown in /tmp/symfony-yaml/vendor/symfony/yaml/Inline.php on line 714
```

This is because the "month" is invalid. Fixing the "month" will trigger about the same issue because the "day" would be invalid.

With the current change it will gracefully handle the value as a string:
```
$ php main.php
/tmp/symfony-yaml/main.php:8:
array(1) {
  'date' =>
  string(10) "6418-75-51"
}
```

I do not know where are the tests.

2024-08-09 19:36 UTC, stof reviewed
This needs some tests to prevent regressions

2024-08-09 20:09 UTC, derrabus commented
What does the YAML spec say about invalid date strings? Is the fallback to a plain string the expected behavior?

2024-08-09 21:51 UTC, homersimpsons commented
> This needs some tests to prevent regressions

I added a test. I do not know how far should I go with the "invalid dates"

> What does the YAML spec say about invalid date strings? Is the fallback to a plain string the expected behavior? 

I cannot seem to find anything searching https://yaml.org/spec/1.2.2/ for "date", "invalid", "incorrect". It does not look like there is a reference implementation, so I do not know what I should refer to.

2024-08-11 11:31 UTC, xabbuh requested changes
https://yaml-online-parser.appspot.com/?yaml=date%3A+2024-50-50&type=python yields an error for invalid date and I think we should do the same (i.e. throw a `ParsException`).

2024-08-11 13:48 UTC, homersimpsons commented
> https://yaml-online-parser.appspot.com/?yaml=date%3A+2024-50-50&type=python yields an error for invalid date and I think we should do the same (i.e. throw a `ParsException`).

I changed the code to an exception.

Which branch should I target? 5.4? 6.4? 7.1?

2024-08-11 15:40 UTC, derrabus commented
5.4

2024-08-11 16:56 UTC, homersimpsons commented
> 5.4

Done, There was a conflict on `src/Symfony/Component/Yaml/Inline.php`: `\DateTime` becomes `\DateTimeImmutable` in later versions

2024-08-11 17:02 UTC, derrabus commented
Can you please adjust the PR title and description? They don't match the implemented logic anymore.

2024-08-11 17:42 UTC, homersimpsons commented
> Can you please adjust the PR title and description? They don't match the implemented logic anymore.

Done. Tests are failing on twig but I didn't change anything there.

2024-08-11 20:50 UTC, derrabus approved these changes

2024-08-12 07:08 UTC, chalasr approved these changes

2024-08-12 07:47 UTC, xabbuh approved these changes

2024-08-12 07:48 UTC, xabbuh commented
Thank you @homersimpsons.

2024-08-12 07:48 UTC, merged