Future compatibility with function autoloading
symfony/symfony pull request #58030
Opened 2024-08-17 21:28 UTC by withinboredom

While working on an RFC (https://wiki.php.net/rfc/function_autoloading4) for function autoloading, I discovered that Symfony registers an autoloader that accepts two arguments. But an autoloader should never accept a second argument for the current implementation, and the implementation may change.

| Q             | A
| ------------- | ---
| Branch?       | 7.2 for features / 5.4, 6.4, and 7.1 for bug fixes 
| Bug fix?      | yes?
| New feature?  | no
| Deprecations? | no
| Issues        | https://github.com/php/php-src/pull/15471
| License       | MIT

2024-08-17 22:15 UTC, stof commented on src/Symfony/Component/Config/Resource/ClassExistenceResource.php
> +            $thrower = fn(string $name) => (__CLASS__.'::throwOnRequiredClass')($name);
```suggestion
            $thrower = fn(string $name) => self::throwOnRequiredClass($name);
```

2024-08-19 07:39 UTC, fabpot reviewed
Is it something we want to do in 5.4 instead?

2024-08-19 07:51 UTC, nicolas-grekas requested changes
This likely breaks stack trace inspection later in the method. I'd suggest waiting for the linked RFC to be accepted before merging. The current usage is fine for the moment.

2024-08-19 07:51 UTC, nicolas-grekas commented on src/Symfony/Component/Config/Resource/ClassExistenceResource.php
> +            $thrower = fn(string $name) => self::throwOnRequiredClass($name);
```suggestion
            $thrower = static fn ($class) => self::throwOnRequiredClass($class);
```

2024-08-21 15:54 UTC, nicolas-grekas commented
Let me close for now.

2024-08-21 15:54 UTC, closed without merging

2024-08-21 18:54 UTC, derrabus commented
> But an autoloader should never accept a second argument for the current implementation, and the implementation may change.

Given that we can currently be certain that PHP won't pass a second argument to the autoloader, I don't see a problem to register a method as autoloader that takes an optional second argument.

The change proposed in the RFC breaks backwards compatibility. That should be taken into consideration when discussing and refining the RFC.