[SecurityBundle] Disallow using legacy hash algorithms for password hashing when migrating passwords
symfony/symfony pull request #58119
Opened 2024-08-29 10:21 UTC by alexandre-daubois

| Q             | A
| ------------- | ---
| Branch?       | 7.2
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Issues        | -
| License       | MIT

After https://github.com/symfony/symfony/issues/58053#issuecomment-2307907528 (cc @chalasr). Two concerns about this PR:
- I'm not sure this is a bug fix or a feature. Stof stated that "using a MessageDigestPasswordHasher as the best hasher of a MigratingPasswordHasher won't work as expected." in the issue, so maybe it could be a bugfix after all.
- What do you think of this approach? Should we forbid more algorithms?

2024-08-29 10:42 UTC, OskarStark commented on src/Symfony/Bundle/SecurityBundle/Tests/DependencyInjection/SecurityExtensionTest.php
> +    public function testMigrateToLegacyHasherThrows()
Could we add a data provider and name the forbidden ones? Can be done after decision on this PR

2024-08-30 15:28 UTC, nicolas-grekas requested changes
Thanks for the PR but this implementation doesn't look correct to me.
We don't know anything about custom hasher so how can we forbid anything when they're used?
And then, how does this prevent using a legacy hasher as a target (non-custom one)?
I'd expect some logic in PasswordHasherFactory instead.
Let me know if I'm wrong of course.

2024-08-30 15:28 UTC, nicolas-grekas commented on src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php
> +    private const LEGACY_HASHES_REGEX = '/^(md\d+|sha[12]\d{0,2}|sha512|plaintext)$/';
I'd rather list the allowed target algos - pbkdf2 needs to be excluded also

2024-08-30 18:14 UTC, chalasr commented
> We don't know anything about custom hasher so how can we forbid anything when they're used?
And then, how does this prevent using a legacy hasher as a target (non-custom one)?

Correct. We only know that all built-in hashers that don't implement `needsRehash()` cannot be targeted for opportunistic password upgrades, since the method is used to control whether the migration should happen or not.
It's the case for all `LegayPasswordHasherInterface` implementations currently. But a custom implementation extending e.g `MessageDigestPasswordHasher::needsRehash()` can indeed make it work. So we can only talk for built-in legacy hashers.

I think we either need to detect all custom hashers from the check by checking if the value of `algorithm` matches the `id` of a defined hasher and exclude them from the check (let them go), or we add an API for password hashers to expose whether they can be the target of a migration or not.

2024-08-30 18:16 UTC, chalasr commented
> I'd expect some logic in PasswordHasherFactory instead.

Definitely. And some (functional ideally) tests consequently.

2024-09-11 10:23 UTC, closed without merging

2024-09-11 10:27 UTC, alexandre-daubois commented
Thanks for closing this, forgot a bit about it while thinking of a better solution. I may come up with something that's more in line with your comments.

In the meantime, if someone wants to take over it because the problem is a blocker for them, please do 🙂