[Dotenv] Fix can not load BOM-signed env files
symfony/symfony pull request #58216
Opened 2024-09-09 20:29 UTC by hosni

| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #58214 
| License       | MIT

In this PR, I fixed the load env file BOM characters.
You can see the full explanation of the issue: https://github.com/symfony/symfony/issues/58214
More about BOM: [Byte Order Mark](https://en.wikipedia.org/wiki/Byte_order_mark)

2024-09-09 20:36 UTC, hosni commented
Unit tests failed, but that's not my fault!
My unit tests working perfectly.

2024-09-10 05:32 UTC, derrabus requested changes

2024-09-10 05:32 UTC, derrabus commented on CHANGELOG-6.4.md
> + * bug #58214 [Dotenv] Fix can not load BOM-signed env files (hosni)
Please revert. This file is generated.

2024-09-10 06:50 UTC, nicolas-grekas requested changes
dotenv files are modeled after sourced shell scripts.
I just tested and neither sh nor bash support parsing dotenv files that start with a BOM.
This means we should not do it.

Instead, we might consider throwing an exception when one is found.
I'd suggest doing it in the doLoad method.

Also, let's use str_starts_with to check for it.

2024-09-11 07:03 UTC, closed without merging

2024-09-11 07:03 UTC, nicolas-grekas commented
Please submit a new PR if you want to provide the exception I suggested.

2024-09-16 07:22 UTC, xabbuh commented
see #58274 for the exception