allow narrow type of not nullable getResponse when hasResponse has be…
symfony/symfony pull request #58241
Opened 2024-09-12 09:08 UTC by shyim

…en called

| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes/
| New feature?  | no
| Deprecations? | no
| Issues        | 
| License       | MIT

```php
if ($event->hasResponse()) {
    return $event->getResponse();
}
```

PHPStan understands now inside the if that Response is not nullable anymore

2024-09-12 16:48 UTC, xabbuh approved these changes
but for 7.2 as this is not a bugfix

2024-09-12 21:19 UTC, derrabus approved these changes
for 7.2

2024-09-13 04:04 UTC, OskarStark approved these changes

2024-09-13 12:07 UTC, wouterj commented
As far as I know, we do not accept static analysis annotations that are not generally supported across Psalm, PHPStan and PhpStorm (see also the [list of accepted annotations in the Symfony standards](https://symfony.com/doc/current/contributing/code/standards.html#documentation)).

It seems like `assert-if-true` is [not supported by Psalm](https://psalm.dev/r/d376298655). So I'm :-1: , although the added annotation is correct (it might be worth submitting this as a stub to the PHPStan Symfony plugin).

2024-09-13 12:51 UTC, stof commented
Psalm does support the `assert-if-true` annotation. However, by default, Psalm does not memoize the type for getters, which is why it has no effect in your code snippet. See https://psalm.dev/docs/running_psalm/configuration/#memoizemethodcallresults for the configuration and https://psalm.dev/r/561c4c3a87 for the same code snippet with this setting turned on.

phpstan has a different default than psalm regarding this option.

2024-09-13 13:11 UTC, wouterj commented
Ah, of course. Thank for correcting me, @stof.

Let's do it then :+1: , but with the `@psalm-` prefix to be consistent with the other annotations in the Symfony code base (although the prefix doesn't change anything in behavior).

2024-09-13 13:20 UTC, stof commented
The only change in behavior is for the case where you write something wrong in the tag: both phpstan and psalm are reporting errors when writing an invalid tag with their own prefix while they silently discard an invalid tag using the prefix of the other tool (because maybe this tag is actually valid in the other tool and they don't have feature parity)

2024-09-13 13:22 UTC, stof commented
For reference, see https://psalm.dev/docs/annotating_code/adding_assertions/#asserting-return-values-of-methods for the Psalm documentation about the exact conditions for `@psalm-assert-if-true ... $this->someGetter()` to work. There are cases that work without `memoizeMethodCallResults` but this class does not correspond to those cases.

2024-09-13 13:25 UTC, stof requested changes

2024-09-13 13:25 UTC, stof commented on src/Symfony/Component/HttpKernel/Event/RequestEvent.php
> +     * @phpstan-assert-if-true !null $this->getResponse()
```suggestion
     * @psalm-assert-if-true !null $this->getResponse()
```

2024-10-09 15:03 UTC, nicolas-grekas commented
Thank you @shyim.

2024-10-09 15:03 UTC, merged