Add ScalarNormalizer to allow custom values for boolean
symfony/symfony pull request #58473
Opened 2024-10-06 19:42 UTC by Hanmac

| Q             | A
| ------------- | ---
| Branch?       | 7.2 for features / 5.4, 6.4, and 7.1 for bug fixes 
| Bug fix?      | yes/no
| New feature?  | yes 
| Deprecations? | no 
| Issues        | Fix #58305 , Fix #58056 
| License       | MIT

i want to fix #58429 with this MR too, but that might need some thinking first

It still does work when the Normalizer is used with Serializer (like it normally would?),
but currently it crashes some Testcases I probably need to fix first. (that's why this is still a draft)

Even without the new ScalarNormalizer, it should still return return the expected result

2024-10-06 19:46 UTC, Hanmac commented
"Allow edits from maintainer" doesn't work because that is a Group Repository

2024-10-09 07:40 UTC, andreybotanic commented
Your fix is very specific. Why ScalarNormalizer allows only booleans? You probably should create BooleanNormalizer instead. And it also mast supports denormalization, so you have to add appropriate methods and fix demormalization method in AbstractObjectNormalizer

2024-10-09 07:47 UTC, Hanmac commented
@andreybotanic because this is only the start, for #58429 I wanted to add something to format numeric/float/int too,
but I first need to think what the best way would be. Probably "sprintf" Format Strings?

Yeah, denormalization might need to be done too. My use-case was for normalizing into stuff that can be denormalized too. (like "true/false" for boolean.)

I will try to update the denormalize way soon. (for example, "yes/no" for boolean)

2025-01-29 08:12 UTC, Hanmac commented
@nicolas-grekas similar to #59501 can you look into this MR?

I need to find a way to normalize boolean into "true" and "false" instead of "1" and "0"

2025-10-02 11:31 UTC, stof requested changes

2025-10-02 11:31 UTC, stof commented on src/Symfony/Component/Serializer/Normalizer/ScalarNormalizer.php
> +class ScalarNormalizer implements NormalizerInterface
Custom values for booleans does not require a ScalarNormalizer but a BooleanNormalizer triggered only for the boolean type.

And this is a new feature that **cannot** be added in 6.4. Thus, I would probably vote against adding it in core even in 7.4 (you can register a custom normalizer if you need this).

2025-10-02 11:31 UTC, stof commented on src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php
> -            if (null === $attributeValue || \is_scalar($attributeValue)) {
this must not be removed entirely but moved inside the `if (!$this->serializer instanceof NormalizerInterface) {` condition, to keep support for scalars in that case.

2025-10-02 11:31 UTC, stof commented on src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php
> -            if (null === $attributeValue || \is_scalar($attributeValue)) {
And please add a test covering this behavior of the object normalizer to prevent future regressions.

2025-10-02 11:46 UTC, Hanmac commented on src/Symfony/Component/Serializer/Normalizer/ScalarNormalizer.php
> +class ScalarNormalizer implements NormalizerInterface
if you noticed the date of this MR, it was a year ago before 6.4
so of course it needs to be rebased

2025-10-02 13:00 UTC, Hanmac commented
hm, I need to think about the test cases.

For example: `testChildContextKeepsOriginalContextCacheKey`
thanks to the change, it creates a new child-context for the scalar attributes

2025-10-02 14:13 UTC, Hanmac commented on src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php
> -            if (null === $attributeValue || \is_scalar($attributeValue)) {
Fixed the existing Tests so far

I added a Test-Case for when Serializer isn't set

now i will add Test-Case for if a custom scalar Normalizer is defined

2025-10-06 09:07 UTC, Hanmac commented
@stof is this MR ready? The Fabbot changes look like false-positive

2025-10-17 08:29 UTC, Hanmac commented
Ping @stof again, because I have done the "Requested change"

2025-10-17 08:55 UTC, Hanmac commented
@stof rebased and fixed the Fabbot thing

just Redis is failing sometimes

2025-10-17 12:36 UTC, xabbuh commented on src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php
> +        $this->markTestSkipped('Scalar attributes change context. See https://github.com/symfony/symfony/pull/58473');
Having a test that is always skipped does not make sense. Let’s rewrite it in a meaningful way instead.

2025-10-17 12:46 UTC, Hanmac commented on src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php
> +        $this->markTestSkipped('Scalar attributes change context. See https://github.com/symfony/symfony/pull/58473');
What is your suggestion?

Change it to `testChildContextChangesContextCacheKey` or something like that?

2025-10-17 13:11 UTC, Hanmac commented
Finally, the tests are green again 😂

2025-10-30 06:05 UTC, Hanmac commented
for reference, @stof said this in Slack:

> looking at a git blame, I suspect that this was working between 2.7 (when serializer added support for normalizing scalars) and 6.1, and got broken in 6.2 (when the handling of scalars was changed in AbstractObjectNormalizer to fix an issue in https://github.com/symfony/symfony/pull/49525)

2025-11-01 13:39 UTC, nicolas-grekas commented on src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php
> -     * @return mixed
let's keep these, they're false-positives from fabbot (same below)

2025-11-01 13:39 UTC, nicolas-grekas commented on src/Symfony/Component/Serializer/Tests/Normalizer/ObjectNormalizerTest.php
> +            ->willReturnCallback(fn ($data) => $data === $object ? 'string_object' : $data)
```suggestion
            ->willReturnCallback(static fn ($data) => $data === $object ? 'string_object' : $data)
```

2025-11-01 13:40 UTC, nicolas-grekas approved these changes

2025-11-01 14:04 UTC, nicolas-grekas commented on src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php
> +    /*
```suggestion
    /**
```

2025-11-01 14:35 UTC, xabbuh requested changes

2025-11-01 14:35 UTC, xabbuh commented on src/Symfony/Component/Serializer/Tests/Normalizer/GetSetMethodNormalizerTest.php
> +    public function testNormalizeWithoutSerializer()
This test would still pass if we reverted the patch.

2025-11-01 14:53 UTC, Hanmac commented on src/Symfony/Component/Serializer/Tests/Normalizer/GetSetMethodNormalizerTest.php
> +    public function testNormalizeWithoutSerializer()
What would be a better way too test?

2025-11-03 10:14 UTC, xabbuh commented on src/Symfony/Component/Serializer/Tests/Normalizer/GetSetMethodNormalizerTest.php
> +    public function testNormalizeWithoutSerializer()
I sent a PR to your fork reworking the tests a bit.

2025-11-03 10:43 UTC, xabbuh approved these changes

2025-11-12 13:46 UTC, nicolas-grekas commented
Thank you @Hanmac.

2025-11-12 13:47 UTC, closed without merging

2025-11-12 13:47 UTC, nicolas-grekas commented
Merged as c5a661a