[HtmlSanitizer] Fix force_attributes not replacing existing attribute in initial data
symfony/symfony pull request #58547
Opened 2024-10-12 08:38 UTC by tgalopin

| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix https://github.com/symfony/symfony/issues/58065
| License       | MIT

Fix the override of an existing attribute value.

2024-10-22 15:24 UTC, chalasr approved these changes

2024-10-22 15:25 UTC, chalasr requested changes
Adding an optional argument is for 7.x

2024-10-23 07:44 UTC, tgalopin commented
Indeed thanks for the catch!

If that's good for you I'll handle it using func_get_args to fix the issue on 6.4 (it's a real bug, I think it's worth it)

2024-10-23 12:22 UTC, stof commented
Node is a final class, so it can add the argument directly (as there is no issue regarding keeping BC for child classes overriding the method)

2024-11-06 11:01 UTC, AppyGG commented
Hi, to help on this issue, is there something to change to allow merge for 6.4 ?

2025-02-13 10:52 UTC, AppyGG commented
Hello, small up on this PR, i really think this needs to be fix to improve sanitized content security

I'm uncertain if the `Node.php` class needs modification or if the changes proposed by @tgalopin are good regarding the BC policy ?

2025-02-13 11:06 UTC, stof approved these changes

2025-08-12 10:22 UTC, nicolas-grekas commented
Thank you @tgalopin.

2025-08-12 10:22 UTC, merged