[Validator] Add `Slug` constraint
symfony/symfony pull request #58542
Opened 2024-10-11 12:29 UTC by raffaelecarelle

| Q             | A
| ------------- | ---
| Branch?       | 7.2
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Issues        | 
| License       | MIT

Introduce Slug constraint class for validating strings as slugs. 
Add unit tests to verify correct behavior for valid and invalid slugs.

2024-11-20 14:42 UTC, stof commented on src/Symfony/Component/Validator/CHANGELOG.md
> + * Add the `Slug` constraint
Adding this to the 7.2 changelog does not make sense. You are submitting this to 7.3

2024-11-20 14:52 UTC, raffaelecarelle commented on src/Symfony/Component/Validator/CHANGELOG.md
> + * Add the `Slug` constraint
Sorry, this PR war created on 7.2 and then moved to 7.3.

2025-01-05 14:51 UTC, fabpot requested changes

2025-01-05 14:51 UTC, fabpot commented on src/Symfony/Component/Validator/Constraints/Slug.php
> +    public const SLUG_PATTERN = '/^[a-z0-9]+(?:-[a-z0-9]+)*$/';
This regex sounds reasonnable to me as the default, but let users override it if needed.

2025-01-05 15:20 UTC, derrabus commented on src/Symfony/Component/Validator/Constraints/Slug.php
> +    public const SLUG_PATTERN = '/^[a-z0-9]+(?:-[a-z0-9]+)*$/';
If someone wanted to override the expression, they might as well just use the `Regex` constraint, don't they?

2025-01-05 15:25 UTC, fabpot commented on src/Symfony/Component/Validator/Constraints/Slug.php
> +    public const SLUG_PATTERN = '/^[a-z0-9]+(?:-[a-z0-9]+)*$/';
Sure, but using a `Slug` constraint for that means you can use the default error message and the intent is more clear.

2025-01-05 15:43 UTC, raffaelecarelle commented on src/Symfony/Component/Validator/Constraints/Slug.php
> +    public const SLUG_PATTERN = '/^[a-z0-9]+(?:-[a-z0-9]+)*$/';
ok @fabpot @derrabus, thanks for your feedback. It's fine to me let user change regex.

I did the changes. let me know.

2025-01-05 16:05 UTC, fabpot reviewed
Can you add a test with a custom regex?

2025-01-05 16:19 UTC, raffaelecarelle commented
> Can you add a test with a custom regex?

Done

2025-01-05 16:33 UTC, fabpot approved these changes

2025-01-06 09:20 UTC, fabpot commented
Thank you @raffaelecarelle.

2025-01-06 09:20 UTC, merged

2025-04-29 07:32 UTC, Kocal commented
Hey, are we fine with `(new AsciiSlugger())->slug('My article title')` failing to be asserted by this new `Slug` assertion, since the generated slug is `My-article-title`, with an uppercase character?

2025-04-29 11:01 UTC, stof commented on src/Symfony/Component/Validator/Constraints/Slug.php
> +    public string $message = 'This value is not a valid slug.';
This message needs to be added in translation files (so that the translators from the community can provide translations for it in core, like other default messages of constraints)

2025-04-29 11:56 UTC, xabbuh commented on src/Symfony/Component/Validator/Constraints/Slug.php
> +    public string $message = 'This value is not a valid slug.';
this has already been done in #59383

2025-05-15 08:43 UTC, xabbuh commented
@Kocal see #60426