[Messenger][Console] Add `$seconds` to `keepalive()` methods
symfony/symfony pull request #58552
Opened 2024-10-13 12:33 UTC by valtzu

| Q             | A
| ------------- | ---
| Branch?       | 7.2
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| License       | MIT

Make the transport aware for how long (at minimum) the message should be kept alive.

F.e. when extending SQS visibility timeout, you need to pass the visibility timeout (seconds) as parameter. If you pass a value which is less than alarm interval, SQS would resend the message too early. By making the transport aware of when the next keepalive call will happen we'll be able to do some assertions/clamping to improve DX.

This is a prerequisite for #58483.

2024-10-13 18:51 UTC, fabpot approved these changes

2024-10-13 19:04 UTC, chalasr requested changes
The component changelog needs to mention the new method

2024-10-13 19:12 UTC, OskarStark commented on src/Symfony/Component/Messenger/Transport/Receiver/KeepaliveReceiverInterface.php
> +    public function keepalive(Envelope $envelope, ?int $seconds = null): void;
Isn't this a BC break?

2024-10-13 19:13 UTC, OskarStark commented on src/Symfony/Component/Messenger/Worker.php
> +    public function keepalive(?int $seconds): void
As this is a public method (API) and it has no default value, this is a BC break, isn't it?

2024-10-13 19:13 UTC, chalasr commented on src/Symfony/Component/Messenger/Transport/Receiver/KeepaliveReceiverInterface.php
> +    public function keepalive(Envelope $envelope, ?int $seconds = null): void;
That method has not been released yet

2024-10-13 19:44 UTC, valtzu commented
> The component changelog needs to mention the new method

As this whole feature is not released yet, I thought the changes here would be covered by the initial changelog entries about adding keepalive / alarm support since from component user perspective it's a single new feature – but ok, I will add those. :+1:

2024-10-14 06:11 UTC, fabpot approved these changes

2024-10-14 06:12 UTC, fabpot commented
Thank you @valtzu.

2024-10-14 06:12 UTC, merged