feature [LoginLink] Added route params in LoginLinkHandler
symfony/symfony pull request #58629
Opened 2024-10-22 13:30 UTC by Pascal229

| Q             | A
| ------------- | ---
| Branch?       | 7.2 for features
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Issues        | no
| License       | MIT

## Add Support for Route Parameters in LoginLinkHandler
This pull request enhances the `LoginLinkHandler` to support passing route parameters when generating login links. This is achieved by adding a new option, `route_params`, which allows specifying additional parameters to be included in the generated URL.

**Changes:**
- Added `'route_params' => []` to the default options in the constructor.
- Merged `route_params` with the existing parameters in the `createLoginLink` method.

This feature is important for use cases where additional route parameters are required for generating login links.

2024-10-22 14:10 UTC, OskarStark commented
Can you please add a testcase?

2024-10-22 15:54 UTC, ro0NL commented on src/Symfony/Component/Security/Http/LoginLink/LoginLinkHandler.php
> +        $parameters = array_merge($parameters, $this->options['route_params']);
id consider `$parameters + ..`

2024-10-22 15:54 UTC, ro0NL commented on src/Symfony/Component/Security/Http/LoginLink/LoginLinkHandler.php
> +        $parameters = array_merge($parameters, $this->options['route_params']);
or vice versa the array_merge args

2024-10-23 10:03 UTC, Pascal229 commented on src/Symfony/Component/Security/Http/LoginLink/LoginLinkHandler.php
> +        $parameters = array_merge($parameters, $this->options['route_params']);
I fixed it with the union operator

2024-10-23 11:28 UTC, Pascal229 commented
> Can you please add a testcase?

An unit test?

2025-03-26 08:48 UTC, fabpot requested changes

2025-03-26 08:48 UTC, fabpot commented on src/Symfony/Component/Security/Http/CHANGELOG.md
> + * Added route_params in `LoginLinkHandler` constructor options param
Should be moved to a new 7.3 section

2025-03-26 08:48 UTC, fabpot commented on src/Symfony/Component/Security/Http/LoginLink/LoginLinkHandler.php
> +        $parameters = $parameters + $this->options['route_params'];
Could be merged with the previous lines:

```php
$parameters = [
    'user' => $user->getUserIdentifier(),
    'expires' => $expires,
    'hash' => $this->signatureHasher->computeSignatureHash($user, $expires),
] + $this->options['route_params'];
```

2026-01-23 12:53 UTC, Spomky commented
Hi @Pascal229,

What is the status of this PR?
It looks like the remaining modifications are minor, but there has been no activity for a few months now.
This change is interesting and would be a nice addition to the project.
Would you mind addressing the comments so we can merge it?

2026-08-07 10:33 UTC, nicolas-grekas commented
Thanks for this. fabpot asked for a couple of changes back in March 2025 and Spomky pinged in January 2026, but the PR has not moved since. On top of the review nits, 'route_params' is only added to the handler's options array and SecurityBundle's LoginLinkFactory never passes it, so the option would not be settable from security.yaml as-is. #64271 is also tackling extra login-link parameters in a way that includes them in the signature. Closing for now; feel free to reopen or open a fresh PR if you want to pick it up again.

2026-08-07 10:33 UTC, closed without merging