[formatTime] Considering minutes and returning a time converted to de…
symfony/symfony pull request #58694
Opened 2024-10-28 13:47 UTC by espoirbaraka

…cimal

| Q             | A
| ------------- | ---
| Branch?       | 7.2 for features / 5.4, 6.4, and 7.1 for bug fixes 
| Bug fix?      | yes/no
| New feature?  | yes/no 
| Deprecations? | yes/no 
| Issues        | Fix #... 
| License       | MIT

2024-10-28 13:56 UTC, espoirbaraka commented
This pull request is related to this issue : [issue](https://github.com/symfony/symfony/issues/58692)

2024-10-28 13:57 UTC, GromNaN commented
Hello, thank you for contributing.

Could you add test cases to [`HelperTest`](https://github.com/symfony/symfony/blob/7.2/src/Symfony/Component/Console/Tests/Helper/HelperTest.php#L20) in order to show the bug you are fixing and ensure there is no regression in the future.

2024-10-28 20:17 UTC, espoirbaraka commented
> Could you add test cases

I have already done this. I added 3 cases to show how it works

2024-10-29 11:16 UTC, GromNaN requested changes
I'm closing because it looks like you're trying to implement a feature that already exists: choose precision. The implementation is not in the logic of the existing code.

2024-10-29 11:16 UTC, GromNaN commented on src/Symfony/Component/Console/Tests/Helper/HelperTest.php
> +            [5199,   '1 hr, 26 mins, 39 secs', 1.4],
The 3rd parameter must be an `int` representing the `$precision`, i.e. the number of units to be displayed).

2024-10-29 11:16 UTC, GromNaN commented on src/Symfony/Component/Console/Helper/Helper.php
> +        if (3600 === $format[0]) {
The change must not be specific to a given time format.

2024-10-29 11:16 UTC, closed without merging