[VarDumper] Add dq() function for SQL query debugging
symfony/symfony pull request #58775
Opened 2024-11-05 22:57 UTC by Jewhurst

This adds a new debugging helper function that formats and dumps SQL queries with their bindings for easier debugging.

| Q             | A
| ------------- | ---
| Branch?       | 7.2 for features / 5.4, 6.4, and 7.1 for bug fixes 
| Bug fix?      | yes/no
| New feature?  | yes/no 
| Deprecations? | yes/no 
| Issues        | Fix #... 
| License       | MIT

2024-11-06 06:23 UTC, derrabus requested changes
Tests are missing.

2024-11-06 06:23 UTC, derrabus commented on src/Symfony/Component/VarDumper/CHANGELOG.md
> +7.2.1
```suggestion
7.3
```

2024-11-06 06:23 UTC, derrabus commented on src/Symfony/Component/VarDumper/Resources/functions/dump.php
> +        if (!method_exists($query, 'toSql') || !method_exists($query, 'getBindings')) {
Can we avoid the duck typing here? What object exactly are you expecting?

2024-11-06 07:40 UTC, lyrixx commented
I would use a caster here with a virtual property

2024-11-10 14:04 UTC, dsentker commented
I don't know if we need a separate function for such a simple task. You can also get an executable query in the Symfony Profiler.

2024-11-10 16:54 UTC, derrabus commented
Indeed, the `dump()` function should be good enough for the task. And if we're not happy with its output, a dedicated caster would do the trick.

Let's close this PR.

2024-11-10 16:54 UTC, closed without merging