Dynamically fix compatibility with doctrine/data-fixtures v2
symfony/symfony pull request #58865
Opened 2024-11-13 20:02 UTC by greg0ire

| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Issues        | see explanation below
| License       | MIT

While working on [allowing v2 of doctrine/data-fixtures in the bundle](https://github.com/doctrine/DoctrineFixturesBundle/pull/457), I stumbled upon an issue that only affects some versions of Symfony that still have a `ContainerAwareLoader` class.

The signature of `ContainerAwareLoader::addFixture()` is not compatible with the v2 signature of the `Loader` interface from `doctrine/data-fixtures`, as per this fatal error:

```
Declaration of Symfony\Bridge\Doctrine\DataFixtures\ContainerAwareLoader::addFixture(Doctrine\Common\DataFixtures\FixtureInterface $fixture)
             must be compatible with Doctrine\Common\DataFixtures\Loader::addFixture(Doctrine\Common\DataFixtures\FixtureInterface $fixture): void
```

Classes that extend ContainerAwareLoader have to also extend Loader, meaning this is no breaking change because it can be argued that the incompatibility of the extending class would be with the Loader interface.

2024-11-13 20:14 UTC, greg0ire commented
How should I deal with the Psalm failures?

2024-11-13 20:24 UTC, derrabus commented
> How should I deal with the Psalm failures?

Ignore them.

2024-11-13 20:25 UTC, derrabus approved these changes

2024-11-13 20:28 UTC, greg0ire commented
> Ignore them.

I'll assume you mean that literally because I couldn't find a baseline or `psalm-suppress` annotations to ignore them programmatically :laughing:

2024-11-13 21:59 UTC, derrabus commented
> > Ignore them.
> 
> I'll assume you mean that literally

Yes. 😎

2024-11-13 23:00 UTC, chalasr requested changes

2024-11-13 23:00 UTC, chalasr commented on src/Symfony/Bridge/Doctrine/DataFixtures/AddFixtureImplementation.php
> +     * @phpstan-require-extends ContainerAwareLoader
Symfony doesn’t use vendor-specific type annotations

2024-11-14 12:15 UTC, greg0ire commented on src/Symfony/Bridge/Doctrine/DataFixtures/AddFixtureImplementation.php
> +     * @phpstan-require-extends ContainerAwareLoader
@chalasr thanks, addressed!

2024-11-15 13:16 UTC, chalasr approved these changes

2024-11-15 13:17 UTC, chalasr commented
Not sure if the failing test is related?

2024-11-15 13:37 UTC, greg0ire commented
The Windows test? It's about http-foundation :thinking: 
Also, it fails on other PRs.

If you're talking about Psalm, the failure is definitely related, but I was told above to ignore it.

2024-11-15 14:01 UTC, chalasr commented
Sorry, I mean this one on the high-deps build: https://github.com/symfony/symfony/actions/runs/11836984636/job/32983037386?pr=58865. 
That test seems to pass on current 5.4, can you please have a look?

2024-11-15 14:43 UTC, greg0ire commented
Oh right, that one does look like it could be related. I'll take a look.

2024-11-15 15:20 UTC, greg0ire commented
@MatTheCat maybe you can help with this?

2024-11-15 15:53 UTC, greg0ire commented
Just noticed the DI tag present in the line I mentioned is missing on 5.4 and was introduced in https://github.com/symfony/symfony/commit/6a4d229b9fcacbe2df4b8f563ad39b91212d936b , hence my last commit, which sadly doesn't seem very successful.

2024-11-15 15:58 UTC, greg0ire commented
Ah this might be what I need to backport: #57489

2024-11-15 16:03 UTC, MatTheCat commented
Err I don’t think I can help :sweat_smile: ; I recently committed to the DoctrineBridge but it doesn’t look like it was related.

2024-11-15 16:05 UTC, greg0ire commented
Yes, sorry!

2024-11-15 17:26 UTC, greg0ire commented
This only happens in `high-deps` mode, which apparently checks out 4.4, that's quite peculiar. At this point I don't really understand what's going on. @xabbuh maybe you would?

2024-11-16 08:42 UTC, xabbuh approved these changes

2024-11-16 08:44 UTC, xabbuh commented
@greg0ire you can ignore the high deps failures

2024-11-16 14:04 UTC, chalasr approved these changes

2024-11-20 10:49 UTC, nicolas-grekas commented
Thank you @greg0ire.

2024-11-20 10:50 UTC, merged