[Serializer] Handle default context in Serializer
symfony/symfony pull request #58889
Opened 2024-11-15 15:18 UTC by Valmonzo

| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  |  no
| Deprecations? | no
| Issues        | Fix #58628
| License       | MIT

This fixes the default context not taken into account by the Serializer class.

2024-11-26 10:12 UTC, chalasr approved these changes, later dismissed

2025-01-06 09:45 UTC, mtarld requested changes

2025-01-06 09:45 UTC, mtarld commented on src/Symfony/Bundle/FrameworkBundle/Resources/config/serializer.php
> +            ->args([[], [], []])
You can revert that change

2025-01-06 09:45 UTC, mtarld commented on src/Symfony/Component/Serializer/DependencyInjection/SerializerPass.php
> +            $container->getDefinition('serializer')->replaceArgument(2, $defaultContext);
```suggestion
            $container->getDefinition('serializer')->setArgument(2, $defaultContext);
```

2025-01-10 18:07 UTC, Valmonzo commented on src/Symfony/Bundle/FrameworkBundle/Resources/config/serializer.php
> +            ->args([[], [], []])
```suggestion
            ->args([[], []])
```

2025-01-10 18:23 UTC, mtarld commented on src/Symfony/Component/Serializer/Tests/DependencyInjection/SerializerPassTest.php
> +        $container->register('serializer')->setArguments([null, null, null]);
```suggestion
        $container->register('serializer')->setArguments([null, null]);
```
 To stick with the initial service definition

2025-01-10 18:24 UTC, Valmonzo commented on src/Symfony/Component/Serializer/Tests/DependencyInjection/SerializerPassTest.php
> +        $container->register('serializer')->setArguments([null, null, null]);
I just saw that, thanks 👍🏽

2025-01-10 18:31 UTC, mtarld approved these changes

2025-01-13 17:35 UTC, chalasr commented on src/Symfony/Component/Serializer/Serializer.php
> +        private array $defaultContext = [],
Adding a new optional parameter to the constructor is expanding the public API. This can only happen as part of a new minor version as per semver. This should target 7.3 I think, even though it means not fixing this bug on lower branches.

2025-01-13 17:42 UTC, chalasr commented on src/Symfony/Component/Serializer/Serializer.php
> +        private array $defaultContext = [],
And then we need an entry in the Serializer's CHANGELOG

2025-01-14 08:22 UTC, mtarld commented on src/Symfony/Component/Serializer/Serializer.php
> +        private array $defaultContext = [],
And then you can update back the changes on `serializer.php` so that the service definition handles the default context.

2025-01-15 02:47 UTC, Valmonzo commented
Thanks @chalasr and @mtarld for your help 👍🏽

2025-01-15 02:48 UTC, chalasr approved these changes

2025-01-15 07:39 UTC, mtarld commented on src/Symfony/Component/Serializer/DependencyInjection/SerializerPass.php
> +            $container->getDefinition('serializer')->setArgument(2, $defaultContext);
I would have set
```suggestion
            $container->getDefinition('serializer')->replaceArgument(2, $defaultContext);
```
 And updated the definition in `serializer.php`

2025-01-16 23:14 UTC, dunglas requested changes
LGTM! I just left some minor CS-related comments.

2025-01-16 23:14 UTC, dunglas commented on src/Symfony/Component/Serializer/Serializer.php
> -
Unrelated CS change to be reverted.

2025-01-16 23:14 UTC, dunglas commented on src/Symfony/Component/Serializer/Tests/DependencyInjection/SerializerPassTest.php
> -        $container->register('serializer')->setArguments([null, null]);
These changes shouldn't be necessary.

2025-01-17 08:01 UTC, mtarld commented on src/Symfony/Component/Serializer/Tests/DependencyInjection/SerializerPassTest.php
> -        $container->register('serializer')->setArguments([null, null]);
Because of `replaceArgument`, I think that having 3 arguments is necessary here.

2025-01-17 08:14 UTC, mtarld approved these changes

2025-01-17 08:14 UTC, mtarld commented on src/Symfony/Component/Serializer/Tests/DependencyInjection/SerializerPassTest.php
> +        $container->register('serializer')->setArguments([null, null, []]);
```suggestion
        $container->register('serializer')->setArguments([null, null, null]);
```

2025-01-17 08:14 UTC, mtarld commented on src/Symfony/Component/Serializer/Tests/DependencyInjection/SerializerPassTest.php
> +        $container->register('serializer')->setArguments([null, null, []]);
```suggestion
        $container->register('serializer')->setArguments([null, null, null]);
```

2025-01-17 08:14 UTC, mtarld commented on src/Symfony/Component/Serializer/Tests/DependencyInjection/SerializerPassTest.php
> +        $container->register('serializer')->setArguments([null, null, []]);
```suggestion
        $container->register('serializer')->setArguments([null, null, null]);
```

2025-01-17 16:25 UTC, mtarld commented
Handling that as a feature won't fix the bug for the older branches.

Maybe we can create a new PR aiming to fix the bug that:
- Add an internal setter on the `Serializer` class to set the default context
- Call that setter from the `SerializerPass`

2025-01-28 15:03 UTC, nicolas-grekas commented on src/Symfony/Component/Serializer/DependencyInjection/SerializerPass.php
> +            $container->getDefinition('serializer')->replaceArgument(2, $defaultContext);
instead of a positional argument, let's use a named one:
```suggestion
            $container->getDefinition('serializer')->setArgument('$defaultContext', $defaultContext);
```

this will make the container fail at compile-time in case the `serrializer` service is overriden. Better than a runtime error.

2025-01-28 15:47 UTC, chalasr commented
rebase+retarget on 6.4 needed also

2025-01-28 19:11 UTC, chalasr commented on src/Symfony/Component/Serializer/Tests/DependencyInjection/SerializerPassTest.php
> +        $container->register('serializer')->setArguments([null, null, []]);
as the actual argument requires an array, this is correct. What's wrong is to pass `null` to both previous arguments which expects arrays as well. We may want to fix this or not, I wouldn't care much tbh

2025-01-28 19:12 UTC, chalasr approved these changes

2025-01-28 19:44 UTC, chalasr commented
Thank you @Valmonzo.

2025-01-28 19:44 UTC, merged