Feature/console helper formattime ms
symfony/symfony pull request #58946
Opened 2024-11-20 13:37 UTC by SebLevDev

| Q             | A
| ------------- | ---
| Branch?       | 7.3
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| License       | MIT

2024-11-21 07:38 UTC, fmarchalemisys commented on src/Symfony/Component/Console/Helper/Helper.php
> +        if ($ms < 0.001) {
Shouldn't it be `$ms < 1` as `$ms` contains the number of milliseconds, i.e. 1 = 1ms.

2024-11-21 07:38 UTC, fmarchalemisys commented on src/Symfony/Component/Console/Helper/Helper.php
> +        $ms = $secs * 1000;
Rounding to int is necessary for modulo to work correctly.

As you don't use sub millisecond time, keeping the decimals is pointless.

2024-11-21 07:38 UTC, fmarchalemisys commented on src/Symfony/Component/Console/Helper/Helper.php
> +            if (abs($ms-$milliSeconds) < 0.001) {
Since `$ms` and `$milliSeconds` should be int, the comparison `===` can be used instead of fuzzy numerical comparaison.

2024-11-21 07:38 UTC, fmarchalemisys commented on src/Symfony/Component/Console/Helper/Helper.php
> +            $ms -= $milliSeconds;
This is why both variables must be int. Float may lead to numerical imprecision.

2024-11-21 07:38 UTC, fmarchalemisys commented on src/Symfony/Component/Console/Helper/Helper.php
> +            if ($milliSeconds < 0.001) {
Here too: `$milliSeconds < 1`.

2024-11-21 08:21 UTC, fmarchalemisys approved these changes

2024-11-21 22:18 UTC, 94noni commented on src/Symfony/Component/Console/Helper/Helper.php
> +            [86400000, '1 day', 'days'],
```suggestion
            [86_400_000, '1 day', 'days'],
```

perhaps?

2024-11-25 18:57 UTC, 94noni approved these changes

2024-11-27 07:31 UTC, fabpot requested changes

2024-11-27 07:31 UTC, fabpot commented on src/Symfony/Component/Console/Tests/Helper/HelperTest.php
> +            [0.95,   '950 ms', 1],
We still need a test that would output `< 1 ms`.

2024-11-27 07:31 UTC, fabpot commented on src/Symfony/Component/Console/Tests/Helper/HelperTest.php
>              [0,      '< 1 sec', 1],
When does it happen now? Shouldn't it be `< 1 ms` instead?

2024-11-27 07:32 UTC, fabpot commented
While doing this, I would change the other units to be more in line with standard scientific notation: `ms`, `s`, `min`, `h`, and `d`.

2024-11-27 10:09 UTC, SebLevDev commented
> While doing this, I would change the other units to be more in line with standard scientific notation: `ms`, `s`, `min`, `h`, and `d`.

Can this change not be considered a BC Break?

2024-11-27 10:37 UTC, fabpot commented
> > While doing this, I would change the other units to be more in line with standard scientific notation: `ms`, `s`, `min`, `h`, and `d`.
> 
> Can this change not be considered a BC Break?

Sure, this is pure display, so no BC promise.

2024-12-09 07:47 UTC, SebLevDev commented
Hello everyone,

Thank you for the feedback, especially @fabpot for the suggestion about aligning the units with standard scientific notation (ms, s, min, h, d).

I’m a bit unsure about the next steps here. Should I proceed with the proposed changes for all the units as suggested, or wait for further input from other reviewers to ensure this aligns with everyone’s expectations?

Any additional guidance or confirmation would be greatly appreciated to avoid conflicting directions.

Thanks in advance!

2024-12-09 07:51 UTC, fabpot commented
> Hello everyone,
> 
> Thank you for the feedback, especially @fabpot for the suggestion about aligning the units with standard scientific notation (ms, s, min, h, d).
> 
> I’m a bit unsure about the next steps here. Should I proceed with the proposed changes for all the units as suggested, or wait for further input from other reviewers to ensure this aligns with everyone’s expectations?
> 
> Any additional guidance or confirmation would be greatly appreciated to avoid conflicting directions.
> 
> Thanks in advance!

Please, go ahead and make the suggested changes.

2024-12-10 11:40 UTC, fabpot approved these changes

2024-12-10 11:41 UTC, fabpot commented
Thank you @SebLevDev.

2024-12-10 11:41 UTC, merged