[Serializer] Trigger deprecation when could not parse date with default format
symfony/symfony pull request #58966
Opened 2024-11-22 10:57 UTC by alexndlm

| Q             | A
| ------------- | ---
| Branch?       | 8.1
| Bug fix?      | no
| New feature?  | no
| Deprecations? | yes
| Issues        | 
| License       | MIT

Relates to https://github.com/symfony/symfony/pull/43329#discussion_r738505208

2024-11-24 14:40 UTC, alexndlm commented
@nicolas-grekas Could you have a look?

2025-01-06 09:40 UTC, mtarld requested changes
Could you update the Serializer's `CHANGELOG.md` file and the `UPGRADE-7.3.md` file as well?

2025-01-06 09:40 UTC, mtarld commented on src/Symfony/Component/Serializer/Normalizer/DateTimeNormalizer.php
> +                trigger_deprecation('symfony/serializer', '7.3', \sprintf('NotNormalizableValueException will be thrown when date could not be parsed using the default format "%s".', $defaultDateTime
```suggestion
                trigger_deprecation('symfony/serializer', '7.3', \sprintf('A "%s" will be thrown when a date could not be parsed using the default format "%s".', NotNormalizableValueException::class, $defaultDateTimeFormat));
```

2025-01-13 16:08 UTC, mtarld commented
Looks like the tests must be updated to not trigger the deprecation.

2025-01-13 16:33 UTC, stof commented on src/Symfony/Component/Serializer/Normalizer/DateTimeNormalizer.php
> +                trigger_deprecation('symfony/serializer', '7.3', \sprintf('A "%s" will be thrown when a date could not be parsed using the default format "%s".', NotNormalizableValueException::class,
I think we should trigger a deprecation here only if the fallback manages to instantiate it. The case where the fallback throws an exception (already turned into a NotNormalizableValueException below) should not trigger a deprecation.

2025-01-13 17:40 UTC, alexndlm commented on src/Symfony/Component/Serializer/Normalizer/DateTimeNormalizer.php
> +                trigger_deprecation('symfony/serializer', '7.3', \sprintf('A "%s" will be thrown when a date could not be parsed using the default format "%s".', NotNormalizableValueException::class,
As I understand, in 8.0, the fallback should be removed, right?

2025-01-13 17:41 UTC, alexndlm commented
@mtarld I have done with your comments.

2025-01-14 09:27 UTC, stof commented on src/Symfony/Component/Serializer/Normalizer/DateTimeNormalizer.php
> +                trigger_deprecation('symfony/serializer', '7.3', \sprintf('A "%s" will be thrown when a date could not be parsed using the default format "%s".', NotNormalizableValueException::class,
yes. And that's my point: if the fallback also fails, you already have the same behavior than what would happen in 8.0 and we should not trigger a deprecation in that case as the behavior will not change. Try submitting `foobar` as value to reproduce that case.

2025-01-14 10:52 UTC, alexndlm commented on src/Symfony/Component/Serializer/Normalizer/DateTimeNormalizer.php
> +                trigger_deprecation('symfony/serializer', '7.3', \sprintf('A "%s" will be thrown when a date could not be parsed using the default format "%s".', NotNormalizableValueException::class,
I have rechecked and now realise that fallback should not be removed in `8.0`. Fallback should still be used when `datetime_format` is set to `null`.

2025-06-18 08:34 UTC, stof commented on src/Symfony/Component/Serializer/Normalizer/DateTimeNormalizer.php
> +                trigger_deprecation('symfony/serializer', '7.3', \sprintf('A "%s" will be thrown when a date could not be parsed using the default format "%s".', NotNormalizableValueException::class,
My point is still not solved. You still trigger a deprecation for not normalizable values (passing `abcdefgh` as date for instance), while there is no behavior change for that case.

2025-06-18 13:05 UTC, alexndlm commented on src/Symfony/Component/Serializer/Normalizer/DateTimeNormalizer.php
> +                trigger_deprecation('symfony/serializer', '7.3', \sprintf('A "%s" will be thrown when a date could not be parsed using the default format "%s".', NotNormalizableValueException::class,
After removing `return new $type($data, $timezone);` (line `133/131`), it will throw `NotNormalizableValueException`  when we pass a valid date but the format does not match `$defaultDateTimeFormat`.

For example, if `$defaultDateTimeFormat = 'Y-m-d H:i:s'` and we pass `2025-03-10` it will work.

In Symfony 8, it should throw an exception.

As I understand, the behaviour will change.

2025-06-18 14:46 UTC, stof commented on src/Symfony/Component/Serializer/Normalizer/DateTimeNormalizer.php
> +                trigger_deprecation('symfony/serializer', '7.3', \sprintf('A "%s" will be thrown when a date could not be parsed using the default format "%s".', NotNormalizableValueException::class,
I'm not talking about the case of passing a valid date not matching the format.

Your current implementation is also triggering the deprecation when passing a totally invalid date.

2025-06-18 15:32 UTC, alexndlm commented on src/Symfony/Component/Serializer/Normalizer/DateTimeNormalizer.php
> +                trigger_deprecation('symfony/serializer', '7.3', \sprintf('A "%s" will be thrown when a date could not be parsed using the default format "%s".', NotNormalizableValueException::class,
I think I finally understood you. Look again, please.

2026-01-30 23:39 UTC, nicolas-grekas approved these changes
I rebased the PR for 8.1 and fixed an issue when the default format is set to `null`

2026-01-31 08:17 UTC, mtarld approved these changes

2026-01-31 09:21 UTC, nicolas-grekas commented
Thank you @alexndlm.

2026-01-31 09:21 UTC, merged