Remove incorrect changelog item
symfony/symfony pull request #59080
Opened 2024-12-03 09:18 UTC by bobvandevijver

| Q             | A
| ------------- | ---
| Branch?       | 7.1 
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Issues        | # 
| License       | MIT

Related to #53851, #57378 & #59079. Whether or not this an actual CVE, I believe this should be removed from the changelog anyways as it does not throw a bad request anymore.

If we do keep considering it a new feature, it should probably be changed to reflex the correct exception.

2024-12-04 09:21 UTC, xabbuh approved these changes
this was reverted in #57378

2024-12-04 09:22 UTC, xabbuh requested changes
on a second though we should probably change this to mention the `BadCredentialsException`

2024-12-04 10:34 UTC, bobvandevijver commented
@xabbuh Done!

2024-12-04 15:55 UTC, xabbuh approved these changes

2024-12-06 13:27 UTC, fabpot approved these changes

2024-12-06 13:28 UTC, fabpot commented
Thank you @bobvandevijver.

2024-12-06 13:28 UTC, merged