[Validator] Validate SVG ratio in Image validator
symfony/symfony pull request #59265
Opened 2024-12-19 14:36 UTC by maximecolin

| Q             | A
| ------------- | ---
| Branch?       | 7.3 
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Issues        | Fix #45269
| License       | MIT

Implement ratio check for SVG images. Checking SGV size is not relevant as a SVG image can be enlarged without loss, but ratio can be important to check.

Currently, the validator add a violation with `SIZE_NOT_DETECTED_ERROR` in case of SVG image.

SVG size is guessed from viewbox, width and height attributes. Viewbox will provides default size, width and height can override viewbox size if they are number. Width and height as percentage are ignored it as the final size will depend on the container.

In case of SVG, `minWidth`, `maxWidth`, `minHeight`, `maxHeight`, `minPixels` and `maxPixels` are ignored because not relevant. Only `maxRatio`, `minRatio`, `allowSquare`, `allowLandscape` and `allowPortrait` can generate violations.

2024-12-19 15:01 UTC, stof requested changes

2024-12-19 15:01 UTC, stof commented on src/Symfony/Component/Validator/Constraints/ImageValidator.php
> +     * @return bool
those phpdoc annotations don't provide any value over the native signature and so should be removed.

2024-12-19 15:01 UTC, stof commented on src/Symfony/Component/Validator/Constraints/ImageValidator.php
> +     * <b>TRUE</b> if <i>value</i> is an SVG, <b>FALSE</b> if it's not, or if we can't detect its MimeType;
We don't use HTML in our phpdoc.

2024-12-19 15:01 UTC, stof commented on src/Symfony/Component/Validator/Constraints/ImageValidator.php
> +    private function getSvgSize(mixed $value): array|false
please use `null` to represent the absence of value, not `false`

2024-12-19 15:01 UTC, stof commented on src/Symfony/Component/Validator/Constraints/ImageValidator.php
> +     * @return array|false Index 0 and 1 contains respectively the width and the height of the image. <i>FALSE</b> if size can be found.
this should describe the proper type: `@return array{int, int}|null` (assuming my other comment is taken into account)

2024-12-19 15:35 UTC, maximecolin commented
Thanks @stof, I fixed the code according to your comments.

2024-12-19 15:41 UTC, stof commented on src/Symfony/Component/Validator/Constraints/ImageValidator.php
> +     * @return array{int, int}|null Index 0 and 1 contains respectively the width and the height of the image, false if size can't be found.
```suggestion
     * @return array{int, int}|null Index 0 and 1 contains respectively the width and the height of the image, null if size can't be found.
```

2024-12-22 07:52 UTC, stof approved these changes

2024-12-22 08:33 UTC, OskarStark commented on src/Symfony/Component/Validator/CHANGELOG.md
> +* Allow `Image` constraint to check SVG ratio
```suggestion
 * Allow `Image` constraint to check SVG ratio
```

2024-12-22 08:33 UTC, OskarStark commented on src/Symfony/Component/Validator/Constraints/ImageValidator.php
> +     * Return true if value is an SVG, false if it's not, or if we can't detect its MimeType.
```suggestion
     * @return bool Return true if value is an SVG, false if it's not, or if we can't detect its MimeType.
```

2024-12-22 08:33 UTC, OskarStark commented on src/Symfony/Component/Validator/Constraints/ImageValidator.php
> +            $width = (int) $widthMatches[1];
What about using capturing groups instead of numbers?

2024-12-22 08:34 UTC, OskarStark commented on src/Symfony/Component/Validator/Tests/Constraints/ImageValidatorTest.php
> +        } else {
What about two testcases and a valid and invalid provider?

2024-12-23 08:54 UTC, maximecolin commented
Thanks @OskarStark, I applied your suggestions.

2024-12-28 12:20 UTC, xabbuh commented on src/Symfony/Component/Validator/CHANGELOG.md
> + * Allow `Image` constraint to check SVG ratio
```suggestion
 * Add support for ratio checks for SVG files to the `Image`
```

2024-12-29 12:59 UTC, fabpot approved these changes

2024-12-29 13:01 UTC, fabpot commented
Thank you @maximecolin.

2024-12-29 13:02 UTC, merged