[Validator] Allow Unique constraint validation on all elements
symfony/symfony pull request #59274
Opened 2024-12-20 21:08 UTC by Jean-Beru

| Q             | A
| ------------- | ---
| Branch?       | 7.3
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Issues        |  
| License       | MIT

Sometimes it could be useful to assert that every elements of a collection is not duplicated.  This PR adds a `multipleErrors` option to the Unique constraint to avoid stopping at the first violation. 

Its value is `false` by default to avoid BC breaks:
```php
$violations = $this->validator->validate(
    ['a1', 'a2', 'a1', 'a1', 'a2'],
    new Unique(),
);
// 1 violation on [2]
```

Now
```php
$violations = $this->validator->validate(
    ['a1', 'a2', 'a1', 'a1', 'a2'],
    new Unique(multipleErrors: true),
);
// 3 violations on [2], [3] and [4]
```

2024-12-21 15:19 UTC, GromNaN reviewed
> Sometimes it could be useful to assert that every elements of a collection is not duplicated.
Is there a situation where it's better to have only the first error?

> This PR adds a `multipleErrors` option to the Unique constraint to avoid stopping at the first violation.
I think we can avoid adding a new option and simply modify the behavior in version 7.3.

2024-12-23 09:49 UTC, Jean-Beru commented
> > Sometimes it could be useful to assert that every elements of a collection is not duplicated.
> 
> Is there a situation where it's better to have only the first error?
> 
> > This PR adds a `multipleErrors` option to the Unique constraint to avoid stopping at the first violation.
> 
> I think we can avoid adding a new option and simply modify the behavior in version 7.3.

That was my first idea but it will lead to a BC break like mentioned in #59037.

2025-01-07 10:55 UTC, nicolas-grekas commented on src/Symfony/Component/Validator/Constraints/Unique.php
> +    public bool $multipleErrors = false;
naming :) what about this? multipleErrors looks like a consequence of something, not an option
```suggestion
    public bool $quickCheck = true;
```

2025-01-17 13:29 UTC, nicolas-grekas approved these changes

2025-01-17 17:45 UTC, mtarld approved these changes

2025-01-17 18:31 UTC, GromNaN approved these changes

2025-01-18 09:32 UTC, fabpot requested changes

2025-01-18 09:32 UTC, fabpot commented on src/Symfony/Component/Validator/Constraints/Unique.php
> +    public bool $multipleErrors = false;
The current name doesn't seem right to me. It's about having all errors, not necessarily multiple ones.

Maybe `$allErrors`?

If we want to name it closer to the behavior, the current one is "stopping on first error", which is more or less similar to PHPUnit `--no-on-error` flag.

So, another suggestion might be: `$stopOnFirstError`?

2025-01-18 11:57 UTC, OskarStark commented on src/Symfony/Component/Validator/Constraints/Unique.php
> +    public bool $multipleErrors = false;
Maybe "$all" so all must be unique?

2025-02-06 09:46 UTC, Jean-Beru commented on src/Symfony/Component/Validator/Constraints/Unique.php
> +    public bool $multipleErrors = false;
Agreed with `$stopOnFirstError` :+1: 

The PR is updated in that way + `CHANGELOG.md`

2025-02-12 14:26 UTC, nicolas-grekas approved these changes

2025-02-12 14:26 UTC, nicolas-grekas commented
Thank you @Jean-Beru.

2025-02-12 14:26 UTC, merged