[TwigBridge] Deprecate passing $field argument to `is_granted()`
symfony/symfony pull request #59282
Opened 2024-12-22 13:29 UTC by smnandre

| Q             | A
| ------------- | ---
| Branch?       | 7.3
| Bug fix?      |  no
| New feature?  | no 
| Deprecations? | yes
| Issues        | Fix #... 
| License       | MIT

This PR deprecates the `$field` argument of the [`is_granted`](https://github.com/symfony/symfony/blob/78f4d9a1059725384ce563c4e1696b8e66c6983a/src/Symfony/Bridge/Twig/Extension/SecurityExtension.php#L37) Twig function, and removes it from the just-added is_user_granted function.

It seems that passing a third argument "field" is a feature made/kept for the [AclBundle](https://github.com/symfony/acl-bundle). 

The Symfony [documentation](https://symfony.com/doc/current/reference/twig_reference.html#is-granted) states:
> Optionally, an object can be passed to be used by the voter. More information can be found in Security.

But in the [linked security page](https://symfony.com/doc/current/security.html#security-template), no mention is made about it.

The last version of the [documentation about ACL](https://symfony.com/doc/3.x/security/acl_advanced.html) writes
> ACL support was deprecated in Symfony 3.4 and will be removed in 4.0. Install the Symfony ACL bundle if you want to keep using ACL.

This feature is, **afaik**, not available in the rest of the similar security tools/helpers (_IsGranted_ attribute, _is_granted_ function in expression language, ...)

Finally, passing an value here will throw an error as the FieldVote class cannot be used without installing the AclBundle (something not documented that can lead to very frustating DX).

...

I may not have all context/history here, so please don't bite :)

2024-12-22 14:38 UTC, chalasr requested changes
Although it's not deprecated, ACL is indeed mostly a thing of the past so 👍 to simplify the function and get rid of this integration in core. 

UPGRADE-7.3 should mention the deprecation too.

2024-12-22 14:38 UTC, chalasr commented on src/Symfony/Bridge/Twig/Extension/SecurityExtension.php
> +            trigger_deprecation('symfony/twig-bridge', '7.3', 'Passing the "$field" argument to the "is_granted" Twig function is deprecated and will be removed in version 8.0.');
```suggestion
            trigger_deprecation('symfony/twig-bridge', '7.3', 'The "$field" parameter of the "is_granted" Twig function is deprecated and will be removed in version 8.0.');
```
Even more correct I think

2024-12-22 14:52 UTC, smnandre commented
> UPGRADE-7.3 should mention the deprecation too.

Done!

2024-12-22 15:47 UTC, chalasr approved these changes

2025-01-02 11:59 UTC, fabpot commented
But AclBundle is still maintained, so it's going to break it, right? Or maybe I'm missing something.

2025-01-03 19:31 UTC, smnandre commented
>  But AclBundle is still maintained

I didn’t know that, to be honest. Not having new features doesn’t mean "not maintained", and I’m sorry for disregarding this aspect. I based this PR on what I read in the current Symfony documentation ("support will be removed in 4.0"). 

Since AclBundle is not compatible with Symfony 8.0 (obviously), I didn’t see a BC issue here. I’ve always considered BC from a "past" perspective (stating this **genuinely** — still learning here).

However, I don’t understand why we added compatibility in the new `is_user_granted()` Twig function. 

---

I may have been too "solution-oriented" instead of describing the problem(s) I tried to solve here.

### **Current problem**

The ACL bundle is not mentioned on any of the pages related to the "is granted" toolkit: `is_granted()` Twig function, `#[IsGranted]` attribute, `isGranted()` Security method, etc.

But...  https://symfony.com/doc/current/reference/twig_reference.html#is-granted

<img width="847" alt="Capture d’écran 2025-01-03 à 19 32 22" src="https://github.com/user-attachments/assets/35be4ea9-743c-4b4c-8c34-8f4447ea7690" />

([Twig functions reference](https://twig.symfony.com/doc/3.x/#symfony-functions) also redirects to this page)

The documentation of the `is_granted` Twig function shown here may lead users to believe they can target a specific field (deducing that the attribute can be checked on the value of the given object's field). This is not the case, and they see an exception message related to a class that isn’t installed. 

This may result in users **installing a bundle they neither _intended_ to nor _needed_ to install**.

---

If we need to maintain both present and future compatibility, I suggest the following:

### 0) Fix `is_granted_for_user()`

Either we decide to remove the third argument, or we should at least make its behavior strictly consistent. [Currently](https://github.com/symfony/symfony/blob/78f4d9a1059725384ce563c4e1696b8e66c6983a/src/Symfony/Bridge/Twig/Extension/SecurityExtension.php#L54), passing a false-ish third argument (e.g., an empty string) is handled differently and won’t trigger any alert if the _FieldVote_ class is missing, whereas the same scenario with `is_granted` [would](https://github.com/symfony/symfony/blob/78f4d9a1059725384ce563c4e1696b8e66c6983a/src/Symfony/Bridge/Twig/Extension/SecurityExtension.php#L37).

### 1) Add a custom exception

When a third argument is passed to the method (_whatever its value_):

* **If AclBundle** (and/or (?) Acl package) is installed: Use the argument as it works today.
* **Else** throw a clear, explicit message.

Additionally, in Symfony 8.0, we could consider ignoring the argument entirely when the bundle is not enabled.

### 2) Update the documentation

What about removing any mention of the third argument from the Symfony documentation? 

Conversely, I suggest adding comments in the code and perhaps one or two tests to ensure non-regression.

### Next?

I think such checks should not be performed at runtime but rather during compilation/configuration. If, for any reason, the ACLBundle wasn’t installed correctly, a simple `class_alias` on `Symfony\Component\Security\Acl\Voter\FieldVote` could provide a solution.

---

I’m, of course, ready to implement any of these changes… or none at all — feel free to drop this PR if you think it’s not worth it!

2025-01-03 19:35 UTC, chalasr commented
Could ACLBundle override these functions? I think it'd be worth it for the sake of not polluting the core API with something we took care of extracting from core.

2025-01-06 09:59 UTC, nicolas-grekas requested changes
> Could ACLBundle override these functions?

is_field_granted + is_field_granted_for_user would be nice replacements.
PR needed on AclBundle before we can consider this one IMHO.

2025-01-07 02:01 UTC, smnandre commented
>  PR needed on AclBundle before we can consider this one IMHO.

There’s no mention of Twig in general—or `is_granted` in particular—in the entire ACLBundle repository or its documentation. The same goes for the security-acl component, with the last references to Twig being in 2015 changelogs.

So, I’ll politely decline the invitation… that wasn’t even one, haha 😘 

As I said, if you think it's good as it is, let's close here :)

2025-01-07 10:06 UTC, nicolas-grekas commented
> If we need to maintain both present and future compatibility, I suggest the following: [...]

I agree with all items then. Can you please update the PR accordingly?

2025-01-07 10:34 UTC, nicolas-grekas commented
Actually, let's do the follow up in another PR to keep the discussion relevant.

2025-01-07 10:34 UTC, closed without merging